# 05 – TFA


Constraint-based analysis on genome-scale metabolic models (GEMs) is a popular method to study metabolism and cellular physiology. Flux Balance Analysis (FBA), in particular, has been used to predict network-level behaviors, such as specific growth rate, gene essentiality, etc. However, FBA-derived approaches often lead to flux distributions
that are contradicting with physiology and bioenergetics due to the
lack of thermodynamic constraints in their formulation. Metabolic reactions in GEMs can be futher constrained thermodynamically using TFA (Salvy...Meric et., al, 2019).

References

*   https://github.com/EPFL-LCSB/pytfa/tree/master
*   Bioinformatics, 35(1), 2019, 167–169
doi: 10.1093/bioinformatics/bty499

# Install dependencies

In [1]:
!pip3 install cobra pytfa catboost optlang modelseedpy

Collecting cobra
  Downloading cobra-0.30.0-py2.py3-none-any.whl.metadata (9.3 kB)
Collecting pytfa
  Downloading pytfa-0.9.4-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.4 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/bb/ac/1d6a4a72f45bfa46a95d3cc9f29c113c5f4a4ece4ac7461b56ac61c2fa2c/pytfa-0.9.4-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.3-py2.py3-none-any.whl.metadata (1.2 kB)
WARNING: Ignoring version 0.9.3 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/a3/b4/9d3a72b34043fc5e4b75afcefd2d386ebab18ca99690cfa1c4c01612c77d/pytfa-0.9.3-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.2-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.2 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/52/75/1b2114796a7f0b51ce973798805a5ccf5e929078bc65e59dc44b4f5601ea/pytfa-0.9.2-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6"); extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.1.tar.gz (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 38.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting optlang
  Downloading optlang-1.8.3-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting modelseedpy
  Downloading modelseedpy-0.4.2-py3-none-any.whl.metadata (5.7 kB)
Collecting appdirs~=1.4 (from cobra)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting depinfo~=2.2 (from cobra)
  Downloading depinfo-2.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting diskcache~=5.0 (from cobra)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from cobra) (1.0.0)
Requirement already satisfied: httpx~=0.24 in /usr/local/lib/python3.12/dist-packages (from cobra) (0.28.1)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.0.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.2.2)
Requirement already satisfied: pydantic>=1.6 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.12.3)
Collecting python-libsbml~=5.19 (from cobra)
  Downloading python_libsbml-5.21.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (666 bytes)
Requirement already satisfied: rich>=8.0 in /usr/local/lib/python3.12/dist-packages (from cobra) (13.9.4)
Collecting ruamel.yaml~=0.16 (from cobra)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting swiglpk (from cobra)
  Downloading swiglpk-5.0.13-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Collecting pytfa
  Using cached pytfa-0.9.4-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.4 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/bb/ac/1d6a4a72f45bfa46a95d3cc9f29c113c5f4a4ece4ac7461b56ac61c2fa2c/pytfa-0.9.4-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Using cached pytfa-0.9.3-py2.py3-none-any.whl.metadata (1.2 kB)
WARNING: Ignoring version 0.9.3 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/a3/b4/9d3a72b34043fc5e4b75afcefd2d386ebab18ca99690cfa1c4c01612c77d/pytfa-0.9.3-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Using cached pytfa-0.9.2-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.2 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/52/75/1b2114796a7f0b51ce973798805a5ccf5e929078bc65e59dc44b4f5601ea/pytfa-0.9.2-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6"); extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
Requirement already satisfied: bokeh>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pytfa) (3.8.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pytfa) (3.6.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (from pytfa) (8.4.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pytfa) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pytfa) (4.67.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: sympy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from optlang) (1.14.0)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from modelseedpy) (1.6.1)
Collecting chemicals>=1.0.13 (from modelseedpy)
  Downloading chemicals-1.5.1-py3-none-any.whl.metadata (15 kB)
Collecting chemw>=0.3.2 (from modelseedpy)
  Downloading ChemW-0.3.5.tar.gz (467 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.6/467.6 kB 27.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Jinja2>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from modelseedpy) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (2.17.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (26.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (2025.11.0)
Collecting fluids>=1.1.0 (from chemicals>=1.0.13->modelseedpy)
  Downloading fluids-1.3.0-py3-none-any.whl.metadata (8.9 kB)
Collecting pubchempy (from chemw>=0.3.2->modelseedpy)
  Downloading pubchempy-1.0.5-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from chemw>=0.3.2->modelseedpy) (2.32.4)
Collecting sigfig (from chemw>=0.3.2->modelseedpy)
  Downloading sigfig-1.3.19-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx~=0.24->cobra) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1.4->modelseedpy) (3.0.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->cobra) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->cobra) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=8.0->cobra) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=8.0->cobra) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->modelseedpy) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->modelseedpy) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.12.0->optlang) (1.3.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest->pytfa) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest->pytfa) (1.6.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=8.0->cobra) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->chemw>=0.3.2->modelseedpy) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->chemw>=0.3.2->modelseedpy) (2.5.0)
Collecting sortedcontainers<3.0.0,>=2.4.0 (from sigfig->chemw>=0.3.2->modelseedpy)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Downloading cobra-0.30.0-py2.py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 46.4 MB/s eta 0:00:00
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.1 MB/s eta 0:00:00
Downloading optlang-1.8.3-py2.py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.8/141.8 kB 11.0 MB/s eta 0:00:00
Downloading modelseedpy-0.4.2-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 14.7 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading chemicals-1.5.1-py3-none-any.whl (22.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 74.6 MB/s eta 0:00:00
Downloading depinfo-2.2.0-py3-none-any.whl (24 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.3 MB/s eta 0:00:00
Downloading python_libsbml-5.21.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 79.3 MB/s eta 0:00:00
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 9.2 MB/s eta 0:00:00
Downloading swiglpk-5.0.13-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 58.6 MB/s eta 0:00:00
Downloading fluids-1.3.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.5/608.5 kB 35.4 MB/s eta 0:00:00
Downloading pubchempy-1.0.5-py3-none-any.whl (21 kB)
Downloading sigfig-1.3.19-py3-none-any.whl (10 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: pytfa, chemw
  Building wheel for pytfa (setup.py) ... done
  Created wheel for pytfa: filename=pytfa-0.9.1-py2.py3-none-any.whl size=79010 sha256=73214ef10df06de5f71a0938dcde519d5e1c33c02525ba919b15af7d89b77521
  Stored in directory: /root/.cache/pip/wheels/57/6d/67/ea678b40a1eb60b5e1716a0c6bc9c318a75fe5f033bb490b6e
  Building wheel for chemw (setup.py) ... done
  Created wheel for chemw: filename=ChemW-0.3.5-py3-none-any.whl size=480096 sha256=f9d4b0f58a310459f0fe446284e4d0679e79e9974b833cc81f01a36beb263597
  Stored in directory: /root/.cache/pip/wheels/a2/47/0b/2f96a35de8e49a49bfe63d6c9d11dec35ef813d66703645e35
Successfully built pytfa chemw
Installing collected packages: swiglpk, sortedcontainers, python-libsbml, appdirs, sigfig, ruamel.yaml, pubchempy, diskcache, depinfo, optlang, fluids, cobra, chemicals, catboost, pytfa, chemw, modelseedpy
Successfully installed appdirs-1.4.4 catboost-1.2.10 chemicals-1.5.1 chemw-0.3.5 cobra-0.30.0 depinfo-2.2.0 diskcache-5.6.3 fluids-1.3.0 modelseedpy-0.4.2 optlang-1.8.3 pubchempy-1.0.5 pytfa-0.9.1 python-libsbml-5.21.0 ruamel.yaml-0.19.1 sigfig-1.3.19 sortedcontainers-2.4.0 swiglpk-5.0.13

In [ ]:
# Check installation
!pip3 show cobra

Name: cobra
Version: 0.30.0
Summary: COBRApy is a package for constraint-based modeling of metabolic networks.
Home-page: https://opencobra.github.io/cobrapy
Author: The cobrapy core development team.
Author-email: cobra-pie@googlegroups.com
License: LGPL-2.0-or-later OR GPL-2.0-or-later
Location: /usr/local/lib/python3.12/dist-packages
Requires: appdirs, depinfo, diskcache, future, httpx, numpy, optlang, pandas, pydantic, python-libsbml, rich, ruamel.yaml, swiglpk
Required-by: ModelSEEDpy, pytfa

In [ ]:
!pip3 show pytfa

Name: pytfa
Version: 0.9.1
Summary: pyTFA, Thermodynamics-based Flux Analysis in Python
Home-page: https://github.com/EPFL-LCSB/pytfa/
Author: pyTFA team
Author-email: softwares.lcsb@epfl.ch
License: Apache 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: bokeh, cobra, networkx, optlang, pytest, scipy, tqdm
Required-by:

# Mount drive

In [ ]:
import os
from pathlib import Path
from google.colab import drive

def mount_drive():
  drive.mount('/content/drive', force_remount=True)
  drive_folder = "metabolic_modelling/phb-optimization-rpalustris/"
  os.chdir('/content/drive/MyDrive/'+ drive_folder)
  global PROJECT_ROOT
  PROJECT_ROOT = Path(os.getcwd())

mount_drive()

Mounted at /content/drive

# Load packages

In [ ]:
# Load packages

import logging
import cobra
from cobra import Reaction, Metabolite, Model, io
from cobra.io import (
    load_model, load_json_model, save_json_model,
    load_matlab_model, save_matlab_model,
    read_sbml_model, write_sbml_model
)

from cobra.flux_analysis import flux_variability_analysis, pfba

from cobra.util.solver import linear_reaction_coefficients

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
from itertools import product
import seaborn as sns
import json
import math
import copy
from tqdm import tqdm
import sys
import seaborn as sns
from scipy.stats import mannwhitneyu
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import pytfa, pkgutil, inspect
from pytfa import ThermoModel
from pytfa.io import load_thermoDB
from pytfa.optim.variables import DeltaG
from pytfa.analysis import variability_analysis

from pytfa.io import read_lexicon, annotate_from_lexicon, read_compartment_data, apply_compartment_data

# Paths

In [ ]:
# Import path saved in src

import sys
sys.path.append(str(PROJECT_ROOT / "src"))
from src.paths import PHB_TFA_DIR, PHB_MODEL_TFA_DIR, DATA_DIR, MODELS_DIR, PHB_MODEL_DIR, PHB_CHECKPOINTS_DIR, PHB_RESULTS_DIR, PHB_FIGURES_DIR, PHB_GEM_EXPERIMENTAL_DIR, PHB_GEM_AUGMENTATION_DIR, PHB_CATBOOST_DIR, PHB_PARETO_DIR

# Load thermo data

In [ ]:
# Download thermo database
!wget https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb -O thermo_data.thermodb

# Load thermodynamics

thermo_data_path = DATA_DIR / "thermo_data.thermodb"
thermo_data = load_thermoDB(thermo_data_path)

# Print thermo_data keys

print(f"Thermo Data loaded successfully:{thermo_data.keys()}")

--2026-03-08 18:28:42--  https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2184378 (2.1M) [application/octet-stream]
Saving to: ‘thermo_data.thermodb’

thermo_data.thermod 100%[===================>]   2.08M  --.-KB/s    in 0.1s

2026-03-08 18:28:42 (18.9 MB/s) - ‘thermo_data.thermodb’ saved [2184378/2184378]

Thermo Data loaded successfully:dict_keys(['name', 'units', 'metabolites', 'cues'])

# *R. palustris GEM

Constrained model in previous notebooks (02_model_rpalustris_PHB_constrained.xml)

In [ ]:
# Load models

# Full path to the SBML file
model_path = PHB_MODEL_DIR / "02_model_rpalustris_PHB_constrained.xml"

# Alternatively use model associated to the Pareto Optimal solution with the maximum PHB production
# model_path = PHB_MODEL_DIR / ""best_pareto_PHB_model.xml"

# Load model
model_phb = io.read_sbml_model(
    str(model_path),
    use_fbc=False
)

print("Model loaded successfully")

Model loaded successfully

In [ ]:
model_phb.summary()

# Check PHB synthesis reaction values

In [ ]:
rxn = model_phb.reactions.get_by_id('PHBS_syn')
print("PHBS_syn bounds:", rxn.bounds)
print("PHBS_syn stoichiometry:", rxn.reaction)

PHBS_syn bounds: (0.0, 0.3978)
PHBS_syn stoichiometry: 3hbcoa__R_c + phbg_c --> PHB_c + coa_c

# Check Photon absorption reaction values

In [ ]:
rxn = model_phb.reactions.get_by_id('EX_photon690_e')
print("EX_photon690_e bounds:", rxn.bounds)
print("EX_photon690_e stoichiometry:", rxn.reaction)

EX_photon690_e bounds: (-1000.0, 1000.0)
EX_photon690_e stoichiometry: photon690_e <=>

# Load lexicon and compartment data

In [ ]:
# Load lexicon
lexicon_path = PHB_MODEL_TFA_DIR / "lexicon_iDT1294.csv" # load lexicon with 8 reactions

# Load compartments
compartments_path = PHB_MODEL_TFA_DIR / "compartment_data.json" # "compartments_data_iDT1294_test.json"

# Copy 02_model_rpalustris_PHB_constrained model
model_constrained = model_phb.copy()

# *Correct key formulas in model

Some formulas are incorrect. Here, only a handful of formulas of key reactions are corrected.

In [ ]:
import re
from collections import Counter

# --------------------------------
# INPUT DATA
# --------------------------------
Thermodb_meta_interest = [
  "C21H27N7O17P3",
  "C21H27N7O14P2",
  "C23H35N7O17P3S",
  "C21H26N7O14P2",
  "C25H39N7O18P3S",
  "C21H26N7O17P3",
  "C25H37N7O18P3S",
  "C21H33N7O16P3S"
]

GEM_meta_interest = [
  "C21H26N7O17P3",
  "C21H27N7O14P2",
  "C23H34N7O17P3S",
  "C21H26N7O14P2",
  "C25H38N7O18P3S",
  "C21H25N7O17P3",
  "C25H36N7O18P3S",
  "C21H32N7O16P3S"
]

# GEM metabolite IDs in SAME ORDER
gem_met_ids = [
  "nadph_c",
  "nadh_c",
  "accoa_c",
  "nad_c",
  "3hbcoa__R_c",
  "nadp_c",
  "aacoa_c",
  "coa_c",
]

# --------------------------------
# FORMULA PARSING UTILITIES
# --------------------------------
def parse_formula(formula):
  """Convert formula string to Counter"""
  return Counter({
      elem: int(count) if count else 1
      for elem, count in re.findall(r'([A-Z][a-z]?)(\d*)', formula)
  })

def counter_to_formula(counter):
  """Convert Counter back to formula string (Hill order, omit 1s)"""
  parts = []

  # Hill system: C, H, then others alphabetically
  if 'C' in counter:
      parts.append(f"C{counter['C']}" if counter['C'] != 1 else "C")
  if 'H' in counter:
      parts.append(f"H{counter['H']}" if counter['H'] != 1 else "H")

  for el in sorted(counter):
      if el in ('C', 'H'):
          continue
      count = counter[el]
      parts.append(f"{el}{count}" if count != 1 else el)

  return ''.join(parts)


def compare_formulas(thermo_f, gem_f):
  """Return element-wise difference GEM − ThermoDB"""
  t = parse_formula(thermo_f)
  g = parse_formula(gem_f)
  elements = set(t) | set(g)
  return {el: g.get(el, 0) - t.get(el, 0) for el in elements}

def update_gem_formula(gem_f, thermo_f):
  """Add missing elements from ThermoDB into GEM formula"""
  g = parse_formula(gem_f)
  t = parse_formula(thermo_f)

  for el, count in t.items():
      if g.get(el, 0) < count:
          g[el] = count

  return counter_to_formula(g)

# --------------------------------
# APPLY UPDATES TO MODEL
# --------------------------------
for met_id, thermo_f, gem_f in zip(gem_met_ids,
                                  Thermodb_meta_interest,
                                  GEM_meta_interest):

    diff = compare_formulas(thermo_f, gem_f)

    # Safety check (CRITICAL for TFA)
    for el in diff:
        if el in ("C", "N", "P") and diff[el] != 0:
            raise ValueError(
                f"Unsafe formula mismatch for {met_id}: element {el}"
            )

    new_formula = update_gem_formula(gem_f, thermo_f)

    if new_formula != gem_f:
        met = model_constrained.metabolites.get_by_id(met_id) ## update cobra model

        print(f"Updating {met_id}")
        print(f"  old: {gem_f}")
        print(f"  new: {new_formula}")
        print(f"  ThermoDB:       {thermo_f}")

        met.formula = new_formula

        # PRINT FROM MODEL OBJECT
        print(f"  new (model):  {met.formula}")
        print("-" * 40)


print("✅ GEM formulas updated and TFA-ready.")

Updating nadph_c
  old: C21H26N7O17P3
  new: C21H27N7O17P3
  ThermoDB:       C21H27N7O17P3
  new (model):  C21H27N7O17P3
----------------------------------------
Updating accoa_c
  old: C23H34N7O17P3S
  new: C23H35N7O17P3S
  ThermoDB:       C23H35N7O17P3S
  new (model):  C23H35N7O17P3S
----------------------------------------
Updating 3hbcoa__R_c
  old: C25H38N7O18P3S
  new: C25H39N7O18P3S
  ThermoDB:       C25H39N7O18P3S
  new (model):  C25H39N7O18P3S
----------------------------------------
Updating nadp_c
  old: C21H25N7O17P3
  new: C21H26N7O17P3
  ThermoDB:       C21H26N7O17P3
  new (model):  C21H26N7O17P3
----------------------------------------
Updating aacoa_c
  old: C25H36N7O18P3S
  new: C25H37N7O18P3S
  ThermoDB:       C25H37N7O18P3S
  new (model):  C25H37N7O18P3S
----------------------------------------
Updating coa_c
  old: C21H32N7O16P3S
  new: C21H33N7O16P3S
  ThermoDB:       C21H33N7O16P3S
  new (model):  C21H33N7O16P3S
----------------------------------------
✅ GEM formulas updated and TFA-ready.

# Opt: Load medium constraints from checkpoint
 Use if best Pareto model conditions are not loaded properly

In [ ]:
# Define function to apply medium condition from excel.
def apply_media_from_excel(model, excel_path, close_exchanges=True):
    """
    Apply media constraints from a CSV or Excel file with columns:
    Reaction | LowerBound | UpperBound
    """

    excel_path = Path(excel_path)

    # --- Read file safely ---
    if excel_path.suffix.lower() == ".csv":
        media_df = pd.read_csv(excel_path)
    else:
        media_df = pd.read_excel(excel_path)

    # --- Clean reaction IDs ---
    media_df["Reaction"] = media_df["Reaction"].astype(str).str.strip()

    required_cols = {"Reaction", "LowerBound", "UpperBound"}
    if not required_cols.issubset(media_df.columns):
        raise ValueError(f"File must contain columns: {required_cols}")

    # --- Close uptake only ---
    if close_exchanges:
        for rxn in model.exchanges:
            rxn.lower_bound = 0.0

    # --- Apply media ---
    for _, row in media_df.iterrows():
        rxn_id = row["Reaction"]

        if rxn_id not in model.reactions:
            print(f"Reaction {rxn_id} not found — skipping")
            continue

        rxn = model.reactions.get_by_id(rxn_id)
        rxn.lower_bound = float(row["LowerBound"])
        rxn.upper_bound = float(row["UpperBound"])

    # --- Debug ---
    ex_ac = model.reactions.get_by_id("EX_ac_e")
    print("DEBUG → EX_ac_e bounds:", ex_ac.bounds)

    return model

In [ ]:
# Load medium conditions from Pareto results
project_root = Path(os.getcwd())
excel_path_pareto_medium = PHB_CHECKPOINTS_DIR / "phb_model_medium_montiel_buitron_2022_exchange_bounds_right_before_fba.csv"

# Print file
media_df = pd.read_csv(excel_path_pareto_medium)
media_df

/content/driveDL/MyDrive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/models/phb/checkpoint_output/phb_model_medium_montiel_buitron_2022_exchange_bounds_right_before_fba.csv

In [ ]:
#model_constrained = model_constrained.copy()
model_constrained = apply_media_from_excel(
    model_constrained,
    excel_path_pareto_medium,
    close_exchanges=True
)

DEBUG → EX_ac_e bounds: (-0.2477, 1000.0)

# *Add compartments to cobra model

In [ ]:
model_constrained.compartments = {
        'c': 'Cytosol',
        'e': 'Extracellular',
        'p': 'Periplasm',
        'u': 'Unknown',
    }

In [ ]:
model_constrained.compartments = {
        'c': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        },
        'e': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        },
        'p': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.15,   # periplasm vs cytosol (example)
        },
        'u': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        }
    }

# Checkup function for wide value reactions

In [ ]:
# Check that all reaction bounds are <>1000

too_wide = [
    rxn.id for rxn in model_constrained.reactions
    if rxn.upper_bound > 1000 or rxn.lower_bound < -1000
]

print(f"Reactions still exceeding ±1000 bounds: {len(too_wide)}")

Reactions still exceeding ±1000 bounds: 0

# Multiple points TFA V4.1

Include operational and calculated parameters, fba, tfba, and their reaction fluxes.
This version does not handle data from diffferent CatBoost modelling strategies (i.e., "_con", "_sup", "_con_pfba"). For that purpose see the next version.

In [ ]:

# ============================================================
# USER PARAMETERS
# ============================================================
logging.getLogger("thermomodel_None").setLevel(logging.ERROR)
logging.getLogger("pytfa").setLevel(logging.ERROR)

PHB_SYN_UB_VALUES = [0.3978]#, 1000

# ============================================================
# CONSTANTS
# ============================================================
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

SUB_TO_RXN = {
    "ace": "EX_ac_e",
    "lac": "EX_lac__L_e",
    "ppa": "EX_ppa_e",
    "but": "EX_but_e",
    "ibt": "EX_ibt_e",
    "mal": "EX_mal__L_e",
    "hxa": "EX_hxa_e",
    "oct": "EX_octa_e",
    "nh4": "EX_nh4_e",
    "hco3": "EX_hco3_e",
}

EXCHANGE_RXNS = list(SUB_TO_RXN.values())

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True


# ============================================================
# LOAD TFA METADATA (ONCE)
# ============================================================
lexicon = read_lexicon(str(lexicon_path))
comp_data = read_compartment_data(str(compartments_path))


# ============================================================
# MAIN LOOP
# ============================================================
for PHB_SYN_UB in PHB_SYN_UB_VALUES:

    print(f"\n==============================")
    print(f"PHB_SYN_UB_VALUE: {PHB_SYN_UB}")
    print(f"==============================")

    PHB_SYN_TAG = f"{PHB_SYN_UB:g}"

    INPUT_CSV = PHB_PARETO_DIR / f"03_pareto_best_all_strategies_{PHB_SYN_TAG}.csv"
    OUT_CSV = PHB_TFA_DIR / f"05_FBA_TFA_PHB_detailed_results_{PHB_SYN_TAG}.csv"

    df = pd.read_csv(INPUT_CSV)

    if len(df) != 5:
        print(
            f" Warning: expected 3 Pareto solutions, found {len(df)} "
            f"for PHB_SYN_UB = {PHB_SYN_UB}"
        )

    results = []

    # ============================================================
    # LOOP OVER PARETO SOLUTIONS
    # ============================================================
    for pareto_id, row in df.iterrows():

        print(f"\n--- Pareto solution {pareto_id} ---")

        # -------------------------
        # BUILD MODEL
        # -------------------------
        m = model_constrained.copy()

        # -------------------------
        # APPLY EXCHANGE CONSTRAINTS
        # -------------------------
        for col, rxn_id in SUB_TO_RXN.items():
            if col in row and rxn_id in m.reactions:
                val = row[col]
                if pd.notna(val) and float(val) != 0.0:
                    rxn = m.reactions.get_by_id(rxn_id)
                    rxn.lower_bound = -abs(float(val))  # uptake
                    rxn.upper_bound = 0.0

        # -------------------------
        # OBJECTIVE: PHB
        # -------------------------
        phb_rxn = m.reactions.get_by_id("PHBS_syn")
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = PHB_SYN_UB
        m.objective = phb_rxn

        # -------------------------
        # NO GROWTH
        # -------------------------
        biomass = m.reactions.get_by_id("BIOMASS__1")
        biomass.lower_bound = 0.0
        biomass.upper_bound = 0.0

        apply_solver_settings(m)

        # -------------------------
        # FBA
        # -------------------------
        fba_sol = m.optimize()
        pfba_sol = pfba(m)

        # -------------------------
        # TFA
        # -------------------------
        mytfa = pytfa.ThermoModel(thermo_data, m.copy())
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)
        mytfa.objective = "PHBS_syn"
        apply_solver_settings(mytfa)
        mytfa.prepare()

        tfa_sol = mytfa.optimize()

        # -------------------------
        # COLLECT RESULTS
        # -------------------------
        result = {
            "PHB_SYN_UB": PHB_SYN_UB,
            "PHB_SYN_TAG": PHB_SYN_TAG,
            "pareto_id": pareto_id,
            "PHB_pFBA": pfba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan),
            "Biomass_pFBA": pfba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_pFBA": pfba_sol.status,
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
        }

        for r in PHB_REACTIONS:
            result[f"{r}_pFBA"] = pfba_sol.fluxes.get(r, np.nan)
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

        for r in EXCHANGE_RXNS:
            result[f"{r}_pFBA"] = pfba_sol.fluxes.get(r, np.nan)
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

        results.append(result)

    # ============================================================
    # SAVE RESULTS (3 ROWS PER PHB_SYN_UB)
    # ============================================================
    results_df = pd.DataFrame(results)

    results_df.to_csv(OUT_CSV, index=False)

    print(f"\nDONE — Results saved to:\n{OUT_CSV}")

Output hidden; open in https://colab.research.google.com to view.

# Multiple points TFA V4

It handles only one PHBS_syn value and no _con, _sup, etc

In [ ]:
# ============================================================
# IMPORTS
# ============================================================
import numpy as np
import pandas as pd
import cobra
import pytfa

from pytfa.io import (
    read_lexicon,
    annotate_from_lexicon,
    read_compartment_data,
    apply_compartment_data,
)

# ============================================================
# USER INPUT
# ============================================================
INPUT_CSV = PHB_PARETO_DIR / "03_pareto_best_all_strategies_0.3978.csv"
OUT_CSV   = PHB_TFA_DIR / "03_FBA_TFA_PHB_detailed_results_20260308.csv"

# ============================================================
# CONSTANTS
# ============================================================
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

# ============================================================
# COLUMN → EXCHANGE REACTION MAP
# ============================================================
SUB_TO_RXN = {
    "ace": "EX_ac_e",
    "lac": "EX_lac__L_e",
    "ppa": "EX_ppa_e",
    "but": "EX_but_e",
    "ibt": "EX_ibt_e",
    "mal": "EX_mal__L_e",
    "hxa": "EX_hxa_e",
    "oct": "EX_octa_e",
    "NH4_model_flux": "EX_nh4_e",
    "hco3": "EX_hco3_e",
}

EXCHANGE_RXNS = list(SUB_TO_RXN.values())

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True

# ============================================================
# LOAD TFA METADATA (ONCE)
# ============================================================
lexicon   = read_lexicon(str(lexicon_path))
comp_data = read_compartment_data(str(compartments_path))

# ============================================================
# LOAD PARETO SOLUTIONS (MULTIPLE ROWS)
# ============================================================
df = pd.read_csv(INPUT_CSV)


# keep only first row
df = df.iloc[:1]


if df.empty:
    raise ValueError("Pareto CSV is empty")

print(f"Loaded {len(df)} Pareto-optimal solutions")

# ============================================================
# OUTPUT COLUMNS
# ============================================================
ALL_COLUMNS = (
    ["Pareto_ID", "PHB_FBA", "PHB_TFA",
     "Biomass_FBA", "Biomass_TFA",
     "status_FBA", "status_TFA"]
    + [f"{r}_FBA" for r in PHB_REACTIONS]
    + [f"{r}_TFA" for r in PHB_REACTIONS]
    + [f"{r}_FBA" for r in EXCHANGE_RXNS]
    + [f"{r}_TFA" for r in EXCHANGE_RXNS]
)

all_results = []

# ============================================================
# MAIN LOOP OVER PARETO SOLUTIONS
# ============================================================
for idx, row in df.iterrows():

    print(f"\n--- Processing Pareto solution {idx} ---")

    # -------------------------
    # BUILD FRESH MODEL
    # -------------------------
    m = model_constrained.copy()
    apply_solver_settings(m)

    # -------------------------
    # APPLY SUBSTRATE CONSTRAINTS
    # -------------------------
    for col, rxn_id in SUB_TO_RXN.items():
        if col in row and rxn_id in m.reactions:
            val = row[col]
            if pd.notna(val) and float(val) != 0.0:
                rxn = m.reactions.get_by_id(rxn_id)
                rxn.lower_bound = -abs(float(val))
                rxn.upper_bound = 0.0

    # -------------------------
    # NO GROWTH
    # -------------------------
    biomass = m.reactions.get_by_id("BIOMASS__1")
    biomass.lower_bound = 0.0
    biomass.upper_bound = 0.0

    # -------------------------
    # PHB OBJECTIVE
    # -------------------------
    phb_rxn = m.reactions.get_by_id("PHBS_syn")
    phb_rxn.lower_bound = 0.0
    phb_rxn.upper_bound = 0.3978
    m.objective = phb_rxn

    # ============================================================
    # FBA
    # ============================================================
    fba_sol = m.optimize()

    # ============================================================
    # TFA
    # ============================================================
    mytfa = pytfa.ThermoModel(thermo_data, m.copy())
    annotate_from_lexicon(mytfa, lexicon)
    apply_compartment_data(mytfa, comp_data)

    mytfa.objective = "PHBS_syn"
    apply_solver_settings(mytfa)
    mytfa.prepare()
    mytfa.convert()


    tfa_sol = mytfa.optimize()

    # ============================================================
    # COLLECT RESULTS
    # ============================================================
    result = {
        "Pareto_ID": idx,
        "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan),
        "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan),
        "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
        "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
        "status_FBA": fba_sol.status,
        "status_TFA": tfa_sol.status,
    }

    for r in PHB_REACTIONS:
        result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
        result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

    for r in EXCHANGE_RXNS:
        result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
        result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

    all_results.append(result)

# ============================================================
# SAVE RESULTS
# ============================================================
results_df = pd.DataFrame(all_results)[ALL_COLUMNS]
results_df.to_csv(OUT_CSV, index=False)

print("\nDONE — FBA vs TFA comparison saved.")
print(f"Results written to: {OUT_CSV}")

Loaded 1 Pareto-optimal solutions

--- Processing Pareto solution 0 ---

Streaming output truncated to the last 5000 lines.
2026-03-08 19:11:53,328 - thermomodel_None - WARNING - dtdpglu_c  not found in annotations
WARNING:thermomodel_None:dtdpglu_c  not found in annotations
2026-03-08 19:11:53,329 - thermomodel_None - WARNING - 1odecg3p_c  not found in annotations
WARNING:thermomodel_None:1odecg3p_c  not found in annotations
2026-03-08 19:11:53,331 - thermomodel_None - WARNING - 1odec11eg3p_c  not found in annotations
WARNING:thermomodel_None:1odec11eg3p_c  not found in annotations
2026-03-08 19:11:53,332 - thermomodel_None - WARNING - octe_9_ACP_c  not found in annotations
WARNING:thermomodel_None:octe_9_ACP_c  not found in annotations
2026-03-08 19:11:53,333 - thermomodel_None - WARNING - 1odec912eg3p_c  not found in annotations
WARNING:thermomodel_None:1odec912eg3p_c  not found in annotations
2026-03-08 19:11:53,335 - thermomodel_None - WARNING - octe_9_12_ACP_c  not found in annotations
WARNING:thermomodel_None:octe_9_12_ACP_c  not found in annotations
2026-03-08 19:11:53,337 - thermomodel_None - WARNING - 1odec691215eg3p_c  not found in annotations
WARNING:thermomodel_None:1odec691215eg3p_c  not found in annotations
2026-03-08 19:11:53,338 - thermomodel_None - WARNING - octe_6_9_12_15_ACP_c  not found in annotations
WARNING:thermomodel_None:octe_6_9_12_15_ACP_c  not found in annotations
2026-03-08 19:11:53,340 - thermomodel_None - WARNING - 1odec91215eg3p_c  not found in annotations
WARNING:thermomodel_None:1odec91215eg3p_c  not found in annotations
2026-03-08 19:11:53,341 - thermomodel_None - WARNING - octe_9_12_15_ACP_c  not found in annotations
WARNING:thermomodel_None:octe_9_12_15_ACP_c  not found in annotations
2026-03-08 19:11:53,343 - thermomodel_None - WARNING - 1odec6912eg3p_c  not found in annotations
WARNING:thermomodel_None:1odec6912eg3p_c  not found in annotations
2026-03-08 19:11:53,344 - thermomodel_None - WARNING - octe_6_9_12_ACP_c  not found in annotations
WARNING:thermomodel_None:octe_6_9_12_ACP_c  not found in annotations
2026-03-08 19:11:53,346 - thermomodel_None - WARNING - fadh2_c  not found in annotations
WARNING:thermomodel_None:fadh2_c  not found in annotations
2026-03-08 19:11:53,348 - thermomodel_None - WARNING - g6p_B_c  not found in annotations
WARNING:thermomodel_None:g6p_B_c  not found in annotations
2026-03-08 19:11:53,349 - thermomodel_None - WARNING - bglycogen_c  not found in annotations
WARNING:thermomodel_None:bglycogen_c  not found in annotations
2026-03-08 19:11:53,350 - thermomodel_None - WARNING - glcglyc_c  not found in annotations
WARNING:thermomodel_None:glcglyc_c  not found in annotations
2026-03-08 19:11:53,352 - thermomodel_None - WARNING - glcglyc_p  not found in annotations
WARNING:thermomodel_None:glcglyc_p  not found in annotations
2026-03-08 19:11:53,353 - thermomodel_None - WARNING - glutrna_gln_c  not found in annotations
WARNING:thermomodel_None:glutrna_gln_c  not found in annotations
2026-03-08 19:11:53,354 - thermomodel_None - WARNING - glu__L_p  not found in annotations
WARNING:thermomodel_None:glu__L_p  not found in annotations
2026-03-08 19:11:53,356 - thermomodel_None - WARNING - 2h3oppan_c  not found in annotations
WARNING:thermomodel_None:2h3oppan_c  not found in annotations
2026-03-08 19:11:53,357 - thermomodel_None - WARNING - gly_p  not found in annotations
WARNING:thermomodel_None:gly_p  not found in annotations
2026-03-08 19:11:53,358 - thermomodel_None - WARNING - 35cgmp_c  not found in annotations
WARNING:thermomodel_None:35cgmp_c  not found in annotations
2026-03-08 19:11:53,360 - thermomodel_None - WARNING - 3hmp_c  not found in annotations
WARNING:thermomodel_None:3hmp_c  not found in annotations
2026-03-08 19:11:53,363 - thermomodel_None - WARNING - mmtsa_c  not found in annotations
WARNING:thermomodel_None:mmtsa_c  not found in annotations
2026-03-08 19:11:53,366 - thermomodel_None - WARNING - his__L_p  not found in annotations
WARNING:thermomodel_None:his__L_p  not found in annotations
2026-03-08 19:11:53,368 - thermomodel_None - WARNING - im4act_c  not found in annotations
WARNING:thermomodel_None:im4act_c  not found in annotations
2026-03-08 19:11:53,369 - thermomodel_None - WARNING - im4ac_c  not found in annotations
WARNING:thermomodel_None:im4ac_c  not found in annotations
2026-03-08 19:11:53,371 - thermomodel_None - WARNING - lald__D_c  not found in annotations
WARNING:thermomodel_None:lald__D_c  not found in annotations
2026-03-08 19:11:53,374 - thermomodel_None - WARNING - lald__L_c  not found in annotations
WARNING:thermomodel_None:lald__L_c  not found in annotations
2026-03-08 19:11:53,377 - thermomodel_None - WARNING - 12ppd__S_c  not found in annotations
WARNING:thermomodel_None:12ppd__S_c  not found in annotations
2026-03-08 19:11:53,378 - thermomodel_None - WARNING - 15dap_c  not found in annotations
WARNING:thermomodel_None:15dap_c  not found in annotations
2026-03-08 19:11:53,382 - thermomodel_None - WARNING - lys__L_p  not found in annotations
WARNING:thermomodel_None:lys__L_p  not found in annotations
2026-03-08 19:11:53,383 - thermomodel_None - WARNING - mi1p__D_c  not found in annotations
WARNING:thermomodel_None:mi1p__D_c  not found in annotations
2026-03-08 19:11:53,385 - thermomodel_None - WARNING - mppp9om_c  not found in annotations
WARNING:thermomodel_None:mppp9om_c  not found in annotations
2026-03-08 19:11:53,386 - thermomodel_None - WARNING - dvpchlld_c  not found in annotations
WARNING:thermomodel_None:dvpchlld_c  not found in annotations
2026-03-08 19:11:53,388 - thermomodel_None - WARNING - n4abutn_c  not found in annotations
WARNING:thermomodel_None:n4abutn_c  not found in annotations
2026-03-08 19:11:53,390 - thermomodel_None - WARNING - 4aabutn_c  not found in annotations
WARNING:thermomodel_None:4aabutn_c  not found in annotations
2026-03-08 19:11:53,393 - thermomodel_None - WARNING - q8_c  not found in annotations
WARNING:thermomodel_None:q8_c  not found in annotations
2026-03-08 19:11:53,395 - thermomodel_None - WARNING - q8h2_c  not found in annotations
WARNING:thermomodel_None:q8h2_c  not found in annotations
2026-03-08 19:11:53,397 - thermomodel_None - WARNING - didp_c  not found in annotations
WARNING:thermomodel_None:didp_c  not found in annotations
2026-03-08 19:11:53,398 - thermomodel_None - WARNING - ditp_c  not found in annotations
WARNING:thermomodel_None:ditp_c  not found in annotations
2026-03-08 19:11:53,400 - thermomodel_None - WARNING - idp_c  not found in annotations
WARNING:thermomodel_None:idp_c  not found in annotations
2026-03-08 19:11:53,404 - thermomodel_None - WARNING - itp_c  not found in annotations
WARNING:thermomodel_None:itp_c  not found in annotations
2026-03-08 19:11:53,405 - thermomodel_None - WARNING - cytd_c  not found in annotations
WARNING:thermomodel_None:cytd_c  not found in annotations
2026-03-08 19:11:53,408 - thermomodel_None - WARNING - 3ophb_c  not found in annotations
WARNING:thermomodel_None:3ophb_c  not found in annotations
2026-03-08 19:11:53,410 - thermomodel_None - WARNING - 2oph_c  not found in annotations
WARNING:thermomodel_None:2oph_c  not found in annotations
2026-03-08 19:11:53,413 - thermomodel_None - WARNING - lpam_c  not found in annotations
WARNING:thermomodel_None:lpam_c  not found in annotations
2026-03-08 19:11:53,416 - thermomodel_None - WARNING - adhlam_c  not found in annotations
WARNING:thermomodel_None:adhlam_c  not found in annotations
2026-03-08 19:11:53,419 - thermomodel_None - WARNING - dhlam_c  not found in annotations
WARNING:thermomodel_None:dhlam_c  not found in annotations
2026-03-08 19:11:53,421 - thermomodel_None - WARNING - pgp160_c  not found in annotations
WARNING:thermomodel_None:pgp160_c  not found in annotations
2026-03-08 19:11:53,422 - thermomodel_None - WARNING - pgp161_c  not found in annotations
WARNING:thermomodel_None:pgp161_c  not found in annotations
2026-03-08 19:11:53,425 - thermomodel_None - WARNING - pgp180_c  not found in annotations
WARNING:thermomodel_None:pgp180_c  not found in annotations
2026-03-08 19:11:53,427 - thermomodel_None - WARNING - pgp181_c  not found in annotations
WARNING:thermomodel_None:pgp181_c  not found in annotations
2026-03-08 19:11:53,431 - thermomodel_None - WARNING - pgp181_9_c  not found in annotations
WARNING:thermomodel_None:pgp181_9_c  not found in annotations
2026-03-08 19:11:53,436 - thermomodel_None - WARNING - pgp182_9_12_c  not found in annotations
WARNING:thermomodel_None:pgp182_9_12_c  not found in annotations
2026-03-08 19:11:53,438 - thermomodel_None - WARNING - pgp183_6_9_12_c  not found in annotations
WARNING:thermomodel_None:pgp183_6_9_12_c  not found in annotations
2026-03-08 19:11:53,441 - thermomodel_None - WARNING - pgp183_9_12_15_c  not found in annotations
WARNING:thermomodel_None:pgp183_9_12_15_c  not found in annotations
2026-03-08 19:11:53,444 - thermomodel_None - WARNING - pgp184_6_9_12_15_c  not found in annotations
WARNING:thermomodel_None:pgp184_6_9_12_15_c  not found in annotations
2026-03-08 19:11:53,446 - thermomodel_None - WARNING - phytoe_c  not found in annotations
WARNING:thermomodel_None:phytoe_c  not found in annotations
2026-03-08 19:11:53,449 - thermomodel_None - WARNING - r1p_c  not found in annotations
WARNING:thermomodel_None:r1p_c  not found in annotations
2026-03-08 19:11:53,452 - thermomodel_None - WARNING - pro__L_p  not found in annotations
WARNING:thermomodel_None:pro__L_p  not found in annotations
2026-03-08 19:11:53,453 - thermomodel_None - WARNING - pyam5p_c  not found in annotations
WARNING:thermomodel_None:pyam5p_c  not found in annotations
2026-03-08 19:11:53,456 - thermomodel_None - WARNING - pydxn_c  not found in annotations
WARNING:thermomodel_None:pydxn_c  not found in annotations
2026-03-08 19:11:53,459 - thermomodel_None - WARNING - pydx_c  not found in annotations
WARNING:thermomodel_None:pydx_c  not found in annotations
2026-03-08 19:11:53,461 - thermomodel_None - WARNING - pydam_c  not found in annotations
WARNING:thermomodel_None:pydam_c  not found in annotations
2026-03-08 19:11:53,464 - thermomodel_None - WARNING - sl26da_c  not found in annotations
WARNING:thermomodel_None:sl26da_c  not found in annotations
2026-03-08 19:11:53,467 - thermomodel_None - WARNING - sl2a6o_c  not found in annotations
WARNING:thermomodel_None:sl2a6o_c  not found in annotations
2026-03-08 19:11:53,470 - thermomodel_None - WARNING - ser__L_p  not found in annotations
WARNING:thermomodel_None:ser__L_p  not found in annotations
2026-03-08 19:11:53,473 - thermomodel_None - WARNING - suc6p_c  not found in annotations
WARNING:thermomodel_None:suc6p_c  not found in annotations
2026-03-08 19:11:53,475 - thermomodel_None - WARNING - sqdg161_c  not found in annotations
WARNING:thermomodel_None:sqdg161_c  not found in annotations
2026-03-08 19:11:53,478 - thermomodel_None - WARNING - 12dgr180_c  not found in annotations
WARNING:thermomodel_None:12dgr180_c  not found in annotations
2026-03-08 19:11:53,481 - thermomodel_None - WARNING - sqdg180_c  not found in annotations
WARNING:thermomodel_None:sqdg180_c  not found in annotations
2026-03-08 19:11:53,484 - thermomodel_None - WARNING - 12dgr181_c  not found in annotations
WARNING:thermomodel_None:12dgr181_c  not found in annotations
2026-03-08 19:11:53,486 - thermomodel_None - WARNING - sqdg181_c  not found in annotations
WARNING:thermomodel_None:sqdg181_c  not found in annotations
2026-03-08 19:11:53,488 - thermomodel_None - WARNING - 12dgr181_9_c  not found in annotations
WARNING:thermomodel_None:12dgr181_9_c  not found in annotations
2026-03-08 19:11:53,489 - thermomodel_None - WARNING - 12dgr182_9_12_c  not found in annotations
WARNING:thermomodel_None:12dgr182_9_12_c  not found in annotations
2026-03-08 19:11:53,491 - thermomodel_None - WARNING - sqdg182_9_12_c  not found in annotations
WARNING:thermomodel_None:sqdg182_9_12_c  not found in annotations
2026-03-08 19:11:53,492 - thermomodel_None - WARNING - 12dgr183_6_9_12_c  not found in annotations
WARNING:thermomodel_None:12dgr183_6_9_12_c  not found in annotations
2026-03-08 19:11:53,494 - thermomodel_None - WARNING - sqdg183_6_9_12_c  not found in annotations
WARNING:thermomodel_None:sqdg183_6_9_12_c  not found in annotations
2026-03-08 19:11:53,495 - thermomodel_None - WARNING - 12dgr183_9_12_15_c  not found in annotations
WARNING:thermomodel_None:12dgr183_9_12_15_c  not found in annotations
2026-03-08 19:11:53,496 - thermomodel_None - WARNING - 12dgr184_6_9_12_15_c  not found in annotations
WARNING:thermomodel_None:12dgr184_6_9_12_15_c  not found in annotations
2026-03-08 19:11:53,498 - thermomodel_None - WARNING - sqdg184_6_9_12_15_c  not found in annotations
WARNING:thermomodel_None:sqdg184_6_9_12_15_c  not found in annotations
2026-03-08 19:11:53,499 - thermomodel_None - WARNING - sql_c  not found in annotations
WARNING:thermomodel_None:sql_c  not found in annotations
2026-03-08 19:11:53,503 - thermomodel_None - WARNING - dptne_c  not found in annotations
WARNING:thermomodel_None:dptne_c  not found in annotations
2026-03-08 19:11:53,504 - thermomodel_None - WARNING - dpterol_c  not found in annotations
WARNING:thermomodel_None:dpterol_c  not found in annotations
2026-03-08 19:11:53,506 - thermomodel_None - WARNING - succoa_c  not found in annotations
WARNING:thermomodel_None:succoa_c  not found in annotations
2026-03-08 19:11:53,509 - thermomodel_None - WARNING - sucr_p  not found in annotations
WARNING:thermomodel_None:sucr_p  not found in annotations
2026-03-08 19:11:53,511 - thermomodel_None - WARNING - dtdprmn_c  not found in annotations
WARNING:thermomodel_None:dtdprmn_c  not found in annotations
2026-03-08 19:11:53,513 - thermomodel_None - WARNING - thfglu_c  not found in annotations
WARNING:thermomodel_None:thfglu_c  not found in annotations
2026-03-08 19:11:53,516 - thermomodel_None - WARNING - 4hba_c  not found in annotations
WARNING:thermomodel_None:4hba_c  not found in annotations
2026-03-08 19:11:53,519 - thermomodel_None - WARNING - 4mpetz_c  not found in annotations
WARNING:thermomodel_None:4mpetz_c  not found in annotations
2026-03-08 19:11:53,521 - thermomodel_None - WARNING - dxyl_c  not found in annotations
WARNING:thermomodel_None:dxyl_c  not found in annotations
2026-03-08 19:11:53,523 - thermomodel_None - WARNING - 4mhetz_c  not found in annotations
WARNING:thermomodel_None:4mhetz_c  not found in annotations
2026-03-08 19:11:53,524 - thermomodel_None - WARNING - u23ga_c  not found in annotations
WARNING:thermomodel_None:u23ga_c  not found in annotations
2026-03-08 19:11:53,527 - thermomodel_None - WARNING - u3hga_c  not found in annotations
WARNING:thermomodel_None:u3hga_c  not found in annotations
2026-03-08 19:11:53,529 - thermomodel_None - WARNING - u3aga_c  not found in annotations
WARNING:thermomodel_None:u3aga_c  not found in annotations
2026-03-08 19:11:53,532 - thermomodel_None - WARNING - uGgl_c  not found in annotations
WARNING:thermomodel_None:uGgl_c  not found in annotations
2026-03-08 19:11:53,535 - thermomodel_None - WARNING - uGgla_c  not found in annotations
WARNING:thermomodel_None:uGgla_c  not found in annotations
2026-03-08 19:11:53,537 - thermomodel_None - WARNING - uppg1_c  not found in annotations
WARNING:thermomodel_None:uppg1_c  not found in annotations
2026-03-08 19:11:53,539 - thermomodel_None - WARNING - cpppg1_c  not found in annotations
WARNING:thermomodel_None:cpppg1_c  not found in annotations
2026-03-08 19:11:53,543 - thermomodel_None - WARNING - n2_e  not found in annotations
WARNING:thermomodel_None:n2_e  not found in annotations
2026-03-08 19:11:53,545 - thermomodel_None - WARNING - fdxo_42_c  not found in annotations
WARNING:thermomodel_None:fdxo_42_c  not found in annotations
2026-03-08 19:11:53,548 - thermomodel_None - WARNING - fdxr_42_c  not found in annotations
WARNING:thermomodel_None:fdxr_42_c  not found in annotations
2026-03-08 19:11:53,549 - thermomodel_None - WARNING - n2_c  not found in annotations
WARNING:thermomodel_None:n2_c  not found in annotations
2026-03-08 19:11:53,550 - thermomodel_None - WARNING - 14glucan_p  not found in annotations
WARNING:thermomodel_None:14glucan_p  not found in annotations
2026-03-08 19:11:53,554 - thermomodel_None - WARNING - 23doguln_c  not found in annotations
WARNING:thermomodel_None:23doguln_c  not found in annotations
2026-03-08 19:11:53,556 - thermomodel_None - WARNING - 23doguln_p  not found in annotations
WARNING:thermomodel_None:23doguln_p  not found in annotations
2026-03-08 19:11:53,559 - thermomodel_None - WARNING - 2ddara_c  not found in annotations
WARNING:thermomodel_None:2ddara_c  not found in annotations
2026-03-08 19:11:53,561 - thermomodel_None - WARNING - 2doxg6p_c  not found in annotations
WARNING:thermomodel_None:2doxg6p_c  not found in annotations
2026-03-08 19:11:53,563 - thermomodel_None - WARNING - 2dglc_p  not found in annotations
WARNING:thermomodel_None:2dglc_p  not found in annotations
2026-03-08 19:11:53,566 - thermomodel_None - WARNING - 2dhguln_c  not found in annotations
WARNING:thermomodel_None:2dhguln_c  not found in annotations
2026-03-08 19:11:53,568 - thermomodel_None - WARNING - glcn_c  not found in annotations
WARNING:thermomodel_None:glcn_c  not found in annotations
2026-03-08 19:11:53,571 - thermomodel_None - WARNING - idon__L_c  not found in annotations
WARNING:thermomodel_None:idon__L_c  not found in annotations
2026-03-08 19:11:53,574 - thermomodel_None - WARNING - 2dglc_c  not found in annotations
WARNING:thermomodel_None:2dglc_c  not found in annotations
2026-03-08 19:11:53,576 - thermomodel_None - WARNING - mercpeth_c  not found in annotations
WARNING:thermomodel_None:mercpeth_c  not found in annotations
2026-03-08 19:11:53,578 - thermomodel_None - WARNING - dtgcl_c  not found in annotations
WARNING:thermomodel_None:dtgcl_c  not found in annotations
2026-03-08 19:11:53,580 - thermomodel_None - WARNING - 2hptcl_c  not found in annotations
WARNING:thermomodel_None:2hptcl_c  not found in annotations
2026-03-08 19:11:53,582 - thermomodel_None - WARNING - 2hptcoa_c  not found in annotations
WARNING:thermomodel_None:2hptcoa_c  not found in annotations
2026-03-08 19:11:53,583 - thermomodel_None - WARNING - msa_c  not found in annotations
WARNING:thermomodel_None:msa_c  not found in annotations
2026-03-08 19:11:53,585 - thermomodel_None - WARNING - 3amac_c  not found in annotations
WARNING:thermomodel_None:3amac_c  not found in annotations
2026-03-08 19:11:53,587 - thermomodel_None - WARNING - 3hppnl_c  not found in annotations
WARNING:thermomodel_None:3hppnl_c  not found in annotations
2026-03-08 19:11:53,588 - thermomodel_None - WARNING - 3hpp_c  not found in annotations
WARNING:thermomodel_None:3hpp_c  not found in annotations
2026-03-08 19:11:53,590 - thermomodel_None - WARNING - uri_p  not found in annotations
WARNING:thermomodel_None:uri_p  not found in annotations
2026-03-08 19:11:53,592 - thermomodel_None - WARNING - 3ump_p  not found in annotations
WARNING:thermomodel_None:3ump_p  not found in annotations
2026-03-08 19:11:53,593 - thermomodel_None - WARNING - cytd_p  not found in annotations
WARNING:thermomodel_None:cytd_p  not found in annotations
2026-03-08 19:11:53,596 - thermomodel_None - WARNING - 3cmp_p  not found in annotations
WARNING:thermomodel_None:3cmp_p  not found in annotations
2026-03-08 19:11:53,598 - thermomodel_None - WARNING - adn_p  not found in annotations
WARNING:thermomodel_None:adn_p  not found in annotations
2026-03-08 19:11:53,599 - thermomodel_None - WARNING - 3amp_p  not found in annotations
WARNING:thermomodel_None:3amp_p  not found in annotations
2026-03-08 19:11:53,602 - thermomodel_None - WARNING - 3gmp_p  not found in annotations
WARNING:thermomodel_None:3gmp_p  not found in annotations
2026-03-08 19:11:53,605 - thermomodel_None - WARNING - gsn_p  not found in annotations
WARNING:thermomodel_None:gsn_p  not found in annotations
2026-03-08 19:11:53,608 - thermomodel_None - WARNING - oxadpcoa_c  not found in annotations
WARNING:thermomodel_None:oxadpcoa_c  not found in annotations

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_None:SPMDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:DHAD2 : thermo constraint NOT created
DEBUG:thermomodel_None:PRAMPC : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS80 : thermo constraint NOT created
DEBUG:thermomodel_None:G1PCTYT : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_CELL_WALL : thermo constraint NOT created
DEBUG:thermomodel_None:CA2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:UHGADA2 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO6 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPK : thermo constraint NOT created
DEBUG:thermomodel_None:DXPS : thermo constraint NOT created
DEBUG:thermomodel_None:PRATPP : thermo constraint NOT created
DEBUG:thermomodel_None:NH4tpp : thermo constraint NOT created
DEBUG:thermomodel_None:PAPSR : thermo constraint NOT created
DEBUG:thermomodel_None:NAD_H2 : thermo constraint NOT created
DEBUG:thermomodel_None:CYRDAAT : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP8 : thermo constraint NOT created
DEBUG:thermomodel_None:PC11M : thermo constraint NOT created
DEBUG:thermomodel_None:ARGabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PMDPHT : thermo constraint NOT created
DEBUG:thermomodel_None:DAPE : thermo constraint NOT created
DEBUG:thermomodel_None:LYCOPC : thermo constraint NOT created
DEBUG:thermomodel_None:RB15BPtcx : thermo constraint NOT created
DEBUG:thermomodel_None:GLCBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_None:DB4PS : thermo constraint NOT created
DEBUG:thermomodel_None:DXPRIi : thermo constraint NOT created
DEBUG:thermomodel_None:GTPCII : thermo constraint NOT created
DEBUG:thermomodel_None:RBFSa : thermo constraint NOT created
DEBUG:thermomodel_None:GLUTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD2y : thermo constraint NOT created
DEBUG:thermomodel_None:EHGLAT : thermo constraint NOT created
DEBUG:thermomodel_None:METAT : thermo constraint NOT created
DEBUG:thermomodel_None:DHORTS : thermo constraint NOT created
DEBUG:thermomodel_None:PDX5PS2 : thermo constraint NOT created
DEBUG:thermomodel_None:GAPDi_nadp : thermo constraint NOT created
DEBUG:thermomodel_None:PGCD : thermo constraint NOT created
DEBUG:thermomodel_None:AIRC3 : thermo constraint NOT created
DEBUG:thermomodel_None:UMPK : thermo constraint NOT created
DEBUG:thermomodel_None:CBPS : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD180 : thermo constraint NOT created
DEBUG:thermomodel_None:IPPMIb : thermo constraint NOT created
DEBUG:thermomodel_None:RZ5PP : thermo constraint NOT created
DEBUG:thermomodel_None:RBFSb_1 : thermo constraint NOT created
DEBUG:thermomodel_None:GLNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK8 : thermo constraint NOT created
DEBUG:thermomodel_None:PC6YM_1 : thermo constraint NOT created
DEBUG:thermomodel_None:DDPA : thermo constraint NOT created
DEBUG:thermomodel_None:ACOTA : thermo constraint NOT created
DEBUG:thermomodel_None:FBP : thermo constraint NOT created
DEBUG:thermomodel_None:MNabc_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD7 : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMMM : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFD : thermo constraint NOT created
DEBUG:thermomodel_None:PANTS : thermo constraint NOT created
DEBUG:thermomodel_None:TMPK : thermo constraint NOT created
DEBUG:thermomodel_None:KARI_23dhmp_1 : thermo constraint NOT created
DEBUG:thermomodel_None:IPMD : thermo constraint NOT created
DEBUG:thermomodel_None:3PGtcx : thermo constraint NOT created
DEBUG:thermomodel_None:CDPMEK : thermo constraint NOT created
DEBUG:thermomodel_None:CITCIa : thermo constraint NOT created
DEBUG:thermomodel_None:DVOCHR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:H2CO3_NAt_syn : thermo constraint NOT created
DEBUG:thermomodel_None:HEMEOS : thermo constraint NOT created
DEBUG:thermomodel_None:RPE : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMT_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UAMAS : thermo constraint NOT created
DEBUG:thermomodel_None:CITCIb : thermo constraint NOT created
DEBUG:thermomodel_None:BPNT2 : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_COFACTORS : thermo constraint NOT created
DEBUG:thermomodel_None:HSERTA : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK1 : thermo constraint NOT created
DEBUG:thermomodel_None:PGL : thermo constraint NOT created
DEBUG:thermomodel_None:EAR160y : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDHf : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR3_1 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD140 : thermo constraint NOT created
DEBUG:thermomodel_None:FBA3 : thermo constraint NOT created
DEBUG:thermomodel_None:LDAPAT : thermo constraint NOT created
DEBUG:thermomodel_None:MG2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3E_1_cx : thermo constraint NOT created
DEBUG:thermomodel_None:ACODA : thermo constraint NOT created
DEBUG:thermomodel_None:GLU5K : thermo constraint NOT created
DEBUG:thermomodel_None:EAR100y : thermo constraint NOT created
DEBUG:thermomodel_None:PGM : thermo constraint NOT created
DEBUG:thermomodel_None:ASPOb : thermo constraint NOT created
DEBUG:thermomodel_None:DM_h2_c : thermo constraint NOT created
DEBUG:thermomodel_None:ACS : thermo constraint NOT created
DEBUG:thermomodel_None:AMPTASECG : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHCS3 : thermo constraint NOT created
DEBUG:thermomodel_None:ATPPRT : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_4_um_copy1 : thermo constraint NOT created
DEBUG:thermomodel_None:UAGCVT : thermo constraint NOT created
DEBUG:thermomodel_None:ADSL2r : thermo constraint NOT created
DEBUG:thermomodel_None:PRASCSi : thermo constraint NOT created
DEBUG:thermomodel_None:MG2tex : thermo constraint NOT created
DEBUG:thermomodel_None:HPROb : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP2 : thermo constraint NOT created
DEBUG:thermomodel_None:TRDR : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK6 : thermo constraint NOT created
DEBUG:thermomodel_None:GLUPRT : thermo constraint NOT created
DEBUG:thermomodel_None:PTRCabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:UPP3MT : thermo constraint NOT created
DEBUG:thermomodel_None:DHNCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:MCOATA : thermo constraint NOT created
DEBUG:thermomodel_None:PMPK : thermo constraint NOT created
DEBUG:thermomodel_None:HMBS : thermo constraint NOT created
DEBUG:thermomodel_None:PGLYCP : thermo constraint NOT created
DEBUG:thermomodel_None:UAGAAT2 : thermo constraint NOT created
DEBUG:thermomodel_None:HTHRPDH : thermo constraint NOT created
DEBUG:thermomodel_None:BCT1_syn : thermo constraint NOT created
DEBUG:thermomodel_None:IPDDI : thermo constraint NOT created
DEBUG:thermomodel_None:GLYALDDy : thermo constraint NOT created
DEBUG:thermomodel_None:CITMS : thermo constraint NOT created
DEBUG:thermomodel_None:IMPC : thermo constraint NOT created
DEBUG:thermomodel_None:Htcx : thermo constraint NOT created
DEBUG:thermomodel_None:DHQTi : thermo constraint NOT created
DEBUG:thermomodel_None:SPODM : thermo constraint NOT created
DEBUG:thermomodel_None:MAN6PI : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS120 : thermo constraint NOT created
DEBUG:thermomodel_None:PGAMT : thermo constraint NOT created
DEBUG:thermomodel_None:PSERT : thermo constraint NOT created
DEBUG:thermomodel_None:HISTP : thermo constraint NOT created
DEBUG:thermomodel_None:NNDPR : thermo constraint NOT created
DEBUG:thermomodel_None:ADSK : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPS : thermo constraint NOT created
DEBUG:thermomodel_None:CUabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADCYRS : thermo constraint NOT created
DEBUG:thermomodel_None:RBPCcx : thermo constraint NOT created

Warning : None/None
Warning : None/None

DEBUG:thermomodel_None:3HAD40_2 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR180y : thermo constraint NOT created
DEBUG:thermomodel_None:GTHRDH_syn : thermo constraint NOT created
DEBUG:thermomodel_None:PRAIi : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTtabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTPATi : thermo constraint NOT created
DEBUG:thermomodel_None:PC6AR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:Kabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ENO : thermo constraint NOT created
DEBUG:thermomodel_None:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_None:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_None:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_None:RBFK : thermo constraint NOT created
DEBUG:thermomodel_None:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_None:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_None:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_None:SPTc : thermo constraint NOT created
DEBUG:thermomodel_None:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_None:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_None:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_None:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_None:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_None:ORPT : thermo constraint NOT created
DEBUG:thermomodel_None:GRTT : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_None:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_None:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_None:FCLT : thermo constraint NOT created
DEBUG:thermomodel_None:PPA : thermo constraint NOT created
DEBUG:thermomodel_None:DHQS : thermo constraint NOT created
DEBUG:thermomodel_None:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_None:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_None:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_None:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_None:NADK : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_None:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_None:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_None:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_None:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_None:NADTRHD : thermo constraint created
DEBUG:thermomodel_None:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_None:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_None:ILETA : thermo constraint NOT created
DEBUG:thermomodel_None:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_None:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_None:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_None:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_None:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_None:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PC20M : thermo constraint NOT created
DEBUG:thermomodel_None:ADSS : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_None:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_None:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_None:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_None:DHFR : thermo constraint NOT created
DEBUG:thermomodel_None:ACGS : thermo constraint NOT created
DEBUG:thermomodel_None:AFAT : thermo constraint NOT created
DEBUG:thermomodel_None:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_None:FRTT : thermo constraint NOT created
DEBUG:thermomodel_None:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_None:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_None:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_None:GTHS : thermo constraint NOT created
DEBUG:thermomodel_None:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_None:DADK : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_None:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_None:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_None:PDH : thermo constraint NOT created
DEBUG:thermomodel_None:MPML : thermo constraint NOT created
DEBUG:thermomodel_None:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_None:TPI : thermo constraint NOT created
DEBUG:thermomodel_None:DHPPDA : thermo constraint NOT created
DEBUG:thermomodel_None:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_None:CAT : thermo constraint NOT created
DEBUG:thermomodel_None:GLUR : thermo constraint NOT created
DEBUG:thermomodel_None:ALAR : thermo constraint NOT created
DEBUG:thermomodel_None:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_None:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_None:ADCS : thermo constraint NOT created
DEBUG:thermomodel_None:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_None:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_None:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_None:MTRI : thermo constraint NOT created
DEBUG:thermomodel_None:SPMS : thermo constraint NOT created
DEBUG:thermomodel_None:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PEPC : thermo constraint NOT created
DEBUG:thermomodel_None:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_None:CHORM : thermo constraint NOT created
DEBUG:thermomodel_None:GAPD : thermo constraint NOT created
DEBUG:thermomodel_None:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_None:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_None:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_None:OCBT : thermo constraint NOT created
DEBUG:thermomodel_None:E4PD : thermo constraint NOT created
DEBUG:thermomodel_None:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_None:GLGC : thermo constraint NOT created
DEBUG:thermomodel_None:PYK : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_None:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_None:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_None:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_None:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_None:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_None:RPI : thermo constraint NOT created
DEBUG:thermomodel_None:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_None:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_None:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_None:BPNT : thermo constraint NOT created
DEBUG:thermomodel_None:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_None:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_so4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cu2_e : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_None:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_None:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_None:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_None:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_None:MNtex : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_None:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_None:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_None:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_None:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_None:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_None:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_None:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_None:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_None:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:NAtex : thermo constraint NOT created
DEBUG:thermomodel_None:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_None:Ktex : thermo constraint NOT created
DEBUG:thermomodel_None:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:PItex : thermo constraint NOT created
DEBUG:thermomodel_None:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_None:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_None:ARD : thermo constraint NOT created
DEBUG:thermomodel_None:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_None:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_None:ZISO : thermo constraint NOT created
DEBUG:thermomodel_None:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_None:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_None:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_None:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_None:SPR : thermo constraint NOT created
DEBUG:thermomodel_None:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_None:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_None:THISAT : thermo constraint NOT created
DEBUG:thermomodel_None:THII : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_None:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_None:THZT : thermo constraint NOT created
DEBUG:thermomodel_None:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_None:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_None:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_None:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_None:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_None:DBTS : thermo constraint NOT created
DEBUG:thermomodel_None:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_None:BACCL : thermo constraint NOT created
DEBUG:thermomodel_None:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_None:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_None:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:MEOHtex : thermo constraint NOT created
DEBUG:thermomodel_None:DM_amob_c : thermo constraint NOT created
DEBUG:thermomodel_None:ADNK1 : thermo constraint NOT created
DEBUG:thermomodel_None:CDGS : thermo constraint NOT created
DEBUG:thermomodel_None:CCGS : thermo constraint NOT created
DEBUG:thermomodel_None:CDGR : thermo constraint NOT created
DEBUG:thermomodel_None:QUERT : thermo constraint NOT created
DEBUG:thermomodel_None:SAMTRI : thermo constraint NOT created
DEBUG:thermomodel_None:EPXQR : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGD : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGLDC : thermo constraint NOT created
DEBUG:thermomodel_None:GMAND : thermo constraint NOT created
DEBUG:thermomodel_None:GFUCS : thermo constraint NOT created
DEBUG:thermomodel_None:CDPGLC46DH : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_1_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_4_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_None:KAS15 : thermo constraint NOT created
DEBUG:thermomodel_None:AACPS6 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDR18 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDDC17 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT1819Z_1 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:AGPAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA161 : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:SQDGS_PALM_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:SQDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:CDPDAGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PGPS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PGPP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_None:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_None:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_None:METTRS : thermo constraint NOT created
DEBUG:thermomodel_None:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_None:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_None:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_None:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_None:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_None:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_None:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_None:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_None:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_None:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_None:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_None:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_None:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_None:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_None:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_None:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_None:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_None:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_None:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_None:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_None:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OANTS : thermo constraint NOT created
DEBUG:thermomodel_None:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_None:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_None:MPTG : thermo constraint NOT created
DEBUG:thermomodel_None:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_None:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_None:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_None:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_None:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_None:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_None:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_None:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:PFOR : thermo constraint NOT created
DEBUG:thermomodel_None:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_None:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_None:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_None:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_None:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_None:OPAH : thermo constraint NOT created
DEBUG:thermomodel_None:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_None:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_None:CLtex : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_None:Ktu : thermo constraint NOT created
DEBUG:thermomodel_None:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_None:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_None:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_None:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_None:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_None:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_None:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_None:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:ABTA : thermo constraint NOT created
DEBUG:thermomodel_None:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_None:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_None:ACLS : thermo constraint NOT created
DEBUG:thermomodel_None:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_None:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_None:AGTi : thermo constraint NOT created
DEBUG:thermomodel_None:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_None:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_None:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_None:AMID : thermo constraint NOT created
DEBUG:thermomodel_None:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_None:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_None:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_None:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_None:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_None:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_None:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_None:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:COCHL : thermo constraint NOT created
DEBUG:thermomodel_None:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1bpp_syn : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_None:CYSS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_None:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_None:DPPS : thermo constraint NOT created
DEBUG:thermomodel_None:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_None:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_None:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_None:FNOR : thermo constraint NOT created
DEBUG:thermomodel_None:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_None:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PD : thermo constraint NOT created
DEBUG:thermomodel_None:G3PD1ir : thermo constraint NOT created
DEBUG:thermomodel_None:G6PBDH : thermo constraint NOT created
DEBUG:thermomodel_None:GCALDD : thermo constraint NOT created
DEBUG:thermomodel_None:GLBRAN2 : thermo constraint NOT created
DEBUG:thermomodel_None:GLCGLYCabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:GLCP : thermo constraint NOT created
DEBUG:thermomodel_None:GLCP2 : thermo constraint NOT created
DEBUG:thermomodel_None:GLCS1 : thermo constraint NOT created
DEBUG:thermomodel_None:GLMS_syn : thermo constraint NOT created
DEBUG:thermomodel_None:GLNTRAT : thermo constraint NOT created
DEBUG:thermomodel_None:GLUCYS : thermo constraint NOT created
DEBUG:thermomodel_None:GLUK_syn : thermo constraint NOT created
DEBUG:thermomodel_None:GLUSx : thermo constraint NOT created
DEBUG:thermomodel_None:GLUt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:GLXCL : thermo constraint NOT created
DEBUG:thermomodel_None:GLYALDDr : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCL_2 : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCTO1 : thermo constraint NOT created
DEBUG:thermomodel_None:GLYK : thermo constraint NOT created
DEBUG:thermomodel_None:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:GMPS : thermo constraint NOT created
DEBUG:thermomodel_None:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_None:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_None:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_None:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HOXG : thermo constraint NOT created
DEBUG:thermomodel_None:HPROa : thermo constraint NOT created
DEBUG:thermomodel_None:HPYRRx : thermo constraint NOT created
DEBUG:thermomodel_None:HSDxi : thermo constraint NOT created
DEBUG:thermomodel_None:IMACTD : thermo constraint NOT created
DEBUG:thermomodel_None:KARA2 : thermo constraint NOT created
DEBUG:thermomodel_None:LALDO : thermo constraint NOT created
DEBUG:thermomodel_None:LCARS : thermo constraint NOT created
DEBUG:thermomodel_None:LGTHL : thermo constraint NOT created
DEBUG:thermomodel_None:LYSDC : thermo constraint NOT created
DEBUG:thermomodel_None:LYSabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MAN1PT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDH : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDH_syn : thermo constraint NOT created
DEBUG:thermomodel_None:METS : thermo constraint NOT created
DEBUG:thermomodel_None:MI1PP : thermo constraint NOT created
DEBUG:thermomodel_None:MI1PS : thermo constraint NOT created
DEBUG:thermomodel_None:MNt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMC1 : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMOR : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMT : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFD2i : thermo constraint NOT created
DEBUG:thermomodel_None:NABTNO : thermo constraint NOT created
DEBUG:thermomodel_None:NADH5 : thermo constraint NOT created
DEBUG:thermomodel_None:NAR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_1p : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_1u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_2p : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_2u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_3u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_4pp : thermo constraint NOT created
DEBUG:thermomodel_None:NDH2_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK10 : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK9 : thermo constraint NOT created
DEBUG:thermomodel_None:NH4tpp_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NOR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NPHS : thermo constraint NOT created
DEBUG:thermomodel_None:NTD4 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP4 : thermo constraint NOT created
DEBUG:thermomodel_None:OPHBDC : thermo constraint NOT created
DEBUG:thermomodel_None:P5CD : thermo constraint NOT created
DEBUG:thermomodel_None:P5CRx : thermo constraint NOT created
DEBUG:thermomodel_None:PC17M : thermo constraint NOT created
DEBUG:thermomodel_None:PDHa : thermo constraint NOT created
DEBUG:thermomodel_None:PDHbr : thermo constraint NOT created
DEBUG:thermomodel_None:PDHcr : thermo constraint NOT created
DEBUG:thermomodel_None:PDX5PS : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA161 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA180 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA181 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:PHCD : thermo constraint NOT created
DEBUG:thermomodel_None:PHYTES2 : thermo constraint NOT created
DEBUG:thermomodel_None:POR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:POR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:PPC : thermo constraint NOT created
DEBUG:thermomodel_None:PPM : thermo constraint NOT created
DEBUG:thermomodel_None:PPNCL : thermo constraint NOT created
DEBUG:thermomodel_None:PPPGO : thermo constraint NOT created
DEBUG:thermomodel_None:PROD2 : thermo constraint NOT created
DEBUG:thermomodel_None:PROabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PUTA3 : thermo constraint NOT created
DEBUG:thermomodel_None:PYAM5PO : thermo constraint NOT created
DEBUG:thermomodel_None:PYDXNO : thermo constraint NOT created
DEBUG:thermomodel_None:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_None:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_None:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_None:RBCh : thermo constraint NOT created
DEBUG:thermomodel_None:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_None:RBPC : thermo constraint NOT created
DEBUG:thermomodel_None:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_None:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_None:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SPS : thermo constraint NOT created
DEBUG:thermomodel_None:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:SQLC : thermo constraint NOT created
DEBUG:thermomodel_None:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_None:SSALy : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_None:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_None:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_None:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_None:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_None:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_None:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_None:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_None:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_None:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_None:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_None:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_None:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_None:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_None:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_None:RNF : thermo constraint NOT created
DEBUG:thermomodel_None:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_None:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_None:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_None:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_None:2HESR : thermo constraint NOT created
DEBUG:thermomodel_None:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_None:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_None:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_None:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_None:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_None:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_None:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_None:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_None:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_None:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_None:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_None:ACALD : thermo constraint NOT created
DEBUG:thermomodel_None:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACNML : thermo constraint NOT created
DEBUG:thermomodel_None:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_None:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_None:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_None:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT140 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:ACt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADK3 : thermo constraint NOT created
DEBUG:thermomodel_None:ADK4 : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBIK : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBLtonex : thermo constraint NOT created
DEBUG:thermomodel_None:ADPRDP : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3PA : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3PApp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PA : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PApp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_None:AGMHE : thermo constraint NOT created
DEBUG:thermomodel_None:AGMt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:AGPR : thermo constraint NOT created
DEBUG:thermomodel_None:AGt3 : thermo constraint NOT created
DEBUG:thermomodel_None:AHGDx : thermo constraint NOT created
DEBUG:thermomodel_None:AI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_None:AKGt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALATA_L : thermo constraint NOT created
DEBUG:thermomodel_None:ALATA_L2 : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD19xr : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD3y : thermo constraint NOT created
DEBUG:thermomodel_None:ALKP : thermo constraint NOT created
DEBUG:thermomodel_None:ALLPI : thermo constraint NOT created
DEBUG:thermomodel_None:ALLTN : thermo constraint NOT created
DEBUG:thermomodel_None:ALLULPE : thermo constraint NOT created
DEBUG:thermomodel_None:ALLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALPATE160pp : thermo constraint NOT created
DEBUG:thermomodel_None:ALPATG160pp : thermo constraint NOT created
DEBUG:thermomodel_None:ALR2 : thermo constraint NOT created
DEBUG:thermomodel_None:ALR2x : thermo constraint NOT created
DEBUG:thermomodel_None:AM3PA : thermo constraint NOT created
DEBUG:thermomodel_None:AM4PA : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT1 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT3 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT4 : thermo constraint NOT created
DEBUG:thermomodel_None:AMMQLT8 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPMS2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPTASEPG : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT140 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:ARBTNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARBabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARGDC : thermo constraint NOT created
DEBUG:thermomodel_None:ARHGDx : thermo constraint NOT created
DEBUG:thermomodel_None:ARMEPNS : thermo constraint NOT created
DEBUG:thermomodel_None:ASCBptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO3 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO4 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPT : thermo constraint NOT created
DEBUG:thermomodel_None:ASPabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ASR : thermo constraint NOT created
DEBUG:thermomodel_None:ATHRDHr : thermo constraint NOT created
DEBUG:thermomodel_None:BETALDHx : thermo constraint NOT created
DEBUG:thermomodel_None:BETALDHy : thermo constraint NOT created
DEBUG:thermomodel_None:BGLA1 : thermo constraint NOT created
DEBUG:thermomodel_None:BMOCOS : thermo constraint NOT created
DEBUG:thermomodel_None:BMOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_None:BMOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_None:BTS5 : thermo constraint NOT created
DEBUG:thermomodel_None:BUTCT : thermo constraint NOT created
DEBUG:thermomodel_None:BUTSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOS : thermo constraint NOT created
DEBUG:thermomodel_None:CA2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:CBIAT : thermo constraint NOT created
DEBUG:thermomodel_None:CBItonex : thermo constraint NOT created
DEBUG:thermomodel_None:CBIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBL1abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBL1tonex : thermo constraint NOT created
DEBUG:thermomodel_None:CBLAT : thermo constraint NOT created
DEBUG:thermomodel_None:CD2abcpp : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_None:LIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:LIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:LIPOS : thermo constraint NOT created
DEBUG:thermomodel_None:LKDRA : thermo constraint NOT created
DEBUG:thermomodel_None:LPADSS : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A120pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A140pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A141pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A160pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A161pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A180pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1A181pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E120pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E140pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E141pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E160pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E161pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E180pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1E181pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G120pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G140pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G141pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G160pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G161pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G180pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL1G181pp : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G181 : thermo constraint NOT created
DEBUG:thermomodel_None:LSERDHr : thermo constraint NOT created
DEBUG:thermomodel_None:LYSAM : thermo constraint NOT created
DEBUG:thermomodel_None:L_LACD2 : thermo constraint NOT created
DEBUG:thermomodel_None:L_LACD3 : thermo constraint NOT created
DEBUG:thermomodel_None:MACPD : thermo constraint NOT created
DEBUG:thermomodel_None:MALDDH : thermo constraint NOT created
DEBUG:thermomodel_None:MALS : thermo constraint NOT created
DEBUG:thermomodel_None:MALTATr : thermo constraint NOT created
DEBUG:thermomodel_None:MALTHXabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MANGLYCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MANptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MCITL2 : thermo constraint NOT created
DEBUG:thermomodel_None:MCPST : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP1App : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP2App : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP4pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP5pp : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDH5 : thermo constraint NOT created
DEBUG:thermomodel_None:MEPNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:METDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:METNA : thermo constraint NOT created
DEBUG:thermomodel_None:METSOXR1 : thermo constraint NOT created
DEBUG:thermomodel_None:METSOXR2 : thermo constraint NOT created
DEBUG:thermomodel_None:METabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MG2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:MICITDr : thermo constraint NOT created
DEBUG:thermomodel_None:MINCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP1App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP2App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP2Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP3App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP2 : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP3 : thermo constraint NOT created
DEBUG:thermomodel_None:MMCD : thermo constraint NOT created
DEBUG:thermomodel_None:MMM : thermo constraint NOT created
DEBUG:thermomodel_None:MN2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MN2tipp : thermo constraint NOT created
DEBUG:thermomodel_None:MN6PP : thermo constraint NOT created
DEBUG:thermomodel_None:MNLptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MOADSUx : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_None:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_None:MPTS : thermo constraint NOT created
DEBUG:thermomodel_None:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_None:MSAR : thermo constraint NOT created
DEBUG:thermomodel_None:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADDP : thermo constraint NOT created
DEBUG:thermomodel_None:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_None:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_None:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_None:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_None:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_None:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_None:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_None:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_None:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_None:NODOx : thermo constraint NOT created
DEBUG:thermomodel_None:NODOy : thermo constraint NOT created
DEBUG:thermomodel_None:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP11 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP6 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP7 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP9 : thermo constraint NOT created
DEBUG:thermomodel_None:NTRIR2x : thermo constraint NOT created
DEBUG:thermomodel_None:O16A4COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:O16AT : thermo constraint NOT created
DEBUG:thermomodel_None:OBTFL : thermo constraint NOT created
DEBUG:thermomodel_None:OCTDPS : thermo constraint NOT created
DEBUG:thermomodel_None:OHPHM : thermo constraint NOT created
DEBUG:thermomodel_None:OMBZLM : thermo constraint NOT created
DEBUG:thermomodel_None:OMMBLHXy : thermo constraint NOT created
DEBUG:thermomodel_None:OMPHHXy : thermo constraint NOT created
DEBUG:thermomodel_None:OPHHXy : thermo constraint NOT created
DEBUG:thermomodel_None:ORNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OXCOAHDH : thermo constraint NOT created
DEBUG:thermomodel_None:OXDHCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:PA120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAE : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAL : thermo constraint NOT created
DEBUG:thermomodel_None:PACOAT : thermo constraint NOT created
DEBUG:thermomodel_None:PAI2I : thermo constraint NOT created
DEBUG:thermomodel_None:PAPSR2 : thermo constraint NOT created
DEBUG:thermomodel_None:PCNO : thermo constraint NOT created
DEBUG:thermomodel_None:PDE1 : thermo constraint NOT created
DEBUG:thermomodel_None:PDE4 : thermo constraint NOT created
DEBUG:thermomodel_None:PE120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PFK : thermo constraint NOT created
DEBUG:thermomodel_None:PFL : thermo constraint NOT created
DEBUG:thermomodel_None:PG120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA120 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA140 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA141 : thermo constraint NOT created
DEBUG:thermomodel_None:PHEMEabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PNSPA : thermo constraint NOT created
DEBUG:thermomodel_None:POAACR : thermo constraint NOT created
DEBUG:thermomodel_None:POR5 : thermo constraint NOT created
DEBUG:thermomodel_None:POX : thermo constraint NOT created
DEBUG:thermomodel_None:PPA2 : thermo constraint NOT created
DEBUG:thermomodel_None:PPAKr : thermo constraint NOT created
DEBUG:thermomodel_None:PPCK : thermo constraint NOT created
DEBUG:thermomodel_None:PPCSCT : thermo constraint NOT created
DEBUG:thermomodel_None:PPDOy : thermo constraint NOT created
DEBUG:thermomodel_None:PPGPPDP : thermo constraint NOT created
DEBUG:thermomodel_None:PPPNDO : thermo constraint NOT created
DEBUG:thermomodel_None:PPPNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PPTHpp : thermo constraint NOT created
DEBUG:thermomodel_None:PROD3 : thermo constraint NOT created
DEBUG:thermomodel_None:PROGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PROt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PSP_Lpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTA2 : thermo constraint NOT created
DEBUG:thermomodel_None:PTHRpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTRCTA : thermo constraint NOT created
DEBUG:thermomodel_None:PUACGAMS : thermo constraint NOT created
DEBUG:thermomodel_None:PUACGAMtr : thermo constraint NOT created
DEBUG:thermomodel_None:PYK6 : thermo constraint NOT created
DEBUG:thermomodel_None:PYROX : thermo constraint NOT created
DEBUG:thermomodel_None:QUINDH : thermo constraint NOT created
DEBUG:thermomodel_None:QUINDHyi : thermo constraint NOT created
DEBUG:thermomodel_None:R15BPK : thermo constraint NOT created
DEBUG:thermomodel_None:R5PP : thermo constraint NOT created
DEBUG:thermomodel_None:R5PPpp : thermo constraint NOT created
DEBUG:thermomodel_None:RBK : thermo constraint NOT created
DEBUG:thermomodel_None:REPHACCOAI : thermo constraint NOT created
DEBUG:thermomodel_None:RFAMPtpp : thermo constraint NOT created
DEBUG:thermomodel_None:RIBabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR1b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR2b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR3b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR4b : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR1c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR2c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR3c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR4c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RPNTPH : thermo constraint NOT created
DEBUG:thermomodel_None:RU5PP : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_None:S4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_None:S4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_None:SADT2 : thermo constraint NOT created
DEBUG:thermomodel_None:SBTPD : thermo constraint NOT created
DEBUG:thermomodel_None:SBTptspp : thermo constraint NOT created
DEBUG:thermomodel_None:SCYSDS : thermo constraint NOT created
DEBUG:thermomodel_None:SDPDS : thermo constraint NOT created
DEBUG:thermomodel_None:SELabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SGSAD : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHD2 : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHF : thermo constraint NOT created
DEBUG:thermomodel_None:SHSL1 : thermo constraint NOT created
DEBUG:thermomodel_None:SKMt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:SLNTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SOTA : thermo constraint NOT created
DEBUG:thermomodel_None:SPMDt3pp : thermo constraint NOT created
DEBUG:thermomodel_None:SSALx : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt2_2pp : thermo constraint NOT created
DEBUG:thermomodel_None:SUCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:SULFACabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SULR : thermo constraint NOT created
DEBUG:thermomodel_None:T2DECAI : thermo constraint NOT created
DEBUG:thermomodel_None:TALA : thermo constraint NOT created
DEBUG:thermomodel_None:TARTD : thermo constraint NOT created
DEBUG:thermomodel_None:TAURabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:TDPAGTA : thermo constraint NOT created
DEBUG:thermomodel_None:TDSK : thermo constraint NOT created
DEBUG:thermomodel_None:TGBPA : thermo constraint NOT created
DEBUG:thermomodel_None:THD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:THDPS : thermo constraint NOT created
DEBUG:thermomodel_None:THFAT : thermo constraint NOT created
DEBUG:thermomodel_None:THIORDXi : thermo constraint NOT created
DEBUG:thermomodel_None:THMabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:THRA : thermo constraint NOT created
DEBUG:thermomodel_None:THRA2 : thermo constraint NOT created
DEBUG:thermomodel_None:THRD : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_None:MMSAD2 : thermo constraint NOT created
DEBUG:thermomodel_None:MMSAD3 : thermo constraint NOT created
DEBUG:thermomodel_None:MNabc : thermo constraint NOT created
DEBUG:thermomodel_None:MOTH1 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTH2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTH3 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTH4 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS1 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS3 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS4 : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:MTI : thermo constraint NOT created
DEBUG:thermomodel_None:NADHDH : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHQR2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHQR3 : thermo constraint NOT created
DEBUG:thermomodel_None:NADS1 : thermo constraint NOT created
DEBUG:thermomodel_None:NAt3_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NFORGLUAH : thermo constraint NOT created
DEBUG:thermomodel_None:NH4t : thermo constraint NOT created
DEBUG:thermomodel_None:NIT1b_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD5pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTPTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:OCBT_1 : thermo constraint NOT created
DEBUG:thermomodel_None:OCOAT1 : thermo constraint NOT created
DEBUG:thermomodel_None:OOR3r : thermo constraint NOT created
DEBUG:thermomodel_None:OPHHX : thermo constraint NOT created
DEBUG:thermomodel_None:OXOAEL : thermo constraint NOT created
DEBUG:thermomodel_None:OXPTNDH : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAL3 : thermo constraint NOT created
DEBUG:thermomodel_None:PC : thermo constraint NOT created
DEBUG:thermomodel_None:PEPCK_re : thermo constraint NOT created
DEBUG:thermomodel_None:PGK_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC100 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC120 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC121 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC140 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC141 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC60 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC80 : thermo constraint NOT created
DEBUG:thermomodel_None:PIabc : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_None:POR : thermo constraint NOT created
DEBUG:thermomodel_None:PPA_1pp : thermo constraint NOT created
DEBUG:thermomodel_None:PPDK : thermo constraint NOT created
DEBUG:thermomodel_None:PPK2r : thermo constraint NOT created
DEBUG:thermomodel_None:PPKr : thermo constraint NOT created
DEBUG:thermomodel_None:PRDX : thermo constraint NOT created
DEBUG:thermomodel_None:PRFGS_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PSD160 : thermo constraint NOT created
DEBUG:thermomodel_None:PSD180 : thermo constraint NOT created
DEBUG:thermomodel_None:PSSA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PSSA180 : thermo constraint NOT created
DEBUG:thermomodel_None:QRr : thermo constraint NOT created
DEBUG:thermomodel_None:QUINtex : thermo constraint NOT created
DEBUG:thermomodel_None:RIBabc : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR1 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR3 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR4 : thermo constraint NOT created
DEBUG:thermomodel_None:S7PI : thermo constraint NOT created
DEBUG:thermomodel_None:SALCHS4abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SDPTAi : thermo constraint NOT created
DEBUG:thermomodel_None:SHSL2r : thermo constraint NOT created
DEBUG:thermomodel_None:SO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SUCBZT1 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCBZT2 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCabc : thermo constraint NOT created
DEBUG:thermomodel_None:SUCR : thermo constraint NOT created
DEBUG:thermomodel_None:SULabc : thermo constraint NOT created
DEBUG:thermomodel_None:THD2 : thermo constraint NOT created
DEBUG:thermomodel_None:THRA2i : thermo constraint NOT created
DEBUG:thermomodel_None:THRAi : thermo constraint NOT created
DEBUG:thermomodel_None:THRabc : thermo constraint NOT created
DEBUG:thermomodel_None:TMDPP : thermo constraint NOT created
DEBUG:thermomodel_None:TREabc : thermo constraint NOT created
DEBUG:thermomodel_None:TRPTA : thermo constraint NOT created
DEBUG:thermomodel_None:TSULabc : thermo constraint NOT created
DEBUG:thermomodel_None:TYRt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:USHD : thermo constraint NOT created
DEBUG:thermomodel_None:VALabc : thermo constraint NOT created
DEBUG:thermomodel_None:ZN2t4 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:4CMLCL_kt : thermo constraint NOT created
DEBUG:thermomodel_None:4HTHRK : thermo constraint NOT created
DEBUG:thermomodel_None:5CM2HMUDI : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAMPM : thermo constraint NOT created
DEBUG:thermomodel_None:AGMtex : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2ir : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD4 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD31_1 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD6 : thermo constraint NOT created
DEBUG:thermomodel_None:ALR3 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ANHGMtex : thermo constraint NOT created
DEBUG:thermomodel_None:APENTAMAH : thermo constraint NOT created
DEBUG:thermomodel_None:APTNAT : thermo constraint NOT created
DEBUG:thermomodel_None:ASO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:ASPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ATPHs : thermo constraint NOT created
DEBUG:thermomodel_None:BSCT : thermo constraint NOT created
DEBUG:thermomodel_None:BTS3r : thermo constraint NOT created
DEBUG:thermomodel_None:CITtex : thermo constraint NOT created
DEBUG:thermomodel_None:CLt3_2pp : thermo constraint NOT created
DEBUG:thermomodel_None:CMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:COALCDH : thermo constraint NOT created
DEBUG:thermomodel_None:CONFRLtex : thermo constraint NOT created
DEBUG:thermomodel_None:CONFRLtpp : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1a : thermo constraint NOT created
DEBUG:thermomodel_None:CYOO2pp : thermo constraint NOT created
DEBUG:thermomodel_None:DAMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DAPDA : thermo constraint NOT created
DEBUG:thermomodel_None:DCMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DGMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DGNSK : thermo constraint NOT created
DEBUG:thermomodel_None:DGSNtex : thermo constraint NOT created
DEBUG:thermomodel_None:DHNAOT : thermo constraint NOT created
DEBUG:thermomodel_None:DKMPPD3 : thermo constraint NOT created
DEBUG:thermomodel_None:DTMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ECOAH12 : thermo constraint NOT created
DEBUG:thermomodel_None:EDTXS2 : thermo constraint NOT created
DEBUG:thermomodel_None:ETOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_12ppd__S_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_2hxmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_3mb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_4hbz_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_4hphac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_agm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ala__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_amp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_anhgm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_arbt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_aso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_aso4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_asp__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_btoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_but_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_buts_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_butso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_bz_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cell4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cell500_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cellb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cgly_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cit_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_confrl_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dad_2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_damp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dca_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dcmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dcyt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dextrin_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dgmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dgsn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_drib_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dtmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_duri_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_enter_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_eths_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sulfac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tartr__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tartr__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_taur_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_thr__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tma_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tmao_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tol_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tre_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tsul_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_udcpo5_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ump_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_urate_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_val__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_vanln_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_xmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:FACOAL160 : thermo constraint NOT created
DEBUG:thermomodel_None:FALGTHLs : thermo constraint NOT created
DEBUG:thermomodel_None:FAS120 : thermo constraint NOT created
DEBUG:thermomodel_None:FAS200 : thermo constraint NOT created
DEBUG:thermomodel_None:FASC200ACP : thermo constraint NOT created
DEBUG:thermomodel_None:FCOAHA : thermo constraint NOT created
DEBUG:thermomodel_None:FOAMtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:FORAMD : thermo constraint NOT created
DEBUG:thermomodel_None:G3PCtex : thermo constraint NOT created
DEBUG:thermomodel_None:G3PItex : thermo constraint NOT created
DEBUG:thermomodel_None:G3PStex : thermo constraint NOT created
DEBUG:thermomodel_None:G6PI : thermo constraint NOT created
DEBUG:thermomodel_None:GCCb : thermo constraint NOT created
DEBUG:thermomodel_None:GCCc : thermo constraint NOT created
DEBUG:thermomodel_None:GLCTR4 : thermo constraint NOT created
DEBUG:thermomodel_None:GLXCBL : thermo constraint NOT created
DEBUG:thermomodel_None:GLYC2Ptex : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:GLYtex : thermo constraint NOT created
DEBUG:thermomodel_None:GMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA1 : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA3 : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA4 : thermo constraint NOT created
DEBUG:thermomodel_None:GTPHs : thermo constraint NOT created
DEBUG:thermomodel_None:H2CO3D : thermo constraint NOT created
DEBUG:thermomodel_None:H2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:HACD8i : thermo constraint NOT created
DEBUG:thermomodel_None:HACD9 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX4 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX7 : thermo constraint NOT created
DEBUG:thermomodel_None:HIStex : thermo constraint NOT created
DEBUG:thermomodel_None:HPAtex : thermo constraint NOT created
DEBUG:thermomodel_None:IMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:KAT1 : thermo constraint NOT created
DEBUG:thermomodel_None:LACD : thermo constraint NOT created
DEBUG:thermomodel_None:LCTStpp : thermo constraint NOT created
DEBUG:thermomodel_None:LPD5 : thermo constraint NOT created
DEBUG:thermomodel_None:LYSMO : thermo constraint NOT created
DEBUG:thermomodel_None:MACCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP2ex : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP3ex : thermo constraint NOT created
DEBUG:thermomodel_None:MELIBt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:METOX1s : thermo constraint NOT created
DEBUG:thermomodel_None:METOX2s : thermo constraint NOT created
DEBUG:thermomodel_None:METtex : thermo constraint NOT created
DEBUG:thermomodel_None:MGSA : thermo constraint NOT created
DEBUG:thermomodel_None:MMTSAO : thermo constraint NOT created
DEBUG:thermomodel_None:MOSDC : thermo constraint NOT created
DEBUG:thermomodel_None:MPTAT : thermo constraint NOT created
DEBUG:thermomodel_None:MUCCY_kt : thermo constraint NOT created
DEBUG:thermomodel_None:N2trpp : thermo constraint NOT created
DEBUG:thermomodel_None:NH3c : thermo constraint NOT created
DEBUG:thermomodel_None:NMNAT : thermo constraint NOT created
DEBUG:thermomodel_None:NMNR : thermo constraint NOT created
DEBUG:thermomodel_None:NOVBCNtex : thermo constraint NOT created
DEBUG:thermomodel_None:NT5C : thermo constraint NOT created
DEBUG:thermomodel_None:NTD10pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD11pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD3pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD6pp : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B
Warning : BO3/B

Streaming output truncated to the last 5000 lines.
DEBUG:thermomodel_None:Added constraint: UF_MDDCP1ex
DEBUG:thermomodel_None:Added constraint: UR_MDDCP1ex
DEBUG:thermomodel_None:generating only use constraints for reactionMDDCP4ex
DEBUG:thermomodel_None:Added variable: FU_MDDCP4ex
DEBUG:thermomodel_None:Added variable: BU_MDDCP4ex
DEBUG:thermomodel_None:Added constraint: SU_MDDCP4ex
DEBUG:thermomodel_None:Added constraint: UF_MDDCP4ex
DEBUG:thermomodel_None:Added constraint: UR_MDDCP4ex
DEBUG:thermomodel_None:generating only use constraints for reactionMDDCP5ex
DEBUG:thermomodel_None:Added variable: FU_MDDCP5ex
DEBUG:thermomodel_None:Added variable: BU_MDDCP5ex
DEBUG:thermomodel_None:Added constraint: SU_MDDCP5ex
DEBUG:thermomodel_None:Added constraint: UF_MDDCP5ex
DEBUG:thermomodel_None:Added constraint: UR_MDDCP5ex
DEBUG:thermomodel_None:generating only use constraints for reactionMETabc
DEBUG:thermomodel_None:Added variable: FU_METabc
DEBUG:thermomodel_None:Added variable: BU_METabc
DEBUG:thermomodel_None:Added constraint: SU_METabc
DEBUG:thermomodel_None:Added constraint: UF_METabc
DEBUG:thermomodel_None:Added constraint: UR_METabc
DEBUG:thermomodel_None:generating only use constraints for reactionMGt5
DEBUG:thermomodel_None:Added variable: FU_MGt5
DEBUG:thermomodel_None:Added variable: BU_MGt5
DEBUG:thermomodel_None:Added constraint: SU_MGt5
DEBUG:thermomodel_None:Added constraint: UF_MGt5
DEBUG:thermomodel_None:Added constraint: UR_MGt5
DEBUG:thermomodel_None:generating only use constraints for reactionMLTG1
DEBUG:thermomodel_None:Added variable: FU_MLTG1
DEBUG:thermomodel_None:Added variable: BU_MLTG1
DEBUG:thermomodel_None:Added constraint: SU_MLTG1
DEBUG:thermomodel_None:Added constraint: UF_MLTG1
DEBUG:thermomodel_None:Added constraint: UR_MLTG1
DEBUG:thermomodel_None:generating only use constraints for reactionMLTG3
DEBUG:thermomodel_None:Added variable: FU_MLTG3
DEBUG:thermomodel_None:Added variable: BU_MLTG3
DEBUG:thermomodel_None:Added constraint: SU_MLTG3
DEBUG:thermomodel_None:Added constraint: UF_MLTG3
DEBUG:thermomodel_None:Added constraint: UR_MLTG3
DEBUG:thermomodel_None:generating only use constraints for reactionMLTG5
DEBUG:thermomodel_None:Added variable: FU_MLTG5
DEBUG:thermomodel_None:Added variable: BU_MLTG5
DEBUG:thermomodel_None:Added constraint: SU_MLTG5
DEBUG:thermomodel_None:Added constraint: UF_MLTG5
DEBUG:thermomodel_None:Added constraint: UR_MLTG5
DEBUG:thermomodel_None:generating only use constraints for reactionMME
DEBUG:thermomodel_None:Added variable: FU_MME
DEBUG:thermomodel_None:Added variable: BU_MME
DEBUG:thermomodel_None:Added constraint: SU_MME
DEBUG:thermomodel_None:Added constraint: UF_MME
DEBUG:thermomodel_None:Added constraint: UR_MME
DEBUG:thermomodel_None:generating only use constraints for reactionMMM2
DEBUG:thermomodel_None:Added variable: FU_MMM2
DEBUG:thermomodel_None:Added variable: BU_MMM2
DEBUG:thermomodel_None:Added constraint: SU_MMM2
DEBUG:thermomodel_None:Added constraint: UF_MMM2
DEBUG:thermomodel_None:Added constraint: UR_MMM2
DEBUG:thermomodel_None:generating only use constraints for reactionMMSAD2
DEBUG:thermomodel_None:Added variable: FU_MMSAD2
DEBUG:thermomodel_None:Added variable: BU_MMSAD2
DEBUG:thermomodel_None:Added constraint: SU_MMSAD2
DEBUG:thermomodel_None:Added constraint: UF_MMSAD2
DEBUG:thermomodel_None:Added constraint: UR_MMSAD2
DEBUG:thermomodel_None:generating only use constraints for reactionMMSAD3
DEBUG:thermomodel_None:Added variable: FU_MMSAD3
DEBUG:thermomodel_None:Added variable: BU_MMSAD3
DEBUG:thermomodel_None:Added constraint: SU_MMSAD3
DEBUG:thermomodel_None:Added constraint: UF_MMSAD3
DEBUG:thermomodel_None:Added constraint: UR_MMSAD3
DEBUG:thermomodel_None:generating only use constraints for reactionMNabc
DEBUG:thermomodel_None:Added variable: FU_MNabc
DEBUG:thermomodel_None:Added variable: BU_MNabc
DEBUG:thermomodel_None:Added constraint: SU_MNabc
DEBUG:thermomodel_None:Added constraint: UF_MNabc
DEBUG:thermomodel_None:Added constraint: UR_MNabc
DEBUG:thermomodel_None:generating only use constraints for reactionMOTH1
DEBUG:thermomodel_None:Added variable: FU_MOTH1
DEBUG:thermomodel_None:Added variable: BU_MOTH1
DEBUG:thermomodel_None:Added constraint: SU_MOTH1
DEBUG:thermomodel_None:Added constraint: UF_MOTH1
DEBUG:thermomodel_None:Added constraint: UR_MOTH1
DEBUG:thermomodel_None:generating only use constraints for reactionMOTH2
DEBUG:thermomodel_None:Added variable: FU_MOTH2
DEBUG:thermomodel_None:Added variable: BU_MOTH2
DEBUG:thermomodel_None:Added constraint: SU_MOTH2
DEBUG:thermomodel_None:Added constraint: UF_MOTH2
DEBUG:thermomodel_None:Added constraint: UR_MOTH2
DEBUG:thermomodel_None:generating only use constraints for reactionMOTH3
DEBUG:thermomodel_None:Added variable: FU_MOTH3
DEBUG:thermomodel_None:Added variable: BU_MOTH3
DEBUG:thermomodel_None:Added constraint: SU_MOTH3
DEBUG:thermomodel_None:Added constraint: UF_MOTH3
DEBUG:thermomodel_None:Added constraint: UR_MOTH3
DEBUG:thermomodel_None:generating only use constraints for reactionMOTH4
DEBUG:thermomodel_None:Added variable: FU_MOTH4
DEBUG:thermomodel_None:Added variable: BU_MOTH4
DEBUG:thermomodel_None:Added constraint: SU_MOTH4
DEBUG:thermomodel_None:Added constraint: UF_MOTH4
DEBUG:thermomodel_None:Added constraint: UR_MOTH4
DEBUG:thermomodel_None:generating only use constraints for reactionMOTS1
DEBUG:thermomodel_None:Added variable: FU_MOTS1
DEBUG:thermomodel_None:Added variable: BU_MOTS1
DEBUG:thermomodel_None:Added constraint: SU_MOTS1
DEBUG:thermomodel_None:Added constraint: UF_MOTS1
DEBUG:thermomodel_None:Added constraint: UR_MOTS1
DEBUG:thermomodel_None:generating only use constraints for reactionMOTS2
DEBUG:thermomodel_None:Added variable: FU_MOTS2
DEBUG:thermomodel_None:Added variable: BU_MOTS2
DEBUG:thermomodel_None:Added constraint: SU_MOTS2
DEBUG:thermomodel_None:Added constraint: UF_MOTS2
DEBUG:thermomodel_None:Added constraint: UR_MOTS2
DEBUG:thermomodel_None:generating only use constraints for reactionMOTS3
DEBUG:thermomodel_None:Added variable: FU_MOTS3
DEBUG:thermomodel_None:Added variable: BU_MOTS3
DEBUG:thermomodel_None:Added constraint: SU_MOTS3
DEBUG:thermomodel_None:Added constraint: UF_MOTS3
DEBUG:thermomodel_None:Added constraint: UR_MOTS3
DEBUG:thermomodel_None:generating only use constraints for reactionMOTS4
DEBUG:thermomodel_None:Added variable: FU_MOTS4
DEBUG:thermomodel_None:Added variable: BU_MOTS4
DEBUG:thermomodel_None:Added constraint: SU_MOTS4
DEBUG:thermomodel_None:Added constraint: UF_MOTS4
DEBUG:thermomodel_None:Added constraint: UR_MOTS4
DEBUG:thermomodel_None:generating only use constraints for reactionMTHFR2_1
DEBUG:thermomodel_None:Added variable: FU_MTHFR2_1
DEBUG:thermomodel_None:Added variable: BU_MTHFR2_1
DEBUG:thermomodel_None:Added constraint: SU_MTHFR2_1
DEBUG:thermomodel_None:Added constraint: UF_MTHFR2_1
DEBUG:thermomodel_None:Added constraint: UR_MTHFR2_1
DEBUG:thermomodel_None:generating only use constraints for reactionMTI
DEBUG:thermomodel_None:Added variable: FU_MTI
DEBUG:thermomodel_None:Added variable: BU_MTI
DEBUG:thermomodel_None:Added constraint: SU_MTI
DEBUG:thermomodel_None:Added constraint: UF_MTI
DEBUG:thermomodel_None:Added constraint: UR_MTI
DEBUG:thermomodel_None:generating only use constraints for reactionNADHDH
DEBUG:thermomodel_None:Added variable: FU_NADHDH
DEBUG:thermomodel_None:Added variable: BU_NADHDH
DEBUG:thermomodel_None:Added constraint: SU_NADHDH
DEBUG:thermomodel_None:Added constraint: UF_NADHDH
DEBUG:thermomodel_None:Added constraint: UR_NADHDH
DEBUG:thermomodel_None:generating only use constraints for reactionNADPHQR2
DEBUG:thermomodel_None:Added variable: FU_NADPHQR2
DEBUG:thermomodel_None:Added variable: BU_NADPHQR2
DEBUG:thermomodel_None:Added constraint: SU_NADPHQR2
DEBUG:thermomodel_None:Added constraint: UF_NADPHQR2
DEBUG:thermomodel_None:Added constraint: UR_NADPHQR2
DEBUG:thermomodel_None:generating only use constraints for reactionNADPHQR3
DEBUG:thermomodel_None:Added variable: FU_NADPHQR3
DEBUG:thermomodel_None:Added variable: BU_NADPHQR3
DEBUG:thermomodel_None:Added constraint: SU_NADPHQR3
DEBUG:thermomodel_None:Added constraint: UF_NADPHQR3
DEBUG:thermomodel_None:Added constraint: UR_NADPHQR3
DEBUG:thermomodel_None:generating only use constraints for reactionNADS1
DEBUG:thermomodel_None:Added variable: FU_NADS1
DEBUG:thermomodel_None:Added variable: BU_NADS1
DEBUG:thermomodel_None:Added constraint: SU_NADS1
DEBUG:thermomodel_None:Added constraint: UF_NADS1
DEBUG:thermomodel_None:Added constraint: UR_NADS1
DEBUG:thermomodel_None:generating only use constraints for reactionNAt3_1
DEBUG:thermomodel_None:Added variable: FU_NAt3_1
DEBUG:thermomodel_None:Added variable: BU_NAt3_1
DEBUG:thermomodel_None:Added constraint: SU_NAt3_1
DEBUG:thermomodel_None:Added constraint: UF_NAt3_1
DEBUG:thermomodel_None:Added constraint: UR_NAt3_1
DEBUG:thermomodel_None:generating only use constraints for reactionNFORGLUAH
DEBUG:thermomodel_None:Added variable: FU_NFORGLUAH
DEBUG:thermomodel_None:Added variable: BU_NFORGLUAH
DEBUG:thermomodel_None:Added constraint: SU_NFORGLUAH
DEBUG:thermomodel_None:Added constraint: UF_NFORGLUAH
DEBUG:thermomodel_None:Added constraint: UR_NFORGLUAH
DEBUG:thermomodel_None:generating only use constraints for reactionNH4t
DEBUG:thermomodel_None:Added variable: FU_NH4t
DEBUG:thermomodel_None:Added variable: BU_NH4t
DEBUG:thermomodel_None:Added constraint: SU_NH4t
DEBUG:thermomodel_None:Added constraint: UF_NH4t
DEBUG:thermomodel_None:Added constraint: UR_NH4t
DEBUG:thermomodel_None:generating only use constraints for reactionNIT1b_1
DEBUG:thermomodel_None:Added variable: FU_NIT1b_1
DEBUG:thermomodel_None:Added variable: BU_NIT1b_1
DEBUG:thermomodel_None:Added constraint: SU_NIT1b_1
DEBUG:thermomodel_None:Added constraint: UF_NIT1b_1
DEBUG:thermomodel_None:Added constraint: UR_NIT1b_1
DEBUG:thermomodel_None:generating only use constraints for reactionNTD5pp
DEBUG:thermomodel_None:Added variable: FU_NTD5pp
DEBUG:thermomodel_None:Added variable: BU_NTD5pp
DEBUG:thermomodel_None:Added constraint: SU_NTD5pp
DEBUG:thermomodel_None:Added constraint: UF_NTD5pp
DEBUG:thermomodel_None:Added constraint: UR_NTD5pp
DEBUG:thermomodel_None:generating only use constraints for reactionNTPTP1
DEBUG:thermomodel_None:Added variable: FU_NTPTP1
DEBUG:thermomodel_None:Added variable: BU_NTPTP1
DEBUG:thermomodel_None:Added constraint: SU_NTPTP1
DEBUG:thermomodel_None:Added constraint: UF_NTPTP1
DEBUG:thermomodel_None:Added constraint: UR_NTPTP1
DEBUG:thermomodel_None:generating only use constraints for reactionOCBT_1
DEBUG:thermomodel_None:Added variable: FU_OCBT_1
DEBUG:thermomodel_None:Added variable: BU_OCBT_1
DEBUG:thermomodel_None:Added constraint: SU_OCBT_1
DEBUG:thermomodel_None:Added constraint: UF_OCBT_1
DEBUG:thermomodel_None:Added constraint: UR_OCBT_1
DEBUG:thermomodel_None:generating only use constraints for reactionOCOAT1
DEBUG:thermomodel_None:Added variable: FU_OCOAT1
DEBUG:thermomodel_None:Added variable: BU_OCOAT1
DEBUG:thermomodel_None:Added constraint: SU_OCOAT1
DEBUG:thermomodel_None:Added constraint: UF_OCOAT1
DEBUG:thermomodel_None:Added constraint: UR_OCOAT1
DEBUG:thermomodel_None:generating only use constraints for reactionOOR3r
DEBUG:thermomodel_None:Added variable: FU_OOR3r
DEBUG:thermomodel_None:Added variable: BU_OOR3r
DEBUG:thermomodel_None:Added constraint: SU_OOR3r
DEBUG:thermomodel_None:Added constraint: UF_OOR3r
DEBUG:thermomodel_None:Added constraint: UR_OOR3r
DEBUG:thermomodel_None:generating only use constraints for reactionOPHHX
DEBUG:thermomodel_None:Added variable: FU_OPHHX
DEBUG:thermomodel_None:Added variable: BU_OPHHX
DEBUG:thermomodel_None:Added constraint: SU_OPHHX
DEBUG:thermomodel_None:Added constraint: UF_OPHHX
DEBUG:thermomodel_None:Added constraint: UR_OPHHX
DEBUG:thermomodel_None:generating only use constraints for reactionOXOAEL
DEBUG:thermomodel_None:Added variable: FU_OXOAEL
DEBUG:thermomodel_None:Added variable: BU_OXOAEL
DEBUG:thermomodel_None:Added constraint: SU_OXOAEL
DEBUG:thermomodel_None:Added constraint: UF_OXOAEL
DEBUG:thermomodel_None:Added constraint: UR_OXOAEL
DEBUG:thermomodel_None:generating only use constraints for reactionOXPTNDH
DEBUG:thermomodel_None:Added variable: FU_OXPTNDH
DEBUG:thermomodel_None:Added variable: BU_OXPTNDH
DEBUG:thermomodel_None:Added constraint: SU_OXPTNDH
DEBUG:thermomodel_None:Added constraint: UF_OXPTNDH
DEBUG:thermomodel_None:Added constraint: UR_OXPTNDH
DEBUG:thermomodel_None:generating only use constraints for reactionPACCOAL3
DEBUG:thermomodel_None:Added variable: FU_PACCOAL3
DEBUG:thermomodel_None:Added variable: BU_PACCOAL3
DEBUG:thermomodel_None:Added constraint: SU_PACCOAL3
DEBUG:thermomodel_None:Added constraint: UF_PACCOAL3
DEBUG:thermomodel_None:Added constraint: UR_PACCOAL3
DEBUG:thermomodel_None:generating only use constraints for reactionPC
DEBUG:thermomodel_None:Added variable: FU_PC
DEBUG:thermomodel_None:Added variable: BU_PC
DEBUG:thermomodel_None:Added constraint: SU_PC
DEBUG:thermomodel_None:Added constraint: UF_PC
DEBUG:thermomodel_None:Added constraint: UR_PC
DEBUG:thermomodel_None:generating only use constraints for reactionPEPCK_re
DEBUG:thermomodel_None:Added variable: FU_PEPCK_re
DEBUG:thermomodel_None:Added variable: BU_PEPCK_re
DEBUG:thermomodel_None:Added constraint: SU_PEPCK_re
DEBUG:thermomodel_None:Added constraint: UF_PEPCK_re
DEBUG:thermomodel_None:Added constraint: UR_PEPCK_re
DEBUG:thermomodel_None:generating only use constraints for reactionPGK_1
DEBUG:thermomodel_None:Added variable: FU_PGK_1
DEBUG:thermomodel_None:Added variable: BU_PGK_1
DEBUG:thermomodel_None:Added constraint: SU_PGK_1
DEBUG:thermomodel_None:Added constraint: UF_PGK_1
DEBUG:thermomodel_None:Added constraint: UR_PGK_1
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC100
DEBUG:thermomodel_None:Added variable: FU_PHAPC100
DEBUG:thermomodel_None:Added variable: BU_PHAPC100
DEBUG:thermomodel_None:Added constraint: SU_PHAPC100
DEBUG:thermomodel_None:Added constraint: UF_PHAPC100
DEBUG:thermomodel_None:Added constraint: UR_PHAPC100
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC120
DEBUG:thermomodel_None:Added variable: FU_PHAPC120
DEBUG:thermomodel_None:Added variable: BU_PHAPC120
DEBUG:thermomodel_None:Added constraint: SU_PHAPC120
DEBUG:thermomodel_None:Added constraint: UF_PHAPC120
DEBUG:thermomodel_None:Added constraint: UR_PHAPC120
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC121
DEBUG:thermomodel_None:Added variable: FU_PHAPC121
DEBUG:thermomodel_None:Added variable: BU_PHAPC121
DEBUG:thermomodel_None:Added constraint: SU_PHAPC121
DEBUG:thermomodel_None:Added constraint: UF_PHAPC121
DEBUG:thermomodel_None:Added constraint: UR_PHAPC121
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC140
DEBUG:thermomodel_None:Added variable: FU_PHAPC140
DEBUG:thermomodel_None:Added variable: BU_PHAPC140
DEBUG:thermomodel_None:Added constraint: SU_PHAPC140
DEBUG:thermomodel_None:Added constraint: UF_PHAPC140
DEBUG:thermomodel_None:Added constraint: UR_PHAPC140
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC141
DEBUG:thermomodel_None:Added variable: FU_PHAPC141
DEBUG:thermomodel_None:Added variable: BU_PHAPC141
DEBUG:thermomodel_None:Added constraint: SU_PHAPC141
DEBUG:thermomodel_None:Added constraint: UF_PHAPC141
DEBUG:thermomodel_None:Added constraint: UR_PHAPC141
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC60
DEBUG:thermomodel_None:Added variable: FU_PHAPC60
DEBUG:thermomodel_None:Added variable: BU_PHAPC60
DEBUG:thermomodel_None:Added constraint: SU_PHAPC60
DEBUG:thermomodel_None:Added constraint: UF_PHAPC60
DEBUG:thermomodel_None:Added constraint: UR_PHAPC60
DEBUG:thermomodel_None:generating only use constraints for reactionPHAPC80
DEBUG:thermomodel_None:Added variable: FU_PHAPC80
DEBUG:thermomodel_None:Added variable: BU_PHAPC80
DEBUG:thermomodel_None:Added constraint: SU_PHAPC80
DEBUG:thermomodel_None:Added constraint: UF_PHAPC80
DEBUG:thermomodel_None:Added constraint: UR_PHAPC80
DEBUG:thermomodel_None:generating only use constraints for reactionPIabc
DEBUG:thermomodel_None:Added variable: FU_PIabc
DEBUG:thermomodel_None:Added variable: BU_PIabc
DEBUG:thermomodel_None:Added constraint: SU_PIabc
DEBUG:thermomodel_None:Added constraint: UF_PIabc
DEBUG:thermomodel_None:Added constraint: UR_PIabc
DEBUG:thermomodel_None:generating only use constraints for reactionPIt2r
DEBUG:thermomodel_None:Added variable: FU_PIt2r
DEBUG:thermomodel_None:Added variable: BU_PIt2r
DEBUG:thermomodel_None:Added constraint: SU_PIt2r
DEBUG:thermomodel_None:Added constraint: UF_PIt2r
DEBUG:thermomodel_None:Added constraint: UR_PIt2r
DEBUG:thermomodel_None:generating only use constraints for reactionPOR
DEBUG:thermomodel_None:Added variable: FU_POR
DEBUG:thermomodel_None:Added variable: BU_POR
DEBUG:thermomodel_None:Added constraint: SU_POR
DEBUG:thermomodel_None:Added constraint: UF_POR
DEBUG:thermomodel_None:Added constraint: UR_POR
DEBUG:thermomodel_None:generating only use constraints for reactionPPA_1pp
DEBUG:thermomodel_None:Added variable: FU_PPA_1pp
DEBUG:thermomodel_None:Added variable: BU_PPA_1pp
DEBUG:thermomodel_None:Added constraint: SU_PPA_1pp
DEBUG:thermomodel_None:Added constraint: UF_PPA_1pp
DEBUG:thermomodel_None:Added constraint: UR_PPA_1pp
DEBUG:thermomodel_None:generating only use constraints for reactionPPDK
DEBUG:thermomodel_None:Added variable: FU_PPDK
DEBUG:thermomodel_None:Added variable: BU_PPDK
DEBUG:thermomodel_None:Added constraint: SU_PPDK
DEBUG:thermomodel_None:Added constraint: UF_PPDK
DEBUG:thermomodel_None:Added constraint: UR_PPDK
DEBUG:thermomodel_None:generating only use constraints for reactionPPK2r
DEBUG:thermomodel_None:Added variable: FU_PPK2r
DEBUG:thermomodel_None:Added variable: BU_PPK2r
DEBUG:thermomodel_None:Added constraint: SU_PPK2r
DEBUG:thermomodel_None:Added constraint: UF_PPK2r
DEBUG:thermomodel_None:Added constraint: UR_PPK2r
DEBUG:thermomodel_None:generating only use constraints for reactionPPKr
DEBUG:thermomodel_None:Added variable: FU_PPKr
DEBUG:thermomodel_None:Added variable: BU_PPKr
DEBUG:thermomodel_None:Added constraint: SU_PPKr
DEBUG:thermomodel_None:Added constraint: UF_PPKr
DEBUG:thermomodel_None:Added constraint: UR_PPKr
DEBUG:thermomodel_None:generating only use constraints for reactionPRDX
DEBUG:thermomodel_None:Added variable: FU_PRDX
DEBUG:thermomodel_None:Added variable: BU_PRDX
DEBUG:thermomodel_None:Added constraint: SU_PRDX
DEBUG:thermomodel_None:Added constraint: UF_PRDX
DEBUG:thermomodel_None:Added constraint: UR_PRDX
DEBUG:thermomodel_None:generating only use constraints for reactionPRFGS_1
DEBUG:thermomodel_None:Added variable: FU_PRFGS_1
DEBUG:thermomodel_None:Added variable: BU_PRFGS_1
DEBUG:thermomodel_None:Added constraint: SU_PRFGS_1
DEBUG:thermomodel_None:Added constraint: UF_PRFGS_1
DEBUG:thermomodel_None:Added constraint: UR_PRFGS_1
DEBUG:thermomodel_None:generating only use constraints for reactionPSD160
DEBUG:thermomodel_None:Added variable: FU_PSD160
DEBUG:thermomodel_None:Added variable: BU_PSD160
DEBUG:thermomodel_None:Added constraint: SU_PSD160
DEBUG:thermomodel_None:Added constraint: UF_PSD160
DEBUG:thermomodel_None:Added constraint: UR_PSD160
DEBUG:thermomodel_None:generating only use constraints for reactionPSD180
DEBUG:thermomodel_None:Added variable: FU_PSD180
DEBUG:thermomodel_None:Added variable: BU_PSD180
DEBUG:thermomodel_None:Added constraint: SU_PSD180
DEBUG:thermomodel_None:Added constraint: UF_PSD180
DEBUG:thermomodel_None:Added constraint: UR_PSD180
DEBUG:thermomodel_None:generating only use constraints for reactionPSSA160
DEBUG:thermomodel_None:Added variable: FU_PSSA160
DEBUG:thermomodel_None:Added variable: BU_PSSA160
DEBUG:thermomodel_None:Added constraint: SU_PSSA160
DEBUG:thermomodel_None:Added constraint: UF_PSSA160
DEBUG:thermomodel_None:Added constraint: UR_PSSA160
DEBUG:thermomodel_None:generating only use constraints for reactionPSSA180

Total variables: 13010
Total constraints: 10290
Number of ΔG variables: 142
['CDGS', 'CDGS_reverse_6b7cb', 'CDGR', 'CDGR_reverse_e4464', 'SQDGS_PALM_PALM', 'SQDGS_PALM_PALM_reverse_eec5a', 'SQDGS_HDE_PALM', 'SQDGS_HDE_PALM_reverse_af549', 'DGDGS_HDE_PALM', 'DGDGS_HDE_PALM_reverse_d95be']
Binary variables: 5442
['FU_QULNS', 'BU_QULNS', 'FU_ORNDC', 'BU_ORNDC', 'FU_MSBENZMT', 'BU_MSBENZMT', 'FU_DESAT18a', 'BU_DESAT18a', 'FU_FUM', 'BU_FUM']
Metabolite concentration variables: 2125
['SQLC_reverse_77a98', 'LC_gam6p_c', 'LC_cgly_c', 'LC_achms_c', 'LC_pcox_u', 'LC_octe9ACP_c', 'LC_fdp_c', 'LC_5caiz_c', 'LC_pep_c', 'LC_coa_c']

In [ ]:
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]


print("\n---- Thermodynamic constraints for PHB reactions ----")

for r_id in PHB_REACTIONS:

    dg_var = f"DG_{r_id}"
    fu_var = f"FU_{r_id}"
    bu_var = f"BU_{r_id}"

    has_dg = dg_var in mytfa.variables
    has_binary = fu_var in mytfa.variables or bu_var in mytfa.variables

    print(
        f"{r_id:12s}",
        "✅ thermo" if has_dg else "❌ no thermo",
        "| binary:" if has_binary else "| no direction vars"
    )

In [ ]:
assert any(c.name.startswith("G_") for c in mytfa.constraints)
assert any(v.name.startswith("DGo_") for v in mytfa.variables)
assert any(v.type == "binary" for v in mytfa.variables)
print("✅ TFBA is active")

# *Multiple points TFA V4.2  

This version handles multiple PHBS_syn_UB and data CatBoost modelling strategies

In [ ]:
# ============================================================
# USER PARAMETERS
# ============================================================

logging.getLogger("thermomodel_None").setLevel(logging.ERROR)
logging.getLogger("pytfa").setLevel(logging.ERROR)

PHB_SYN_UB_VALUES =  [0.3978] #, 1000
# ============================================================
# CONSTANTS
# ============================================================
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

SUB_TO_RXN_BASE = {
    "ace": "EX_ac_e",
    "lac": "EX_lac__L_e",
    "ppa": "EX_ppa_e",
    "but": "EX_but_e",
    "ibt": "EX_ibt_e",
    "mal": "EX_mal__L_e",
    "hxa": "EX_hxa_e",
    "oct": "EX_octa_e",
    "nh4": "EX_nh4_e",
    "hco3": "EX_hco3_e",
}

EXCHANGE_RXNS = list(SUB_TO_RXN_BASE.values())

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True


# ============================================================
# LOAD TFA METADATA (ONCE)
# ============================================================
lexicon = read_lexicon(str(lexicon_path))
comp_data = read_compartment_data(str(compartments_path))


# ============================================================
# MAIN LOOP
# ============================================================
for PHB_SYN_UB in PHB_SYN_UB_VALUES:

    print("\n==============================")
    print(f"PHB_SYN_UB_VALUE: {PHB_SYN_UB}")
    print("==============================")

    PHB_SYN_TAG = f"{PHB_SYN_UB:g}"

    INPUT_CSV = PHB_PARETO_DIR / f"03_pareto_best_all_strategies_{PHB_SYN_TAG}.csv"
    OUT_CSV = PHB_TFA_DIR / f"05_FBA_TFA_PFBA_detailed_results_all_strategies_{PHB_SYN_TAG}.csv"

    df = pd.read_csv(INPUT_CSV)
    results = []

    for pareto_id, row in df.iterrows():

        strategy = row["optimization_strategy"]

        if "SUP" in strategy:
            suffix = "_sup"

        elif strategy == "CON":
            suffix = "_con"

        elif strategy == "SUP_and_CON":
            suffix = "_sup"

        elif strategy == "PFBA":
            suffix = "_con_pfba"

        elif strategy == "SUP_and_PFBA":
            suffix = "_sup"

        else:
            print('Other optimization strategy')

        m = model_constrained.copy()

        # ---------------------------------
        # STORE INPUT VALUES USED
        # ---------------------------------
        input_values_used = {}

        for base_col, rxn_id in SUB_TO_RXN_BASE.items():

            col_name = f"{base_col}{suffix}"
            val_used = np.nan

            if col_name in row:
                val = row[col_name]
                if pd.notna(val) and float(val) != 0.0 and rxn_id in m.reactions:
                    rxn = m.reactions.get_by_id(rxn_id)
                    rxn.lower_bound = -abs(float(val))
                    rxn.upper_bound = 0.0
                    val_used = float(val)

            input_values_used[f"{base_col}_supplied"] = 0.0 if pd.isna(val_used) else val_used

        # ---------------------------------
        # OBJECTIVE & NO GROWTH
        # ---------------------------------
        phb_rxn = m.reactions.get_by_id("PHBS_syn")
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = PHB_SYN_UB
        m.objective = phb_rxn

        biomass = m.reactions.get_by_id("BIOMASS__1")
        biomass.lower_bound = 0.0
        biomass.upper_bound = 0.0

        apply_solver_settings(m)

        # ---------------------------------
        # FBA
        # ---------------------------------
        fba_sol = m.optimize()

        # ---------------------------------
        # pFBA
        # ---------------------------------

        pfba_sol = pfba(m)

        # ---------------------------------
        # TFA
        # ---------------------------------
        # Build ThermoModel
        mytfa = pytfa.ThermoModel(thermo_data, m.copy())

        # Apply annotations
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)

        # Set objective
        mytfa.objective = "PHBS_syn"

        # Prepare thermodynamic data
        mytfa.prepare()

        # Convert model to thermodynamic formulation
        mytfa.convert()

        # Apply solver settings AFTER conversion
        apply_solver_settings(mytfa)

        # ---------------------------------
        # VERIFY THAT TFA IS ACTIVE
        # ---------------------------------
        from pytfa.optim.variables import DeltaG

        dg_vars = mytfa.get_variables_of_type(DeltaG)

        if len(dg_vars) > 0:
            print(f"  TFA ACTIVE — {len(dg_vars)} ΔG variables created for Pareto solution {pareto_id}")

            # Example: print ΔG bounds for a reaction
            try:
                rxn_aa = mytfa.reactions.get_by_id("AACOAR_syn")
                dg_var = next(v for v in dg_vars if v.reaction.id == rxn_aa.id)

                print(
                    f"    AACOAR_syn ΔG bounds: ({dg_var.lb:.2f}, {dg_var.ub:.2f}) kJ/mol"
                )

            except Exception:
                print("    AACOAR_syn ΔG variable not found.")

        else:
            print(
                f"  TFA NOT ACTIVE for Pareto solution {pareto_id} "
                "(no ΔG variables created → model behaves like FBA)"
            )

        # ---------------------------------
        # OPTIMIZE TFA
        # ---------------------------------
        try:
            tfa_sol = mytfa.optimize()

        except Exception as e:
            print(f"TFA optimization failed for Pareto solution {pareto_id}: {e}")
            tfa_sol = fba_sol

        # ---------------------------------
        # COLLECT RESULTS
        # ---------------------------------
        result = {
            "PHB_SYN_UB": PHB_SYN_UB,
            "PHB_SYN_TAG": PHB_SYN_TAG,
            "pareto_id": pareto_id,
            "PHB_pFBA": pfba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan),
            "Biomass_pFBA": pfba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_pFBA": pfba_sol.status,
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
            "optimization_strategy": strategy
        }

        for r in PHB_REACTIONS:
            result[f"{r}_pFBA"] = pfba_sol.fluxes.get(r, np.nan)
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

        for base_col, rxn_id in SUB_TO_RXN_BASE.items():
            result[f"{base_col}_pFBA"] = pfba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_FBA"]  = fba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_TFA"]  = tfa_sol.fluxes.get(rxn_id, np.nan)

        result.update(input_values_used)
        print(pd.Series(result))
        print("-" * 60)
        results.append(result)

    pd.DataFrame(results).to_csv(OUT_CSV, index=False)
    print(f"\nDONE — Results saved to:\n{OUT_CSV}")

==============================
PHB_SYN_UB_VALUE: 0.3978
==============================
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : F/F
Warning : F/F
Warning : CrO4/Cr
Warning : CrO4/Cr
Warning : BO3/B
Warning : BO3/B
Warning : BO3/B
  TFA ACTIVE — 1 ΔG variables created for Pareto solution 0
    AACOAR_syn ΔG variable not found.
PHB_SYN_UB         0.3978
PHB_SYN_TAG        0.3978
pareto_id               0
PHB_pFBA           0.3978
PHB_FBA            0.3978
                   ...
mal_supplied    -0.238157
hxa_supplied          0.0
oct_supplied       -0.112
nh4_supplied          0.0
hco3_supplied      0.2696
Length: 74, dtype: object
------------------------------------------------------------
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : F/F
Warning : F/F
Warning : CrO4/Cr
Warning : CrO4/Cr
Warning : BO3/B
Warning : BO3/B
Warning : BO3/B
  TFA ACTIVE — 1 ΔG variables created for Pareto solution 1
    AACOAR_syn ΔG variable not found.
PHB_SYN_UB         0.3978
PHB_SYN_TAG        0.3978
pareto_id               1
PHB_pFBA           0.3978
PHB_FBA            0.3978
                   ...
mal_supplied          0.0
hxa_supplied    -0.079939
oct_supplied          0.0
nh4_supplied          0.0
hco3_supplied         0.0
Length: 74, dtype: object
------------------------------------------------------------
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : F/F
Warning : F/F
Warning : CrO4/Cr
Warning : CrO4/Cr
Warning : BO3/B
Warning : BO3/B
Warning : BO3/B
  TFA ACTIVE — 1 ΔG variables created for Pareto solution 2
    AACOAR_syn ΔG variable not found.
PHB_SYN_UB         0.3978
PHB_SYN_TAG        0.3978
pareto_id               2
PHB_pFBA           0.3978
PHB_FBA            0.3978
                   ...
mal_supplied    -0.238157
hxa_supplied          0.0
oct_supplied          0.0
nh4_supplied       0.2205
hco3_supplied         0.0
Length: 74, dtype: object
------------------------------------------------------------
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : F/F
Warning : F/F
Warning : CrO4/Cr
Warning : CrO4/Cr
Warning : BO3/B
Warning : BO3/B
Warning : BO3/B
  TFA ACTIVE — 1 ΔG variables created for Pareto solution 3
    AACOAR_syn ΔG variable not found.
PHB_SYN_UB        0.3978
PHB_SYN_TAG       0.3978
pareto_id              3
PHB_pFBA          0.3978
PHB_FBA           0.3978
                  ...
mal_supplied         0.0
hxa_supplied         0.0
oct_supplied         0.0
nh4_supplied    -0.12398
hco3_supplied        0.0
Length: 74, dtype: object
------------------------------------------------------------
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : F/F
Warning : F/F
Warning : CrO4/Cr
Warning : CrO4/Cr
Warning : BO3/B
Warning : BO3/B
Warning : BO3/B
  TFA ACTIVE — 1 ΔG variables created for Pareto solution 4
    AACOAR_syn ΔG variable not found.
PHB_SYN_UB       0.3978
PHB_SYN_TAG      0.3978
pareto_id             4
PHB_pFBA         0.3978
PHB_FBA          0.3978
                  ...
mal_supplied        0.0
hxa_supplied        0.0
oct_supplied        0.0
nh4_supplied     0.2205
hco3_supplied    0.2696
Length: 74, dtype: object
------------------------------------------------------------

DONE — Results saved to:
/content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/results/phb/tfa/05_FBA_TFA_PFBA_detailed_results_all_strategies_0.3978.csv

In [ ]:
from pytfa.optim.variables import DeltaG

dg_vars = mytfa.get_variables_of_type(DeltaG)

print("Number of ΔG variables:", len(dg_vars))

Number of ΔG variables: 1

In [ ]:
thermo_rxns = []

for v in dg_vars:
    thermo_rxns.append(v.reaction.id)

thermo_rxns = sorted(set(thermo_rxns))

print("Thermodynamically constrained reactions:")
print(thermo_rxns)
print("Total:", len(thermo_rxns))

Thermodynamically constrained reactions:
['NADTRHD']
Total: 1

In [ ]:
def has_dGr_variable(tmodel, rxn_id):
    return any(v.reaction.id == rxn_id for v in tmodel.get_variables_of_type(DeltaG))

for rxn_id in ["ACACT1r", "ACACCT", "AACOAR_syn", "HACD1_2", "PHBS_syn"]:
    print(rxn_id, "thermo constrained:", has_dGr_variable(tmodel, rxn_id))

NameError: name 'tmodel' is not defined

# *Compare results

In [ ]:
import pandas as pd
import numpy as np


CSV_FILE = PHB_TFA_DIR / f"05_FBA_TFA_PHB_detailed_results_0.3978.csv"

TOL = 1e-6

PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

df = pd.read_csv(CSV_FILE)

for idx, row in df.iterrows():

    print(f"\nPareto row: {row['pareto_id']} | Strategy: {row['optimization_strategy']}")
    print("-" * 60)

    for r in PHB_REACTIONS:

        pfba = row[f"{r}_pFBA"]
        tfa  = row[f"{r}_TFA"]

        if pd.isna(pfba) or pd.isna(tfa):
            relation = "missing values"

        elif np.isclose(pfba, tfa, atol=TOL):
            relation = "≈ equal"

        elif pfba > tfa:
            relation = "pFBA HIGHER than TFA"

        else:
            relation = "pFBA LOWER than TFA"

        print(f"{r:12s} → {relation}  (pFBA={pfba:.6f}, TFA={tfa:.6f})")

Pareto row: 0 | Strategy: SUP
------------------------------------------------------------
ACACT1r      → pFBA LOWER than TFA  (pFBA=0.128257, TFA=0.397800)
ACACCT       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
AACOAR_syn   → ≈ equal  (pFBA=0.397800, TFA=0.397800)
HACD1_2      → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1        → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1i       → pFBA HIGHER than TFA  (pFBA=0.269543, TFA=0.000000)
KAT1         → ≈ equal  (pFBA=0.000000, TFA=0.000000)

Pareto row: 1 | Strategy: CON
------------------------------------------------------------
ACACT1r      → ≈ equal  (pFBA=0.397800, TFA=0.397800)
ACACCT       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
AACOAR_syn   → ≈ equal  (pFBA=0.397800, TFA=0.397800)
HACD1_2      → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1        → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1i       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
KAT1         → ≈ equal  (pFBA=0.000000, TFA=0.000000)

Pareto row: 2 | Strategy: SUP_and_CON
------------------------------------------------------------
ACACT1r      → ≈ equal  (pFBA=0.397800, TFA=0.397800)
ACACCT       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
AACOAR_syn   → ≈ equal  (pFBA=0.397800, TFA=0.397800)
HACD1_2      → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1        → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1i       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
KAT1         → ≈ equal  (pFBA=0.000000, TFA=0.000000)

Pareto row: 3 | Strategy: PFBA
------------------------------------------------------------
ACACT1r      → pFBA LOWER than TFA  (pFBA=0.311353, TFA=0.397800)
ACACCT       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
AACOAR_syn   → ≈ equal  (pFBA=0.397800, TFA=0.397800)
HACD1_2      → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1        → pFBA LOWER than TFA  (pFBA=-0.086447, TFA=0.000000)
HACD1i       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
KAT1         → ≈ equal  (pFBA=0.000000, TFA=0.000000)

Pareto row: 4 | Strategy: SUP_and_PFBA
------------------------------------------------------------
ACACT1r      → ≈ equal  (pFBA=0.397800, TFA=0.397800)
ACACCT       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
AACOAR_syn   → ≈ equal  (pFBA=0.397800, TFA=0.397800)
HACD1_2      → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1        → ≈ equal  (pFBA=0.000000, TFA=0.000000)
HACD1i       → ≈ equal  (pFBA=0.000000, TFA=0.000000)
KAT1         → ≈ equal  (pFBA=0.000000, TFA=0.000000)

In [ ]:
import numpy as np
import pandas as pd
import cobra
import pytfa

from cobra.flux_analysis import pfba

from pytfa.io import (
    read_lexicon,
    annotate_from_lexicon,
    read_compartment_data,
    apply_compartment_data,
)
import logging

logging.getLogger("thermomodel_None").setLevel(logging.ERROR)
logging.getLogger("pytfa").setLevel(logging.ERROR)

# ============================================================
# USER PARAMETERS
# ============================================================
PHB_SYN_UB_VALUES =  [0.3978, 1000]
# ============================================================
# CONSTANTS
# ============================================================
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

SUB_TO_RXN_BASE = {
    "ace": "EX_ac_e",
    "lac": "EX_lac__L_e",
    "ppa": "EX_ppa_e",
    "but": "EX_but_e",
    "ibt": "EX_ibt_e",
    "mal": "EX_mal__L_e",
    "hxa": "EX_hxa_e",
    "oct": "EX_octa_e",
    "nh4": "EX_nh4_e",
    "hco3": "EX_hco3_e",
}

EXCHANGE_RXNS = list(SUB_TO_RXN_BASE.values())

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True


# ============================================================
# LOAD TFA METADATA (ONCE)
# ============================================================
lexicon = read_lexicon(str(lexicon_path))
comp_data = read_compartment_data(str(compartments_path))


# ============================================================
# MAIN LOOP
# ============================================================
for PHB_SYN_UB in PHB_SYN_UB_VALUES:

    print("\n==============================")
    print(f"PHB_SYN_UB_VALUE: {PHB_SYN_UB}")
    print("==============================")

    PHB_SYN_TAG = f"{PHB_SYN_UB:g}"

    INPUT_CSV = PHB_PARETO_DIR / f"03_pareto_best_all_strategies_{PHB_SYN_TAG}.csv"
    OUT_CSV = PHB_TFA_DIR / f"05_FBA_TFA_PFBA_detailed_results_all_strategies_{PHB_SYN_TAG}.csv"

    df = pd.read_csv(INPUT_CSV)
    results = []

    for pareto_id, row in df.iterrows():

        strategy = row["optimization_strategy"]

        if "SUP" in strategy:
            suffix = "_sup"

        elif strategy == "CON":
            suffix = "_con"

        elif strategy == "SUP_and_CON":
            suffix = "_sup"

        elif strategy == "PFBA":
            suffix = "_con_pfba"

        elif strategy == "SUP_and_PFBA":
            suffix = "_sup"

        else:
            print('Other optimization strategy')

        m = model_constrained.copy()

        # ---------------------------------
        # STORE INPUT VALUES USED
        # ---------------------------------
        input_values_used = {}

        for base_col, rxn_id in SUB_TO_RXN_BASE.items():

            col_name = f"{base_col}{suffix}"
            val_used = np.nan

            if col_name in row:
                val = row[col_name]
                if pd.notna(val) and float(val) != 0.0 and rxn_id in m.reactions:
                    rxn = m.reactions.get_by_id(rxn_id)
                    rxn.lower_bound = -abs(float(val))
                    rxn.upper_bound = 0.0
                    val_used = float(val)

            input_values_used[f"{base_col}_supplied"] = 0.0 if pd.isna(val_used) else val_used

        # ---------------------------------
        # OBJECTIVE & NO GROWTH
        # ---------------------------------
        phb_rxn = m.reactions.get_by_id("PHBS_syn")
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = PHB_SYN_UB
        m.objective = phb_rxn

        biomass = m.reactions.get_by_id("BIOMASS__1")
        biomass.lower_bound = 0.0
        biomass.upper_bound = 0.0

        apply_solver_settings(m)

        # ---------------------------------
        # FBA
        # ---------------------------------
        fba_sol = m.optimize()

        # ---------------------------------
        # pFBA
        # ---------------------------------

        pfba_sol = pfba(m)

        # ---------------------------------
        # TFA
        # ---------------------------------
        # Ensure thermo_data metabolites keys are plain strings
        thermo_data['metabolites'] = {k: v for k, v in thermo_data['metabolites'].items()}

        mytfa = pytfa.ThermoModel(thermo_data, m)

        # Explicitly set compartments to avoid TypeError, mimicking cobra_model_mat setup
        mytfa.compartments = {
            'c': {
                'pH': 7.0,
                'ionicStr': 0.25,
                'c_min': 1e-6,
                'c_max': 0.02,
                'membranePot': 0.0,
            },
            'e': {
                'pH': 7.0,
                'ionicStr': 0.25,
                'c_min': 1e-6,
                'c_max': 0.02,
                'membranePot': 0.0,
            },
            'p': {
                'pH': 7.0,
                'ionicStr': 0.25,
                'c_min': 1e-6,
                'c_max': 0.02,
                'membranePot': 0.15,
            },
            'u': {
                'pH': 7.0,
                'ionicStr': 0.25,
                'c_min': 1e-6,
                'c_max': 0.02,
                'membranePot': 0.0,
            }
        }

        # These lines are crucial for TFA to work correctly
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)

        mytfa.objective = "PHBS_syn"
        apply_solver_settings(mytfa)
        mytfa.prepare()
        mytfa.convert()

        # Check if DeltaG variables are created to confirm TFA is active
        from pytfa.optim.variables import DeltaG
        if DeltaG in mytfa.variables and len(mytfa.variables[DeltaG]) > 0:
            print(f"  TFA: DeltaG variables created. TFA is active for Pareto solution {pareto_id}.")
        else:
            print(f"  TFA: No DeltaG variables created. TFA is NOT active for Pareto solution {pareto_id}. (Falling back to FBA behavior)")

        tfa_sol = mytfa.optimize()

        cobra.io.write_sbml_model(
            mytfa,
            PHB_MODEL_TFA_DIR / f"model_TFA_PHB_{PHB_SYN_TAG}.xml"
        )

        # ---------------------------------
        # COLLECT RESULTS
        # ---------------------------------
        result = {
            "PHB_SYN_UB": PHB_SYN_UB,
            "PHB_SYN_TAG": PHB_SYN_TAG,
            "pareto_id": pareto_id,
            "PHB_pFBA": pfba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan),
            "Biomass_pFBA": pfba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_pFBA": pfba_sol.status,
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
            "optimization_strategy": strategy
        }

        for r in PHB_REACTIONS:
            result[f"{r}_pFBA"] = pfba_sol.fluxes.get(r, np.nan)
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

        for base_col, rxn_id in SUB_TO_RXN_BASE.items():
            result[f"{base_col}_pFBA"] = pfba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_FBA"]  = fba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_TFA"]  = tfa_sol.fluxes.get(rxn_id, np.nan)

        result.update(input_values_used)
        print(pd.Series(result))
        print("-" * 60)
        results.append(result)

    pd.DataFrame(results).to_csv(OUT_CSV, index=False)
    print(f"\nDONE — Results saved to:\n{OUT_CSV}")

# *** Additional code ***

# Check TFA model

In [ ]:
assert any(c.name.startswith("G_") for c in mytfa.constraints)
assert any(v.name.startswith("DGo_") for v in mytfa.variables)
assert any(v.type == "binary" for v in mytfa.variables)
print("✅ TFBA is active")

✅ TFBA is active

In [ ]:
for v in mytfa.variables.values():
  print(v)

  #0.0 <= DM_4CRSOL <= 1000.0

0.0 <= QULNS <= 1000.0
0.0 <= QULNS_reverse_66da1 <= 0.0
0.0 <= ORNDC <= 1000.0
0.0 <= ORNDC_reverse_63596 <= 0.0
0.0 <= MSBENZMT <= 1000.0
0.0 <= MSBENZMT_reverse_a902a <= 0.0
0.0 <= DESAT18a <= 1000.0
0.0 <= DESAT18a_reverse_fd859 <= 1000.0
0.0 <= FUM <= 1000.0
0.0 <= FUM_reverse_d3642 <= 1000.0
0.0 <= PHYFXOR <= 1000.0
0.0 <= PHYFXOR_reverse_84960 <= 0.0
0.0 <= VPAMTr <= 1000.0
0.0 <= VPAMTr_reverse_872bd <= 0.0
0.0 <= GLYCL <= 1000.0
0.0 <= GLYCL_reverse_e418f <= 0.0
0.0 <= NDPK7 <= 1000.0
0.0 <= NDPK7_reverse_9dc79 <= 1000.0
0.0 <= GTPCI <= 1000.0
0.0 <= GTPCI_reverse_1ee86 <= 0.0
0.0 <= MTHFC <= 1000.0
0.0 <= MTHFC_reverse_f6fcc <= 1000.0
0.0 <= GCATENEC <= 1000.0
0.0 <= GCATENEC_reverse_ae4a5 <= 1000.0
0.0 <= ORNTA <= 1000.0
0.0 <= ORNTA_reverse_5adff <= 1000.0
0.0 <= UPPDC1 <= 1000.0
0.0 <= UPPDC1_reverse_cb592 <= 0.0
0.0 <= GARFT <= 1000.0
0.0 <= GARFT_reverse_7ecb6 <= 0.0
0.0 <= H4THDPR <= 1000.0
0.0 <= H4THDPR_reverse_617be <= 0.0
0.0 <= UDPG4E <= 1000.0
0.0 <= UDPG4E_reverse_08c7f <= 1000.0
0.0 <= GLCS3 <= 1000.0
0.0 <= GLCS3_reverse_5e7ed <= 0.0
0.0 <= ASPTA <= 1000.0
0.0 <= ASPTA_reverse_36525 <= 1000.0
0.0 <= PRAGSr <= 1000.0
0.0 <= PRAGSr_reverse_fd2d8 <= 0.0
0.0 <= ACKr <= 1000.0
0.0 <= ACKr_reverse_b49c0 <= 1000.0
0.0 <= KAS14 <= 1000.0
0.0 <= KAS14_reverse_25582 <= 0.0
0.0 <= UDCPDPS <= 1000.0
0.0 <= UDCPDPS_reverse_04082 <= 0.0
0.0 <= GLNS <= 1000.0
0.0 <= GLNS_reverse_59581 <= 0.0
0.0 <= SHKK <= 1000.0
0.0 <= SHKK_reverse_163fd <= 0.0
0.0 <= G1PACT <= 1000.0
0.0 <= G1PACT_reverse_51580 <= 0.0
0.0 <= 5DOAN <= 1000.0
0.0 <= 5DOAN_reverse_c8e7d <= 0.0
0.0 <= OHPBAT <= 1000.0
0.0 <= OHPBAT_reverse_7e72e <= 1000.0
0.0 <= Htex <= 1000.0
0.0 <= Htex_reverse_6f9a4 <= 1000.0
0.0 <= 3HAD60 <= 1000.0
0.0 <= 3HAD60_reverse_d7fb5 <= 1000.0
0.0 <= PGI <= 1000.0
0.0 <= PGI_reverse_27efc <= 1000.0
0.0 <= PNTK <= 1000.0
0.0 <= PNTK_reverse_236b6 <= 0.0
0.0 <= 3OAR60 <= 1000.0
0.0 <= 3OAR60_reverse_40a5c <= 1000.0
0.0 <= ACGK <= 1000.0
0.0 <= ACGK_reverse_684be <= 0.0
0.0 <= LEUabcpp <= 1000.0
0.0 <= LEUabcpp_reverse_ab30a <= 0.0
0.0 <= G5SD <= 1000.0
0.0 <= G5SD_reverse_af8c0 <= 0.0
0.0 <= DTMPK <= 1000.0
0.0 <= DTMPK_reverse_44d5a <= 1000.0
0.0 <= NDH_1_1_um_copy1 <= 1000.0
0.0 <= NDH_1_1_um_copy1_reverse_4db8b <= 0.0
0.0 <= HSTPT <= 1000.0
0.0 <= HSTPT_reverse_b3657 <= 1000.0
0.0 <= U23GAAT2 <= 1000.0
0.0 <= U23GAAT2_reverse_387ef <= 0.0
0.0 <= PGK <= 1000.0
0.0 <= PGK_reverse_02696 <= 1000.0
0.0 <= IMPD <= 1000.0
0.0 <= IMPD_reverse_6e625 <= 0.0
0.0 <= LPOR <= 1000.0
0.0 <= LPOR_reverse_ae81c <= 0.0
0.0 <= CHRPL <= 1000.0
0.0 <= CHRPL_reverse_46f50 <= 0.0
0.0 <= GCALDDy <= 1000.0
0.0 <= GCALDDy_reverse_2af46 <= 0.0
0.0 <= RNDR1 <= 1000.0
0.0 <= RNDR1_reverse_f4be1 <= 0.0
0.0 <= AIRC2 <= 1000.0
0.0 <= AIRC2_reverse_50d74 <= 0.0
0.0 <= MTAP <= 1000.0
0.0 <= MTAP_reverse_96009 <= 0.0
0.0 <= DHORD3um <= 1000.0
0.0 <= DHORD3um_reverse_137f3 <= 0.0
0.0 <= TRPS1 <= 1000.0
0.0 <= TRPS1_reverse_35c22 <= 0.0
0.0 <= NNATr <= 1000.0
0.0 <= NNATr_reverse_8ab73 <= 1000.0
0.0 <= 3OAR120 <= 1000.0
0.0 <= 3OAR120_reverse_5a2b4 <= 1000.0
0.0 <= HISTDb <= 1000.0
0.0 <= HISTDb_reverse_acd55 <= 0.0
0.0 <= ADCL <= 1000.0
0.0 <= ADCL_reverse_0051f <= 0.0
0.0 <= CYTK1 <= 1000.0
0.0 <= CYTK1_reverse_2fa21 <= 1000.0
0.0 <= PSIum <= 1000.0
0.0 <= PSIum_reverse_43c5e <= 0.0
0.0 <= Cobalt2abcppI <= 1000.0
0.0 <= Cobalt2abcppI_reverse_894f2 <= 0.0
0.0 <= THRS <= 1000.0
0.0 <= THRS_reverse_a994c <= 0.0
0.0 <= AOXPBDC <= 1000.0
0.0 <= AOXPBDC_reverse_81d1e <= 0.0
0.0 <= NAMNPP <= 1000.0
0.0 <= NAMNPP_reverse_ebb31 <= 1000.0
0.0 <= PERD <= 1000.0
0.0 <= PERD_reverse_c9aa4 <= 0.0
0.0 <= DAPDC <= 1000.0
0.0 <= DAPDC_reverse_d3ab8 <= 0.0
0.0 <= COCHL_1 <= 1000.0
0.0 <= COCHL_1_reverse_736d9 <= 0.0
0.0 <= 3OAR100 <= 1000.0
0.0 <= 3OAR100_reverse_d47e7 <= 1000.0
0.0 <= PPK2 <= 1000.0
0.0 <= PPK2_reverse_3275d <= 1000.0
0.0 <= ZNabcpp <= 1000.0
0.0 <= ZNabcpp_reverse_14d34 <= 1000.0
0.0 <= GLYDHDA <= 1000.0
0.0 <= GLYDHDA_reverse_663d3 <= 1000.0
0.0 <= ANS <= 1000.0
0.0 <= ANS_reverse_4e062 <= 0.0
0.0 <= SUCBZL <= 1000.0
0.0 <= SUCBZL_reverse_536e6 <= 0.0
0.0 <= ADPT <= 1000.0
0.0 <= ADPT_reverse_567cf <= 1000.0
0.0 <= RNDR3 <= 1000.0
0.0 <= RNDR3_reverse_bc84a <= 0.0
0.0 <= DHNANT <= 1000.0
0.0 <= DHNANT_reverse_39a88 <= 0.0
0.0 <= GND <= 1000.0
0.0 <= GND_reverse_eec5c <= 0.0
0.0 <= O2tcx <= 1000.0
0.0 <= O2tcx_reverse_6b2f8 <= 0.0
0.0 <= TRPS3 <= 1000.0
0.0 <= TRPS3_reverse_bdfbb <= 0.0
0.0 <= DNTPPA <= 1000.0
0.0 <= DNTPPA_reverse_7e624 <= 0.0
0.0 <= HOXGfx <= 1000.0
0.0 <= HOXGfx_reverse_2964c <= 0.0
0.0 <= TMPPP_1 <= 1000.0
0.0 <= TMPPP_1_reverse_7b964 <= 0.0
0.0 <= ACONT <= 1000.0
0.0 <= ACONT_reverse_7c2d5 <= 1000.0
0.0 <= IGPS <= 1000.0
0.0 <= IGPS_reverse_feb80 <= 0.0
0.0 <= HBZNPT <= 1000.0
0.0 <= HBZNPT_reverse_37fab <= 0.0
0.0 <= HSDy <= 0.0
0.0 <= HSDy_reverse_77ce7 <= 1000.0
0.0 <= GLYOX <= 1000.0
0.0 <= GLYOX_reverse_6ab0a <= 0.0
0.0 <= AICART <= 1000.0
0.0 <= AICART_reverse_b7b59 <= 0.0
0.0 <= SQD1 <= 1000.0
0.0 <= SQD1_reverse_c0265 <= 0.0
0.0 <= GK1 <= 1000.0
0.0 <= GK1_reverse_11a40 <= 1000.0
0.0 <= R05219 <= 1000.0
0.0 <= R05219_reverse_1009e <= 0.0
0.0 <= PPND <= 1000.0
0.0 <= PPND_reverse_5463c <= 0.0
0.0 <= IPDPS_syn <= 1000.0
0.0 <= IPDPS_syn_reverse_8eea6 <= 0.0
0.0 <= H4THDPS <= 1000.0
0.0 <= H4THDPS_reverse_5f722 <= 0.0
0.0 <= BIOMASS_PIGMENTS <= 1000.0
0.0 <= BIOMASS_PIGMENTS_reverse_b23ff <= 0.0
0.0 <= 3HAD160 <= 1000.0
0.0 <= 3HAD160_reverse_c0da0 <= 1000.0
0.0 <= HISTDa <= 1000.0
0.0 <= HISTDa_reverse_76147 <= 0.0
0.0 <= ADSL1r <= 1000.0
0.0 <= ADSL1r_reverse_2ae14 <= 0.0
0.0 <= H2Otu_syn <= 1000.0
0.0 <= H2Otu_syn_reverse_7aa62 <= 1000.0
0.0 <= ADOCBLS <= 1000.0
0.0 <= ADOCBLS_reverse_005a5 <= 0.0
0.0 <= ALAALAr <= 1000.0
0.0 <= ALAALAr_reverse_18faa <= 0.0
0.0 <= ACOATA <= 1000.0
0.0 <= ACOATA_reverse_8c02f <= 0.0
0.0 <= GLCP2_1 <= 1000.0
0.0 <= GLCP2_1_reverse_b0967 <= 0.0
0.0 <= GLYCK <= 1000.0
0.0 <= GLYCK_reverse_c3ee2 <= 0.0
0.0 <= MAN1PT <= 1000.0
0.0 <= MAN1PT_reverse_c317b <= 0.0
0.0 <= DMBZIDS2 <= 1000.0
0.0 <= DMBZIDS2_reverse_6417b <= 0.0
0.0 <= CS <= 1000.0
0.0 <= CS_reverse_8d7e9 <= 0.0
0.0 <= DMATT <= 1000.0
0.0 <= DMATT_reverse_3a731 <= 0.0
0.0 <= PSP_L <= 1000.0
0.0 <= PSP_L_reverse_cfa3c <= 0.0
0.0 <= NDPK3 <= 1000.0
0.0 <= NDPK3_reverse_37ea6 <= 1000.0
0.0 <= G3PD2 <= 1000.0
0.0 <= G3PD2_reverse_0c363 <= 1000.0
0.0 <= PHYTES <= 1000.0
0.0 <= PHYTES_reverse_45da8 <= 0.0
0.0 <= MOHMT <= 1000.0
0.0 <= MOHMT_reverse_83ce0 <= 0.0
0.0 <= FBA <= 1000.0
0.0 <= FBA_reverse_84806 <= 1000.0
0.0 <= BIOMASS__1 <= 2.0
0.0 <= BIOMASS__1_reverse_063c7 <= 0.0
0.0 <= ACLSa <= 1000.0
0.0 <= ACLSa_reverse_75fb2 <= 0.0
0.0 <= ASAD <= 0.0
0.0 <= ASAD_reverse_39a64 <= 1000.0
0.0 <= PSCVT <= 1000.0
0.0 <= PSCVT_reverse_1a852 <= 1000.0
0.0 <= TYRTA <= 1000.0
0.0 <= TYRTA_reverse_e9311 <= 1000.0
0.0 <= SERAT <= 1000.0
0.0 <= SERAT_reverse_0de5e <= 0.0
0.0 <= DHFS <= 1000.0
0.0 <= DHFS_reverse_f7920 <= 0.0
0.0 <= AMPMS3 <= 1000.0
0.0 <= AMPMS3_reverse_b5e80 <= 1000.0
0.0 <= ACBIPGT <= 1000.0
0.0 <= ACBIPGT_reverse_bcc45 <= 0.0
0.0 <= ATPM <= 1000.0
0.0 <= ATPM_reverse_5b752 <= 0.0
0.0 <= SEPHCHCS <= 1000.0
0.0 <= SEPHCHCS_reverse_cb185 <= 0.0
0.0 <= NMNDA <= 1000.0
0.0 <= NMNDA_reverse_0dc65 <= 0.0
0.0 <= IGPDH <= 1000.0
0.0 <= IGPDH_reverse_b1a3c <= 0.0
0.0 <= OMPDC <= 1000.0
0.0 <= OMPDC_reverse_45ba1 <= 0.0
0.0 <= 3OAR80 <= 1000.0
0.0 <= 3OAR80_reverse_fe338 <= 1000.0
0.0 <= 3OAR180 <= 1000.0
0.0 <= 3OAR180_reverse_e234c <= 1000.0
0.0 <= GLUSfx <= 1000.0
0.0 <= GLUSfx_reverse_468d6 <= 0.0
0.0 <= NADS2 <= 1000.0
0.0 <= NADS2_reverse_b427b <= 0.0
0.0 <= GLUTRR <= 1000.0
0.0 <= GLUTRR_reverse_355d5 <= 0.0
0.0 <= UAMAGS <= 1000.0
0.0 <= UAMAGS_reverse_a0d94 <= 0.0
0.0 <= FOLD3 <= 1000.0
0.0 <= FOLD3_reverse_4bc58 <= 0.0
0.0 <= 3HAD100 <= 1000.0
0.0 <= 3HAD100_reverse_ca00f <= 1000.0
0.0 <= GALUi <= 1000.0
0.0 <= GALUi_reverse_c40d5 <= 1000.0
0.0 <= P5CR <= 1000.0
0.0 <= P5CR_reverse_55c58 <= 0.0
0.0 <= PQH2tum <= 1000.0
0.0 <= PQH2tum_reverse_270a9 <= 0.0
0.0 <= ICHORS <= 1000.0
0.0 <= ICHORS_reverse_8e175 <= 1000.0
0.0 <= 3OAS140 <= 1000.0
0.0 <= 3OAS140_reverse_65ddc <= 0.0
0.0 <= SBP <= 1000.0
0.0 <= SBP_reverse_78d5c <= 0.0
0.0 <= EAR60y <= 1000.0
0.0 <= EAR60y_reverse_02e5e <= 0.0
0.0 <= O2tu <= 1000.0
0.0 <= O2tu_reverse_2d1e7 <= 1000.0
0.0 <= SULabcpp <= 1000.0
0.0 <= SULabcpp_reverse_40679 <= 0.0
0.0 <= PPK <= 1000.0
0.0 <= PPK_reverse_69cd8 <= 1000.0
0.0 <= BIOMASS_DNA <= 1000.0
0.0 <= BIOMASS_DNA_reverse_9947a <= 0.0
0.0 <= UAPGR <= 1000.0
0.0 <= UAPGR_reverse_4f67b <= 1000.0
0.0 <= DHAD1 <= 1000.0
0.0 <= DHAD1_reverse_39dca <= 0.0
0.0 <= IPPS <= 1000.0
0.0 <= IPPS_reverse_d94c0 <= 0.0
0.0 <= PPBNGS <= 1000.0
0.0 <= PPBNGS_reverse_dc5a2 <= 0.0
0.0 <= PRE3BS <= 1000.0
0.0 <= PRE3BS_reverse_ea947 <= 0.0
0.0 <= PHYTES2_1 <= 1000.0
0.0 <= PHYTES2_1_reverse_bb66c <= 0.0
0.0 <= 3HAD80 <= 1000.0
0.0 <= 3HAD80_reverse_29891 <= 1000.0
0.0 <= LTHRK <= 1000.0
0.0 <= LTHRK_reverse_61b82 <= 0.0
0.0 <= ADCPS2 <= 1000.0
0.0 <= ADCPS2_reverse_34636 <= 0.0
0.0 <= GF6PTA <= 1000.0
0.0 <= GF6PTA_reverse_21fb1 <= 1000.0
0.0 <= O2tpp <= 1000.0
0.0 <= O2tpp_reverse_28c7e <= 1000.0
0.0 <= PGMT <= 1000.0
0.0 <= PGMT_reverse_5bcdd <= 1000.0
0.0 <= 3OAR140 <= 1000.0
0.0 <= 3OAR140_reverse_4eb2a <= 1000.0
0.0 <= NDPK2 <= 1000.0
0.0 <= NDPK2_reverse_10df6 <= 1000.0
0.0 <= LPADSS2 <= 1000.0
0.0 <= LPADSS2_reverse_9cafc <= 0.0
0.0 <= DPR <= 1000.0
0.0 <= DPR_reverse_691d8 <= 1000.0
0.0 <= H2Otex <= 1000.0
0.0 <= H2Otex_reverse_57da2 <= 1000.0
0.0 <= TKT2 <= 1000.0
0.0 <= TKT2_reverse_7ebc7 <= 1000.0
0.0 <= SK_for_c <= 1000.0
0.0 <= SK_for_c_reverse_b95aa <= 0.0
0.0 <= PPNCL2 <= 1000.0
0.0 <= PPNCL2_reverse_a65ee <= 0.0
0.0 <= CYTBD4cm <= 1000.0
0.0 <= CYTBD4cm_reverse_64e50 <= 0.0
0.0 <= HPYRRy <= 1000.0
0.0 <= HPYRRy_reverse_197c5 <= 0.0
0.0 <= CHORS <= 1000.0
0.0 <= CHORS_reverse_17772 <= 0.0
0.0 <= 3OAR160 <= 1000.0
0.0 <= 3OAR160_reverse_15066 <= 1000.0
0.0 <= ADMDC <= 1000.0
0.0 <= ADMDC_reverse_e2782 <= 0.0
0.0 <= PPPGO2_1 <= 1000.0
0.0 <= PPPGO2_1_reverse_9826c <= 0.0
0.0 <= ASP1DC <= 1000.0
0.0 <= ASP1DC_reverse_5dad1 <= 0.0
0.0 <= MI3PP <= 1000.0
0.0 <= MI3PP_reverse_1228d <= 0.0
0.0 <= CYSS_2 <= 1000.0
0.0 <= CYSS_2_reverse_8e1d0 <= 0.0
0.0 <= FTHFD <= 1000.0
0.0 <= FTHFD_reverse_44321 <= 0.0
0.0 <= MEPCT <= 1000.0
0.0 <= MEPCT_reverse_de97a <= 0.0
0.0 <= PDX5POi <= 1000.0
0.0 <= PDX5POi_reverse_797dd <= 1000.0
0.0 <= PPCDC <= 1000.0
0.0 <= PPCDC_reverse_39306 <= 0.0
0.0 <= NTD6 <= 1000.0
0.0 <= NTD6_reverse_c5bce <= 1000.0
0.0 <= NNDMBRT <= 1000.0
0.0 <= NNDMBRT_reverse_13f8c <= 0.0
0.0 <= PRAIS <= 1000.0
0.0 <= PRAIS_reverse_8e616 <= 0.0
0.0 <= ORNTAC <= 1000.0
0.0 <= ORNTAC_reverse_b265a <= 0.0
0.0 <= SUCBZS <= 1000.0
0.0 <= SUCBZS_reverse_cdbc9 <= 0.0
0.0 <= HGYDAS <= 1000.0
0.0 <= HGYDAS_reverse_bc303 <= 0.0
0.0 <= GGDPR <= 1000.0
0.0 <= GGDPR_reverse_ea652 <= 0.0
0.0 <= ASPCT <= 1000.0
0.0 <= ASPCT_reverse_c18b9 <= 1000.0
0.0 <= PPNDH <= 1000.0
0.0 <= PPNDH_reverse_58300 <= 0.0
0.0 <= ME2 <= 1000.0
0.0 <= ME2_reverse_2b0a2 <= 1000.0
0.0 <= APRAUR <= 1000.0
0.0 <= APRAUR_reverse_e674d <= 0.0
0.0 <= SADT <= 1000.0
0.0 <= SADT_reverse_91e08 <= 0.0
0.0 <= LDH_D <= 1000.0
0.0 <= LDH_D_reverse_f8507 <= 1000.0
0.0 <= DPCOAK <= 1000.0
0.0 <= DPCOAK_reverse_56ab9 <= 0.0
0.0 <= O2tex <= 1000.0
0.0 <= O2tex_reverse_a3b28 <= 1000.0
0.0 <= DPOR <= 0.0
0.0 <= DPOR_reverse_8b09e <= 0.0
0.0 <= ARGSL <= 1000.0
0.0 <= ARGSL_reverse_1b949 <= 0.0
0.0 <= HSK <= 1000.0
0.0 <= HSK_reverse_e4218 <= 0.0
0.0 <= EAR120y <= 1000.0
0.0 <= EAR120y_reverse_c7353 <= 0.0
0.0 <= BCAROHX2 <= 1000.0
0.0 <= BCAROHX2_reverse_888eb <= 0.0
0.0 <= HPPK <= 1000.0
0.0 <= HPPK_reverse_e0ee3 <= 1000.0
0.0 <= PPNCL3 <= 1000.0
0.0 <= PPNCL3_reverse_cd065 <= 0.0
0.0 <= AHCi <= 1000.0
0.0 <= AHCi_reverse_d29ff <= 0.0
0.0 <= G6PDH2r <= 1000.0
0.0 <= G6PDH2r_reverse_19ddf <= 0.0
0.0 <= PMANM <= 1000.0
0.0 <= PMANM_reverse_53eb0 <= 1000.0
0.0 <= CPPPGO2 <= 0.0
0.0 <= CPPPGO2_reverse_e5000 <= 0.0
0.0 <= PC17M_1 <= 1000.0
0.0 <= PC17M_1_reverse_fc1bc <= 0.0
0.0 <= ACCOAC <= 1000.0
0.0 <= ACCOAC_reverse_9d1cd <= 0.0
0.0 <= CYNL <= 1000.0
0.0 <= CYNL_reverse_91a39 <= 0.0
0.0 <= CYOOum <= 1000.0
0.0 <= CYOOum_reverse_37909 <= 0.0
0.0 <= ACLSb <= 1000.0
0.0 <= ACLSb_reverse_588fa <= 0.0
0.0 <= DNMPPA <= 1000.0
0.0 <= DNMPPA_reverse_131b7 <= 0.0
0.0 <= METS_1 <= 1000.0
0.0 <= METS_1_reverse_65e3f <= 0.0
0.0 <= TRPS2 <= 1000.0
0.0 <= TRPS2_reverse_cd73f <= 0.0
0.0 <= PRUK <= 1000.0
0.0 <= PRUK_reverse_a0fb4 <= 0.0
0.0 <= FNOR_1 <= 1000.0
0.0 <= FNOR_1_reverse_80b2d <= 1000.0
0.0 <= GART <= 1000.0
0.0 <= GART_reverse_61742 <= 0.0
0.0 <= G5SADs <= 1000.0
0.0 <= G5SADs_reverse_c7fa4 <= 1000.0
0.0 <= DMTPHT <= 1000.0
0.0 <= DMTPHT_reverse_a16f8 <= 0.0
0.0 <= SPMDabcpp <= 1000.0
0.0 <= SPMDabcpp_reverse_7abfe <= 0.0
0.0 <= DHAD2 <= 1000.0
0.0 <= DHAD2_reverse_755c6 <= 0.0
0.0 <= PRAMPC <= 1000.0
0.0 <= PRAMPC_reverse_54696 <= 0.0
0.0 <= 3OAS80 <= 1000.0
0.0 <= 3OAS80_reverse_c6446 <= 0.0
0.0 <= G1PCTYT <= 1000.0
0.0 <= G1PCTYT_reverse_16243 <= 0.0
0.0 <= BIOMASS_CELL_WALL <= 1000.0
0.0 <= BIOMASS_CELL_WALL_reverse_8d1a4 <= 0.0
0.0 <= CA2abcpp <= 1000.0
0.0 <= CA2abcpp_reverse_aa3d6 <= 0.0
0.0 <= UHGADA2 <= 1000.0
0.0 <= UHGADA2_reverse_e04ae <= 0.0
0.0 <= ASPO6 <= 1000.0
0.0 <= ASPO6_reverse_ec15c <= 0.0
0.0 <= ASPK <= 1000.0
0.0 <= ASPK_reverse_115d7 <= 0.0
0.0 <= DXPS <= 1000.0
0.0 <= DXPS_reverse_86aca <= 0.0
0.0 <= PRATPP <= 1000.0
0.0 <= PRATPP_reverse_99bf0 <= 0.0
0.0 <= NH4tpp <= 1000.0
0.0 <= NH4tpp_reverse_eca16 <= 0.0
0.0 <= PAPSR <= 1000.0
0.0 <= PAPSR_reverse_75961 <= 0.0
0.0 <= NAD_H2 <= 1000.0
0.0 <= NAD_H2_reverse_69196 <= 1000.0
0.0 <= CYRDAAT <= 1000.0
0.0 <= CYRDAAT_reverse_d0652 <= 0.0
0.0 <= NTPP8 <= 1000.0
0.0 <= NTPP8_reverse_ce3f8 <= 0.0
0.0 <= PC11M <= 1000.0
0.0 <= PC11M_reverse_f4161 <= 0.0
0.0 <= ARGabcpp <= 1000.0
0.0 <= ARGabcpp_reverse_2f37a <= 0.0
0.0 <= PMDPHT <= 1000.0
0.0 <= PMDPHT_reverse_8a0fd <= 1000.0
0.0 <= DAPE <= 1000.0
0.0 <= DAPE_reverse_e08be <= 1000.0
0.0 <= LYCOPC <= 1000.0
0.0 <= LYCOPC_reverse_fd996 <= 1000.0
0.0 <= RB15BPtcx <= 1000.0
0.0 <= RB15BPtcx_reverse_6fe05 <= 0.0
0.0 <= GLCBRAN3 <= 1000.0
0.0 <= GLCBRAN3_reverse_4cd37 <= 0.0
0.0 <= DB4PS <= 1000.0
0.0 <= DB4PS_reverse_43dd1 <= 0.0
0.0 <= DXPRIi <= 1000.0
0.0 <= DXPRIi_reverse_85956 <= 0.0
0.0 <= GTPCII <= 1000.0
0.0 <= GTPCII_reverse_a84d9 <= 0.0
0.0 <= RBFSa <= 1000.0
0.0 <= RBFSa_reverse_61d96 <= 0.0
0.0 <= GLUTRS <= 1000.0
0.0 <= GLUTRS_reverse_b214d <= 0.0
0.0 <= ALDD2y <= 1000.0
0.0 <= ALDD2y_reverse_03afb <= 1000.0
0.0 <= EHGLAT <= 1000.0
0.0 <= EHGLAT_reverse_8439b <= 1000.0
0.0 <= METAT <= 1000.0
0.0 <= METAT_reverse_793ef <= 0.0
0.0 <= DHORTS <= 1000.0
0.0 <= DHORTS_reverse_82d73 <= 1000.0
0.0 <= PDX5PS2 <= 1000.0
0.0 <= PDX5PS2_reverse_cfb17 <= 1000.0
0.0 <= GAPDi_nadp <= 1000.0
0.0 <= GAPDi_nadp_reverse_782a6 <= 0.0
0.0 <= PGCD <= 1000.0
0.0 <= PGCD_reverse_1bc76 <= 1000.0
0.0 <= AIRC3 <= 1000.0
0.0 <= AIRC3_reverse_f015f <= 1000.0
0.0 <= UMPK <= 1000.0
0.0 <= UMPK_reverse_ae8e3 <= 1000.0
0.0 <= CBPS <= 1000.0
0.0 <= CBPS_reverse_80907 <= 0.0
0.0 <= 3HAD180 <= 1000.0
0.0 <= 3HAD180_reverse_c801d <= 1000.0
0.0 <= IPPMIb <= 0.0
0.0 <= IPPMIb_reverse_e37a1 <= 1000.0
0.0 <= RZ5PP <= 1000.0
0.0 <= RZ5PP_reverse_b2942 <= 0.0
0.0 <= RBFSb_1 <= 1000.0
0.0 <= RBFSb_1_reverse_7d59e <= 0.0
0.0 <= GLNabcpp <= 1000.0
0.0 <= GLNabcpp_reverse_c0546 <= 0.0
0.0 <= NDPK8 <= 1000.0
0.0 <= NDPK8_reverse_13dd1 <= 1000.0
0.0 <= PC6YM_1 <= 1000.0
0.0 <= PC6YM_1_reverse_0b971 <= 0.0
0.0 <= DDPA <= 1000.0
0.0 <= DDPA_reverse_575e8 <= 0.0
0.0 <= ACOTA <= 1000.0
0.0 <= ACOTA_reverse_c4379 <= 1000.0
0.0 <= FBP <= 1000.0
0.0 <= FBP_reverse_bf2c9 <= 0.0
0.0 <= MNabc_1 <= 1000.0
0.0 <= MNabc_1_reverse_d9c27 <= 0.0
0.0 <= NTD7 <= 1000.0
0.0 <= NTD7_reverse_20dab <= 0.0
0.0 <= MPOMMM <= 1000.0
0.0 <= MPOMMM_reverse_30349 <= 0.0
0.0 <= MTHFD <= 1000.0
0.0 <= MTHFD_reverse_c10fd <= 1000.0
0.0 <= PANTS <= 1000.0
0.0 <= PANTS_reverse_11dcb <= 0.0
0.0 <= TMPK <= 1000.0
0.0 <= TMPK_reverse_b7673 <= 0.0
0.0 <= KARI_23dhmp_1 <= 1000.0
0.0 <= KARI_23dhmp_1_reverse_ef22e <= 0.0
0.0 <= IPMD <= 1000.0
0.0 <= IPMD_reverse_d7a5e <= 0.0
0.0 <= 3PGtcx <= 1000.0
0.0 <= 3PGtcx_reverse_a3768 <= 0.0
0.0 <= CDPMEK <= 1000.0
0.0 <= CDPMEK_reverse_01872 <= 0.0
0.0 <= CITCIa <= 1000.0
0.0 <= CITCIa_reverse_6a08b <= 1000.0
0.0 <= DVOCHR_1 <= 1000.0
0.0 <= DVOCHR_1_reverse_1b3d8 <= 0.0
0.0 <= H2CO3_NAt_syn <= 1000.0
0.0 <= H2CO3_NAt_syn_reverse_5b4d9 <= 1000.0
0.0 <= HEMEOS <= 1000.0
0.0 <= HEMEOS_reverse_b63ba <= 1000.0
0.0 <= RPE <= 1000.0
0.0 <= RPE_reverse_a1b04 <= 1000.0
0.0 <= MPOMT_1 <= 1000.0
0.0 <= MPOMT_1_reverse_63f7f <= 0.0
0.0 <= UAMAS <= 1000.0
0.0 <= UAMAS_reverse_2b5e6 <= 0.0
0.0 <= CITCIb <= 1000.0
0.0 <= CITCIb_reverse_a5ab2 <= 1000.0
0.0 <= BPNT2 <= 1000.0
0.0 <= BPNT2_reverse_ab8bb <= 0.0
0.0 <= BIOMASS_COFACTORS <= 1000.0
0.0 <= BIOMASS_COFACTORS_reverse_d79f8 <= 0.0
0.0 <= HSERTA <= 1000.0
0.0 <= HSERTA_reverse_23c8f <= 0.0
0.0 <= NDPK1 <= 1000.0
0.0 <= NDPK1_reverse_9216a <= 1000.0
0.0 <= PGL <= 1000.0
0.0 <= PGL_reverse_2bb6b <= 0.0
0.0 <= EAR160y <= 1000.0
0.0 <= EAR160y_reverse_e0622 <= 0.0
0.0 <= MECDPDHf <= 1000.0
0.0 <= MECDPDHf_reverse_07da8 <= 0.0
0.0 <= MTHFR3_1 <= 1000.0
0.0 <= MTHFR3_1_reverse_1a948 <= 0.0
0.0 <= 3HAD140 <= 1000.0
0.0 <= 3HAD140_reverse_13958 <= 1000.0
0.0 <= FBA3 <= 1000.0
0.0 <= FBA3_reverse_0d49f <= 1000.0
0.0 <= LDAPAT <= 0.0
0.0 <= LDAPAT_reverse_81d9c <= 1000.0
0.0 <= MG2uabcpp <= 1000.0
0.0 <= MG2uabcpp_reverse_adeed <= 0.0
0.0 <= HCO3E_1_cx <= 1000.0
0.0 <= HCO3E_1_cx_reverse_3a8f8 <= 1000.0
0.0 <= ACODA <= 1000.0
0.0 <= ACODA_reverse_504cc <= 1000.0
0.0 <= GLU5K <= 1000.0
0.0 <= GLU5K_reverse_0d895 <= 0.0
0.0 <= EAR100y <= 1000.0
0.0 <= EAR100y_reverse_863b6 <= 0.0
0.0 <= PGM <= 1000.0
0.0 <= PGM_reverse_fc9af <= 1000.0
0.0 <= ASPOb <= 1000.0
0.0 <= ASPOb_reverse_0f7c6 <= 0.0
0.0 <= DM_h2_c <= 1000.0
0.0 <= DM_h2_c_reverse_84240 <= 0.0
0.0 <= ACS <= 1000.0
0.0 <= ACS_reverse_37635 <= 0.0
0.0 <= AMPTASECG <= 1000.0
0.0 <= AMPTASECG_reverse_11d5d <= 0.0
0.0 <= SHCHCS3 <= 1000.0
0.0 <= SHCHCS3_reverse_fb361 <= 0.0
0.0 <= ATPPRT <= 1000.0
0.0 <= ATPPRT_reverse_00060 <= 0.0
0.0 <= NDH_1_4_um_copy1 <= 1000.0
0.0 <= NDH_1_4_um_copy1_reverse_4512a <= 0.0
0.0 <= UAGCVT <= 1000.0
0.0 <= UAGCVT_reverse_ba1ab <= 0.0
0.0 <= ADSL2r <= 1000.0
0.0 <= ADSL2r_reverse_42348 <= 1000.0
0.0 <= PRASCSi <= 1000.0
0.0 <= PRASCSi_reverse_11704 <= 1000.0
0.0 <= MG2tex <= 1000.0
0.0 <= MG2tex_reverse_a1983 <= 1000.0
0.0 <= HPROb <= 1000.0
0.0 <= HPROb_reverse_9e6b2 <= 0.0
0.0 <= NTPP2 <= 1000.0
0.0 <= NTPP2_reverse_bff4f <= 0.0
0.0 <= TRDR <= 1000.0
0.0 <= TRDR_reverse_6372e <= 0.0
0.0 <= NDPK6 <= 1000.0
0.0 <= NDPK6_reverse_d41ea <= 1000.0
0.0 <= GLUPRT <= 1000.0
0.0 <= GLUPRT_reverse_1f180 <= 0.0
0.0 <= PTRCabcpp <= 1000.0
0.0 <= PTRCabcpp_reverse_96b27 <= 0.0
0.0 <= UPP3MT <= 1000.0
0.0 <= UPP3MT_reverse_2adf0 <= 0.0
0.0 <= DHNCOAS <= 1000.0
0.0 <= DHNCOAS_reverse_af3a9 <= 0.0
0.0 <= MCOATA <= 1000.0
0.0 <= MCOATA_reverse_d10f2 <= 0.0
0.0 <= PMPK <= 1000.0
0.0 <= PMPK_reverse_48b12 <= 0.0
0.0 <= HMBS <= 1000.0
0.0 <= HMBS_reverse_23a06 <= 0.0
0.0 <= PGLYCP <= 1000.0
0.0 <= PGLYCP_reverse_9063f <= 0.0
0.0 <= UAGAAT2 <= 1000.0
0.0 <= UAGAAT2_reverse_8209e <= 0.0
0.0 <= HTHRPDH <= 1000.0
0.0 <= HTHRPDH_reverse_9ee3b <= 0.0
0.0 <= BCT1_syn <= 1000.0
0.0 <= BCT1_syn_reverse_8b530 <= 0.0
0.0 <= IPDDI <= 1000.0
0.0 <= IPDDI_reverse_6c5f9 <= 1000.0
0.0 <= GLYALDDy <= 1000.0
0.0 <= GLYALDDy_reverse_7e106 <= 1000.0
0.0 <= CITMS <= 1000.0
0.0 <= CITMS_reverse_37134 <= 0.0
0.0 <= IMPC <= 1000.0
0.0 <= IMPC_reverse_efa41 <= 1000.0
0.0 <= Htcx <= 1000.0
0.0 <= Htcx_reverse_e3f6b <= 1000.0
0.0 <= DHQTi <= 1000.0
0.0 <= DHQTi_reverse_c4498 <= 1000.0
0.0 <= SPODM <= 1000.0
0.0 <= SPODM_reverse_2648f <= 0.0
0.0 <= MAN6PI <= 1000.0
0.0 <= MAN6PI_reverse_d96f0 <= 1000.0
0.0 <= 3OAS120 <= 1000.0
0.0 <= 3OAS120_reverse_06658 <= 0.0
0.0 <= PGAMT <= 1000.0
0.0 <= PGAMT_reverse_52c23 <= 1000.0
0.0 <= PSERT <= 1000.0

In [ ]:
[v.name for v in mytfa.variables if v.name.startswith("LC_")]

['LC_gam6p_c',
 'LC_cgly_c',
 'LC_achms_c',
 'LC_pcox_u',
 'LC_octe9ACP_c',
 'LC_fdp_c',
 'LC_5caiz_c',
 'LC_pep_c',
 'LC_coa_c',
 'LC_hgbam_c',
 'LC_nac_c',
 'LC_r3mmal_c',
 'LC_leu__L_c',
 'LC_ahcys_c',
 'LC_ru5p__D_c',
 'LC_14dhncoa_c',
 'LC_h2o_cx_c',
 'LC_h2s_c',
 'LC_orot_c',
 'LC_g1p_c',
 'LC_3hdecACP_c',
 'LC_na1_c',
 'LC_2pglyc_c',
 'LC_ala_B_c',
 'LC_glyc3p_c',
 'LC_pqh2_um_p',
 'LC_26dap_LL_c',
 'LC_ddcaACP_c',
 'LC_2pglyc_cx_c',
 'LC_trdox_c',
 'LC_3oddecACP_c',
 'LC_glu__D_c',
 'LC_h_cx_c',
 'LC_dutp_c',
 'LC_paps_c',
 'LC_mg2_c',
 'LC_hdeACP_c',
 'LC_o2_c',
 'LC_anth_c',
 'LC_dhpt_c',
 'LC_thex2eACP_c',
 'LC_fmn_c',
 'LC_pppi_c',
 'LC_udp_c',
 'LC_cit_c',
 'LC_acACP_c',
 'LC_uama_c',
 'LC_eig3p_c',
 'LC_3c4mop_c',
 'LC_lys__L_c',
 'LC_13dpg_c',
 'LC_gmp_c',
 'LC_utp_c',
 'LC_trdrd_c',
 'LC_so4_c',
 'LC_5apru_c',
 'LC_hmppp9_c',
 'LC_pydx5p_c',
 'LC_2dhp_c',
 'LC_ade_c',
 'LC_asp__L_c',
 'LC_2sephchc_c',
 'LC_acg5p_c',
 'LC_gdp_c',
 'LC_hgbyr_c',
 'LC_palmACP_c',
 'LC_pser__L_c',
 'LC_ocACP_c',
 'LC_dttp_c',
 'LC_6pgc_c',
 'LC_gcald_c',
 'LC_2p4c2me_c',
 'LC_cmp_c',
 'LC_bm_pro_c',
 'LC_pi_c',
 'LC_pnto__R_c',
 'LC_dump_c',
 'LC_omppp9_c',
 'LC_23dhmp_c',
 'LC_gtp_c',
 'LC_4h2oglt_c',
 'LC_prfp_c',
 'LC_man1p_c',
 'LC_dxyl5p_c',
 'LC_3hddecACP_c',
 'LC_cu2_c',
 'LC_malACP_c',
 'LC_2mahmp_c',
 'LC_phpyr_c',
 'LC_fe2_c',
 'LC_phllqne_c',
 'LC_toct2eACP_c',
 'LC_dgdp_c',
 'LC_uaccg_c',
 'LC_acald_c',
 'LC_o2s_c',
 'LC_alac__S_c',
 'LC_3hmop_c',
 'LC_4abz_c',
 'LC_prbamp_c',
 'LC_ca2_c',
 'LC_glyclt_c',
 'LC_butACP_c',
 'LC_4ppcys_c',
 'LC_udpgal_c',
 'LC_f6p_c',
 'LC_lac__D_c',
 'LC_his__L_c',
 'LC_agdpcbi_c',
 'LC_s17bp_c',
 'LC_dctp_c',
 'LC_thf_c',
 'LC_25aics_c',
 'LC_ni2_c',
 'LC_dtdp4d6dg_c',
 'LC_malcoa_c',
 'LC_fum_c',
 'LC_bm_cw_c',
 'LC_ACP_c',
 'LC_mlthf_c',
 'LC_h_p',
 'LC_dhf_c',
 'LC_dudp_c',
 'LC_3omrsACP_c',
 'LC_trnaglu_c',
 'LC_pre6a_c',
 'LC_ametam_c',
 'LC_3hhexACP_c',
 'LC_4ppan_c',
 'LC_quln_c',
 'LC_frdp_c',
 'LC_glyald_c',
 'LC_uacgam_c',
 'LC_pram_c',
 'LC_26dap__M_c',
 'LC_gdpmann_c',
 'LC_db4p_c',
 'LC_actACP_c',
 'LC_actp_c',
 'LC_ugmd_c',
 'LC_s7p_c',
 'LC_cbm_c',
 'LC_co2_c',
 'LC_zeax_c',
 'LC_ptrc_c',
 'LC_adp_c',
 'LC_3a2oxpp_c',
 'LC_aspsa_c',
 'LC_tdec2eACP_c',
 'LC_phom_c',
 'LC_amylose_c',
 'LC_5mdr1p_c',
 'LC_rb15bp_cx_c',
 'LC_bcryptox_c',
 'LC_spmd_c',
 'LC_udpsq_c',
 'LC_h2_c',
 'LC_adocbip_c',
 'LC_phycy_c',
 'LC_nadh_c',
 'LC_aps_c',
 'LC_dpcoa_c',
 'LC_xu5p__D_c',
 'LC_no2_c',
 'LC_4hbz_c',
 'LC_3odecACP_c',
 'LC_dhnpt_c',
 'LC_5aprbu_c',
 'LC_iasp_c',
 'LC_nmn_c',
 'LC_bm_pigm_c',
 'LC_2cpr5p_c',
 'LC_pchlld_c',
 'LC_o2_u',
 'LC_ala__L_c',
 'LC_3c2hmp_c',
 'LC_pyr_c',
 'LC_hco3_c',
 'LC_pan4p_c',
 'LC_succ_c',
 'LC_citac_c',
 'LC_h2o_c',
 'LC_h_c',
 'LC_ugmda_c',
 'LC_pq_um_p',
 'LC_man6p_c',
 'LC_cobalt2_c',
 'LC_gam1p_c',
 'LC_argsuc_c',
 'LC_dhap_c',
 'LC_mn2_c',
 'LC_u3hga2_c',
 'LC_2obut_c',
 'LC_dtmp_c',
 'LC_fpram_c',
 'LC_ump_c',
 'LC_3pg_cx_c',
 'LC_pq_cm_c',
 'LC_ahdt_c',
 'LC_npdp_c',
 'LC_dhor__S_c',
 'LC_3opalmACP_c',
 'LC_glx_c',
 'LC_thdp_c',
 'LC_fprica_c',
 'LC_adocbl_c',
 'LC_thr__L_c',
 'LC_so3_c',
 'LC_2m6sbenzq_c',
 'LC_hco3_cx_c',
 'LC_glu5p_c',
 'LC_3hmrsACP_c',
 'LC_4c2me_c',
 'LC_damp_c',
 'LC_histda_c',
 'LC_gthox_c',
 'LC_amp_c',
 'LC_23dhmb_c',
 'LC_5mdru1p_c',
 'LC_mppp9_c',
 'LC_cdp_c',
 'LC_dcaACP_c',
 'LC_2me4p_c',
 'LC_3hpalmACP_c',
 'LC_2ahbut_c',
 'LC_caro_c',
 'LC_3dhq_c',
 'LC_4adcho_c',
 'LC_glu__L_c',
 'LC_bm_cofactors_c',
 'LC_34hpp_c',
 'LC_ctp_c',
 'LC_pqh2_cm_c',
 'LC_fad_c',
 'LC_2shchc_c',
 'LC_dhna_c',
 'LC_co2_cx_c',
 'LC_acg5sa_c',
 'LC_ala__D_c',
 'LC_aicar_c',
 'LC_g6p_c',
 'LC_glu5sa_c',
 'LC_ac_c',
 'LC_pre3b_c',
 'LC_mthgxl_c',
 'LC_3mop_c',
 'LC_5drib_c',
 'LC_e4hglu_c',
 'LC_dgtp_c',
 'LC_cys__L_c',
 'LC_bm_rna_c',
 'LC_hisp_c',
 'LC_lycop_c',
 'LC_citr__L_c',
 'LC_2ahhmp_c',
 'LC_pdx5p_c',
 'LC_2mecdp_c',
 'LC_cbasp_c',
 'LC_dnad_c',
 'LC_datp_c',
 'LC_prlp_c',
 'LC_toctd2eACP_c',
 'LC_cholphya_c',
 'LC_glc__D_c',
 'LC_o2_cx_c',
 'LC_orot5p_c',
 'LC_k_c',
 'LC_amet_c',
 'LC_2ippm_c',
 'LC_pro__L_c',
 'LC_cpppg3_c',
 'LC_h2mb4p_c',
 'LC_thmmp_c',
 'LC_cdpglc_c',
 'LC_xmp_c',
 'LC_co2dam_c',
 'LC_fdxox_c',
 'LC_orn_c',
 'LC_2ahhmd_c',
 'LC_pre6b_c',
 'LC_gln__L_c',
 'LC_3ohexACP_c',
 'LC_3pg_c',
 'LC_pheme_c',
 'LC_methf_c',
 'LC_co1dam_c',
 'LC_mppp9me_c',
 'LC_bm_dna_c',
 'LC_fe3_c',
 'LC_zn2_c',
 'LC_hexACP_c',
 'LC_prephytedp_c',
 'LC_glu1sa_c',
 'LC_chor_c',
 'LC_4per_c',
 'LC_glucys_c',
 'LC_dmpp_c',
 'LC_inost_c',
 'LC_4hthdp_c',
 'LC_applp_c',
 'LC_oaa_c',
 'LC_no3_c',
 'LC_uamag_c',
 'LC_dialurate_c',
 'LC_gcarote_c',
 'LC_ser__L_c',
 'LC_1pyr5c_c',
 'LC_ppi_c',
 'LC_ribflv_c',
 'LC_tyr__L_c',
 'LC_pap_c',
 'LC_25dhpp_c',
 'LC_3nphb_c',
 'LC_h2o_p',
 'LC_pre8_c',
 'LC_3dhsk_c',
 'LC_dhpmp_c',
 'LC_glyc__R_c',
 'LC_dad_5_c',
 'LC_2dda7p_c',
 'LC_acglu_c',
 'LC_imp_c',
 'LC_nad_c',
 'LC_dcamp_c',
 'LC_bm_carbs_c',
 'LC_2ahethmpp_c',
 'LC_imacp_c',
 'LC_dmlz_c',
 'LC_g3p_c',
 'LC_dadp_c',
 'LC_o2_p',
 'LC_fmnh2_c',
 'LC_nadph_c',
 'LC_cbp_c',
 'LC_mi3p__D_c',
 'LC_tmrs2eACP_c',
 'LC_6pgl_c',
 'LC_ppp9_c',
 'LC_mobd_c',
 'LC_bm_memlip_c',
 'LC_dad_2_c',
 'LC_biliverd_c',
 'LC_pre4_c',
 'LC_ggdp_c',
 'LC_pre3a_c',
 'LC_rb15bp_c',
 'LC_3hbutACP_c',
 'LC_histd_c',
 'LC_pphn_c',
 'LC_nicrnt_c',
 'LC_3ooctdACP_c',
 'LC_atp_c',
 'LC_lipidX2_c',
 'LC_2pg_c',
 'LC_pppg9_c',
 'LC_uagmda_c',
 'LC_met__L_c',
 'LC_phyto_c',
 'LC_4hpro_LT_c',
 'LC_1p3h5c_c',
 'LC_hemeO_c',
 'LC_lgt__S_c',
 'LC_h2o_u',
 'LC_adcobhex_c',
 'LC_co_c',
 'LC_sbzcoa_c',
 'LC_e4p_c',
 'LC_accoa_c',
 'LC_asn__L_c',
 'LC_mal__L_c',
 'LC_ocdcaACP_c',
 'LC_ichor_c',
 'LC_pant__R_c',
 'LC_phdp_c',
 'LC_r5p_c',
 'LC_grdp_c',
 'LC_ohpb_c',
 'LC_ipdp_c',
 'LC_arg__L_c',
 'LC_phe__L_c',
 'LC_acgam1p_c',
 'LC_nadp_c',
 'LC_3ig3p_c',
 'LC_val__L_c',
 'LC_dmbzid_c',
 'LC_2a3pp_c',
 'LC_3mob_c',
 'LC_5prdmbz_c',
 'LC_rdmbzi_c',
 'LC_5mthf_c',
 'LC_3hoctACP_c',
 'LC_dvpchlda_c',
 'LC_10fthf_c',
 'LC_4r5au_c',
 'LC_skm_c',
 'LC_gar_c',
 'LC_for_c',
 'LC_dmtphllqne_c',
 'LC_skm5p_c',
 'LC_citm_c',
 'LC_udpg_c',
 'LC_5mta_c',
 'LC_dcdp_c',
 'LC_pcrd_u',
 'LC_myrsACP_c',
 'LC_glutrna_c',
 'LC_adcobdam_c',
 'LC_nh4_c',
 'LC_hom__L_c',
 'LC_acser_c',
 'LC_pre5_c',
 'LC_fdxrd_c',
 'LC_sucbz_c',
 'LC_prpp_c',
 'LC_5aizc_c',
 'LC_dtdp4d6dm_c',
 'LC_but2eACP_c',
 'LC_chlld_c',
 'LC_h_u',
 'LC_gly_c',
 'LC_uppg3_c',
 'LC_dtdp_c',
 'LC_uamr_c',
 'LC_trp__L_c',
 'LC_udcpdp_c',
 'LC_lipidAds2_c',
 'LC_hpyr_c',
 'LC_hcys__L_c',
 'LC_prbatp_c',
 'LC_indole_c',
 'LC_dscl_c',
 'LC_glycogen_c',
 'LC_5aop_c',
 'LC_gthrd_c',
 'LC_fgam_c',
 'LC_adpglc_c',
 'LC_air_c',
 'LC_3hoctaACP_c',
 'LC_hmbil_c',
 'LC_3psme_c',
 'LC_thrp_c',
 'LC_akg_c',
 'LC_thmpp_c',
 'LC_tpalm2eACP_c',
 'LC_h2o2_c',
 'LC_alaala_c',
 'LC_pran_c',
 'LC_tddec2eACP_c',
 'LC_icit_c',
 'LC_3ooctACP_c',
 'LC_4ampm_c',
 'LC_adn_c',
 'LC_4pasp_c',
 'LC_3php_c',
 'LC_ppbng_c',
 'LC_acorn_c',
 'LC_ile__L_c',
 'LC_3c3hmp_c',
 'LC_phthr_c',
 'LC_cynt_c',
 'LC_pqh2_c',
 'LC_cthzp_c',
 'LC_14glucan_c',
 'LC_cobalt2_p',
 'LC_zn2_p',
 'LC_so4_p',
 'LC_spmd_p',
 'LC_ca2_p',
 'LC_nh4_p',
 'LC_arg__L_p',
 'LC_gln__L_p',
 'LC_mn2_p',
 'LC_hco3_p',
 'LC_mg2_p',
 'LC_ptrc_p',
 'LC_fe2_p',
 'LC_cu2_p',
 'LC_k_p',
 'LC_no3_p',
 'LC_fe3_p',
 'LC_mobd_p',
 'LC_ni2_p',
 'LC_cynt_p',
 'LC_pi_p',
 'LC_h2o_e',
 'LC_o2_e',
 'LC_co2_e',
 'LC_cobalt2_e',
 'LC_zn2_e',
 'LC_so4_e',
 'LC_spmd_e',
 'LC_ca2_e',
 'LC_nh4_e',
 'LC_arg__L_e',
 'LC_gln__L_e',
 'LC_mn2_e',
 'LC_hco3_e',
 'LC_mg2_e',
 'LC_ptrc_e',
 'LC_fe2_e',
 'LC_cu2_e',
 'LC_k_e',
 'LC_no3_e',
 'LC_fe3_e',
 'LC_mobd_e',
 'LC_ni2_e',
 'LC_na1_e',
 'LC_cynt_e',
 'LC_co2_p',
 'LC_h_e',
 'LC_na1_p',
 'LC_pi_e',
 'LC_dkmpp_c',
 'LC_dhmtp_c',
 'LC_2kmb_c',
 'LC_tczcaro_c',
 'LC_dczcaro_c',
 'LC_ttclyco_c',
 'LC_6pthp_c',
 'LC_thbpt_c',
 'LC_gthbpt_c',
 'LC_iscssh_c',
 'LC_iscsh_c',
 'LC_this_c',
 'LC_athis_c',
 'LC_thissh_c',
 'LC_imgly_c',
 'LC_2c4mthzep_c',
 'LC_sheme_c',
 'LC_malcoame_c',
 'LC_ogmeACP_c',
 'LC_hgmeACP_c',
 'LC_egmeACP_c',
 'LC_gmeACP_c',
 'LC_opmeACP_c',
 'LC_hpmeACP_c',
 'LC_epmeACP_c',
 'LC_pmeACP_c',
 'LC_pimACP_c',
 'LC_meoh_c',
 'LC_8aonn_c',
 'LC_dann_c',
 'LC_amob_c',
 'LC_dtbt_c',
 'LC_btn_c',
 'LC_btamp_c',
 'LC_octapb_c',
 'LC_lipopb_c',
 'LC_meoh_p',
 'LC_meoh_e',
 'LC_cph4_c',
 'LC_cdg_c',
 'LC_preq0_c',
 'LC_preq1_c',
 'LC_preqtrna_c',
 'LC_epxqtrna_c',
 'LC_quetrna_c',
 'LC_udpglcur_c',
 'LC_udpxyl_c',
 'LC_gdpddman_c',
 'LC_gdpfuc_c',
 'LC_cdp4dh6doglc_c',
 'LC_ocdca_c',
 'LC_ocdcal_c',
 'LC_hpdcn_c',
 'LC_1hdecg3p_c',
 'LC_1hdec9eg3p_c',
 'LC_1odec9eg3p_c',
 'LC_pa160_c',
 'LC_pa1619Z160_c',
 'LC_pa161_c',
 'LC_pa1819Z1619Z_c',
 'LC_pa1819Z160_c',
 'LC_12dgr160_c',
 'LC_12dgr1619Z160_c',
 'LC_12dgr161_c',
 'LC_12dgr1819Z1619Z_c',
 'LC_12dgr1819Z160_c',
 'LC_sqdg160_c',
 'LC_sqdg1619Z160_c',
 'LC_mgdg1619Z160_c',
 'LC_dgdg1619Z160_c',
 'LC_dgdg161_c',
 'LC_mgdg161_c',
 'LC_dgdg1819Z1619Z_c',
 'LC_mgdg1819Z1619Z_c',
 'LC_cdp12dgr1819Z160_c',
 'LC_pgp1819Z160_c',
 'LC_pg1819Z160_c',
 'LC_glcdg1619Z160_c',
 'LC_glcdg161_c',
 'LC_glcdg1819Z1619Z_c',
 'LC_glcdg1819Z160_c',
 'LC_mgdg1819Z160_c',
 'LC_dgdg1819Z160Z_c',
 'LC_glntrna_c',
 'LC_trnagln_c',
 'LC_trnatyr_c',
 'LC_tyrtrna_c',
 'LC_trnamet_c',
 'LC_mettrna_c',
 'LC_trnaser_c',
 'LC_sertrna_c',
 'LC_glytrna_c',
 'LC_trnagly_c',
 'LC_protrna_c',
 'LC_trnapro_c',
 'LC_trnacys_c',
 'LC_cystrna_c',
 'LC_trnaarg_c',
 'LC_argtrna_c',
 'LC_trnatrp_c',
 'LC_trptrna_c',
 'LC_phetrna_c',
 'LC_trnaphe_c',
 'LC_trnahis_c',
 'LC_histrna_c',
 'LC_asntrna_c',
 'LC_asptrna_c',
 'LC_trnaasp_c',
 'LC_trnathr_c',
 'LC_thrtrna_c',
 'LC_trnaleu_c',
 'LC_leutrna_c',
 'LC_trnaile_c',
 'LC_iletrna_c',
 'LC_trnalys_c',
 'LC_lystrna_c',
 'LC_alatrna_c',
 'LC_trnaala_c',
 'LC_valtrna_c',
 'LC_trnaval_c',
 'LC_fmettrna_c',
 'LC_photon410_e',
 'LC_photon430_e',
 'LC_photon450_e',
 'LC_photon470_e',
 'LC_photon490_e',
 'LC_photon510_e',
 'LC_photon530_e',
 'LC_photon550_e',
 'LC_photon570_e',
 'LC_photon590_e',
 'LC_photon610_e',
 'LC_photon630_e',
 'LC_photon650_e',
 'LC_photon670_e',
 'LC_photon690_e',
 'LC_calxan_c',
 'LC_nstxan_c',
 'LC_chla_qy1_exc_c',
 'LC_pho_loss_c',
 'LC_u23ga2_c',
 'LC_u3aga2_c',
 'LC_ara5p_c',
 'LC_kdo8p_c',
 'LC_kdo_c',
 'LC_ckdo_c',
 'LC_uacmam_c',
 'LC_udcpp_c',
 'LC_unaga_c',
 'LC_kdolipid4cy_c',
 'LC_unagam_c',
 'LC_uaagmda_c',
 'LC_murein5p5p_p',
 'LC_murein5p5p5p_p',
 'LC_ala__D_p',
 'LC_murein5px4p_p',
 'LC_alaala_p',
 'LC_murein4px4p_p',
 'LC_murein4px4px4p_p',
 'LC_murein5p4p_p',
 'LC_murein4p4p_p',
 'LC_murein4p3p_p',
 'LC_murein3px4p_p',
 'LC_murein4px4p4p_p',
 'LC_murein3p3p_p',
 'LC_anhgm4p_p',
 'LC_anhgm3p_p',
 'LC_anhgm_c',
 'LC_LalaDgluMdapDala_c',
 'LC_anhgm4p_c',
 'LC_LalaDgluMdapDala_p',
 'LC_anhgm3p_c',
 'LC_anhm4p_c',
 'LC_anhm_c',
 'LC_anhm3p_c',
 'LC_LalaDgluMdap_c',
 'LC_LalaDglu_c',
 'LC_um4p_c',
 'LC_LalaLglu_c',
 'LC_pchlld_exc_c',
 'LC_fldox_c',
 'LC_fldrd_c',
 'LC_leu__L_p',
 'LC_leu__L_e',
 'LC_no2_p',
 'LC_chla_qy2_exc_c',
 'LC_p700_um_p',
 'LC_p700_exc_um_p',
 'LC_p680_exc_um_p',
 'LC_p680_um_p',
 'LC_hmgth_c',
 'LC_Sfglutth_c',
 'LC_5oxpro_c',
 'LC_acmum6p_c',
 'LC_cl_p',
 'LC_cl_c',
 'LC_cl_e',
 'LC_k_u',
 'LC_ps2d1_um_p',
 'LC_ps2d1_exc_um_p',
 'LC_34dhmald_c',
 'LC_34dhoxpeg_c',
 'LC_3hcddec5eACP_c',
 'LC_t3c5ddeceACP_c',
 'LC_3hcmrs7eACP_c',
 'LC_t3c7mrseACP_c',
 'LC_3hcpalm9eACP_c',
 'LC_t3c9palmeACP_c',
 'LC_3hcvac11eACP_c',
 'LC_t3c11vaceACP_c',
 'LC_3ocddec5eACP_c',
 'LC_3ocmrs7eACP_c',
 'LC_3ocpalm9eACP_c',
 'LC_3ocvac11eACP_c',
 'LC_cdec3eACP_c',
 'LC_cddec5eACP_c',
 'LC_tdeACP_c',
 'LC_aacoa_c',
 'LC_3hbcoa__R_c',
 'LC_4abut_c',
 'LC_sucsal_c',
 'LC_4abutn_c',
 'LC_appl_c',
 'LC_adocbi_c',
 'LC_C04051_c',
 'LC_4ahmmp_c',
 'LC_ala__L_p',
 'LC_glyc_c',
 'LC_etoh_c',
 'LC_id3acald_c',
 'LC_ind3ac_c',
 'LC_4gudbd_c',
 'LC_4gudbutn_c',
 'LC_pad_c',
 'LC_pac_c',
 'LC_iad_c',
 'LC_pmcoa_c',
 'LC_bamppald_c',
 'LC_echin_c',
 'LC_s_c',
 'LC_ficytc6_u',
 'LC_pqh2_u',
 'LC_focytc6_u',
 'LC_pq_u',
 'LC_pqh2_p',
 'LC_pq_p',
 'LC_ficytc6_p',
 'LC_focytc6_p',
 'LC_pcox_p',
 'LC_pcrd_p',
 'LC_cu2_u',
 'LC_mercppyr_c',
 'LC_cdpdhdecg_c',
 'LC_cdpdhdec9eg_c',
 'LC_pa180_c',
 'LC_cdpdodecg_c',
 'LC_pa181_c',
 'LC_cdpdodec11eg_c',
 'LC_pa181_9_c',
 'LC_cdpdodec9eg_c',
 'LC_pa182_9_12_c',
 'LC_cdpdodec912eg_c',
 'LC_pa183_6_9_12_c',
 'LC_cdpdodec6912eg_c',
 'LC_pa183_9_12_15_c',
 'LC_cdpdodec91215eg_c',
 'LC_pa184_6_9_12_15_c',
 'LC_cdpdodec691215eg_c',
 'LC_23dhdp_c',
 'LC_decdp_c',
 'LC_octeACP_c',
 'LC_f1p_c',
 'LC_5fthf_c',
 'LC_dtdpglu_c',
 'LC_1odecg3p_c',
 'LC_1odec11eg3p_c',
 'LC_octe_9_ACP_c',
 'LC_1odec912eg3p_c',
 'LC_octe_9_12_ACP_c',
 'LC_1odec691215eg3p_c',
 'LC_octe_6_9_12_15_ACP_c',
 'LC_1odec91215eg3p_c',
 'LC_octe_9_12_15_ACP_c',
 'LC_1odec6912eg3p_c',
 'LC_octe_6_9_12_ACP_c',
 'LC_fadh2_c',
 'LC_g6p_B_c',
 'LC_bglycogen_c',
 'LC_glcglyc_c',
 'LC_glcglyc_p',
 'LC_glutrna_gln_c',
 'LC_glu__L_p',
 'LC_2h3oppan_c',
 'LC_gly_p',
 'LC_35cgmp_c',
 'LC_3hmp_c',
 'LC_mmtsa_c',
 'LC_his__L_p',
 'LC_im4act_c',
 'LC_im4ac_c',
 'LC_lald__D_c',
 'LC_lald__L_c',
 'LC_12ppd__S_c',
 'LC_15dap_c',
 'LC_lys__L_p',
 'LC_mi1p__D_c',
 'LC_mppp9om_c',
 'LC_dvpchlld_c',
 'LC_n4abutn_c',
 'LC_4aabutn_c',
 'LC_q8_c',
 'LC_q8h2_c',
 'LC_didp_c',
 'LC_ditp_c',
 'LC_idp_c',
 'LC_itp_c',
 'LC_cytd_c',
 'LC_3ophb_c',
 'LC_2oph_c',
 'LC_lpam_c',
 'LC_adhlam_c',
 'LC_dhlam_c',
 'LC_pgp160_c',
 'LC_pgp161_c',
 'LC_pgp180_c',
 'LC_pgp181_c',
 'LC_pgp181_9_c',
 'LC_pgp182_9_12_c',
 'LC_pgp183_6_9_12_c',
 'LC_pgp183_9_12_15_c',
 'LC_pgp184_6_9_12_15_c',
 'LC_phytoe_c',
 'LC_r1p_c',
 'LC_pro__L_p',
 'LC_pyam5p_c',
 'LC_pydxn_c',
 'LC_pydx_c',
 'LC_pydam_c',
 'LC_sl26da_c',
 'LC_sl2a6o_c',
 'LC_ser__L_p',
 'LC_suc6p_c',
 'LC_sqdg161_c',
 'LC_12dgr180_c',
 'LC_sqdg180_c',
 'LC_12dgr181_c',
 'LC_sqdg181_c',
 'LC_12dgr181_9_c',
 'LC_12dgr182_9_12_c',
 'LC_sqdg182_9_12_c',
 'LC_12dgr183_6_9_12_c',
 'LC_sqdg183_6_9_12_c',
 'LC_12dgr183_9_12_15_c',
 'LC_12dgr184_6_9_12_15_c',
 'LC_sqdg184_6_9_12_15_c',
 'LC_sql_c',
 'LC_dptne_c',
 'LC_dpterol_c',
 'LC_succoa_c',
 'LC_sucr_p',
 'LC_dtdprmn_c',
 'LC_thfglu_c',
 'LC_4hba_c',
 'LC_4mpetz_c',
 'LC_dxyl_c',
 'LC_4mhetz_c',
 'LC_u23ga_c',
 'LC_u3hga_c',
 'LC_u3aga_c',
 'LC_uGgl_c',
 'LC_uGgla_c',
 'LC_uppg1_c',
 'LC_cpppg1_c',
 'LC_n2_e',
 'LC_fdxo_42_c',
 'LC_fdxr_42_c',
 'LC_n2_c',
 'LC_14glucan_p',
 'LC_23doguln_c',
 'LC_23doguln_p',
 'LC_2ddara_c',
 'LC_2doxg6p_c',
 'LC_2dglc_p',
 'LC_2dhguln_c',
 'LC_glcn_c',
 'LC_idon__L_c',
 'LC_2dglc_c',
 'LC_mercpeth_c',
 'LC_dtgcl_c',
 'LC_2hptcl_c',
 'LC_2hptcoa_c',
 'LC_msa_c',
 'LC_3amac_c',
 'LC_3hppnl_c',
 'LC_3hpp_c',
 'LC_uri_p',
 'LC_3ump_p',
 'LC_cytd_p',
 'LC_3cmp_p',
 'LC_adn_p',
 'LC_3amp_p',
 'LC_3gmp_p',
 'LC_gsn_p',
 'LC_oxadpcoa_c',
 'LC_LalaDgluMdap_p',
 'LC_sla_c',
 'LC_dhps_c',
 'LC_4abzglu_c',
 'LC_4hthr_c',
 'LC_5dglcn_c',
 'LC_sf_c',
 'LC_sfp_c',
 'LC_malthx_p',
 'LC_acac_c',
 'LC_btcoa_c',
 'LC_3ohcoa_c',
 'LC_3oocoa_c',
 'LC_hxcoa_c',
 'LC_occoa_c',
 'LC_3odcoa_c',
 'LC_3oddcoa_c',
 'LC_dcacoa_c',
 'LC_ddcacoa_c',
 'LC_3otdcoa_c',
 'LC_3ohdcoa_c',
 'LC_tdcoa_c',
 'LC_3ohodcoa_c',
 'LC_pmtcoa_c',
 'LC_ppcoa_c',
 'LC_ppa_c',
 'LC_acgam6p_c',
 'LC_acgam_p',
 'LC_acmana_p',
 'LC_acmanap_c',
 'LC_acmum_p',
 'LC_acnam_c',
 'LC_acmana_c',
 'LC_b2coa_c',
 'LC_acolipa_p',
 'LC_acolipa_e',
 'LC_aconm_c',
 'LC_acon_T_c',
 'LC_acon_C_c',
 'LC_oxalcoa_c',
 'LC_oxa_c',
 'LC_ribflv_p',
 'LC_fmn_p',
 'LC_ddcap_c',
 'LC_ttdcap_c',
 'LC_ttdceap_c',
 'LC_hdcap_c',
 'LC_hdceap_c',
 'LC_ocdcap_c',
 'LC_ocdceap_c',
 'LC_apoACP_c',
 'LC_ac_p',
 'LC_adocbl_p',
 'LC_adocbl_e',
 'LC_adprib_c',
 'LC_anhgm_p',
 'LC_adphep_LD_c',
 'LC_adphep_DD_c',
 'LC_ag_e',
 'LC_ag_c',
 'LC_S2hglut_c',
 'LC_mththf_c',
 'LC_mththf_p',
 'LC_akg_p',
 'LC_pacald_c',
 'LC_ppal_c',
 'LC_dha_c',
 'LC_all6p_c',
 'LC_allul6p_c',
 'LC_alltt_c',
 'LC_alltn_c',
 'LC_all__D_p',
 'LC_all__D_c',
 'LC_alpp_p',
 'LC_lpp_p',
 'LC_pe160_p',
 'LC_2agpe160_p',
 'LC_pg160_p',
 'LC_2agpg160_p',
 'LC_acetol_c',
 'LC_malt_c',
 'LC_maltttr_c',
 'LC_malttr_c',
 'LC_maltpt_c',
 ...]

# Find reactions for building lexicon for iDT1294

In [ ]:
# Add PHB_REACTIONS

# Acetyl-CoA C-acetyltransferase
#Acetyl-CoA:acetoacetyl-CoA transferase
#Acetoacetyl CoA reductase
#3 hydroxyacyl CoA dehydrogenase  acetoacetyl CoA
#3-ketoacyl-CoA thiolase

PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

phb_mets = set()

for rxn_id in PHB_REACTIONS:
    rxn = cobra_model_mat.reactions.get_by_id(rxn_id)
    for met in rxn.metabolites:
        phb_mets.add(met)

for met in sorted(phb_mets, key=lambda m: m.id):
    print(f"{met.id}\t{met.name}\t{met.formula}\t{met.compartment}")

3hbcoa__R_c	(R)-3-Hydroxybutyryl-CoA	C25H39N7O18P3S	c
3hbcoa_c	(S)-3-Hydroxybutanoyl-CoA	C25H38N7O18P3S	c
3hbycoa_c	S  3 Hydroxybutyryl CoA C25H38N7O18P3S	C25H38N7O18P3S	c
aacoa_c	Acetoacetyl-CoA	C25H37N7O18P3S	c
ac_c	Acetate	C2H3O2	c
acac_c	Acetoacetate	C4H5O3	c
accoa_c	Acetyl-CoA	C23H35N7O17P3S	c
coa_c	Coenzyme A	C21H33N7O16P3S	c
h_c	H+	H	c
nad_c	Nicotinamide adenine dinucleotide	C21H26N7O14P2	c
nadh_c	Nicotinamide adenine dinucleotide - reduced	C21H27N7O14P2	c
nadp_c	Nicotinamide adenine dinucleotide phosphate	C21H26N7O17P3	c
nadph_c	Nicotinamide adenine dinucleotide phosphate - reduced	C21H27N7O17P3	c

In [ ]:
from pytfa.io import annotate_from_lexicon

lexicon = pd.read_csv("phb_lexicon.csv")

annotate_from_lexicon(
    mytfa,
    lexicon,
    inplace=True
)

## Check TFA R. palustris

In [ ]:
# Convert DataFrame → dict lexicon
lexicon_dict = (
    lexicon['seed_id']
    .dropna()
    .astype(str)
    .to_dict()
)

print(type(lexicon_dict))
print(len(lexicon_dict))
print(list(lexicon_dict.items())[:5])

<class 'dict'>
8
[('glc__D_c', 'cpd00027'), ('pyr_c', 'cpd00020'), ('accoa_c', 'cpd00022'), ('atp_c', 'cpd00002'), ('adp_c', 'cpd00008')]

In [ ]:
import pandas as pd

rows = []
for m in cobra_model_mat.metabolites:
    rows.append({
        "met_id": m.id,
        "name": m.name,
        "formula": m.formula,
        "charge": m.charge,
        "compartment": m.compartment
    })

df = pd.DataFrame(rows)
df.to_csv("metabolites_for_mapping.csv", index=False)

# Assing deltaG0_prime to important reactions

In [ ]:
from pytfa.optim.variables import DeltaG

PHB_REACTION_THERMO = {
    "ACACT1r": {      # 2 acetyl-CoA ⇌ acetoacetyl-CoA + CoA
        "delta_g0": +18.0,
        "uncertainty": 5.0
    },

    "AACOAR_syn": {   # acetoacetyl-CoA + NADPH → 3HB-CoA + NADP+
        "delta_g0": -25.0,
        "uncertainty": 5.0
    },

    "PHBS_syn": {     # polymerization (CoA-releasing)
        "delta_g0": -35.0,
        "uncertainty": 7.0
    },

    "ACACCT": {       # CoA transfer / activation
        "delta_g0": -10.0,
        "uncertainty": 5.0
    }
}


for rxn_id in PHB_REACTION_THERMO:
    rxn = tmodel.reactions.get_by_id(rxn_id)
    dg_vars = [v for v in tmodel.variables.values() if isinstance(v, DeltaG) and v.reaction == rxn]
    print(rxn_id, "ΔG vars:", dg_vars)

ACACT1r ΔG vars: []
AACOAR_syn ΔG vars: []
PHBS_syn ΔG vars: []
ACACCT ΔG vars: []

In [ ]:
thermo_data2['cues'].update({
    "AACOAR_syn": {"delta_g0": -25.0, "uncertainty": 5.0},
    "PHBS_syn":    {"delta_g0": -20.0, "uncertainty": 5.0},
    "ACACT1r":     {"delta_g0": -10.0, "uncertainty": 5.0},
    "ACACCT":      {"delta_g0": -15.0, "uncertainty": 5.0},
})

In [ ]:
# Reactions of interest
phb_reactions = ["AACOAR_syn", "ACACT1r"]

thermo_mets = thermo_data["metabolites"]  # ThermoDB compounds dict

def normalize(s):
    return s.lower().replace("-", "").replace("_", "").replace(" ", "")

print("\n=== PHB Reactions: On-the-fly ThermoDB mapping ===")

for rxn_id in phb_reactions:
    if rxn_id not in model.reactions:
        print(f"\n Reaction {rxn_id} not in model")
        continue

    rxn = model.reactions.get_by_id(rxn_id)
    print(f"\nReaction: {rxn_id}")
    print(rxn.build_reaction_string())
    print("-" * 70)

    for met in rxn.metabolites:
        print(f"\nMetabolite: {met.id}")
        print(f"  Name:        {met.name}")
        print(f"  Formula:     {met.formula}")
        print(f"  Compartment: {met.compartment}")

        formula_hits = []
        name_hits = []

        for seed_id, tmeta in thermo_mets.items():
            # Formula match
            if met.formula and tmeta.get("formula") == met.formula:
                formula_hits.append((seed_id, tmeta.get("name")))

            # Name match (loose)
            if met.name and normalize(met.name) in normalize(tmeta.get("name", "")):
                name_hits.append((seed_id, tmeta.get("name")))

        if formula_hits:
            print("  🔬 ThermoDB formula matches:")
            for sid, name in formula_hits[:5]:
                print(f"     - seed_id: {sid} | {name}")
        else:
            print("   No ThermoDB formula matches")

        if name_hits:
            print("  🧬 ThermoDB name matches:")
            for sid, name in name_hits[:5]:
                print(f"     - seed_id: {sid} | {name}")
        else:
            print("  ❌ No ThermoDB name matches")

=== PHB Reactions: On-the-fly ThermoDB mapping ===

Reaction: AACOAR_syn
aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]
----------------------------------------------------------------------

Metabolite: h[c]
  Name:        H+
  Formula:     H
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: h_cx[c] | None
     - seed_id: h[c] | None
  ❌ No ThermoDB name matches

Metabolite: nadph[c]
  Name:        Nicotinamide adenine dinucleotide phosphate - reduced
  Formula:     C21H27N7O17P3
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: nadph[c] | None
  ❌ No ThermoDB name matches

Metabolite: aacoa[c]
  Name:        Acetoacetyl-CoA
  Formula:     C25H37N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: aacoa[c] | None
  ❌ No ThermoDB name matches

Metabolite: nadp[c]
  Name:        Nicotinamide adenine dinucleotide phosphate
  Formula:     C21H26N7O17P3
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: nadp[c] | None
  ❌ No ThermoDB name matches

Metabolite: 3hbcoa__R[c]
  Name:        (R)-3-Hydroxybutyryl-CoA
  Formula:     C25H39N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: 3hbcoa__R[c] | None
  ❌ No ThermoDB name matches

Reaction: ACACT1r
2.0 accoa[c] --> aacoa[c] + coa[c]
----------------------------------------------------------------------

Metabolite: accoa[c]
  Name:        Acetyl-CoA
  Formula:     C23H35N7O17P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: accoa[c] | None
  ❌ No ThermoDB name matches

Metabolite: coa[c]
  Name:        Coenzyme A
  Formula:     C21H33N7O16P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: coa[c] | None
  ❌ No ThermoDB name matches

Metabolite: aacoa[c]
  Name:        Acetoacetyl-CoA
  Formula:     C25H37N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: aacoa[c] | None
  ❌ No ThermoDB name matches

In [ ]:
# List of reactions of interest
phb_reactions = ["AACOAR_syn", "ACACT1r"] #"PHBS_syn","ACACCT"

print("=== PHB Reactions Metabolites ===")
for rxn_id in phb_reactions:
    if rxn_id not in model.reactions:
        print(f"Reaction {rxn_id} not in model")
        continue

    rxn = model.reactions.get_by_id(rxn_id)
    print(f"\nReaction: {rxn_id} | Equation: {rxn.build_reaction_string()}")
    print(f"{'Metabolite ID':<20} | {'Formula':<15} | {'Compartment'}")
    print("-"*55)

    for met, coeff in rxn.metabolites.items():
        # check if formula exists
        formula = met.formula if met.formula is not None else "None"
        print(f"{met.id:<20} | {formula:<15} | {met.compartment}")

=== PHB Reactions Metabolites ===

Reaction: AACOAR_syn | Equation: aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]
Metabolite ID        | Formula         | Compartment
-------------------------------------------------------
h[c]                 | H               | c
nadph[c]             | C21H27N7O17P3   | c
aacoa[c]             | C25H37N7O18P3S  | c
nadp[c]              | C21H26N7O17P3   | c
3hbcoa__R[c]         | C25H39N7O18P3S  | c

Reaction: ACACT1r | Equation: 2.0 accoa[c] --> aacoa[c] + coa[c]
Metabolite ID        | Formula         | Compartment
-------------------------------------------------------
accoa[c]             | C23H35N7O17P3S  | c
coa[c]               | C21H33N7O16P3S  | c
aacoa[c]             | C25H37N7O18P3S  | c

In [ ]:
from pytfa.optim.variables import DeltaG

for rxn_id in PHB_REACTION_THERMO:
    rxn = mytfa.reactions.get_by_id(rxn_id)

    dg_vars = [
        v for v in mytfa.variables.values()
        if isinstance(v, DeltaG) and v.reaction == rxn
    ]

    print(rxn_id, "ΔG vars:", dg_vars)

ACACT1r ΔG vars: []
AACOAR_syn ΔG vars: []
PHBS_syn ΔG vars: []
ACACCT ΔG vars: []

# Check up thermodata

In [ ]:
# CHECK METABOLITES FORMULAS (OR NAME)
names = [entry['formula'] for entry in thermo_data['metabolites'].values()]
thermo_formulas = [str(f) for f in names if f is not None]
print(thermo_formulas)

['C6H12O9P', 'C37H56N8O9', 'CH3Br', 'C19H15N3O7', 'C21H26N2O6Cl2', 'NA', 'C18H16N6O8S3', 'C5H10O8P', 'C30H50O4', 'C22H29N7O5', 'C15H28N2', 'C27H46O', 'C22H16N4O', 'C7H17N4O', 'C36H61N7O17P3S', 'C19H21N7O6', 'C30H51N7O7', 'C23H31NO7', 'C9H14N4O4', 'C10H14CaO6', 'C15H26O2', 'C3H4N2', 'H2Cu2O', 'C6H7O3RS', 'C8H11NO', 'C14H14O4', 'C16H20N2O2', 'C20H28O', 'C28H50O2', 'C16H17NO2', 'C40H60', 'C7H9N2', 'C11H18N2O2S', 'C20H30N6O12S2', 'C16H21N4O9', 'C15H16O2', 'C60H78OSn2', 'C12H19N2O', 'C9H11O11PR3', 'C18H26O4', 'C8H16N2O4Se2', 'C13H20O', 'C9H16N4OS', 'C6H14O6', 'C7H10N2O3', 'C10H12O2', 'C20H32', 'NA', 'NA', 'C27H34O5', 'C9H9O5', 'C15H20O3', 'C35H32N4O5Mg', 'C35H44O16', 'C12H6O4', 'CNR', 'C20H24O6', 'C8H18O4S4', 'C8H10O', 'NA', 'C23H18O8', 'C11H16O16P2R2', 'C22H24N3OCl', 'C4H8O2', 'C19H28O3', 'C40H71N3O15P2', 'C8H8NO4', 'C25H39N7O18P3S', 'C23H26O8', 'C30H50O', 'C16H16O11', 'C17H22N3', 'C11H17O2', 'NA', 'C19H11O2', 'C18H26NO6', 'C24H47NO10S', 'C13H16N2O3', 'C19H25N2O', 'C20H25N2OS', 'C34H63N2O6SCl', 'C17H19N3', 'C21H32N6O3', 'C25H33NO', 'C6H4O2Cl2', 'C13H14N2O4S2', 'C18H16O4', 'C6H9N2O6S', 'C16H30O', 'C21H33OF', 'C18H29O3', 'C23H34N2O19P2R4S', 'C12H24O11', 'C88H97N9O33Cl2', 'C16H10O5', 'C10H16O2', 'C17H24NO4', 'C30H46N8O18P3S', 'C31H34O12', 'C3H6O5P', 'C5H6NO2', 'C36H52O8', 'C5H11NO2S', 'C10H16O2', 'C14H12N4O2', 'C8H5O4', 'C19H20NO4', 'C67H110O17P2', 'C7H8NCl', 'C48H74O4', 'C6H6NR', 'C4H12N2', 'C18H21O8RS', 'C27H46O', 'C32H54N2O4', 'C19H24O3', 'C18H16N2O3', 'C22H27O8Cl', 'C18H31O16R', 'C8H11N', 'C24H17O8', 'C15H11NO2', 'C5H8NO4', 'C18H24NO4', 'NA', 'C28H34N5O5', 'C16H18NO3', 'C16H28NO5', 'NA', 'C16H23NO3', 'C9H10O2', 'C39H70N2O19', 'C21H29O3F', 'C23H22O7', 'C19H17N3O', 'C20H24O6', 'C4H8O2', 'C22H28O8', 'C7H6NO3', 'C23H30O6', 'C21H23NO3', 'C5H6O5', 'C11H13N', 'NA', 'C10H13Cl3', 'C6H12O5', 'C6H11O6R', 'C23H21O5', 'NA', 'C4H10N', 'C63H88CoN14O14P', 'C6H13N4O9P2', 'C13H22N3O5', 'C2H3O3', 'C21H27N7O14P2', 'C15H21N3O15P2', 'C8H15N2O4PS3', 'NA', 'C87H171O4', 'C36H62O31', 'C5H12N2S', 'NA', 'C17H36', 'C28H46O', 'C10H6O4', 'C4Cl6', 'C9H10NO6', 'NA', 'C7H5O5', 'C10H9O4', 'C6H5F', 'C18H32O16', 'C42H85NO3', 'C5H10N2O3', 'C18H12', 'C7H14N5O2R2', 'C18H16O3', 'C22H22N3O3F', 'C12H7OCl3', 'C3H4O2R', 'C63H97N14O14S', 'C65H116O17P2', 'C10H18O', 'C21H23N2O5S2', 'C41H70N2O17P2', 'C11H23NO2', 'C20H32O2', 'C19H17N3O5SCl', 'C13H11NO2Cl2', 'C24H34N2O', 'C17H21O3', 'C17H22O5', 'C21H44N7O18P2', 'C17H14O4S', 'C9H10O3', 'C22H20O10', 'C10H10O4', 'C23H38O', 'C16H24NO2', 'C30H47O3', 'C14H9NO3', 'C4H6N2O3R2', 'C15H22O3', 'C17H21NO3', 'C19H40N5O6', 'C6H11O5SAu', 'C15H12', 'C29H37N4O4', 'C16H26O4', 'NA', 'C3H3O5P', 'C33H38N4O8', 'C10H10NO4', 'C21H28N2O3', 'C13H16O2', 'NA', 'C10H16O', 'C15H14O11', 'C4H6NO4', 'C39H42N6O18', 'C11H8NO4', 'C17H23N2O4S', 'C4H7NO2', 'C23H29N7O6', 'C13H18NOCl', 'C16H20N5O4Br2', 'C18H24NO', 'C11H8', 'C11H16N5Cl', 'NA', 'C20H32', 'C21H16O8', 'C5H3O3', 'C18H15N2OCl3', 'C8H15NO9P', 'C10H6N2Cl2', 'C12H2OCl6', 'C11H19N4O6', 'C13H7N2O4SCl2F3', 'C5H7N3O5', 'NA', 'C37H50N2O', 'C16H16N3O6', 'C21H38O9P', 'C15H16O4', 'C40H62N8O21', 'X', 'C6H12O6', 'C12H16O6', 'C23H34N2O19P2R4S', 'C20H18O5', 'C14H10O5', 'C11H7O2', 'C39H49N5O7', 'C12H22N2O2', 'C21H24O5', 'C3H5Cl', 'C11H20NO9S2', 'C13H15NO6', 'C29H45O3', 'C6H6O2', 'C20H24O2', 'C7H16N8O4', 'C88H178NO9P', 'C2H5OCl', 'C14H21O8PR3', 'C6H7NO', 'C13H6NO2Cl4', 'C13H6N3O6Br2', 'C6H7O6', 'C9H9N', 'C22H39N2O8PRS', 'C20H40N3O16P', 'C8H7NO', 'C15H29OX', 'C6H3O5Cl', 'C11H15N2S', 'C5H9O3R', 'C21H22O6', 'C16H13O3', 'NA', 'C24H14', 'C14H7NO2Br2', 'C21H30O3', 'C10H14O', 'C44H51NO17', 'C25H46NO8R', 'C19H18O6', 'C20H24O3', 'C9H10O2', 'C5H7N2O3', 'C23H44O5', 'C8H4O5', 'C16H22O8', 'C35H43N6O15', 'H2N3O9Bi', 'C27H46O2', 'C14H17N3O15P2R2', 'C21H26NO5', 'C15H15NO2', 'C40H56O4', 'C6H11O4', 'C9H4O4Br2', 'C45H46N4O17', 'C20H31O4', 'C15H22O', 'C21H44N4O13', 'C20H27O3', 'C92H176O16P', 'C12H16O15R2S2*2', 'C40H48N4O2', 'C34H52N7O24P2', 'C80H124N16O42', 'C23H27NO8', 'C8H12N2O2', 'C45H72O16', 'C53H68N9O10S', 'C21H42O7P', 'C45H54N4O14', 'C6H13NO2', 'C2H2O2R2', 'C17H14O7', 'C36H54O8', 'C19H23NO3', 'C34H37N3O6', 'C15H16O', 'C6H12O5', 'C10H13N2Cl', 'C21H34O2', 'C6H9O3', 'C38H44N2O6', 'C32H40N5O5Br', 'C28H34O14', 'C16H17NO4', 'C23H38O5', 'NA', 'O3S2', 'C5H12O', 'C40H64NO10', 'C19H25N2', 'C10H12N5O4Br', 'C17H26NO3', 'C14H10O2', 'C18H14NO4', 'C14H12Cl2', 'C25H49O2', 'C9H7NO', 'HFeS', 'C176H307N2O100P4', 'C21H30O2', 'C19H37N8O8', 'C24H21O12', 'C30H40O8', 'C3H4NO2R2', 'C12H24NO10', 'C87H117N13O19S2', 'C6H9O6', 'C7H8N2O2', 'C6H15O3PS2', 'C9H13NO', 'NA', 'C28H36N7O17P3SF', 'C12H14O4PCl3', 'C4H9NO2Se', 'C16H14O4Cl2', 'C10H17ORS', 'C18H15ClSn', 'C16H14O5', 'C6H11NO2', 'C21H26O4S', 'C12H3OCl6', 'C12H24N4S8Se', 'C14H17NO6', 'C6H13N3O2', 'C23H34O5', 'C27H42O', 'C5H9O6', 'C12H10O', 'C15H22O2', 'C17H26O9', 'NA', 'C53H78O17', 'C22H21N2O7Cl', 'C6H10N2O3R2', 'C43H49NO19', 'C14H10O6', 'C21H28O2F2', 'C15H10O4', 'C21H23O8', 'C8H12NO3', 'C13H4N4O4Cl2F6', 'C47H77O14', 'NA', 'C10H12N5O3R', 'NA', 'C15H10N2O2', 'C8H13O4RS', 'C21H26O10', 'C11H19N5S', 'C18H26NO6', 'C6H6O2', 'C21H42N7O15P', 'C7H12N4O3', 'C10H20O', 'C19H23O6', 'NA', 'C11H15N4O5', 'C41H61N9O28P2', 'NA', 'C46H64N8O14', 'C22H39N2O8PRS', 'C22H26N10O2Br2', 'C23H32O2', 'C12H26', 'C15H12O5', 'C6H6NO3S', 'C12H4Cl6', 'C22H22N3O5Cl', 'C19H40NO7P', 'C20H15N3O', 'C14H21NO8', 'C20H32O', 'NA', 'C28H46O3', 'C37H34N2O9S3', 'C8H14NO4', 'C10H19N5O', 'C22H26O8', 'C20H35N2O9PRS', 'C15H15N2O2Cl', 'C20H22O6', 'C10H13N5O10P2', 'C18H37NO2', 'C27H46O3', 'CH6N', 'C15H23O3', 'C21H43N7O12', 'C13H12O2', 'Ba', 'C14H16N5O7S2', 'C5H6O8PR2', 'C18H10', 'C5H11O2As', 'C17H25N3O4S2', 'C25H39N7O18P3S', 'C35H42N5O5', 'C27H27O5', 'C6H6N4S', 'C7H8NO4', 'C35H43N5O9', 'C22H27O5Cl', 'C13H14N4O', 'C21H30O3', 'C19H32O', 'C20H21N7O7', 'C15H20O', 'C25H31O8', 'C4H4O6', 'C52H91N2O23P2R5', 'C6H9NO2', 'C8H12N2O4', 'C6H11O6R', 'C83H161O4', 'C11H8NO5', 'NA', 'C14H22N2O3SCl', 'C10H15N5O3', 'C16H26O7', 'C12HO2Cl7', 'C15H9N2O6SClF3', 'C21H20O12', 'C7H11N2O3', 'C26H49N2O8PRS', 'C15H12O6', 'C28H46O2', 'C20H21N2O3', 'C9H13N3O11P2', 'C14H21NO12R', 'NA', 'C6H12O6', 'C11H7N2Br', 'C9H11N5O6P', 'C16H12N2O2', 'C9H10N2O2ClBr', 'C49H84N2O32P2', 'C9H7O3', 'C29H36N3O7', 'C17H31N2O8PRS', 'NA', 'C15H22N6O4RS', 'C9H13N3O13P3', 'C11H10O3', 'C11H19N4O10P2', 'C39H64NO15', 'C7H13N2O2R2S', 'C20H37N2O9PRS', 'C15H21N5O14P2', 'C6H8N2', 'C30H50O', 'C10H11N5O4', 'C20H24O6', 'C21H16O7', 'C10H5NO3', 'C11H9N3O5', 'C7H10N2O4', 'C17H14O7', 'C10H22O', 'C27H41N7O18P3S', 'C10H18O', 'C22H37N2O16R', 'C11H10N3', 'C9H20O', 'C37H68NO12', 'NA', 'C28H48O', 'C19H24NO4', 'C8H7O5', 'C41H27O27', 'C15H18N3O3', 'C5H8O2', 'C4H10O3PS', 'NA', 'C22H49N4O', 'C53H62N10O14S2', 'C4H6N2O6PR2', 'C21H32O2', 'C8HO3SF17', 'C100H163N10O28P2', 'C18H26NO6', 'C20H24NO2S2', 'C10H20O2', 'H2O2P', 'C9H15N2O7P', 'C20H31NO7', 'C15H14O5', 'C57H111NO16P', 'C5H10O7B', 'C15H25N4O8', 'C6H8O6', 'C11H8N2O5', 'C14H12O2S2', 'C5H9O4R', 'C19H20O7', 'C8H15NO9P', 'C20H26O6', 'C9H15N5O14P3', 'C10H9O3Cl2', 'C11H16N2O3S', 'C29H30O8', 'C12H22NO9S3', 'C68H131N2O9PRS', 'C17H26NO2Cl', 'C23H17N2O5', 'C20H22O7', 'C8H9N3O4', 'C7H14O6', 'C40H56O3', 'C3H7NO4Se', 'C33H48O9', 'C26H30O6', 'C22H26O11', 'C18H28NO5', 'C9H8NO6', 'H3NO', 'C20H24O2', 'C7H14O6', 'C11H15NO', 'C21H44N7O11', 'C18H14O2', 'C6H6O5', 'C16H23N5O6', 'C25H49N6O8', 'C5H10NO5S', 'C20H23N3O2', 'C13H18N2O2Cl2', 'NA', 'C20H31O5', 'C12H22O11', 'C25H31NO3', 'C17H22N3OCl', 'C8H20NO6P', 'C22H30O8', 'C11H9O3Cl5', 'C14H18N6O', 'C26H42NO4', 'C25H40NO6', 'C17H28O', 'C7H7NO2', 'C18H12', 'C15H9O10', 'C21H13N', 'C16H18N3O5S', 'C28H38NO9', 'C31H29N2O5', 'C15H12O2', 'C7H7O2SF', 'C33H62NO8P', 'C14H16N2O6P', 'C52H76O12', 'C42H38CoN4O16', 'C7H11NO8PR2', 'C3H2OF6', 'C16H23N5O15P2', 'NA', 'C10H14O3', 'C17H22O7', 'C28H48O', 'C6H9NOS', 'Na', 'C49H93N2O8PRS', 'NA', 'C19H32O2', 'C15H13NO2', 'C13H9O4', 'C7H13N3O3R', 'C8H10NO10PR2', 'C6H7NO3', 'C9H16N4O3', 'C18H22NO5', 'C7H13N3O2R2', 'C121H226O18', 'C15H14O2Br2', 'C21H23NO6', 'C12H11N', 'C5H7O2', 'C27H42N8O18P3S', 'C3H8O3', 'C14H15N3O', 'C30H47N3O10S', 'C7H8N2O3', 'C4H10NO', 'C6H14N3', 'C40H56', 'C21H30O4', 'CO2R2', 'C7H8NO3', 'C28H45N4O4', 'C48H77N7O20P3S', 'C38H41N2O7', 'C60H89CoN13O15P', 'C9H15NO3', 'C4H6O2', 'NA', 'C9H9O4', 'C18H20NO5', 'C10H16', 'C28H40N7O20P3S', 'C16H24NO', 'C20H24N3SCl', 'C17H23N3O16P2', 'C43H67N7O17P3S', 'C19H34PCl2', 'C43H80O15', 'C13H16N5O13P2', 'C24H33O6F', 'NA', 'C29H31NO10Cl', 'NA', 'C15H12O2', 'C16H16N5O7S2', 'C22H26O9', 'C19H30O', 'C17H16O5', 'C17H22NO3', 'C20H22O6', 'C13H27NO2', 'C9H7NO', 'C33H61N2O8PRS', 'C5H10N3', 'C21H36N4O5S', 'C11H16NO8', 'C30H39O4', 'C16H30O2F', 'NA', 'C34H26O22', 'C24H24O2', 'C24H39O5', 'C20H25N3O7', 'C33H68', 'CH3OR', 'C10H15N6O6P', 'C6H2O5Cl2', 'C18H33O3', 'C124H222N2O51P2', 'C9H14O5S', 'C6H6O4', 'C19H28O2', 'C13H25OX', 'C6H9O7', 'NA', 'NA', 'C3H7N2', 'C13H5O2Cl6', 'C15H12N2O', 'C14H11NO4Cl2', 'C28H42N2O8S', 'C21H30O4', 'C28H58O', 'C20H23NO4', 'C17H21NO2', 'C10H5O4', 'C17H20NO3', 'C15H22O9', 'C27H44O4', 'NA', 'C2H2OR2', 'C4H4O', 'C11H15NO2S', 'C48H75N7O21P3S', 'C22H31O3F', 'C10H8O', 'C21H29N3O19P2R6', 'C11H13NO3', 'C7H6O5', 'C17H27NO7', 'C6H12O7PS', 'C5H9NO3', 'C12H5O2SCl4', 'C104H170N14O30P2', 'C48H70O6', 'C23H32N2OS', 'C21H30O4', 'NA', 'C44H50N8', 'C42H40N4O16', 'C17H17N3O3F', 'C27H42O6', 'NA', 'C11H19N2O6', 'C5H12O5', 'C27H44O3', 'C4H5NO3R', 'C21H29N7O15P2', 'C18H31O2', 'C15H24', 'C11H10N2O', 'C6H9O9P', 'C21H19O10', 'C18H18O2', 'NA', 'NA', 'C10H8N3O2Cl', 'C21H13O8', 'C10H16O2', 'C15H24', 'C18H39N6O6', 'NA', 'C34H67N3O5S', 'C10H18O', 'C39H77O2', 'C8H14NO6R', 'C7H6N2', 'C8H7NO3', 'C90H74O36', 'C30H42N4O2', 'C26H27O15', 'C41H68O13', 'C6H4N4O4', 'C8H18NO2', 'C40H36O11', 'C7H7NO2', 'C27H46O2', 'C7H6O5P', 'NA', 'C39H58O4', 'C12H10OS2', 'C26H28O12', 'C6H8O2', 'C7H4NO2Cl', 'C35H33N4O6Mg', 'C16H17NO3', 'C7H7NO4', 'C17H16O4', 'C10H19N5O', 'C19H25NO10', 'C3H5NO3', 'C24H34O5', 'C9H9NO4', 'C11H12O2', 'C4H12N3O4P', 'C20H12', 'C12H22O11', 'C15H24', 'C6H7O3', 'C21H29N5O17P2R2', 'C11H18N', 'C15H23N5O15P2', 'C14H19O3', 'C7H11N2O5', 'C8H5O7', 'C29H47N2', 'C15H21N3O16P2', 'C14H12O3', 'C26H38N7O19P3S', 'C43H80O13P', 'C21H31O3F', 'C16H21NO5', 'C20H30O3', 'C30H40O', 'NA', 'C9H9N5O', 'NA', 'C8H10NO5PS', 'C12H22O10', 'C10H14O', 'C15H24', 'C10H15N5O13P2Se', 'C8H8O', 'C9H10NO6', 'C7H14O6', 'C25H25O4', 'C32H44NO13', 'C5H10O8P', 'C6H8N2O3R2', 'C14H16O4', 'C9H15N5O8P', 'C20H30N6O12S2', 'C10H14O2', 'C12H15NO3', 'C18H35O3', 'C31H47N9O18P3S2', 'C20H30O4', 'C12H15NO', 'C95H182O15P2', 'C4H12NS', 'C18H21NO4', 'C6H5O4', 'C9H15O4PBr6', 'C21H22O7', 'C22H36O19R2', 'C3H4O6S', 'C8H12N2', 'CH3F', 'C2HNCl2', 'C8H12NO6', 'C33H54O11', 'C8H9NO', 'C22H35O2', 'C31H41N7O6', 'C6H2NO3R2S', 'C33H60O8', 'NA', 'C3H5Cl3', 'C8H8NO3', 'C8H12O10PR2', 'C15H12O6', 'C6H11N3O4', 'C15H22O3', 'C40H54O', 'C7H6O6', 'C16H26NO3', 'C6H12O12P2', 'C4H12N2', 'C8H14O', 'C19H22N2O4', 'C14H21N4O2', 'C7H12NO6RS', 'C22H32O3', 'C6H11N2O4PS3', 'NA', 'C22H29O5F', 'C11H21O2', 'C24H34N7O19P3S', 'C19H20N3O12P', 'C6H12O4Br2', 'NA', 'C20H14O2', 'Fe', 'C15H10N2O3', 'C11H13O2SCl', 'C23H28N3O4', 'C29H51N2O9PRS', 'C10H16O4', 'C56H77N4O6', 'C9H13N5O3', 'C18H38N6O5S', 'NA', 'C33H41N7O19P3S', 'C10H21NO7PR', 'C13H16N5O13P2', 'C12H24O11', 'C19H30N12O6R2', 'C26H39N7O17P3S', 'C8H13O5', 'C20H21O10RS', 'C6H17N3S', 'C12H15N3O3S', 'NA', 'H2NOR', 'C30H50O', 'C10H15N3O4', 'C10H17N4O4R2', 'C15H8N2O2F6', 'C12H10N2OCl2', 'C10H16O', 'C7H11N3O', 'C3H9N3O3S', 'C26H28N2O8', 'C20H40O7P', 'C34H56NO14', 'C29H36O15', 'C14H21NO3', 'C88H138O35P2', 'C53H98O20', 'C20H12O', 'C14H12N2O8', 'C9H10NO3', 'C6H11O6R', 'C12H11N', 'C20H13NO5', 'C41H70O12', 'C14H19N6O5R', 'C22H32O6', 'C20H32O', 'C31H51N7O17P3S', 'C28H38O6', 'C43H70O11', 'C9H13NO2', 'C5H10N2O3S', 'C20H34O2', 'C30H24O6', 'C8H6O2Br', 'CH2NO2R', 'C86H99N10O26Cl3', 'C7H16NO2', 'C21H32O2', 'C31H45N7O17P3S', 'C13H12O2', 'C7H8N4S', 'C26H38N7O20P3S', 'C12H12N2O2As2', 'C56H78N2O16', 'C15H20NO2', 'C12H16N2O4', 'C16H16N3O5S', 'C18H30NO3', 'C16H21NO2', 'C22H34O3', 'C261H468O255P24', 'C27H46O', 'C13H14', 'C6H10O6', 'C12H12N4', 'C10H11N5O7P', 'C24H42O21', 'C11H12NO8', 'C12H19N3O', 'C30H50O7P2', 'C15H7O7', 'C16H12O5', 'C18H27O3', 'C14H7NO3', 'C8H19N4O6P', 'C15H18N3O4', 'C39H68O7', 'C40H56', 'C10H18O7P2', 'C15H20O7', 'NA', 'C38H54N8O10', 'C10H8', 'C40H56O3', 'C9H18N2O4', 'C20H27O3', 'C29H32O13', 'C10H14N2O', 'C22H36O', 'C23H32O8', 'C26H43O9', 'C24H39O5', 'C6H12N3PS', 'C30H52O8P', 'C13H23O2', 'C8H13N2O5', 'C20H27O2', 'C30H50O5', 'C14H13NO', 'C14H11Cl3', 'C5H10O5', 'C28H50', 'C54H76N8O15', 'C12H6Cl4', 'C14H15NO7', 'C4H5O7PR', 'C6H9NO', 'C6H6NO3S', 'C10H11NO3', 'H3O3Al', 'C26H32NO5', 'C11H11NO3', 'C21H22O9', 'C17H21N2O10S2', 'C9H7O2', 'C11H16N3O2', 'C6H7N', 'C6H8O4', 'C19H21O6', 'C20H28N3O6', 'C28H53N2O9PRS', 'C14H14NSCl', 'NA', 'C26H22N2O3ClF3', 'O4RS', 'C28H36N7O17P3SCl', 'C7H13O2S', 'C5H9O7PR', 'C16H16O2', 'C16H10O', 'C14H21N3O4', 'NA', 'C47H82N3O23R', 'C27H43O3', 'C16H19NO7', 'C153H225N43O49S', 'C29H57O2', 'C6H5OCl', 'NA', 'C16H12NO3S', 'NA', 'C26H47N2O9PRS', 'CH2R2S', 'C6H6O2', 'C35H62O3', 'C18H39O7P', 'C26H29NOCl', 'NA', 'NA', 'C6H12O6', 'C21H39N2O8PRS', 'C32H38NO4', 'C9H13N5O3', 'C10H18O', 'C27H44O', 'C14H14N3O5', 'C44H72O12', 'C9H5NO4Cl', 'C6H10O3', 'C21H43N7O18P2', 'C10H12N2O', 'C20H28O2', 'C21H22NO4Cl', 'C15H15NO', 'C22H32O3', 'C14H28O', 'C18H22NO4', 'C14H12N2O6', 'C11H16O', 'C19H30O', 'C9H8N2OCl2', 'O4S', 'C7H7O7', 'C20H32', 'NA', 'C31H42O12', 'C30H50O4', 'NA', 'C18H44N7', 'C10H16O', 'C9H10NO3RS', 'C4H6NO4', 'C8H19N4O2', 'C15H7O16S3', 'C11H21NO', 'C22H24O5', 'C16H15O2F', 'C13H10O2', 'C10H13NO', 'C10H12N5O3R', 'C27H32O15', 'C23H14O3Cl', 'C15H27O2', 'C20H29O5', 'C12H6OCl4', 'C4H8NO2', 'C23H13N4O3SF9', 'C16H12O6', 'C45H71N7O20P3S', 'C42H47N6NiO14', 'NA', 'C37H44O14', 'C8H20N6O3', 'C3H10N', 'NA', 'C26H46N2', 'C20H20O6', 'C8H8O2Cl2', 'C13H14N9O4S3', 'C20H31O5', 'C20H20O7', 'CO2', 'C23H32O6', 'NA', 'Na', 'C52H74O24', 'C14H8NO5Cl2F', 'NA', 'noformula', 'C6H5O4', 'C26H30N2O8', 'C15H23O19P4R3', 'NA', 'C6H5NO', 'C16H22N2O6', 'C28H46O7', 'C24H41NO10', 'C20H24N10O19P4', 'C20H16O6', 'C18H24O', 'C48H77O18', 'C60H115NO24P2', 'C5H10O5', 'C21H30O3', 'C19H26O3', 'C25H45N2O9PRS', 'C19H22NO4', 'C13H17NO3', 'C21H25N7O9P', 'C27H33NO4', 'C13H12N2Cl2', 'C40H49O18', 'C15H15NO2', 'C12H15N', 'C6H9O7', 'C30H52O', 'C21H19O11', 'C16H23N5O16P2', 'C28H35N3O7', 'C17H24O6', 'C19H22NO3', 'C21H29N5O20P3R2', 'C10H14N2O14P3', 'C39H47NO14', 'C32H39O19', 'C22H28O8', 'C9H14N2O7R2', 'C28H50O10', 'C17H26N2O2', 'C6H7NO2', 'C5H9NO7P', 'C19H18O7', 'Co', 'C19H34NO', 'C19H17N7O6', 'C15H10O2', 'C20H24O7', 'C2H4O4S*2', 'C8H16O4', 'C16H27N2O11R', 'C11H13N2O2', 'C30H47O4', 'C24H32O4', 'C9H11N2O2Br', 'C21H29N2O5', 'C23H31N2O6', 'CH2NOR', 'H2O4Cr', 'C19H20O6', 'C15H11NO4F3', 'C13H8O5', 'C15H9O5', 'C35H61NO8', 'C33H41N5O6S2', 'C12H20NO3', 'C20H32O', 'C28H37O7Cl', 'C171H304N4O88P2', 'C10H6N2OS2', 'C18H19NO3', 'C13H19N3O4', 'C31H42N5O5', 'C11H22N4O3R2', 'C42H70NO15', 'HRS', 'C28H46O', 'C16H22N6O4', 'H2NR', 'C15H12N4O6S2', 'C23H22O6', 'C24H20O13R', 'C22H33N4O13', 'C3H2O4', 'C6H6O3', 'C10H18O', 'C22H23N6OCl', 'NA', 'C9H17NO8', 'C2HO2ClBr', 'C19H22O2', 'C20H40O7P', 'C42H52NO15', 'C15H13NO', 'C44H44CoN4O16', 'C22H30O2', 'C17H19N3O6', 'C17H25N', 'C15H20O3', 'NA', 'C23H24O12', 'C9H8N3O7', 'C21H21NO6', 'C44H49N4O16', 'C45H80N2O24', 'C30H48O5', 'C13H16N5O16P3', 'C16H16O3', 'C3H5N2O4', 'C10H12O4', 'C40H62N9O26P2', 'C13H10O5', 'C12H20NO10S3', 'C12H16N3O3PS2', 'C5H11NO', 'C13H19NO3PS2Cl', 'C37H66O7', 'C2H8NO4P', 'C22H22O7', 'C16H21N3O3', 'C17H18N4O5', 'C10H12N4O4', 'C6H9O3', 'C30H50O', 'C12H20NO2S2', 'C32H63O3', 'C25H34O3', 'C17H14O8', 'C15H14O4', 'C12H18NO17S2', 'C8H6NO5', 'C42H52FeN8O6S2', 'C31H49O3', 'C56H75N9O17', 'NA', 'NA', 'C18H31O3', 'C21H24N2O4', 'C19H12O6', 'C21H26N2O3', 'C5H10O8P', 'NA', 'C17H20N3OCl', 'C20H22O4', 'NA', 'C16H16', 'C28H51N', 'C30H45O4', 'C13H10O3', 'C4H9NO2', 'C5H4O4', 'C10H8Cl8', 'C5H16N2', 'C16H16O6', 'C17H15NO4', 'C12H5OCl5', 'C11H20O10', 'C9H13N3O4', 'C44H69N7O18P3S', 'C9H13N5O7P', 'NA', 'C13H10O3PSCl2Br', 'C32H52O2', 'C11H14N2O5', 'C12H10O4', 'C23H28O7', 'C14H8O4', 'C15H20NO', 'C102H187N3O31P2', 'C10H18O9', 'C3H5NO2R', 'C26H32O7', 'C45H67N7O17P3S', 'C36H35N2O7', 'C9H18O8', 'C15H16O5', 'C22H27N2O3', 'C12H14O12', 'C18H23N6O8P', 'C12H22O11', 'C15H23N6O5S', 'C15H19N4O10RS2', 'C18H11NO2', 'NA', 'C9H6NO2', 'C16H16O2', 'C22H44O9P', 'C27H33N2O7', 'C11H19O15P2R', 'C35H58N6O7', 'C12H6O5PBr4', 'C18H35O3', 'H2NR', 'C15H16N2O2', 'C12H10N2', 'C110H198N2O39P2', 'C11H10O', 'C15H8O5', 'C26H41N7O17P3S', 'C18H29NO3', 'C42H68NO10', 'C14H11O4', 'C19036H39872N2400O18300P2400', 'C18H38NO2', 'C21H21O7', 'NA', 'C45H74O10', 'C14H21NO12R', 'C5H11NO2S2', 'C6H8O2', 'C8H5O4', 'C20H16O7', 'C27H48O4', 'C22H19N4O2F3', 'C24H33N4O5S', 'C12H8O2', 'C15H24', 'C3H5O4P', 'C17H14O5', 'C6H12N3O3R', 'C3H6O', 'C6H5Br', 'C21H21O10', 'C9H5O6', 'C11H6O4', 'C16H15N3O4SF2', 'C9H14NO2', 'C3H5O2R', 'C19H20NO10RS', 'C6H12O12P2', 'C6H6N2O3', 'C19H24N7O8P', 'C7H9N3', 'C11H14O3', 'C15H20O3', 'H2NO3P', 'C16H12O6', 'C21H29O2R', 'C4H5O5', 'C12H21N2O3S', 'C40H71N3O15P2', 'C8H7NO2Cl2', 'C18H36O7P', 'C6H6NO5R', 'C6H14N4O9P2', 'C15H14O2', 'C17H12O2', 'C40H41FeN4O6S', 'NA', 'C19H33N2O9PRS', 'C4H5O7PR', 'C5H7O5', 'C7H14O4', 'C31H41N7O19P3S', 'C42H78O10P', 'C21H30O4', 'C45H65N3O6', 'C12H22O11', 'C3H5O6P', 'C19H36NO2', 'C23H36O4', 'C34H24O22', 'CH3NO2', 'C8H14N2O4', 'C9H13N', 'C6H9O6', 'C6H5O5S', 'C14H20N3O5PS', 'C9H13NO2', 'C35H66O4', 'C68H129N2O9PRS', 'NA', 'C18H41N5O5', 'C29H39N5O8', 'C47H68O17', 'C20H19NO5', 'C6H12O9P', 'C4H2O6', 'C12H20O29S6*2', 'C6H5N2O2', 'C31H47N7O17P3S', 'C13H16O2', 'C38H48N8O12S', 'C50H80O23', 'C22H34O18*2', 'C21H24NO4', 'C15H23N5O8P', 'C16H12O7', 'C17H24N3O15P', 'C4H9NO6P', 'C16H12O4', 'C4H8N2O3', 'C39H67N7O17P3S', 'C38H44N2O6', 'C37H42N2O6', 'C9H13N5OCl', 'C17H28', 'C10H11N5O7P', 'C6H4O4Cl', 'NA', 'C4H8NO5S', 'C9H5NOI2', 'C30H50O25', 'C9H15N2O5Se', 'C8H11NO5', 'C5H4NORS', 'C24H30N2O3', 'C9H16N3O3', 'C26H37N5O5S2', 'C17H24NO3', 'C16H34O', 'C12H10NO4Cl2', 'C6H12O9P', 'C22H14', 'C16H24O7', 'C16H14N2O2S', 'C6H13NO2', 'C35H60NO13', 'C19H42N5O7', 'C17H16O5', 'C21H20O6', 'C6H12O6', 'C12H14NO9P', 'C6H12O6', 'C19H37O2', 'C21H28O7', 'C29H34O7', 'C10H13NO3', 'C15H27N5O5', 'C15H27N2O8PRS', 'C13H20N2Cl', 'C19H17O11', 'C15H10O4', 'C6H12O6', 'C2H6Se', 'C41H71N7O18P3S', 'C16H12O8', 'C13H18N6O3', 'C27H48', 'C10H5Cl7', 'C20H24NO4', 'C42H64O12', 'C47H72O2', 'C8H16N2O3', 'C30H52O', 'C4H4O3', 'C5H13N2O', 'C30H48O2', 'C7H7NO3', 'C10H12N2O3S', 'NA', 'C23H36O6', 'C22H28O3S', 'C11H15NO3', 'C6H12O6', 'C12H14O12', 'C32H42N5O5', 'C20H32O20PR2', 'C37H72O5', 'C14H23N2O9', 'C12H3OCl5', 'C12H16N2O2', 'C41H62O', 'C6H12O2', 'C16H12N2O3', 'C40H56O2', 'C10H10N2O', 'C21H28O2', 'C8H16O', 'C3H7N3O2', 'C32H47N2O8', 'C26H41N7O17P3S', 'NA', 'C2H2OR', 'C27H40N4O14S', 'NA', 'C38H44N2O6', 'C17H17NO4', 'C18H18O6', 'C30H51N7O7', 'C38H44N2O6', 'C28H50N2O4', 'C82H57O52', 'C15H24N5O4', 'C21H30O', 'C18H22N2', 'C24H34O', 'C27H30O6Cl2', 'C9H15O12P', 'C29H34N4', 'C12H5Cl5', 'C19H19N7O6', 'C8H12N4OS2', 'C6H6NF', 'C19H25N4O18P2', 'C30H31N2O19', 'C9H17N4O4', 'C19H24O4', 'NA', 'C22H20N2O3Cl2', 'C14H21NO4', 'C8H9NO2', 'C14H10N2O4', 'C15H18O3', 'C44H67O13', 'NA', 'C62H111N5O8P', 'C16H18O10', 'C20H44N4O10', 'C6H3O4Cl2', 'C21H29N5O19P3R2', 'C20H32O2', 'C6H10O6PS', 'C14H12O4', 'C22H20O9', 'C30H28O12', 'C17H9NO4', 'C55H57N5O20', 'C21H22O8', 'C54H96O2', 'C13H20N6O4', 'C30H52', 'C2H6O', 'C6H12O9P', 'C8H18N2O3S', 'C42H59O16', 'C81H156O17P2', 'C14H9O4', 'C13H25NO2S2', 'C31H45N7O18P3S', 'C22H29N2O4', 'C31H40N5O4', 'C4H5O3Se', 'C54H62N10O33P', 'C6H8O5', 'C20H33O5', 'C25H28O4', 'C3H4NO4', 'C20H23N2O8', 'C9H10NO2F', 'C24H40N3O16R', 'C18H20NO4', 'C27H42O3', 'C51H84O22', 'C8H7NO', 'C21H34O3', 'C5H8N5Cl', 'C6H11O2', 'C13H19N2O', 'C19H30O3', 'C18H33O3', 'C12H10N4O2', 'C22H23NO7', 'C169H295N2O94P4', 'C10H10N2O6PR2', 'C11H17NO7', 'C10H16', 'C20H28O7', 'C6H4O2', 'C9H7NO', 'C20H19O5', 'C7H11O3', 'C10H7O3S', 'C20H23N2O2', 'C151H265N2O79P4', 'C6H12O9P', 'C44H79N3O15P2', 'C16H22NO3', 'C7H17N4O2', 'C18H21N6O7S', 'C7H7O7', 'C15H20NO2', 'NA', 'C12H19NO23S4*2', 'NA', 'C6H12O9P', 'C34H30FeN4O4', 'C15H9O10S', 'C6H15O2PS3', 'C7H5NO5', 'C25H34NO4', 'C15H16O9', 'NA', 'C26H43O2R', 'C34H44O9', 'C15H14O5', 'C17H11O8', 'C55H72N4O6M

In [ ]:
# Look for metabolites with specific composition

target_elements = ["C21", "N7", "P2"]

for entry in thermo_formulas:
    if all(elem in entry for elem in target_elements):
        print(entry)

C21H27N7O14P2
C21H44N7O18P2
C21H29N7O15P2
C21H43N7O18P2
C21H26N7O14P2
C21H33N7O13P2S
C21H44N7O17P2
C21H44N7O17P2
C21H44N7O18P2

In [ ]:
# LOOCKUP INFORMATION OF SPECIFIC METABOLITES USING THEIR FORMULA

metabolites_to_check = [
    "C21H27N7O14P2",
    "C21H29N7O15P2",
    "C21H26N7O14P2",
]

for met in metabolites_to_check:
    found = False
    for met_id, entry in thermo_data['metabolites'].items():
        name_lower = entry.get('formula', '').lower()
        # Exact match
        if met.lower() == name_lower:
            print(f"Metabolite ID: {met_id}")
            for key, value in entry.items():
                print(f"  {key}: {value}")
            print("-"*50)
            found = True
            break  # stop after the first exact match
    if not found:
        print(f"{met}  NOT found in thermo_data")
        print("-"*50)

Metabolite ID: cpd00004
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.2679
  mass_std: 663.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWOW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00004
  nH_std: 27
  name: NADH
  formula: C21H27N7O14P2
  deltaGf_std: -524.32
  error: Nil
  charge_std: -2
  other_names: ['NADH', 'DPNH', 'Nicotinamide adenine dinucleotide - reduced', 'Nicotinamideadeninedinucleotide-reduced', 'nadh']
--------------------------------------------------
Metabolite ID: cpd02951
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.238
  mass_std: 681.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 9, 'RWOW': 2, 'RWCHdblW': 3, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 2, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 5, 'RWCdblWW': 2}
  id: cpd02951
  nH_std: 29
  name: (6S)-6-beta-Hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide
  formula: C21H29N7O15P2
  deltaGf_std: -574.72
  error: Nil
  charge_std: -2
  other_names: ['(6S)-6-beta-Hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide']
--------------------------------------------------
Metabolite ID: cpd00003
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.3569
  mass_std: 662.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWCHdblW': 6, 'mid_phos': 1, 'WPO4nW': 1, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'TWWCdblW': 2, 'HeteroAromatic': 3, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00003
  nH_std: 26
  name: NAD+
  formula: C21H26N7O14P2
  deltaGf_std: -529.59
  error: Nil
  charge_std: -1
  other_names: ['NAD+', 'NAD', 'Nicotinamide adenine dinucleotide', 'DPN', 'Diphosphopyridine nucleotide', 'Nadide', 'Nicotinamideadeninedinucleotide', 'nad']
--------------------------------------------------

# Load thermodynamics database

In [ ]:
# Download thermo database
!wget https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb -O thermo_data.thermodb

# Load thermodynamics
thermo_data = load_thermoDB("thermo_data.thermodb")

# Print thermo_data keys

print(f"Thermo Data loaded successfully:{thermo_data.keys()}")

--2026-01-04 16:01:23--  https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2184378 (2.1M) [application/octet-stream]
Saving to: ‘thermo_data.thermodb’

thermo_data.thermod 100%[===================>]   2.08M  --.-KB/s    in 0.07s

2026-01-04 16:01:24 (31.0 MB/s) - ‘thermo_data.thermodb’ saved [2184378/2184378]

Thermo Data loaded successfully:dict_keys(['name', 'units', 'metabolites', 'cues'])

In [ ]:
# Adjust model compartments as required by TFA

model.compartments = {
    'c': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'e': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },

    'u': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'p': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    }
}

# Step 1: map metabolites to standard compartments
for met in model.metabolites:
    if met.compartment in ["c", "cytosol"]:
        met.compartment = "c"
    elif met.compartment in ["e", "extracellular"]:
        met.compartment = "e"

# Step 2: collect all compartments used by metabolites
used_compartments = set([met.compartment for met in model.metabolites])

# Step 3: ensure all compartments exist and are dicts
for c in used_compartments:
    val = model.compartments.get(c)
    # overwrite any string or missing compartment with dict
    model.compartments[c] = {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02
    }

print("Final compartments:", model.compartments)

Final compartments: {'c': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'u': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'p': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'e': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}}

In [ ]:
rxn = model.reactions.get_by_id('AACOAR_syn')
rxn.lower_bound = -1000
rxn.upper_bound = 1000

for rxn in model.reactions:
    rxn.lower_bound = max(rxn.lower_bound, -1000)
    rxn.upper_bound = min(rxn.upper_bound, 1000)


tmodel = ThermoModel(
    thermo_data,
    model
)

for comp in tmodel.compartments:
    tmodel.compartments[comp] = {
        "pH": 7.0,
        "ionicStr": 0.25
    }

tmodel.solver = "glpk" #'optlang-cplex'


# Set physiological concentration ranges
tmodel.metabolites.get_by_id("nadph[c]").concentration = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("nadp[c]").concentration  = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("h[c]").concentration     = (1e-8, 1e-6)
tmodel.metabolites.get_by_id("coa[c]").concentration   = (1e-6, 1e-3)
#for met in tmodel.metabolites:
#    met.concentration = (1e-9, 1e-2)


tmodel.prepare()
tmodel.convert()

In [ ]:
# TFA OPTIMIZATION

sol = tmodel.optimize()

DEBUG:thermomodel_Model Exported from COBRA Toolbox:'slim_optimize' ((), {}) 441.55 sec

In [ ]:
# Explain why thi is necessary
rxn = tmodel.reactions.get_by_id('AACOAR_syn')
rxn.thermo['deltaG0_prime'] = (-25.0, 2.0)
rxn.thermo

{'isTrans': False,
 'computed': False,
 'deltaGR': 1000.0,
 'deltaGRerr': 1000.0,
 'deltaG0_prime': (-25.0, 2.0)}

In [ ]:
rxn = tmodel.reactions.get_by_id('AACOAR_syn')
rxn.thermo

{'isTrans': False,
 'computed': False,
 'deltaGR': 1000.0,
 'deltaGRerr': 1000.0,
 'deltaG0_prime': (-25.0, 2.0)}

# Formula normalization and matching

In [ ]:
gem_formulas = {
    m.id: m.formula
    for m in model.metabolites
    if m.formula is not None
}
gem_formulas

In [ ]:
# Normalize Formula using Hill notation
import re
from collections import defaultdict

def normalize_formula(formula):
    """
    Normalize chemical formula to Hill-like notation.
    Example: 'H12C6O6P1' -> 'C6H12O6P'
    """
    if formula is None:
        return None

    # Parse elements and counts
    tokens = re.findall(r'([A-Z][a-z]?)(\d*)', formula)
    if not tokens:
        return None

    elements = defaultdict(int)
    for el, count in tokens:
        elements[el] += int(count) if count else 1

    # Hill system: C, then H, then others alphabetically
    ordered = []
    if 'C' in elements:
        ordered.append(('C', elements.pop('C')))
    if 'H' in elements:
        ordered.append(('H', elements.pop('H')))
    for el in sorted(elements):
        ordered.append((el, elements[el]))

    return ''.join(f"{el}{cnt if cnt > 1 else ''}" for el, cnt in ordered)

In [ ]:
# Find
thermo_norm = set(
    normalize_formula(f) for f in thermo_formulas
    if normalize_formula(f) is not None
)

gem_norm = {
    mid: normalize_formula(f)
    for mid, f in gem_formulas.items()
    if normalize_formula(f) is not None
}

In [ ]:
matched = {
    mid: f for mid, f in gem_norm.items()
    if f in thermo_norm
}

In [ ]:
len(matched)

1412

In [ ]:
unmatched = {
    mid: f for mid, f in gem_norm.items()
    if f not in thermo_norm
}

In [ ]:
len(unmatched)

706

In [ ]:
for mid, f in list(matched.items())[:20]:
    print(mid, f)

gam6p[c] C6H13NO8P
cgly[c] C5H10N2O3S
achms[c] C6H11NO4
pcox_u R
octe9ACP[c] C18H33ORS
pep[c] C3H2O6P
hgbam[c] C45H58N6O12
nac[c] C6H4NO2
r3mmal[c] C5H6O5
leu__L[c] C6H13NO2
ahcys[c] C14H20N6O5S
h2o_cx[c] H2O
orot[c] C5H3N2O4
na1[c] Na
ala_B[c] C3H7NO2
pqh2_um[p] C53H82O2
26dap_LL[c] C7H14N2O4
ddcaACP[c] C12H23ORS
trdox[c] X
glu__D[c] C5H8NO4

In [ ]:
# CHANGE FORMULA MANUALLY

met = model.metabolites.get_by_id('coa[c]')
met.formula = 'C21H36N7O16P3S'
# keep the charge as is

# Match metabolites by name

In [ ]:
'Acetyl-CoA' in thermo_formulas

True

In [ ]:
metabolites_to_check = [
    "nadph",
    "nadh",
    "acetyl-coa",
    "nad+",
    "nadp+",
    "3-hydroxybutyryl-coa",
    "acetoacetyl-coa",
    "coa"
]

for met in metabolites_to_check:
    found = False
    for met_id, entry in thermo_data['metabolites'].items():
        name_lower = entry.get('name', '').lower()
        # Exact match
        if met.lower() == name_lower:
            print(f"Metabolite ID: {met_id}")
            for key, value in entry.items():
                print(f"  {key}: {value}")
            print("-"*50)
            found = True
            break  # stop after the first exact match
    if not found:
        print(f"{met} ❌ NOT found in thermo_data")
        print("-"*50)

Metabolite ID: cpd00005
  pKa: []
  deltaGf_err: 4.2579
  mass_std: 742.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'prim_phos': 1, 'amide': 1, 'RWCHWW': 8, 'TWWCdblW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'WNH2': 2, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 3, 'RWCdblWW': 2}
  id: cpd00005
  nH_std: 27
  name: NADPH
  formula: C21H27N7O17P3
  deltaGf_std: -736.82
  error: Nil
  charge_std: -3
  other_names: ['NADPH', 'TPNH', 'Nicotinamide adenine dinucleotide phosphate - reduced', 'Nicotinamideadeninedinucleotidephosphate-reduced', 'nadph']
--------------------------------------------------
Metabolite ID: cpd00004
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.2679
  mass_std: 663.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWOW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00004
  nH_std: 27
  name: NADH
  formula: C21H27N7O14P2
  deltaGf_std: -524.32
  error: Nil
  charge_std: -2
  other_names: ['NADH', 'DPNH', 'Nicotinamide adenine dinucleotide - reduced', 'Nicotinamideadeninedinucleotide-reduced', 'nadh']
--------------------------------------------------
Metabolite ID: cpd00022
  pKa: [1.46, 2.01, 2.62, 6.72, 12.78]
  deltaGf_err: 3.5344
  mass_std: 806.0
  struct_cues: {'WNH2': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'WSW': 1, 'smide': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 3, 'WCH2W': 6, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 3}
  id: cpd00022
  nH_std: 35
  name: Acetyl-CoA
  formula: C23H35N7O17P3S
  deltaGf_std: -785.83
  error: Nil
  charge_std: -3
  other_names: ['Acetyl-CoA', 'Acetyl coenzyme A', 'acetyl-coA', 'acetyl-CoA', 'acetyl-coa']
--------------------------------------------------
Metabolite ID: cpd00003
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.3569
  mass_std: 662.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWCHdblW': 6, 'mid_phos': 1, 'WPO4nW': 1, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'TWWCdblW': 2, 'HeteroAromatic': 3, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00003
  nH_std: 26
  name: NAD+
  formula: C21H26N7O14P2
  deltaGf_std: -529.59
  error: Nil
  charge_std: -1
  other_names: ['NAD+', 'NAD', 'Nicotinamide adenine dinucleotide', 'DPN', 'Diphosphopyridine nucleotide', 'Nadide', 'Nicotinamideadeninedinucleotide', 'nad']
--------------------------------------------------
Metabolite ID: cpd00006
  pKa: []
  deltaGf_err: 4.3471
  mass_std: 741.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'mid_phos': 1, 'prim_phos': 1, 'amide': 1, 'RWCHWW': 8, 'TWWCdblW': 2, 'RWCHdblW': 6, 'WPO4nW': 1, 'WNH2': 2, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'HeteroAromatic': 3, 'PrimOH': 3, 'RWCdblWW': 2}
  id: cpd00006
  nH_std: 26
  name: NADP+
  formula: C21H26N7O17P3
  deltaGf_std: -742.09
  error: Nil
  charge_std: -2
  other_names: ['NADP+', 'NADP', 'Nicotinamide adenine dinucleotide phosphate', 'beta-Nicotinamide adenine dinucleotide phosphate', 'TPN', 'Triphosphopyridine nucleotide', 'Nicotinamide adenine dinucleotide phosphate -', 'Nicotinamideadeninedinucleotidephosphate', 'nadp']
--------------------------------------------------
Metabolite ID: cpd16898
  pKa: []
  deltaGf_err: 10000000.0
  mass_std: 850.0
  struct_cues: {}
  id: cpd16898
  nH_std: 39
  name: 3-Hydroxybutyryl-CoA
  formula: C25H39N7O18P3S
  deltaGf_std: 10000000.0
  error: No molfile exists for this compound.
  charge_std: 10000000
  other_names: ['3-Hydroxybutyryl-CoA']
--------------------------------------------------
Metabolite ID: cpd00279
  pKa: [1.46, 2.01, 2.62, 6.72, 10.35]
  deltaGf_err: 3.5804
  mass_std: 848.0
  struct_cues: {'WNH2': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'WSW': 1, 'smide': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 4, 'WCH2W': 7, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 3}
  id: cpd00279
  nH_std: 37
  name: Acetoacetyl-CoA
  formula: C25H37N7O18P3S
  deltaGf_std: -812.61
  error: Nil
  charge_std: -3
  other_names: ['Acetoacetyl-CoA', 'Acetoacetyl coenzyme A', '3-Acetoacetyl-CoA', 'acetoacetyl-CoA', 'acetoacetyl-coa']
--------------------------------------------------
Metabolite ID: cpd00010
  pKa: [1.46, 2.01, 2.62, 8.38, 10.07]
  deltaGf_err: 3.4521
  mass_std: 764.0
  struct_cues: {'WNH2': 1, 'WSH': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 2, 'WCH2W': 6, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 2}
  id: cpd00010
  nH_std: 33
  name: CoA
  formula: C21H33N7O16P3S
  deltaGf_std: -751.994
  error: Nil
  charge_std: -3
  other_names: ['CoA', 'Coenzyme A', 'CoA-SH', 'CoenzymeA', 'coA', 'coenzyme a']
--------------------------------------------------

# Alternative version fro adding compartments

In [ ]:
# Adjust model compartments as required by TFA

model.compartments = {
    'c': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'e': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },

    'u': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'p': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    }
}

# Step 1: map metabolites to standard compartments
for met in model.metabolites:
    if met.compartment in ["c", "cytosol"]:
        met.compartment = "c"
    elif met.compartment in ["e", "extracellular"]:
        met.compartment = "e"

# Step 2: collect all compartments used by metabolites
used_compartments = set([met.compartment for met in model.metabolites])

# Step 3: ensure all compartments exist and are dicts
for c in used_compartments:
    val = model.compartments.get(c)
    # overwrite any string or missing compartment with dict
    model.compartments[c] = {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02
    }

print("Final compartments:", model.compartments)

Final compartments: {'c': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'u': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'p': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'e': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}}

# Match reactions

In [ ]:
# CHECK PRECURSOR REACTIONS
precursor_rxns = [
    "AACOAR_syn",
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
]

for rxn_id in precursor_rxns:
    if any(rxn_id in v.name for v in dg_vars):
        print(f"{rxn_id}: thermo-constrained ✅")
    else:
        print(f"{rxn_id}: NOT thermo-constrained ❌")

AACOAR_syn: NOT thermo-constrained ❌
PHBS_syn: NOT thermo-constrained ❌
ACACT1r: NOT thermo-constrained ❌
ACACCT: NOT thermo-constrained ❌

In [ ]:
# Assuming your model is called 'model' and it's a COBRApy model

# Get the metabolite
met = model.metabolites.get_by_id("3hbcoa__R[c]")

# Find reactions where this metabolite is produced (stoichiometry > 0)
producing_reactions = [rxn for rxn in met.reactions if rxn.get_coefficient(met) > 0]

# Print them
for rxn in producing_reactions:
    print(rxn.id, rxn.reaction)

AACOAR_syn aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]

In [ ]:


# Re-run prepare and convert
tmodel.prepare()
tmodel.convert()

2025-12-30 06:15:19,195 - thermomodel_Model Exported from COBRA Toolbox - INFO - # Model preparation starting...
INFO:thermomodel_Model Exported from COBRA Toolbox:# Model preparation starting...
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gam6p_c (D-Glucosamine 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cgly_c (Cys Gly C5H10N2O3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite achms_c (O Acetyl L homoserine C6H11NO4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pcox_u (Plastocyanin(Cu2+)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite octe9ACP_c (Cis-octadec-9-enoyl-[acyl-carrier protein] ((9Z)-n-C18:1)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fdp_c (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5caiz_c (5-phosphoribosyl-5-carboxyaminoimidazole) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pep_c (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cpd00010 (Coenzyme A) not present in thermoDB
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbam_c (Hydrogenobyrinate a,c diamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nac_c (Nicotinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite r3mmal_c (D-erythro-3-Methylmalate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite leu__L_c (L-Leucine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ahcys_c (S-Adenosyl-L-homocysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ru5p__D_c (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 14dhncoa_c (1,4-dihydroxy-2-napthoyl-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2o_cx_c (H2O H2O) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2s_c (Hydrogen sulfide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite orot_c (Orotate C5H3N2O4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite g1p_c (D-Glucose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hdecACP_c ((R)-3-Hydroxydecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite na1_c (Sodium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala_B_c (Beta-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyc3p_c (Glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pqh2_um[p] (Plastoquinol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap_LL_c (LL-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ddcaACP_c (Dodecanoyl-ACP (n-C12:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_cx_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdox_c (Oxidized thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3oddecACP_c (3-Oxododecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glu__D_c (D-Glutamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h_cx_c (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dutp_c (DUTP C9H11N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite paps_c (3'-Phosphoadenylyl sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mg2_c (Magnesium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hdeACP_c (Cis-hexadec-9-enoyl-[acyl-carrier protein] (n-C16:1)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_c (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite anth_c (Anthranilate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhpt_c (Dihydropteroate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thex2eACP_c (Trans-Hex-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fmn_c (FMN C17H19N4O9P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pppi_c (Inorganic triphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udp_c (UDP C9H11N2O12P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cit_c (Citrate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acACP_c (Acetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uama_c (UDP-N-acetylmuramoyl-L-alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite eig3p_c (D-erythro-1-(Imidazol-4-yl)glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c4mop_c (3-Carboxy-4-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lys__L_c (L-Lysine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 13dpg_c (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gmp_c (GMP C10H12N5O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite utp_c (UTP C9H11N2O15P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdrd_c (Reduced thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite so4_c (Sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5apru_c (5-Amino-6-(5'-phosphoribosylamino)uracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hmppp9_c ( 13(1)-Hydroxy-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pydx5p_c (Pyridoxal 5'-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2dhp_c (2-Dehydropantoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ade_c (Adenine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite asp__L_c (L-Aspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2sephchc_c (2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acg5p_c (N-Acetyl-L-glutamyl 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdp_c (GDP C10H12N5O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbyr_c (Hydrogenobyrinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite palmACP_c (Palmitoyl-ACP (n-C16:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pser__L_c (O-Phospho-L-serine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ocACP_c (Octanoyl-ACP (n-C8:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dttp_c (DTTP C10H13N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 6pgc_c (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gcald_c (Glycolaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2p4c2me_c (2-phospho-4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cmp_c (CMP C9H12N3O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pro_c (Protein component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pi_c (Phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pnto__R_c ((R)-Pantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dump_c (DUMP C9H11N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite omppp9_c (13(1)-Oxo-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 23dhmp_c ((R)-2,3-Dihydroxy-3-methylpentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gtp_c (GTP C10H12N5O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4h2oglt_c (4 Hydroxy 2 oxoglutarate C5H4O6) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prfp_c (1-(5-Phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite man1p_c (D-Mannose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dxyl5p_c (1-deoxy-D-xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hddecACP_c ((R)-3-Hydroxydodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cu2_c (Copper) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malACP_c (Malonyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2mahmp_c (2-Methyl-4-amino-5-hydroxymethylpyrimidine diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phpyr_c (Phenylpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fe2_c (Fe2+ mitochondria) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phllqne_c (Phylloquinone) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite toct2eACP_c (Trans-Oct-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dgdp_c (DGDP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uaccg_c (UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acald_c (Acetaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2s_c (Superoxide anion) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite alac__S_c ((S)-2-Acetolactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hmop_c ((R)-3-Hydroxy-3-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4abz_c (4-Aminobenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prbamp_c (1-(5-Phosphoribosyl)-AMP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ca2_c (Calcium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyclt_c (Glycolate C2H3O3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite butACP_c (Butyryl-ACP (n-C4:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppcys_c (N-((R)-4-Phosphopantothenoyl)-L-cysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpgal_c (UDPgalactose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite f6p_c (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lac__D_c (D-Lactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite his__L_c (L-Histidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite agdpcbi_c (Adenosine-GDP-cobinamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s17bp_c (Sedoheptulose 1,7-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dctp_c (DCTP C9H12N3O13P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thf_c (5,6,7,8-Tetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 25aics_c ((S)-2-[5-Amino-1-(5-phospho-D-ribosyl)imidazole-4-carboxamido]succinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ni2_c (Nickel) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dtdp4d6dg_c (DTDP-4-dehydro-6-deoxy-D-glucose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malcoa_c (Malonyl CoA C24H33N7O19P3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fum_c (Fumarate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_cw_c (Cell wall component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ACP_c (Acyl carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mlthf_c (5,10-Methylenetetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h[p] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhf_c (7,8-Dihydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dudp_c (DUDP C9H11N2O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3omrsACP_c (3-Oxotetradecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trnaglu_c (TRNA (Glu)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pre6a_c (Precorrin 6A) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ametam_c (S-Adenosylmethioninamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hhexACP_c ((R)-3-Hydroxyhexanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppan_c (D-4'-Phosphopantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite quln_c (Quinolinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite frdp_c (Farnesyl diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyald_c (D-Glyceraldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uacgam_c (UDP-N-acetyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pram_c (5-Phospho-beta-D-ribosylamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap__M_c (Meso-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdpmann_c (GDP-D-mannose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite db4p_c (3,4-dihydroxy-2-butanone 4-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actACP_c (Acetoacetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actp_c (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ugmd_c (UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s7p_c (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cbm_c (Carbamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite co2_c (CO2 CO2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite zeax_c (Zeaxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ptrc_c (Putrescine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adp_c (ADP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3a2oxpp_c (3-Amino-2-oxopropyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aspsa_c (L-Aspartate 4-semialdehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite tdec2eACP_c (Trans-Dec-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phom_c (O-Phospho-L-homoserine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite amylose_c (Amylose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5mdr1p_c (5-Methylthio-5-deoxy-D-ribose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite rb15bp_cx_c (D-Ribulose 1,5-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bcryptox_c (Beta-Cryptoxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite spmd_c (Spermidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpsq_c (UDP-6-sulfoquinovose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2_c (Hydrogen) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adocbip_c (Adenosyl cobinamide phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phycy_c ((3Z)-Phycocyanobilin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nadh_c (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aps_c (Adenosine 5'-phosphosulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dpcoa_c (Dephospho-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite xu5p__D_c (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite no2_c (Nitrite) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4hbz_c (4-Hydroxybenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3odecACP_c (3-Oxodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhnpt_c (Dihydroneopterin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5aprbu_c (5-Amino-6-(5'-phosphoribitylamino)uracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite iasp_c (Iminoaspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nmn_c (NMN C11H14N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pigm_c (Pigment component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2cpr5p_c (1-(2-Carboxyphenylamino)-1-deoxy-D-ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pchlld_c (Protochlorophyllide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_u (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala__L_c (L-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c2hmp_c (3-Carboxy-2-hydroxy-4-methylpentanoate) has no seed_id

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPTc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC20M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHFR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHPPDA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHORM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCBT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:E4PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLGC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cu2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THISAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DBTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BACCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtex : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COCHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1bpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FNOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD1ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PBDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCALDD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLBRAN2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCGLYCabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLMS_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUCYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUK_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUSx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCL_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCTO1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOXG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRRx : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBCh : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HESR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACALD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACNML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBIK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBLtonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPRDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3PApp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PApp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMHE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGt3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHGDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AKGt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATA_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATA_L2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD19xr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD3y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALKP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLTN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLULPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALPATE160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALPATG160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AM3PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AM4PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMMQLT8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPMS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPTASEPG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARBTNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARBabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARHGDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARMEPNS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASCBptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATHRDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BETALDHx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BETALDHy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BGLA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BUTCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BUTSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBIAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBItonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBL1abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBL1tonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBLAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CD2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CD2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGUNPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CELBpts : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS160E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS160G : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS180E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS180G : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHLt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHOLD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHOLID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHTBSptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CINNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CMtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAPabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPGNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPGNtonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPH4S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CRNCAL2 : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIR2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:O16A4COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:O16AT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OBTFL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCTDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OHPHM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMBZLM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMMBLHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMPHHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXCOAHDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXDHCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAI2I : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPSR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDE1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDE4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHEMEabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PNSPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POAACR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPAKr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCSCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPDOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPGPPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPTHpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSP_Lpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHRpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTRCTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUACGAMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUACGAMtr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYROX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINDHyi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R15BPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R5PPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:REPHACCOAI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RFAMPtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RIBabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR3b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR1c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR2c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR3c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR4c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPNTPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RU5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SADT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SBTPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SBTptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SCYSDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SELabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SGSAD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHSL1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SKMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SLNTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SOTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCt2_2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULFACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:T2DECAI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TALA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TAURabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPAGTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TGBPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THIORDXi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THMabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMAOR1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMAOR2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMPPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPRDCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TREptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPAS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TSULabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TTRCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TUNGSabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UACMAMO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPKAAT : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sulfac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tartr__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tartr__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_taur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_thr__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tma_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tmao_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tol_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tre_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tsul_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_udcpo5_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ump_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_urate_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_val__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_vanln_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_xmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FACOAL160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALGTHLs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FAS120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FAS200 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FASC200ACP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCOAHA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOAMtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FORAMD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PCtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PStex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCCb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCCc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCTR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCBL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYC2Ptex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTPHs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2CO3D : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD8i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIStex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KAT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LACD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCTStpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSMO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MACCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP2ex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP3ex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MELIBt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METOX1s : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METOX2s : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MGSA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMTSAO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOSDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MUCCY_kt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:N2trpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH3c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NMNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NT5C : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD6pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OHEDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHACOAOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPAt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCOAC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PREPHACPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RFAMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SCYSSL_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SLCYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTRDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTRDtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THPAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPPtppi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VNLNpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:XMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:XTSNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BSORy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:INS2D : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HGD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6AR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:N2OR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6YM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MHPGLUT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APPLDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTMLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APATr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRUK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFK_2 : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B
Warning : BO3/B

Streaming output truncated to the last 5000 lines.
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP1ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP1ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMETabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionPACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionPC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_PC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_PC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_PC

In [ ]:
from pytfa.optim.variables import DeltaG

print("ΔG present:", DeltaG in tmodel.variables)

ΔG present: False

In [ ]:
rxn = tmodel.reactions.get_by_id("AACOAR_syn")

# Manually define standard Gibbs energy (kJ/mol)
tmodel.add_reaction_thermo(
    rxn,
    delta_g0=-25.0,    # literature estimate
    uncertainty=5.0
)

AttributeError: 'ThermoModel' object has no attribute 'add_reaction_thermo'

In [ ]:
print("ΔG variables present:", DeltaG in tmodel.variables)

if DeltaG not in tmodel.variables:
    raise RuntimeError(
        "❌ No DeltaG variables created → thermo_data not matched"
    )

ΔG variables present: False

RuntimeError: ❌ No DeltaG variables created → thermo_data not matched

In [ ]:
tmodel.metabolites.get_by_id("nadph[c]").concentration = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("nadp[c]").concentration  = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("h[c]").concentration     = (1e-8, 1e-6)
tmodel.metabolites.get_by_id("coa[c]").concentration   = (1e-6, 1e-3)

KeyError: 'nadph_c'

In [ ]:
rxn_id = "AACOAR_syn"
rxn = tmodel.reactions.get_by_id(rxn_id)

dg = tmodel.variables[DeltaG][rxn]

print(f"{rxn_id} ΔG bounds (kJ/mol):")
print("  LB:", dg.lb)
print("  UB:", dg.ub)

In [ ]:
# Solve
# FBA max PHB
fba = model.optimize()

# TFA max PHB
tfa = tmodel.optimize()
print("Thermo-FBA objective:", tfa.objective_value)

DEBUG:thermomodel_Model Exported from COBRA Toolbox:'slim_optimize' ((), {}) 91.40 sec

Thermo-FBA objective: 0.18

In [ ]:
# Reaction ID in your GEM
rxn = tmodel.reactions.get_by_id("AACOAR_syn")


# Add standard Gibbs energy (kJ/mol)
tmodel.add_reaction_thermo(
    rxn,
    delta_g0=-25.0,   # literature-based estimate
    uncertainty=5.0
)

In [ ]:
# --------------------------------------
# 2. PREPARE + CONVERT (safe even if partial)
# --------------------------------------
tmodel.convert()

2025-12-30 02:59:25,442 - thermomodel_Model Exported from COBRA Toolbox - INFO - # Model preparation starting...
INFO:thermomodel_Model Exported from COBRA Toolbox:# Model preparation starting...
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gam6p[c] (D-Glucosamine 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cgly[c] (Cys Gly C5H10N2O3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite achms[c] (O Acetyl L homoserine C6H11NO4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pcox_u (Plastocyanin_Cu2+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite octe9ACP[c] (Cis-octadec-9-enoyl-_acyl-carrier protein __9Z-n-C18:1) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fdp[c] (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5caiz[c] (5-phosphoribosyl-5-carboxyaminoimidazole) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pep[c] (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbam[c] (Hydrogenobyrinate a,c diamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nac[c] (Nicotinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite r3mmal[c] (D-erythro-3-Methylmalate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite leu__L[c] (L-Leucine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ahcys[c] (S-Adenosyl-L-homocysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ru5p__D[c] (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 14dhncoa[c] (1,4-dihydroxy-2-napthoyl-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2o_cx[c] (H2O H2O) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2s[c] (Hydrogen sulfide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite orot[c] (Orotate C5H3N2O4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite g1p[c] (D-Glucose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hdecACP[c] (_R-3-Hydroxydecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite na1[c] (Sodium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc[c] (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala_B[c] (Beta-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyc3p[c] (Glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pqh2_um[p] (Plastoquinol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap_LL[c] (LL-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ddcaACP[c] (Dodecanoyl-ACP _n-C12:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_cx[c] (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdox[c] (Oxidized thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3oddecACP[c] (3-Oxododecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glu__D[c] (D-Glutamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h_cx[c] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dutp[c] (DUTP C9H11N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite paps[c] (3'-Phosphoadenylyl sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mg2[c] (Magnesium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hdeACP[c] (Cis-hexadec-9-enoyl-_acyl-carrier protein _n-C16:1) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2[c] (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite anth[c] (Anthranilate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhpt[c] (Dihydropteroate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thex2eACP[c] (Trans-Hex-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fmn[c] (FMN C17H19N4O9P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pppi[c] (Inorganic triphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udp[c] (UDP C9H11N2O12P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cit[c] (Citrate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acACP[c] (Acetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uama[c] (UDP-N-acetylmuramoyl-L-alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite eig3p[c] (D-erythro-1-_Imidazol-4-ylglycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c4mop[c] (3-Carboxy-4-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lys__L[c] (L-Lysine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 13dpg[c] (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gmp[c] (GMP C10H12N5O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite utp[c] (UTP C9H11N2O15P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdrd[c] (Reduced thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite so4[c] (Sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5apru[c] (5-Amino-6-_5'-phosphoribosylaminouracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hmppp9[c] ( 13_1-Hydroxy-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pydx5p[c] (Pyridoxal 5'-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2dhp[c] (2-Dehydropantoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ade[c] (Adenine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite asp__L[c] (L-Aspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2sephchc[c] (2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acg5p[c] (N-Acetyl-L-glutamyl 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdp[c] (GDP C10H12N5O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbyr[c] (Hydrogenobyrinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite palmACP[c] (Palmitoyl-ACP _n-C16:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pser__L[c] (O-Phospho-L-serine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ocACP[c] (Octanoyl-ACP _n-C8:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dttp[c] (DTTP C10H13N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 6pgc[c] (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gcald[c] (Glycolaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2p4c2me[c] (2-phospho-4-_cytidine 5'-diphospho-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cmp[c] (CMP C9H12N3O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pro[c] (Protein component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pi[c] (Phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pnto__R[c] (_R-Pantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dump[c] (DUMP C9H11N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite omppp9[c] (13_1-Oxo-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 23dhmp[c] (_R-2,3-Dihydroxy-3-methylpentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gtp[c] (GTP C10H12N5O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4h2oglt[c] (4 Hydroxy 2 oxoglutarate C5H4O6) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prfp[c] (1-_5-Phosphoribosyl-5-__5-phosphoribosylaminomethylideneaminoimidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite man1p[c] (D-Mannose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dxyl5p[c] (1-deoxy-D-xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hddecACP[c] (_R-3-Hydroxydodecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cu2[c] (Copper) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malACP[c] (Malonyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2mahmp[c] (2-Methyl-4-amino-5-hydroxymethylpyrimidine diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phpyr[c] (Phenylpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fe2[c] (Fe2+ mitochondria) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phllqne[c] (Phylloquinone) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite toct2eACP[c] (Trans-Oct-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dgdp[c] (DGDP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uaccg[c] (UDP-N-acetyl-3-O-_1-carboxyvinyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acald[c] (Acetaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2s[c] (Superoxide anion) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite alac__S[c] (_S-2-Acetolactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hmop[c] (_R-3-Hydroxy-3-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4abz[c] (4-Aminobenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prbamp[c] (1-_5-Phosphoribosyl-AMP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ca2[c] (Calcium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyclt[c] (Glycolate C2H3O3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite butACP[c] (Butyryl-ACP _n-C4:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppcys[c] (N-__R-4-Phosphopantothenoyl-L-cysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpgal[c] (UDPgalactose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite f6p[c] (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lac__D[c] (D-Lactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite his__L[c] (L-Histidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite agdpcbi[c] (Adenosine-GDP-cobinamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s17bp[c] (Sedoheptulose 1,7-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dctp[c] (DCTP C9H12N3O13P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thf[c] (5,6,7,8-Tetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 25aics[c] (_S-2-_5-Amino-1-_5-phospho-D-ribosylimidazole-4-carboxamidosuccinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ni2[c] (Nickel) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dtdp4d6dg[c] (DTDP-4-dehydro-6-deoxy-D-glucose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malcoa[c] (Malonyl CoA C24H33N7O19P3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fum[c] (Fumarate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_cw[c] (Cell wall component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ACP[c] (Acyl carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mlthf[c] (5,10-Methylenetetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h[p] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhf[c] (7,8-Dihydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dudp[c] (DUDP C9H11N2O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3omrsACP[c] (3-Oxotetradecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trnaglu[c] (TRNA _Glu) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pre6a[c] (Precorrin 6A) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ametam[c] (S-Adenosylmethioninamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hhexACP[c] (_R-3-Hydroxyhexanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppan[c] (D-4'-Phosphopantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite quln[c] (Quinolinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite frdp[c] (Farnesyl diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyald[c] (D-Glyceraldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uacgam[c] (UDP-N-acetyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pram[c] (5-Phospho-beta-D-ribosylamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap__M[c] (Meso-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdpmann[c] (GDP-D-mannose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite db4p[c] (3,4-dihydroxy-2-butanone 4-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actACP[c] (Acetoacetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actp[c] (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ugmd[c] (UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s7p[c] (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cbm[c] (Carbamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite co2[c] (CO2 CO2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite zeax[c] (Zeaxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ptrc[c] (Putrescine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adp[c] (ADP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3a2oxpp[c] (3-Amino-2-oxopropyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aspsa[c] (L-Aspartate 4-semialdehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite tdec2eACP[c] (Trans-Dec-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phom[c] (O-Phospho-L-homoserine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite amylose[c] (Amylose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5mdr1p[c] (5-Methylthio-5-deoxy-D-ribose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite rb15bp_cx[c] (D-Ribulose 1,5-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bcryptox[c] (Beta-Cryptoxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite spmd[c] (Spermidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpsq[c] (UDP-6-sulfoquinovose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2[c] (Hydrogen) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adocbip[c] (Adenosyl cobinamide phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phycy[c] (_3Z-Phycocyanobilin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nadh[c] (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aps[c] (Adenosine 5'-phosphosulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dpcoa[c] (Dephospho-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite xu5p__D[c] (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite no2[c] (Nitrite) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4hbz[c] (4-Hydroxybenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3odecACP[c] (3-Oxodecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhnpt[c] (Dihydroneopterin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5aprbu[c] (5-Amino-6-_5'-phosphoribitylaminouracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite iasp[c] (Iminoaspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nmn[c] (NMN C11H14N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pigm[c] (Pigment component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2cpr5p[c] (1-_2-Carboxyphenylamino-1-deoxy-D-ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pchlld[c] (Protochlorophyllide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_u (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala__L[c] (L-Alanine) has no seed_id

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC11M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMDPHT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYCOPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RB15BPtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DB4PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXPRIi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTPCII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EHGLAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDX5PS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPDi_nadp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRC3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RZ5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6YM_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DDPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNabc_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMMM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_23dhmp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPMD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PGtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPMEK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITCIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DVOCHR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2CO3_NAt_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEMEOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAMAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITCIb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_COFACTORS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSERTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR160y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDHf : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR3_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDAPAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E_1_cx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACODA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLU5K : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR100y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPOb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_h2_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPTASECG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHCS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_4_um_copy1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGCVT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSL2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRASCSi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRDR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTRCabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3MT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCOATA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HMBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGLYCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HTHRPDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCT1_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPDDI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPODM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MAN6PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSERT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NNDPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CUabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCYRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPCcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR180y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHRDH_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRAIi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTPATi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6AR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPTc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC20M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHFR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHPPDA : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHORM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCBT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:E4PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLGC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cu2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THISAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DBTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BACCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_amob_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADNK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CCGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUERT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SAMTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPXQR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGLDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMAND : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GFUCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPGLC46DH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_1_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_4_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KAS15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACPS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDR18 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDDC17 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT161 : thermo constraint NOT created

Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT1819Z_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQDGS_PALM_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPDAGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGPS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGPP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COCHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1bpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181_9 : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FNOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD1ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PBDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCALDD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLBRAN2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCGLYCabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLMS_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUCYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUK_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUSx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCL_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCTO1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOXG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSDxi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMACTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LALDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCARS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LGTHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MAN1PT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDH_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MI1PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MI1PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFD2i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NABTNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_1u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_2p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_2u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_3u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:P5CD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:P5CRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC17M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHbr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHcr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDX5PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYTES2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPNCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUTA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYAM5PO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBCh : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HESR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACALD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACNML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT120 : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HADPCOADH3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HBZOPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEPT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HG2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HKNDDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HKNTDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HMPK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPACOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPPK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPPPNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXAND : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICYSDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILEabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:INDOLEt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ISETACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:K2L4Aabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:K2L4Aabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCADi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCARSyi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDGUNPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDH_D2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LKDRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LSERDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSAM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:L_LACD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:L_LACD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALDDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTATr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTHXabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MANGLYCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MANptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCITL2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCPST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP1App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP2App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP5pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDH5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEPNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METSOXR1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METSOXR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MICITDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MINCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP1App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP2App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP2Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP3App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN2tipp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNLptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOADSUx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP1 : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCOAT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OOR3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXOAEL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXPTNDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPCK_re : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGK_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC80 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPDK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPKr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRDX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSSA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSSA180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QRr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RIBabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S7PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SALCHS4abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHSL2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCBZT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCBZT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA2i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TREabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TSULabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2t4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4CMLCL_kt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5CM2HMUDI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMPM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD31_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHGMtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APENTAMAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APTNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPHs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BSCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COALCDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CONFRLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CONFRLtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYOO2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAPDA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DCMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGNSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGSNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNAOT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DKMPPD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DTMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ECOAH12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EDTXS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ETOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_12ppd__S_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_2hxmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_3mb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_4hbz_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_4hphac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_agm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ala__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_amp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_anhgm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arbt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_aso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_aso4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_asp__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_btoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_but_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_buts_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_butso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_bz_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cell4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cell500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cellb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cgly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cit_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_confrl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dad_2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_damp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dca_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dcmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dcyt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dextrin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dgmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dgsn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_drib_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dtmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_duri_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_enter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_eths_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sulfac_e : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B
Warning : BO3/B

Streaming output truncated to the last 5000 lines.
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for starch[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_starch[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for zcarote[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_zcarote[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 1h12dhl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_1h12dhl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhrdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhrdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34thsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34thsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhr[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhr[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for sxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_sxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for phytfl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_phytfl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for phytof[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_phytof[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for pq[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_pq[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for neuspn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_neuspn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 3vbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_3vbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 3hebcpd[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_3hebcpd[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpda[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpda[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpdb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpdb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ggbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ggbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ggbcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ggbcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bo3[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bo3[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bo3[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bo3[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bm_min[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bm_min[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bm_oth[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bm_oth[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4abut[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4abut[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4hpro_LT[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4hpro_LT[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5dglcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5dglcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5oxpro[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5oxpro[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acac[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acac[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acglu[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acglu[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acmana[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acmana[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for akg[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_akg[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for arab__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_arab__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for asn__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_asn__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for citm[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_citm[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for etha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_etha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for f6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_f6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fum[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fum[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g1p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g1p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gal[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gal[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ghb[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ghb[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glu__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glu__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glyclt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glyclt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glycogen[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glycogen[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hpyr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hpyr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hxa[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hxa[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for inost[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_inost[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lac__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lac__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for malttr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_malttr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for man[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_man[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for xyl__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_xyl__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 12ppd__S[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_12ppd__S[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4abut[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4abut[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4hpro_LT[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4hpro_LT[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5dglcn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5dglcn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5oxpro[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5oxpro[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acac[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acac[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acglu[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acglu[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for asn__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_asn__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for citm[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_citm[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for etha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_etha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for f6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_f6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fum[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fum[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ghb[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ghb[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glyclt[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glyclt[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glycogen[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glycogen[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hpyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hpyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for inost[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_inost[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lac__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lac__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for oxa[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_oxa[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for pyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_pyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for tartr__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_tartr__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rbl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rbl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ru5p__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ru5p__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gal1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gal1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fcl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fcl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fc1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fc1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcur[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcur[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fruur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fruur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mana[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mana[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2ddglcn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2ddglcn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for xylu__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_xylu__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mnl[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mnl[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2dh3dgal[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2dh3dgal[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2dh3dgal6p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2dh3dgal6p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rml[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rml[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rml1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rml1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for melib[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_melib[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gam[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gam[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lcts[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lcts[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dkdi[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dkdi[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for d5kg[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_d5kg[c]

In [ ]:


# --------------------------------------
# 3. MANUAL SEED-ID ANNOTATION (COFACTORS ONLY)
# --------------------------------------
SEED_MAP1 = {
    "h[c]":     "cpd00067",
    "nadp[c]":  "cpd00005",
    "nadph[c]": "cpd00006",
    "coa[c]":   "cpd00010"
}

for met_id, seed_id in SEED_MAP1.items():
    met = tmodel.metabolites.get_by_id(met_id)
    met.annotation["seed_id"] = seed_id


conc_bounds = {
    "nadph[c]": (1e-6, 1e-3),
    "nadp[c]":  (1e-6, 1e-3),
    "h[c]":     (1e-8, 1e-6),
    "coa[c]":   (1e-6, 1e-3),
}

for met_id, bounds in conc_bounds.items():
    met = tmodel.metabolites.get_by_id(met_id)
    met.concentration = bounds

# --------------------------------------
# 5. FORCE THERMODYNAMIC FEASIBILITY
#    Acetoacetyl-CoA reductase (AACOAR)
# --------------------------------------
# Reaction: aacoa + nadph + H -> 3hbcoa + nadp
# Literature ΔG°′ ≈ −25 to −30 kJ/mol
# We enforce directionality conservatively


from pytfa.optim.variables import DeltaG

rxn = tmodel.reactions.get_by_id("AACOAR_syn")
dg = tmodel.variables[DeltaG][rxn]

# Set thermodynamic directionality
dg.upper_bound = -1.0   # kJ/mol
dg.lower_bound = -100.0

# --------------------------------------
# 6. OPTIONAL: OBJECTIVE (PHB / growth)
# --------------------------------------
# Example: maximize PHB precursor
# tmodel.objective = "PHB_SYN"

# --------------------------------------
# 7. RUN TFA OPTIMIZATION
# --------------------------------------
solution = tmodel.optimize()

dg_value = solution.raw[dg.name]
print("ΔG_AACOAR (kJ/mol):", dg_value)


# --------------------------------------
# 8. REPORT RESULTS
# --------------------------------------
print("TFA status:", solution.status)
print("Objective value:", solution.objective_value)

print("\n--- AACOAR thermodynamics ---")
print("Flux:", solution.fluxes["AACOAR_syn"])
print("ΔG (kJ/mol):", solution.raw[tmodel.reactions.AACOAR_syn.delta_g.name])

# Optional: check PHB precursor
if "3hbcoa__R[c]" in solution.fluxes:
    print("\n3HB-CoA flux:", solution.fluxes["3hbcoa__R[c]"])

KeyError: <class 'pytfa.optim.variables.DeltaG'>

In [ ]:
from pytfa.optim.variables import DeltaG

phb_rxns = [
    "AACOAR_syn",
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
]

# Force thermo mode
tmodel.convert(add_thermo=True)

for r_id in phb_rxns:
    rxn = tmodel.reactions.get_by_id(r_id)

    dg = tmodel.variables[DeltaG][rxn]
    dg.lower_bound = -100
    dg.upper_bound = -5   # irreversible forward

TypeError: ThermoModel.convert() got an unexpected keyword argument 'add_thermo'

In [ ]:
def has_dGr_variable(tmodel, rxn_id):
    return any(v.name == f"DG_r_{rxn_id}" for v in tmodel.variables)

for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    print(rxn_id, has_dGr_variable(tmodel, rxn_id))

def thermo_constraints_for_rxn(tmodel, rxn_id):
    return [
        c.name for c in tmodel.constraints
        if rxn_id in c.name and "thermo" in c.name.lower()
    ]

for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    cons = thermo_constraints_for_rxn(tmodel, rxn_id)
    print(rxn_id, cons)


rows = []
for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    rows.append({
        "reaction": rxn_id,
        "has_DG": has_dGr_variable(tmodel, rxn_id),
        "n_thermo_constraints": len(thermo_constraints_for_rxn(tmodel, rxn_id))
    })

pd.DataFrame(rows)

ACACT1 False
ACCOAC False
PHBS_syn False
ACACT1 []
ACCOAC []
PHBS_syn []

   reaction  has_DG  n_thermo_constraints
0    ACACT1   False                     0
1    ACCOAC   False                     0
2  PHBS_syn   False                     0

In [ ]:
thermo_rxns = []

for rxn in tmodel.reactions:
    rxn_id = rxn.id

    # 1) check ΔG variable
    has_dg = f"DG_r_{rxn_id}" in [v.name for v in tmodel.variables]

    if not has_dg:
        continue

    # 2) check thermo constraints
    thermo_cons = [
        c for c in tmodel.constraints
        if rxn_id in c.name and "thermo" in c.name.lower()
    ]

    if len(thermo_cons) > 0:
        thermo_rxns.append(rxn_id)

print(f"Number of thermo-constrained reactions: {len(thermo_rxns)}")
thermo_rxns[:20]

Number of thermo-constrained reactions: 0

[]

In [ ]:
rxn = tmodel.reactions.get_by_id('PHBS_syn')
for met in rxn.metabolites:
    print(met.id, getattr(met, "seed_id", "no seed_id"))

3hbcoa__R[c] C12345
phbg[c] C23456
coa[c] C00010
PHB[c] C34567

In [ ]:
# List all variables (variable objects)
for var in tmodel.variables:
    print(var)

In [ ]:
rxn = tmodel.reactions.get_by_id('PHBS_syn')

if hasattr(rxn, 'deltaG_r') and rxn.deltaG_r in tmodel.variables:
    print(f"{rxn.id} now has a thermodynamic constraint (ΔG applied).")
else:
    print(f"{rxn.id} still does NOT have a thermodynamic constraint.")

PHBS_syn still does NOT have a thermodynamic constraint.

## Map to ModelSEED Database

*   https://modelseed.org/biochem/compounds/cpd00805

*   https://academic.oup.com/nar/article/49/D1/D575/5912569

*   https://github.com/ModelSEED/ModelSEEDpy/tree/dev/tests/biochem

*   https://github.com/ModelSEED/ModelSEEDDatabase?utm_source=chatgpt.com

In [ ]:
import json
from pathlib import Path

db_path = Path("ModelSEEDDatabase/Biochemistry/compounds.json")
if not db_path.exists():
    raise FileNotFoundError(f"File not found: {db_path}")

with open(db_path) as f:
    compounds = json.load(f)

FileNotFoundError: File not found: ModelSEEDDatabase/Biochemistry/compounds.json

In [ ]:
import json
from pathlib import Path

# Load ModelSEED compounds
with open("ModelSEEDDatabase/Biochemistry/compounds.json") as f:
    compounds = json.load(f)  # dict keyed by 'cpdXXXX'
    print(compounds)


import pandas as pd

# Load your GEM metabolites
gem_mets = [
    '13dpg_c', '2pg_c', '3pg_c', '6pgc_c', '6pgl_c', 'ac_c', 'ac_e',
    'acald_c', 'acald_e', 'accoa_c', 'acon_C_c', 'actp_c', 'adp_c',
    'akg_c', 'akg_e', 'amp_c', 'atp_c', 'cit_c', 'co2_c', 'co2_e'
]

# Load ModelSEED thermodynamic database (JSON or CSV)
thermobase = pd.read_json(db_path)  # replace with your thermodb path
# Example columns: 'id', 'name', 'formula', 'synonyms'

def map_to_modelseed(gem_mets, gem_met_info, thermobase):
    """
    gem_met_info: dict {met_id: {'name': ..., 'formula': ...}}
    thermobase: pandas DataFrame of ModelSEED compounds
    """
    mapping = {}
    unmatched = []
    for met in gem_mets:
        info = gem_met_info.get(met, {})
        formula = info.get('formula', None)
        name = info.get('name', None)

        # Match by formula first
        candidates = thermobase[thermobase['formula'] == formula]
        if len(candidates) == 1:
            mapping[met] = candidates['id'].values[0]
            continue

        # Match by name / synonym
        candidates = thermobase[
            thermobase['name'].str.lower() == name.lower() |
            thermobase['synonyms'].apply(lambda x: name.lower() in [s.lower() for s in x])
        ]
        if len(candidates) >= 1:
            mapping[met] = candidates['id'].values[0]
        else:
            unmatched.append(met)

    return mapping, unmatched

# Example usage:
# gem_met_info = {met.id: {'name': met.name, 'formula': met.formula} for met in cobra_model.metabolites}
# mapping, unmatched = map_to_modelseed(gem_mets, gem_met_info, thermobase)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
print("Number of metabolites with ΔG° info:", len(tmodel.metabolites))
print("Number of reactions with ΔG° info:", len(tmodel.reactions))

Number of metabolites with ΔG° info: 72
Number of reactions with ΔG° info: 95

In [ ]:
tmodel.prepare()  # sets up thermodynamic variables and constraints
tmodel.convert()  # adds thermodynamic constraints to the COBRA model

2025-12-02 18:56:22,544 - thermomodel_None - INFO - # Model preparation starting...
INFO:thermomodel_None:# Model preparation starting...
DEBUG:thermomodel_None:Metabolite 13dpg_c (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 2pg_c (D-Glycerate 2-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3pg_c (3-Phospho-D-glycerate) has no seed_id
DEBUG:thermomodel_None:Metabolite 6pgc_c (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_None:Metabolite 6pgl_c (6-phospho-D-glucono-1,5-lactone) has no seed_id
DEBUG:thermomodel_None:Metabolite ac_c (Acetate) has no seed_id
DEBUG:thermomodel_None:Metabolite ac_e (Acetate) has no seed_id
DEBUG:thermomodel_None:Metabolite acald_c (Acetaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite acald_e (Acetaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite accoa_c (Acetyl-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite acon_C_c (cis-Aconitate) has no seed_id
DEBUG:thermomodel_None:Metabolite actp_c (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite adp_c (ADP) has no seed_id
DEBUG:thermomodel_None:Metabolite akg_c (2-Oxoglutarate) has no seed_id
DEBUG:thermomodel_None:Metabolite akg_e (2-Oxoglutarate) has no seed_id
DEBUG:thermomodel_None:Metabolite amp_c (AMP) has no seed_id
DEBUG:thermomodel_None:Metabolite atp_c (ATP) has no seed_id
DEBUG:thermomodel_None:Metabolite cit_c (Citrate) has no seed_id
DEBUG:thermomodel_None:Metabolite co2_c (CO2) has no seed_id
DEBUG:thermomodel_None:Metabolite co2_e (CO2) has no seed_id
DEBUG:thermomodel_None:Metabolite coa_c (Coenzyme A) has no seed_id
DEBUG:thermomodel_None:Metabolite dhap_c (Dihydroxyacetone phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite e4p_c (D-Erythrose 4-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite etoh_c (Ethanol) has no seed_id
DEBUG:thermomodel_None:Metabolite etoh_e (Ethanol) has no seed_id
DEBUG:thermomodel_None:Metabolite f6p_c (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite fdp_c (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite for_c (Formate) has no seed_id
DEBUG:thermomodel_None:Metabolite for_e (Formate) has no seed_id
DEBUG:thermomodel_None:Metabolite fru_e (D-Fructose) has no seed_id
DEBUG:thermomodel_None:Metabolite fum_c (Fumarate) has no seed_id
DEBUG:thermomodel_None:Metabolite fum_e (Fumarate) has no seed_id
DEBUG:thermomodel_None:Metabolite g3p_c (Glyceraldehyde 3-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite g6p_c (D-Glucose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite glc__D_e (D-Glucose) has no seed_id
DEBUG:thermomodel_None:Metabolite gln__L_c (L-Glutamine) has no seed_id
DEBUG:thermomodel_None:Metabolite gln__L_e (L-Glutamine) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__L_c (L-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__L_e (L-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite glx_c (Glyoxylate) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_c (H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_e (H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h_c (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite h_e (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite icit_c (Isocitrate) has no seed_id
DEBUG:thermomodel_None:Metabolite lac__D_c (D-Lactate) has no seed_id
DEBUG:thermomodel_None:Metabolite lac__D_e (D-Lactate) has no seed_id
DEBUG:thermomodel_None:Metabolite mal__L_c (L-Malate) has no seed_id
DEBUG:thermomodel_None:Metabolite mal__L_e (L-Malate) has no seed_id
DEBUG:thermomodel_None:Metabolite nad_c (Nicotinamide adenine dinucleotide) has no seed_id
DEBUG:thermomodel_None:Metabolite nadh_c (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_None:Metabolite nadp_c (Nicotinamide adenine dinucleotide phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite nadph_c (Nicotinamide adenine dinucleotide phosphate - reduced) has no seed_id
DEBUG:thermomodel_None:Metabolite nh4_c (Ammonium) has no seed_id
DEBUG:thermomodel_None:Metabolite nh4_e (Ammonium) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_c (O2) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_e (O2) has no seed_id
DEBUG:thermomodel_None:Metabolite oaa_c (Oxaloacetate) has no seed_id
DEBUG:thermomodel_None:Metabolite pep_c (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite pi_c (Phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pi_e (Phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pyr_c (Pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite pyr_e (Pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite q8_c (Ubiquinone-8) has no seed_id
DEBUG:thermomodel_None:Metabolite q8h2_c (Ubiquinol-8) has no seed_id
DEBUG:thermomodel_None:Metabolite r5p_c (alpha-D-Ribose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite ru5p__D_c (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite s7p_c (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite succ_c (Succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite succ_e (Succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite succoa_c (Succinyl-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite xu5p__D_c (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:computing reaction thermodynamic data
DEBUG:thermomodel_None:ACALD : thermo constraint NOT created
DEBUG:thermomodel_None:ACALDt : thermo constraint NOT created
DEBUG:thermomodel_None:ACKr : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_None:ACt2r : thermo constraint NOT created
DEBUG:thermomodel_None:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_None:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_None:AKGt2r : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_None:ATPM : thermo constraint NOT created
DEBUG:thermomodel_None:ATPS4r : thermo constraint NOT created
DEBUG:thermomodel_None:Biomass_Ecoli_core : thermo constraint NOT created
DEBUG:thermomodel_None:CO2t : thermo constraint NOT created
DEBUG:thermomodel_None:CS : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBD : thermo constraint NOT created
DEBUG:thermomodel_None:D_LACt2 : thermo constraint NOT created
DEBUG:thermomodel_None:ENO : thermo constraint NOT created
DEBUG:thermomodel_None:ETOHt2r : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_akg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fum_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glu__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lac__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mal__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_None:FBA : thermo constraint NOT created
DEBUG:thermomodel_None:FBP : thermo constraint NOT created
DEBUG:thermomodel_None:FORt2 : thermo constraint NOT created
DEBUG:thermomodel_None:FORti : thermo constraint NOT created
DEBUG:thermomodel_None:FRD7 : thermo constraint NOT created
DEBUG:thermomodel_None:FRUpts2 : thermo constraint NOT created
DEBUG:thermomodel_None:FUM : thermo constraint NOT created
DEBUG:thermomodel_None:FUMt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:G6PDH2r : thermo constraint NOT created
DEBUG:thermomodel_None:GAPD : thermo constraint NOT created
DEBUG:thermomodel_None:GLCpts : thermo constraint NOT created
DEBUG:thermomodel_None:GLNS : thermo constraint NOT created
DEBUG:thermomodel_None:GLNabc : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDy : thermo constraint NOT created
DEBUG:thermomodel_None:GLUN : thermo constraint NOT created
DEBUG:thermomodel_None:GLUSy : thermo constraint NOT created
DEBUG:thermomodel_None:GLUt2r : thermo constraint NOT created
DEBUG:thermomodel_None:GND : thermo constraint NOT created
DEBUG:thermomodel_None:H2Ot : thermo constraint NOT created
DEBUG:thermomodel_None:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_None:ICL : thermo constraint NOT created
DEBUG:thermomodel_None:LDH_D : thermo constraint NOT created
DEBUG:thermomodel_None:MALS : thermo constraint NOT created
DEBUG:thermomodel_None:MALt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDH : thermo constraint NOT created
DEBUG:thermomodel_None:ME1 : thermo constraint NOT created
DEBUG:thermomodel_None:ME2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADH16 : thermo constraint NOT created
DEBUG:thermomodel_None:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_None:NH4t : thermo constraint NOT created
DEBUG:thermomodel_None:O2t : thermo constraint NOT created
DEBUG:thermomodel_None:PDH : thermo constraint NOT created
DEBUG:thermomodel_None:PFK : thermo constraint NOT created
DEBUG:thermomodel_None:PFL : thermo constraint NOT created
DEBUG:thermomodel_None:PGI : thermo constraint NOT created
DEBUG:thermomodel_None:PGK : thermo constraint NOT created
DEBUG:thermomodel_None:PGL : thermo constraint NOT created
DEBUG:thermomodel_None:PGM : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_None:PPC : thermo constraint NOT created
DEBUG:thermomodel_None:PPCK : thermo constraint NOT created
DEBUG:thermomodel_None:PPS : thermo constraint NOT created
DEBUG:thermomodel_None:PTAr : thermo constraint NOT created
DEBUG:thermomodel_None:PYK : thermo constraint NOT created
DEBUG:thermomodel_None:PYRt2 : thermo constraint NOT created
DEBUG:thermomodel_None:RPE : thermo constraint NOT created
DEBUG:thermomodel_None:RPI : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt3 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_None:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:TALA : thermo constraint NOT created
DEBUG:thermomodel_None:THD2 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT2 : thermo constraint NOT created
DEBUG:thermomodel_None:TPI : thermo constraint NOT created
2025-12-02 18:56:22,767 - thermomodel_None - INFO - # Model preparation done.
INFO:thermomodel_None:# Model preparation done.
2025-12-02 18:56:22,768 - thermomodel_None - INFO - # Model conversion starting...
INFO:thermomodel_None:# Model conversion starting...
DEBUG:thermomodel_None:generating thermo variables for 13dpg_c
DEBUG:thermomodel_None:Added variable: LC_13dpg_c
DEBUG:thermomodel_None:generating thermo variables for 2pg_c
DEBUG:thermomodel_None:Added variable: LC_2pg_c
DEBUG:thermomodel_None:generating thermo variables for 3pg_c
DEBUG:thermomodel_None:Added variable: LC_3pg_c
DEBUG:thermomodel_None:generating thermo variables for 6pgc_c
DEBUG:thermomodel_None:Added variable: LC_6pgc_c
DEBUG:thermomodel_None:generating thermo variables for 6pgl_c
DEBUG:thermomodel_None:Added variable: LC_6pgl_c
DEBUG:thermomodel_None:generating thermo variables for ac_c
DEBUG:thermomodel_None:Added variable: LC_ac_c
DEBUG:thermomodel_None:generating thermo variables for ac_e
DEBUG:thermomodel_None:Added variable: LC_ac_e
DEBUG:thermomodel_None:generating thermo variables for acald_c
DEBUG:thermomodel_None:Added variable: LC_acald_c
DEBUG:thermomodel_None:generating thermo variables for acald_e
DEBUG:thermomodel_None:Added variable: LC_acald_e
DEBUG:thermomodel_None:generating thermo variables for accoa_c
DEBUG:thermomodel_None:Added variable: LC_accoa_c
DEBUG:thermomodel_None:generating thermo variables for acon_C_c
DEBUG:thermomodel_None:Added variable: LC_acon_C_c
DEBUG:thermomodel_None:generating thermo variables for actp_c
DEBUG:thermomodel_None:Added variable: LC_actp_c
DEBUG:thermomodel_None:generating thermo variables for adp_c
DEBUG:thermomodel_None:Added variable: LC_adp_c
DEBUG:thermomodel_None:generating thermo variables for akg_c
DEBUG:thermomodel_None:Added variable: LC_akg_c
DEBUG:thermomodel_None:generating thermo variables for akg_e
DEBUG:thermomodel_None:Added variable: LC_akg_e
DEBUG:thermomodel_None:generating thermo variables for amp_c
DEBUG:thermomodel_None:Added variable: LC_amp_c
DEBUG:thermomodel_None:generating thermo variables for atp_c
DEBUG:thermomodel_None:Added variable: LC_atp_c
DEBUG:thermomodel_None:generating thermo variables for cit_c
DEBUG:thermomodel_None:Added variable: LC_cit_c
DEBUG:thermomodel_None:generating thermo variables for co2_c
DEBUG:thermomodel_None:Added variable: LC_co2_c
DEBUG:thermomodel_None:generating thermo variables for co2_e
DEBUG:thermomodel_None:Added variable: LC_co2_e
DEBUG:thermomodel_None:generating thermo variables for coa_c
DEBUG:thermomodel_None:Added variable: LC_coa_c
DEBUG:thermomodel_None:generating thermo variables for dhap_c
DEBUG:thermomodel_None:Added variable: LC_dhap_c
DEBUG:thermomodel_None:generating thermo variables for e4p_c
DEBUG:thermomodel_None:Added variable: LC_e4p_c
DEBUG:thermomodel_None:generating thermo variables for etoh_c
DEBUG:thermomodel_None:Added variable: LC_etoh_c
DEBUG:thermomodel_None:generating thermo variables for etoh_e
DEBUG:thermomodel_None:Added variable: LC_etoh_e
DEBUG:thermomodel_None:generating thermo variables for f6p_c
DEBUG:thermomodel_None:Added variable: LC_f6p_c
DEBUG:thermomodel_None:generating thermo variables for fdp_c
DEBUG:thermomodel_None:Added variable: LC_fdp_c
DEBUG:thermomodel_None:generating thermo variables for for_c
DEBUG:thermomodel_None:Added variable: LC_for_c
DEBUG:thermomodel_None:generating thermo variables for for_e
DEBUG:thermomodel_None:Added variable: LC_for_e
DEBUG:thermomodel_None:generating thermo variables for fru_e
DEBUG:thermomodel_None:Added variable: LC_fru_e
DEBUG:thermomodel_None:generating thermo variables for fum_c
DEBUG:thermomodel_None:Added variable: LC_fum_c
DEBUG:thermomodel_None:generating thermo variables for fum_e
DEBUG:thermomodel_None:Added variable: LC_fum_e
DEBUG:thermomodel_None:generating thermo variables for g3p_c
DEBUG:thermomodel_None:Added variable: LC_g3p_c
DEBUG:thermomodel_None:generating thermo variables for g6p_c
DEBUG:thermomodel_None:Added variable: LC_g6p_c
DEBUG:thermomodel_None:generating thermo variables for glc__D_e
DEBUG:thermomodel_None:Added variable: LC_glc__D_e
DEBUG:thermomodel_None:generating thermo variables for gln__L_c
DEBUG:thermomodel_None:Added variable: LC_gln__L_c
DEBUG:thermomodel_None:generating thermo variables for gln__L_e
DEBUG:thermomodel_None:Added variable: LC_gln__L_e
DEBUG:thermomodel_None:generating thermo variables for glu__L_c
DEBUG:thermomodel_None:Added variable: LC_glu__L_c
DEBUG:thermomodel_None:generating thermo variables for glu__L_e
DEBUG:thermomodel_None:Added variable: LC_glu__L_e
DEBUG:thermomodel_None:generating thermo variables for glx_c
DEBUG:thermomodel_None:Added variable: LC_glx_c
DEBUG:thermomodel_None:Added variable: LC_h2o_c
DEBUG:thermomodel_None:Added variable: LC_h2o_e
DEBUG:thermomodel_None:Added variable: LC_h_c
DEBUG:thermomodel_None:Added variable: LC_h_e
DEBUG:thermomodel_None:generating thermo variables for icit_c
DEBUG:thermomodel_None:Added variable: LC_icit_c
DEBUG:thermomodel_None:generating thermo variables for lac__D_c
DEBUG:thermomodel_None:Added variable: LC_lac__D_c
DEBUG:thermomodel_None:generating thermo variables for lac__D_e
DEBUG:thermomodel_None:Added variable: LC_lac__D_e
DEBUG:thermomodel_None:generating thermo variables for mal__L_c
DEBUG:thermomodel_None:Added variable: LC_mal__L_c
DEBUG:thermomodel_None:generating thermo variables for mal__L_e
DEBUG:thermomodel_None:Added variable: LC_mal__L_e
DEBUG:thermomodel_None:generating thermo variables for nad_c
DEBUG:thermomodel_None:Added variable: LC_nad_c
DEBUG:thermomodel_None:generating thermo variables for nadh_c
DEBUG:thermomodel_None:Added variable: LC_nadh_c
DEBUG:thermomodel_None:generating thermo variables for nadp_c
DEBUG:thermomodel_None:Added variable: LC_nadp_c
DEBUG:thermomodel_None:generating thermo variables for nadph_c
DEBUG:thermomodel_None:Added variable: LC_nadph_c
DEBUG:thermomodel_None:generating thermo variables for nh4_c
DEBUG:thermomodel_None:Added variable: LC_nh4_c
DEBUG:thermomodel_None:generating thermo variables for nh4_e
DEBUG:thermomodel_None:Added variable: LC_nh4_e
DEBUG:thermomodel_None:generating thermo variables for o2_c
DEBUG:thermomodel_None:Added variable: LC_o2_c
DEBUG:thermomodel_None:generating thermo variables for o2_e
DEBUG:thermomodel_None:Added variable: LC_o2_e
DEBUG:thermomodel_None:generating thermo variables for oaa_c
DEBUG:thermomodel_None:Added variable: LC_oaa_c
DEBUG:thermomodel_None:generating thermo variables for pep_c
DEBUG:thermomodel_None:Added variable: LC_pep_c
DEBUG:thermomodel_None:generating thermo variables for pi_c
DEBUG:thermomodel_None:Added variable: LC_pi_c
DEBUG:thermomodel_None:generating thermo variables for pi_e
DEBUG:thermomodel_None:Added variable: LC_pi_e
DEBUG:thermomodel_None:generating thermo variables for pyr_c
DEBUG:thermomodel_None:Added variable: LC_pyr_c
DEBUG:thermomodel_None:generating thermo variables for pyr_e
DEBUG:thermomodel_None:Added variable: LC_pyr_e
DEBUG:thermomodel_None:generating thermo variables for q8_c
DEBUG:thermomodel_None:Added variable: LC_q8_c
DEBUG:thermomodel_None:generating thermo variables for q8h2_c
DEBUG:thermomodel_None:Added variable: LC_q8h2_c
DEBUG:thermomodel_None:generating thermo variables for r5p_c
DEBUG:thermomodel_None:Added variable: LC_r5p_c
DEBUG:thermomodel_None:generating thermo variables for ru5p__D_c
DEBUG:thermomodel_None:Added variable: LC_ru5p__D_c
DEBUG:thermomodel_None:generating thermo variables for s7p_c
DEBUG:thermomodel_None:Added variable: LC_s7p_c
DEBUG:thermomodel_None:generating thermo variables for succ_c
DEBUG:thermomodel_None:Added variable: LC_succ_c
DEBUG:thermomodel_None:generating thermo variables for succ_e
DEBUG:thermomodel_None:Added variable: LC_succ_e
DEBUG:thermomodel_None:generating thermo variables for succoa_c
DEBUG:thermomodel_None:Added variable: LC_succoa_c
DEBUG:thermomodel_None:generating thermo variables for xu5p__D_c
DEBUG:thermomodel_None:Added variable: LC_xu5p__D_c
DEBUG:thermomodel_None:generating only use constraints for reactionACALD
DEBUG:thermomodel_None:Added variable: FU_ACALD
DEBUG:thermomodel_None:Added variable: BU_ACALD
DEBUG:thermomodel_None:Added constraint: SU_ACALD
DEBUG:thermomodel_None:Added constraint: UF_ACALD
DEBUG:thermomodel_None:Added constraint: UR_ACALD
DEBUG:thermomodel_None:generating only use constraints for reactionACALDt
DEBUG:thermomodel_None:Added variable: FU_ACALDt
DEBUG:thermomodel_None:Added variable: BU_ACALDt
DEBUG:thermomodel_None:Added constraint: SU_ACALDt
DEBUG:thermomodel_None:Added constraint: UF_ACALDt
DEBUG:thermomodel_None:Added constraint: UR_ACALDt
DEBUG:thermomodel_None:generating only use constraints for reactionACKr
DEBUG:thermomodel_None:Added variable: FU_ACKr