# TFBA for R. palustris GEM

Constraint-based analysis on genome-scale metabolic models (GEMs) is a popular method to study metabolism and cellular physiology. Flux Balance Analysis (FBA), in particular, has been used to predict network-level behaviors, such as specific growth rate, gene essentiality, etc. However, FBA-derived approaches often lead to flux distributions
that are contradicting with physiology and bioenergetics due to the
lack of thermodynamic constraints in their formulation. Metabolic reactions in GEMs can be futher constrained thermodynamically using TFA (Salvy...Meric et., al, 2019).

References

*   https://github.com/EPFL-LCSB/pytfa/tree/master
*   Bioinformatics, 35(1), 2019, 167–169
doi: 10.1093/bioinformatics/bty499

# Install dependencies

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
!rm -rf /root/.cache/pip

In [3]:
import importlib.util
print(importlib.util.find_spec("pytfa"))

None

In [1]:
!pip3 install pytfa cobra optlang modelseedpy

Collecting pytfa
  Downloading pytfa-0.9.4-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.4 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/bb/ac/1d6a4a72f45bfa46a95d3cc9f29c113c5f4a4ece4ac7461b56ac61c2fa2c/pytfa-0.9.4-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.3-py2.py3-none-any.whl.metadata (1.2 kB)
WARNING: Ignoring version 0.9.3 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/a3/b4/9d3a72b34043fc5e4b75afcefd2d386ebab18ca99690cfa1c4c01612c77d/pytfa-0.9.3-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.2-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.2 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/52/75/1b2114796a7f0b51ce973798805a5ccf5e929078bc65e59dc44b4f5601ea/pytfa-0.9.2-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6"); extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Downloading pytfa-0.9.1.tar.gz (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting cobra
  Downloading cobra-0.30.0-py2.py3-none-any.whl.metadata (9.3 kB)
Collecting optlang
  Downloading optlang-1.8.3-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting modelseedpy
  Downloading modelseedpy-0.4.2-py3-none-any.whl.metadata (5.7 kB)
Collecting pytfa
  Using cached pytfa-0.9.4-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.4 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/bb/ac/1d6a4a72f45bfa46a95d3cc9f29c113c5f4a4ece4ac7461b56ac61c2fa2c/pytfa-0.9.4-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Using cached pytfa-0.9.3-py2.py3-none-any.whl.metadata (1.2 kB)
WARNING: Ignoring version 0.9.3 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/a3/b4/9d3a72b34043fc5e4b75afcefd2d386ebab18ca99690cfa1c4c01612c77d/pytfa-0.9.3-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6") ; extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
  Using cached pytfa-0.9.2-py2.py3-none-any.whl.metadata (1.3 kB)
WARNING: Ignoring version 0.9.2 of pytfa since it has invalid metadata:
Requested pytfa from https://files.pythonhosted.org/packages/52/75/1b2114796a7f0b51ce973798805a5ccf5e929078bc65e59dc44b4f5601ea/pytfa-0.9.2-py2.py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    python-version (>="3.6"); extra == 'equilibrator'
                   ~^
Please use pip<24.1 if you need to use this version.
Requirement already satisfied: bokeh>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pytfa) (3.8.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pytfa) (3.6.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (from pytfa) (8.4.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pytfa) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pytfa) (4.67.3)
Collecting appdirs~=1.4 (from cobra)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting depinfo~=2.2 (from cobra)
  Downloading depinfo-2.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting diskcache~=5.0 (from cobra)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from cobra) (1.0.0)
Requirement already satisfied: httpx~=0.24 in /usr/local/lib/python3.12/dist-packages (from cobra) (0.28.1)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.0.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.2.2)
Requirement already satisfied: pydantic>=1.6 in /usr/local/lib/python3.12/dist-packages (from cobra) (2.12.3)
Collecting python-libsbml~=5.19 (from cobra)
  Downloading python_libsbml-5.21.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (666 bytes)
Requirement already satisfied: rich>=8.0 in /usr/local/lib/python3.12/dist-packages (from cobra) (13.9.4)
Collecting ruamel.yaml~=0.16 (from cobra)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting swiglpk (from cobra)
  Downloading swiglpk-5.0.13-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Requirement already satisfied: sympy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from optlang) (1.14.0)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from modelseedpy) (1.6.1)
Collecting chemicals>=1.0.13 (from modelseedpy)
  Downloading chemicals-1.5.1-py3-none-any.whl.metadata (15 kB)
Collecting chemw>=0.3.2 (from modelseedpy)
  Downloading ChemW-0.3.5.tar.gz (467 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.6/467.6 kB 20.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from modelseedpy) (3.10.0)
Requirement already satisfied: Jinja2>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from modelseedpy) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (2.18.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (26.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=0.12.1->pytfa) (2025.11.0)
Collecting fluids>=1.1.0 (from chemicals>=1.0.13->modelseedpy)
  Downloading fluids-1.3.0-py3-none-any.whl.metadata (8.9 kB)
Collecting pubchempy (from chemw>=0.3.2->modelseedpy)
  Downloading pubchempy-1.0.5-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from chemw>=0.3.2->modelseedpy) (2.32.4)
Collecting sigfig (from chemw>=0.3.2->modelseedpy)
  Downloading sigfig-1.3.19-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx~=0.24->cobra) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx~=0.24->cobra) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1.4->modelseedpy) (3.0.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->modelseedpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->modelseedpy) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->modelseedpy) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->modelseedpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->modelseedpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->cobra) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->cobra) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.6->cobra) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=8.0->cobra) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=8.0->cobra) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->modelseedpy) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->modelseedpy) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.12.0->optlang) (1.3.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest->pytfa) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest->pytfa) (1.6.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=8.0->cobra) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->modelseedpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->chemw>=0.3.2->modelseedpy) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->chemw>=0.3.2->modelseedpy) (2.5.0)
Collecting sortedcontainers<3.0.0,>=2.4.0 (from sigfig->chemw>=0.3.2->modelseedpy)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Downloading cobra-0.30.0-py2.py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 32.1 MB/s eta 0:00:00
Downloading optlang-1.8.3-py2.py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.8/141.8 kB 8.5 MB/s eta 0:00:00
Downloading modelseedpy-0.4.2-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 9.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading chemicals-1.5.1-py3-none-any.whl (22.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 65.6 MB/s eta 0:00:00
Downloading depinfo-2.2.0-py3-none-any.whl (24 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.0 MB/s eta 0:00:00
Downloading python_libsbml-5.21.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 91.0 MB/s eta 0:00:00
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 12.9 MB/s eta 0:00:00
Downloading swiglpk-5.0.13-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 86.1 MB/s eta 0:00:00
Downloading fluids-1.3.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.5/608.5 kB 47.5 MB/s eta 0:00:00
Downloading pubchempy-1.0.5-py3-none-any.whl (21 kB)
Downloading sigfig-1.3.19-py3-none-any.whl (10 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: pytfa, chemw
  Building wheel for pytfa (setup.py) ... done
  Created wheel for pytfa: filename=pytfa-0.9.1-py2.py3-none-any.whl size=79010 sha256=6a656eec98df88cf9f9f6acece4932a5527baf8dcaf9c48f6d328b8b9f4dfa7c
  Stored in directory: /root/.cache/pip/wheels/57/6d/67/ea678b40a1eb60b5e1716a0c6bc9c318a75fe5f033bb490b6e
  Building wheel for chemw (setup.py) ... done
  Created wheel for chemw: filename=ChemW-0.3.5-py3-none-any.whl size=480096 sha256=edd08ec8f643c6531b57210a16f10eda345332976ff696a6793775271748b336
  Stored in directory: /root/.cache/pip/wheels/a2/47/0b/2f96a35de8e49a49bfe63d6c9d11dec35ef813d66703645e35
Successfully built pytfa chemw
Installing collected packages: swiglpk, sortedcontainers, python-libsbml, appdirs, sigfig, ruamel.yaml, pubchempy, diskcache, depinfo, optlang, fluids, cobra, chemicals, pytfa, chemw, modelseedpy
Successfully installed appdirs-1.4.4 chemicals-1.5.1 chemw-0.3.5 cobra-0.30.0 depinfo-2.2.0 diskcache-5.6.3 fluids-1.3.0 modelseedpy-0.4.2 optlang-1.8.3 pubchempy-1.0.5 pytfa-0.9.1 python-libsbml-5.21.1 ruamel.yaml-0.19.1 sigfig-1.3.19 sortedcontainers-2.4.0 swiglpk-5.0.13

In [ ]:
# Check installation
!pip3 show cobra

Name: cobra
Version: 0.30.0
Summary: COBRApy is a package for constraint-based modeling of metabolic networks.
Home-page: https://opencobra.github.io/cobrapy
Author: The cobrapy core development team.
Author-email: cobra-pie@googlegroups.com
License: LGPL-2.0-or-later OR GPL-2.0-or-later
Location: /usr/local/lib/python3.12/dist-packages
Requires: appdirs, depinfo, diskcache, future, httpx, numpy, optlang, pandas, pydantic, python-libsbml, rich, ruamel.yaml, swiglpk
Required-by: ModelSEEDpy, pytfa

In [ ]:
!pip3 show pytfa

Name: pytfa
Version: 0.9.1
Summary: pyTFA, Thermodynamics-based Flux Analysis in Python
Home-page: https://github.com/EPFL-LCSB/pytfa/
Author: pyTFA team
Author-email: softwares.lcsb@epfl.ch
License: Apache 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: bokeh, cobra, networkx, optlang, pytest, scipy, tqdm
Required-by:

## Mount drive

In [2]:
import os
from pathlib import Path
from google.colab import drive

def mount_drive():
  drive.mount('/content/drive', force_remount=True)
  drive_folder = "metabolic_modelling/phb-optimization-rpalustris/"
  os.chdir('/content/drive/MyDrive/'+ drive_folder)
  global PROJECT_ROOT
  PROJECT_ROOT = Path(os.getcwd())

mount_drive()

Mounted at /content/drive

In [ ]:
!pwd

/content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris

# Load packages

In [12]:
# Load packages

import logging
import cobra
from cobra import Reaction, Metabolite, Model, io
from cobra.io import (
    load_model, load_json_model, save_json_model,
    load_matlab_model, save_matlab_model,
    read_sbml_model, write_sbml_model,
)

from cobra.flux_analysis import flux_variability_analysis, pfba

from cobra.util.solver import linear_reaction_coefficients

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
from itertools import product
import seaborn as sns
import json
import math
import copy
from tqdm import tqdm
import sys
import seaborn as sns
from scipy.stats import mannwhitneyu
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import pytfa, pkgutil, inspect
from pytfa.thermo import ThermoModel
from pytfa.io import load_thermoDB
from pytfa.optim.variables import DeltaG
from pytfa.analysis import variability_analysis

from pytfa.io import read_lexicon, annotate_from_lexicon, read_compartment_data, apply_compartment_data

# Set paths

In [13]:
# Import path saved in src

import sys
sys.path.append(str(PROJECT_ROOT / "src"))
from src.paths import PHBV_MODEL_DIR, PHB_TFA_DIR, PHB_MODEL_TFA_DIR, DATA_DIR, MODELS_DIR, PHB_MODEL_DIR, PHB_CHECKPOINTS_DIR, PHB_RESULTS_DIR, PHB_FIGURES_DIR, PHB_GEM_EXPERIMENTAL_DIR, PHB_GEM_AUGMENTATION_DIR, PHB_CATBOOST_DIR, PHB_PARETO_DIR

# Load thermo data

In [14]:
# Download thermo data from source page
from src.paths import DATA_DIR

!wget https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb -O {DATA_DIR}/thermo_data.thermodb
# Load thermodynamics

thermo_data_path = DATA_DIR / "thermo_data.thermodb"
thermo_data = load_thermoDB(thermo_data_path)

# Print thermo_data keys

print(f"Thermo Data loaded successfully:{thermo_data.keys()}")

--2026-03-18 02:39:57--  https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2184378 (2.1M) [application/octet-stream]
Saving to: ‘/content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/data/thermo_data.thermodb’

/content/drive/MyDr 100%[===================>]   2.08M  --.-KB/s    in 0.1s

2026-03-18 02:39:58 (20.4 MB/s) - ‘/content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/data/thermo_data.thermodb’ saved [2184378/2184378]

Thermo Data loaded successfully:dict_keys(['name', 'units', 'metabolites', 'cues'])

# E.coli TFA tutorial

## Load E. coli model and data

In [ ]:
# Import ecoli model from tutorial

from pytfa.io import import_matlab_model

from pathlib import Path

tutorial_root = Path(
    "/content/drive/MyDrive/metabolic_modelling/other_materials/pytfa/"
)
print(tutorial_root)
ec_model_mat_path = tutorial_root / "models"/"small_ecoli.mat"
ec_model_json_path = tutorial_root / "models"/ "iJO1366.json"
ec_model_lexicon_path = tutorial_root / "models"/ "iJO1366" / "lexicon.csv"
ec_model_comp_path = tutorial_root / "models"/ "iJO1366" /"compartment_data.json"

/content/drive/MyDrive/metabolic_modelling/other_materials/pytfa

In [ ]:
ecoli_model= load_json_model(ec_model_json_path)

In [ ]:
ecoli_model.compartments

{'c': '', 'e': '', 'p': ''}

In [ ]:
lexicon = read_lexicon(ec_model_lexicon_path)
lexicon.columns

Index(['seed_id'], dtype='object')

In [ ]:
mytfa.solver = "glpk"
mytfa.objective = biomass_rxn

# Solver settings

def apply_solver_settings(model, solver = "glpk"):
    model.solver = "glpk"
    # model.solver.configuration.verbosity = 1
    model.solver.configuration.tolerances.feasibility = 1e-9
    if solver == 'optlang_gurobi':
        model.solver.problem.Params.NumericFocus = 3
    model.solver.configuration.presolve = True

apply_solver_settings(mytfa)

NameError: name 'mytfa' is not defined

In [ ]:
mytfa.convert()#add_displacement = True)

## Info on the cobra_model
mytfa.summary()

## Optimality
tfa_solution = mytfa_rpalustris.optimize()
tfa_value = tfa_solution.objective_value

NameError: name 'mytfa' is not defined

In [ ]:
# List metabolites with thermo data
annotated = [m.id for m in mytfa.metabolites if hasattr(m, "thermo")]
print(f"Metabolites annotated with thermodynamic data: {len(annotated)} / {len(mytfa.metabolites)}")

Metabolites annotated with thermodynamic data: 1807 / 1807

# R. palustirs TFA

## Load COBRA model

In [21]:
# Load COBRA modele produced in notebook 2

cobra_model = load_json_model(
    PHB_MODEL_DIR / "02_model_rpalustris_PHB_constrained.json"
)

## Correct formulas of key metabolites

In [16]:
# The following metabolites are

import re
from collections import Counter

# --------------------------------
# INPUT DATA
# --------------------------------
Thermodb_meta_interest = [
  "C21H27N7O17P3",
  "C21H27N7O14P2",
  "C23H35N7O17P3S",
  "C21H26N7O14P2",
  "C25H39N7O18P3S",
  "C21H26N7O17P3",
  "C25H37N7O18P3S",
  "C21H33N7O16P3S"
]

GEM_meta_interest = [
  "C21H26N7O17P3",
  "C21H27N7O14P2",
  "C23H34N7O17P3S",
  "C21H26N7O14P2",
  "C25H38N7O18P3S",
  "C21H25N7O17P3",
  "C25H36N7O18P3S",
  "C21H32N7O16P3S"
]

# GEM metabolite IDs in SAME ORDER
gem_met_ids = [
  "nadph_c",
  "nadh_c",
  "accoa_c",
  "nad_c",
  "3hbcoa__R_c",
  "nadp_c",
  "aacoa_c",
  "coa_c",
]

# --------------------------------
# FORMULA PARSING UTILITIES
# --------------------------------
def parse_formula(formula):
  """Convert formula string to Counter"""
  return Counter({
      elem: int(count) if count else 1
      for elem, count in re.findall(r'([A-Z][a-z]?)(\d*)', formula)
  })

def counter_to_formula(counter):
  """Convert Counter back to formula string (Hill order, omit 1s)"""
  parts = []

  # Hill system: C, H, then others alphabetically
  if 'C' in counter:
      parts.append(f"C{counter['C']}" if counter['C'] != 1 else "C")
  if 'H' in counter:
      parts.append(f"H{counter['H']}" if counter['H'] != 1 else "H")

  for el in sorted(counter):
      if el in ('C', 'H'):
          continue
      count = counter[el]
      parts.append(f"{el}{count}" if count != 1 else el)

  return ''.join(parts)


def compare_formulas(thermo_f, gem_f):
  """Return element-wise difference GEM − ThermoDB"""
  t = parse_formula(thermo_f)
  g = parse_formula(gem_f)
  elements = set(t) | set(g)
  return {el: g.get(el, 0) - t.get(el, 0) for el in elements}

def update_gem_formula(gem_f, thermo_f):
  """Add missing elements from ThermoDB into GEM formula"""
  g = parse_formula(gem_f)
  t = parse_formula(thermo_f)

  for el, count in t.items():
      if g.get(el, 0) < count:
          g[el] = count

  return counter_to_formula(g)

# --------------------------------
# APPLY UPDATES TO MODEL
# --------------------------------
for met_id, thermo_f, gem_f in zip(gem_met_ids,
                                  Thermodb_meta_interest,
                                  GEM_meta_interest):

    diff = compare_formulas(thermo_f, gem_f)

    # Safety check (CRITICAL for TFA)
    for el in diff:
        if el in ("C", "N", "P") and diff[el] != 0:
            raise ValueError(
                f"Unsafe formula mismatch for {met_id}: element {el}"
            )

    new_formula = update_gem_formula(gem_f, thermo_f)

    if new_formula != gem_f:
        met = cobra_model.metabolites.get_by_id(met_id) ## update cobra model

        print(f"Updating {met_id}")
        print(f"  old: {gem_f}")
        print(f"  new: {new_formula}")
        print(f"  ThermoDB:       {thermo_f}")

        met.formula = new_formula

        # PRINT FROM MODEL OBJECT
        print(f"  new (model):  {met.formula}")
        print("-" * 40)


print("GEM formulas updated and TFA-ready.")

Updating nadph_c
  old: C21H26N7O17P3
  new: C21H27N7O17P3
  ThermoDB:       C21H27N7O17P3
  new (model):  C21H27N7O17P3
----------------------------------------
Updating accoa_c
  old: C23H34N7O17P3S
  new: C23H35N7O17P3S
  ThermoDB:       C23H35N7O17P3S
  new (model):  C23H35N7O17P3S
----------------------------------------
Updating 3hbcoa__R_c
  old: C25H38N7O18P3S
  new: C25H39N7O18P3S
  ThermoDB:       C25H39N7O18P3S
  new (model):  C25H39N7O18P3S
----------------------------------------
Updating nadp_c
  old: C21H25N7O17P3
  new: C21H26N7O17P3
  ThermoDB:       C21H26N7O17P3
  new (model):  C21H26N7O17P3
----------------------------------------
Updating aacoa_c
  old: C25H36N7O18P3S
  new: C25H37N7O18P3S
  ThermoDB:       C25H37N7O18P3S
  new (model):  C25H37N7O18P3S
----------------------------------------
Updating coa_c
  old: C21H32N7O16P3S
  new: C21H33N7O16P3S
  ThermoDB:       C21H33N7O16P3S
  new (model):  C21H33N7O16P3S
----------------------------------------
GEM formulas updated and TFA-ready.

## TFA preparation and conversion

In [22]:

palustris_model_lexicon_path = PHB_MODEL_TFA_DIR / "lexicon_auto.csv"
lexicon_palustris = read_lexicon(palustris_model_lexicon_path)

compartment_data = read_compartment_data(
    str(PHB_MODEL_TFA_DIR / "compartment_data.json")
)

mytfa_rpalustris = ThermoModel(thermo_data, cobra_model)

annotate_from_lexicon(mytfa_rpalustris, lexicon_palustris)
apply_compartment_data(mytfa_rpalustris, compartment_data)

## Prepare

In [23]:
# Prepare TFA model

mytfa_rpalustris.prepare()

Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : C17H10N4SF6/F
Warning : None/None
Warning : None/None
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : None/None
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : None/None
Warning : None/None
Warning : None/None
Warning : C17H10N4SF6/F
Warning : None/None
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : Z/Z
Warning : Z/Z
Warning : Z/Z
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C16H12NO3ClF/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C5H10O2Br2/Br
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : F6Si/F
Warning : F6Si/Si
Warning : F6Si/F
Warning : F6Si/Si
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : F/F
Warning : F/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C16H12NO3ClF/F
Warning : F6Si/F
Warning : F6Si/Si
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C5H10O2Br2/Br
Warning : C17H10N4SF6/F
Warning : H2O4Cr/Cr
Warning : H2O4Cr/Cr
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C16H12NO3ClF/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : BO3/B
Warning : BO3/B
Warning : C16H12NO3ClF/F
Warning : C16H12NO3ClF/F
Warning : C16H12NO3ClF/F
Warning : C16H12NO3ClF/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F
Warning : C17H10N4SF6/F

## Find metabolites and reactions without thermo data

In [24]:
bad_mets = []

for m in mytfa_rpalustris.metabolites:
    if hasattr(m, "thermo"):
        if m.thermo.deltaGf_tr >= 1e6:
            bad_mets.append(m)

print("Metabolites without thermo:", len(bad_mets))

Metabolites without thermo: 289

In [25]:
bad_rxns = []

for rxn in mytfa_rpalustris.reactions:
    if any(m in bad_mets for m in rxn.metabolites):
        bad_rxns.append(rxn)

print("Reactions affected:", len(bad_rxns))

Reactions affected: 527

## Turn off reactions that lack thermo data

In [26]:
for rxn in bad_rxns:
    if hasattr(rxn, "thermo"):
        rxn.thermo["computed"] = False

## Convert

In [27]:
mytfa_rpalustris.convert()#add_displacement = True)

## Coverage

In [28]:
thermo_rxns = [
    r.id for r in mytfa_rpalustris.reactions
    if hasattr(r, "thermo") and r.thermo["computed"]
]

fba_rxns = [
    r.id for r in mytfa_rpalustris.reactions
    if hasattr(r, "thermo") and not r.thermo["computed"]
]

print("Thermo reactions:", len(thermo_rxns))
print("FBA fallback reactions:", len(fba_rxns))

Thermo reactions: 1417
FBA fallback reactions: 1304

## Check that tfa was executed

In [29]:
# Check that "DG_" variables exist
len([v for v in mytfa_rpalustris.variables if "DG_" in v.name])

1419

## Check PHB functions thermo data

In [30]:
PHB_RXNS = [
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

for r in PHB_RXNS:
    rxn = mytfa_rpalustris.reactions.get_by_id(r)

    print("\nReaction:", r)

    if hasattr(rxn, "thermo"):
        print("include thermo data:", r in thermo_rxns)
        print("ΔG°:", rxn.thermo["deltaGR"])
        print("ΔG° uncertainty:", rxn.thermo["deltaGRerr"])
        print("computed:", rxn.thermo["computed"])
        print("transport:", rxn.thermo["isTrans"])
    else:
        print("No thermo data")

Reaction: PHBS_syn
include thermo data: False
ΔG°: 1000.0
ΔG° uncertainty: 1000.0
computed: False
transport: True

Reaction: ACACT1r
include thermo data: True
ΔG°: 9.06445594322821
ΔG° uncertainty: 1.087366929789572
computed: True
transport: False

Reaction: ACACCT
include thermo data: True
ΔG°: -1.540445621776371
ΔG° uncertainty: 0.5236430081649138
computed: True
transport: False

Reaction: AACOAR_syn
include thermo data: True
ΔG°: -1.9038808744587072
ΔG° uncertainty: 1.079693011925149
computed: True
transport: False

Reaction: HACD1_2
include thermo data: False
ΔG°: 1000.0
ΔG° uncertainty: 1000.0
computed: False
transport: False

Reaction: HACD1
include thermo data: True
ΔG°: -2.2909134854636477
ΔG° uncertainty: 1.079693011925149
computed: True
transport: False

Reaction: HACD1i
include thermo data: True
ΔG°: 2.2909134854636477
ΔG° uncertainty: 1.079693011925149
computed: True
transport: False

Reaction: KAT1
include thermo data: True
ΔG°: -9.06445594322821
ΔG° uncertainty: 1.087366929789572
computed: True
transport: False

## Check objective functions

In [31]:
# FBA reaction
phb_fba_rxn = cobra_model.reactions.get_by_id('PHBS_syn')
print(f"FBA bounds: {phb_fba_rxn.bounds}")
print(f"FBA reaction: {phb_fba_rxn.reaction}")

# TFA reaction
phb_tfa_rxn = mytfa_rpalustris.reactions.get_by_id('PHBS_syn')
print(f"TFA bounds: {phb_tfa_rxn.bounds}")
print(f"TFA reaction: {phb_tfa_rxn.reaction}")

FBA bounds: (0.0, 0.3978)
FBA reaction: 3hbcoa__R_c + phbg_c --> PHB_c + coa_c
TFA bounds: (0.0, 0.3978)
TFA reaction: 3hbcoa__R_c + phbg_c --> PHB_c + coa_c

## Test Run FBA and TFA

In [156]:
# Solve both models
sol_fba = cobra_model.optimize()
sol_tfa = mytfa_rpalustris.optimize()

# Compare Objective values
print(sol_fba.objective_value)
print(sol_tfa.objective_value)

DEBUG:thermomodel_None:'slim_optimize' ((), {}) 52.70 sec

0.12375000000000189
0.1237499999999816

## Compare fluxes of key reactions

In [32]:
# Compare flux of key reactions in FBA and TFA
rows = []
for r in PHB_RXNS:
    rows.append({
        "Reaction": r,
        "FBA Flux": sol_fba.fluxes[r],
        "TFA Flux": sol_tfa.fluxes[r]
    })

df = pd.DataFrame(rows)
print(df)

NameError: name 'sol_fba' is not defined

## FVA PHB reactions

In [168]:
# FVA for FBA optimization

PHB_RXNS = [
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

# run FVA
fva_fba = flux_variability_analysis(cobra_model, PHB_RXNS, fraction_of_optimum=1.0)
fva_fba

In [ ]:
# FVA for TFA optimization

fva_tfa = flux_variability_analysis(mytfa_rpalustris, PHB_RXNS, fraction_of_optimum=1.0)

DEBUG:thermomodel_None:'slim_optimize' ((), {'error_value': None, 'message': 'There is no optimal solution for the chosen objective!'}) 89.42 sec
DEBUG:thermomodel_None:'slim_optimize' ((), {}) 254.29 sec
DEBUG:thermomodel_None:'slim_optimize' ((), {}) 832.86 sec
DEBUG:thermomodel_None:'slim_optimize' ((), {}) 124.12 sec
DEBUG:thermomodel_None:'slim_optimize' ((), {}) 168.42 sec

In [ ]:
fva_tfa

## Report DG_ variables

In [161]:
dg_vars = [v for v in mytfa_rpalustris.variables if v.name.startswith("DG_")]

print("Thermodynamically constrained reactions:", len(dg_vars))
print("Total reactions:", len(mytfa_rpalustris.reactions))
print("Fraction constrained:",
      len(dg_vars) / len(mytfa_rpalustris.reactions))

Thermodynamically constrained reactions: 1417
Total reactions: 2721
Fraction constrained: 0.5207644248438075

## Report specific DG_ values

In [165]:
for v in mytfa_rpalustris.variables:
    if "DG_" in v.name:
        print(v.name, sol_tfa.raw[v.name])

BG_MADG_reverse_90e03 0.0
BG_MBDG_reverse_25438 0.0
DG_QULNS -11.623985681943154
DG_FUM -1.1092780300495884
DG_VPAMTr -1.9999771606751153
DG_NDPK7 11.037396093831456
DG_GTPCI -34.35325130501178
DG_MTHFC 8.11936439306578
DG_GCATENEC -15.185125041493105
DG_GARFT -1.0213067764095687
DG_UDPG4E -8.406275779637213
DG_ASPTA -8.830458334455077
DG_PRAGSr 10.442621478470315
DG_ACKr 11.16151367208828
DG_UDCPDPS -166.06207272656158
DG_SHKK 6.17245069682761
DG_Htex -2.0
DG_PNTK 6.146022850389787
DG_ACGK 7.004097698254102
DG_LEUabcpp -1.8732913934763804
DG_G5SD 8.961867352729051
DG_DTMPK 11.113118144182858
DG_HSTPT -1.170032945313963
DG_PGK 13.321757205510707
DG_IMPD -8.937397840648007
DG_CHRPL -51.521514024145745
DG_GCALDDy -7.51105483025265
DG_AIRC2 -18.450021263869033
DG_NNATr -3.7705856139442875
DG_HISTDb -19.549508154932504
DG_ADCL -36.00028233763307
DG_CYTK1 4.706841918765537
DG_THRS 1.0408768038922718
DG_NAMNPP -13.633111887641963
DG_PERD -2.7504535593003068
DG_DAPDC -11.116695695343676
DG_ANS -72.65440032682568
DG_SUCBZL -7.0096358324580805
DG_ADPT -14.461202935708144
DG_DHNANT -2.034666746442962
DG_GND 3.9423297759143896
DG_ACONT 0.9900107592108425
DG_HSDy 15.106604017584132
DG_GLYOX -10.400886484924094
DG_AICART -7.024605567179897
DG_SQD1 -12.740361374479054
DG_GK1 4.706842364545748
DG_PPND -39.19922728672236
DG_IPDPS_syn -22.63834957155445
DG_HISTDa -3.7251907103225816
DG_ADSL1r -0.3116989317357364
DG_H2Otu_syn 9.999996564147295e-08
DG_ALAALAr -2.093869002874115
DG_GLYCK -5.725057982499772
DG_MAN1PT -10.255312534264371
DG_CS -18.0189973307848
DG_DMATT -19.956974618365614
DG_PSP_L 9.476129164947451
DG_NDPK3 11.037395991182247
DG_G3PD2 5.798283737153248
DG_PHYTES -25.907960335715533
DG_MOHMT 3.07711953348268
DG_ACLSa -6.566032203625053
DG_ASAD -11.488282161844403
DG_PSCVT -6.38312360555913
DG_TYRTA -19.6032168224192
DG_SERAT -13.993018242761122
DG_DHFS 8.905822009549887
DG_ATPM -4.389003365008154
DG_SEPHCHCS -12.87679435395247
DG_IGPDH -4.8012009813973675
DG_OMPDC -14.348293059846242
DG_NADS2 -17.74142152288978
DG_UAMAGS 8.131250425529418
DG_FOLD3 -23.98079566193933
DG_GALUi 2.5959400525681104
DG_P5CR -11.214391567679513
DG_PQH2tum -16.896849722700722
DG_ICHORS -8.406272163550625
DG_SBP -9.963534186183075
DG_O2tu -1.4574739917573667
DG_SULabcpp 1.755231412982079
DG_PPK 9.999996564147295e-08
DG_UAPGR -27.48623521876243
DG_IPPS -14.500474863489965
DG_PPBNGS -4.7170250294586555
DG_LTHRK -7.685076752006612
DG_O2tpp 4.406275779637175
DG_NDPK2 11.02522603843803
DG_DPR -18.271595735559913
DG_H2Otex 9.999996564147295e-08
DG_PPNCL2 -15.135516570675712
DG_HPYRRy -5.45899827751818
DG_CHORS -8.625754816219949
DG_ADMDC -17.91000408598586
DG_ASP1DC -18.152606870645855
DG_MI3PP -11.45827397894673
DG_FTHFD -16.69280011865971
DG_MEPCT -10.583575557487743
DG_PDX5POi -29.515386348221817
DG_PPCDC -16.376289429777444
DG_NTD6 -11.523341982607043
DG_NNDMBRT 0.5546145927978223
DG_PRAIS 27.939870620875528
DG_GGDPR -76.1481616720605
DG_ASPCT -13.51752010513247
DG_PPNDH -43.83552328305473
DG_ME2 9.999996564147295e-08
DG_APRAUR -15.7959670288503
DG_SADT 13.280837204281468
DG_LDH_D -9.156671146460326
DG_DPCOAK 0.8873764404382909
DG_O2tex -8.81668086168429
DG_HSK -1.1320632486830235
DG_BCAROHX2 -100.31943800145537
DG_PPNCL3 -8.63337457679251
DG_AHCi 2.795641058189748
DG_PMANM -1.6717369767766295
DG_ACCOAC -3.2190418607070796
DG_CYNL -25.255233680778968
DG_METS_1 -14.083420169231161
DG_TRPS2 -10.868074548545088
DG_PRUK -1.0865543234978627
DG_GART 11.07821084088375
DG_G5SADs -16.17504683787023
DG_DMTPHT -28.749972239163004
DG_SPMDabcpp -12.250741393476387
DG_PRAMPC -0.4385250598889403
DG_G1PCTYT -3.822505234032943
DG_ASPO6 -52.6210209220857
DG_ASPK -3.8871136436455154
DG_DXPS 0.2088527092259449
DG_PRATPP -23.380117412963898
DG_NAD_H2 15.727453606398512
DG_NTPP8 -24.869093058060514
DG_ARGabcpp -5.138925087973961
DG_DAPE -2.000000000000001
DG_LYCOPC -21.591400821130073
DG_RB15BPtcx -8.406275779637213
DG_DB4PS -37.045606699897235
DG_DXPRIi -10.8536555815543
DG_GTPCII -46.48302803165956
DG_ALDD2y -9.489891053985115
DG_METAT -1.5694288015346451
DG_DHORTS -14.669707423847058
DG_PDX5PS2 -26.952118018255376
DG_GAPDi_nadp -13.783835548735343
DG_PGCD 2.82003584677679
DG_AIRC3 -11.941085056561953
DG_UMPK 4.706842364545748
DG_CBPS -15.892294005509992
DG_IPPMIb -2.3724367321367463
DG_RZ5PP -11.613825575796831
DG_GLNabcpp 3.9524354696534747
DG_NDPK8 11.037395545402001
DG_DDPA -19.143175525988198
DG_ACOTA -6.46315739716041
DG_NTD7 -5.06503456796764
DG_MTHFD -6.3907155536533296
DG_PANTS -4.8210628290190805
DG_TMPK 5.567715148651969
DG_IPMD -9.155996606236094
DG_CDPMEK 5.258249998575066
DG_CITCIa 0.5727900052671577
DG_RPE -8.406275779637213
DG_UAMAS 4.114635510444275
DG_CITCIb -0.9473039154703464
DG_BPNT2 -3.5227332272540615
DG_HSERTA -7.586742463123882
DG_NDPK1 11.037395545402058
DG_PGL -15.033156110803475
DG_MTHFR3_1 -10.27157478633136
DG_FBA3 -5.8720163808367385
DG_LDAPAT -24.35319194623526
DG_GLU5K 3.8001841431803767
DG_PGM -8.534267857860982
DG_ACS -9.999996564147295e-08
DG_AMPTASECG -4.342821023538448
DG_ATPPRT -11.108532842889677
DG_UAGCVT 0.3350750631820478
DG_HPROb -11.214340438021791
DG_NTPP2 -24.88126256502443
DG_NDPK6 11.02522603843803
DG_GLUPRT -43.84866208013228
DG_PTRCabcpp -9.372140309983747
DG_PMPK 11.061098576045959
DG_PGLYCP -10.935074781742948
DG_BCT1_syn 5.578708288627274
DG_IPDDI -6.165200402928804
DG_GLYALDDy -7.511047443751423
DG_CITMS -14.499831902103447
DG_IMPC -11.15777330590413
DG_Htcx -2.0
DG_DHQTi -3.04569647907302
DG_SPODM -31.25516715597547
DG_PGAMT -7.615569086032451
DG_PSERT -4.768407161551927
DG_HISTP 2.4270046697099916
DG_NNDPR -10.21964266266211
DG_ADSK -1.1210795027896534
DG_MECDPS 17.95566588196684
DG_GTHRDH_syn -20.473926137520607
DG_PRAIi -0.6814791252699761
DG_CYNTtabcpp -1.123369670510618
DG_PTPATi 2.350945034919123
DG_ENO -3.262464029824109
DG_PRFGS -38.39934094075305
DG_GMPS2 -32.71267856096319
DG_RBFK -0.2671286491468656
DG_GTHPi -73.77999589206323
DG_SPTc -8.406275779637259
DG_H2Otpp 9.999996564147295e-08
DG_TDPDRE 4.406275779637195
DG_GTHOr -10.17364239756251
DG_SHK3Dr -12.846472608169847
DG_ORPT 0.6461185455336071
DG_GRTT -13.550698838728351
DG_PPA -4.178639978121435
DG_DHQS -19.565629603686816
DG_ANPRT -16.04791565710514
DG_ADK1 11.24209591606458
DG_NDPK5 -9.999996564147295e-08
DG_NDPK4 4.618950258800835
DG_NADK -4.521628977875119
DG_NO3abcpp -1.123369670510618
DG_FE3abcpp -16.508100114530144
DG_NADTRHD -14.42551894826952
DG_G1SAT -8.139702917686918
DG_ILETA -19.60324908356631
DG_ATPSum -9.999996564147295e-08
DG_BCAROHX -110.65806641071194
DG_GLYCLTDx -7.296313643303883
DG_PIuabcpp 14.550789325223054
DG_ADSS -17.236772898257936
DG_THRPDC -17.26948505195662
DG_TMDS3 -29.7069256915172
DG_DHFR -0.10566736903316354
DG_ACGS -5.639528225825286
DG_AFAT -12.027335609106126
DG_GLYOX_1 0.38163249397127075
DG_FRTT -19.95697461836549
DG_CTPS2 -17.46810711640926
DG_CO2tex -8.81668086168429
DG_GTHS 10.047582198397478
DG_DADK -1.6994334150914905
DG_ERTHMMOR -12.696144998801877
DG_PDH -13.732880520968848
DG_TPI 1.1593110577357768
DG_PRMICI -1.3007931421466497
DG_CAT -45.08055874561603
DG_GLUR -2.000000000000001
DG_ALAR -2.000000000000001
DG_ADCS -30.83134984976118
DG_ICDHyr 6.52211051571717
DG_SPMS -20.314448023404218
DG_PEPC -9.29845535929286
DG_PHETA1 -19.6032376521664
DG_CHORM -17.836916119463737
DG_GAPD -1.0317202193342414
DG_PQH2tcm -8.406275779637213
DG_URIDK2r -1.6994334150914194
DG_E4PD -26.9442890447603
DG_IPPMIa -7.248441819767095
DG_PYK -15.600244381216163
DG_2PGLYCtcx -2.000000000000001
DG_IG3PS -47.74870627446383
DG_FMNRy_1 -16.215153561000594
DG_GHMT2r -8.179069513028502
DG_BPNT -10.015565821185342
DG_FE3tex -8.81668086168429
DG_FE2tex -2.410405082047115
DG_SPMDtex -8.81668086168429
DG_LEUtex -8.81668086168429
DG_HCO3tex -8.81668086168429
DG_GLNtex -8.81668086168429
DG_CYNTtex -8.81668086168429
DG_ARGtex -8.81668086168429
DG_SO4tex -8.81668086168429
DG_NO3tex -8.81668086168429
DG_CO2tpp -2.0000000000000204
DG_PItex -8.81668086168429
DG_MDRPD -8.86035260870643
DG_ENOPH -4.208576022194023
DG_ARD -139.42940346624357
DG_UNK3 9.196960482255992
DG_TRNFE -44.02554160352045
DG_SPR -27.653715526226293
DG_GLYCOX1 -55.67558672283586
DG_AMAOTr -13.972811410932149
DG_DBTS 4.091309636872724
DG_BTS6 -49.49174729847027
DG_BACCL 23.116613281394145
DG_MEOHtrpp -1.225934777990246
DG_MEOHtex -8.81668086168429
DG_ADNK1 0.4212218379238415
DG_UDPGD -24.34904262523932
DG_UDPGLDC -14.628432389475051
DG_GMAND -14.578919232754114
DG_GFUCS -7.9645389942288425
DG_CDPGLC46DH -14.578919232754227
DG_ALDDC17 -142.135093991163
DG_PAPA160 -11.523341982607185
DG_PAPA161 -11.523341982607072
DG_ZXANHX -100.31943800145548
DG_CXANHX -100.31943800145534
DG_A5PISO -5.246964721901463
DG_KDOPS -12.935188259930074
DG_KDOPP -4.356791824484215
DG_KDOCT2 -7.4883824764670095
DG_UAG2E -8.406275779637213
DG_ICLIPAabcpp -72.03243585849395
DG_MDDEP1pp -1.3792520051525727
DG_MDDEP2pp 2.901560735841862
DG_MDDEP3pp -16.19804611576592
DG_MDDEP4pp -1.3113148762985745
DG_MLTGY1pp -16.166524181737355
DG_MLTGY2pp -7.548946792216935
DG_MLTGY3pp 5.894120015736737
DG_MLTGY4pp -29.03549538919152
DG_UM4PL 14.726684949509847
DG_ALAGLUE 3.617315424100866
DG_AGM4Pt2pp 9.191842893906845
DG_4PEPTabcpp -1.7241562850744792
DG_ALAALAabcpp -3.1354243992027744
DG_NO2tabcpp -7.529542113676786
DG_Htabcpp -12.67063953734501
DG_FALDH2 12.080140985667885
DG_SFGTHi -8.80444053765374
DG_GGCLUT2 -18.13039986158242
DG_OPAH -7.63844265263231
DG_ANHMK 18.38562622875806
DG_ASPO5 -35.91209954097955
DG_PCXHtpp 2.1408180861684514
DG_34DHOXPEGOX -4.818989778994069
DG_AACOAR_syn -9.38984966602105
DG_ABTA -1.7063239440670053
DG_ABUTD -30.3922550204627
DG_ACACT1r -9.999996564147295e-08
DG_ACP1_FMN -4.376684080896876
DG_AGTi -8.166964721901348
DG_AIRCr 0.9718967917861425
DG_ALAabcpp -9.440665006128238
DG_ALCD19 -4.820741901612699
DG_ALCD2y 9.067598932643232
DG_ALDD20x -19.936985938470507
DG_ALDD2x -21.91541000225464
DG_AOXSr -13.534333357192592
DG_ATPSu -0.6816681861683378
DG_BCAROKE -104.95426481532854
DG_CYSTA -11.959626434965458
DG_DASYN160 -4.17729977785049
DG_DASYN161 -10.583575557487686
DG_DASYN180 -5.9757257176912875
DG_DASYN181 -12.382001497328483
DG_DHORDi -34.5688766661187
DG_FBA2 -6.507550591127558
DG_FMNAT -12.027335609106126
DG_FOMETRi -14.082401310537193
DG_G1PTT -3.810335727069085
DG_G3PD -1.0609848326624949
DG_G3PD1ir 4.467849187265976
DG_G6PBDH 7.347222379079015
DG_GCALDD -19.9365737785222
DG_GLBRAN2 -2.000000000000001
DG_GLCGLYCabcpp_syn -7.311985645601368
DG_GLUCYS 4.0159552809881
DG_GLUK_syn 0.4732534729261628
DG_GLUSx -29.565370765374542
DG_GLUt2rpp -2.7817801567349285
DG_GLXCL -22.980550984329057
DG_GLYALDDr -19.936566392020943
DG_GLYCTO1 -18.387570401423087
DG_GLYK 0.4732534729261353
DG_GLYabcpp -3.421421837495945
DG_GUACYC -15.224211129539423
DG_H2ASE_syn 0.9832695249111758
DG_HCO3E 5.32483702424679
DG_HISabcpp -2.647356615486162
DG_HPROa 1.2111785102477572
DG_HPYRRx 6.9665206707513425
DG_HSDxi -4.820741901612699
DG_IMACTD -26.34284955815932
DG_LALDO -11.088739294061442
DG_LGTHL -2.628805829519732
DG_LYSDC -11.503728306348588
DG_LYSabcpp -5.138925087973961
DG_MAN1PT2 3.5096683721233397
DG_MDH -9.999996564147295e-08
DG_MECDPDH_syn -50.21054519895847
DG_METS -14.083420169231161
DG_MI1PP -11.45827397894673
DG_MTHFD2i -18.81623450192285
DG_NABTNO -26.343117555792023
DG_NDPK10 4.468148552862414
DG_NDPK9 14.87442433249953
DG_NPHS -27.542145655769218
DG_NTD4 -5.117066202969784
DG_NTPP4 -24.881262565024464
DG_OPHBDC -7.859601532501465
DG_P5CD -16.887758848690737
DG_P5CRx 1.2111273805900087
DG_PGSA160 -6.908397358819755
DG_PGSA161 -0.5021215791825604
DG_PGSA180 -40.11440075455417
DG_PGSA181 -29.86410381080787
DG_PHYTES2 -20.415428993606486
DG_PPC -4.962061438305136
DG_PPNCL -7.6854519116503734
DG_PROD2 2.6392096758734898
DG_PROabcpp 0.42476077350883923
DG_PUTA3 -31.520552001926177
DG_PYDXNO -29.15519578107466
DG_PYK2 -2.5750183427781614
DG_PYK3 -2.5628488358141595
DG_PYK4 -2.5628483900339134
DG_PYK5 -2.7258200487165762
DG_RBCh -132.35970955090144
DG_RBPC -15.270380503421311
DG_SDPTA -14.79898087043955
DG_SERabcpp -3.0343892264910455
DG_SPT_syn -14.573240501538635
DG_SQLC -138.63596667812544
DG_SQLC2 -146.3318244709942
DG_SSALy -14.30640833085672
DG_SUCOAS 13.376559572703957
DG_SUCRabcpp_syn 6.274631135682769
DG_TDPDRR -14.370814773866073
DG_TDPGDH -14.57891923275417
DG_THFGLUS 2.1120049397349066
DG_THZPSN -68.8471750441886
DG_TRSARr 10.131451546740664
DG_UHGADA -16.79368642734935
DG_14GLUCANabcpp -8.473083478616033
DG_2DGLCptspp -10.775492261471673
DG_2DGULRGx 0.5602466015104532
DG_2DGULRGy -11.86527234675907
DG_2DGULRx 0.5602466015104532
DG_2DGULRy -11.86527234675907
DG_2DOXG6PP -5.117066202969875
DG_3HPADHi -26.34297094120723
DG_3NTD2pp -17.599926531034612
DG_3NTD4pp -17.599926531034612
DG_3NTD7pp -17.599926531034612
DG_3NTD9pp -17.599926531034498
DG_3OXCOAT -5.349241015057014
DG_3PEPTabcpp 2.2593844323661907
DG_4HTHRA -12.40592005188023
DG_4PCPpp -19.947248757575153
DG_5DGLCNR -9.38985665059856
DG_5DKGR -5.195048321521226
DG_ACACCT -6.473157882204227
DG_ACACT2r 3.1745071689929603
DG_ACACT3r -3.2317686106442913
DG_ACACT4r 3.1745071689928466
DG_ACACT5r 3.1745071689929603
DG_ACACT6r 5.7932008625398925
DG_ACACT7r 3.1745071689931024
DG_ACACT8r -11.75551680820929
DG_ACALD 9.999996564147295e-08
DG_ACCOAL 8.126295955003345
DG_ACMUMptspp -4.33540913681603
DG_ACOLIPAabctex -13.521951489319072
DG_ACONMT -19.204148896020683
DG_ACONTa 0.5804269078977375
DG_ACONTb -0.9489583288335872
DG_ACOXT -17.00028840025513
DG_ACP1p -17.653651321453594
DG_ACt2rpp -1.8983502810117212
DG_ADK3 -1.7952996293373644
DG_ADK4 9.999996564147295e-08
DG_AGM3PA -38.027388564316354
DG_AGM3PApp -32.20551487933183
DG_AGM3Pt2pp 11.522213758014537
DG_AGM4PA -15.76787219488524
DG_AGM4PApp -8.292828656567877
DG_AGM4PCPpp 3.9654374651888133
DG_AGMt2pp -0.5610151133393595
DG_AGPR -3.357353822198231
DG_AHGDx -2.750418373809186
DG_AKGDH -19.693098847770237
DG_AKGt2rpp 7.184158870577228
DG_ALATA_L -13.196941042781983
DG_ALATA_L2 -12.145539199462906
DG_ALCD2x -3.3579200156263154
DG_ALDD3y -13.917845231777004
DG_ALKP -3.6848862979522856
DG_ALLPI -5.241462818607033
DG_ALLabcpp -8.473083478616035
DG_ALR2 -13.315523799351439
DG_ALR2x -0.890004851081919
DG_AM3PA -33.434620357523045
DG_AM4PA -27.929724295462847
DG_AMALT1 -8.40627577963729
DG_AMALT2 4.406275779637234
DG_AMALT3 -1.9999999999999822
DG_AMALT4 -18.63009155842957
DG_AMMQLT8 -64.6018004074519
DG_AMPMS2 -78.7127859012146
DG_AMPTASEPG -3.5228295813669934
DG_ARBTNabcpp 4.22656218741331
DG_ARBabcpp -2.4538403099836312
DG_ARGDC -11.503728306348588
DG_ARHGDx -2.750418373809186
DG_ASCBptspp 3.2653225300253528
DG_ASPO4 -59.98746359953384
DG_ASPabcpp -1.4110790347867717
DG_ATHRDHr 0.824187862533627
DG_BETALDHx -25.95578393456967
DG_BETALDHy -13.53026498630015
DG_BUTCT -0.06619270558407386
DG_BUTSO3abcpp 0.6182770790113947
DG_CFAS160E -38.11568621500725
DG_CFAS160G -60.85051949787294
DG_CFAS180E -44.521961994644506
DG_CFAS180G -51.51451863289503
DG_CGLYabcpp -3.5224787377655478
DG_CHLabcpp -5.3324413934763815
DG_CHLt3pp -5.197380057700203
DG_CHOLD 2.681085069314584
DG_CINNDO -71.02377507118845
DG_CITL -2.913619489635677
DG_CLIPAabctex -7.115675709681881
DG_COLIPAabcpp -84.9365359642759
DG_COLIPAabctex -7.115675709681881
DG_CRNCAL2 14.035084032244448
DG_CRNCAR -10.063252468372525
DG_CRNCDH 3.765254060030202
DG_CRNDCAL2 5.971831563871946
DG_CRNDabcpp -8.960451999338218
DG_CRNDt2rpp -10.71226672049852
DG_CRNabcpp -8.960451999338218
DG_CRNt2rpp -10.71226672049852
DG_CTBTabcpp -11.351684562108694
DG_CTBTt2rpp -13.103499283269002
DG_CTECOAI6 -8.19627577963729
DG_CTECOAI7 -26.793031626089792
DG_CTECOAI8 -8.406275779637213
DG_CYSabc2pp -4.463722109154579
DG_CYSabcpp -4.314284620861725
DG_CYTBD2pp -10.593032072495362
DG_CYTK2 -1.6994339635209026
DG_DAGK120 0.47325347292607667
DG_DAGK140 0.47325347292604825
DG_DAGK141 0.4732534729262188
DG_DAGK160 6.879529252563414
DG_DAGK161 6.879529252563301
DG_DAGK180 2.271679412766902
DG_DAGK181 2.271679412766902
DG_DASYN120 -10.583575557487515
DG_DASYN140 -10.583575557487743
DG_DASYN141 -10.583575557487686
DG_DGK1 4.706842056141098
DG_DHAPT -16.303609086902547
DG_DHBS -7.046941139129952
DG_DHORD5 -42.12430524509978
DG_DHPPD -26.961191914090016
DG_DHPS2 -23.98079566193933
DG_DKGLCNR1 -15.79612544565839
DG_DKGLCNR2x -5.846022193549263
DG_DKGLCNR2y -18.271541141818812
DG_DMPPS -15.902442259057539
DG_DMQMT -3.6984653390653826
DG_DOXRBCNtpp -15.27376621047938
DG_DSERDHr 2.2940524583097286
DG_DURADx -10.604788575837347
DG_DUTPDP -18.462817278423262
DG_E4PP -12.469105701898068
DG_ECA4COLIPAabctex -13.521951489319072
DG_ECOAH2 1.3956344808372636
DG_ECOAH4 1.3956344808373133
DG_ECOAH5 1.3956344808371712
DG_ECOAH7 1.3956344808372778
DG_EDD -8.847149892884739
DG_ENLIPAabctex -13.521951489319072
DG_ETHSO3abcpp -0.15578814299839383
DG_F1PP -11.497355779091414
DG_FACOAE100 -20.625027299945465
DG_FACOAE120 -14.218751520308272
DG_FACOAE140 -20.625027299945472
DG_FACOAE141 -21.35477803033439
DG_FACOAE160 -14.218751520308345
DG_FACOAE161 -39.22091543886363
DG_FACOAE180 -14.21875152030846
DG_FACOAE60 -20.62535702867433
DG_FACOAE80 -20.625666681059883
DG_FACOAL100t2pp 10.588077233361982
DG_FACOAL120t2pp 14.08881480004547
DG_FACOAL140t2pp 23.995828146366083
DG_FACOAL141t2pp 22.830911658983876
DG_FACOAL160t2pp 14.684014153775289
DG_FACOAL161t2pp 37.93142337126998
DG_FACOAL180t2pp 18.184751720458898
DG_FACOAL60t2pp 3.5885883214101213
DG_FACOAL80t2pp 7.091186128774748
DG_FADRx2 -8.211323380409201
DG_FDH5pp -33.57984138667804
DG_FDMO -96.24825950737454
DG_FDMO2 -91.82933000245703
DG_FDMO3 -95.65207463915067
DG_FDMO4 -96.24725950737457
DG_FDMO6 -87.00270237661991
DG_FE2abcpp -18.48764436665513
DG_FE2t2pp -20.239459087815362
DG_FEROpp -28.6067545242446
DG_FHL 3.818968640278243
DG_FLVR -23.135404402855173
DG_FMNRx2 -16.215153561000594
DG_FORCT -9.881951385876576
DG_FORt2pp -2.6807479842952553
DG_FORtppi -5.460070101873175
DG_FRD2 19.751738436481535
DG_FRD3 9.080789868567628
DG_FRUptspp 2.0110730942870596
DG_FUSAtpp -15.27376621047938
DG_G1PP -4.762271659152415
DG_G1PPpp -10.98081210705971
DG_G2PP -11.471314533358914
DG_G2PPpp -11.202556276416038
DG_G3PCabcpp -0.518677254959309
DG_G3PEabcpp -1.6797750879739386
DG_G3PGabcpp 1.5858586065235576
DG_G3PIabcpp 2.359923828533363
DG_G3PSabcpp 1.3923423010210971
DG_G3PT -5.117066202969877
DG_GALCTLO -13.972941622417466
DG_GALT1 61.34845893208995
DG_GALTptspp 3.787428081144437
DG_GALabcpp -2.0668076989788826
DG_GDPDPK -9.487478366941938
DG_GDPMNH -15.400959948461605
DG_GDPTPDP -3.871706957623018
DG_GGGABADr -18.958723875932034
DG_GHBDHx -4.820878770120107
DG_GLCATr -7.5867424631239135
DG_GLCRAL -7.335850605126755
DG_GLCTR1 -29.79064455214575
DG_GLCabcpp -2.0668076989788364
DG_GLDBRAN2 -2.0
DG_GLTPD -13.972925821371405
DG_GLUSy -41.99088971364381
DG_GLUabcpp -1.0299654355746526
DG_GLYAT 1.359219148672416
DG_GLYBabcpp -2.2603240044812782
DG_GLYBt2pp -4.012138725641556
DG_GLYBt3pp -8.269497446695304
DG_GLYC2Pabcpp 5.603195415180572
DG_GLYC3Pabcpp -0.7859566221435923
DG_GLYCLTDy -19.721832591573403
DG_GLYCTO3 -26.36817292814966
DG_GLYCTO4 -15.34494118464158
DG_GNK -0.16777249079158896
DG_GNP -4.476040239252153
DG_GTHRDHpp -19.798526353348734
DG_GTHRDabc2pp -8.902933094851294
DG_GTHRDabcpp 0.12492636483498654
DG_GTPDPDP -12.172073682690666
DG_GTPDPK -14.74180359466131
DG_GUAPRT -14.409171300705939
DG_HACD1 3.0356692822484668
DG_HACD2 -3.370606497388838
DG_HACD4 -3.370606497388838
DG_HACD5 -3.370606497388838
DG_HACD7 -3.370606497388952
DG_HADPCOADH3 -5.195055275031394
DG_HEPT1 19.40418323796162
DG_HEPT2 7.030447265715051
DG_HISTD -23.18793874859054
DG_HKNDDH -21.90017613586713
DG_HKNTDH -28.304491062799116
DG_HMPK1 -5.816830517088572
DG_HOMt2pp -7.882464835690421
DG_HPPPNDO -74.03892512657643
DG_HPYRI -1.352009035133312
DG_HPYRP -10.895494819023675
DG_HXAND -14.491601300616352
DG_HXCT -0.06578667899923296
DG_HXPRT -8.094257821478848
DG_HYD2pp -38.905053179496235
DG_HYD3pp -27.884305167875937
DG_ICL 3.597053901688561
DG_ILEabcpp 4.532984386160767

# * TORUN: R palustris model multiple PHB syn values

In [ ]:
# ============================================================
# USER PARAMETERS
# ============================================================

import logging
import pandas as pd
import numpy as np
from cobra.flux_analysis import pfba

logging.getLogger("thermomodel_None").setLevel(logging.ERROR)
logging.getLogger("pytfa").setLevel(logging.ERROR)

PHB_SYN_UB_VALUES = [0.3978, 1000]  # 0.3978,
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

SUB_TO_RXN_BASE = {
    "ace": "EX_ac_e",
    "lac": "EX_lac__L_e",
    "ppa": "EX_ppa_e",
    "but": "EX_but_e",
    "ibt": "EX_ibt_e",
    "mal": "EX_mal__L_e",
    "hxa": "EX_hxa_e",
    "oct": "EX_octa_e",
    "nh4": "EX_nh4_e",
    "hco3": "EX_hco3_e",
}

EXCHANGE_RXNS = list(SUB_TO_RXN_BASE.values())

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True

# Apply solver settings once to original models
apply_solver_settings(cobra_model)
apply_solver_settings(mytfa_rpalustris)


# ============================================================
# MAIN LOOP OVER PHB SYNTHESIS UB VALUES
# ============================================================
for PHB_SYN_UB in PHB_SYN_UB_VALUES:

    print("\n==============================")
    print(f"PHB_SYN_UB_VALUE: {PHB_SYN_UB}")
    print("==============================")

    PHB_SYN_TAG = f"{PHB_SYN_UB:g}"

    INPUT_CSV = PHB_PARETO_DIR / f"04_pareto_best_all_strategies_{PHB_SYN_TAG}.csv"
    OUT_CSV = PHB_TFA_DIR / f"05_FBA_TFA_PFBA_detailed_results_all_strategies_checked_{PHB_SYN_TAG}.csv"


    # Keep ONLY SUP_and_CON

    df = df[df["optimization_strategy"] == "SUP_and_CON"].copy()

    results = []

    for pareto_id, row in df.iterrows():

        strategy = row["optimization_strategy"]
        suffix = "_sup"

    #df = pd.read_csv(INPUT_CSV)
    #results = []

    #for pareto_id, row in df.iterrows():

        #strategy = row["optimization_strategy"]

        #if "SUP_and_CON" in strategy:
        #    suffix = "_sup"
        #elif strategy == "CON":
        #    suffix = "_con"
        #elif strategy == "SUP":
        #    suffix = "_sup"
        #elif strategy == "PFBA":
        #    suffix = "_con_pfba"
        #elif strategy == "SUP_and_PFBA":
        #    suffix = "_sup"
        #else:
        #    print(f'Other optimization strategy: {strategy}')
        #    suffix = ""

        # -----------------------------
        # COPY COBRA MODEL (FBA/pFBA)
        # -----------------------------
        m = cobra_model.copy()

        #tfa_model = mytfa_rpalustris.copy()

        # -----------------------------
        # UPDATE EXCHANGE BOUNDS
        # -----------------------------
        input_values_used = {}
        for base_col, rxn_id in SUB_TO_RXN_BASE.items():
            col_name = f"{base_col}{suffix}"
            val_used = np.nan

            if col_name in row:
                val = row[col_name]
                if pd.notna(val) and float(val) != 0.0 and rxn_id in m.reactions:
                    rxn = m.reactions.get_by_id(rxn_id)
                    rxn.lower_bound = -abs(float(val))
                    rxn.upper_bound = 0.0
                    val_used = float(val)

            input_values_used[f"{base_col}_supplied"] = 0.0 if pd.isna(val_used) else val_used

            # Also update TFA bounds
            if rxn_id in mytfa_rpalustris.reactions:
                rxn_tfa = mytfa_rpalustris.reactions.get_by_id(rxn_id)
                rxn_tfa.lower_bound = -abs(val_used) if pd.notna(val_used) else rxn_tfa.lower_bound
                rxn_tfa.upper_bound = 0.0


        # -----------------------------
        # OBJECTIVE & NO GROWTH
        # -----------------------------
        phb_rxn = m.reactions.get_by_id("PHBS_syn")
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = PHB_SYN_UB
        m.objective = phb_rxn

        biomass = m.reactions.get_by_id("BIOMASS__1")
        biomass.lower_bound = 0.0
        biomass.upper_bound = 0.0

        # Update TFA objective and PHB bounds
        phb_tfa = mytfa_rpalustris.reactions.get_by_id("PHBS_syn")
        phb_tfa.lower_bound = 0.0
        phb_tfa.upper_bound = PHB_SYN_UB
        mytfa_rpalustris.objective = phb_tfa

        biomass_tfa = mytfa_rpalustris.reactions.get_by_id("BIOMASS__1")
        biomass_tfa.lower_bound = 0.0
        biomass_tfa.upper_bound = 0.0

        # -----------------------------
        # FBA
        # -----------------------------
        fba_sol = m.optimize()

        # -----------------------------
        # pFBA
        # -----------------------------
        pfba_sol = pfba(m)

        # -----------------------------
        # TFA
        # -----------------------------
        try:
            tfa_sol = mytfa_rpalustris.optimize()
        except Exception as e:
            print(f"TFA optimization failed for Pareto solution {pareto_id}: {e}")
            tfa_sol = None

        # -----------------------------
        # COLLECT RESULTS
        # -----------------------------
        result = {
            "PHB_SYN_UB": PHB_SYN_UB,
            "PHB_SYN_TAG": PHB_SYN_TAG,
            "pareto_id": pareto_id,
            "PHB_pFBA": pfba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan),
            "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan),
            "Biomass_pFBA": pfba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_pFBA": pfba_sol.status,
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
            "optimization_strategy": strategy
        }

        # PHB reactions
        for r in PHB_REACTIONS:
            result[f"{r}_pFBA"] = pfba_sol.fluxes.get(r, np.nan)
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

        # Exchange reactions
        for base_col, rxn_id in SUB_TO_RXN_BASE.items():
            result[f"{base_col}_pFBA"] = pfba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_FBA"]  = fba_sol.fluxes.get(rxn_id, np.nan)
            result[f"{base_col}_TFA"]  = tfa_sol.fluxes.get(rxn_id, np.nan)

        result.update(input_values_used)
        print(pd.Series(result))
        print("-" * 60)
        results.append(result)

    # Save results
    pd.DataFrame(results).to_csv(OUT_CSV, index=False)
    print(f"\nDONE — Results saved to:\n{OUT_CSV}")

==============================
PHB_SYN_UB_VALUE: 0.3978
==============================
PHB_SYN_UB         0.3978
PHB_SYN_TAG        0.3978
pareto_id               2
PHB_pFBA           0.3978
PHB_FBA            0.3978
                   ...
mal_supplied    -0.238157
hxa_supplied          0.0
oct_supplied       -0.112
nh4_supplied          0.0
hco3_supplied         0.0
Length: 74, dtype: object
------------------------------------------------------------

DONE — Results saved to:
/content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/results/phb/tfa/05_FBA_TFA_PFBA_detailed_results_all_strategies_checked_0.3978.csv

==============================
PHB_SYN_UB_VALUE: 1000
==============================

# Main E. coli tutorial

In [ ]:
!pip install sympy==1.10.1

Collecting sympy==1.10.1
  Using cached sympy-1.10.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.12/dist-packages (from sympy==1.10.1) (1.3.0)
Using cached sympy-1.10.1-py3-none-any.whl (6.4 MB)
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
modelseedpy 0.4.2 requires sympy>=1.12.0, but you have sympy 1.10.1 which is incompatible.
optlang 1.8.3 requires sympy>=1.12.0, but you have sympy 1.10.1 which is incompatible.
torch 2.10.0+cpu requires sympy>=1.13.3, but you have sympy 1.10.1 which is incompatible.
Successfully installed sympy-1.10.1

In [ ]:
from pytfa.io import import_matlab_model, load_thermoDB,                    \
                            read_lexicon, annotate_from_lexicon,            \
                            read_compartment_data, apply_compartment_data

case = 'full' # 'reduced' or full'

# Load reaction DB
print("Loading thermo data...")

#thermo_data = load_thermoDB('/Users/hector/git/pytfa/data/thermo_data.thermodb')


thermo_data['metabolites'] = {
    str(k): v
    for k, v in thermo_data['metabolites'].items()
}

print("Done !")

if case == 'reduced':
    cobra_model = import_matlab_model(str(ec_model_mat_path))
    mytfa = pytfa.ThermoModel(thermo_data, cobra_model)
    biomass_rxn = 'Ec_biomass_iJO1366_WT_53p95M'
elif case == 'full':
    # We import pre-compiled data as it is faster for bigger models
    cobra_model = load_json_model(ec_model_json_path)

    lexicon = read_lexicon(ec_model_lexicon_path)
    compartment_data = read_compartment_data(str(ec_model_comp_path))

    # Initialize the cobra_model
    mytfa = pytfa.ThermoModel(thermo_data, cobra_model)

    # Annotate the cobra_model
    annotate_from_lexicon(mytfa, lexicon)
    apply_compartment_data(mytfa, compartment_data)

    biomass_rxn = 'Ec_biomass_iJO1366_WT_53p95M'

mytfa.name = 'tutorial_basics'
mytfa.solver = "glpk"
mytfa.objective = biomass_rxn

# Solver settings

def apply_solver_settings(model, solver = "glpk"):
    model.solver = "glpk"
    # model.solver.configuration.verbosity = 1
    model.solver.configuration.tolerances.feasibility = 1e-9
    if solver == 'optlang_gurobi':
        model.solver.problem.Params.NumericFocus = 3
    model.solver.configuration.presolve = True

apply_solver_settings(mytfa)


## FBA
fba_solution = cobra_model.optimize()
fba_value = fba_solution.objective_value
# fva = flux_variability_analysis(mytfa)

## TFA conversion
mytfa.prepare()
mytfa.convert()#add_displacement = True)

## Info on the cobra_model
mytfa.summary()

## Optimality
tfa_solution = mytfa.optimize()
tfa_value = tfa_solution.objective_value

# It might happen that the model is infeasible. In this case, we can relax
# thermodynamics constraints:

#if tfa_value < 0.1:
#    from pytfa.optim.relaxation import relax_dgo

#    mytfa.reactions.get_by_id(biomass_rxn).lower_bound = 0.5*fba_value
#    relaxed_model, slack_model, relax_table = relax_dgo(mytfa)

 #   original_model, mytfa = mytfa, relaxed_model

 #   print('Relaxation: ')
 #   print(relax_table)

  #  tfa_solution = mytfa.optimize()
  #  tfa_value = tfa_solution.objective_value

# Report
print('FBA Solution found : {0:.5g}'.format(fba_value))
print('TFA Solution found : {0:.5g}'.format(tfa_value))


solver_results = dict()

In [ ]:
# It might happen that the model is infeasible. In this case, we can relax
# thermodynamics constraints:

if tfa_value < 0.1:
    from pytfa.optim.relaxation import relax_dgo

    mytfa.reactions.get_by_id(biomass_rxn).lower_bound = 0.5*fba_value
    relaxed_model, slack_model, relax_table = relax_dgo(mytfa)

    original_model, mytfa = mytfa, relaxed_model

    print('Relaxation: ')
    print(relax_table)

    tfa_solution = mytfa.optimize()
    tfa_value = tfa_solution.objective_value

# Report
print('FBA Solution found : {0:.5g}'.format(fba_value))
print('TFA Solution found : {0:.5g}'.format(tfa_value))


solver_results = dict()

In [ ]:
mytfa.compartments

In [ ]:
print(f"TBA:{tfa_value}")
print(f"FBA:{fba_value}")

TBA:0.8109971377524022
FBA:0.8109621653343299

# Check TFA E.coli tutorial

In [ ]:
for v in mytfa.variables.values():
  print(v)

In [ ]:
len([v.name for v in mytfa.variables if v.name.startswith("DGo_")])

416

In [ ]:
[c.name for c in mytfa.constraints if c.name.startswith("G_")][:10]

['G_5MTRtex',
 'G_ACALD',
 'G_ACALDtex',
 'G_ACALDtpp',
 'G_ACKr',
 'G_ACONTa',
 'G_ACONTb',
 'G_ACS',
 'G_ACSERtex',
 'G_ACt2rpp']

In [ ]:
[c.name for c in mytfa.constraints if "DG_" in str(c.expression)][:10]

['G_5MTRtex',
 'FU_5MTRtex',
 'BU_5MTRtex',
 'G_ACALD',
 'FU_ACALD',
 'BU_ACALD',
 'G_ACALDtex',
 'FU_ACALDtex',
 'BU_ACALDtex',
 'G_ACALDtpp']

In [ ]:
[c.name for c in mytfa.constraints if c.name.startswith(("FU_", "BU_", "SU_", "UF_"))][:10]

['SU_DM_4CRSOL',
 'UF_DM_4CRSOL',
 'SU_DM_5DRIB',
 'UF_DM_5DRIB',
 'SU_DM_AMOB',
 'UF_DM_AMOB',
 'SU_DM_MTHTHF',
 'UF_DM_MTHTHF',
 'SU_Ec_biomass_iJO1366_WT_53p95M',
 'UF_Ec_biomass_iJO1366_WT_53p95M']

In [ ]:
assert any(c.name.startswith("G_") for c in mytfa.constraints)
assert any(v.name.startswith("DGo_") for v in mytfa.variables)
assert any(v.type == "binary" for v in mytfa.variables)
print("✅ TFBA is active")

✅ TFBA is active

In [ ]:
for c in mytfa.constraints:
  print(c)

10fthf_c: 0.0 <= -0.000223*Ec_biomass_iJO1366_WT_53p95M + 0.000223*Ec_biomass_iJO1366_WT_53p95M_reverse_55db7 + 1.0*LMPD_1_10fthf_c - 1.0*LMPD_1_10fthf_c_reverse_e2a7c + 1.0*LMPD_2_10fthf_c - 1.0*LMPD_2_10fthf_c_reverse_0c02d + 1.0*LMPD_3_10fthf_c - 1.0*LMPD_3_10fthf_c_reverse_4cbc5 + 1.0*LMPD_4_10fthf_c - 1.0*LMPD_4_10fthf_c_reverse_ebfa8 <= 0.0
13dpg_c: 0.0 <= 1.0*GAPD - 1.0*GAPD_reverse_459c1 + 1.0*PGK - 1.0*PGK_reverse_02696 <= 0.0
2ddg6p_c: 0.0 <= -1.0*EDA + 1.0*EDA_reverse_81f1b + 1.0*EDD - 1.0*EDD_reverse_007a2 <= 0.0
2dmmq8_c: 0.0 <= 1.0*FRD3 - 1.0*FRD3_reverse_78134 - 1.0*G3PD7 + 1.0*G3PD7_reverse_74364 - 1.0*GLYCTO4 + 1.0*GLYCTO4_reverse_9c086 - 1.0*NADH18pp + 1.0*NADH18pp_reverse_8cf33 - 1.0*NADH9 + 1.0*NADH9_reverse_91511 - 1.0*NADPHQR4 + 1.0*NADPHQR4_reverse_ebd03 <= 0.0
2dmmql8_c: 0.0 <= -0.000223*Ec_biomass_iJO1366_WT_53p95M + 0.000223*Ec_biomass_iJO1366_WT_53p95M_reverse_55db7 - 1.0*FRD3 + 1.0*FRD3_reverse_78134 + 1.0*G3PD7 - 1.0*G3PD7_reverse_74364 + 1.0*GLYCTO4 - 1.0*GLYCTO4_reverse_9c086 + 1.0*LMPD_5_2dmmql8_c - 1.0*LMPD_5_2dmmql8_c_reverse_433d3 + 1.0*NADH18pp - 1.0*NADH18pp_reverse_8cf33 + 1.0*NADH9 - 1.0*NADH9_reverse_91511 + 1.0*NADPHQR4 - 1.0*NADPHQR4_reverse_ebd03 <= 0.0
2fe2s_c: 0.0 <= -2.5e-5*Ec_biomass_iJO1366_WT_53p95M + 2.5e-5*Ec_biomass_iJO1366_WT_53p95M_reverse_55db7 + 1.0*LMPD_10_2fe2s_c - 1.0*LMPD_10_2fe2s_c_reverse_f6cf8 + 1.0*LMPD_11_2fe2s_c - 1.0*LMPD_11_2fe2s_c_reverse_31d62 + 1.0*LMPD_12_2fe2s_c - 1.0*LMPD_12_2fe2s_c_reverse_c9941 + 1.0*LMPD_130_lipopb_c - 1.0*LMPD_130_lipopb_c_reverse_15570 + 1.0*LMPD_131_lipopb_c - 1.0*LMPD_131_lipopb_c_reverse_0e862 + 1.0*LMPD_132_lipopb_c - 1.0*LMPD_132_lipopb_c_reverse_aea25 + 1.0*LMPD_133_lipopb_c - 1.0*LMPD_133_lipopb_c_reverse_fccb7 + 1.0*LMPD_13_2fe2s_c - 1.0*LMPD_13_2fe2s_c_reverse_e341b + 1.0*LMPD_6_2fe2s_c - 1.0*LMPD_6_2fe2s_c_reverse_ad57c + 1.0*LMPD_7_2fe2s_c - 1.0*LMPD_7_2fe2s_c_reverse_ef12e + 1.0*LMPD_8_2fe2s_c - 1.0*LMPD_8_2fe2s_c_reverse_e1207 + 1.0*LMPD_9_2fe2s_c - 1.0*LMPD_9_2fe2s_c_reverse_21570 <= 0.0
2h3oppan_c: 0.0 <= 1.0*GLXCL - 1.0*GLXCL_reverse_ea654 - 1.0*TRSARr + 1.0*TRSARr_reverse_ac605 <= 0.0
2pg_c: 0.0 <= -1.0*ENO + 1.0*ENO_reverse_40eea + 1.0*GLYCK2 - 1.0*GLYCK2_reverse_31342 - 1.0*PGM + 1.0*PGM_reverse_fc9af <= 0.0
3pg_c: 0.0 <= 1.0*GLYCK - 1.0*GLYCK_reverse_c3ee2 - 2.0*LMPD_100_dgtp_c + 2.0*LMPD_100_dgtp_c_reverse_fadd8 - 2.0*LMPD_101_dgtp_c + 2.0*LMPD_101_dgtp_c_reverse_31a13 - 1.0*LMPD_102_dgtp_c + 1.0*LMPD_102_dgtp_c_reverse_934d0 - 1.0*LMPD_103_dgtp_c + 1.0*LMPD_103_dgtp_c_reverse_c2562 - 1.0*LMPD_104_dgtp_c + 1.0*LMPD_104_dgtp_c_reverse_e344a - 3.0*LMPD_107_enter_c + 3.0*LMPD_107_enter_c_reverse_ca470 - 2.0*LMPD_108_fad_c + 2.0*LMPD_108_fad_c_reverse_dc934 - 2.0*LMPD_109_fad_c + 2.0*LMPD_109_fad_c_reverse_ad66d - 2.0*LMPD_10_2fe2s_c + 2.0*LMPD_10_2fe2s_c_reverse_f6cf8 - 4.0*LMPD_110_fad_c + 4.0*LMPD_110_fad_c_reverse_0bbad - 4.0*LMPD_111_fad_c + 4.0*LMPD_111_fad_c_reverse_27985 - 2.0*LMPD_112_GAM_c + 2.0*LMPD_112_GAM_c_reverse_7f6ea - 2.0*LMPD_113_GAM_c + 2.0*LMPD_113_GAM_c_reverse_cf3a8 - 1.0*LMPD_114_GAM_c + 1.0*LMPD_114_GAM_c_reverse_c3f11 - 1.0*LMPD_115_GAM_c + 1.0*LMPD_115_GAM_c_reverse_9bdbf - 2.0*LMPD_118_gthrd_c + 2.0*LMPD_118_gthrd_c_reverse_6b32d - 2.0*LMPD_119_gthrd_c + 2.0*LMPD_119_gthrd_c_reverse_075fc - 2.0*LMPD_11_2fe2s_c + 2.0*LMPD_11_2fe2s_c_reverse_31d62 - 2.0*LMPD_120_gtp_c + 2.0*LMPD_120_gtp_c_reverse_5d79c - 2.0*LMPD_121_gtp_c + 2.0*LMPD_121_gtp_c_reverse_e4a78 - 1.0*LMPD_122_gtp_c + 1.0*LMPD_122_gtp_c_reverse_2bdef - 1.0*LMPD_123_gtp_c + 1.0*LMPD_123_gtp_c_reverse_fd567 - 2.0*LMPD_12_2fe2s_c + 2.0*LMPD_12_2fe2s_c_reverse_c9941 - 4.0*LMPD_130_lipopb_c + 4.0*LMPD_130_lipopb_c_reverse_15570 - 4.0*LMPD_131_lipopb_c + 4.0*LMPD_131_lipopb_c_reverse_0e862 - 4.0*LMPD_132_lipopb_c + 4.0*LMPD_132_lipopb_c_reverse_aea25 - 4.0*LMPD_133_lipopb_c + 4.0*LMPD_133_lipopb_c_reverse_fccb7 - 2.0*LMPD_135_malcoa_c + 2.0*LMPD_135_malcoa_c_reverse_bcfd0 - 2.0*LMPD_136_malcoa_c + 2.0*LMPD_136_malcoa_c_reverse_2606b - 2.0*LMPD_137_met-L_c + 2.0*LMPD_137_met-L_c_reverse_63dae - 2.0*LMPD_138_met-L_c + 2.0*LMPD_138_met-L_c_reverse_d00d2 - 1.0*LMPD_139_mlthf_c + 1.0*LMPD_139_mlthf_c_reverse_7eccc - 2.0*LMPD_13_2fe2s_c + 2.0*LMPD_13_2fe2s_c_reverse_e341b - 1.0*LMPD_140_mlthf_c + 1.0*LMPD_140_mlthf_c_reverse_855db - 3.0*LMPD_141_mococdp_c + 3.0*LMPD_141_mococdp_c_reverse_d47c0 - 3.0*LMPD_142_mococdp_c + 3.0*LMPD_142_mococdp_c_reverse_d4ecd - 3.0*LMPD_143_mococdp_c + 3.0*LMPD_143_mococdp_c_reverse_f0cc1 - 3.0*LMPD_144_mococdp_c + 3.0*LMPD_144_mococdp_c_reverse_ca546 - 4.0*LMPD_145_mococdp_c + 4.0*LMPD_145_mococdp_c_reverse_cafc7 - 4.0*LMPD_146_mococdp_c + 4.0*LMPD_146_mococdp_c_reverse_52fcf - 4.0*LMPD_147_mococdp_c + 4.0*LMPD_147_mococdp_c_reverse_542b8 - 4.0*LMPD_148_mococdp_c + 4.0*LMPD_148_mococdp_c_reverse_76699 - 4.0*LMPD_149_mocogdp_c + 4.0*LMPD_149_mocogdp_c_reverse_0d569 - 4.0*LMPD_14_4fe4s_c + 4.0*LMPD_14_4fe4s_c_reverse_a3fa2 - 4.0*LMPD_150_mocogdp_c + 4.0*LMPD_150_mocogdp_c_reverse_f8bcb - 6.0*LMPD_151_mocogdp_c + 6.0*LMPD_151_mocogdp_c_reverse_efca5 - 6.0*LMPD_152_mocogdp_c + 6.0*LMPD_152_mocogdp_c_reverse_e7e53 - 2.0*LMPD_159_nad_c + 2.0*LMPD_159_nad_c_reverse_7a8f9 - 4.0*LMPD_15_4fe4s_c + 4.0*LMPD_15_4fe4s_c_reverse_f68ab - 2.0*LMPD_160_nad_c + 2.0*LMPD_160_nad_c_reverse_9a2ec - 1.0*LMPD_161_nad_c + 1.0*LMPD_161_nad_c_reverse_44e83 - 1.0*LMPD_162_nad_c + 1.0*LMPD_162_nad_c_reverse_0329f - 1.0*LMPD_163_pe160_c + 1.0*LMPD_163_pe160_c_reverse_c78ff - 1.0*LMPD_164_pe160_c + 1.0*LMPD_164_pe160_c_reverse_c879a - 1.0*LMPD_165_pe160_c + 1.0*LMPD_165_pe160_c_reverse_a345a - 1.0*LMPD_166_pe160_c + 1.0*LMPD_166_pe160_c_reverse_ac1d5 - 1.0*LMPD_167_pe160_c + 1.0*LMPD_167_pe160_c_reverse_41a48 - 1.0*LMPD_168_pe160_c + 1.0*LMPD_168_pe160_c_reverse_8a704 - 1.0*LMPD_169_pe160_c + 1.0*LMPD_169_pe160_c_reverse_e2b23 - 4.0*LMPD_16_4fe4s_c + 4.0*LMPD_16_4fe4s_c_reverse_29cdf - 1.0*LMPD_170_pe160_c + 1.0*LMPD_170_pe160_c_reverse_8d5d0 - 1.0*LMPD_171_pe160_c + 1.0*LMPD_171_pe160_c_reverse_9eb24 - 1.0*LMPD_172_pe160_c + 1.0*LMPD_172_pe160_c_reverse_460d3 - 1.0*LMPD_173_pe161_c + 1.0*LMPD_173_pe161_c_reverse_b7142 - 1.0*LMPD_174_pe161_c + 1.0*LMPD_174_pe161_c_reverse_32022 - 1.0*LMPD_175_pe161_c + 1.0*LMPD_175_pe161_c_reverse_06c73 - 1.0*LMPD_176_pe161_c + 1.0*LMPD_176_pe161_c_reverse_157cd - 1.0*LMPD_177_pe161_c + 1.0*LMPD_177_pe161_c_reverse_800e7 - 1.0*LMPD_178_pe161_c + 1.0*LMPD_178_pe161_c_reverse_d846c - 1.0*LMPD_179_pe161_c + 1.0*LMPD_179_pe161_c_reverse_ebdd9 - 4.0*LMPD_17_4fe4s_c + 4.0*LMPD_17_4fe4s_c_reverse_729cf - 1.0*LMPD_180_pe181_c + 1.0*LMPD_180_pe181_c_reverse_a5a20 - 1.0*LMPD_181_pe181_c + 1.0*LMPD_181_pe181_c_reverse_64d85 - 1.0*LMPD_182_pe181_c + 1.0*LMPD_182_pe181_c_reverse_9b69f - 1.0*LMPD_183_pe181_c + 1.0*LMPD_183_pe181_c_reverse_0fec5 - 1.0*LMPD_184_pe181_c + 1.0*LMPD_184_pe181_c_reverse_44dc5 - 1.0*LMPD_185_pe181_c + 1.0*LMPD_185_pe181_c_reverse_6ff41 - 1.0*LMPD_186_pe181_c + 1.0*LMPD_186_pe181_c_reverse_519c0 - 1.0*LMPD_187_pe181_c + 1.0*LMPD_187_pe181_c_reverse_71904 - 1.0*LMPD_188_pe181_c + 1.0*LMPD_188_pe181_c_reverse_6ae32 - 1.0*LMPD_189_pe181_c + 1.0*LMPD_189_pe181_c_reverse_527c1 - 4.0*LMPD_18_4fe4s_c + 4.0*LMPD_18_4fe4s_c_reverse_6d61d - 4.0*LMPD_19_4fe4s_c + 4.0*LMPD_19_4fe4s_c_reverse_f2384 - 2.0*LMPD_1_10fthf_c + 2.0*LMPD_1_10fthf_c_reverse_e2a7c - 4.0*LMPD_20_4fe4s_c + 4.0*LMPD_20_4fe4s_c_reverse_87165 - 4.0*LMPD_21_4fe4s_c + 4.0*LMPD_21_4fe4s_c_reverse_19fa6 - 3.0*LMPD_224_q8h2_c + 3.0*LMPD_224_q8h2_c_reverse_f48fd - 3.0*LMPD_225_q8h2_c + 3.0*LMPD_225_q8h2_c_reverse_56c79 - 3.0*LMPD_226_q8h2_c + 3.0*LMPD_226_q8h2_c_reverse_2ad02 - 1.0*LMPD_22_5mthf_c + 1.0*LMPD_22_5mthf_c_reverse_2e913 - 6.0*LMPD_232_q8h2_c + 6.0*LMPD_232_q8h2_c_reverse_87945 - 2.0*LMPD_235_ribflv_c + 2.0*LMPD_235_ribflv_c_reverse_e7b73 - 2.0*LMPD_236_ribflv_c + 2.0*LMPD_236_ribflv_c_reverse_b16eb - 1.0*LMPD_237_ribflv_c + 1.0*LMPD_237_ribflv_c_reverse_e7248 - 1.0*LMPD_238_ribflv_c + 1.0*LMPD_238_ribflv_c_reverse_e68fc - 1.0*LMPD_239_ser-L_c + 1.0*LMPD_239_ser-L_c_reverse_6a7ff - 1.0*LMPD_23_5mthf_c + 1.0*LMPD_23_5mthf_c_reverse_654e6 - 2.0*LMPD_241_spmd_c + 2.0*LMPD_241_spmd_c_reverse_7b0ce - 2.0*LMPD_242_spmd_c + 2.0*LMPD_242_spmd_c_reverse_c3a59 - 2.0*LMPD_243_thf_c + 2.0*LMPD_243_thf_c_reverse_fff4b - 2.0*LMPD_244_thf_c + 2.0*LMPD_244_thf_c_reverse_f65b9 - 1.0*LMPD_245_thf_c + 1.0*LMPD_245_thf_c_reverse_ef955 - 1.0*LMPD_246_thf_c + 1.0*LMPD_246_thf_c_reverse_eaf7d - 2.0*LMPD_247_thmpp_c + 2.0*LMPD_247_thmpp_c_reverse_8ed78 - 2.0*LMPD_248_thmpp_c + 2.0*LMPD_248_thmpp_c_reverse_768a6 - 2.0*LMPD_24_accoa_c + 2.0*LMPD_24_accoa_c_reverse_de241 - 2.0*LMPD_25_accoa_c + 2.0*LMPD_25_accoa_c_reverse_4dc8b - 2.0*LMPD_26_adocbl_c + 2.0*LMPD_26_adocbl_c_reverse_5a421 - 2.0*LMPD_27_adocbl_c + 2.0*LMPD_27_adocbl_c_reverse_37bdf - 1.0*LMPD_28_adocbl_c + 1.0*LMPD_28_adocbl_c_reverse_668cc - 1.0*LMPD_29_adocbl_c + 1.0*LMPD_29_adocbl_c_reverse_b8ebb - 2.0*LMPD_2_10fthf_c + 2.0*LMPD_2_10fthf_c_reverse_0c02d - 2.0*LMPD_31_amet_c + 2.0*LMPD_31_amet_c_reverse_9d1bb - 2.0*LMPD_32_amet_c + 2.0*LMPD_32_amet_c_reverse_6062b - 12.0*LMPD_35_bmocogdp_c + 12.0*LMPD_35_bmocogdp_c_reverse_1c0a0 - 12.0*LMPD_36_bmocogdp_c + 12.0*LMPD_36_bmocogdp_c_reverse_f1d5e - 8.0*LMPD_37_bmocogdp_c + 8.0*LMPD_37_bmocogdp_c_reverse_dc4f7 - 8.0*LMPD_38_bmocogdp_c + 8.0*LMPD_38_bmocogdp_c_reverse_bb4c9 - 4.0*LMPD_39_btn_c + 4.0*LMPD_39_btn_c_reverse_f338c - 3.0*LMPD_3_10fthf_c + 3.0*LMPD_3_10fthf_c_reverse_4cbc5 - 4.0*LMPD_40_btn_c + 4.0*LMPD_40_btn_c_reverse_48e5e - 4.0*LMPD_41_btn_c + 4.0*LMPD_41_btn_c_reverse_6cc40 - 4.0*LMPD_42_btn_c + 4.0*LMPD_42_btn_c_reverse_f18fb - 6.0*LMPD_43_btn_c + 6.0*LMPD_43_btn_c_reverse_a145b - 6.0*LMPD_44_btn_c + 6.0*LMPD_44_btn_c_reverse_94ba7 - 6.0*LMPD_45_btn_c + 6.0*LMPD_45_btn_c_reverse_de671 - 6.0*LMPD_47_btn_c + 6.0*LMPD_47_btn_c_reverse_ff9a4 - 1.0*LMPD_48_ca2_c + 1.0*LMPD_48_ca2_c_reverse_94b84 - 1.0*LMPD_49_ca2_c + 1.0*LMPD_49_ca2_c_reverse_0b839 - 3.0*LMPD_4_10fthf_c + 3.0*LMPD_4_10fthf_c_reverse_ebfa8 - 2.0*LMPD_6_2fe2s_c + 2.0*LMPD_6_2fe2s_c_reverse_ad57c - 2.0*LMPD_7_2fe2s_c + 2.0*LMPD_7_2fe2s_c_reverse_ef12e - 2.0*LMPD_8_2fe2s_c + 2.0*LMPD_8_2fe2s_c_reverse_e1207 - 1.0*LMPD_92_cys-L_c + 1.0*LMPD_92_cys-L_c_reverse_c37ee - 1.0*LMPD_93_cys-L_c + 1.0*LMPD_93_cys-L_c_reverse_74c9b - 2.0*LMPD_94_datp_c + 2.0*LMPD_94_datp_c_reverse_e9db9 - 2.0*LMPD_95_datp_c + 2.0*LMPD_95_datp_c_reverse_f7e36 - 1.0*LMPD_96_datp_c + 1.0*LMPD_96_datp_c_reverse_596a6 - 1.0*LMPD_97_datp_c + 1.0*LMPD_97_datp_c_reverse_3ea85 - 2.0*LMPD_99_dgtp_c + 2.0*LMPD_99_dgtp_c_reverse_65e5c - 2.0*LMPD_9_2fe2s_c + 2.0*LMPD_9_2fe2s_c_reverse_21570 - 1.0*PGK + 1.0*PGK_reverse_02696 + 1.0*PGM - 1.0*PGM_reverse_fc9af <= 0.0
4crsol_c: 0.0 <= -1.0*DM_4CRSOL + 1.0*DM_4CRSOL_reverse_50477 + 1.0*LMPD_247_thmpp_c - 1.0*LMPD_247_thmpp_c_reverse_8ed78 + 1.0*LMPD_248_thmpp_c - 1.0*LMPD_248_thmpp_c_reverse_768a6 <= 0.0
4fe4s_c: 0.0 <= -0.000248*Ec_biomass_iJO1366_WT_53p95M + 0.000248*Ec_biomass_iJO1366_WT_53p95M_reverse_55db7 + 1.0*LMPD_14_4fe4s_c - 1.0*LMPD_14_4fe4s_c_reverse_a3fa2 + 1.0*LMPD_15_4fe4s_c - 1.0*LMPD_15_4fe4s_c_reverse_f68ab + 1.0*LMPD_16_4fe4s_c - 1.0*LMPD_16_4fe4s_c_reverse_29cdf + 1.0*LMPD_17_4fe4s_c - 1.0*LMPD_17_4fe4s_c_reverse_729cf + 1.0*LMPD_18_4fe4s_c - 1.0*LMPD_18_4fe4s_c_reverse_6d61d + 1.0*LMPD_19_4fe4s_c - 1.0*LMPD_19_4fe4s_c_reverse_f2384 + 1.0*LMPD_20_4fe4s_c - 1.0*LMPD_20_4fe4s_c_reverse_87165 + 1.0*LMPD_21_4fe4s_c - 1.0*LMPD_21_4fe4s_c_reverse_19fa6 <= 0.0
5drib_c: 0.0 <= -1.0*DM_5DRIB + 1.0*DM_5DRIB_reverse_0b428 + 2.0*LMPD_125_hemeO_c - 2.0*LMPD_125_hemeO_c_reverse_b52ca + 2.0*LMPD_130_lipopb_c - 2.0*LMPD_130_lipopb_c_reverse_15570 + 2.0*LMPD_131_lipopb_c - 2.0*LMPD_131_lipopb_c_reverse_0e862 + 2.0*LMPD_132_lipopb_c - 2.0*LMPD_132_lipopb_c_reverse_aea25 + 2.0*LMPD_133_lipopb_c - 2.0*LMPD_133_lipopb_c_reverse_fccb7 + 2.0*LMPD_219_pheme_c - 2.0*LMPD_219_pheme_c_reverse_0e507 + 1.0*LMPD_247_thmpp_c - 1.0*LMPD_247_thmpp_c_reverse_8ed78 + 1.0*LMPD_248_thmpp_c - 1.0*LMPD_248_thmpp_c_reverse_768a6 + 1.0*LMPD_39_btn_c - 1.0*LMPD_39_btn_c_reverse_f338c + 1.0*LMPD_40_btn_c - 1.0*LMPD_40_btn_c_reverse_48e5e + 1.0*LMPD_41_btn_c - 1.0*LMPD_41_btn_c_reverse_6cc40 + 1.0*LMPD_42_btn_c - 1.0*LMPD_42_btn_c_reverse_f18fb + 1.0*LMPD_43_btn_c - 1.0*LMPD_43_btn_c_reverse_a145b + 1.0*LMPD_44_btn_c - 1.0*LMPD_44_btn_c_reverse_94ba7 + 1.0*LMPD_45_btn_c - 1.0*LMPD_45_btn_c_reverse_de671 + 1.0*LMPD_47_btn_c - 1.0*LMPD_47_btn_c_reverse_ff9a4 <= 0.0
5mthf_c: 0.0 <= -0.000223*Ec_biomass_iJO1366_WT_53p95M + 0.000223*Ec_biomass_iJO1366_WT_53p95M_reverse_55db7 + 1.0*LMPD_22_5mthf_c - 1.0*LMPD_22_5mthf_c_reverse_2e913 + 1.0*LMPD_23_5mthf_c - 1.0*LMPD_23_5mthf_c_reverse_654e6 <= 0.0
6pgc_c: 0.0 <= -1.0*EDD + 1.0*EDD_reverse_007a2 - 1.0*GND + 1.0*GND_reverse_eec5c + 1.0*PGL - 1.0*PGL_reverse_2bb6b <= 0.0
6pgl_c: 0.0 <= 1.0*G6PDH2r - 1.0*G6PDH2r_reverse_19ddf - 1.0*PGL + 1.0*PGL_reverse_2bb6b <= 0.0
ac_c: 0.0 <= -1.0*ACKr + 1.0*ACKr_reverse_b49c0 - 1.0*ACS + 1.0*ACS_reverse_37635 + 1.0*ACt2rpp - 1.0*ACt2rpp_reverse_213f1 + 1.0*ALDD2x - 1.0*ALDD2x_reverse_90781 + 1.0*ALDD2y - 1.0*ALDD2y_reverse_03afb + 1.0*CITL - 1.0*CITL_reverse_4d27f + 2.0*LMPD_10_2fe2s_c - 2.0*LMPD_10_2fe2s_c_reverse_f6cf8 + 1.0*LMPD_118_gthrd_c - 1.0*LMPD_118_gthrd_c_reverse_6b32d + 1.0*LMPD_119_gthrd_c - 1.0*LMPD_119_gthrd_c_reverse_075fc + 2.0*LMPD_11_2fe2s_c - 2.0*LMPD_11_2fe2s_c_reverse_31d62 + 2.0*LMPD_12_2fe2s_c - 2.0*LMPD_12_2fe2s_c_reverse_c9941 + 4.0*LMPD_130_lipopb_c - 4.0*LMPD_130_lipopb_c_reverse_15570 + 4.0*LMPD_131_lipopb_c - 4.0*LMPD_131_lipopb_c_reverse_0e862 + 4.0*LMPD_132_lipopb_c - 4.0*LMPD_132_lipopb_c_reverse_aea25 + 4.0*LMPD_133_lipopb_c - 4.0*LMPD_133_lipopb_c_reverse_fccb7 + 1.0*LMPD_135_malcoa_c - 1.0*LMPD_135_malcoa_c_reverse_bcfd0 + 1.0*LMPD_136_malcoa_c - 1.0*LMPD_136_malcoa_c_reverse_2606b + 1.0*LMPD_137_met-L_c - 1.0*LMPD_137_met-L_c_reverse_63dae + 1.0*LMPD_138_met-L_c - 1.0*LMPD_138_met-L_c_reverse_d00d2 + 2.0*LMPD_13_2fe2s_c - 2.0*LMPD_13_2fe2s_c_reverse_e341b + 2.0*LMPD_141_mococdp_c - 2.0*LMPD_141_mococdp_c_reverse_d47c0 + 2.0*LMPD_142_mococdp_c - 2.0*LMPD_142_mococdp_c_reverse_d4ecd + 2.0*LMPD_143_mococdp_c - 2.0*LMPD_143_mococdp_c_reverse_f0cc1 + 2.0*LMPD_144_mococdp_c - 2.0*LMPD_144_mococdp_c_reverse_ca546 + 2.0*LMPD_145_mococdp_c - 2.0*LMPD_145_mococdp_c_reverse_cafc7 + 2.0*LMPD_146_mococdp_c - 2.0*LMPD_146_mococdp_c_reverse_52fcf + 2.0*LMPD_147_mococdp_c - 2.0*LMPD_147_mococdp_c_reverse_542b8 + 2.0*LMPD_148_mococdp_c - 2.0*LMPD_148_mococdp_c_reverse_76699 + 2.0*LMPD_149_mocogdp_c - 2.0*LMPD_149_mocogdp_c_reverse_0d569 + 4.0*LMPD_14_4fe4s_c - 4.0*LMPD_14_4fe4s_c_reverse_a3fa2 + 2.0*LMPD_150_mocogdp_c - 2.0*LMPD_150_mocogdp_c_reverse_f8bcb + 2.0*LMPD_151_mocogdp_c - 2.0*LMPD_151_mocogdp_c_reverse_efca5 + 2.0*LMPD_152_mocogdp_c - 2.0*LMPD_152_mocogdp_c_reverse_e7e53 + 4.0*LMPD_15_4fe4s_c - 4.0*LMPD_15_4fe4s_c_reverse_f68ab + 4.0*LMPD_16_4fe4s_c - 4.0*LMPD_16_4fe4s_c_reverse_29cdf + 4.0*LMPD_17_4fe4s_c - 4.0*LMPD_17_4fe4s_c_reverse_729cf + 4.0*LMPD_18_4fe4s_c - 4.0*LMPD_18_4fe4s_c_reverse_6d61d + 4.0*LMPD_19_4fe4s_c - 4.0*LMPD_19_4fe4s_c_reverse_f2384 + 4.0*LMPD_20_4fe4s_c - 4.0*LMPD_20_4fe4s_c_reverse_87165 + 4.0*LMPD_21_4fe4s_c - 4.0*LMPD_21_4fe4s_c_reverse_19fa6 + 1.0*LMPD_221_ptrc_c - 1.0*LMPD_221_ptrc_c_reverse_0ea03 + 2.0*LMPD_241_spmd_c - 2.0*LMPD_241_spmd_c_reverse_7b0ce + 2.0*LMPD_242_spmd_c - 2.0*LMPD_242_spmd_c_reverse_c3a59 + 1.0*LMPD_247_thmpp_c - 1.0*LMPD_247_thmpp_c_reverse_8ed78 + 1.0*LMPD_248_thmpp_c - 1.0*LMPD_248_thmpp_c_reverse_768a6 + 1.0*LMPD_24_accoa_c - 1.0*LMPD_24_accoa_c_reverse_de241 + 1.0*LMPD_25_accoa_c - 1.0*LMPD_25_accoa_c_reverse_4dc8b + 1.0*LMPD_31_amet_c - 1.0*LMPD_31_amet_c_reverse_9d1bb + 1.0*LMPD_32_amet_c - 1.0*LMPD_32_amet_c_reverse_6062b + 1.0*LMPD_33_arg-L_c - 1.0*LMPD_33_arg-L_c_reverse_e46b4 + 4.0*LMPD_35_bmocogdp_c - 4.0*LMPD_35_bmocogdp_c_reverse_1c0a0 + 4.0*LMPD_36_bmocogdp_c - 4.0*LMPD_36_bmocogdp_c_reverse_f1d5e + 4.0*LMPD_37_bmocogdp_c - 4.0*LMPD_37_bmocogdp_c_reverse_dc4f7 + 4.0*LMPD_38_bmocogdp_c - 4.0*LMPD_38_bmocogdp_c_reverse_bb4c9 + 2.0*LMPD_39_btn_c - 2.0*LMPD_39_btn_c_reverse_f338c + 2.0*LMPD_40_btn_c - 2.0*LMPD_40_btn_c_reverse_48e5e + 2.0*LMPD_41_btn_c - 2.0*LMPD_41_btn_c_reverse_6cc40 + 2.0*LMPD_42_btn_c - 2.0*LMPD_42_btn_c_reverse_f18fb + 3.0*LMPD_43_btn_c - 3.0*LMPD_43_btn_c_reverse_a145b + 3.0*LMPD_44_btn_c - 3.0*LMPD_44_btn_c_reverse_94ba7 + 3.0*LMPD_45_btn_c - 3.0*LMPD_45_btn_c_reverse_de671 + 3.0*LMPD_47_btn_c - 3.0*LMPD_47_btn_c_reverse_ff9a4 + 1.0*LMPD_49_ca2_c - 1.0*LMPD_49_ca2_c_reverse_0b839 + 2.0*LMPD_6_2fe2s_c - 2.0*LMPD_6_2fe2s_c_reverse_ad57c + 2.0*LMPD_79_colipa_e - 2.0*LMPD_79_colipa_e_reverse_4066c + 2.0*LMPD_7_2fe2s_c - 2.0*LMPD_7_2fe2s_c_reverse_ef12e + 2.0*LMPD_80_colipa_e - 2.0*LMPD_80_colipa_e_reverse_4a038 + 2.0*LMPD_81_colipa_e - 2.0*LMPD_81_colipa_e_reverse_3f64a + 2.0*LMPD_82_colipa_e - 2.0*LMPD_82_colipa_e_reverse_964e6 + 2.0*LMPD_83_colipa_e - 2.0*LMPD_83_colipa_e_reverse_c70d1 + 2.0*LMPD_84_colipa_e - 2.0*LMPD_84_colipa_e_reverse_9295e + 2.0*LMPD_85_colipa_e - 2.0*LMPD_85_colipa_e_reverse_efb04 + 2.0*LMPD_86_colipa_e - 2.0*LMPD_86_colipa_e_reverse_537a8 + 2.0*LMPD_87_colipa_e - 2.0*LMPD_87_colipa_e_reverse_314af + 2.0*LMPD_88_colipa_e - 2.0*LMPD_88_colipa_e_reverse_df934 + 2.0*LMPD_89_colipa_e - 2.0*LMPD_89_colipa_e_reverse_ffd20 + 2.0*LMPD_8_2fe2s_c - 2.0*LMPD_8_2fe2s_c_reverse_e1207 + 2.0*LMPD_90_colipa_e - 2.0*LMPD_90_colipa_e_reverse_e176b + 1.0*LMPD_92_cys-L_c - 1.0*LMPD_92_cys-L_c_reverse_c37ee + 1.0*LMPD_93_cys-L_c - 1.0*LMPD_93_cys-L_c_reverse_74c9b + 2.0*LMPD_9_2fe2s_c - 2.0*LMPD_9_2fe2s_c_reverse_21570 + 1.0*POX - 1.0*POX_reverse_35cf5 <= 0.0
acald_c: 0.0 <= -1.0*ACALD + 1.0*ACALD_reverse_fda2b + 1.0*ACALDtpp - 1.0*ACALDtpp_reverse_52ae6 + 1.0*ALCD2x - 1.0*ALCD2x_reverse_5d107 - 1.0*ALDD2x + 1.0*ALDD2x_reverse_90781 - 1.0*ALDD2y + 1.0*ALDD2y_reverse_03afb + 1.0*LMPD_117_gly_c - 1.0*LMPD_117_gly_c_reverse_3be87 <= 0.0

In [ ]:
thermo_data['metabolites'].keys()

In [ ]:
[r.id for r in mytfa.reactions if r.thermo is not None]

# R. palustris model

Previously constrained

In [ ]:
# Load models

# Directory where the model lives
phbv_model_dir = PHBV_MODEL_DIR / "phbv"
phbv_model_dir.mkdir(parents=True, exist_ok=True)

# Full path to the SBML file
rp_lex_mat_path = PHBV_MODEL_DIR / "model_rpalustris_PHBV_constrained.xml"

# Load model
model_phbv = io.read_sbml_model(
    str(rp_lex_mat_path),
    use_fbc=False
)

print("Model loaded successfully")

Model loaded successfully

In [ ]:
r_phbv  = model_phbv.reactions.get_by_id("PHBVS_syn")     # PHBV copolymer
model_phbv.objective = r_phbv
model_phbv.summary()

In [ ]:


#rp_model_mat_path = project_root_palustris / "iDT1294.mat" # Load iDT1294.mat file (base model)
rp_lex_mat_path = PHB_MODEL_TFA_DIR / "lexicon_iDT1294.csv" # load lexicon with 8 reactions
rp_comp_mat_path = PHB_MODEL_TFA_DIR / "compartment_data.json" # "compartments_data_iDT1294_test.json"


cobra_model_mat = model_phbv #load_matlab_model(str(rp_model_mat_path))

# Correct formulas

In [ ]:
import re
from collections import Counter

# --------------------------------
# INPUT DATA
# --------------------------------
Thermodb_meta_interest = [
  "C21H27N7O17P3",
  "C21H27N7O14P2",
  "C23H35N7O17P3S",
  "C21H26N7O14P2",
  "C25H39N7O18P3S",
  "C21H26N7O17P3",
  "C25H37N7O18P3S",
  "C21H33N7O16P3S"
]

GEM_meta_interest = [
  "C21H26N7O17P3",
  "C21H27N7O14P2",
  "C23H34N7O17P3S",
  "C21H26N7O14P2",
  "C25H38N7O18P3S",
  "C21H25N7O17P3",
  "C25H36N7O18P3S",
  "C21H32N7O16P3S"
]

# GEM metabolite IDs in SAME ORDER
gem_met_ids = [
  "nadph_c",
  "nadh_c",
  "accoa_c",
  "nad_c",
  "3hbcoa__R_c",
  "nadp_c",
  "aacoa_c",
  "coa_c",
]

# --------------------------------
# FORMULA PARSING UTILITIES
# --------------------------------
def parse_formula(formula):
  """Convert formula string to Counter"""
  return Counter({
      elem: int(count) if count else 1
      for elem, count in re.findall(r'([A-Z][a-z]?)(\d*)', formula)
  })

def counter_to_formula(counter):
  """Convert Counter back to formula string (Hill order, omit 1s)"""
  parts = []

  # Hill system: C, H, then others alphabetically
  if 'C' in counter:
      parts.append(f"C{counter['C']}" if counter['C'] != 1 else "C")
  if 'H' in counter:
      parts.append(f"H{counter['H']}" if counter['H'] != 1 else "H")

  for el in sorted(counter):
      if el in ('C', 'H'):
          continue
      count = counter[el]
      parts.append(f"{el}{count}" if count != 1 else el)

  return ''.join(parts)


def compare_formulas(thermo_f, gem_f):
  """Return element-wise difference GEM − ThermoDB"""
  t = parse_formula(thermo_f)
  g = parse_formula(gem_f)
  elements = set(t) | set(g)
  return {el: g.get(el, 0) - t.get(el, 0) for el in elements}

def update_gem_formula(gem_f, thermo_f):
  """Add missing elements from ThermoDB into GEM formula"""
  g = parse_formula(gem_f)
  t = parse_formula(thermo_f)

  for el, count in t.items():
      if g.get(el, 0) < count:
          g[el] = count

  return counter_to_formula(g)

# --------------------------------
# APPLY UPDATES TO MODEL
# --------------------------------
for met_id, thermo_f, gem_f in zip(gem_met_ids,
                                  Thermodb_meta_interest,
                                  GEM_meta_interest):

    diff = compare_formulas(thermo_f, gem_f)

    # Safety check (CRITICAL for TFA)
    for el in diff:
        if el in ("C", "N", "P") and diff[el] != 0:
            raise ValueError(
                f"Unsafe formula mismatch for {met_id}: element {el}"
            )

    new_formula = update_gem_formula(gem_f, thermo_f)

    if new_formula != gem_f:
        met = cobra_model_mat.metabolites.get_by_id(met_id) ## update cobra model

        print(f"Updating {met_id}")
        print(f"  old: {gem_f}")
        print(f"  new: {new_formula}")
        print(f"  ThermoDB:       {thermo_f}")

        met.formula = new_formula

        # PRINT FROM MODEL OBJECT
        print(f"  new (model):  {met.formula}")
        print("-" * 40)


print("✅ GEM formulas updated and TFA-ready.")

NameError: name 'cobra_model_mat' is not defined

In [ ]:
annotated = [
    m for m in mytfa.metabolites
    if "seed_id" in m.annotation
]

print("Annotated metabolites:", len(annotated))

NameError: name 'mytfa' is not defined

In [ ]:
rxns_with_annotated_mets = []

for r in mytfa.reactions:
    mets = r.metabolites
    if all(
        ("seed_id" in m.annotation) and (m.formula is not None)
        for m in mets
    ):
        rxns_with_annotated_mets.append(r.id)

print("Thermo-eligible reactions:", len(rxns_with_annotated_mets))

NameError: name 'mytfa' is not defined

# Load medium constraints

In [ ]:
# Apply medium constraints from Montiel-Corona 2022.
def apply_media_from_excel(model, excel_path, close_exchanges=True):
    """
    Apply media constraints from an Excel file with columns:
    Reaction | LowerBound | UpperBound
    """

    #media_df = pd.read_csv(excel_path)
    media_df = pd.read_excel(excel_path)


    required_cols = {"Reaction", "LowerBound", "UpperBound"}
    if not required_cols.issubset(media_df.columns):
        raise ValueError(
            f"Excel file must contain columns: {required_cols}"
        )

    # Optionally close all exchanges first
    if close_exchanges:
        for rxn in model.exchanges:
            rxn.lower_bound = 0
            rxn.upper_bound = 1000

    # Apply media bounds
    for _, row in media_df.iterrows():
        rxn_id = row["Reaction"]

        if rxn_id not in model.reactions:
            raise KeyError(f"Reaction {rxn_id} not found in model")

        rxn = model.reactions.get_by_id(rxn_id)
        rxn.lower_bound = float(row["LowerBound"])
        rxn.upper_bound = float(row["UpperBound"])

    # Check reaction directly associated to PHB production
    EX_acetate_rxn = model.reactions.get_by_id("EX_ac_e")
    print(EX_acetate_rxn.bounds)
    print(EX_acetate_rxn.reaction)

    return model

In [ ]:
# Load medium conditions from Pareto results
project_root = Path(os.getcwd())
excel_path_pareto_medium = project_root / "phbv" / "checkpoint_output" / "Pareto_result_PHBV_model_medium_montiel_buitron_2022_exchange_bounds.xlsx"
print(excel_path_pareto_medium)

/content/driveDL/MyDrive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/models/phbv/checkpoint_output/Pareto_result_PHBV_model_medium_montiel_buitron_2022_exchange_bounds.xlsx

In [ ]:
cobra_model_mat

In [ ]:
#cobra_model_mat2 = cobra_model_mat.copy()
apply_media_from_excel(cobra_model_mat, excel_path_pareto_medium)

(-1.7, 1000.0)
ac_e <=>

# Add compartments to cobra model

In [ ]:
cobra_model.compartments = {
        'c': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        },
        'e': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        },
        'p': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.15,   # periplasm vs cytosol (example)
        },
        'u': {
            'pH': 7.0,
            'ionicStr': 0.25,
            'c_min': 1e-6,
            'c_max': 0.02,
            'membranePot': 0.0,
        }
    }

# Multiple points FBA (version 1)

In [ ]:
model_phbv2 = model_phbv.copy()

In [ ]:
"""
Full corrected script: converts experimental values → fluxes and runs FBA per row.
Features / changes:
 - Uses per-row Time (d) -> TIME_H_ROW
 - Uses INITIAL_BIOMASS as the mean of the provided inoculum list
 - Uses effective biomass X_eff = (INITIAL_BIOMASS + biomass_final)/2 for normalization
 - Supports substrates: acetate, hexanoate, fumarate, lactate, propionate, butyrate, succinate
 - Converts g COD/L (fed) -> mg COD/L -> substrate mg/L -> mmol/L -> mmol·gDW⁻¹·h⁻¹
 - Converts PHB mg/L -> mmol/L -> mmol·gDW⁻¹·h⁻¹ using X_eff and TIME_H_ROW
 - Keeps your medium / photon scaling / reaction checks / CSV outputs
 - Assumes `model_phbv2` (COBRA model) is already loaded in the session
"""

# -------------------------
# USER: input dataset path
# -------------------------
CSV_PATH = "/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/data/Buitron2025_dataset.csv"

# -------------------------
# CONSTANTS (mg / mmol)
# -------------------------
PHB_MW        = 86.0     # mg/mmol (3HB monomer)
PHV_MW  = 100.12  # mg/mmol (3HV monomer)
ACETATE_MW    = 59.04
HEXANOATE_MW  = 116.16
FUMARATE_MW   = 116.07
LACTATE_MW    = 90.08
PROPIONATE_MW = 74.08
BUTYRATE_MW   = 88.11
SUCCINATE_MW  = 118.09

# COD to acetate mass equivalence (mg COD per mg acetate)
COD_TO_ACETATE_RATIO = 1.066  #Constant

# If Time(d) missing fallback (hours)
FALLBACK_TIME_H = 72.0

# Initial inoculum values provided (mg DW/L)

INITIAL_BIOMASS = 0.094  # gDW/L

# -------------------------
# Load dataset and slice as in original
# -------------------------
df = pd.read_csv(CSV_PATH)

# Select rows 1 to 34 (the original used iloc[1:35])
df = df.iloc[1:35].reset_index(drop=True)

# Drop rows 17 and 18 (indices 15 and 16 after reset)
df = df.drop(index=[15, 16]).reset_index(drop=True)

print("Loaded dataset shape:", df.shape)
print(f"Using INITIAL_BIOMASS (mean inoculum) = {INITIAL_BIOMASS:.6f} gDW/L")

# -------------------------
# Medium conservative upperbounds (unchanged)
# -------------------------
nh4_from_acetate = 0.06590
nh4_from_nh4cl   = 0.07598
total_nh4_uptake = nh4_from_acetate + nh4_from_nh4cl

medium_montiel_buitron_2022_conservative_upperbound = {
    "EX_ac_e"   : 0.2477,
    "EX_nh4_e"  : total_nh4_uptake,
    "EX_pi_e"   : 0.03733,
    "EX_mg2_e"  : 0.01604,
    "EX_na1_e"  : 0.06955,
    "EX_ca2_e"  : 0.003455,
    "EX_fe3_e"  : 0.0004147,
    "EX_zn2_e"  : 0.000002337,
    "EX_mn2_e"  : 0.000000620,
    "EX_bo3_e"  : 0.00001972,
    "EX_cu2_e"  : 0.000000234,
    "EX_ni2_e"  : 0.000000345,
    "EX_mobd_e" : 0.000000559,
    "EX_co2_e"  : 0,
    "EX_o2_e"   : 0,
    # photons (kept)
    "EX_photon410_e": 100,
    "EX_photon430_e": 100,
    "EX_photon450_e": 100,
    "EX_photon470_e": 100,
    "EX_photon490_e": 100,
    "EX_photon510_e": 100,
    "EX_photon530_e": 100,
    "EX_photon550_e": 100,
    "EX_photon570_e": 100,
    "EX_photon590_e": 100,
    "EX_photon610_e": 100,
    "EX_photon630_e": 100,
    "EX_photon650_e": 100,
    "EX_photon670_e": 100,
    "EX_photon690_e": 100
}

# -------------------------
# Safe photon scaling (unchanged)
# -------------------------
def safe_scale_photons(model, illum_value, ref=1000.0):

    def photons_off():
        for rxn in model.reactions:
            if rxn.id.startswith("EX_photon"):
                model.reactions.get_by_id(rxn.id).lower_bound = 0

    # NaN or empty
    if pd.isna(illum_value):
        photons_off()
        return

    illum_str = str(illum_value).lower()

    if illum_str in ["continuous", "light", "constant", "on"]:
        for rxn_id, ub in medium_montiel_buitron_2022_conservative_upperbound.items():
            if rxn_id.startswith("EX_photon") and rxn_id in model.reactions:
                model.reactions.get_by_id(rxn_id).lower_bound = -ub
        return

    extracted = "".join(ch for ch in illum_str if ch.isdigit() or ch == ".")

    if extracted == "":
        photons_off()
        return

    try:
        num = float(extracted)
    except:
        photons_off()
        return

    if num == 0:
        photons_off()
        return

    scale = num / ref

    for rxn_id, ub in medium_montiel_buitron_2022_conservative_upperbound.items():
        if rxn_id.startswith("EX_photon") and rxn_id in model.reactions:
            model.reactions.get_by_id(rxn_id).lower_bound = -scale * ub

# -------------------------
# Helper to safe-get flux from solution
# -------------------------
def get_flux(sol, rxn_id):
    try:
        return float(sol.fluxes.get(rxn_id, np.nan))
    except Exception:
        return np.nan

# -------------------------
# Output directories
# -------------------------
os.makedirs("medium_rows", exist_ok=True)
os.makedirs("fluxes_rows", exist_ok=True)

# -------------------------
# Pre-check reaction ids in GEM
# -------------------------
r_ac_exists     = "EX_ac_e"        in model_phbv2.reactions
r_hxa_exists    = "EX_hxa_e"       in model_phbv2.reactions
r_fum_exists    = "EX_fum_e"       in model_phbv2.reactions
r_lac_exists    = "EX_lac__L_e"    in model_phbv2.reactions
r_ppa_exists    = "EX_ppa_e"       in model_phbv2.reactions
r_but_exists    = "EX_but_e"       in model_phbv2.reactions
r_succ_exists   = "EX_succ_e"      in model_phbv2.reactions
r_phb_exists    = "PHBS_syn"       in model_phbv2.reactions
r_phv_exists     = "PHVS_syn"       in model_phbv2.reactions
r_phbv_exists    = "PHBVS_syn"       in model_phbv2.reactions
r_3hvcoa_exists    = "3hvcoa_syn"       in model_phbv2.reactions
r_biomass_exists= "BIOMASS__1"     in model_phbv2.reactions

print(
    f"Model reaction presence: "
    f"EX_ac_e={r_ac_exists}, EX_hxa_e={r_hxa_exists}, EX_fum_e={r_fum_exists}, "
    f"EX_lac__L_e={r_lac_exists}, EX_ppa_e={r_ppa_exists}, EX_but_e={r_but_exists}, EX_succ_e={r_succ_exists}, "
    f"PHBS_syn={r_phb_exists}, BIOMASS__1={r_biomass_exists}, PHBVS_syn={r_phb_exists}"
)

# -------------------------
# MAIN LOOP
# -------------------------
results = []

for idx, row in df.iterrows():

    row_id = idx + 1
    print(f"\n=== Row {row_id} / {len(df)} ===")

    # copy model for this row
    m = model_phbv2.copy()

    # reset exchange lower bounds to 0 then apply conservative upperbounds
    for ex in m.exchanges:
        ex.lower_bound = 0.0

    for rxn_id, ub in medium_montiel_buitron_2022_conservative_upperbound.items():
        if rxn_id in m.reactions:
            m.reactions.get_by_id(rxn_id).lower_bound = -ub

    # -------------------------
    # Final biomass (from dataset)
    # -------------------------
    biomass_mgL = row.get("Biomass (mg dw/L)", np.nan)
    if pd.isna(biomass_mgL) or biomass_mgL == 0:
        print(f"  WARNING: Biomass missing or zero in row {row_id}; setting biomass_final_gL = NaN")
        biomass_final_gL = np.nan
    else:
        biomass_final_gL = biomass_mgL / 1000.0  # mg -> gDW/L

    # -------------------------
    # Row-specific time handling (Time (d) -> hours)
    # -------------------------
    time_days = row.get("Time (d)", np.nan)
    if pd.isna(time_days) or time_days <= 0:
        print(f"  WARNING: Missing or invalid Time (d) in row {row_id}; using fallback {FALLBACK_TIME_H} h")
        t_hours = FALLBACK_TIME_H
    else:
        t_hours = float(time_days) * 24

    # -------------------------
    # Effective biomass (X_eff = (initial_inoculum + final)/2)
    # -------------------------
    if pd.isna(biomass_final_gL):
        X_eff = np.nan
    else:
        X_eff = (INITIAL_BIOMASS + biomass_final_gL) / 2 #biomass_final_gL #

    print(f"  Time (h) = {t_hours:.2f}, biomass_final_gL = {biomass_final_gL}, X_eff = {X_eff}")

    # -------------------------
    # PHB experimental conversion mg/L -> q_phb (mmol·gDW⁻¹·h⁻¹)
    # -------------------------
    phb_mgL = row.get("PHB (mg/L)", np.nan)
    if pd.isna(phb_mgL) or pd.isna(X_eff) or X_eff == 0:
        q_phb = np.nan
    else:
        phb_mmolL = phb_mgL / PHB_MW
        q_phb = phb_mmolL / (X_eff * t_hours)

    # -------------------------
    # PHV experimental conversion mg/L -> q_phv (mmol·gDW⁻¹·h⁻¹)
    # -------------------------
    phv_mgL = row.get("PHV (mg/L)", np.nan)

    if pd.isna(phv_mgL) or pd.isna(X_eff) or X_eff == 0:
        q_phv = np.nan
    else:
        phv_mmolL = phv_mgL / PHV_MW
        q_phv = phv_mmolL / (X_eff * t_hours)

    # -------------------------
    # Experimental PHBV flux (PHB + PHV)
    # -------------------------
    if not pd.isna(q_phb) and not pd.isna(q_phv):
        q_phbv = q_phb + q_phv
    else:
        q_phbv = np.nan


    # -------------------------
    # COD-fed -> substrate uptake flux (q_sub)
    # -------------------------
    COD_gL_fed = row.get("g substrate COD/L", np.nan)   # g COD / L fed
    substrate_type = str(row.get("Type of substrate", "")).strip().lower()

    q_sub = np.nan
    sub_rxn_id = None

    if not pd.isna(COD_gL_fed) and COD_gL_fed > 0 and not pd.isna(X_eff) and X_eff > 0:
        # convert g COD/L -> mg COD/L
        cod_mgL = COD_gL_fed * 1000.0

        # for acetate we convert COD to acetate mass using COD_TO_ACETATE_RATIO
        if substrate_type in ["acetate", "ac", "acetic acid"]:
            substrate_mgL = cod_mgL / COD_TO_ACETATE_RATIO
            substrate_mmolL = substrate_mgL / ACETATE_MW
            sub_rxn_id = "EX_ac_e"

        elif substrate_type in ["hexanoate", "hexanoic acid", "hxa", "hex"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / HEXANOATE_MW
            sub_rxn_id = "EX_hxa_e"

        elif substrate_type in ["fumarate", "fum"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / FUMARATE_MW
            sub_rxn_id = "EX_fum_e"

        elif substrate_type in ["lactate", "lac", "lactic acid"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / LACTATE_MW
            sub_rxn_id = "EX_lac__L_e"

        elif substrate_type in ["propionate", "ppa", "propionic acid", "prop"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / PROPIONATE_MW
            sub_rxn_id = "EX_ppa_e"

        elif substrate_type in ["butyrate", "but", "butyric acid"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / BUTYRATE_MW
            sub_rxn_id = "EX_but_e"

        elif substrate_type in ["succinate", "succ", "succinic acid"]:
            substrate_mgL = cod_mgL
            substrate_mmolL = substrate_mgL / SUCCINATE_MW
            sub_rxn_id = "EX_succ_e"

        else:
            # default conservative: treat as acetate COD
            substrate_mgL = cod_mgL / COD_TO_ACETATE_RATIO
            substrate_mmolL = substrate_mgL / ACETATE_MW
            sub_rxn_id = "EX_ac_e"
            print(f"  NOTE row {row_id}: substrate_type '{substrate_type}' not recognized -> assuming acetate conversion")

        # compute q_sub (mmol·gDW⁻¹·h⁻¹)
        try:
            q_sub = substrate_mmolL / (X_eff * t_hours)
        except Exception as e:
            print(f"  ERROR computing q_sub row {row_id}: {e}")
            q_sub = np.nan

    else:
        print(f"  WARNING row {row_id}: Missing COD_fed or X_eff -> q_sub set to NaN")

    # -------------------------
    # Apply substrate flux bounds if reaction exists
    # -------------------------
    if sub_rxn_id and sub_rxn_id in m.reactions and not pd.isna(q_sub):
        # set both bounds to -q_sub to force uptake (negative uptake in COBRA convention)
        m.reactions.get_by_id(sub_rxn_id).lower_bound = -q_sub
        m.reactions.get_by_id(sub_rxn_id).upper_bound = -q_sub
    else:
        if sub_rxn_id and sub_rxn_id not in m.reactions:
            print(f"  Reaction {sub_rxn_id} not present in model; skipping substrate constraint for row {row_id}")

    # -------------------------
    # Illumination -> photon scaling
    # -------------------------
    illum = row.get("Illumination", np.nan)
    safe_scale_photons(m, illum)

    # -------------------------
    # PHB physiological cap and objective (Option A)
    # -------------------------

#PHVS_syn: imbalance -> {'H': 2.0, 'O': 1.0}
#PHBS_syn: imbalance -> {'C': 1.0, 'H': 2.0}
#PHBVS_syn: imbalance -> {}

    phb_rxn_id = 'PHBVS_syn'
    mu_max = 0.08 # growth rate
    f = 0.50       # fraction of the maximum growth-associated carbon/flux that is diverted to PHB synthesis

    v_phbv_max = 1 #mu_max * f * 1000 / PHV_MW
    v_phbv_max_eff = mu_max * f * 1000 / PHV_MW + PHB_MW
    print(f" Calculated v_phbv_max (mmol/gDW/h) = {v_phbv_max_eff:.6f}")
    print(f" v_phbv_max (mmol/gDW/h) = {v_phbv_max:.6f}")

    if r_phb_exists and phb_rxn_id in m.reactions:
        phb_rxn = m.reactions.get_by_id(phb_rxn_id)
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = v_phbv_max
        m.objective = phb_rxn # define OBJECTIVE
    else:
        print(f"WARNING: PHBS_syn not found in model for row {row_id}")

    # -------------------------
    # Minimal biomass requirement (if present)
    # Enabling biomass bounds turn predictions infeasible (probably because biomass and PHB produciton are competing objectives)
    # -------------------------
    if r_biomass_exists and "BIOMASS__1" in m.reactions:
        biomass_rxn = m.reactions.get_by_id("BIOMASS__1")
        biomass_rxn.lower_bound = 0 #0.001626
        biomass_rxn.upper_bound = 0

    # optional model fixes
    #if "EX_h2_e" in m.reactions:
    #    m.reactions.get_by_id("EX_h2_e").lower_bound = 0
    #    m.reactions.get_by_id("EX_h2_e").upper_bound = 1000.0

    #if "EX_no3_e" in m.reactions:
    #    no3 = m.reactions.get_by_id("EX_no3_e")
    #    no3.lower_bound = -1000.0
    #    no3.upper_bound = 0

    #if "ATPM" in m.reactions:
    #   m.reactions.get_by_id("ATPM").lower_bound = 10


    # Disable homopolymer synthetases to avoid competition (temporary)
      #"PHVS_syn"
    #for rid in ["PHVS_syn", "PHBVS_syn"]:
    #    if rid in m.reactions:
    #        m.reactions.get_by_id(rid).lower_bound = 0
    #        m.reactions.get_by_id(rid).upper_bound = 0

    m.summary()

    # Finla check of key reactions before optimization
    EX_ac_e_rxn = m.reactions.get_by_id('EX_ac_e') #PDH #PHBS_syn #EX_ac_e
    print(f"{EX_ac_e_rxn.id}: lower = {EX_ac_e_rxn.lower_bound}, upper = {EX_ac_e_rxn.upper_bound}") # bounds
    # -------------------------
    # Run FBA
    # -------------------------
    sol = m.optimize()
    if sol.status != "optimal":
        print(f"  Row {row_id}: no optimal solution (status={sol.status}); saving NaNs")
        fluxes = sol.fluxes if hasattr(sol, "fluxes") else pd.Series()
    else:
        fluxes = sol.fluxes

    # Save model

    # Directory where the model lives
    phb_model_dir = project_root / "phbv"

    # Ensure folder exists
    phb_model_dir.mkdir(parents=True, exist_ok=True)

    # Target file
    phb_model_file = phb_model_dir / "model_rpalustris_PHBV_constrained_FBA_loop.xml"

    # Save COBRA model
    cobra.io.write_sbml_model(m, str(phb_model_file))

    # -------------------------
    # Save medium CSV for this row
    # -------------------------
    try:
        medium_df = pd.DataFrame({
            "reaction": [rxn.id for rxn in m.exchanges],
            "lb":       [rxn.lower_bound for rxn in m.exchanges],
            "ub":       [rxn.upper_bound for rxn in m.exchanges],
            "flux":     [float(fluxes.get(rxn.id, np.nan)) for rxn in m.exchanges]
        })
        medium_df.to_csv(f"medium_rows/medium_row_{row_id}.csv", index=False)
    except Exception as e:
        print(f"  Error saving medium_row_{row_id}.csv: {e}")

    # -------------------------
    # Save full flux vector for this row
    # -------------------------
    try:
        fluxes_df = pd.DataFrame({
            "reaction": fluxes.index.astype(str),
            "flux": fluxes.values
        })
        fluxes_df.to_csv(f"fluxes_rows/fluxes_row_{row_id}.csv", index=False)
    except Exception as e:
        print(f"  Error saving fluxes_row_{row_id}.csv: {e}")

    # -------------------------
    # Collect outputs for summary table
    # -------------------------
    biomass_flux = get_flux(sol, "BIOMASS__1") if r_biomass_exists else np.nan
    #phb_flux_model = get_flux(sol, "PHBS_syn") if r_phb_exists else np.nan
    #phv_flux_model = get_flux(sol, "PHVS_syn") if r_phv_exists else np.nan
    phbv_flux_model = get_flux(sol, "PHBVS_syn") if r_phbv_exists else np.nan
    hv_flux_model = get_flux(sol, "3hvcoa_syn") if r_phbv_exists else np.nan
    hb_flux_model = get_flux(sol, "AACOAR_syn") if r_phbv_exists else np.nan
    PHBV_model_accumulation = get_flux(sol, "DM_PHBV_c") if r_phbv_exists else np.nan
    sub_flux_model = get_flux(sol, sub_rxn_id) if sub_rxn_id and sub_rxn_id in m.reactions else np.nan

    # top 10 absolute fluxes
    try:
      top10 = fluxes.abs().sort_values(ascending=False).head(10)

      records = []
      for rxn_id in top10.index:
          rxn = m.reactions.get_by_id(rxn_id)

          records.append({
              "reaction_id": rxn_id,
              "flux": float(fluxes.get(rxn_id, np.nan)),
              "name": rxn.name if rxn.name else "Unnamed",
              "subsystem": rxn.subsystem if rxn.subsystem else "Unassigned"
          })

      # Final DataFrame with full metadata
      top10_df = pd.DataFrame(records)

      # JSON/dict format for later use if needed
      top10_dict = {row["reaction_id"]: row["flux"] for row in records}

      # store for wordcloud later
      top10_subsystems = list(top10_df["subsystem"])

      # Save top 10 flux details per row
      top10_df.to_csv(f"fluxes_rows/top10_fluxes_row_{row_id}.csv", index=False)

    except Exception as e:
        print(f"Error extracting top10 fluxes row {row_id}: {e}")
        top10_df = pd.DataFrame(columns=["reaction_id","flux","name","subsystem"])
        top10_dict = {}
        top10_subsystems = []

    print(f"PHB_exp_flux  : {q_phb}")
    print(f"PHV_exp_flux  : {q_phv}")
    print(f"PHBV_exp_flux : {q_phbv}")
    #print(f"PHB_model_flux: {phb_flux_model}")
    #print(f"PHV_model_flux: {phv_flux_model}")
    print(f"3HV_model_flux: {hv_flux_model}")
    print(f"3HB_model_flux: {hb_flux_model}")
    print(f"PHBV_model_flux:{phbv_flux_model}")
    print(f"PHBV_model_accumulation:{PHBV_model_accumulation}")
    print(f"Biomass_model_flux:{biomass_flux}")

    results.append({
    "Row": row_id,

    # original experiment columns
    "Biomass_mgL": biomass_mgL,
    "COD_gL_fed": COD_gL_fed,
    "Substrate_type": substrate_type,
    "Time_h": t_hours,
    "PHB_mgL": phb_mgL,
    "PHV_mgL": phv_mgL,

    # biomass
    "biomass_initial_gL": INITIAL_BIOMASS,
    "biomass_final_gL": biomass_final_gL,
    "biomass_eff_gL": X_eff,

    # experimental fluxes
    "PHB_exp_flux": q_phb,
    "PHV_exp_flux": q_phv,
    "PHBV_exp_flux": q_phbv,
    "Substrate_exp_flux": q_sub,
    "sub_rxn_id": sub_rxn_id,

    # model outputs
    #"PHB_model_flux": phb_flux_model,
    #"PHV_model_flux": sol.fluxes.get("PHVS_syn", np.nan) if sol.status == "optimal" else np.nan,
    "PHBV_model_flux": sol.fluxes.get("PHBVS_syn", np.nan) if sol.status == "optimal" else np.nan,
    "PHBV_model_accumulation": sol.fluxes.get("DM_PHBV_c", np.nan) if sol.status == "optimal" else np.nan,
    "3HV_model_flux": sol.fluxes.get("3hvcoa_syn", np.nan) if sol.status == "optimal" else np.nan,
    "3HB_model_flux": sol.fluxes.get("AACOAR_syn", np.nan) if sol.status == "optimal" else np.nan,
    "Biomass_model_flux": biomass_flux,
    "Substrate_model_flux": sub_flux_model,
    })


# -------------------------
# SAVE SUMMARY CSV and MERGE WITH ORIGINAL ROWS
# -------------------------
results_df = pd.DataFrame(results)
results_df.to_csv("FBA_PHBV_results_summary.csv", index=False)

df_merged = pd.concat([df.reset_index(drop=True), results_df.reset_index(drop=True)], axis=1)
df_merged.to_csv(phbv_model_dir/"Buitron_dataset_augmented_with_FBA_fluxes_PHBV_before_tfa.csv", index=False)

print("\nSaved: FBA_PHBV_results_summary.csv and Buitron_dataset_augmented_with_FBA_fluxes_PHBV.csv")

Loaded dataset shape: (32, 23)
Using INITIAL_BIOMASS (mean inoculum) = 0.094000 gDW/L
Model reaction presence: EX_ac_e=True, EX_hxa_e=True, EX_fum_e=True, EX_lac__L_e=True, EX_ppa_e=True, EX_but_e=True, EX_succ_e=True, PHBS_syn=True, BIOMASS__1=True, PHBVS_syn=True

=== Row 1 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 2.467, X_eff = 1.2805
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.5304604174858837, upper = -0.5304604174858837
PHB_exp_flux  : 0.0064745784259419015
PHV_exp_flux  : 0.0007780589103306411
PHBV_exp_flux : 0.007252637336272543
3HV_model_flux: 0.050236250077610144
3HB_model_flux: 0.20094500031044055
PHBV_model_flux:0.25118125038805067
PHBV_model_accumulation:0.25118125038805067
Biomass_model_flux:0.0

=== Row 2 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.15, X_eff = 0.622
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0920491392133023, upper = -1.0920491392133023
PHB_exp_flux  : 0.010828722051895612
PHV_exp_flux  : 0.0011976517782091285
PHBV_exp_flux : 0.01202637383010474
3HV_model_flux: 0.10343939213599658
3HB_model_flux: 0.4137575685439869
PHBV_model_flux:0.5171969606799836
PHBV_model_accumulation:0.5171969606799836
Biomass_model_flux:0.0

=== Row 3 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.133, X_eff = 0.6135
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.1071794043857768, upper = -1.1071794043857768
PHB_exp_flux  : 0.008529027122306248
PHV_exp_flux  : 0.0011762576025314039
PHBV_exp_flux : 0.009705284724837651
3HV_model_flux: 0.1048727856786529
3HB_model_flux: 0.4194911427146115
PHBV_model_flux:0.5243639283932644
PHBV_model_accumulation:0.5243639283932644
Biomass_model_flux:0.0

=== Row 4 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.683, X_eff = 0.8885000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.764495852099802, upper = -0.764495852099802
PHB_exp_flux  : 0.010017100504726631
PHV_exp_flux  : 0.0004421630827849948
PHBV_exp_flux : 0.010459263587511626
3HV_model_flux: 0.07240802809366545
3HB_model_flux: 0.2896321123746618
PHBV_model_flux:0.3620401404683273
PHBV_model_accumulation:0.3620401404683273
Biomass_model_flux:0.0

=== Row 5 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.667, X_eff = 0.8805000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.7714418677917934, upper = -0.7714418677917934
PHB_exp_flux  : 0.010254480144738058
PHV_exp_flux  : 0.0004839923683478368
PHBV_exp_flux : 0.010738472513085896
3HV_model_flux: 0.07306607168553866
3HB_model_flux: 0.2922642867421546
PHBV_model_flux:0.3653303584276932
PHBV_model_accumulation:0.3653303584276932
Biomass_model_flux:0.0

=== Row 6 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 2.0, X_eff = 1.047
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.6487627168965369, upper = -0.6487627168965369
PHB_exp_flux  : 0.007552031274294218
PHV_exp_flux  : 0.000620077301698325
PHBV_exp_flux : 0.008172108575992543
3HV_model_flux: 0.06144383633756683
3HB_model_flux: 0.24577534535026732
PHBV_model_flux:0.3072191816878341
PHBV_model_accumulation:0.3072191816878341
Biomass_model_flux:0.0

=== Row 7 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 2.067, X_eff = 1.0805
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.6286483707456493, upper = -0.6286483707456493
PHB_exp_flux  : 0.007489175625697262
PHV_exp_flux  : 0.0006370575269571624
PHBV_exp_flux : 0.008126233152654424
3HV_model_flux: 0.05953826670221965
3HB_model_flux: 0.2381530668088786
PHBV_model_flux:0.29769133351109817
PHBV_model_accumulation:0.29769133351109817
Biomass_model_flux:0.0

=== Row 8 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 2.133, X_eff = 1.1135
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.6100175703553427, upper = -0.6100175703553427
PHB_exp_flux  : 0.007682320220827547
PHV_exp_flux  : 0.0007332915813103306
PHBV_exp_flux : 0.008415611802137877
3HV_model_flux: 0.057773243507348034
3HB_model_flux: 0.23109297402939208
PHBV_model_flux:0.2888662175367401
PHBV_model_accumulation:0.2888662175367401
Biomass_model_flux:0.0

=== Row 9 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 2.083, X_eff = 1.0885
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.6240280795504585, upper = -0.6240280795504585
PHB_exp_flux  : 0.007602382910840251
PHV_exp_flux  : 0.0007960130892997305
PHBV_exp_flux : 0.00839839600013998
3HV_model_flux: 0.059100554904780514
3HB_model_flux: 0.23640221961912206
PHBV_model_flux:0.29550277452390256
PHBV_model_accumulation:0.29550277452390256
Biomass_model_flux:0.0

=== Row 10 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.313, X_eff = 0.7035
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.6092266396367545, upper = -1.6092266396367545
PHB_exp_flux  : 0.030072964817845067
PHV_exp_flux  : 0.002464861797841327
PHBV_exp_flux : 0.0325378266156864
3HV_model_flux: 0.15243515533400911
3HB_model_flux: 0.6097406213360365
PHBV_model_flux:0.7621757766700455
PHBV_model_accumulation:0.7621757766700455
Biomass_model_flux:0.0

=== Row 11 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.237, X_eff = 0.6655000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.7011133598564339, upper = -1.7011133598564339
PHB_exp_flux  : 0.02402460119162022
PHV_exp_flux  : 0.001980259968195107
PHBV_exp_flux : 0.026004861159815325
3HV_model_flux: 0.16114021303903076
3HB_model_flux: 0.644560852156123
PHBV_model_flux:0.8057010651951537
PHBV_model_accumulation:0.8057010651951537
Biomass_model_flux:0.0

=== Row 12 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.333, X_eff = 0.7135
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.3686211517657156, upper = -1.3686211517657156
PHB_exp_flux  : 0.0204866826377232
PHV_exp_flux  : 0.0011242640576227937
PHBV_exp_flux : 0.021610946695345995
3HV_model_flux: 0.1296409512199096
3HB_model_flux: 0.5185638048796383
PHBV_model_flux:0.6482047560995478
PHBV_model_accumulation:0.6482047560995478
Biomass_model_flux:0.0

=== Row 13 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.383, X_eff = 0.7385
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.3222900362692462, upper = -1.3222900362692462
PHB_exp_flux  : 0.02053614072102995
PHV_exp_flux  : 0.0011270609775153137
PHBV_exp_flux : 0.021663201698545263
3HV_model_flux: 0.12525168764656072
3HB_model_flux: 0.5010067505862429
PHBV_model_flux:0.6262584382328035
PHBV_model_accumulation:0.6262584382328035
Biomass_model_flux:0.0

=== Row 14 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.667, X_eff = 0.8805000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.109041671533036, upper = -1.109041671533036
PHB_exp_flux  : 0.027797311693056707
PHV_exp_flux  : 0.0011331754913222057
PHBV_exp_flux : 0.028930487184378913
3HV_model_flux: 0.10504921098733971
3HB_model_flux: 0.42019684394935813
PHBV_model_flux:0.5252460549366976
PHBV_model_accumulation:0.5252460549366976
Biomass_model_flux:0.0

=== Row 15 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.733, X_eff = 0.9135000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0689777687847162, upper = -1.0689777687847162
PHB_exp_flux  : 0.02786449383281781
PHV_exp_flux  : 0.001135519332648295
PHBV_exp_flux : 0.029000013165466104
3HV_model_flux: 0.1012536833585517
3HB_model_flux: 0.4050147334342061
PHBV_model_flux:0.5062684167927576
PHBV_model_accumulation:0.5062684167927576
Biomass_model_flux:0.0

=== Row 16 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.683, X_eff = 0.8885000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0990559277263232, upper = -1.0990559277263232
PHB_exp_flux  : 0.021111162005470415
PHV_exp_flux  : 0.0012763711870647362
PHBV_exp_flux : 0.022387533192535152
3HV_model_flux: 0.10410319315302058
3HB_model_flux: 0.4164127726120823
PHBV_model_flux:0.5205159657651028
PHBV_model_accumulation:0.5205159657651028
Biomass_model_flux:0.0

=== Row 17 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.717, X_eff = 0.9055000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0784220781721017, upper = -1.0784220781721017
PHB_exp_flux  : 0.021125475667646894
PHV_exp_flux  : 0.0012765373618655587
PHBV_exp_flux : 0.022402013029512453
3HV_model_flux: 0.10214840740577832
3HB_model_flux: 0.40859362962311335
PHBV_model_flux:0.5107420370288916
PHBV_model_accumulation:0.5107420370288916
Biomass_model_flux:0.0

=== Row 18 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.417, X_eff = 0.7555000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0427920162639694, upper = -1.0427920162639694
PHB_exp_flux  : 0.05096989005689543
PHV_exp_flux  : 0.0019555179273510657
PHBV_exp_flux : 0.0529254079842465
3HV_model_flux: 0.09877292785658691
3HB_model_flux: 0.3950917114263475
PHBV_model_flux:0.49386463928293434
PHBV_model_accumulation:0.49386463928293434
Biomass_model_flux:0.0

=== Row 19 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.367, X_eff = 0.7305
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.0784796280457616, upper = -1.0784796280457616
PHB_exp_flux  : 0.050854959347867996
PHV_exp_flux  : 0.0019502796355378182
PHBV_exp_flux : 0.05280523898340581
3HV_model_flux: 0.10215385949907249
3HB_model_flux: 0.4086154379962899
PHBV_model_flux:0.5107692974953623
PHBV_model_accumulation:0.5107692974953623
Biomass_model_flux:0.0

=== Row 20 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.417, X_eff = 0.7555000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.1275006114226673, upper = -1.1275006114226673
PHB_exp_flux  : 0.04437313277139051
PHV_exp_flux  : 0.001707635373179804
PHBV_exp_flux : 0.046080768144570315
3HV_model_flux: 0.1067979526610952
3HB_model_flux: 0.4271918106443808
PHBV_model_flux:0.5339897633054759
PHBV_model_accumulation:0.5339897633054759
Biomass_model_flux:0.0

=== Row 21 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.467, X_eff = 0.7805000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.091385921755061, upper = -1.091385921755061
PHB_exp_flux  : 0.044468529581680065
PHV_exp_flux  : 0.0017115911898674826
PHBV_exp_flux : 0.046180120771547546
3HV_model_flux: 0.10337656100837458
3HB_model_flux: 0.4135062440334983
PHBV_model_flux:0.5168828050418728
PHBV_model_accumulation:0.5168828050418728
Biomass_model_flux:0.0

=== Row 22 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.433, X_eff = 0.7635000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.202397983661306, upper = -1.202397983661306
PHB_exp_flux  : 0.047745236898615616
PHV_exp_flux  : 0.0019386617453220432
PHBV_exp_flux : 0.04968389864393766
3HV_model_flux: 0.11389349318896626
3HB_model_flux: 0.45557397275586503
PHBV_model_flux:0.5694674659448312
PHBV_model_accumulation:0.5694674659448312
Biomass_model_flux:0.0

=== Row 23 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.4, X_eff = 0.747
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.228956975268283, upper = -1.228956975268283
PHB_exp_flux  : 0.04766481948465697
PHV_exp_flux  : 0.0019369141382564632
PHBV_exp_flux : 0.04960173362291344
3HV_model_flux: 0.11640960818331064
3HB_model_flux: 0.46563843273324246
PHBV_model_flux:0.5820480409165529
PHBV_model_accumulation:0.5820480409165529
Biomass_model_flux:0.0

=== Row 24 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.333, X_eff = 0.7135
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.472234278509561, upper = -1.472234278509561
PHB_exp_flux  : 0.04419202207699788
PHV_exp_flux  : 0.002210615189826401
PHBV_exp_flux : 0.04640263726682428
3HV_model_flux: 0.13945693164827483
3HB_model_flux: 0.5578277265930994
PHBV_model_flux:0.6972846582413741
PHBV_model_accumulation:0.6972846582413741
Biomass_model_flux:0.0

=== Row 25 / 32 ===
  Time (h) = 72.00, biomass_final_gL = 1.35, X_eff = 0.7220000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.4549018804938665, upper = -1.4549018804938665
PHB_exp_flux  : 0.04421754099651413
PHV_exp_flux  : 0.0022114890263416733
PHBV_exp_flux : 0.046429030022855804
3HV_model_flux: 0.13781491499415627
3HB_model_flux: 0.5512596599766252
PHBV_model_flux:0.6890745749707813
PHBV_model_accumulation:0.6890745749707813
Biomass_model_flux:0.0

=== Row 26 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.538, X_eff = 0.8160000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.8697407756674532, upper = -0.8697407756674532
PHB_exp_flux  : 0.01877066233470132
PHV_exp_flux  : 6.120106852169553e-05
PHBV_exp_flux : 0.018831863403223015
3HV_model_flux: 0.08237859980007402
3HB_model_flux: 0.32951439920029535
PHBV_model_flux:0.41189299900036913
PHBV_model_accumulation:0.41189299900036913
Biomass_model_flux:0.0

=== Row 27 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.463, X_eff = 0.7785000000000001
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.9116358033970992, upper = -0.9116358033970992
PHB_exp_flux  : 0.0197271138593897
PHV_exp_flux  : 6.949485494306852e-05
PHBV_exp_flux : 0.019796608714332767
3HV_model_flux: 0.08634760242709395
3HB_model_flux: 0.3453904097083758
PHBV_model_flux:0.43173801213546975
PHBV_model_accumulation:0.43173801213546975
Biomass_model_flux:0.0

=== Row 28 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.313, X_eff = 0.7035
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.1198711702735307, upper = -1.1198711702735307
PHB_exp_flux  : 0.018813738615890647
PHV_exp_flux  : 7.926995541857707e-05
PHBV_exp_flux : 0.018893008571309225
3HV_model_flux: 0.10607516349959813
3HB_model_flux: 0.4243006539983925
PHBV_model_flux:0.5303758174979906
PHBV_model_accumulation:0.5303758174979906
Biomass_model_flux:0.0

=== Row 29 / 32 ===
  Time (h) = 120.00, biomass_final_gL = 1.212, X_eff = 0.653
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.2064768273926936, upper = -1.2064768273926936
PHB_exp_flux  : 0.01872544131438679
PHV_exp_flux  : 8.54003271622802e-05
PHBV_exp_flux : 0.01881084164154907
3HV_model_flux: 0.11427990996351874
3HB_model_flux: 0.45711963985407494
PHBV_model_flux:0.5713995498175936
PHBV_model_accumulation:0.5713995498175936
Biomass_model_flux:0.0

=== Row 30 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.513, X_eff = 0.8035
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.7951089408181319, upper = -0.7951089408181319
PHB_exp_flux  : 0.01787540460099468
PHV_exp_flux  : nan
PHBV_exp_flux : nan
3HV_model_flux: 0.07530821544592863
3HB_model_flux: 0.3012328617837145
PHBV_model_flux:0.37654107722964314
PHBV_model_accumulation:0.37654107722964314
Biomass_model_flux:0.0

=== Row 31 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.575, X_eff = 0.8345
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -0.7655722396014008, upper = -0.7655722396014008
PHB_exp_flux  : 0.016751257541767105
PHV_exp_flux  : nan
PHBV_exp_flux : nan
3HV_model_flux: 0.07251000164644852
3HB_model_flux: 0.2900400065857941
PHBV_model_flux:0.36255000823224265
PHBV_model_accumulation:0.36255000823224265
Biomass_model_flux:0.0

=== Row 32 / 32 ===
  Time (h) = 96.00, biomass_final_gL = 1.513, X_eff = 0.8035
 Calculated v_phbv_max (mmol/gDW/h) = 0.399521
 v_phbv_max (mmol/gDW/h) = 1.000000
EX_ac_e: lower = -1.1329272472797214, upper = -1.1329272472797214
PHB_exp_flux  : 0.018939668022170446
PHV_exp_flux  : nan
PHBV_exp_flux : nan
3HV_model_flux: 0.10731205500544783
3HB_model_flux: 0.4292482200217912
PHBV_model_flux:0.5365602750272389
PHBV_model_accumulation:0.5365602750272389
Biomass_model_flux:0.0

Saved: FBA_PHBV_results_summary.csv and Buitron_dataset_augmented_with_FBA_fluxes_PHBV.csv

# Multiple points fba and tfa (version 2)

In [ ]:
import cobra
import pytfa
import pandas as pd
import numpy as np
import os
from pathlib import Path
from cobra.flux_analysis import flux_variability_analysis
from pytfa.io import read_lexicon, annotate_from_lexicon, read_compartment_data, apply_compartment_data

# ===============================
# USER INPUT
# ===============================
CSV_PATH = "/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/data/Buitron2025_dataset.csv"
INITIAL_BIOMASS = 0.094     # gDW/L
FALLBACK_TIME_H = 72.0

# ===============================
# CONSTANTS
# ===============================
PHB_MW = 86.0
ACETATE_MW = 59.04
COD_TO_ACETATE_RATIO = 1.066

# ===============================
# LOAD DATA
# ===============================
df = pd.read_csv(CSV_PATH)
df = df.iloc[1:35].drop(index=[15, 16]).reset_index(drop=True)

# ===============================
# MEDIUM (unchanged)
# ===============================
medium_ub = {
    "EX_ac_e": 0.2477,
    "EX_nh4_e": 0.14188,
    "EX_pi_e": 0.03733,
    "EX_o2_e": 0,
    "EX_co2_e": 0,
    **{f"EX_photon{x}_e": 10 for x in range(410, 700, 20)}
}

# ===============================
# PHOTON SCALING
# ===============================
def scale_photons(model, illum, ref=1000):
    for rxn in model.reactions:
        if rxn.id.startswith("EX_photon"):
            rxn.lower_bound = 0

    if pd.isna(illum):
        return

    s = str(illum).lower()
    if s in ["continuous", "light", "on"]:
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -ub
        return

    try:
        val = float("".join(c for c in s if c.isdigit() or c == "."))
        scale = val / ref
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -scale * ub
    except:
        pass

# ===============================
# SOLVER SETTINGS
# ===============================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True

# ===============================
# LOAD TFA METADATA
# ===============================
lexicon = read_lexicon(str(rp_lex_mat_path))
comp_data = read_compartment_data(str(rp_comp_mat_path))

# ===============================
# OUTPUT
# ===============================
results = []

# ===============================
# MAIN LOOP
# ===============================
for i, row in df.iterrows():
    print(f"\n--- ROW {i+1} ---")

    # ---------------------------
    # BUILD COBRA MODEL
    # ---------------------------
    m = model_phbv2.copy() # DEFINE MODEL

    for ex in m.exchanges:
        ex.lower_bound = 0

    for rid, ub in medium_ub.items():
        if rid in m.reactions:
            m.reactions.get_by_id(rid).lower_bound = -ub

    # ---------------------------
    # TIME & BIOMASS
    # ---------------------------
    t_h = row.get("Time (d)", np.nan)
    t_h = FALLBACK_TIME_H if pd.isna(t_h) else float(t_h) * 24

    biomass_final = row.get("Biomass (mg dw/L)", np.nan)
    biomass_final = np.nan if pd.isna(biomass_final) else biomass_final / 1000
    X_eff = (INITIAL_BIOMASS + biomass_final) / 2 if not pd.isna(biomass_final) else np.nan

    # ---------------------------
    # SUBSTRATE UPTAKE
    # ---------------------------
    COD = row.get("g substrate COD/L", np.nan)
    if not pd.isna(COD) and X_eff > 0:
        mmol_L = (COD * 1000 / COD_TO_ACETATE_RATIO) / ACETATE_MW
        q_sub = mmol_L / (X_eff * t_h)
        if "EX_ac_e" in m.reactions:
            rxn = m.reactions.get_by_id("EX_ac_e")
            rxn.lower_bound = -q_sub
            rxn.upper_bound = -q_sub

    # ---------------------------
    # PHOTONS
    # ---------------------------
    scale_photons(m, row.get("Illumination", np.nan))

    # ---------------------------
    # PHB CAP & OBJECTIVE
    # ---------------------------
    phb_rxn_id = 'PHBVS_syn'
    mu_max = 0.08 # growth rate
    f = 0.50       # fraction of the maximum growth-associated carbon/flux that is diverted to PHB synthesis

    v_phbv_max = 1 #mu_max * f * 1000 / PHV_MW
    v_phbv_max_eff = mu_max * f * 1000 / PHV_MW + PHB_MW
    print(f" Calculated v_phbv_max (mmol/gDW/h) = {v_phbv_max_eff:.6f}")
    print(f" v_phbv_max (mmol/gDW/h) = {v_phbv_max:.6f}")

    if r_phb_exists and phb_rxn_id in m.reactions:
        phb_rxn = m.reactions.get_by_id(phb_rxn_id)
        phb_rxn.lower_bound = 0.0
        phb_rxn.upper_bound = v_phbv_max
        m.objective = phb_rxn # define OBJECTIVE
    else:
        print(f"WARNING: PHBS_syn not found in model for row {row_id}")

    # ===========================
    # FBA
    # ===========================
    fba_sol = m.optimize()

    # ===========================
    # TFA (ROW-SPECIFIC)
    # ===========================
    mytfa = pytfa.ThermoModel(thermo_data, m)
    annotate_from_lexicon(mytfa, lexicon)
    apply_compartment_data(mytfa, comp_data)

    mytfa.objective = "PHBS_syn"
    apply_solver_settings(mytfa)

    mytfa.prepare()
    tfa_sol = mytfa.optimize()

    # ===========================
    # STORE RESULTS
    # ===========================
    results.append({
        "row": i+1,
        "PHB_FBA": fba_sol.fluxes.get("PHBS_syn", np.nan) if fba_sol.status == "optimal" else np.nan,
        "PHB_TFA": tfa_sol.fluxes.get("PHBS_syn", np.nan) if tfa_sol.status == "optimal" else np.nan,
        "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan) if fba_sol.status == "optimal" else np.nan,
        "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan) if tfa_sol.status == "optimal" else np.nan,
        "status_FBA": fba_sol.status,
        "status_TFA": tfa_sol.status
    })

# ===============================
# SAVE
# ===============================
results_df = pd.DataFrame(results)
results_df.to_csv(project_root_palustris / "FBA_vs_TFA_PHB_results.csv", index=False)

print("\nDONE: FBA_vs_TFA_PHB_results.csv")

--- ROW 1 ---
 Calculated v_phbv_max (mmol/gDW/h) = 86.399521
 v_phbv_max (mmol/gDW/h) = 1.000000

2026-01-13 17:26:16,134 - thermomodel_None - INFO - # Model initialized with units kcal/mol and temperature 298.15 K
INFO:thermomodel_None:# Model initialized with units kcal/mol and temperature 298.15 K
2026-01-13 17:26:16,141 - thermomodel_None - WARNING - gam6p_c  not found in annotations
WARNING:thermomodel_None:gam6p_c  not found in annotations
2026-01-13 17:26:16,146 - thermomodel_None - WARNING - cgly_c  not found in annotations
WARNING:thermomodel_None:cgly_c  not found in annotations
2026-01-13 17:26:16,150 - thermomodel_None - WARNING - achms_c  not found in annotations
WARNING:thermomodel_None:achms_c  not found in annotations
2026-01-13 17:26:16,155 - thermomodel_None - WARNING - pcox_u  not found in annotations
WARNING:thermomodel_None:pcox_u  not found in annotations
2026-01-13 17:26:16,160 - thermomodel_None - WARNING - octe9ACP_c  not found in annotations
WARNING:thermomodel_None:octe9ACP_c  not found in annotations
2026-01-13 17:26:16,163 - thermomodel_None - WARNING - fdp_c  not found in annotations
WARNING:thermomodel_None:fdp_c  not found in annotations
2026-01-13 17:26:16,168 - thermomodel_None - WARNING - 5caiz_c  not found in annotations
WARNING:thermomodel_None:5caiz_c  not found in annotations
2026-01-13 17:26:16,170 - thermomodel_None - WARNING - pep_c  not found in annotations
WARNING:thermomodel_None:pep_c  not found in annotations
2026-01-13 17:26:16,174 - thermomodel_None - WARNING - hgbam_c  not found in annotations
WARNING:thermomodel_None:hgbam_c  not found in annotations
2026-01-13 17:26:16,177 - thermomodel_None - WARNING - nac_c  not found in annotations
WARNING:thermomodel_None:nac_c  not found in annotations
2026-01-13 17:26:16,180 - thermomodel_None - WARNING - r3mmal_c  not found in annotations
WARNING:thermomodel_None:r3mmal_c  not found in annotations
2026-01-13 17:26:16,184 - thermomodel_None - WARNING - leu__L_c  not found in annotations
WARNING:thermomodel_None:leu__L_c  not found in annotations
2026-01-13 17:26:16,186 - thermomodel_None - WARNING - ahcys_c  not found in annotations
WARNING:thermomodel_None:ahcys_c  not found in annotations
2026-01-13 17:26:16,191 - thermomodel_None - WARNING - ru5p__D_c  not found in annotations
WARNING:thermomodel_None:ru5p__D_c  not found in annotations
2026-01-13 17:26:16,195 - thermomodel_None - WARNING - 14dhncoa_c  not found in annotations
WARNING:thermomodel_None:14dhncoa_c  not found in annotations
2026-01-13 17:26:16,197 - thermomodel_None - WARNING - h2o_cx_c  not found in annotations
WARNING:thermomodel_None:h2o_cx_c  not found in annotations
2026-01-13 17:26:16,200 - thermomodel_None - WARNING - h2s_c  not found in annotations
WARNING:thermomodel_None:h2s_c  not found in annotations
2026-01-13 17:26:16,203 - thermomodel_None - WARNING - orot_c  not found in annotations
WARNING:thermomodel_None:orot_c  not found in annotations
2026-01-13 17:26:16,206 - thermomodel_None - WARNING - g1p_c  not found in annotations
WARNING:thermomodel_None:g1p_c  not found in annotations
2026-01-13 17:26:16,208 - thermomodel_None - WARNING - 3hdecACP_c  not found in annotations
WARNING:thermomodel_None:3hdecACP_c  not found in annotations
2026-01-13 17:26:16,209 - thermomodel_None - WARNING - na1_c  not found in annotations
WARNING:thermomodel_None:na1_c  not found in annotations
2026-01-13 17:26:16,210 - thermomodel_None - WARNING - 2pglyc_c  not found in annotations
WARNING:thermomodel_None:2pglyc_c  not found in annotations
2026-01-13 17:26:16,213 - thermomodel_None - WARNING - ala_B_c  not found in annotations
WARNING:thermomodel_None:ala_B_c  not found in annotations
2026-01-13 17:26:16,218 - thermomodel_None - WARNING - glyc3p_c  not found in annotations
WARNING:thermomodel_None:glyc3p_c  not found in annotations
2026-01-13 17:26:16,221 - thermomodel_None - WARNING - pqh2_um_p  not found in annotations
WARNING:thermomodel_None:pqh2_um_p  not found in annotations
2026-01-13 17:26:16,223 - thermomodel_None - WARNING - 26dap_LL_c  not found in annotations
WARNING:thermomodel_None:26dap_LL_c  not found in annotations
2026-01-13 17:26:16,226 - thermomodel_None - WARNING - ddcaACP_c  not found in annotations
WARNING:thermomodel_None:ddcaACP_c  not found in annotations
2026-01-13 17:26:16,228 - thermomodel_None - WARNING - 2pglyc_cx_c  not found in annotations
WARNING:thermomodel_None:2pglyc_cx_c  not found in annotations
2026-01-13 17:26:16,229 - thermomodel_None - WARNING - trdox_c  not found in annotations
WARNING:thermomodel_None:trdox_c  not found in annotations
2026-01-13 17:26:16,231 - thermomodel_None - WARNING - 3oddecACP_c  not found in annotations
WARNING:thermomodel_None:3oddecACP_c  not found in annotations
2026-01-13 17:26:16,234 - thermomodel_None - WARNING - glu__D_c  not found in annotations
WARNING:thermomodel_None:glu__D_c  not found in annotations
2026-01-13 17:26:16,236 - thermomodel_None - WARNING - h_cx_c  not found in annotations
WARNING:thermomodel_None:h_cx_c  not found in annotations
2026-01-13 17:26:16,238 - thermomodel_None - WARNING - dutp_c  not found in annotations
WARNING:thermomodel_None:dutp_c  not found in annotations
2026-01-13 17:26:16,239 - thermomodel_None - WARNING - paps_c  not found in annotations
WARNING:thermomodel_None:paps_c  not found in annotations
2026-01-13 17:26:16,242 - thermomodel_None - WARNING - mg2_c  not found in annotations
WARNING:thermomodel_None:mg2_c  not found in annotations
2026-01-13 17:26:16,244 - thermomodel_None - WARNING - hdeACP_c  not found in annotations
WARNING:thermomodel_None:hdeACP_c  not found in annotations
2026-01-13 17:26:16,246 - thermomodel_None - WARNING - o2_c  not found in annotations
WARNING:thermomodel_None:o2_c  not found in annotations
2026-01-13 17:26:16,249 - thermomodel_None - WARNING - anth_c  not found in annotations
WARNING:thermomodel_None:anth_c  not found in annotations
2026-01-13 17:26:16,251 - thermomodel_None - WARNING - dhpt_c  not found in annotations
WARNING:thermomodel_None:dhpt_c  not found in annotations
2026-01-13 17:26:16,253 - thermomodel_None - WARNING - thex2eACP_c  not found in annotations
WARNING:thermomodel_None:thex2eACP_c  not found in annotations
2026-01-13 17:26:16,255 - thermomodel_None - WARNING - fmn_c  not found in annotations
WARNING:thermomodel_None:fmn_c  not found in annotations
2026-01-13 17:26:16,257 - thermomodel_None - WARNING - pppi_c  not found in annotations
WARNING:thermomodel_None:pppi_c  not found in annotations
2026-01-13 17:26:16,259 - thermomodel_None - WARNING - udp_c  not found in annotations
WARNING:thermomodel_None:udp_c  not found in annotations
2026-01-13 17:26:16,261 - thermomodel_None - WARNING - cit_c  not found in annotations
WARNING:thermomodel_None:cit_c  not found in annotations
2026-01-13 17:26:16,263 - thermomodel_None - WARNING - acACP_c  not found in annotations
WARNING:thermomodel_None:acACP_c  not found in annotations
2026-01-13 17:26:16,266 - thermomodel_None - WARNING - uama_c  not found in annotations
WARNING:thermomodel_None:uama_c  not found in annotations
2026-01-13 17:26:16,269 - thermomodel_None - WARNING - eig3p_c  not found in annotations
WARNING:thermomodel_None:eig3p_c  not found in annotations
2026-01-13 17:26:16,273 - thermomodel_None - WARNING - 3c4mop_c  not found in annotations
WARNING:thermomodel_None:3c4mop_c  not found in annotations
2026-01-13 17:26:16,276 - thermomodel_None - WARNING - lys__L_c  not found in annotations
WARNING:thermomodel_None:lys__L_c  not found in annotations
2026-01-13 17:26:16,279 - thermomodel_None - WARNING - 13dpg_c  not found in annotations
WARNING:thermomodel_None:13dpg_c  not found in annotations
2026-01-13 17:26:16,282 - thermomodel_None - WARNING - gmp_c  not found in annotations
WARNING:thermomodel_None:gmp_c  not found in annotations
2026-01-13 17:26:16,284 - thermomodel_None - WARNING - utp_c  not found in annotations
WARNING:thermomodel_None:utp_c  not found in annotations
2026-01-13 17:26:16,288 - thermomodel_None - WARNING - trdrd_c  not found in annotations
WARNING:thermomodel_None:trdrd_c  not found in annotations
2026-01-13 17:26:16,290 - thermomodel_None - WARNING - so4_c  not found in annotations
WARNING:thermomodel_None:so4_c  not found in annotations
2026-01-13 17:26:16,295 - thermomodel_None - WARNING - 5apru_c  not found in annotations
WARNING:thermomodel_None:5apru_c  not found in annotations
2026-01-13 17:26:16,297 - thermomodel_None - WARNING - hmppp9_c  not found in annotations
WARNING:thermomodel_None:hmppp9_c  not found in annotations
2026-01-13 17:26:16,300 - thermomodel_None - WARNING - pydx5p_c  not found in annotations
WARNING:thermomodel_None:pydx5p_c  not found in annotations
2026-01-13 17:26:16,304 - thermomodel_None - WARNING - 2dhp_c  not found in annotations
WARNING:thermomodel_None:2dhp_c  not found in annotations
2026-01-13 17:26:16,308 - thermomodel_None - WARNING - ade_c  not found in annotations
WARNING:thermomodel_None:ade_c  not found in annotations
2026-01-13 17:26:16,312 - thermomodel_None - WARNING - asp__L_c  not found in annotations
WARNING:thermomodel_None:asp__L_c  not found in annotations
2026-01-13 17:26:16,316 - thermomodel_None - WARNING - 2sephchc_c  not found in annotations
WARNING:thermomodel_None:2sephchc_c  not found in annotations
2026-01-13 17:26:16,322 - thermomodel_None - WARNING - acg5p_c  not found in annotations
WARNING:thermomodel_None:acg5p_c  not found in annotations
2026-01-13 17:26:16,327 - thermomodel_None - WARNING - gdp_c  not found in annotations
WARNING:thermomodel_None:gdp_c  not found in annotations
2026-01-13 17:26:16,331 - thermomodel_None - WARNING - hgbyr_c  not found in annotations
WARNING:thermomodel_None:hgbyr_c  not found in annotations
2026-01-13 17:26:16,333 - thermomodel_None - WARNING - palmACP_c  not found in annotations
WARNING:thermomodel_None:palmACP_c  not found in annotations
2026-01-13 17:26:16,337 - thermomodel_None - WARNING - pser__L_c  not found in annotations
WARNING:thermomodel_None:pser__L_c  not found in annotations
2026-01-13 17:26:16,340 - thermomodel_None - WARNING - ocACP_c  not found in annotations
WARNING:thermomodel_None:ocACP_c  not found in annotations
2026-01-13 17:26:16,342 - thermomodel_None - WARNING - dttp_c  not found in annotations
WARNING:thermomodel_None:dttp_c  not found in annotations
2026-01-13 17:26:16,345 - thermomodel_None - WARNING - 6pgc_c  not found in annotations
WARNING:thermomodel_None:6pgc_c  not found in annotations
2026-01-13 17:26:16,347 - thermomodel_None - WARNING - gcald_c  not found in annotations
WARNING:thermomodel_None:gcald_c  not found in annotations
2026-01-13 17:26:16,350 - thermomodel_None - WARNING - 2p4c2me_c  not found in annotations
WARNING:thermomodel_None:2p4c2me_c  not found in annotations
2026-01-13 17:26:16,352 - thermomodel_None - WARNING - cmp_c  not found in annotations
WARNING:thermomodel_None:cmp_c  not found in annotations
2026-01-13 17:26:16,355 - thermomodel_None - WARNING - bm_pro_c  not found in annotations
WARNING:thermomodel_None:bm_pro_c  not found in annotations
2026-01-13 17:26:16,357 - thermomodel_None - WARNING - pnto__R_c  not found in annotations
WARNING:thermomodel_None:pnto__R_c  not found in annotations
2026-01-13 17:26:16,359 - thermomodel_None - WARNING - dump_c  not found in annotations
WARNING:thermomodel_None:dump_c  not found in annotations
2026-01-13 17:26:16,360 - thermomodel_None - WARNING - omppp9_c  not found in annotations
WARNING:thermomodel_None:omppp9_c  not found in annotations
2026-01-13 17:26:16,362 - thermomodel_None - WARNING - 23dhmp_c  not found in annotations
WARNING:thermomodel_None:23dhmp_c  not found in annotations
2026-01-13 17:26:16,365 - thermomodel_None - WARNING - gtp_c  not found in annotations
WARNING:thermomodel_None:gtp_c  not found in annotations
2026-01-13 17:26:16,367 - thermomodel_None - WARNING - 4h2oglt_c  not found in annotations
WARNING:thermomodel_None:4h2oglt_c  not found in annotations
2026-01-13 17:26:16,369 - thermomodel_None - WARNING - prfp_c  not found in annotations
WARNING:thermomodel_None:prfp_c  not found in annotations
2026-01-13 17:26:16,371 - thermomodel_None - WARNING - man1p_c  not found in annotations
WARNING:thermomodel_None:man1p_c  not found in annotations
2026-01-13 17:26:16,372 - thermomodel_None - WARNING - dxyl5p_c  not found in annotations
WARNING:thermomodel_None:dxyl5p_c  not found in annotations
2026-01-13 17:26:16,374 - thermomodel_None - WARNING - 3hddecACP_c  not found in annotations
WARNING:thermomodel_None:3hddecACP_c  not found in annotations
2026-01-13 17:26:16,375 - thermomodel_None - WARNING - cu2_c  not found in annotations
WARNING:thermomodel_None:cu2_c  not found in annotations
2026-01-13 17:26:16,377 - thermomodel_None - WARNING - malACP_c  not found in annotations
WARNING:thermomodel_None:malACP_c  not found in annotations
2026-01-13 17:26:16,379 - thermomodel_None - WARNING - 2mahmp_c  not found in annotations
WARNING:thermomodel_None:2mahmp_c  not found in annotations
2026-01-13 17:26:16,382 - thermomodel_None - WARNING - phpyr_c  not found in annotations
WARNING:thermomodel_None:phpyr_c  not found in annotations
2026-01-13 17:26:16,383 - thermomodel_None - WARNING - fe2_c  not found in annotations
WARNING:thermomodel_None:fe2_c  not found in annotations
2026-01-13 17:26:16,385 - thermomodel_None - WARNING - phllqne_c  not found in annotations
WARNING:thermomodel_None:phllqne_c  not found in annotations
2026-01-13 17:26:16,386 - thermomodel_None - WARNING - toct2eACP_c  not found in annotations
WARNING:thermomodel_None:toct2eACP_c  not found in annotations
2026-01-13 17:26:16,391 - thermomodel_None - WARNING - dgdp_c  not found in annotations
WARNING:thermomodel_None:dgdp_c  not found in annotations
2026-01-13 17:26:16,394 - thermomodel_None - WARNING - uaccg_c  not found in annotations
WARNING:thermomodel_None:uaccg_c  not found in annotations
2026-01-13 17:26:16,398 - thermomodel_None - WARNING - acald_c  not found in annotations
WARNING:thermomodel_None:acald_c  not found in annotations
2026-01-13 17:26:16,399 - thermomodel_None - WARNING - o2s_c  not found in annotations
WARNING:thermomodel_None:o2s_c  not found in annotations
2026-01-13 17:26:16,401 - thermomodel_None - WARNING - alac__S_c  not found in annotations
WARNING:thermomodel_None:alac__S_c  not found in annotations
2026-01-13 17:26:16,404 - thermomodel_None - WARNING - 3hmop_c  not found in annotations
WARNING:thermomodel_None:3hmop_c  not found in annotations
2026-01-13 17:26:16,406 - thermomodel_None - WARNING - 4abz_c  not found in annotations
WARNING:thermomodel_None:4abz_c  not found in annotations
2026-01-13 17:26:16,408 - thermomodel_None - WARNING - prbamp_c  not found in annotations
WARNING:thermomodel_None:prbamp_c  not found in annotations
2026-01-13 17:26:16,413 - thermomodel_None - WARNING - ca2_c  not found in annotations
WARNING:thermomodel_None:ca2_c  not found in annotations
2026-01-13 17:26:16,416 - thermomodel_None - WARNING - glyclt_c  not found in annotations
WARNING:thermomodel_None:glyclt_c  not found in annotations
2026-01-13 17:26:16,419 - thermomodel_None - WARNING - butACP_c  not found in annotations
WARNING:thermomodel_None:butACP_c  not found in annotations
2026-01-13 17:26:16,422 - thermomodel_None - WARNING - 4ppcys_c  not found in annotations
WARNING:thermomodel_None:4ppcys_c  not found in annotations
2026-01-13 17:26:16,424 - thermomodel_None - WARNING - udpgal_c  not found in annotations
WARNING:thermomodel_None:udpgal_c  not found in annotations
2026-01-13 17:26:16,428 - thermomodel_None - WARNING - f6p_c  not found in annotations
WARNING:thermomodel_None:f6p_c  not found in annotations
2026-01-13 17:26:16,429 - thermomodel_None - WARNING - lac__D_c  not found in annotations
WARNING:thermomodel_None:lac__D_c  not found in annotations
2026-01-13 17:26:16,431 - thermomodel_None - WARNING - his__L_c  not found in annotations
WARNING:thermomodel_None:his__L_c  not found in annotations
2026-01-13 17:26:16,433 - thermomodel_None - WARNING - agdpcbi_c  not found in annotations
WARNING:thermomodel_None:agdpcbi_c  not found in annotations
2026-01-13 17:26:16,435 - thermomodel_None - WARNING - s17bp_c  not found in annotations
WARNING:thermomodel_None:s17bp_c  not found in annotations
2026-01-13 17:26:16,436 - thermomodel_None - WARNING - dctp_c  not found in annotations
WARNING:thermomodel_None:dctp_c  not found in annotations
2026-01-13 17:26:16,439 - thermomodel_None - WARNING - thf_c  not found in annotations
WARNING:thermomodel_None:thf_c  not found in annotations
2026-01-13 17:26:16,441 - thermomodel_None - WARNING - 25aics_c  not found in annotations
WARNING:thermomodel_None:25aics_c  not found in annotations
2026-01-13 17:26:16,442 - thermomodel_None - WARNING - ni2_c  not found in annotations
WARNING:thermomodel_None:ni2_c  not found in annotations
2026-01-13 17:26:16,444 - thermomodel_None - WARNING - dtdp4d6dg_c  not found in annotations
WARNING:thermomodel_None:dtdp4d6dg_c  not found in annotations
2026-01-13 17:26:16,446 - thermomodel_None - WARNING - malcoa_c  not found in annotations
WARNING:thermomodel_None:malcoa_c  not found in annotations
2026-01-13 17:26:16,447 - thermomodel_None - WARNING - fum_c  not found in annotations
WARNING:thermomodel_None:fum_c  not found in annotations
2026-01-13 17:26:16,449 - thermomodel_None - WARNING - bm_cw_c  not found in annotations
WARNING:thermomodel_None:bm_cw_c  not found in annotations
2026-01-13 17:26:16,452 - thermomodel_None - WARNING - ACP_c  not found in annotations
WARNING:thermomodel_None:ACP_c  not found in annotations
2026-01-13 17:26:16,454 - thermomodel_None - WARNING - mlthf_c  not found in annotations
WARNING:thermomodel_None:mlthf_c  not found in annotations
2026-01-13 17:26:16,456 - thermomodel_None - WARNING - h_p  not found in annotations
WARNING:thermomodel_None:h_p  not found in annotations
2026-01-13 17:26:16,457 - thermomodel_None - WARNING - dhf_c  not found in annotations
WARNING:thermomodel_None:dhf_c  not found in annotations
2026-01-13 17:26:16,459 - thermomodel_None - WARNING - dudp_c  not found in annotations
WARNING:thermomodel_None:dudp_c  not found in annotations
2026-01-13 17:26:16,462 - thermomodel_None - WARNING - 3omrsACP_c  not found in annotations
WARNING:thermomodel_None:3omrsACP_c  not found in annotations
2026-01-13 17:26:16,463 - thermomodel_None - WARNING - trnaglu_c  not found in annotations
WARNING:thermomodel_None:trnaglu_c  not found in annotations
2026-01-13 17:26:16,464 - thermomodel_None - WARNING - pre6a_c  not found in annotations
WARNING:thermomodel_None:pre6a_c  not found in annotations
2026-01-13 17:26:16,466 - thermomodel_None - WARNING - ametam_c  not found in annotations
WARNING:thermomodel_None:ametam_c  not found in annotations
2026-01-13 17:26:16,468 - thermomodel_None - WARNING - 3hhexACP_c  not found in annotations
WARNING:thermomodel_None:3hhexACP_c  not found in annotations
2026-01-13 17:26:16,471 - thermomodel_None - WARNING - 4ppan_c  not found in annotations
WARNING:thermomodel_None:4ppan_c  not found in annotations
2026-01-13 17:26:16,473 - thermomodel_None - WARNING - quln_c  not found in annotations
WARNING:thermomodel_None:quln_c  not found in annotations
2026-01-13 17:26:16,475 - thermomodel_None - WARNING - frdp_c  not found in annotations
WARNING:thermomodel_None:frdp_c  not found in annotations
2026-01-13 17:26:16,477 - thermomodel_None - WARNING - glyald_c  not found in annotations
WARNING:thermomodel_None:glyald_c  not found in annotations
2026-01-13 17:26:16,481 - thermomodel_None - WARNING - uacgam_c  not found in annotations
WARNING:thermomodel_None:uacgam_c  not found in annotations
2026-01-13 17:26:16,482 - thermomodel_None - WARNING - pram_c  not found in annotations
WARNING:thermomodel_None:pram_c  not found in annotations
2026-01-13 17:26:16,484 - thermomodel_None - WARNING - 26dap__M_c  not found in annotations
WARNING:thermomodel_None:26dap__M_c  not found in annotations

TypeError: string indices must be integers, not 'str'

# Multiple points fba tfba (version 3)

Checkpoints to save data each iteration

In [ ]:

from tqdm import tqdm
for i in tqdm(range(10000)):
    pass


# -------------------------
r_ac_exists     = "EX_ac_e"        in cobra_model_mat.reactions
r_hxa_exists    = "EX_hxa_e"       in cobra_model_mat.reactions
r_fum_exists    = "EX_fum_e"       in cobra_model_mat.reactions
r_lac_exists    = "EX_lac__L_e"    in cobra_model_mat.reactions
r_ppa_exists    = "EX_ppa_e"       in cobra_model_mat.reactions
r_but_exists    = "EX_but_e"       in cobra_model_mat.reactions
r_succ_exists   = "EX_succ_e"      in cobra_model_mat.reactions
r_phb_exists    = "PHBS_syn"       in cobra_model_mat.reactions
r_phv_exists     = "PHVS_syn"       in cobra_model_mat.reactions
r_phbv_exists    = "PHBVS_syn"       in cobra_model_mat.reactions
r_3hvcoa_exists    = "3hvcoa_syn"       in cobra_model_mat.reactions
r_biomass_exists= "BIOMASS__1"     in cobra_model_mat.reactions

# ===============================
# USER INPUT
# ===============================
#CSV_PATH = "/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/data/Buitron2025_dataset.csv"
OUT_CSV = project_root_palustris / "FBA_vs_TFA_PHB_results.csv"

INITIAL_BIOMASS = 0.094
FALLBACK_TIME_H = 72.0

# ===============================
# CONSTANTS
# ===============================
PHB_MW = 86.0
PHV_MW  = 100.12  # mg/mmol (3HV monomer)
ACETATE_MW = 59.04
COD_TO_ACETATE_RATIO = 1.066

# ===============================
# LOAD DATA
# ===============================
df = pd.read_csv(phbv_model_dir / "subset_pareto_optimal_conditions_for_tfa.csv") #pd.read_csv(CSV_PATH)
df = df.iloc[1:35].drop(index=[15, 16]).reset_index(drop=True)

# ===============================
# MEDIUM
# ===============================
medium_ub = {
    "EX_ac_e": 0.2477,
    "EX_nh4_e": 0.14188,
    "EX_pi_e": 0.03733,
    "EX_o2_e": 0,
    "EX_co2_e": 0,
    **{f"EX_photon{x}_e": 10 for x in range(410, 700, 20)}
}

PHBV_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

# ===============================
# PHOTON SCALING
# ===============================
def scale_photons(model, illum, ref=1000):
    for rxn in model.reactions:
        if rxn.id.startswith("EX_photon"):
            rxn.lower_bound = 0

    if pd.isna(illum):
        return

    s = str(illum).lower()

    if s in ["continuous", "light", "on"]:
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -ub
        return

    try:
        val = float("".join(c for c in s if c.isdigit() or c == "."))
        scale = val / ref
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -scale * ub
    except Exception:
        pass

# ===============================
# SOLVER SETTINGS
# ===============================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True

# ===============================
# LOAD TFA METADATA
# ===============================
lexicon = read_lexicon(str(rp_lex_mat_path))
comp_data = read_compartment_data(str(rp_comp_mat_path))


# ============================================================
# OUTPUT HEADER
# ============================================================
BASE_COLUMNS = [
    "row",
    "Time_d",
    "Time_h",
    "Biomass_final_gDW_L",
    "X_eff_gDW_L",
    "COD_g_L",
    "Illumination",
    "q_ac_mmol_gDW_h",
    "EX_ac_e_lb",
    "EX_ac_e_ub",
    "PHBV_FBA",
    "PHBV_TFA",
    "Biomass_FBA",
    "Biomass_TFA",
    "status_FBA",
    "status_TFA",
]

PHBV_FBA_COLS = [f"{r}_FBA" for r in PHBV_REACTIONS]
PHBV_TFA_COLS = [f"{r}_TFA" for r in PHBV_REACTIONS]

ALL_COLUMNS = BASE_COLUMNS + PHBV_FBA_COLS + PHBV_TFA_COLS

if not OUT_CSV.exists():
    pd.DataFrame(columns=ALL_COLUMNS).to_csv(OUT_CSV, index=False)



# ===============================
# MAIN LOOP (APPEND EACH ROW)
# ===============================
for i, row in df.iterrows():
    print(f"\n--- ROW {i+1} ---")

    try:
        # ---------------------------
        # BUILD MODEL
        # ---------------------------
        m = cobra_model_mat.copy()

        for ex in m.exchanges:
            ex.lower_bound = 0

        for rid, ub in medium_ub.items():
            if rid in m.reactions:
                m.reactions.get_by_id(rid).lower_bound = -ub

        # ---------------------------
        # TIME & BIOMASS
        # ---------------------------
        t_h = row.get("Time (d)", np.nan)
        t_h = FALLBACK_TIME_H if pd.isna(t_h) else float(t_h) * 24

        biomass_final = row.get("Biomass (mg dw/L)", np.nan)
        biomass_final = biomass_final / 1000 if not pd.isna(biomass_final) else np.nan

        X_eff = (INITIAL_BIOMASS + biomass_final) / 2 if not pd.isna(biomass_final) else np.nan

        # ---------------------------
        # COD → ACETATE FLUX
        # ---------------------------
        COD = row.get("g substrate COD/L", np.nan)
        q_ac = np.nan

        if not pd.isna(COD) and X_eff > 0:
            mmol_L = (COD * 1000 / COD_TO_ACETATE_RATIO) / ACETATE_MW
            q_ac = mmol_L / (X_eff * t_h)

            rxn = m.reactions.get_by_id("EX_ac_e")
            rxn.lower_bound = -q_ac
            rxn.upper_bound = -q_ac

        # ---------------------------
        # PHOTONS
        # ---------------------------
        scale_photons(m, row.get("Illumination", np.nan))

        # ---------------------------
        # PHB CAP & OBJECTIVE
        # ---------------------------
        phb_rxn_id = 'PHBVS_syn'
        mu_max = 0.08 # growth rate
        f = 0.50       # fraction of the maximum growth-associated carbon/flux that is diverted to PHB synthesis

        v_phbv_max = 1 #mu_max * f * 1000 / PHV_MW
        v_phbv_max_eff = mu_max * f * 1000 / PHV_MW + PHB_MW
        print(f" Calculated v_phbv_max (mmol/gDW/h) = {v_phbv_max_eff:.6f}")
        print(f" v_phbv_max (mmol/gDW/h) = {v_phbv_max:.6f}")

        if r_phbv_exists and phb_rxn_id in m.reactions:
            phb_rxn = m.reactions.get_by_id(phb_rxn_id)
            phb_rxn.lower_bound = 0.0
            phb_rxn.upper_bound = v_phbv_max
            m.objective = phb_rxn # define OBJECTIVE
        else:
            print(f"WARNING: PHBS_syn not found in model for row {row_id}")

        #m.reactions.get_by_id("ATPM").lower_bound = 20

        apply_solver_settings(m)

        # ---------------------------
        # FBA
        # ---------------------------
        fba_sol = m.optimize()

        # ---------------------------
        # TFA
        # ---------------------------
        mytfa = pytfa.ThermoModel(thermo_data, m)
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)

        mytfa.objective = "PHBVS_syn"
        apply_solver_settings(mytfa)
        mytfa.prepare()
        tfa_sol = mytfa.optimize()

        result = {
            "row": i + 1,
            "X_eff": X_eff,
            "COD_g_L": COD,
            "q_ac_mmol_gDW_h": q_ac,
            "PHBV_FBA": fba_sol.fluxes.get("PHBVS_syn", np.nan),
            "PHBV_TFA": tfa_sol.fluxes.get("PHBVS_syn", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
        }

    except Exception as e:
        print(f"Row {i+1} failed: {e}")
        result = {
            "row": i + 1,
            "X_eff": np.nan,
            "COD_g_L": np.nan,
            "q_ac_mmol_gDW_h": np.nan,
            "PHB_FBA": np.nan,
            "PHB_TFA": np.nan,
            "Biomass_FBA": np.nan,
            "Biomass_TFA": np.nan,
            "status_FBA": "error",
            "status_TFA": "error",
        }

    # ---------------------------
    # APPEND IMMEDIATELY
    # ---------------------------
    pd.DataFrame([result]).to_csv(
        OUT_CSV,
        mode="a",
        header=False,
        index=False
    )

    for i, row in tqdm(df.iterrows(), total=len(df), desc="Running FBA/TFA"):
    tqdm.write(f"--- ROW {i+1} ---")

print("\nDONE — results safely saved per row.")

# Dumbell plot TFBA vs FBA

In [ ]:
# Load TFBA and FBA results
df_results_fba_tfba = pd.read_csv(phbv_model_dir / "FBA_vs_TFA_PHB_results.csv")
len(df_results_fba_tfba)

df = df_results_fba_tfba.copy()

# Keep only successful runs
df = df[
    (df["status_FBA"] == "optimal") &
    (df["status_TFA"] == "optimal")
].reset_index(drop=True)

# Sort by TFA flux for clean ordering
df = df.sort_values("PHBV_TFA").reset_index(drop=True)

# Best solution = highest TFA PHBV flux
best_idx = df["PHBV_TFA"].idxmax()

# Opt: Quantify thermodynamic thightening

In [ ]:
# Quantify thermodynamic thightening
df["flux_loss_pct"] = 100 * (df["PHBV_FBA"] - df["PHBV_TFA"]) / df["PHBV_FBA"]

# *Multiple points fba tfba (version 4).

Include operational and calculated parameters, fba, tfba, and their reaction fluxes

In [ ]:
# ============================================================
# IMPORTS
# ============================================================
import cobra
import pytfa
import pandas as pd
import numpy as np
from pathlib import Path

from pytfa.io import (
    read_lexicon,
    annotate_from_lexicon,
    read_compartment_data,
    apply_compartment_data,
)

# ============================================================
# REQUIRED PRE-LOADED OBJECTS (ASSUMED TO EXIST)
# ============================================================
# cobra_model_mat
# thermo_data
# rp_lex_mat_path
# rp_comp_mat_path
# project_root_palustris
# ============================================================

# ============================================================
# USER INPUT
# ============================================================

#model_phbv2 = model_phbv.copy()
#CSV_PATH = "/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/data/Buitron2025_dataset.csv"

OUT_CSV = PHB_MODEL_TFA_DIR / "FBA_TFA_PHB_detailed_results_phbv_20260308.csv"

INITIAL_BIOMASS = 0.094      # gDW/L
FALLBACK_TIME_H = 72.0

# ============================================================
# CONSTANTS
# ============================================================
PHB_MW = 86.0
PHV_MW  = 100.12  # mg/mmol (3HV monomer)
ACETATE_MW = 59.04
COD_TO_ACETATE_RATIO = 1.066

PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1",
]

# ============================================================
# LOAD DATA
# ============================================================
df = pd.read_csv(PHBV_MODEL_DIR / "subset_pareto_optimal_conditions_for_tfa.csv")
df = df.iloc[1:35].drop(index=[15, 16]).reset_index(drop=True)

# ============================================================
# MEDIUM
# ============================================================
medium_ub = {
    "EX_ac_e": 0.2477,
    "EX_nh4_e": 0.14188,
    "EX_pi_e": 0.03733,
    "EX_o2_e": 0,
    "EX_co2_e": 0,
    **{f"EX_photon{x}_e": 10 for x in range(410, 700, 20)},
}

# ============================================================
# PHOTON SCALING
# ============================================================
def scale_photons(model, illum, ref=1000):
    for rxn in model.reactions:
        if rxn.id.startswith("EX_photon"):
            rxn.lower_bound = 0

    if pd.isna(illum):
        return

    s = str(illum).lower()
    if s in ["continuous", "light", "on"]:
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -ub
        return

    try:
        val = float("".join(c for c in s if c.isdigit() or c == "."))
        scale = val / ref
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -scale * ub
    except Exception:
        pass

# ============================================================
# SOLVER SETTINGS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True

# ============================================================
# LOAD TFA METADATA
# ============================================================
lexicon = read_lexicon(str(rp_lex_mat_path))
comp_data = read_compartment_data(str(rp_comp_mat_path))

# ============================================================
# OUTPUT HEADER
# ============================================================
BASE_COLUMNS = [
    "row",
    "Time_d",
    "Time_h",
    "Biomass_final_gDW_L",
    "X_eff_gDW_L",
    "COD_g_L",
    "Illumination",
    "q_ac_mmol_gDW_h",
    "EX_ac_e_lb",
    "EX_ac_e_ub",
    "PHB_FBA",
    "PHB_TFA",
    "Biomass_FBA",
    "Biomass_TFA",
    "status_FBA",
    "status_TFA",
]

PHB_FBA_COLS = [f"{r}_FBA" for r in PHB_REACTIONS]
PHB_TFA_COLS = [f"{r}_TFA" for r in PHB_REACTIONS]

ALL_COLUMNS = BASE_COLUMNS + PHB_FBA_COLS + PHB_TFA_COLS

if not OUT_CSV.exists():
    pd.DataFrame(columns=ALL_COLUMNS).to_csv(OUT_CSV, index=False)

# ============================================================
# MAIN LOOP (APPEND PER ROW)
# ============================================================
for i, row in df.iterrows():
    print(f"\n--- ROW {i+1} ---")

    try:
        # ---------------------------
        # RAW INPUT
        # ---------------------------
        time_d = row.get("Time (d)", np.nan)
        illum = row.get("Illumination", np.nan)
        COD = row.get("g substrate COD/L", np.nan)

        biomass_final = row.get("Biomass (mg dw/L)", np.nan)
        biomass_final = biomass_final / 1000 if not pd.isna(biomass_final) else np.nan

        # ---------------------------
        # DERIVED PARAMETERS
        # ---------------------------
        time_h = FALLBACK_TIME_H if pd.isna(time_d) else float(time_d) * 24
        X_eff = (INITIAL_BIOMASS + biomass_final) / 2 if not pd.isna(biomass_final) else np.nan

        q_ac = np.nan
        ex_lb = np.nan
        ex_ub = np.nan

        # ---------------------------
        # BUILD MODEL
        # ---------------------------
        m = cobra_model_mat.copy()

        for ex in m.exchanges:
            ex.lower_bound = 0

        for rid, ub in medium_ub.items():
            if rid in m.reactions:
                m.reactions.get_by_id(rid).lower_bound = -ub

        # ---------------------------
        # COD → ACETATE
        # ---------------------------
        if not pd.isna(COD) and X_eff > 0:
            mmol_L = (COD * 1000 / COD_TO_ACETATE_RATIO) / ACETATE_MW
            q_ac = mmol_L / (X_eff * time_h)

            rxn = m.reactions.get_by_id("EX_ac_e")
            rxn.lower_bound = -q_ac
            rxn.upper_bound = -q_ac
            ex_lb = rxn.lower_bound
            ex_ub = rxn.upper_bound

        # ---------------------------
        # PHOTONS
        # ---------------------------
        scale_photons(m, illum)

        # ---------------------------
        # PHB OBJECTIVE
        # ---------------------------
        mu_max = 0.08
        f = 0.20
        v_phb_max = mu_max * f * 1000 / PHB_MW

        phb_rxn = m.reactions.get_by_id("PHBVS_syn")
        phb_rxn.lower_bound = 0
        phb_rxn.upper_bound = v_phb_max
        m.objective = phb_rxn

        m.reactions.get_by_id("ATPM").lower_bound = 20
        apply_solver_settings(m)

        # ---------------------------
        # FBA
        # ---------------------------
        fba_sol = m.optimize()

        # ---------------------------
        # TFA
        # ---------------------------
        mytfa = pytfa.ThermoModel(thermo_data, m)
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)
        mytfa.objective = "PHBVS_syn"
        apply_solver_settings(mytfa)
        mytfa.prepare()
        tfa_sol = mytfa.optimize()

        # ---------------------------
        # COLLECT RESULTS
        # ---------------------------
        result = {
            "row": i + 1,
            "Time_d": time_d,
            "Time_h": time_h,
            "Biomass_final_gDW_L": biomass_final,
            "X_eff_gDW_L": X_eff,
            "COD_g_L": COD,
            "Illumination": illum,
            "q_ac_mmol_gDW_h": q_ac,
            "EX_ac_e_lb": ex_lb,
            "EX_ac_e_ub": ex_ub,
            "PHBV_FBA": fba_sol.fluxes.get("PHBVS_syn", np.nan),
            "PHBV_TFA": tfa_sol.fluxes.get("PHBVS_syn", np.nan),
            "Biomass_FBA": fba_sol.fluxes.get("BIOMASS__1", np.nan),
            "Biomass_TFA": tfa_sol.fluxes.get("BIOMASS__1", np.nan),
            "status_FBA": fba_sol.status,
            "status_TFA": tfa_sol.status,
        }

        for r in PHB_REACTIONS:
            result[f"{r}_FBA"] = fba_sol.fluxes.get(r, np.nan)
            result[f"{r}_TFA"] = tfa_sol.fluxes.get(r, np.nan)

    except Exception as e:
        print(f" Row {i+1} failed: {e}")
        result = {c: np.nan for c in ALL_COLUMNS}
        result["row"] = i + 1
        result["status_FBA"] = "error"
        result["status_TFA"] = "error"

    # ---------------------------
    # APPEND TO CSV
    # ---------------------------
    pd.DataFrame([result])[ALL_COLUMNS].to_csv(
        OUT_CSV,
        mode="a",
        header=False,
        index=False,
    )

    print(f"✓ Row {i+1} saved")

print("\nDONE — all rows processed safely.")

In [ ]:
import cobra
import pytfa
import pandas as pd
import numpy as np
from pathlib import Path
from pytfa.io import (
    read_lexicon,
    annotate_from_lexicon,
    read_compartment_data,
    apply_compartment_data
)

# ============================================================
# USER INPUT
# ============================================================
CSV_PATH = "/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/data/Buitron2025_dataset.csv"
OUTPUT_CSV = Path("FBA_TFA_PHB_complete_dataset.csv")

INITIAL_BIOMASS = 0.094   # gDW/L
FALLBACK_TIME_H = 72.0

UPTAKE_FACTORS = [1, 10, 100]

# ============================================================
# CONSTANTS
# ============================================================
PHB_MW = 86.0
ACETATE_MW = 59.04
COD_TO_ACETATE_RATIO = 1.066

PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

# ============================================================
# LOAD DATA
# ============================================================
df = pd.read_csv(CSV_PATH)
df = df.iloc[1:35].drop(index=[15, 16]).reset_index(drop=True)

# ============================================================
# MEDIUM
# ============================================================
medium_ub = {
    "EX_ac_e": 0.2477,
    "EX_nh4_e": 0.14188,
    "EX_pi_e": 0.03733,
    "EX_o2_e": 0,
    "EX_co2_e": 0,
    **{f"EX_photon{x}_e": 10 for x in range(410, 700, 20)}
}

# ============================================================
# HELPERS
# ============================================================
def apply_solver_settings(model):
    model.solver = "glpk"
    model.solver.configuration.tolerances.feasibility = 1e-9
    model.solver.configuration.presolve = True


def scale_photons(model, illum, ref=1000):
    for rxn in model.reactions:
        if rxn.id.startswith("EX_photon"):
            rxn.lower_bound = 0

    if pd.isna(illum):
        return

    s = str(illum).lower()
    if s in ["continuous", "light", "on"]:
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -ub
        return

    try:
        val = float("".join(c for c in s if c.isdigit() or c == "."))
        scale = val / ref
        for rid, ub in medium_ub.items():
            if rid.startswith("EX_photon") and rid in model.reactions:
                model.reactions.get_by_id(rid).lower_bound = -scale * ub
    except Exception:
        pass


# ============================================================
# LOAD TFA METADATA
# ============================================================
lexicon = read_lexicon(str(rp_lex_mat_path))
comp_data = read_compartment_data(str(rp_comp_mat_path))

# ============================================================
# RESUME LOGIC
# ============================================================
if OUTPUT_CSV.exists():
    existing = pd.read_csv(OUTPUT_CSV)
    done = set(zip(existing.row, existing.uptake_factor))
    results = existing.to_dict("records")
else:
    done = set()
    results = []

# ============================================================
# MAIN LOOP
# ============================================================
for i, row in df.iterrows():

    base_metadata = row.to_dict()  # ALL original CSV columns

    for factor in UPTAKE_FACTORS:

        if (i + 1, factor) in done:
            continue

        print(f"ROW {i+1} | uptake ×{factor}")

        m = cobra_model_mat.copy()

        for ex in m.exchanges:
            ex.lower_bound = 0
        for rid, ub in medium_ub.items():
            if rid in m.reactions:
                m.reactions.get_by_id(rid).lower_bound = -ub

        # Time & biomass
        t_h = row.get("Time (d)", np.nan)
        t_h = FALLBACK_TIME_H if pd.isna(t_h) else float(t_h) * 24

        biomass_final = row.get("Biomass (mg dw/L)", np.nan)
        biomass_final = biomass_final / 1000 if not pd.isna(biomass_final) else np.nan

        X_eff = (INITIAL_BIOMASS + biomass_final) / 2 if not pd.isna(biomass_final) else np.nan

        # Acetate uptake
        COD = row.get("g substrate COD/L", np.nan)
        q_ac = lb = ub = np.nan

        if not pd.isna(COD) and X_eff > 0:
            mmol_L = (COD * 1000 / COD_TO_ACETATE_RATIO) / ACETATE_MW
            q_ac = mmol_L / (X_eff * t_h) * factor
            rxn = m.reactions.get_by_id("EX_ac_e")
            rxn.lower_bound = -q_ac
            rxn.upper_bound = -q_ac
            lb, ub = rxn.lower_bound, rxn.upper_bound

        scale_photons(m, row.get("Illumination", np.nan))

        # PHB objective
        v_phb_max = 0.08 * 0.20 * 1000 / PHB_MW
        phb = m.reactions.get_by_id("PHBS_syn")
        phb.lower_bound = 0
        phb.upper_bound = 1000# v_phb_max ### IMPORTANT!
        m.objective = phb
        m.reactions.get_by_id("ATPM").lower_bound = 20

        apply_solver_settings(m)

        fba = m.optimize()

        # TFA
        mytfa = pytfa.ThermoModel(thermo_data, m)
        annotate_from_lexicon(mytfa, lexicon)
        apply_compartment_data(mytfa, comp_data)
        mytfa.objective = "PHBS_syn"
        apply_solver_settings(mytfa)
        mytfa.prepare()
        tfa = mytfa.optimize()

        record = {
            **base_metadata,
            "row": i + 1,
            "uptake_factor": factor,
            "Time_h": t_h,
            "Biomass_final_gDW_L": biomass_final,
            "X_eff_gDW_L": X_eff,
            "COD_g_L": COD,
            "q_ac_mmol_gDW_h": q_ac,
            "EX_ac_e_lb": lb,
            "EX_ac_e_ub": ub,
            "PHB_FBA": fba.fluxes.get("PHBS_syn", np.nan) if fba.status == "optimal" else np.nan,
            "Biomass_FBA": fba.fluxes.get("BIOMASS__1", np.nan) if fba.status == "optimal" else np.nan,
            "PHB_TFA": tfa.fluxes.get("PHBS_syn", np.nan) if tfa.status == "optimal" else np.nan,
            "Biomass_TFA": tfa.fluxes.get("BIOMASS__1", np.nan) if tfa.status == "optimal" else np.nan,
            "status_FBA": fba.status,
            "status_TFA": tfa.status,
        }

        for r in PHB_REACTIONS:
            record[f"{r}_FBA"] = fba.fluxes.get(r, np.nan) if fba.status == "optimal" else np.nan
            record[f"{r}_TFA"] = tfa.fluxes.get(r, np.nan) if tfa.status == "optimal" else np.nan

        results.append(record)
        pd.DataFrame(results).to_csv(OUTPUT_CSV, index=False)

print("DONE — complete dataset saved")

In [ ]:
too_wide = [
    rxn.id for rxn in cobra_model_mat.reactions
    if rxn.upper_bound > 1000 or rxn.lower_bound < -1000
]

print(f"Reactions still exceeding ±1000 bounds: {len(too_wide)}")

Reactions still exceeding ±1000 bounds: 423

# One datapoint

Build themo model rpalustris for one data point (e.g., the one resulting from Pareto optimality)

In [ ]:
from pytfa.io import import_matlab_model, load_thermoDB,                    \
                            read_lexicon, annotate_from_lexicon,            \
                            read_compartment_data, apply_compartment_data

# =====================================
# ADD THERMODYNAMIC COMPARTMENT DATA
# (REPLACES read_compartment_data)
# =====================================

case = 'full' # 'reduced' or full'

# Load reaction DB
print("Loading thermo data...")

#thermo_data = load_thermoDB('/Users/hector/git/pytfa/data/thermo_data.thermodb')

thermo_data['metabolites'] = {
    str(k): v
    for k, v in thermo_data['metabolites'].items()
}

print("Done !")

if case == 'reduced':
    cobra_model = cobra_model_mat
    mytfa = pytfa.ThermoModel(thermo_data, cobra_model)
    biomass_rxn = 'PHBVS_syn'
elif case == 'full':
    # We import pre-compiled data as it is faster for bigger models

    cobra_model = cobra_model_mat

    lexicon = read_lexicon(str(rp_lex_mat_path))
    #lexicon = pd.read_csv(rp_lex_mat_path, index_col=0)
    compartment_data = read_compartment_data(str(rp_comp_mat_path))

    # Initialize the cobra_model
    mytfa = pytfa.ThermoModel(thermo_data, cobra_model)
    # Annotate the cobra_model
    annotate_from_lexicon(mytfa, lexicon)
    apply_compartment_data(mytfa, compartment_data)

    rxn = mytfa.reactions.get_by_id("PHBVS_syn")

    rxn.lower_bound = 0.0      # e.g. no negative growth
    rxn.upper_bound = 1.0   # or any max growth rate you want

    biomass_rxn = 'PHBVS_syn'

mytfa.name = 'RP_iDT1294'
mytfa.solver = "glpk"
mytfa.objective = biomass_rxn

# Solver settings

def apply_solver_settings(model, solver = "glpk"):
    model.solver = "glpk"
    # model.solver.configuration.verbosity = 1
    model.solver.configuration.tolerances.feasibility = 1e-9
    if solver == 'optlang_gurobi':
        model.solver.problem.Params.NumericFocus = 3
    model.solver.configuration.presolve = True

apply_solver_settings(mytfa)


## FBA
cobra_model.objective = biomass_rxn
fba_solution = cobra_model.optimize()
fba_value = fba_solution.objective_value
#fva = flux_variability_analysis(mytfa)


## TFA conversion
mytfa.prepare()

mytfa.solver.update()
print(len(mytfa.constraints))
print(len(mytfa.variables))

In [ ]:
rxn = cobra_model.reactions.get_by_id('PHBVS_syn')
print("PHBS_syn bounds:", rxn.bounds)
print("PHBS_syn stoichiometry:", rxn.reaction)

NameError: name 'cobra_model' is not defined

# Save TFBA model

In [ ]:
from cobra.io import write_sbml_model

mytfa.convert() # convert

phbv_tfba_dir = project_root / "tfba"
phbv_tfba_dir.mkdir(parents=True, exist_ok=True)

cobra.io.write_sbml_model(
    mytfa,
    phbv_tfba_dir / "model_GEM_PHBV.xml"
)

print("Model saved successfully")

# Run TFBA

In [ ]:
# Optimize TFA
tfa_sol = mytfa.optimize()

DEBUG:thermomodel_None:'slim_optimize' ((), {}) 335.95 sec

# Compare FBA and TFBA solutions

In [ ]:

## Optimality
tfa_value = tfa_sol.objective_value

# It might happen that the model is infeasible. In this case, we can relax
# thermodynamics constraints:

#if tfa_value < 0.1:
#    from pytfa.optim.relaxation import relax_dgo

 #   mytfa.reactions.get_by_id(biomass_rxn).lower_bound = 0.5*fba_value
 #   relaxed_model, slack_model, relax_table = relax_dgo(mytfa)

 #   original_model, mytfa = mytfa, relaxed_model

  #  print('Relaxation: ')
  #  print(relax_table)

   # tfa_solution = mytfa.optimize()
  #  tfa_value = tfa_solution.objective_value

# Report
print('FBA Solution found : {0:.5g}'.format(fba_value))
print('TFA Solution found : {0:.5g}'.format(tfa_value))


solver_results = dict()

FBA Solution found : 1
TFA Solution found : 1

## Check value of PHB_reactions in FBA and TFBA

In [ ]:
PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

thermo_rxns = {r.id for r in mytfa.reactions if r.thermo is not None}

for r_id in PHB_REACTIONS:
    print(
        f"{r_id:12s}",
        "✅ thermo" if r_id in thermo_rxns else "❌ no thermo"
    )

ACACT1r      ✅ thermo
ACACCT       ✅ thermo
AACOAR_syn   ✅ thermo
HACD1_2      ✅ thermo
HACD1        ✅ thermo
HACD1i       ✅ thermo
KAT1         ✅ thermo

In [ ]:
for r_id in PHB_REACTIONS:

  rxn_id = r_id
  flux = fba_solution.fluxes[rxn_id]
  print(f"FBA Flux of {rxn_id}: {flux}")

FBA Flux of ACACT1r: 0.6000000000000003
FBA Flux of ACACCT: 0.0
FBA Flux of AACOAR_syn: 0.8000000000000004
FBA Flux of HACD1_2: 0.0
FBA Flux of HACD1: -0.20000000000000015
FBA Flux of HACD1i: 0.0
FBA Flux of KAT1: 0.0

In [ ]:
for r_id in PHB_REACTIONS:

  rxn_id = r_id
  flux = tfa_sol.fluxes[rxn_id]
  print(f"TFBA Flux of {rxn_id}: {flux}")

TFBA Flux of ACACT1r: 0.6000000000000001
TFBA Flux of ACACCT: 0.0
TFBA Flux of AACOAR_syn: 0.8
TFBA Flux of HACD1_2: 0.0
TFBA Flux of HACD1: 0.0
TFBA Flux of HACD1i: 0.2
TFBA Flux of KAT1: 0.0

In [ ]:
assert any(c.name.startswith("G_") for c in mytfa.constraints)
assert any(v.name.startswith("DGo_") for v in mytfa.variables)
assert any(v.type == "binary" for v in mytfa.variables)
print("✅ TFBA is active")

✅ TFBA is active

In [ ]:
for v in mytfa.variables.values():
  print(v)

  #0.0 <= DM_4CRSOL <= 1000.0

0.0 <= QULNS <= 1000.0
0.0 <= QULNS_reverse_66da1 <= 0.0
0.0 <= ORNDC <= 1000.0
0.0 <= ORNDC_reverse_63596 <= 0.0
0.0 <= MSBENZMT <= 1000.0
0.0 <= MSBENZMT_reverse_a902a <= 0.0
0.0 <= DESAT18a <= 1000.0
0.0 <= DESAT18a_reverse_fd859 <= 1000.0
0.0 <= FUM <= 1000.0
0.0 <= FUM_reverse_d3642 <= 1000.0
0.0 <= PHYFXOR <= 1000.0
0.0 <= PHYFXOR_reverse_84960 <= 0.0
0.0 <= VPAMTr <= 1000.0
0.0 <= VPAMTr_reverse_872bd <= 0.0
0.0 <= GLYCL <= 1000.0
0.0 <= GLYCL_reverse_e418f <= 0.0
0.0 <= NDPK7 <= 1000.0
0.0 <= NDPK7_reverse_9dc79 <= 1000.0
0.0 <= GTPCI <= 1000.0
0.0 <= GTPCI_reverse_1ee86 <= 0.0
0.0 <= MTHFC <= 1000.0
0.0 <= MTHFC_reverse_f6fcc <= 1000.0
0.0 <= GCATENEC <= 1000.0
0.0 <= GCATENEC_reverse_ae4a5 <= 1000.0
0.0 <= ORNTA <= 1000.0
0.0 <= ORNTA_reverse_5adff <= 1000.0
0.0 <= UPPDC1 <= 1000.0
0.0 <= UPPDC1_reverse_cb592 <= 0.0
0.0 <= GARFT <= 1000.0
0.0 <= GARFT_reverse_7ecb6 <= 0.0
0.0 <= H4THDPR <= 1000.0
0.0 <= H4THDPR_reverse_617be <= 0.0
0.0 <= UDPG4E <= 1000.0
0.0 <= UDPG4E_reverse_08c7f <= 1000.0
0.0 <= GLCS3 <= 1000.0
0.0 <= GLCS3_reverse_5e7ed <= 0.0
0.0 <= ASPTA <= 1000.0
0.0 <= ASPTA_reverse_36525 <= 1000.0
0.0 <= PRAGSr <= 1000.0
0.0 <= PRAGSr_reverse_fd2d8 <= 0.0
0.0 <= ACKr <= 1000.0
0.0 <= ACKr_reverse_b49c0 <= 1000.0
0.0 <= KAS14 <= 1000.0
0.0 <= KAS14_reverse_25582 <= 0.0
0.0 <= UDCPDPS <= 1000.0
0.0 <= UDCPDPS_reverse_04082 <= 0.0
0.0 <= GLNS <= 1000.0
0.0 <= GLNS_reverse_59581 <= 0.0
0.0 <= SHKK <= 1000.0
0.0 <= SHKK_reverse_163fd <= 0.0
0.0 <= G1PACT <= 1000.0
0.0 <= G1PACT_reverse_51580 <= 0.0
0.0 <= 5DOAN <= 1000.0
0.0 <= 5DOAN_reverse_c8e7d <= 0.0
0.0 <= OHPBAT <= 1000.0
0.0 <= OHPBAT_reverse_7e72e <= 1000.0
0.0 <= Htex <= 1000.0
0.0 <= Htex_reverse_6f9a4 <= 1000.0
0.0 <= 3HAD60 <= 1000.0
0.0 <= 3HAD60_reverse_d7fb5 <= 1000.0
0.0 <= PGI <= 1000.0
0.0 <= PGI_reverse_27efc <= 1000.0
0.0 <= PNTK <= 1000.0
0.0 <= PNTK_reverse_236b6 <= 0.0
0.0 <= 3OAR60 <= 1000.0
0.0 <= 3OAR60_reverse_40a5c <= 1000.0
0.0 <= ACGK <= 1000.0
0.0 <= ACGK_reverse_684be <= 0.0
0.0 <= LEUabcpp <= 1000.0
0.0 <= LEUabcpp_reverse_ab30a <= 0.0
0.0 <= G5SD <= 1000.0
0.0 <= G5SD_reverse_af8c0 <= 0.0
0.0 <= DTMPK <= 1000.0
0.0 <= DTMPK_reverse_44d5a <= 1000.0
0.0 <= NDH_1_1_um_copy1 <= 1000.0
0.0 <= NDH_1_1_um_copy1_reverse_4db8b <= 0.0
0.0 <= HSTPT <= 1000.0
0.0 <= HSTPT_reverse_b3657 <= 1000.0
0.0 <= U23GAAT2 <= 1000.0
0.0 <= U23GAAT2_reverse_387ef <= 0.0
0.0 <= PGK <= 1000.0
0.0 <= PGK_reverse_02696 <= 1000.0
0.0 <= IMPD <= 1000.0
0.0 <= IMPD_reverse_6e625 <= 0.0
0.0 <= LPOR <= 1000.0
0.0 <= LPOR_reverse_ae81c <= 0.0
0.0 <= CHRPL <= 1000.0
0.0 <= CHRPL_reverse_46f50 <= 0.0
0.0 <= GCALDDy <= 1000.0
0.0 <= GCALDDy_reverse_2af46 <= 0.0
0.0 <= RNDR1 <= 1000.0
0.0 <= RNDR1_reverse_f4be1 <= 0.0
0.0 <= AIRC2 <= 1000.0
0.0 <= AIRC2_reverse_50d74 <= 0.0
0.0 <= MTAP <= 1000.0
0.0 <= MTAP_reverse_96009 <= 0.0
0.0 <= DHORD3um <= 1000.0
0.0 <= DHORD3um_reverse_137f3 <= 0.0
0.0 <= TRPS1 <= 1000.0
0.0 <= TRPS1_reverse_35c22 <= 0.0
0.0 <= NNATr <= 1000.0
0.0 <= NNATr_reverse_8ab73 <= 1000.0
0.0 <= 3OAR120 <= 1000.0
0.0 <= 3OAR120_reverse_5a2b4 <= 1000.0
0.0 <= HISTDb <= 1000.0
0.0 <= HISTDb_reverse_acd55 <= 0.0
0.0 <= ADCL <= 1000.0
0.0 <= ADCL_reverse_0051f <= 0.0
0.0 <= CYTK1 <= 1000.0
0.0 <= CYTK1_reverse_2fa21 <= 1000.0
0.0 <= PSIum <= 1000.0
0.0 <= PSIum_reverse_43c5e <= 0.0
0.0 <= Cobalt2abcppI <= 1000.0
0.0 <= Cobalt2abcppI_reverse_894f2 <= 0.0
0.0 <= THRS <= 1000.0
0.0 <= THRS_reverse_a994c <= 0.0
0.0 <= AOXPBDC <= 1000.0
0.0 <= AOXPBDC_reverse_81d1e <= 0.0
0.0 <= NAMNPP <= 1000.0
0.0 <= NAMNPP_reverse_ebb31 <= 1000.0
0.0 <= PERD <= 1000.0
0.0 <= PERD_reverse_c9aa4 <= 0.0
0.0 <= DAPDC <= 1000.0
0.0 <= DAPDC_reverse_d3ab8 <= 0.0
0.0 <= COCHL_1 <= 1000.0
0.0 <= COCHL_1_reverse_736d9 <= 0.0
0.0 <= 3OAR100 <= 1000.0
0.0 <= 3OAR100_reverse_d47e7 <= 1000.0
0.0 <= PPK2 <= 1000.0
0.0 <= PPK2_reverse_3275d <= 1000.0
0.0 <= ZNabcpp <= 1000.0
0.0 <= ZNabcpp_reverse_14d34 <= 1000.0
0.0 <= GLYDHDA <= 1000.0
0.0 <= GLYDHDA_reverse_663d3 <= 1000.0
0.0 <= ANS <= 1000.0
0.0 <= ANS_reverse_4e062 <= 0.0
0.0 <= SUCBZL <= 1000.0
0.0 <= SUCBZL_reverse_536e6 <= 0.0
0.0 <= ADPT <= 1000.0
0.0 <= ADPT_reverse_567cf <= 1000.0
0.0 <= RNDR3 <= 1000.0
0.0 <= RNDR3_reverse_bc84a <= 0.0
0.0 <= DHNANT <= 1000.0
0.0 <= DHNANT_reverse_39a88 <= 0.0
0.0 <= GND <= 1000.0
0.0 <= GND_reverse_eec5c <= 0.0
0.0 <= O2tcx <= 1000.0
0.0 <= O2tcx_reverse_6b2f8 <= 0.0
0.0 <= TRPS3 <= 1000.0
0.0 <= TRPS3_reverse_bdfbb <= 0.0
0.0 <= DNTPPA <= 1000.0
0.0 <= DNTPPA_reverse_7e624 <= 0.0
0.0 <= HOXGfx <= 1000.0
0.0 <= HOXGfx_reverse_2964c <= 0.0
0.0 <= TMPPP_1 <= 1000.0
0.0 <= TMPPP_1_reverse_7b964 <= 0.0
0.0 <= ACONT <= 1000.0
0.0 <= ACONT_reverse_7c2d5 <= 1000.0
0.0 <= IGPS <= 1000.0
0.0 <= IGPS_reverse_feb80 <= 0.0
0.0 <= HBZNPT <= 1000.0
0.0 <= HBZNPT_reverse_37fab <= 0.0
0.0 <= HSDy <= 0.0
0.0 <= HSDy_reverse_77ce7 <= 1000.0
0.0 <= GLYOX <= 1000.0
0.0 <= GLYOX_reverse_6ab0a <= 0.0
0.0 <= AICART <= 1000.0
0.0 <= AICART_reverse_b7b59 <= 0.0
0.0 <= SQD1 <= 1000.0
0.0 <= SQD1_reverse_c0265 <= 0.0
0.0 <= GK1 <= 1000.0
0.0 <= GK1_reverse_11a40 <= 1000.0
0.0 <= R05219 <= 1000.0
0.0 <= R05219_reverse_1009e <= 0.0
0.0 <= PPND <= 1000.0
0.0 <= PPND_reverse_5463c <= 0.0
0.0 <= IPDPS_syn <= 1000.0
0.0 <= IPDPS_syn_reverse_8eea6 <= 0.0
0.0 <= H4THDPS <= 1000.0
0.0 <= H4THDPS_reverse_5f722 <= 0.0
0.0 <= BIOMASS_PIGMENTS <= 1000.0
0.0 <= BIOMASS_PIGMENTS_reverse_b23ff <= 0.0
0.0 <= 3HAD160 <= 1000.0
0.0 <= 3HAD160_reverse_c0da0 <= 1000.0
0.0 <= HISTDa <= 1000.0
0.0 <= HISTDa_reverse_76147 <= 0.0
0.0 <= ADSL1r <= 1000.0
0.0 <= ADSL1r_reverse_2ae14 <= 0.0
0.0 <= H2Otu_syn <= 1000.0
0.0 <= H2Otu_syn_reverse_7aa62 <= 1000.0
0.0 <= ADOCBLS <= 1000.0
0.0 <= ADOCBLS_reverse_005a5 <= 0.0
0.0 <= ALAALAr <= 1000.0
0.0 <= ALAALAr_reverse_18faa <= 0.0
0.0 <= ACOATA <= 1000.0
0.0 <= ACOATA_reverse_8c02f <= 0.0
0.0 <= GLCP2_1 <= 1000.0
0.0 <= GLCP2_1_reverse_b0967 <= 0.0
0.0 <= GLYCK <= 1000.0
0.0 <= GLYCK_reverse_c3ee2 <= 0.0
0.0 <= MAN1PT <= 1000.0
0.0 <= MAN1PT_reverse_c317b <= 0.0
0.0 <= DMBZIDS2 <= 1000.0
0.0 <= DMBZIDS2_reverse_6417b <= 0.0
0.0 <= CS <= 1000.0
0.0 <= CS_reverse_8d7e9 <= 0.0
0.0 <= DMATT <= 1000.0
0.0 <= DMATT_reverse_3a731 <= 0.0
0.0 <= PSP_L <= 1000.0
0.0 <= PSP_L_reverse_cfa3c <= 0.0
0.0 <= NDPK3 <= 1000.0
0.0 <= NDPK3_reverse_37ea6 <= 1000.0
0.0 <= G3PD2 <= 1000.0
0.0 <= G3PD2_reverse_0c363 <= 1000.0
0.0 <= PHYTES <= 1000.0
0.0 <= PHYTES_reverse_45da8 <= 0.0
0.0 <= MOHMT <= 1000.0
0.0 <= MOHMT_reverse_83ce0 <= 0.0
0.0 <= FBA <= 1000.0
0.0 <= FBA_reverse_84806 <= 1000.0
0.0 <= BIOMASS__1 <= 2.0
0.0 <= BIOMASS__1_reverse_063c7 <= 0.0
0.0 <= ACLSa <= 1000.0
0.0 <= ACLSa_reverse_75fb2 <= 0.0
0.0 <= ASAD <= 0.0
0.0 <= ASAD_reverse_39a64 <= 1000.0
0.0 <= PSCVT <= 1000.0
0.0 <= PSCVT_reverse_1a852 <= 1000.0
0.0 <= TYRTA <= 1000.0
0.0 <= TYRTA_reverse_e9311 <= 1000.0
0.0 <= SERAT <= 1000.0
0.0 <= SERAT_reverse_0de5e <= 0.0
0.0 <= DHFS <= 1000.0
0.0 <= DHFS_reverse_f7920 <= 0.0
0.0 <= AMPMS3 <= 1000.0
0.0 <= AMPMS3_reverse_b5e80 <= 1000.0
0.0 <= ACBIPGT <= 1000.0
0.0 <= ACBIPGT_reverse_bcc45 <= 0.0
0.0 <= ATPM <= 1000.0
0.0 <= ATPM_reverse_5b752 <= 0.0
0.0 <= SEPHCHCS <= 1000.0
0.0 <= SEPHCHCS_reverse_cb185 <= 0.0
0.0 <= NMNDA <= 1000.0
0.0 <= NMNDA_reverse_0dc65 <= 0.0
0.0 <= IGPDH <= 1000.0
0.0 <= IGPDH_reverse_b1a3c <= 0.0
0.0 <= OMPDC <= 1000.0
0.0 <= OMPDC_reverse_45ba1 <= 0.0
0.0 <= 3OAR80 <= 1000.0
0.0 <= 3OAR80_reverse_fe338 <= 1000.0
0.0 <= 3OAR180 <= 1000.0
0.0 <= 3OAR180_reverse_e234c <= 1000.0
0.0 <= GLUSfx <= 1000.0
0.0 <= GLUSfx_reverse_468d6 <= 0.0
0.0 <= NADS2 <= 1000.0
0.0 <= NADS2_reverse_b427b <= 0.0
0.0 <= GLUTRR <= 1000.0
0.0 <= GLUTRR_reverse_355d5 <= 0.0
0.0 <= UAMAGS <= 1000.0
0.0 <= UAMAGS_reverse_a0d94 <= 0.0
0.0 <= FOLD3 <= 1000.0
0.0 <= FOLD3_reverse_4bc58 <= 0.0
0.0 <= 3HAD100 <= 1000.0
0.0 <= 3HAD100_reverse_ca00f <= 1000.0
0.0 <= GALUi <= 1000.0
0.0 <= GALUi_reverse_c40d5 <= 1000.0
0.0 <= P5CR <= 1000.0
0.0 <= P5CR_reverse_55c58 <= 0.0
0.0 <= PQH2tum <= 1000.0
0.0 <= PQH2tum_reverse_270a9 <= 0.0
0.0 <= ICHORS <= 1000.0
0.0 <= ICHORS_reverse_8e175 <= 1000.0
0.0 <= 3OAS140 <= 1000.0
0.0 <= 3OAS140_reverse_65ddc <= 0.0
0.0 <= SBP <= 1000.0
0.0 <= SBP_reverse_78d5c <= 0.0
0.0 <= EAR60y <= 1000.0
0.0 <= EAR60y_reverse_02e5e <= 0.0
0.0 <= O2tu <= 1000.0
0.0 <= O2tu_reverse_2d1e7 <= 1000.0
0.0 <= SULabcpp <= 1000.0
0.0 <= SULabcpp_reverse_40679 <= 0.0
0.0 <= PPK <= 1000.0
0.0 <= PPK_reverse_69cd8 <= 1000.0
0.0 <= BIOMASS_DNA <= 1000.0
0.0 <= BIOMASS_DNA_reverse_9947a <= 0.0
0.0 <= UAPGR <= 1000.0
0.0 <= UAPGR_reverse_4f67b <= 1000.0
0.0 <= DHAD1 <= 1000.0
0.0 <= DHAD1_reverse_39dca <= 0.0
0.0 <= IPPS <= 1000.0
0.0 <= IPPS_reverse_d94c0 <= 0.0
0.0 <= PPBNGS <= 1000.0
0.0 <= PPBNGS_reverse_dc5a2 <= 0.0
0.0 <= PRE3BS <= 1000.0
0.0 <= PRE3BS_reverse_ea947 <= 0.0
0.0 <= PHYTES2_1 <= 1000.0
0.0 <= PHYTES2_1_reverse_bb66c <= 0.0
0.0 <= 3HAD80 <= 1000.0
0.0 <= 3HAD80_reverse_29891 <= 1000.0
0.0 <= LTHRK <= 1000.0
0.0 <= LTHRK_reverse_61b82 <= 0.0
0.0 <= ADCPS2 <= 1000.0
0.0 <= ADCPS2_reverse_34636 <= 0.0
0.0 <= GF6PTA <= 1000.0
0.0 <= GF6PTA_reverse_21fb1 <= 1000.0
0.0 <= O2tpp <= 1000.0
0.0 <= O2tpp_reverse_28c7e <= 1000.0
0.0 <= PGMT <= 1000.0
0.0 <= PGMT_reverse_5bcdd <= 1000.0
0.0 <= 3OAR140 <= 1000.0
0.0 <= 3OAR140_reverse_4eb2a <= 1000.0
0.0 <= NDPK2 <= 1000.0
0.0 <= NDPK2_reverse_10df6 <= 1000.0
0.0 <= LPADSS2 <= 1000.0
0.0 <= LPADSS2_reverse_9cafc <= 0.0
0.0 <= DPR <= 1000.0
0.0 <= DPR_reverse_691d8 <= 1000.0
0.0 <= H2Otex <= 1000.0
0.0 <= H2Otex_reverse_57da2 <= 1000.0
0.0 <= TKT2 <= 1000.0
0.0 <= TKT2_reverse_7ebc7 <= 1000.0
0.0 <= SK_for_c <= 1000.0
0.0 <= SK_for_c_reverse_b95aa <= 0.0
0.0 <= PPNCL2 <= 1000.0
0.0 <= PPNCL2_reverse_a65ee <= 0.0
0.0 <= CYTBD4cm <= 1000.0
0.0 <= CYTBD4cm_reverse_64e50 <= 0.0
0.0 <= HPYRRy <= 1000.0
0.0 <= HPYRRy_reverse_197c5 <= 0.0
0.0 <= CHORS <= 1000.0
0.0 <= CHORS_reverse_17772 <= 0.0
0.0 <= 3OAR160 <= 1000.0
0.0 <= 3OAR160_reverse_15066 <= 1000.0
0.0 <= ADMDC <= 1000.0
0.0 <= ADMDC_reverse_e2782 <= 0.0
0.0 <= PPPGO2_1 <= 1000.0
0.0 <= PPPGO2_1_reverse_9826c <= 0.0
0.0 <= ASP1DC <= 1000.0
0.0 <= ASP1DC_reverse_5dad1 <= 0.0
0.0 <= MI3PP <= 1000.0
0.0 <= MI3PP_reverse_1228d <= 0.0
0.0 <= CYSS_2 <= 1000.0
0.0 <= CYSS_2_reverse_8e1d0 <= 0.0
0.0 <= FTHFD <= 1000.0
0.0 <= FTHFD_reverse_44321 <= 0.0
0.0 <= MEPCT <= 1000.0
0.0 <= MEPCT_reverse_de97a <= 0.0
0.0 <= PDX5POi <= 1000.0
0.0 <= PDX5POi_reverse_797dd <= 1000.0
0.0 <= PPCDC <= 1000.0
0.0 <= PPCDC_reverse_39306 <= 0.0
0.0 <= NTD6 <= 1000.0
0.0 <= NTD6_reverse_c5bce <= 1000.0
0.0 <= NNDMBRT <= 1000.0
0.0 <= NNDMBRT_reverse_13f8c <= 0.0
0.0 <= PRAIS <= 1000.0
0.0 <= PRAIS_reverse_8e616 <= 0.0
0.0 <= ORNTAC <= 1000.0
0.0 <= ORNTAC_reverse_b265a <= 0.0
0.0 <= SUCBZS <= 1000.0
0.0 <= SUCBZS_reverse_cdbc9 <= 0.0
0.0 <= HGYDAS <= 1000.0
0.0 <= HGYDAS_reverse_bc303 <= 0.0
0.0 <= GGDPR <= 1000.0
0.0 <= GGDPR_reverse_ea652 <= 0.0
0.0 <= ASPCT <= 1000.0
0.0 <= ASPCT_reverse_c18b9 <= 1000.0
0.0 <= PPNDH <= 1000.0
0.0 <= PPNDH_reverse_58300 <= 0.0
0.0 <= ME2 <= 1000.0
0.0 <= ME2_reverse_2b0a2 <= 1000.0
0.0 <= APRAUR <= 1000.0
0.0 <= APRAUR_reverse_e674d <= 0.0
0.0 <= SADT <= 1000.0
0.0 <= SADT_reverse_91e08 <= 0.0
0.0 <= LDH_D <= 1000.0
0.0 <= LDH_D_reverse_f8507 <= 1000.0
0.0 <= DPCOAK <= 1000.0
0.0 <= DPCOAK_reverse_56ab9 <= 0.0
0.0 <= O2tex <= 1000.0
0.0 <= O2tex_reverse_a3b28 <= 1000.0
0.0 <= DPOR <= 0.0
0.0 <= DPOR_reverse_8b09e <= 0.0
0.0 <= ARGSL <= 1000.0
0.0 <= ARGSL_reverse_1b949 <= 0.0
0.0 <= HSK <= 1000.0
0.0 <= HSK_reverse_e4218 <= 0.0
0.0 <= EAR120y <= 1000.0
0.0 <= EAR120y_reverse_c7353 <= 0.0
0.0 <= BCAROHX2 <= 1000.0
0.0 <= BCAROHX2_reverse_888eb <= 0.0
0.0 <= HPPK <= 1000.0
0.0 <= HPPK_reverse_e0ee3 <= 1000.0
0.0 <= PPNCL3 <= 1000.0
0.0 <= PPNCL3_reverse_cd065 <= 0.0
0.0 <= AHCi <= 1000.0
0.0 <= AHCi_reverse_d29ff <= 0.0
0.0 <= G6PDH2r <= 1000.0
0.0 <= G6PDH2r_reverse_19ddf <= 0.0
0.0 <= PMANM <= 1000.0
0.0 <= PMANM_reverse_53eb0 <= 1000.0
0.0 <= CPPPGO2 <= 0.0
0.0 <= CPPPGO2_reverse_e5000 <= 0.0
0.0 <= PC17M_1 <= 1000.0
0.0 <= PC17M_1_reverse_fc1bc <= 0.0
0.0 <= ACCOAC <= 1000.0
0.0 <= ACCOAC_reverse_9d1cd <= 0.0
0.0 <= CYNL <= 1000.0
0.0 <= CYNL_reverse_91a39 <= 0.0
0.0 <= CYOOum <= 1000.0
0.0 <= CYOOum_reverse_37909 <= 0.0
0.0 <= ACLSb <= 1000.0
0.0 <= ACLSb_reverse_588fa <= 0.0
0.0 <= DNMPPA <= 1000.0
0.0 <= DNMPPA_reverse_131b7 <= 0.0
0.0 <= METS_1 <= 1000.0
0.0 <= METS_1_reverse_65e3f <= 0.0
0.0 <= TRPS2 <= 1000.0
0.0 <= TRPS2_reverse_cd73f <= 0.0
0.0 <= PRUK <= 1000.0
0.0 <= PRUK_reverse_a0fb4 <= 0.0
0.0 <= FNOR_1 <= 1000.0
0.0 <= FNOR_1_reverse_80b2d <= 1000.0
0.0 <= GART <= 1000.0
0.0 <= GART_reverse_61742 <= 0.0
0.0 <= G5SADs <= 1000.0
0.0 <= G5SADs_reverse_c7fa4 <= 1000.0
0.0 <= DMTPHT <= 1000.0
0.0 <= DMTPHT_reverse_a16f8 <= 0.0
0.0 <= SPMDabcpp <= 1000.0
0.0 <= SPMDabcpp_reverse_7abfe <= 0.0
0.0 <= DHAD2 <= 1000.0
0.0 <= DHAD2_reverse_755c6 <= 0.0
0.0 <= PRAMPC <= 1000.0
0.0 <= PRAMPC_reverse_54696 <= 0.0
0.0 <= 3OAS80 <= 1000.0
0.0 <= 3OAS80_reverse_c6446 <= 0.0
0.0 <= G1PCTYT <= 1000.0
0.0 <= G1PCTYT_reverse_16243 <= 0.0
0.0 <= BIOMASS_CELL_WALL <= 1000.0
0.0 <= BIOMASS_CELL_WALL_reverse_8d1a4 <= 0.0
0.0 <= CA2abcpp <= 1000.0
0.0 <= CA2abcpp_reverse_aa3d6 <= 0.0
0.0 <= UHGADA2 <= 1000.0
0.0 <= UHGADA2_reverse_e04ae <= 0.0
0.0 <= ASPO6 <= 1000.0
0.0 <= ASPO6_reverse_ec15c <= 0.0
0.0 <= ASPK <= 1000.0
0.0 <= ASPK_reverse_115d7 <= 0.0
0.0 <= DXPS <= 1000.0
0.0 <= DXPS_reverse_86aca <= 0.0
0.0 <= PRATPP <= 1000.0
0.0 <= PRATPP_reverse_99bf0 <= 0.0
0.0 <= NH4tpp <= 1000.0
0.0 <= NH4tpp_reverse_eca16 <= 0.0
0.0 <= PAPSR <= 1000.0
0.0 <= PAPSR_reverse_75961 <= 0.0
0.0 <= NAD_H2 <= 1000.0
0.0 <= NAD_H2_reverse_69196 <= 1000.0
0.0 <= CYRDAAT <= 1000.0
0.0 <= CYRDAAT_reverse_d0652 <= 0.0
0.0 <= NTPP8 <= 1000.0
0.0 <= NTPP8_reverse_ce3f8 <= 0.0
0.0 <= PC11M <= 1000.0
0.0 <= PC11M_reverse_f4161 <= 0.0
0.0 <= ARGabcpp <= 1000.0
0.0 <= ARGabcpp_reverse_2f37a <= 0.0
0.0 <= PMDPHT <= 1000.0
0.0 <= PMDPHT_reverse_8a0fd <= 1000.0
0.0 <= DAPE <= 1000.0
0.0 <= DAPE_reverse_e08be <= 1000.0
0.0 <= LYCOPC <= 1000.0
0.0 <= LYCOPC_reverse_fd996 <= 1000.0
0.0 <= RB15BPtcx <= 1000.0
0.0 <= RB15BPtcx_reverse_6fe05 <= 0.0
0.0 <= GLCBRAN3 <= 1000.0
0.0 <= GLCBRAN3_reverse_4cd37 <= 0.0
0.0 <= DB4PS <= 1000.0
0.0 <= DB4PS_reverse_43dd1 <= 0.0
0.0 <= DXPRIi <= 1000.0
0.0 <= DXPRIi_reverse_85956 <= 0.0
0.0 <= GTPCII <= 1000.0
0.0 <= GTPCII_reverse_a84d9 <= 0.0
0.0 <= RBFSa <= 1000.0
0.0 <= RBFSa_reverse_61d96 <= 0.0
0.0 <= GLUTRS <= 1000.0
0.0 <= GLUTRS_reverse_b214d <= 0.0
0.0 <= ALDD2y <= 1000.0
0.0 <= ALDD2y_reverse_03afb <= 1000.0
0.0 <= EHGLAT <= 1000.0
0.0 <= EHGLAT_reverse_8439b <= 1000.0
0.0 <= METAT <= 1000.0
0.0 <= METAT_reverse_793ef <= 0.0
0.0 <= DHORTS <= 1000.0
0.0 <= DHORTS_reverse_82d73 <= 1000.0
0.0 <= PDX5PS2 <= 1000.0
0.0 <= PDX5PS2_reverse_cfb17 <= 1000.0
0.0 <= GAPDi_nadp <= 1000.0
0.0 <= GAPDi_nadp_reverse_782a6 <= 0.0
0.0 <= PGCD <= 1000.0
0.0 <= PGCD_reverse_1bc76 <= 1000.0
0.0 <= AIRC3 <= 1000.0
0.0 <= AIRC3_reverse_f015f <= 1000.0
0.0 <= UMPK <= 1000.0
0.0 <= UMPK_reverse_ae8e3 <= 1000.0
0.0 <= CBPS <= 1000.0
0.0 <= CBPS_reverse_80907 <= 0.0
0.0 <= 3HAD180 <= 1000.0
0.0 <= 3HAD180_reverse_c801d <= 1000.0
0.0 <= IPPMIb <= 0.0
0.0 <= IPPMIb_reverse_e37a1 <= 1000.0
0.0 <= RZ5PP <= 1000.0
0.0 <= RZ5PP_reverse_b2942 <= 0.0
0.0 <= RBFSb_1 <= 1000.0
0.0 <= RBFSb_1_reverse_7d59e <= 0.0
0.0 <= GLNabcpp <= 1000.0
0.0 <= GLNabcpp_reverse_c0546 <= 0.0
0.0 <= NDPK8 <= 1000.0
0.0 <= NDPK8_reverse_13dd1 <= 1000.0
0.0 <= PC6YM_1 <= 1000.0
0.0 <= PC6YM_1_reverse_0b971 <= 0.0
0.0 <= DDPA <= 1000.0
0.0 <= DDPA_reverse_575e8 <= 0.0
0.0 <= ACOTA <= 1000.0
0.0 <= ACOTA_reverse_c4379 <= 1000.0
0.0 <= FBP <= 1000.0
0.0 <= FBP_reverse_bf2c9 <= 0.0
0.0 <= MNabc_1 <= 1000.0
0.0 <= MNabc_1_reverse_d9c27 <= 0.0
0.0 <= NTD7 <= 1000.0
0.0 <= NTD7_reverse_20dab <= 0.0
0.0 <= MPOMMM <= 1000.0
0.0 <= MPOMMM_reverse_30349 <= 0.0
0.0 <= MTHFD <= 1000.0
0.0 <= MTHFD_reverse_c10fd <= 1000.0
0.0 <= PANTS <= 1000.0
0.0 <= PANTS_reverse_11dcb <= 0.0
0.0 <= TMPK <= 1000.0
0.0 <= TMPK_reverse_b7673 <= 0.0
0.0 <= KARI_23dhmp_1 <= 1000.0
0.0 <= KARI_23dhmp_1_reverse_ef22e <= 0.0
0.0 <= IPMD <= 1000.0
0.0 <= IPMD_reverse_d7a5e <= 0.0
0.0 <= 3PGtcx <= 1000.0
0.0 <= 3PGtcx_reverse_a3768 <= 0.0
0.0 <= CDPMEK <= 1000.0
0.0 <= CDPMEK_reverse_01872 <= 0.0
0.0 <= CITCIa <= 1000.0
0.0 <= CITCIa_reverse_6a08b <= 1000.0
0.0 <= DVOCHR_1 <= 1000.0
0.0 <= DVOCHR_1_reverse_1b3d8 <= 0.0
0.0 <= H2CO3_NAt_syn <= 1000.0
0.0 <= H2CO3_NAt_syn_reverse_5b4d9 <= 1000.0
0.0 <= HEMEOS <= 1000.0
0.0 <= HEMEOS_reverse_b63ba <= 1000.0
0.0 <= RPE <= 1000.0
0.0 <= RPE_reverse_a1b04 <= 1000.0
0.0 <= MPOMT_1 <= 1000.0
0.0 <= MPOMT_1_reverse_63f7f <= 0.0
0.0 <= UAMAS <= 1000.0
0.0 <= UAMAS_reverse_2b5e6 <= 0.0
0.0 <= CITCIb <= 1000.0
0.0 <= CITCIb_reverse_a5ab2 <= 1000.0
0.0 <= BPNT2 <= 1000.0
0.0 <= BPNT2_reverse_ab8bb <= 0.0
0.0 <= BIOMASS_COFACTORS <= 1000.0
0.0 <= BIOMASS_COFACTORS_reverse_d79f8 <= 0.0
0.0 <= HSERTA <= 1000.0
0.0 <= HSERTA_reverse_23c8f <= 0.0
0.0 <= NDPK1 <= 1000.0
0.0 <= NDPK1_reverse_9216a <= 1000.0
0.0 <= PGL <= 1000.0
0.0 <= PGL_reverse_2bb6b <= 0.0
0.0 <= EAR160y <= 1000.0
0.0 <= EAR160y_reverse_e0622 <= 0.0
0.0 <= MECDPDHf <= 1000.0
0.0 <= MECDPDHf_reverse_07da8 <= 0.0
0.0 <= MTHFR3_1 <= 1000.0
0.0 <= MTHFR3_1_reverse_1a948 <= 0.0
0.0 <= 3HAD140 <= 1000.0
0.0 <= 3HAD140_reverse_13958 <= 1000.0
0.0 <= FBA3 <= 1000.0
0.0 <= FBA3_reverse_0d49f <= 1000.0
0.0 <= LDAPAT <= 0.0
0.0 <= LDAPAT_reverse_81d9c <= 1000.0
0.0 <= MG2uabcpp <= 1000.0
0.0 <= MG2uabcpp_reverse_adeed <= 0.0
0.0 <= HCO3E_1_cx <= 1000.0
0.0 <= HCO3E_1_cx_reverse_3a8f8 <= 1000.0
0.0 <= ACODA <= 1000.0
0.0 <= ACODA_reverse_504cc <= 1000.0
0.0 <= GLU5K <= 1000.0
0.0 <= GLU5K_reverse_0d895 <= 0.0
0.0 <= EAR100y <= 1000.0
0.0 <= EAR100y_reverse_863b6 <= 0.0
0.0 <= PGM <= 1000.0
0.0 <= PGM_reverse_fc9af <= 1000.0
0.0 <= ASPOb <= 1000.0
0.0 <= ASPOb_reverse_0f7c6 <= 0.0
0.0 <= DM_h2_c <= 1000.0
0.0 <= DM_h2_c_reverse_84240 <= 0.0
0.0 <= ACS <= 1000.0
0.0 <= ACS_reverse_37635 <= 0.0
0.0 <= AMPTASECG <= 1000.0
0.0 <= AMPTASECG_reverse_11d5d <= 0.0
0.0 <= SHCHCS3 <= 1000.0
0.0 <= SHCHCS3_reverse_fb361 <= 0.0
0.0 <= ATPPRT <= 1000.0
0.0 <= ATPPRT_reverse_00060 <= 0.0
0.0 <= NDH_1_4_um_copy1 <= 1000.0
0.0 <= NDH_1_4_um_copy1_reverse_4512a <= 0.0
0.0 <= UAGCVT <= 1000.0
0.0 <= UAGCVT_reverse_ba1ab <= 0.0
0.0 <= ADSL2r <= 1000.0
0.0 <= ADSL2r_reverse_42348 <= 1000.0
0.0 <= PRASCSi <= 1000.0
0.0 <= PRASCSi_reverse_11704 <= 1000.0
0.0 <= MG2tex <= 1000.0
0.0 <= MG2tex_reverse_a1983 <= 1000.0
0.0 <= HPROb <= 1000.0
0.0 <= HPROb_reverse_9e6b2 <= 0.0
0.0 <= NTPP2 <= 1000.0
0.0 <= NTPP2_reverse_bff4f <= 0.0
0.0 <= TRDR <= 1000.0
0.0 <= TRDR_reverse_6372e <= 0.0
0.0 <= NDPK6 <= 1000.0
0.0 <= NDPK6_reverse_d41ea <= 1000.0
0.0 <= GLUPRT <= 1000.0
0.0 <= GLUPRT_reverse_1f180 <= 0.0
0.0 <= PTRCabcpp <= 1000.0
0.0 <= PTRCabcpp_reverse_96b27 <= 0.0
0.0 <= UPP3MT <= 1000.0
0.0 <= UPP3MT_reverse_2adf0 <= 0.0
0.0 <= DHNCOAS <= 1000.0
0.0 <= DHNCOAS_reverse_af3a9 <= 0.0
0.0 <= MCOATA <= 1000.0
0.0 <= MCOATA_reverse_d10f2 <= 0.0
0.0 <= PMPK <= 1000.0
0.0 <= PMPK_reverse_48b12 <= 0.0
0.0 <= HMBS <= 1000.0
0.0 <= HMBS_reverse_23a06 <= 0.0
0.0 <= PGLYCP <= 1000.0
0.0 <= PGLYCP_reverse_9063f <= 0.0
0.0 <= UAGAAT2 <= 1000.0
0.0 <= UAGAAT2_reverse_8209e <= 0.0
0.0 <= HTHRPDH <= 1000.0
0.0 <= HTHRPDH_reverse_9ee3b <= 0.0
0.0 <= BCT1_syn <= 1000.0
0.0 <= BCT1_syn_reverse_8b530 <= 0.0
0.0 <= IPDDI <= 1000.0
0.0 <= IPDDI_reverse_6c5f9 <= 1000.0
0.0 <= GLYALDDy <= 1000.0
0.0 <= GLYALDDy_reverse_7e106 <= 1000.0
0.0 <= CITMS <= 1000.0
0.0 <= CITMS_reverse_37134 <= 0.0
0.0 <= IMPC <= 1000.0
0.0 <= IMPC_reverse_efa41 <= 1000.0
0.0 <= Htcx <= 1000.0
0.0 <= Htcx_reverse_e3f6b <= 1000.0
0.0 <= DHQTi <= 1000.0
0.0 <= DHQTi_reverse_c4498 <= 1000.0
0.0 <= SPODM <= 1000.0
0.0 <= SPODM_reverse_2648f <= 0.0
0.0 <= MAN6PI <= 1000.0
0.0 <= MAN6PI_reverse_d96f0 <= 1000.0
0.0 <= 3OAS120 <= 1000.0
0.0 <= 3OAS120_reverse_06658 <= 0.0
0.0 <= PGAMT <= 1000.0
0.0 <= PGAMT_reverse_52c23 <= 1000.0
0.0 <= PSERT <= 1000.0

In [ ]:
[v.name for v in mytfa.variables if v.name.startswith("LC_")]

['LC_gam6p_c',
 'LC_cgly_c',
 'LC_achms_c',
 'LC_pcox_u',
 'LC_octe9ACP_c',
 'LC_fdp_c',
 'LC_5caiz_c',
 'LC_pep_c',
 'LC_coa_c',
 'LC_hgbam_c',
 'LC_nac_c',
 'LC_r3mmal_c',
 'LC_leu__L_c',
 'LC_ahcys_c',
 'LC_ru5p__D_c',
 'LC_14dhncoa_c',
 'LC_h2o_cx_c',
 'LC_h2s_c',
 'LC_orot_c',
 'LC_g1p_c',
 'LC_3hdecACP_c',
 'LC_na1_c',
 'LC_2pglyc_c',
 'LC_ala_B_c',
 'LC_glyc3p_c',
 'LC_pqh2_um_p',
 'LC_26dap_LL_c',
 'LC_ddcaACP_c',
 'LC_2pglyc_cx_c',
 'LC_trdox_c',
 'LC_3oddecACP_c',
 'LC_glu__D_c',
 'LC_h_cx_c',
 'LC_dutp_c',
 'LC_paps_c',
 'LC_mg2_c',
 'LC_hdeACP_c',
 'LC_o2_c',
 'LC_anth_c',
 'LC_dhpt_c',
 'LC_thex2eACP_c',
 'LC_fmn_c',
 'LC_pppi_c',
 'LC_udp_c',
 'LC_cit_c',
 'LC_acACP_c',
 'LC_uama_c',
 'LC_eig3p_c',
 'LC_3c4mop_c',
 'LC_lys__L_c',
 'LC_13dpg_c',
 'LC_gmp_c',
 'LC_utp_c',
 'LC_trdrd_c',
 'LC_so4_c',
 'LC_5apru_c',
 'LC_hmppp9_c',
 'LC_pydx5p_c',
 'LC_2dhp_c',
 'LC_ade_c',
 'LC_asp__L_c',
 'LC_2sephchc_c',
 'LC_acg5p_c',
 'LC_gdp_c',
 'LC_hgbyr_c',
 'LC_palmACP_c',
 'LC_pser__L_c',
 'LC_ocACP_c',
 'LC_dttp_c',
 'LC_6pgc_c',
 'LC_gcald_c',
 'LC_2p4c2me_c',
 'LC_cmp_c',
 'LC_bm_pro_c',
 'LC_pi_c',
 'LC_pnto__R_c',
 'LC_dump_c',
 'LC_omppp9_c',
 'LC_23dhmp_c',
 'LC_gtp_c',
 'LC_4h2oglt_c',
 'LC_prfp_c',
 'LC_man1p_c',
 'LC_dxyl5p_c',
 'LC_3hddecACP_c',
 'LC_cu2_c',
 'LC_malACP_c',
 'LC_2mahmp_c',
 'LC_phpyr_c',
 'LC_fe2_c',
 'LC_phllqne_c',
 'LC_toct2eACP_c',
 'LC_dgdp_c',
 'LC_uaccg_c',
 'LC_acald_c',
 'LC_o2s_c',
 'LC_alac__S_c',
 'LC_3hmop_c',
 'LC_4abz_c',
 'LC_prbamp_c',
 'LC_ca2_c',
 'LC_glyclt_c',
 'LC_butACP_c',
 'LC_4ppcys_c',
 'LC_udpgal_c',
 'LC_f6p_c',
 'LC_lac__D_c',
 'LC_his__L_c',
 'LC_agdpcbi_c',
 'LC_s17bp_c',
 'LC_dctp_c',
 'LC_thf_c',
 'LC_25aics_c',
 'LC_ni2_c',
 'LC_dtdp4d6dg_c',
 'LC_malcoa_c',
 'LC_fum_c',
 'LC_bm_cw_c',
 'LC_ACP_c',
 'LC_mlthf_c',
 'LC_h_p',
 'LC_dhf_c',
 'LC_dudp_c',
 'LC_3omrsACP_c',
 'LC_trnaglu_c',
 'LC_pre6a_c',
 'LC_ametam_c',
 'LC_3hhexACP_c',
 'LC_4ppan_c',
 'LC_quln_c',
 'LC_frdp_c',
 'LC_glyald_c',
 'LC_uacgam_c',
 'LC_pram_c',
 'LC_26dap__M_c',
 'LC_gdpmann_c',
 'LC_db4p_c',
 'LC_actACP_c',
 'LC_actp_c',
 'LC_ugmd_c',
 'LC_s7p_c',
 'LC_cbm_c',
 'LC_co2_c',
 'LC_zeax_c',
 'LC_ptrc_c',
 'LC_adp_c',
 'LC_3a2oxpp_c',
 'LC_aspsa_c',
 'LC_tdec2eACP_c',
 'LC_phom_c',
 'LC_amylose_c',
 'LC_5mdr1p_c',
 'LC_rb15bp_cx_c',
 'LC_bcryptox_c',
 'LC_spmd_c',
 'LC_udpsq_c',
 'LC_h2_c',
 'LC_adocbip_c',
 'LC_phycy_c',
 'LC_nadh_c',
 'LC_aps_c',
 'LC_dpcoa_c',
 'LC_xu5p__D_c',
 'LC_no2_c',
 'LC_4hbz_c',
 'LC_3odecACP_c',
 'LC_dhnpt_c',
 'LC_5aprbu_c',
 'LC_iasp_c',
 'LC_nmn_c',
 'LC_bm_pigm_c',
 'LC_2cpr5p_c',
 'LC_pchlld_c',
 'LC_o2_u',
 'LC_ala__L_c',
 'LC_3c2hmp_c',
 'LC_pyr_c',
 'LC_hco3_c',
 'LC_pan4p_c',
 'LC_succ_c',
 'LC_citac_c',
 'LC_h2o_c',
 'LC_h_c',
 'LC_ugmda_c',
 'LC_pq_um_p',
 'LC_man6p_c',
 'LC_cobalt2_c',
 'LC_gam1p_c',
 'LC_argsuc_c',
 'LC_dhap_c',
 'LC_mn2_c',
 'LC_u3hga2_c',
 'LC_2obut_c',
 'LC_dtmp_c',
 'LC_fpram_c',
 'LC_ump_c',
 'LC_3pg_cx_c',
 'LC_pq_cm_c',
 'LC_ahdt_c',
 'LC_npdp_c',
 'LC_dhor__S_c',
 'LC_3opalmACP_c',
 'LC_glx_c',
 'LC_thdp_c',
 'LC_fprica_c',
 'LC_adocbl_c',
 'LC_thr__L_c',
 'LC_so3_c',
 'LC_2m6sbenzq_c',
 'LC_hco3_cx_c',
 'LC_glu5p_c',
 'LC_3hmrsACP_c',
 'LC_4c2me_c',
 'LC_damp_c',
 'LC_histda_c',
 'LC_gthox_c',
 'LC_amp_c',
 'LC_23dhmb_c',
 'LC_5mdru1p_c',
 'LC_mppp9_c',
 'LC_cdp_c',
 'LC_dcaACP_c',
 'LC_2me4p_c',
 'LC_3hpalmACP_c',
 'LC_2ahbut_c',
 'LC_caro_c',
 'LC_3dhq_c',
 'LC_4adcho_c',
 'LC_glu__L_c',
 'LC_bm_cofactors_c',
 'LC_34hpp_c',
 'LC_ctp_c',
 'LC_pqh2_cm_c',
 'LC_fad_c',
 'LC_2shchc_c',
 'LC_dhna_c',
 'LC_co2_cx_c',
 'LC_acg5sa_c',
 'LC_ala__D_c',
 'LC_aicar_c',
 'LC_g6p_c',
 'LC_glu5sa_c',
 'LC_ac_c',
 'LC_pre3b_c',
 'LC_mthgxl_c',
 'LC_3mop_c',
 'LC_5drib_c',
 'LC_e4hglu_c',
 'LC_dgtp_c',
 'LC_cys__L_c',
 'LC_bm_rna_c',
 'LC_hisp_c',
 'LC_lycop_c',
 'LC_citr__L_c',
 'LC_2ahhmp_c',
 'LC_pdx5p_c',
 'LC_2mecdp_c',
 'LC_cbasp_c',
 'LC_dnad_c',
 'LC_datp_c',
 'LC_prlp_c',
 'LC_toctd2eACP_c',
 'LC_cholphya_c',
 'LC_glc__D_c',
 'LC_o2_cx_c',
 'LC_orot5p_c',
 'LC_k_c',
 'LC_amet_c',
 'LC_2ippm_c',
 'LC_pro__L_c',
 'LC_cpppg3_c',
 'LC_h2mb4p_c',
 'LC_thmmp_c',
 'LC_cdpglc_c',
 'LC_xmp_c',
 'LC_co2dam_c',
 'LC_fdxox_c',
 'LC_orn_c',
 'LC_2ahhmd_c',
 'LC_pre6b_c',
 'LC_gln__L_c',
 'LC_3ohexACP_c',
 'LC_3pg_c',
 'LC_pheme_c',
 'LC_methf_c',
 'LC_co1dam_c',
 'LC_mppp9me_c',
 'LC_bm_dna_c',
 'LC_fe3_c',
 'LC_zn2_c',
 'LC_hexACP_c',
 'LC_prephytedp_c',
 'LC_glu1sa_c',
 'LC_chor_c',
 'LC_4per_c',
 'LC_glucys_c',
 'LC_dmpp_c',
 'LC_inost_c',
 'LC_4hthdp_c',
 'LC_applp_c',
 'LC_oaa_c',
 'LC_no3_c',
 'LC_uamag_c',
 'LC_dialurate_c',
 'LC_gcarote_c',
 'LC_ser__L_c',
 'LC_1pyr5c_c',
 'LC_ppi_c',
 'LC_ribflv_c',
 'LC_tyr__L_c',
 'LC_pap_c',
 'LC_25dhpp_c',
 'LC_3nphb_c',
 'LC_h2o_p',
 'LC_pre8_c',
 'LC_3dhsk_c',
 'LC_dhpmp_c',
 'LC_glyc__R_c',
 'LC_dad_5_c',
 'LC_2dda7p_c',
 'LC_acglu_c',
 'LC_imp_c',
 'LC_nad_c',
 'LC_dcamp_c',
 'LC_bm_carbs_c',
 'LC_2ahethmpp_c',
 'LC_imacp_c',
 'LC_dmlz_c',
 'LC_g3p_c',
 'LC_dadp_c',
 'LC_o2_p',
 'LC_fmnh2_c',
 'LC_nadph_c',
 'LC_cbp_c',
 'LC_mi3p__D_c',
 'LC_tmrs2eACP_c',
 'LC_6pgl_c',
 'LC_ppp9_c',
 'LC_mobd_c',
 'LC_bm_memlip_c',
 'LC_dad_2_c',
 'LC_biliverd_c',
 'LC_pre4_c',
 'LC_ggdp_c',
 'LC_pre3a_c',
 'LC_rb15bp_c',
 'LC_3hbutACP_c',
 'LC_histd_c',
 'LC_pphn_c',
 'LC_nicrnt_c',
 'LC_3ooctdACP_c',
 'LC_atp_c',
 'LC_lipidX2_c',
 'LC_2pg_c',
 'LC_pppg9_c',
 'LC_uagmda_c',
 'LC_met__L_c',
 'LC_phyto_c',
 'LC_4hpro_LT_c',
 'LC_1p3h5c_c',
 'LC_hemeO_c',
 'LC_lgt__S_c',
 'LC_h2o_u',
 'LC_adcobhex_c',
 'LC_co_c',
 'LC_sbzcoa_c',
 'LC_e4p_c',
 'LC_accoa_c',
 'LC_asn__L_c',
 'LC_mal__L_c',
 'LC_ocdcaACP_c',
 'LC_ichor_c',
 'LC_pant__R_c',
 'LC_phdp_c',
 'LC_r5p_c',
 'LC_grdp_c',
 'LC_ohpb_c',
 'LC_ipdp_c',
 'LC_arg__L_c',
 'LC_phe__L_c',
 'LC_acgam1p_c',
 'LC_nadp_c',
 'LC_3ig3p_c',
 'LC_val__L_c',
 'LC_dmbzid_c',
 'LC_2a3pp_c',
 'LC_3mob_c',
 'LC_5prdmbz_c',
 'LC_rdmbzi_c',
 'LC_5mthf_c',
 'LC_3hoctACP_c',
 'LC_dvpchlda_c',
 'LC_10fthf_c',
 'LC_4r5au_c',
 'LC_skm_c',
 'LC_gar_c',
 'LC_for_c',
 'LC_dmtphllqne_c',
 'LC_skm5p_c',
 'LC_citm_c',
 'LC_udpg_c',
 'LC_5mta_c',
 'LC_dcdp_c',
 'LC_pcrd_u',
 'LC_myrsACP_c',
 'LC_glutrna_c',
 'LC_adcobdam_c',
 'LC_nh4_c',
 'LC_hom__L_c',
 'LC_acser_c',
 'LC_pre5_c',
 'LC_fdxrd_c',
 'LC_sucbz_c',
 'LC_prpp_c',
 'LC_5aizc_c',
 'LC_dtdp4d6dm_c',
 'LC_but2eACP_c',
 'LC_chlld_c',
 'LC_h_u',
 'LC_gly_c',
 'LC_uppg3_c',
 'LC_dtdp_c',
 'LC_uamr_c',
 'LC_trp__L_c',
 'LC_udcpdp_c',
 'LC_lipidAds2_c',
 'LC_hpyr_c',
 'LC_hcys__L_c',
 'LC_prbatp_c',
 'LC_indole_c',
 'LC_dscl_c',
 'LC_glycogen_c',
 'LC_5aop_c',
 'LC_gthrd_c',
 'LC_fgam_c',
 'LC_adpglc_c',
 'LC_air_c',
 'LC_3hoctaACP_c',
 'LC_hmbil_c',
 'LC_3psme_c',
 'LC_thrp_c',
 'LC_akg_c',
 'LC_thmpp_c',
 'LC_tpalm2eACP_c',
 'LC_h2o2_c',
 'LC_alaala_c',
 'LC_pran_c',
 'LC_tddec2eACP_c',
 'LC_icit_c',
 'LC_3ooctACP_c',
 'LC_4ampm_c',
 'LC_adn_c',
 'LC_4pasp_c',
 'LC_3php_c',
 'LC_ppbng_c',
 'LC_acorn_c',
 'LC_ile__L_c',
 'LC_3c3hmp_c',
 'LC_phthr_c',
 'LC_cynt_c',
 'LC_pqh2_c',
 'LC_cthzp_c',
 'LC_14glucan_c',
 'LC_cobalt2_p',
 'LC_zn2_p',
 'LC_so4_p',
 'LC_spmd_p',
 'LC_ca2_p',
 'LC_nh4_p',
 'LC_arg__L_p',
 'LC_gln__L_p',
 'LC_mn2_p',
 'LC_hco3_p',
 'LC_mg2_p',
 'LC_ptrc_p',
 'LC_fe2_p',
 'LC_cu2_p',
 'LC_k_p',
 'LC_no3_p',
 'LC_fe3_p',
 'LC_mobd_p',
 'LC_ni2_p',
 'LC_cynt_p',
 'LC_pi_p',
 'LC_h2o_e',
 'LC_o2_e',
 'LC_co2_e',
 'LC_cobalt2_e',
 'LC_zn2_e',
 'LC_so4_e',
 'LC_spmd_e',
 'LC_ca2_e',
 'LC_nh4_e',
 'LC_arg__L_e',
 'LC_gln__L_e',
 'LC_mn2_e',
 'LC_hco3_e',
 'LC_mg2_e',
 'LC_ptrc_e',
 'LC_fe2_e',
 'LC_cu2_e',
 'LC_k_e',
 'LC_no3_e',
 'LC_fe3_e',
 'LC_mobd_e',
 'LC_ni2_e',
 'LC_na1_e',
 'LC_cynt_e',
 'LC_co2_p',
 'LC_h_e',
 'LC_na1_p',
 'LC_pi_e',
 'LC_dkmpp_c',
 'LC_dhmtp_c',
 'LC_2kmb_c',
 'LC_tczcaro_c',
 'LC_dczcaro_c',
 'LC_ttclyco_c',
 'LC_6pthp_c',
 'LC_thbpt_c',
 'LC_gthbpt_c',
 'LC_iscssh_c',
 'LC_iscsh_c',
 'LC_this_c',
 'LC_athis_c',
 'LC_thissh_c',
 'LC_imgly_c',
 'LC_2c4mthzep_c',
 'LC_sheme_c',
 'LC_malcoame_c',
 'LC_ogmeACP_c',
 'LC_hgmeACP_c',
 'LC_egmeACP_c',
 'LC_gmeACP_c',
 'LC_opmeACP_c',
 'LC_hpmeACP_c',
 'LC_epmeACP_c',
 'LC_pmeACP_c',
 'LC_pimACP_c',
 'LC_meoh_c',
 'LC_8aonn_c',
 'LC_dann_c',
 'LC_amob_c',
 'LC_dtbt_c',
 'LC_btn_c',
 'LC_btamp_c',
 'LC_octapb_c',
 'LC_lipopb_c',
 'LC_meoh_p',
 'LC_meoh_e',
 'LC_cph4_c',
 'LC_cdg_c',
 'LC_preq0_c',
 'LC_preq1_c',
 'LC_preqtrna_c',
 'LC_epxqtrna_c',
 'LC_quetrna_c',
 'LC_udpglcur_c',
 'LC_udpxyl_c',
 'LC_gdpddman_c',
 'LC_gdpfuc_c',
 'LC_cdp4dh6doglc_c',
 'LC_ocdca_c',
 'LC_ocdcal_c',
 'LC_hpdcn_c',
 'LC_1hdecg3p_c',
 'LC_1hdec9eg3p_c',
 'LC_1odec9eg3p_c',
 'LC_pa160_c',
 'LC_pa1619Z160_c',
 'LC_pa161_c',
 'LC_pa1819Z1619Z_c',
 'LC_pa1819Z160_c',
 'LC_12dgr160_c',
 'LC_12dgr1619Z160_c',
 'LC_12dgr161_c',
 'LC_12dgr1819Z1619Z_c',
 'LC_12dgr1819Z160_c',
 'LC_sqdg160_c',
 'LC_sqdg1619Z160_c',
 'LC_mgdg1619Z160_c',
 'LC_dgdg1619Z160_c',
 'LC_dgdg161_c',
 'LC_mgdg161_c',
 'LC_dgdg1819Z1619Z_c',
 'LC_mgdg1819Z1619Z_c',
 'LC_cdp12dgr1819Z160_c',
 'LC_pgp1819Z160_c',
 'LC_pg1819Z160_c',
 'LC_glcdg1619Z160_c',
 'LC_glcdg161_c',
 'LC_glcdg1819Z1619Z_c',
 'LC_glcdg1819Z160_c',
 'LC_mgdg1819Z160_c',
 'LC_dgdg1819Z160Z_c',
 'LC_glntrna_c',
 'LC_trnagln_c',
 'LC_trnatyr_c',
 'LC_tyrtrna_c',
 'LC_trnamet_c',
 'LC_mettrna_c',
 'LC_trnaser_c',
 'LC_sertrna_c',
 'LC_glytrna_c',
 'LC_trnagly_c',
 'LC_protrna_c',
 'LC_trnapro_c',
 'LC_trnacys_c',
 'LC_cystrna_c',
 'LC_trnaarg_c',
 'LC_argtrna_c',
 'LC_trnatrp_c',
 'LC_trptrna_c',
 'LC_phetrna_c',
 'LC_trnaphe_c',
 'LC_trnahis_c',
 'LC_histrna_c',
 'LC_asntrna_c',
 'LC_asptrna_c',
 'LC_trnaasp_c',
 'LC_trnathr_c',
 'LC_thrtrna_c',
 'LC_trnaleu_c',
 'LC_leutrna_c',
 'LC_trnaile_c',
 'LC_iletrna_c',
 'LC_trnalys_c',
 'LC_lystrna_c',
 'LC_alatrna_c',
 'LC_trnaala_c',
 'LC_valtrna_c',
 'LC_trnaval_c',
 'LC_fmettrna_c',
 'LC_photon410_e',
 'LC_photon430_e',
 'LC_photon450_e',
 'LC_photon470_e',
 'LC_photon490_e',
 'LC_photon510_e',
 'LC_photon530_e',
 'LC_photon550_e',
 'LC_photon570_e',
 'LC_photon590_e',
 'LC_photon610_e',
 'LC_photon630_e',
 'LC_photon650_e',
 'LC_photon670_e',
 'LC_photon690_e',
 'LC_calxan_c',
 'LC_nstxan_c',
 'LC_chla_qy1_exc_c',
 'LC_pho_loss_c',
 'LC_u23ga2_c',
 'LC_u3aga2_c',
 'LC_ara5p_c',
 'LC_kdo8p_c',
 'LC_kdo_c',
 'LC_ckdo_c',
 'LC_uacmam_c',
 'LC_udcpp_c',
 'LC_unaga_c',
 'LC_kdolipid4cy_c',
 'LC_unagam_c',
 'LC_uaagmda_c',
 'LC_murein5p5p_p',
 'LC_murein5p5p5p_p',
 'LC_ala__D_p',
 'LC_murein5px4p_p',
 'LC_alaala_p',
 'LC_murein4px4p_p',
 'LC_murein4px4px4p_p',
 'LC_murein5p4p_p',
 'LC_murein4p4p_p',
 'LC_murein4p3p_p',
 'LC_murein3px4p_p',
 'LC_murein4px4p4p_p',
 'LC_murein3p3p_p',
 'LC_anhgm4p_p',
 'LC_anhgm3p_p',
 'LC_anhgm_c',
 'LC_LalaDgluMdapDala_c',
 'LC_anhgm4p_c',
 'LC_LalaDgluMdapDala_p',
 'LC_anhgm3p_c',
 'LC_anhm4p_c',
 'LC_anhm_c',
 'LC_anhm3p_c',
 'LC_LalaDgluMdap_c',
 'LC_LalaDglu_c',
 'LC_um4p_c',
 'LC_LalaLglu_c',
 'LC_pchlld_exc_c',
 'LC_fldox_c',
 'LC_fldrd_c',
 'LC_leu__L_p',
 'LC_leu__L_e',
 'LC_no2_p',
 'LC_chla_qy2_exc_c',
 'LC_p700_um_p',
 'LC_p700_exc_um_p',
 'LC_p680_exc_um_p',
 'LC_p680_um_p',
 'LC_hmgth_c',
 'LC_Sfglutth_c',
 'LC_5oxpro_c',
 'LC_acmum6p_c',
 'LC_cl_p',
 'LC_cl_c',
 'LC_cl_e',
 'LC_k_u',
 'LC_ps2d1_um_p',
 'LC_ps2d1_exc_um_p',
 'LC_34dhmald_c',
 'LC_34dhoxpeg_c',
 'LC_3hcddec5eACP_c',
 'LC_t3c5ddeceACP_c',
 'LC_3hcmrs7eACP_c',
 'LC_t3c7mrseACP_c',
 'LC_3hcpalm9eACP_c',
 'LC_t3c9palmeACP_c',
 'LC_3hcvac11eACP_c',
 'LC_t3c11vaceACP_c',
 'LC_3ocddec5eACP_c',
 'LC_3ocmrs7eACP_c',
 'LC_3ocpalm9eACP_c',
 'LC_3ocvac11eACP_c',
 'LC_cdec3eACP_c',
 'LC_cddec5eACP_c',
 'LC_tdeACP_c',
 'LC_aacoa_c',
 'LC_3hbcoa__R_c',
 'LC_4abut_c',
 'LC_sucsal_c',
 'LC_4abutn_c',
 'LC_appl_c',
 'LC_adocbi_c',
 'LC_C04051_c',
 'LC_4ahmmp_c',
 'LC_ala__L_p',
 'LC_glyc_c',
 'LC_etoh_c',
 'LC_id3acald_c',
 'LC_ind3ac_c',
 'LC_4gudbd_c',
 'LC_4gudbutn_c',
 'LC_pad_c',
 'LC_pac_c',
 'LC_iad_c',
 'LC_pmcoa_c',
 'LC_bamppald_c',
 'LC_echin_c',
 'LC_s_c',
 'LC_ficytc6_u',
 'LC_pqh2_u',
 'LC_focytc6_u',
 'LC_pq_u',
 'LC_pqh2_p',
 'LC_pq_p',
 'LC_ficytc6_p',
 'LC_focytc6_p',
 'LC_pcox_p',
 'LC_pcrd_p',
 'LC_cu2_u',
 'LC_mercppyr_c',
 'LC_cdpdhdecg_c',
 'LC_cdpdhdec9eg_c',
 'LC_pa180_c',
 'LC_cdpdodecg_c',
 'LC_pa181_c',
 'LC_cdpdodec11eg_c',
 'LC_pa181_9_c',
 'LC_cdpdodec9eg_c',
 'LC_pa182_9_12_c',
 'LC_cdpdodec912eg_c',
 'LC_pa183_6_9_12_c',
 'LC_cdpdodec6912eg_c',
 'LC_pa183_9_12_15_c',
 'LC_cdpdodec91215eg_c',
 'LC_pa184_6_9_12_15_c',
 'LC_cdpdodec691215eg_c',
 'LC_23dhdp_c',
 'LC_decdp_c',
 'LC_octeACP_c',
 'LC_f1p_c',
 'LC_5fthf_c',
 'LC_dtdpglu_c',
 'LC_1odecg3p_c',
 'LC_1odec11eg3p_c',
 'LC_octe_9_ACP_c',
 'LC_1odec912eg3p_c',
 'LC_octe_9_12_ACP_c',
 'LC_1odec691215eg3p_c',
 'LC_octe_6_9_12_15_ACP_c',
 'LC_1odec91215eg3p_c',
 'LC_octe_9_12_15_ACP_c',
 'LC_1odec6912eg3p_c',
 'LC_octe_6_9_12_ACP_c',
 'LC_fadh2_c',
 'LC_g6p_B_c',
 'LC_bglycogen_c',
 'LC_glcglyc_c',
 'LC_glcglyc_p',
 'LC_glutrna_gln_c',
 'LC_glu__L_p',
 'LC_2h3oppan_c',
 'LC_gly_p',
 'LC_35cgmp_c',
 'LC_3hmp_c',
 'LC_mmtsa_c',
 'LC_his__L_p',
 'LC_im4act_c',
 'LC_im4ac_c',
 'LC_lald__D_c',
 'LC_lald__L_c',
 'LC_12ppd__S_c',
 'LC_15dap_c',
 'LC_lys__L_p',
 'LC_mi1p__D_c',
 'LC_mppp9om_c',
 'LC_dvpchlld_c',
 'LC_n4abutn_c',
 'LC_4aabutn_c',
 'LC_q8_c',
 'LC_q8h2_c',
 'LC_didp_c',
 'LC_ditp_c',
 'LC_idp_c',
 'LC_itp_c',
 'LC_cytd_c',
 'LC_3ophb_c',
 'LC_2oph_c',
 'LC_lpam_c',
 'LC_adhlam_c',
 'LC_dhlam_c',
 'LC_pgp160_c',
 'LC_pgp161_c',
 'LC_pgp180_c',
 'LC_pgp181_c',
 'LC_pgp181_9_c',
 'LC_pgp182_9_12_c',
 'LC_pgp183_6_9_12_c',
 'LC_pgp183_9_12_15_c',
 'LC_pgp184_6_9_12_15_c',
 'LC_phytoe_c',
 'LC_r1p_c',
 'LC_pro__L_p',
 'LC_pyam5p_c',
 'LC_pydxn_c',
 'LC_pydx_c',
 'LC_pydam_c',
 'LC_sl26da_c',
 'LC_sl2a6o_c',
 'LC_ser__L_p',
 'LC_suc6p_c',
 'LC_sqdg161_c',
 'LC_12dgr180_c',
 'LC_sqdg180_c',
 'LC_12dgr181_c',
 'LC_sqdg181_c',
 'LC_12dgr181_9_c',
 'LC_12dgr182_9_12_c',
 'LC_sqdg182_9_12_c',
 'LC_12dgr183_6_9_12_c',
 'LC_sqdg183_6_9_12_c',
 'LC_12dgr183_9_12_15_c',
 'LC_12dgr184_6_9_12_15_c',
 'LC_sqdg184_6_9_12_15_c',
 'LC_sql_c',
 'LC_dptne_c',
 'LC_dpterol_c',
 'LC_succoa_c',
 'LC_sucr_p',
 'LC_dtdprmn_c',
 'LC_thfglu_c',
 'LC_4hba_c',
 'LC_4mpetz_c',
 'LC_dxyl_c',
 'LC_4mhetz_c',
 'LC_u23ga_c',
 'LC_u3hga_c',
 'LC_u3aga_c',
 'LC_uGgl_c',
 'LC_uGgla_c',
 'LC_uppg1_c',
 'LC_cpppg1_c',
 'LC_n2_e',
 'LC_fdxo_42_c',
 'LC_fdxr_42_c',
 'LC_n2_c',
 'LC_14glucan_p',
 'LC_23doguln_c',
 'LC_23doguln_p',
 'LC_2ddara_c',
 'LC_2doxg6p_c',
 'LC_2dglc_p',
 'LC_2dhguln_c',
 'LC_glcn_c',
 'LC_idon__L_c',
 'LC_2dglc_c',
 'LC_mercpeth_c',
 'LC_dtgcl_c',
 'LC_2hptcl_c',
 'LC_2hptcoa_c',
 'LC_msa_c',
 'LC_3amac_c',
 'LC_3hppnl_c',
 'LC_3hpp_c',
 'LC_uri_p',
 'LC_3ump_p',
 'LC_cytd_p',
 'LC_3cmp_p',
 'LC_adn_p',
 'LC_3amp_p',
 'LC_3gmp_p',
 'LC_gsn_p',
 'LC_oxadpcoa_c',
 'LC_LalaDgluMdap_p',
 'LC_sla_c',
 'LC_dhps_c',
 'LC_4abzglu_c',
 'LC_4hthr_c',
 'LC_5dglcn_c',
 'LC_sf_c',
 'LC_sfp_c',
 'LC_malthx_p',
 'LC_acac_c',
 'LC_btcoa_c',
 'LC_3ohcoa_c',
 'LC_3oocoa_c',
 'LC_hxcoa_c',
 'LC_occoa_c',
 'LC_3odcoa_c',
 'LC_3oddcoa_c',
 'LC_dcacoa_c',
 'LC_ddcacoa_c',
 'LC_3otdcoa_c',
 'LC_3ohdcoa_c',
 'LC_tdcoa_c',
 'LC_3ohodcoa_c',
 'LC_pmtcoa_c',
 'LC_ppcoa_c',
 'LC_ppa_c',
 'LC_acgam6p_c',
 'LC_acgam_p',
 'LC_acmana_p',
 'LC_acmanap_c',
 'LC_acmum_p',
 'LC_acnam_c',
 'LC_acmana_c',
 'LC_b2coa_c',
 'LC_acolipa_p',
 'LC_acolipa_e',
 'LC_aconm_c',
 'LC_acon_T_c',
 'LC_acon_C_c',
 'LC_oxalcoa_c',
 'LC_oxa_c',
 'LC_ribflv_p',
 'LC_fmn_p',
 'LC_ddcap_c',
 'LC_ttdcap_c',
 'LC_ttdceap_c',
 'LC_hdcap_c',
 'LC_hdceap_c',
 'LC_ocdcap_c',
 'LC_ocdceap_c',
 'LC_apoACP_c',
 'LC_ac_p',
 'LC_adocbl_p',
 'LC_adocbl_e',
 'LC_adprib_c',
 'LC_anhgm_p',
 'LC_adphep_LD_c',
 'LC_adphep_DD_c',
 'LC_ag_e',
 'LC_ag_c',
 'LC_S2hglut_c',
 'LC_mththf_c',
 'LC_mththf_p',
 'LC_akg_p',
 'LC_pacald_c',
 'LC_ppal_c',
 'LC_dha_c',
 'LC_all6p_c',
 'LC_allul6p_c',
 'LC_alltt_c',
 'LC_alltn_c',
 'LC_all__D_p',
 'LC_all__D_c',
 'LC_alpp_p',
 'LC_lpp_p',
 'LC_pe160_p',
 'LC_2agpe160_p',
 'LC_pg160_p',
 'LC_2agpg160_p',
 'LC_acetol_c',
 'LC_malt_c',
 'LC_maltttr_c',
 'LC_malttr_c',
 'LC_maltpt_c',
 ...]

# Sensitivity analysis

In [ ]:
for phbv_flux in [0.25, 0.5, 1.0, 1.5, 10, 100, 1000]:

    with model:
        # Fix PHBV synthesis flux
        rxn = cobra_model_mat.reactions.PHBVS_syn
        rxn.lower_bound = phbv_flux
        rxn.upper_bound = phbv_flux

        # ---------- FBA ----------
        fba_sol = cobra_model_mat.optimize()
        fba_value = fba_sol.objective_value

        # ---------- TFA ----------
        tfa_sol = mytfa.optimize()
        tfa_value = tfa_sol.objective_value

        print(f"PHBV flux = {phbv_flux:.2f}")
        print(f"  FBA solution: {fba_value:.5g}")
        print(f"  TFA solution: {tfa_value:.5g}")
        print(f"  TFA feasible: {tfa_sol.status == 'optimal'}")

# Find reactions for building lexicon for iDT1294

In [ ]:
# Add PHB_REACTIONS

# Acetyl-CoA C-acetyltransferase
#Acetyl-CoA:acetoacetyl-CoA transferase
#Acetoacetyl CoA reductase
#3 hydroxyacyl CoA dehydrogenase  acetoacetyl CoA
#3-ketoacyl-CoA thiolase

PHB_REACTIONS = [
    "ACACT1r",
    "ACACCT",
    "AACOAR_syn",
    "HACD1_2",
    "HACD1",
    "HACD1i",
    "KAT1"
]

phb_mets = set()

for rxn_id in PHB_REACTIONS:
    rxn = cobra_model_mat.reactions.get_by_id(rxn_id)
    for met in rxn.metabolites:
        phb_mets.add(met)

for met in sorted(phb_mets, key=lambda m: m.id):
    print(f"{met.id}\t{met.name}\t{met.formula}\t{met.compartment}")

3hbcoa__R_c	(R)-3-Hydroxybutyryl-CoA	C25H39N7O18P3S	c
3hbcoa_c	(S)-3-Hydroxybutanoyl-CoA	C25H38N7O18P3S	c
3hbycoa_c	S  3 Hydroxybutyryl CoA C25H38N7O18P3S	C25H38N7O18P3S	c
aacoa_c	Acetoacetyl-CoA	C25H37N7O18P3S	c
ac_c	Acetate	C2H3O2	c
acac_c	Acetoacetate	C4H5O3	c
accoa_c	Acetyl-CoA	C23H35N7O17P3S	c
coa_c	Coenzyme A	C21H33N7O16P3S	c
h_c	H+	H	c
nad_c	Nicotinamide adenine dinucleotide	C21H26N7O14P2	c
nadh_c	Nicotinamide adenine dinucleotide - reduced	C21H27N7O14P2	c
nadp_c	Nicotinamide adenine dinucleotide phosphate	C21H26N7O17P3	c
nadph_c	Nicotinamide adenine dinucleotide phosphate - reduced	C21H27N7O17P3	c

In [ ]:
import pandas as pd
from pytfa.io import annotate_from_lexicon

lexicon = pd.read_csv("phb_lexicon.csv")

annotate_from_lexicon(
    mytfa,
    lexicon,
    inplace=True
)

## Check TFA R. palustris

In [ ]:
[c.name for c in mytfa.constraints if c.name.startswith(("FU_", "BU_", "SU_", "UF_"))][:10]

['SU_QULNS',
 'UF_QULNS',
 'SU_ORNDC',
 'UF_ORNDC',
 'SU_MSBENZMT',
 'UF_MSBENZMT',
 'SU_DESAT18a',
 'UF_DESAT18a',
 'SU_FUM',
 'UF_FUM']

In [ ]:
mytfa.description = "R. palustris iDT1294 TFA model"
mytfa.print_info()

                                          value
key
name                            tutorial_basics
description      R. palustris iDT1294 TFA model
num constraints                           10287
num variables                             13008
num metabolites                            2124
num reactions                              2721
                            value
key
num metabolites(thermo)  8.000000
num reactions(thermo)    0.000000
pct metabolites(thermo)  0.376648
pct reactions(thermo)    0.000000

In [ ]:
for v in mytfa.variables.values():
  print(v)

In [ ]:
for c in mytfa.constraints.values():
    if rxn.id in c.name:
        print(c)

In [ ]:
len([v.name for v in mytfa.variables if v.name.startswith("DGo_")])

0

In [ ]:
[c.name for c in mytfa.constraints if c.name.startswith("G_")][:10]

[]

In [ ]:
fba_fluxes = cobra_model.optimize().fluxes
tfa_fluxes = mytfa.optimize().fluxes

diff = (fba_fluxes - tfa_fluxes).abs()
print("Max flux difference:", diff.max())

In [ ]:
print(type(thermo_data["metabolites"]))
print("ThermoDB metabolites:", len(thermo_data["metabolites"]))
print(list(thermo_data["metabolites"].keys())[:10])

<class 'dict'>
ThermoDB metabolites: 18307
['cpd00805', 'cpd11364', 'cpd18424', 'cpd17488', 'cpd03902', 'cpd14767', 'cpd05076', 'cpd00475', 'cpd17550', 'cpd08432']

In [ ]:
# Convert DataFrame → dict lexicon
lexicon_dict = (
    lexicon['seed_id']
    .dropna()
    .astype(str)
    .to_dict()
)

print(type(lexicon_dict))
print(len(lexicon_dict))
print(list(lexicon_dict.items())[:5])

<class 'dict'>
8
[('glc__D_c', 'cpd00027'), ('pyr_c', 'cpd00020'), ('accoa_c', 'cpd00022'), ('atp_c', 'cpd00002'), ('adp_c', 'cpd00008')]

In [ ]:
import pandas as pd

rows = []
for m in cobra_model_mat.metabolites:
    rows.append({
        "met_id": m.id,
        "name": m.name,
        "formula": m.formula,
        "charge": m.charge,
        "compartment": m.compartment
    })

df = pd.DataFrame(rows)
df.to_csv("metabolites_for_mapping.csv", index=False)

In [ ]:
from collections import Counter

print("Metabolites:", len(model.metabolites))
print("With formula:", sum(1 for m in model.metabolites if m.formula))
print("With annotation:", sum(1 for m in model.metabolites if m.annotation))

Metabolites: 2124
With formula: 2118
With annotation: 0

In [ ]:
# Load COBRA model

# Path to base model
base_model_dir = project_root / "base"
base_model_dir.mkdir(parents=True, exist_ok=True)

# Full path to the SBML file
base_model_path = base_model_dir / "model_rpalustris_comp_fixed.xml"

# Load model
model = read_sbml_model(
    str(base_model_path),
    use_fbc=False
)

print(f"Reactions: {len(model.reactions)}")
print(f"Metabolites: {len(model.metabolites)}")

Reactions: 2721
Metabolites: 2124

# Load Buitrons medium constraints

In [ ]:
# Apply medium constraints from Montiel-Corona 2022.
def apply_media_from_excel(model, excel_path, close_exchanges=True):
    """
    Apply media constraints from an Excel file with columns:
    Reaction | LowerBound | UpperBound
    """

    media_df = pd.read_csv(excel_path)

    required_cols = {"Reaction", "LowerBound", "UpperBound"}
    if not required_cols.issubset(media_df.columns):
        raise ValueError(
            f"Excel file must contain columns: {required_cols}"
        )

    # Optionally close all exchanges first
    if close_exchanges:
        for rxn in model.exchanges:
            rxn.lower_bound = 0
            rxn.upper_bound = 1000

    # Apply media bounds
    for _, row in media_df.iterrows():
        rxn_id = row["Reaction"]

        if rxn_id not in model.reactions:
            raise KeyError(f"Reaction {rxn_id} not found in model")

        rxn = model.reactions.get_by_id(rxn_id)
        rxn.lower_bound = float(row["LowerBound"])
        rxn.upper_bound = float(row["UpperBound"])

    # Check reaction directly associated to PHB production
    EX_acetate_rxn = model.reactions.get_by_id("EX_ac_e")
    print(EX_acetate_rxn.bounds)
    print(EX_acetate_rxn.reaction)

    return model

In [ ]:
# Load model

excel_path =  project_root / "phbv" / "checkpoint_output" / "PHBV_model_medium_montiel_buitron_2022_exchange_bounds.xlsx"
print(excel_path)

/content/driveDL/My Drive/Genome_scale_metabolic_models_PNSB/Model_Tec_Campos_2023_RPiDT1294/rpalustris_pha_optimization/models/phbv/checkpoint_output/PHBV_model_medium_montiel_buitron_2022_exchange_bounds.xlsx

In [ ]:

apply_media_from_excel(model, excel_path)

(-0.2477, 1000.0)
ac[e] <=>

# Define PHBS_syn as objective

In [ ]:
# Get the reaction
rxn = model.reactions.get_by_id('PHBS_syn')
# Set it as objective
model.objective = rxn
# Set lower and upper bounds
rxn.lower_bound = 0.02
rxn.upper_bound = 0.18

model.summary() #  is the default objective function

# Assing deltaG0_prime to important reactions

In [ ]:
tmodel.reactions.get_by_id("AACOAR_syn")

In [ ]:
from pytfa.optim.variables import DeltaG

PHB_REACTION_THERMO = {
    "ACACT1r": {      # 2 acetyl-CoA ⇌ acetoacetyl-CoA + CoA
        "delta_g0": +18.0,
        "uncertainty": 5.0
    },

    "AACOAR_syn": {   # acetoacetyl-CoA + NADPH → 3HB-CoA + NADP+
        "delta_g0": -25.0,
        "uncertainty": 5.0
    },

    "PHBS_syn": {     # polymerization (CoA-releasing)
        "delta_g0": -35.0,
        "uncertainty": 7.0
    },

    "ACACCT": {       # CoA transfer / activation
        "delta_g0": -10.0,
        "uncertainty": 5.0
    }
}


for rxn_id in PHB_REACTION_THERMO:
    rxn = tmodel.reactions.get_by_id(rxn_id)
    dg_vars = [v for v in tmodel.variables.values() if isinstance(v, DeltaG) and v.reaction == rxn]
    print(rxn_id, "ΔG vars:", dg_vars)

ACACT1r ΔG vars: []
AACOAR_syn ΔG vars: []
PHBS_syn ΔG vars: []
ACACCT ΔG vars: []

In [ ]:
thermo_data2['cues'].update({
    "AACOAR_syn": {"delta_g0": -25.0, "uncertainty": 5.0},
    "PHBS_syn":    {"delta_g0": -20.0, "uncertainty": 5.0},
    "ACACT1r":     {"delta_g0": -10.0, "uncertainty": 5.0},
    "ACACCT":      {"delta_g0": -15.0, "uncertainty": 5.0},
})

In [ ]:
# -----------------------------
# Minimal PHB-focused TFA setup
# -----------------------------

import cobra
from pytfa import ThermoModel
from pytfa.io import load_thermoDB

# -----------------------------
# 1️⃣ Load thermodynamic database (optional, here we skip it for manual ΔG°)
# -----------------------------
# thermo_data = load_thermoDB()  # only needed if you want full database

# -----------------------------
# 2️⃣ Define your minimal thermo_data
# -----------------------------
# Include only metabolites and reactions relevant for PHB production
# Make sure metabolite formulas are correct (already done)

thermo_data = {
    "name": "PHB_minimal",
    "units": {"energy": "kJ/mol"},
    "metabolites": {
        m.id: {"formula": m.formula}
        for m in model.metabolites
        if m.formula is not None and m.id.endswith("[c]")
    },
    "cues": {
        "AACOAR_syn": {"deltaG0_prime": -25.0, "deltaG0_uncertainty": 5.0},
        "ACACT1r":    {"deltaG0_prime": -10.0, "deltaG0_uncertainty": 5.0},
    }
}

tmodel = ThermoModel(thermo_data, model)

tmodel.compartments["c"] = {"pH": 7.0, "ionicStr": 0.25}



# Adjust constraints since some reactions have values ><1000
for rxn in tmodel.reactions:
    if rxn.lower_bound < -1000:
        rxn.lower_bound = -1000
    if rxn.upper_bound > 1000:
        rxn.upper_bound = 1000

# -----------------------------
# 5️⃣ Add concentration bounds for key metabolites
# -----------------------------
bounds = {
    "nadph[c]": (1e-6, 1e-3),
    "nadp[c]":  (1e-6, 1e-3),
    "h[c]":     (1e-8, 1e-6),
    "coa[c]":   (1e-6, 1e-3),
    "aacoa[c]": (1e-6, 1e-3),
    "3hbcoa__R[c]": (1e-6, 1e-3)
}

for met_id, (lb, ub) in bounds.items():
    met = tmodel.metabolites.get_by_id(met_id)
    met.concentration = (lb, ub)


# -----------------------------
# 6️⃣ Prepare and convert TFA model
# -----------------------------
tmodel.prepare()  # prepare metabolite concentrations
tmodel.convert()  # add ΔG variables & thermodynamic constraints

In [ ]:
from pytfa.optim.variables import DeltaG

rxn = tmodel.reactions.get_by_id("AACOAR_syn")
dg_vars = [
    v for v in tmodel.variables.values()
    if isinstance(v, DeltaG) and v.reaction == rxn
]

print(dg_vars)

[]

In [ ]:
from pytfa.optim.variables import DeltaG

for rxn_id in ["AACOAR_syn", "ACACT1r"]:
    rxn = tmodel.reactions.get_by_id(rxn_id)
    dg_vars = [
        v for v in tmodel.variables.values()
        if isinstance(v, DeltaG) and v.reaction == rxn
    ]
    print(rxn_id, "ΔG vars:", dg_vars)

AACOAR_syn ΔG vars: []
ACACT1r ΔG vars: []

In [ ]:
rxn = tmodel.reactions.get_by_id("AACOAR_syn")

print("Stoichiometry:", rxn.metabolites)
print("Is transport:", rxn.id.endswith("t") or rxn.boundary)
print("All formulas present:",
      all(m.formula is not None for m in rxn.metabolites))
print("Compartments:",
      {m.compartment for m in rxn.metabolites})

Stoichiometry: {<Metabolite h[c] at 0x799a5e8bd580>: -1.0, <Metabolite nadph[c] at 0x799a5e8bd0d0>: -1.0, <Metabolite aacoa[c] at 0x799a5ea840e0>: -1.0, <Metabolite nadp[c] at 0x799a5ea98a40>: 1.0, <Metabolite 3hbcoa__R[c] at 0x799a5ea86900>: 1.0}
Is transport: False
All formulas present: True
Compartments: {'c'}

In [ ]:
from pytfa.optim.variables import DeltaG

rxn = tmodel.reactions.get_by_id("AACOAR_syn")
dg_vars = [
    v for v in tmodel.variables.values()
    if isinstance(v, DeltaG) and v.reaction == rxn
]

print(dg_vars)

[]

In [ ]:
phb_mets = [
    "aacoa[c]",
    "accoa[c]",
    "coa[c]",
    "nadph[c]",
    "nadp[c]",
    "3hbcoa__R[c]",
    "acac[c]",
    "ac[c]",
    "h[c]"
]

print("\n=== PHB metabolites: seed_id check ===")
for mid in phb_mets:
    met = tmodel.metabolites.get_by_id(mid)
    sid = met.annotation.get("seed_id", None)
    print(f"{mid:15s} | seed_id: {sid}")

=== PHB metabolites: seed_id check ===
aacoa[c]        | seed_id: None
accoa[c]        | seed_id: None
coa[c]          | seed_id: None
nadph[c]        | seed_id: None
nadp[c]         | seed_id: None
3hbcoa__R[c]    | seed_id: None
acac[c]         | seed_id: None
ac[c]           | seed_id: None
h[c]            | seed_id: None

In [ ]:
# Reactions of interest
phb_reactions = ["AACOAR_syn", "ACACT1r"]

thermo_mets = thermo_data["metabolites"]  # ThermoDB compounds dict

def normalize(s):
    return s.lower().replace("-", "").replace("_", "").replace(" ", "")

print("\n=== PHB Reactions: On-the-fly ThermoDB mapping ===")

for rxn_id in phb_reactions:
    if rxn_id not in model.reactions:
        print(f"\n❌ Reaction {rxn_id} not in model")
        continue

    rxn = model.reactions.get_by_id(rxn_id)
    print(f"\nReaction: {rxn_id}")
    print(rxn.build_reaction_string())
    print("-" * 70)

    for met in rxn.metabolites:
        print(f"\nMetabolite: {met.id}")
        print(f"  Name:        {met.name}")
        print(f"  Formula:     {met.formula}")
        print(f"  Compartment: {met.compartment}")

        formula_hits = []
        name_hits = []

        for seed_id, tmeta in thermo_mets.items():
            # Formula match
            if met.formula and tmeta.get("formula") == met.formula:
                formula_hits.append((seed_id, tmeta.get("name")))

            # Name match (loose)
            if met.name and normalize(met.name) in normalize(tmeta.get("name", "")):
                name_hits.append((seed_id, tmeta.get("name")))

        if formula_hits:
            print("  🔬 ThermoDB formula matches:")
            for sid, name in formula_hits[:5]:
                print(f"     - seed_id: {sid} | {name}")
        else:
            print("  ❌ No ThermoDB formula matches")

        if name_hits:
            print("  🧬 ThermoDB name matches:")
            for sid, name in name_hits[:5]:
                print(f"     - seed_id: {sid} | {name}")
        else:
            print("  ❌ No ThermoDB name matches")

=== PHB Reactions: On-the-fly ThermoDB mapping ===

Reaction: AACOAR_syn
aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]
----------------------------------------------------------------------

Metabolite: h[c]
  Name:        H+
  Formula:     H
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: h_cx[c] | None
     - seed_id: h[c] | None
  ❌ No ThermoDB name matches

Metabolite: nadph[c]
  Name:        Nicotinamide adenine dinucleotide phosphate - reduced
  Formula:     C21H27N7O17P3
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: nadph[c] | None
  ❌ No ThermoDB name matches

Metabolite: aacoa[c]
  Name:        Acetoacetyl-CoA
  Formula:     C25H37N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: aacoa[c] | None
  ❌ No ThermoDB name matches

Metabolite: nadp[c]
  Name:        Nicotinamide adenine dinucleotide phosphate
  Formula:     C21H26N7O17P3
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: nadp[c] | None
  ❌ No ThermoDB name matches

Metabolite: 3hbcoa__R[c]
  Name:        (R)-3-Hydroxybutyryl-CoA
  Formula:     C25H39N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: 3hbcoa__R[c] | None
  ❌ No ThermoDB name matches

Reaction: ACACT1r
2.0 accoa[c] --> aacoa[c] + coa[c]
----------------------------------------------------------------------

Metabolite: accoa[c]
  Name:        Acetyl-CoA
  Formula:     C23H35N7O17P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: accoa[c] | None
  ❌ No ThermoDB name matches

Metabolite: coa[c]
  Name:        Coenzyme A
  Formula:     C21H33N7O16P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: coa[c] | None
  ❌ No ThermoDB name matches

Metabolite: aacoa[c]
  Name:        Acetoacetyl-CoA
  Formula:     C25H37N7O18P3S
  Compartment: c
  🔬 ThermoDB formula matches:
     - seed_id: aacoa[c] | None
  ❌ No ThermoDB name matches

In [ ]:
# List of reactions of interest
phb_reactions = ["AACOAR_syn", "ACACT1r"] #"PHBS_syn","ACACCT"

print("=== PHB Reactions Metabolites ===")
for rxn_id in phb_reactions:
    if rxn_id not in model.reactions:
        print(f"Reaction {rxn_id} not in model")
        continue

    rxn = model.reactions.get_by_id(rxn_id)
    print(f"\nReaction: {rxn_id} | Equation: {rxn.build_reaction_string()}")
    print(f"{'Metabolite ID':<20} | {'Formula':<15} | {'Compartment'}")
    print("-"*55)

    for met, coeff in rxn.metabolites.items():
        # check if formula exists
        formula = met.formula if met.formula is not None else "None"
        print(f"{met.id:<20} | {formula:<15} | {met.compartment}")

=== PHB Reactions Metabolites ===

Reaction: AACOAR_syn | Equation: aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]
Metabolite ID        | Formula         | Compartment
-------------------------------------------------------
h[c]                 | H               | c
nadph[c]             | C21H27N7O17P3   | c
aacoa[c]             | C25H37N7O18P3S  | c
nadp[c]              | C21H26N7O17P3   | c
3hbcoa__R[c]         | C25H39N7O18P3S  | c

Reaction: ACACT1r | Equation: 2.0 accoa[c] --> aacoa[c] + coa[c]
Metabolite ID        | Formula         | Compartment
-------------------------------------------------------
accoa[c]             | C23H35N7O17P3S  | c
coa[c]               | C21H33N7O16P3S  | c
aacoa[c]             | C25H37N7O18P3S  | c

In [ ]:
tmodel.compartments

{'c': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02},
 'u': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02},
 'p': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02},
 'e': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}}

In [ ]:
# Print all compartments defined in the GEM
print("=== Model Compartments ===")
for comp_id, comp in model.compartments.items():
    print(f"{comp_id}: {comp}")

print("\n=== Metabolites and their compartments ===")
for met in model.metabolites:
    # ID and compartment
    print(f"{met.id:20} | {met.compartment:5} | formula: {met.formula}")

In [ ]:
## Optimality
tfa_solution = mytfa.optimize()

In [ ]:
from pytfa.optim.variables import DeltaG

for rxn_id in PHB_REACTION_THERMO:
    rxn = mytfa.reactions.get_by_id(rxn_id)

    dg_vars = [
        v for v in mytfa.variables.values()
        if isinstance(v, DeltaG) and v.reaction == rxn
    ]

    print(rxn_id, "ΔG vars:", dg_vars)

ACACT1r ΔG vars: []
AACOAR_syn ΔG vars: []
PHBS_syn ΔG vars: []
ACACCT ΔG vars: []

# Check up thermodata

In [ ]:
thermo_data.keys()

dict_keys(['name', 'units', 'metabolites', 'cues'])

In [ ]:
# CHECK THERMODATA STRUCTURE
#thermo_data['metabolites'].items()

In [ ]:
# CHECK METABOLITES FORMULAS (OR NAME)
names = [entry['formula'] for entry in thermo_data['metabolites'].values()]
thermo_formulas = [str(f) for f in names if f is not None]
print(thermo_formulas)

['C6H12O9P', 'C37H56N8O9', 'CH3Br', 'C19H15N3O7', 'C21H26N2O6Cl2', 'NA', 'C18H16N6O8S3', 'C5H10O8P', 'C30H50O4', 'C22H29N7O5', 'C15H28N2', 'C27H46O', 'C22H16N4O', 'C7H17N4O', 'C36H61N7O17P3S', 'C19H21N7O6', 'C30H51N7O7', 'C23H31NO7', 'C9H14N4O4', 'C10H14CaO6', 'C15H26O2', 'C3H4N2', 'H2Cu2O', 'C6H7O3RS', 'C8H11NO', 'C14H14O4', 'C16H20N2O2', 'C20H28O', 'C28H50O2', 'C16H17NO2', 'C40H60', 'C7H9N2', 'C11H18N2O2S', 'C20H30N6O12S2', 'C16H21N4O9', 'C15H16O2', 'C60H78OSn2', 'C12H19N2O', 'C9H11O11PR3', 'C18H26O4', 'C8H16N2O4Se2', 'C13H20O', 'C9H16N4OS', 'C6H14O6', 'C7H10N2O3', 'C10H12O2', 'C20H32', 'NA', 'NA', 'C27H34O5', 'C9H9O5', 'C15H20O3', 'C35H32N4O5Mg', 'C35H44O16', 'C12H6O4', 'CNR', 'C20H24O6', 'C8H18O4S4', 'C8H10O', 'NA', 'C23H18O8', 'C11H16O16P2R2', 'C22H24N3OCl', 'C4H8O2', 'C19H28O3', 'C40H71N3O15P2', 'C8H8NO4', 'C25H39N7O18P3S', 'C23H26O8', 'C30H50O', 'C16H16O11', 'C17H22N3', 'C11H17O2', 'NA', 'C19H11O2', 'C18H26NO6', 'C24H47NO10S', 'C13H16N2O3', 'C19H25N2O', 'C20H25N2OS', 'C34H63N2O6SCl', 'C17H19N3', 'C21H32N6O3', 'C25H33NO', 'C6H4O2Cl2', 'C13H14N2O4S2', 'C18H16O4', 'C6H9N2O6S', 'C16H30O', 'C21H33OF', 'C18H29O3', 'C23H34N2O19P2R4S', 'C12H24O11', 'C88H97N9O33Cl2', 'C16H10O5', 'C10H16O2', 'C17H24NO4', 'C30H46N8O18P3S', 'C31H34O12', 'C3H6O5P', 'C5H6NO2', 'C36H52O8', 'C5H11NO2S', 'C10H16O2', 'C14H12N4O2', 'C8H5O4', 'C19H20NO4', 'C67H110O17P2', 'C7H8NCl', 'C48H74O4', 'C6H6NR', 'C4H12N2', 'C18H21O8RS', 'C27H46O', 'C32H54N2O4', 'C19H24O3', 'C18H16N2O3', 'C22H27O8Cl', 'C18H31O16R', 'C8H11N', 'C24H17O8', 'C15H11NO2', 'C5H8NO4', 'C18H24NO4', 'NA', 'C28H34N5O5', 'C16H18NO3', 'C16H28NO5', 'NA', 'C16H23NO3', 'C9H10O2', 'C39H70N2O19', 'C21H29O3F', 'C23H22O7', 'C19H17N3O', 'C20H24O6', 'C4H8O2', 'C22H28O8', 'C7H6NO3', 'C23H30O6', 'C21H23NO3', 'C5H6O5', 'C11H13N', 'NA', 'C10H13Cl3', 'C6H12O5', 'C6H11O6R', 'C23H21O5', 'NA', 'C4H10N', 'C63H88CoN14O14P', 'C6H13N4O9P2', 'C13H22N3O5', 'C2H3O3', 'C21H27N7O14P2', 'C15H21N3O15P2', 'C8H15N2O4PS3', 'NA', 'C87H171O4', 'C36H62O31', 'C5H12N2S', 'NA', 'C17H36', 'C28H46O', 'C10H6O4', 'C4Cl6', 'C9H10NO6', 'NA', 'C7H5O5', 'C10H9O4', 'C6H5F', 'C18H32O16', 'C42H85NO3', 'C5H10N2O3', 'C18H12', 'C7H14N5O2R2', 'C18H16O3', 'C22H22N3O3F', 'C12H7OCl3', 'C3H4O2R', 'C63H97N14O14S', 'C65H116O17P2', 'C10H18O', 'C21H23N2O5S2', 'C41H70N2O17P2', 'C11H23NO2', 'C20H32O2', 'C19H17N3O5SCl', 'C13H11NO2Cl2', 'C24H34N2O', 'C17H21O3', 'C17H22O5', 'C21H44N7O18P2', 'C17H14O4S', 'C9H10O3', 'C22H20O10', 'C10H10O4', 'C23H38O', 'C16H24NO2', 'C30H47O3', 'C14H9NO3', 'C4H6N2O3R2', 'C15H22O3', 'C17H21NO3', 'C19H40N5O6', 'C6H11O5SAu', 'C15H12', 'C29H37N4O4', 'C16H26O4', 'NA', 'C3H3O5P', 'C33H38N4O8', 'C10H10NO4', 'C21H28N2O3', 'C13H16O2', 'NA', 'C10H16O', 'C15H14O11', 'C4H6NO4', 'C39H42N6O18', 'C11H8NO4', 'C17H23N2O4S', 'C4H7NO2', 'C23H29N7O6', 'C13H18NOCl', 'C16H20N5O4Br2', 'C18H24NO', 'C11H8', 'C11H16N5Cl', 'NA', 'C20H32', 'C21H16O8', 'C5H3O3', 'C18H15N2OCl3', 'C8H15NO9P', 'C10H6N2Cl2', 'C12H2OCl6', 'C11H19N4O6', 'C13H7N2O4SCl2F3', 'C5H7N3O5', 'NA', 'C37H50N2O', 'C16H16N3O6', 'C21H38O9P', 'C15H16O4', 'C40H62N8O21', 'X', 'C6H12O6', 'C12H16O6', 'C23H34N2O19P2R4S', 'C20H18O5', 'C14H10O5', 'C11H7O2', 'C39H49N5O7', 'C12H22N2O2', 'C21H24O5', 'C3H5Cl', 'C11H20NO9S2', 'C13H15NO6', 'C29H45O3', 'C6H6O2', 'C20H24O2', 'C7H16N8O4', 'C88H178NO9P', 'C2H5OCl', 'C14H21O8PR3', 'C6H7NO', 'C13H6NO2Cl4', 'C13H6N3O6Br2', 'C6H7O6', 'C9H9N', 'C22H39N2O8PRS', 'C20H40N3O16P', 'C8H7NO', 'C15H29OX', 'C6H3O5Cl', 'C11H15N2S', 'C5H9O3R', 'C21H22O6', 'C16H13O3', 'NA', 'C24H14', 'C14H7NO2Br2', 'C21H30O3', 'C10H14O', 'C44H51NO17', 'C25H46NO8R', 'C19H18O6', 'C20H24O3', 'C9H10O2', 'C5H7N2O3', 'C23H44O5', 'C8H4O5', 'C16H22O8', 'C35H43N6O15', 'H2N3O9Bi', 'C27H46O2', 'C14H17N3O15P2R2', 'C21H26NO5', 'C15H15NO2', 'C40H56O4', 'C6H11O4', 'C9H4O4Br2', 'C45H46N4O17', 'C20H31O4', 'C15H22O', 'C21H44N4O13', 'C20H27O3', 'C92H176O16P', 'C12H16O15R2S2*2', 'C40H48N4O2', 'C34H52N7O24P2', 'C80H124N16O42', 'C23H27NO8', 'C8H12N2O2', 'C45H72O16', 'C53H68N9O10S', 'C21H42O7P', 'C45H54N4O14', 'C6H13NO2', 'C2H2O2R2', 'C17H14O7', 'C36H54O8', 'C19H23NO3', 'C34H37N3O6', 'C15H16O', 'C6H12O5', 'C10H13N2Cl', 'C21H34O2', 'C6H9O3', 'C38H44N2O6', 'C32H40N5O5Br', 'C28H34O14', 'C16H17NO4', 'C23H38O5', 'NA', 'O3S2', 'C5H12O', 'C40H64NO10', 'C19H25N2', 'C10H12N5O4Br', 'C17H26NO3', 'C14H10O2', 'C18H14NO4', 'C14H12Cl2', 'C25H49O2', 'C9H7NO', 'HFeS', 'C176H307N2O100P4', 'C21H30O2', 'C19H37N8O8', 'C24H21O12', 'C30H40O8', 'C3H4NO2R2', 'C12H24NO10', 'C87H117N13O19S2', 'C6H9O6', 'C7H8N2O2', 'C6H15O3PS2', 'C9H13NO', 'NA', 'C28H36N7O17P3SF', 'C12H14O4PCl3', 'C4H9NO2Se', 'C16H14O4Cl2', 'C10H17ORS', 'C18H15ClSn', 'C16H14O5', 'C6H11NO2', 'C21H26O4S', 'C12H3OCl6', 'C12H24N4S8Se', 'C14H17NO6', 'C6H13N3O2', 'C23H34O5', 'C27H42O', 'C5H9O6', 'C12H10O', 'C15H22O2', 'C17H26O9', 'NA', 'C53H78O17', 'C22H21N2O7Cl', 'C6H10N2O3R2', 'C43H49NO19', 'C14H10O6', 'C21H28O2F2', 'C15H10O4', 'C21H23O8', 'C8H12NO3', 'C13H4N4O4Cl2F6', 'C47H77O14', 'NA', 'C10H12N5O3R', 'NA', 'C15H10N2O2', 'C8H13O4RS', 'C21H26O10', 'C11H19N5S', 'C18H26NO6', 'C6H6O2', 'C21H42N7O15P', 'C7H12N4O3', 'C10H20O', 'C19H23O6', 'NA', 'C11H15N4O5', 'C41H61N9O28P2', 'NA', 'C46H64N8O14', 'C22H39N2O8PRS', 'C22H26N10O2Br2', 'C23H32O2', 'C12H26', 'C15H12O5', 'C6H6NO3S', 'C12H4Cl6', 'C22H22N3O5Cl', 'C19H40NO7P', 'C20H15N3O', 'C14H21NO8', 'C20H32O', 'NA', 'C28H46O3', 'C37H34N2O9S3', 'C8H14NO4', 'C10H19N5O', 'C22H26O8', 'C20H35N2O9PRS', 'C15H15N2O2Cl', 'C20H22O6', 'C10H13N5O10P2', 'C18H37NO2', 'C27H46O3', 'CH6N', 'C15H23O3', 'C21H43N7O12', 'C13H12O2', 'Ba', 'C14H16N5O7S2', 'C5H6O8PR2', 'C18H10', 'C5H11O2As', 'C17H25N3O4S2', 'C25H39N7O18P3S', 'C35H42N5O5', 'C27H27O5', 'C6H6N4S', 'C7H8NO4', 'C35H43N5O9', 'C22H27O5Cl', 'C13H14N4O', 'C21H30O3', 'C19H32O', 'C20H21N7O7', 'C15H20O', 'C25H31O8', 'C4H4O6', 'C52H91N2O23P2R5', 'C6H9NO2', 'C8H12N2O4', 'C6H11O6R', 'C83H161O4', 'C11H8NO5', 'NA', 'C14H22N2O3SCl', 'C10H15N5O3', 'C16H26O7', 'C12HO2Cl7', 'C15H9N2O6SClF3', 'C21H20O12', 'C7H11N2O3', 'C26H49N2O8PRS', 'C15H12O6', 'C28H46O2', 'C20H21N2O3', 'C9H13N3O11P2', 'C14H21NO12R', 'NA', 'C6H12O6', 'C11H7N2Br', 'C9H11N5O6P', 'C16H12N2O2', 'C9H10N2O2ClBr', 'C49H84N2O32P2', 'C9H7O3', 'C29H36N3O7', 'C17H31N2O8PRS', 'NA', 'C15H22N6O4RS', 'C9H13N3O13P3', 'C11H10O3', 'C11H19N4O10P2', 'C39H64NO15', 'C7H13N2O2R2S', 'C20H37N2O9PRS', 'C15H21N5O14P2', 'C6H8N2', 'C30H50O', 'C10H11N5O4', 'C20H24O6', 'C21H16O7', 'C10H5NO3', 'C11H9N3O5', 'C7H10N2O4', 'C17H14O7', 'C10H22O', 'C27H41N7O18P3S', 'C10H18O', 'C22H37N2O16R', 'C11H10N3', 'C9H20O', 'C37H68NO12', 'NA', 'C28H48O', 'C19H24NO4', 'C8H7O5', 'C41H27O27', 'C15H18N3O3', 'C5H8O2', 'C4H10O3PS', 'NA', 'C22H49N4O', 'C53H62N10O14S2', 'C4H6N2O6PR2', 'C21H32O2', 'C8HO3SF17', 'C100H163N10O28P2', 'C18H26NO6', 'C20H24NO2S2', 'C10H20O2', 'H2O2P', 'C9H15N2O7P', 'C20H31NO7', 'C15H14O5', 'C57H111NO16P', 'C5H10O7B', 'C15H25N4O8', 'C6H8O6', 'C11H8N2O5', 'C14H12O2S2', 'C5H9O4R', 'C19H20O7', 'C8H15NO9P', 'C20H26O6', 'C9H15N5O14P3', 'C10H9O3Cl2', 'C11H16N2O3S', 'C29H30O8', 'C12H22NO9S3', 'C68H131N2O9PRS', 'C17H26NO2Cl', 'C23H17N2O5', 'C20H22O7', 'C8H9N3O4', 'C7H14O6', 'C40H56O3', 'C3H7NO4Se', 'C33H48O9', 'C26H30O6', 'C22H26O11', 'C18H28NO5', 'C9H8NO6', 'H3NO', 'C20H24O2', 'C7H14O6', 'C11H15NO', 'C21H44N7O11', 'C18H14O2', 'C6H6O5', 'C16H23N5O6', 'C25H49N6O8', 'C5H10NO5S', 'C20H23N3O2', 'C13H18N2O2Cl2', 'NA', 'C20H31O5', 'C12H22O11', 'C25H31NO3', 'C17H22N3OCl', 'C8H20NO6P', 'C22H30O8', 'C11H9O3Cl5', 'C14H18N6O', 'C26H42NO4', 'C25H40NO6', 'C17H28O', 'C7H7NO2', 'C18H12', 'C15H9O10', 'C21H13N', 'C16H18N3O5S', 'C28H38NO9', 'C31H29N2O5', 'C15H12O2', 'C7H7O2SF', 'C33H62NO8P', 'C14H16N2O6P', 'C52H76O12', 'C42H38CoN4O16', 'C7H11NO8PR2', 'C3H2OF6', 'C16H23N5O15P2', 'NA', 'C10H14O3', 'C17H22O7', 'C28H48O', 'C6H9NOS', 'Na', 'C49H93N2O8PRS', 'NA', 'C19H32O2', 'C15H13NO2', 'C13H9O4', 'C7H13N3O3R', 'C8H10NO10PR2', 'C6H7NO3', 'C9H16N4O3', 'C18H22NO5', 'C7H13N3O2R2', 'C121H226O18', 'C15H14O2Br2', 'C21H23NO6', 'C12H11N', 'C5H7O2', 'C27H42N8O18P3S', 'C3H8O3', 'C14H15N3O', 'C30H47N3O10S', 'C7H8N2O3', 'C4H10NO', 'C6H14N3', 'C40H56', 'C21H30O4', 'CO2R2', 'C7H8NO3', 'C28H45N4O4', 'C48H77N7O20P3S', 'C38H41N2O7', 'C60H89CoN13O15P', 'C9H15NO3', 'C4H6O2', 'NA', 'C9H9O4', 'C18H20NO5', 'C10H16', 'C28H40N7O20P3S', 'C16H24NO', 'C20H24N3SCl', 'C17H23N3O16P2', 'C43H67N7O17P3S', 'C19H34PCl2', 'C43H80O15', 'C13H16N5O13P2', 'C24H33O6F', 'NA', 'C29H31NO10Cl', 'NA', 'C15H12O2', 'C16H16N5O7S2', 'C22H26O9', 'C19H30O', 'C17H16O5', 'C17H22NO3', 'C20H22O6', 'C13H27NO2', 'C9H7NO', 'C33H61N2O8PRS', 'C5H10N3', 'C21H36N4O5S', 'C11H16NO8', 'C30H39O4', 'C16H30O2F', 'NA', 'C34H26O22', 'C24H24O2', 'C24H39O5', 'C20H25N3O7', 'C33H68', 'CH3OR', 'C10H15N6O6P', 'C6H2O5Cl2', 'C18H33O3', 'C124H222N2O51P2', 'C9H14O5S', 'C6H6O4', 'C19H28O2', 'C13H25OX', 'C6H9O7', 'NA', 'NA', 'C3H7N2', 'C13H5O2Cl6', 'C15H12N2O', 'C14H11NO4Cl2', 'C28H42N2O8S', 'C21H30O4', 'C28H58O', 'C20H23NO4', 'C17H21NO2', 'C10H5O4', 'C17H20NO3', 'C15H22O9', 'C27H44O4', 'NA', 'C2H2OR2', 'C4H4O', 'C11H15NO2S', 'C48H75N7O21P3S', 'C22H31O3F', 'C10H8O', 'C21H29N3O19P2R6', 'C11H13NO3', 'C7H6O5', 'C17H27NO7', 'C6H12O7PS', 'C5H9NO3', 'C12H5O2SCl4', 'C104H170N14O30P2', 'C48H70O6', 'C23H32N2OS', 'C21H30O4', 'NA', 'C44H50N8', 'C42H40N4O16', 'C17H17N3O3F', 'C27H42O6', 'NA', 'C11H19N2O6', 'C5H12O5', 'C27H44O3', 'C4H5NO3R', 'C21H29N7O15P2', 'C18H31O2', 'C15H24', 'C11H10N2O', 'C6H9O9P', 'C21H19O10', 'C18H18O2', 'NA', 'NA', 'C10H8N3O2Cl', 'C21H13O8', 'C10H16O2', 'C15H24', 'C18H39N6O6', 'NA', 'C34H67N3O5S', 'C10H18O', 'C39H77O2', 'C8H14NO6R', 'C7H6N2', 'C8H7NO3', 'C90H74O36', 'C30H42N4O2', 'C26H27O15', 'C41H68O13', 'C6H4N4O4', 'C8H18NO2', 'C40H36O11', 'C7H7NO2', 'C27H46O2', 'C7H6O5P', 'NA', 'C39H58O4', 'C12H10OS2', 'C26H28O12', 'C6H8O2', 'C7H4NO2Cl', 'C35H33N4O6Mg', 'C16H17NO3', 'C7H7NO4', 'C17H16O4', 'C10H19N5O', 'C19H25NO10', 'C3H5NO3', 'C24H34O5', 'C9H9NO4', 'C11H12O2', 'C4H12N3O4P', 'C20H12', 'C12H22O11', 'C15H24', 'C6H7O3', 'C21H29N5O17P2R2', 'C11H18N', 'C15H23N5O15P2', 'C14H19O3', 'C7H11N2O5', 'C8H5O7', 'C29H47N2', 'C15H21N3O16P2', 'C14H12O3', 'C26H38N7O19P3S', 'C43H80O13P', 'C21H31O3F', 'C16H21NO5', 'C20H30O3', 'C30H40O', 'NA', 'C9H9N5O', 'NA', 'C8H10NO5PS', 'C12H22O10', 'C10H14O', 'C15H24', 'C10H15N5O13P2Se', 'C8H8O', 'C9H10NO6', 'C7H14O6', 'C25H25O4', 'C32H44NO13', 'C5H10O8P', 'C6H8N2O3R2', 'C14H16O4', 'C9H15N5O8P', 'C20H30N6O12S2', 'C10H14O2', 'C12H15NO3', 'C18H35O3', 'C31H47N9O18P3S2', 'C20H30O4', 'C12H15NO', 'C95H182O15P2', 'C4H12NS', 'C18H21NO4', 'C6H5O4', 'C9H15O4PBr6', 'C21H22O7', 'C22H36O19R2', 'C3H4O6S', 'C8H12N2', 'CH3F', 'C2HNCl2', 'C8H12NO6', 'C33H54O11', 'C8H9NO', 'C22H35O2', 'C31H41N7O6', 'C6H2NO3R2S', 'C33H60O8', 'NA', 'C3H5Cl3', 'C8H8NO3', 'C8H12O10PR2', 'C15H12O6', 'C6H11N3O4', 'C15H22O3', 'C40H54O', 'C7H6O6', 'C16H26NO3', 'C6H12O12P2', 'C4H12N2', 'C8H14O', 'C19H22N2O4', 'C14H21N4O2', 'C7H12NO6RS', 'C22H32O3', 'C6H11N2O4PS3', 'NA', 'C22H29O5F', 'C11H21O2', 'C24H34N7O19P3S', 'C19H20N3O12P', 'C6H12O4Br2', 'NA', 'C20H14O2', 'Fe', 'C15H10N2O3', 'C11H13O2SCl', 'C23H28N3O4', 'C29H51N2O9PRS', 'C10H16O4', 'C56H77N4O6', 'C9H13N5O3', 'C18H38N6O5S', 'NA', 'C33H41N7O19P3S', 'C10H21NO7PR', 'C13H16N5O13P2', 'C12H24O11', 'C19H30N12O6R2', 'C26H39N7O17P3S', 'C8H13O5', 'C20H21O10RS', 'C6H17N3S', 'C12H15N3O3S', 'NA', 'H2NOR', 'C30H50O', 'C10H15N3O4', 'C10H17N4O4R2', 'C15H8N2O2F6', 'C12H10N2OCl2', 'C10H16O', 'C7H11N3O', 'C3H9N3O3S', 'C26H28N2O8', 'C20H40O7P', 'C34H56NO14', 'C29H36O15', 'C14H21NO3', 'C88H138O35P2', 'C53H98O20', 'C20H12O', 'C14H12N2O8', 'C9H10NO3', 'C6H11O6R', 'C12H11N', 'C20H13NO5', 'C41H70O12', 'C14H19N6O5R', 'C22H32O6', 'C20H32O', 'C31H51N7O17P3S', 'C28H38O6', 'C43H70O11', 'C9H13NO2', 'C5H10N2O3S', 'C20H34O2', 'C30H24O6', 'C8H6O2Br', 'CH2NO2R', 'C86H99N10O26Cl3', 'C7H16NO2', 'C21H32O2', 'C31H45N7O17P3S', 'C13H12O2', 'C7H8N4S', 'C26H38N7O20P3S', 'C12H12N2O2As2', 'C56H78N2O16', 'C15H20NO2', 'C12H16N2O4', 'C16H16N3O5S', 'C18H30NO3', 'C16H21NO2', 'C22H34O3', 'C261H468O255P24', 'C27H46O', 'C13H14', 'C6H10O6', 'C12H12N4', 'C10H11N5O7P', 'C24H42O21', 'C11H12NO8', 'C12H19N3O', 'C30H50O7P2', 'C15H7O7', 'C16H12O5', 'C18H27O3', 'C14H7NO3', 'C8H19N4O6P', 'C15H18N3O4', 'C39H68O7', 'C40H56', 'C10H18O7P2', 'C15H20O7', 'NA', 'C38H54N8O10', 'C10H8', 'C40H56O3', 'C9H18N2O4', 'C20H27O3', 'C29H32O13', 'C10H14N2O', 'C22H36O', 'C23H32O8', 'C26H43O9', 'C24H39O5', 'C6H12N3PS', 'C30H52O8P', 'C13H23O2', 'C8H13N2O5', 'C20H27O2', 'C30H50O5', 'C14H13NO', 'C14H11Cl3', 'C5H10O5', 'C28H50', 'C54H76N8O15', 'C12H6Cl4', 'C14H15NO7', 'C4H5O7PR', 'C6H9NO', 'C6H6NO3S', 'C10H11NO3', 'H3O3Al', 'C26H32NO5', 'C11H11NO3', 'C21H22O9', 'C17H21N2O10S2', 'C9H7O2', 'C11H16N3O2', 'C6H7N', 'C6H8O4', 'C19H21O6', 'C20H28N3O6', 'C28H53N2O9PRS', 'C14H14NSCl', 'NA', 'C26H22N2O3ClF3', 'O4RS', 'C28H36N7O17P3SCl', 'C7H13O2S', 'C5H9O7PR', 'C16H16O2', 'C16H10O', 'C14H21N3O4', 'NA', 'C47H82N3O23R', 'C27H43O3', 'C16H19NO7', 'C153H225N43O49S', 'C29H57O2', 'C6H5OCl', 'NA', 'C16H12NO3S', 'NA', 'C26H47N2O9PRS', 'CH2R2S', 'C6H6O2', 'C35H62O3', 'C18H39O7P', 'C26H29NOCl', 'NA', 'NA', 'C6H12O6', 'C21H39N2O8PRS', 'C32H38NO4', 'C9H13N5O3', 'C10H18O', 'C27H44O', 'C14H14N3O5', 'C44H72O12', 'C9H5NO4Cl', 'C6H10O3', 'C21H43N7O18P2', 'C10H12N2O', 'C20H28O2', 'C21H22NO4Cl', 'C15H15NO', 'C22H32O3', 'C14H28O', 'C18H22NO4', 'C14H12N2O6', 'C11H16O', 'C19H30O', 'C9H8N2OCl2', 'O4S', 'C7H7O7', 'C20H32', 'NA', 'C31H42O12', 'C30H50O4', 'NA', 'C18H44N7', 'C10H16O', 'C9H10NO3RS', 'C4H6NO4', 'C8H19N4O2', 'C15H7O16S3', 'C11H21NO', 'C22H24O5', 'C16H15O2F', 'C13H10O2', 'C10H13NO', 'C10H12N5O3R', 'C27H32O15', 'C23H14O3Cl', 'C15H27O2', 'C20H29O5', 'C12H6OCl4', 'C4H8NO2', 'C23H13N4O3SF9', 'C16H12O6', 'C45H71N7O20P3S', 'C42H47N6NiO14', 'NA', 'C37H44O14', 'C8H20N6O3', 'C3H10N', 'NA', 'C26H46N2', 'C20H20O6', 'C8H8O2Cl2', 'C13H14N9O4S3', 'C20H31O5', 'C20H20O7', 'CO2', 'C23H32O6', 'NA', 'Na', 'C52H74O24', 'C14H8NO5Cl2F', 'NA', 'noformula', 'C6H5O4', 'C26H30N2O8', 'C15H23O19P4R3', 'NA', 'C6H5NO', 'C16H22N2O6', 'C28H46O7', 'C24H41NO10', 'C20H24N10O19P4', 'C20H16O6', 'C18H24O', 'C48H77O18', 'C60H115NO24P2', 'C5H10O5', 'C21H30O3', 'C19H26O3', 'C25H45N2O9PRS', 'C19H22NO4', 'C13H17NO3', 'C21H25N7O9P', 'C27H33NO4', 'C13H12N2Cl2', 'C40H49O18', 'C15H15NO2', 'C12H15N', 'C6H9O7', 'C30H52O', 'C21H19O11', 'C16H23N5O16P2', 'C28H35N3O7', 'C17H24O6', 'C19H22NO3', 'C21H29N5O20P3R2', 'C10H14N2O14P3', 'C39H47NO14', 'C32H39O19', 'C22H28O8', 'C9H14N2O7R2', 'C28H50O10', 'C17H26N2O2', 'C6H7NO2', 'C5H9NO7P', 'C19H18O7', 'Co', 'C19H34NO', 'C19H17N7O6', 'C15H10O2', 'C20H24O7', 'C2H4O4S*2', 'C8H16O4', 'C16H27N2O11R', 'C11H13N2O2', 'C30H47O4', 'C24H32O4', 'C9H11N2O2Br', 'C21H29N2O5', 'C23H31N2O6', 'CH2NOR', 'H2O4Cr', 'C19H20O6', 'C15H11NO4F3', 'C13H8O5', 'C15H9O5', 'C35H61NO8', 'C33H41N5O6S2', 'C12H20NO3', 'C20H32O', 'C28H37O7Cl', 'C171H304N4O88P2', 'C10H6N2OS2', 'C18H19NO3', 'C13H19N3O4', 'C31H42N5O5', 'C11H22N4O3R2', 'C42H70NO15', 'HRS', 'C28H46O', 'C16H22N6O4', 'H2NR', 'C15H12N4O6S2', 'C23H22O6', 'C24H20O13R', 'C22H33N4O13', 'C3H2O4', 'C6H6O3', 'C10H18O', 'C22H23N6OCl', 'NA', 'C9H17NO8', 'C2HO2ClBr', 'C19H22O2', 'C20H40O7P', 'C42H52NO15', 'C15H13NO', 'C44H44CoN4O16', 'C22H30O2', 'C17H19N3O6', 'C17H25N', 'C15H20O3', 'NA', 'C23H24O12', 'C9H8N3O7', 'C21H21NO6', 'C44H49N4O16', 'C45H80N2O24', 'C30H48O5', 'C13H16N5O16P3', 'C16H16O3', 'C3H5N2O4', 'C10H12O4', 'C40H62N9O26P2', 'C13H10O5', 'C12H20NO10S3', 'C12H16N3O3PS2', 'C5H11NO', 'C13H19NO3PS2Cl', 'C37H66O7', 'C2H8NO4P', 'C22H22O7', 'C16H21N3O3', 'C17H18N4O5', 'C10H12N4O4', 'C6H9O3', 'C30H50O', 'C12H20NO2S2', 'C32H63O3', 'C25H34O3', 'C17H14O8', 'C15H14O4', 'C12H18NO17S2', 'C8H6NO5', 'C42H52FeN8O6S2', 'C31H49O3', 'C56H75N9O17', 'NA', 'NA', 'C18H31O3', 'C21H24N2O4', 'C19H12O6', 'C21H26N2O3', 'C5H10O8P', 'NA', 'C17H20N3OCl', 'C20H22O4', 'NA', 'C16H16', 'C28H51N', 'C30H45O4', 'C13H10O3', 'C4H9NO2', 'C5H4O4', 'C10H8Cl8', 'C5H16N2', 'C16H16O6', 'C17H15NO4', 'C12H5OCl5', 'C11H20O10', 'C9H13N3O4', 'C44H69N7O18P3S', 'C9H13N5O7P', 'NA', 'C13H10O3PSCl2Br', 'C32H52O2', 'C11H14N2O5', 'C12H10O4', 'C23H28O7', 'C14H8O4', 'C15H20NO', 'C102H187N3O31P2', 'C10H18O9', 'C3H5NO2R', 'C26H32O7', 'C45H67N7O17P3S', 'C36H35N2O7', 'C9H18O8', 'C15H16O5', 'C22H27N2O3', 'C12H14O12', 'C18H23N6O8P', 'C12H22O11', 'C15H23N6O5S', 'C15H19N4O10RS2', 'C18H11NO2', 'NA', 'C9H6NO2', 'C16H16O2', 'C22H44O9P', 'C27H33N2O7', 'C11H19O15P2R', 'C35H58N6O7', 'C12H6O5PBr4', 'C18H35O3', 'H2NR', 'C15H16N2O2', 'C12H10N2', 'C110H198N2O39P2', 'C11H10O', 'C15H8O5', 'C26H41N7O17P3S', 'C18H29NO3', 'C42H68NO10', 'C14H11O4', 'C19036H39872N2400O18300P2400', 'C18H38NO2', 'C21H21O7', 'NA', 'C45H74O10', 'C14H21NO12R', 'C5H11NO2S2', 'C6H8O2', 'C8H5O4', 'C20H16O7', 'C27H48O4', 'C22H19N4O2F3', 'C24H33N4O5S', 'C12H8O2', 'C15H24', 'C3H5O4P', 'C17H14O5', 'C6H12N3O3R', 'C3H6O', 'C6H5Br', 'C21H21O10', 'C9H5O6', 'C11H6O4', 'C16H15N3O4SF2', 'C9H14NO2', 'C3H5O2R', 'C19H20NO10RS', 'C6H12O12P2', 'C6H6N2O3', 'C19H24N7O8P', 'C7H9N3', 'C11H14O3', 'C15H20O3', 'H2NO3P', 'C16H12O6', 'C21H29O2R', 'C4H5O5', 'C12H21N2O3S', 'C40H71N3O15P2', 'C8H7NO2Cl2', 'C18H36O7P', 'C6H6NO5R', 'C6H14N4O9P2', 'C15H14O2', 'C17H12O2', 'C40H41FeN4O6S', 'NA', 'C19H33N2O9PRS', 'C4H5O7PR', 'C5H7O5', 'C7H14O4', 'C31H41N7O19P3S', 'C42H78O10P', 'C21H30O4', 'C45H65N3O6', 'C12H22O11', 'C3H5O6P', 'C19H36NO2', 'C23H36O4', 'C34H24O22', 'CH3NO2', 'C8H14N2O4', 'C9H13N', 'C6H9O6', 'C6H5O5S', 'C14H20N3O5PS', 'C9H13NO2', 'C35H66O4', 'C68H129N2O9PRS', 'NA', 'C18H41N5O5', 'C29H39N5O8', 'C47H68O17', 'C20H19NO5', 'C6H12O9P', 'C4H2O6', 'C12H20O29S6*2', 'C6H5N2O2', 'C31H47N7O17P3S', 'C13H16O2', 'C38H48N8O12S', 'C50H80O23', 'C22H34O18*2', 'C21H24NO4', 'C15H23N5O8P', 'C16H12O7', 'C17H24N3O15P', 'C4H9NO6P', 'C16H12O4', 'C4H8N2O3', 'C39H67N7O17P3S', 'C38H44N2O6', 'C37H42N2O6', 'C9H13N5OCl', 'C17H28', 'C10H11N5O7P', 'C6H4O4Cl', 'NA', 'C4H8NO5S', 'C9H5NOI2', 'C30H50O25', 'C9H15N2O5Se', 'C8H11NO5', 'C5H4NORS', 'C24H30N2O3', 'C9H16N3O3', 'C26H37N5O5S2', 'C17H24NO3', 'C16H34O', 'C12H10NO4Cl2', 'C6H12O9P', 'C22H14', 'C16H24O7', 'C16H14N2O2S', 'C6H13NO2', 'C35H60NO13', 'C19H42N5O7', 'C17H16O5', 'C21H20O6', 'C6H12O6', 'C12H14NO9P', 'C6H12O6', 'C19H37O2', 'C21H28O7', 'C29H34O7', 'C10H13NO3', 'C15H27N5O5', 'C15H27N2O8PRS', 'C13H20N2Cl', 'C19H17O11', 'C15H10O4', 'C6H12O6', 'C2H6Se', 'C41H71N7O18P3S', 'C16H12O8', 'C13H18N6O3', 'C27H48', 'C10H5Cl7', 'C20H24NO4', 'C42H64O12', 'C47H72O2', 'C8H16N2O3', 'C30H52O', 'C4H4O3', 'C5H13N2O', 'C30H48O2', 'C7H7NO3', 'C10H12N2O3S', 'NA', 'C23H36O6', 'C22H28O3S', 'C11H15NO3', 'C6H12O6', 'C12H14O12', 'C32H42N5O5', 'C20H32O20PR2', 'C37H72O5', 'C14H23N2O9', 'C12H3OCl5', 'C12H16N2O2', 'C41H62O', 'C6H12O2', 'C16H12N2O3', 'C40H56O2', 'C10H10N2O', 'C21H28O2', 'C8H16O', 'C3H7N3O2', 'C32H47N2O8', 'C26H41N7O17P3S', 'NA', 'C2H2OR', 'C27H40N4O14S', 'NA', 'C38H44N2O6', 'C17H17NO4', 'C18H18O6', 'C30H51N7O7', 'C38H44N2O6', 'C28H50N2O4', 'C82H57O52', 'C15H24N5O4', 'C21H30O', 'C18H22N2', 'C24H34O', 'C27H30O6Cl2', 'C9H15O12P', 'C29H34N4', 'C12H5Cl5', 'C19H19N7O6', 'C8H12N4OS2', 'C6H6NF', 'C19H25N4O18P2', 'C30H31N2O19', 'C9H17N4O4', 'C19H24O4', 'NA', 'C22H20N2O3Cl2', 'C14H21NO4', 'C8H9NO2', 'C14H10N2O4', 'C15H18O3', 'C44H67O13', 'NA', 'C62H111N5O8P', 'C16H18O10', 'C20H44N4O10', 'C6H3O4Cl2', 'C21H29N5O19P3R2', 'C20H32O2', 'C6H10O6PS', 'C14H12O4', 'C22H20O9', 'C30H28O12', 'C17H9NO4', 'C55H57N5O20', 'C21H22O8', 'C54H96O2', 'C13H20N6O4', 'C30H52', 'C2H6O', 'C6H12O9P', 'C8H18N2O3S', 'C42H59O16', 'C81H156O17P2', 'C14H9O4', 'C13H25NO2S2', 'C31H45N7O18P3S', 'C22H29N2O4', 'C31H40N5O4', 'C4H5O3Se', 'C54H62N10O33P', 'C6H8O5', 'C20H33O5', 'C25H28O4', 'C3H4NO4', 'C20H23N2O8', 'C9H10NO2F', 'C24H40N3O16R', 'C18H20NO4', 'C27H42O3', 'C51H84O22', 'C8H7NO', 'C21H34O3', 'C5H8N5Cl', 'C6H11O2', 'C13H19N2O', 'C19H30O3', 'C18H33O3', 'C12H10N4O2', 'C22H23NO7', 'C169H295N2O94P4', 'C10H10N2O6PR2', 'C11H17NO7', 'C10H16', 'C20H28O7', 'C6H4O2', 'C9H7NO', 'C20H19O5', 'C7H11O3', 'C10H7O3S', 'C20H23N2O2', 'C151H265N2O79P4', 'C6H12O9P', 'C44H79N3O15P2', 'C16H22NO3', 'C7H17N4O2', 'C18H21N6O7S', 'C7H7O7', 'C15H20NO2', 'NA', 'C12H19NO23S4*2', 'NA', 'C6H12O9P', 'C34H30FeN4O4', 'C15H9O10S', 'C6H15O2PS3', 'C7H5NO5', 'C25H34NO4', 'C15H16O9', 'NA', 'C26H43O2R', 'C34H44O9', 'C15H14O5', 'C17H11O8', 'C55H72N4O6M

In [ ]:
# Look for metabolites with specific composition

target_elements = ["C21", "N7", "P2"]

for entry in thermo_formulas:
    if all(elem in entry for elem in target_elements):
        print(entry)

C21H27N7O14P2
C21H44N7O18P2
C21H29N7O15P2
C21H43N7O18P2
C21H26N7O14P2
C21H33N7O13P2S
C21H44N7O17P2
C21H44N7O17P2
C21H44N7O18P2

In [ ]:
# LOOCKUP INFORMATION OF SPECIFIC METABOLITES USING THEIR FORMULA

metabolites_to_check = [
    "C21H27N7O14P2",
    "C21H29N7O15P2",
    "C21H26N7O14P2",
]

for met in metabolites_to_check:
    found = False
    for met_id, entry in thermo_data['metabolites'].items():
        name_lower = entry.get('formula', '').lower()
        # Exact match
        if met.lower() == name_lower:
            print(f"Metabolite ID: {met_id}")
            for key, value in entry.items():
                print(f"  {key}: {value}")
            print("-"*50)
            found = True
            break  # stop after the first exact match
    if not found:
        print(f"{met} ❌ NOT found in thermo_data")
        print("-"*50)

Metabolite ID: cpd00004
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.2679
  mass_std: 663.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWOW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00004
  nH_std: 27
  name: NADH
  formula: C21H27N7O14P2
  deltaGf_std: -524.32
  error: Nil
  charge_std: -2
  other_names: ['NADH', 'DPNH', 'Nicotinamide adenine dinucleotide - reduced', 'Nicotinamideadeninedinucleotide-reduced', 'nadh']
--------------------------------------------------
Metabolite ID: cpd02951
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.238
  mass_std: 681.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 9, 'RWOW': 2, 'RWCHdblW': 3, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 2, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 5, 'RWCdblWW': 2}
  id: cpd02951
  nH_std: 29
  name: (6S)-6-beta-Hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide
  formula: C21H29N7O15P2
  deltaGf_std: -574.72
  error: Nil
  charge_std: -2
  other_names: ['(6S)-6-beta-Hydroxy-1,4,5,6-tetrahydronicotinamide-adenine dinucleotide']
--------------------------------------------------
Metabolite ID: cpd00003
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.3569
  mass_std: 662.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWCHdblW': 6, 'mid_phos': 1, 'WPO4nW': 1, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'TWWCdblW': 2, 'HeteroAromatic': 3, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00003
  nH_std: 26
  name: NAD+
  formula: C21H26N7O14P2
  deltaGf_std: -529.59
  error: Nil
  charge_std: -1
  other_names: ['NAD+', 'NAD', 'Nicotinamide adenine dinucleotide', 'DPN', 'Diphosphopyridine nucleotide', 'Nadide', 'Nicotinamideadeninedinucleotide', 'nad']
--------------------------------------------------

# Load thermodynamics database

In [ ]:
# Download thermo database
!wget https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb -O thermo_data.thermodb

# Load thermodynamics
thermo_data = load_thermoDB("thermo_data.thermodb")

# Print thermo_data keys

print(f"Thermo Data loaded successfully:{thermo_data.keys()}")

--2026-01-04 16:01:23--  https://raw.githubusercontent.com/EPFL-LCSB/pytfa/master/data/thermo_data.thermodb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2184378 (2.1M) [application/octet-stream]
Saving to: ‘thermo_data.thermodb’

thermo_data.thermod 100%[===================>]   2.08M  --.-KB/s    in 0.07s

2026-01-04 16:01:24 (31.0 MB/s) - ‘thermo_data.thermodb’ saved [2184378/2184378]

Thermo Data loaded successfully:dict_keys(['name', 'units', 'metabolites', 'cues'])

In [ ]:
type(thermo_data)

dict

In [ ]:
thermo_data.keys()

dict_keys(['name', 'units', 'metabolites', 'cues'])

In [ ]:
# Adjust model compartments as required by TFA

model.compartments = {
    'c': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'e': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },

    'u': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'p': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    }
}

# Step 1: map metabolites to standard compartments
for met in model.metabolites:
    if met.compartment in ["c", "cytosol"]:
        met.compartment = "c"
    elif met.compartment in ["e", "extracellular"]:
        met.compartment = "e"

# Step 2: collect all compartments used by metabolites
used_compartments = set([met.compartment for met in model.metabolites])

# Step 3: ensure all compartments exist and are dicts
for c in used_compartments:
    val = model.compartments.get(c)
    # overwrite any string or missing compartment with dict
    model.compartments[c] = {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02
    }

print("Final compartments:", model.compartments)

Final compartments: {'c': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'u': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'p': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'e': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}}

In [ ]:
rxn = model.reactions.get_by_id('AACOAR_syn')
rxn.lower_bound = -1000
rxn.upper_bound = 1000

for rxn in model.reactions:
    rxn.lower_bound = max(rxn.lower_bound, -1000)
    rxn.upper_bound = min(rxn.upper_bound, 1000)


tmodel = ThermoModel(
    thermo_data,
    model
)

for comp in tmodel.compartments:
    tmodel.compartments[comp] = {
        "pH": 7.0,
        "ionicStr": 0.25
    }

tmodel.solver = "glpk" #'optlang-cplex'


# Set physiological concentration ranges
tmodel.metabolites.get_by_id("nadph[c]").concentration = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("nadp[c]").concentration  = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("h[c]").concentration     = (1e-8, 1e-6)
tmodel.metabolites.get_by_id("coa[c]").concentration   = (1e-6, 1e-3)
#for met in tmodel.metabolites:
#    met.concentration = (1e-9, 1e-2)


tmodel.prepare()
tmodel.convert()

In [ ]:
# TFA OPTIMIZATION

sol = tmodel.optimize()

DEBUG:thermomodel_Model Exported from COBRA Toolbox:'slim_optimize' ((), {}) 441.55 sec

In [ ]:
print(sol.status)
print(sol.fluxes['AACOAR_syn'])

optimal
0.12374999999995748

In [ ]:
# FBA OPTIMIZATION

sol2 = model.optimize()
print(sol2.status)
print(sol2.fluxes['PHBS_syn'])

optimal
0.12375000000000087

In [ ]:
# Explain why thi is necessary??
rxn = tmodel.reactions.get_by_id('AACOAR_syn')
rxn.thermo['deltaG0_prime'] = (-25.0, 2.0)
rxn.thermo

{'isTrans': False,
 'computed': False,
 'deltaGR': 1000.0,
 'deltaGRerr': 1000.0,
 'deltaG0_prime': (-25.0, 2.0)}

In [ ]:
rxn = tmodel.reactions.get_by_id('AACOAR_syn')
rxn.thermo

{'isTrans': False,
 'computed': False,
 'deltaGR': 1000.0,
 'deltaGRerr': 1000.0,
 'deltaG0_prime': (-25.0, 2.0)}

# Formula normalization and matching

In [ ]:
gem_formulas = {
    m.id: m.formula
    for m in model.metabolites
    if m.formula is not None
}
gem_formulas

In [ ]:
# Normalize Formula using Hill notation
import re
from collections import defaultdict

def normalize_formula(formula):
    """
    Normalize chemical formula to Hill-like notation.
    Example: 'H12C6O6P1' -> 'C6H12O6P'
    """
    if formula is None:
        return None

    # Parse elements and counts
    tokens = re.findall(r'([A-Z][a-z]?)(\d*)', formula)
    if not tokens:
        return None

    elements = defaultdict(int)
    for el, count in tokens:
        elements[el] += int(count) if count else 1

    # Hill system: C, then H, then others alphabetically
    ordered = []
    if 'C' in elements:
        ordered.append(('C', elements.pop('C')))
    if 'H' in elements:
        ordered.append(('H', elements.pop('H')))
    for el in sorted(elements):
        ordered.append((el, elements[el]))

    return ''.join(f"{el}{cnt if cnt > 1 else ''}" for el, cnt in ordered)

In [ ]:
# Find
thermo_norm = set(
    normalize_formula(f) for f in thermo_formulas
    if normalize_formula(f) is not None
)

gem_norm = {
    mid: normalize_formula(f)
    for mid, f in gem_formulas.items()
    if normalize_formula(f) is not None
}

In [ ]:
matched = {
    mid: f for mid, f in gem_norm.items()
    if f in thermo_norm
}

In [ ]:
len(matched)

1412

In [ ]:
unmatched = {
    mid: f for mid, f in gem_norm.items()
    if f not in thermo_norm
}

In [ ]:
len(unmatched)

706

In [ ]:
for mid, f in list(matched.items())[:20]:
    print(mid, f)

gam6p[c] C6H13NO8P
cgly[c] C5H10N2O3S
achms[c] C6H11NO4
pcox_u R
octe9ACP[c] C18H33ORS
pep[c] C3H2O6P
hgbam[c] C45H58N6O12
nac[c] C6H4NO2
r3mmal[c] C5H6O5
leu__L[c] C6H13NO2
ahcys[c] C14H20N6O5S
h2o_cx[c] H2O
orot[c] C5H3N2O4
na1[c] Na
ala_B[c] C3H7NO2
pqh2_um[p] C53H82O2
26dap_LL[c] C7H14N2O4
ddcaACP[c] C12H23ORS
trdox[c] X
glu__D[c] C5H8NO4

In [ ]:
# CHANGE FORMULA MANUALLY

met = model.metabolites.get_by_id('coa[c]')
met.formula = 'C21H36N7O16P3S'
# keep the charge as is

# Match metabolites by name

In [ ]:
'Acetyl-CoA' in thermo_formulas

True

In [ ]:
metabolites_to_check = [
    "nadph",
    "nadh",
    "acetyl-coa",
    "nad+",
    "nadp+",
    "3-hydroxybutyryl-coa",
    "acetoacetyl-coa",
    "coa"
]

for met in metabolites_to_check:
    found = False
    for met_id, entry in thermo_data['metabolites'].items():
        name_lower = entry.get('name', '').lower()
        # Exact match
        if met.lower() == name_lower:
            print(f"Metabolite ID: {met_id}")
            for key, value in entry.items():
                print(f"  {key}: {value}")
            print("-"*50)
            found = True
            break  # stop after the first exact match
    if not found:
        print(f"{met} ❌ NOT found in thermo_data")
        print("-"*50)

Metabolite ID: cpd00005
  pKa: []
  deltaGf_err: 4.2579
  mass_std: 742.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'prim_phos': 1, 'amide': 1, 'RWCHWW': 8, 'TWWCdblW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'WNH2': 2, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 3, 'RWCdblWW': 2}
  id: cpd00005
  nH_std: 27
  name: NADPH
  formula: C21H27N7O17P3
  deltaGf_std: -736.82
  error: Nil
  charge_std: -3
  other_names: ['NADPH', 'TPNH', 'Nicotinamide adenine dinucleotide phosphate - reduced', 'Nicotinamideadeninedinucleotidephosphate-reduced', 'nadph']
--------------------------------------------------
Metabolite ID: cpd00004
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.2679
  mass_std: 663.0
  struct_cues: {'RWWNW': 2, 'mid_phos': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWOW': 2, 'RWCHdblW': 5, 'WPO4nW': 1, 'TWWCdblW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'RWCH2W': 1, 'OCCC': 1, 'HeteroAromatic': 2, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00004
  nH_std: 27
  name: NADH
  formula: C21H27N7O14P2
  deltaGf_std: -524.32
  error: Nil
  charge_std: -2
  other_names: ['NADH', 'DPNH', 'Nicotinamide adenine dinucleotide - reduced', 'Nicotinamideadeninedinucleotide-reduced', 'nadh']
--------------------------------------------------
Metabolite ID: cpd00022
  pKa: [1.46, 2.01, 2.62, 6.72, 12.78]
  deltaGf_err: 3.5344
  mass_std: 806.0
  struct_cues: {'WNH2': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'WSW': 1, 'smide': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 3, 'WCH2W': 6, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 3}
  id: cpd00022
  nH_std: 35
  name: Acetyl-CoA
  formula: C23H35N7O17P3S
  deltaGf_std: -785.83
  error: Nil
  charge_std: -3
  other_names: ['Acetyl-CoA', 'Acetyl coenzyme A', 'acetyl-coA', 'acetyl-CoA', 'acetyl-coa']
--------------------------------------------------
Metabolite ID: cpd00003
  pKa: [1.8, 2.56, 12.69, 13.31, 14.3]
  deltaGf_err: 4.3569
  mass_std: 662.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'WNH2': 2, 'amide': 1, 'RWCHWW': 8, 'RWCHdblW': 6, 'mid_phos': 1, 'WPO4nW': 1, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'TWWCdblW': 2, 'HeteroAromatic': 3, 'PrimOH': 4, 'RWCdblWW': 2}
  id: cpd00003
  nH_std: 26
  name: NAD+
  formula: C21H26N7O14P2
  deltaGf_std: -529.59
  error: Nil
  charge_std: -1
  other_names: ['NAD+', 'NAD', 'Nicotinamide adenine dinucleotide', 'DPN', 'Diphosphopyridine nucleotide', 'Nadide', 'Nicotinamideadeninedinucleotide', 'nad']
--------------------------------------------------
Metabolite ID: cpd00006
  pKa: []
  deltaGf_err: 4.3471
  mass_std: 741.0
  struct_cues: {'RWWNW': 1, 'WRdNWRW': 1, 'mid_phos': 1, 'prim_phos': 1, 'amide': 1, 'RWCHWW': 8, 'TWWCdblW': 2, 'RWCHdblW': 6, 'WPO4nW': 1, 'WNH2': 2, 'RWOW': 2, 'Origin': 1, 'WketoneW': 1, 'WCH2W': 2, 'RWdblNW': 3, 'OCCC': 1, 'HeteroAromatic': 3, 'PrimOH': 3, 'RWCdblWW': 2}
  id: cpd00006
  nH_std: 26
  name: NADP+
  formula: C21H26N7O17P3
  deltaGf_std: -742.09
  error: Nil
  charge_std: -2
  other_names: ['NADP+', 'NADP', 'Nicotinamide adenine dinucleotide phosphate', 'beta-Nicotinamide adenine dinucleotide phosphate', 'TPN', 'Triphosphopyridine nucleotide', 'Nicotinamide adenine dinucleotide phosphate -', 'Nicotinamideadeninedinucleotidephosphate', 'nadp']
--------------------------------------------------
Metabolite ID: cpd16898
  pKa: []
  deltaGf_err: 10000000.0
  mass_std: 850.0
  struct_cues: {}
  id: cpd16898
  nH_std: 39
  name: 3-Hydroxybutyryl-CoA
  formula: C25H39N7O18P3S
  deltaGf_std: 10000000.0
  error: No molfile exists for this compound.
  charge_std: 10000000
  other_names: ['3-Hydroxybutyryl-CoA']
--------------------------------------------------
Metabolite ID: cpd00279
  pKa: [1.46, 2.01, 2.62, 6.72, 10.35]
  deltaGf_err: 3.5804
  mass_std: 848.0
  struct_cues: {'WNH2': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'WSW': 1, 'smide': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 4, 'WCH2W': 7, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 3}
  id: cpd00279
  nH_std: 37
  name: Acetoacetyl-CoA
  formula: C25H37N7O18P3S
  deltaGf_std: -812.61
  error: Nil
  charge_std: -3
  other_names: ['Acetoacetyl-CoA', 'Acetoacetyl coenzyme A', '3-Acetoacetyl-CoA', 'acetoacetyl-CoA', 'acetoacetyl-coa']
--------------------------------------------------
Metabolite ID: cpd00010
  pKa: [1.46, 2.01, 2.62, 8.38, 10.07]
  deltaGf_err: 3.4521
  mass_std: 764.0
  struct_cues: {'WNH2': 1, 'WSH': 1, 'RWCHWW': 4, 'RWCHdblW': 2, 'TWWCdblW': 2, 'RWdblNW': 3, 'WWCWW': 1, 'PrimOH': 2, 'RWCdblWW': 1, 'RWWNW': 1, 'WWCHW': 1, 'HeteroAromatic': 2, 'RWOW': 1, 'WPO4nW': 1, 'prim_phos': 1, 'amide': 2, 'Origin': 1, 'WketoneW': 2, 'WCH2W': 6, 'WNHW': 2, 'mid_phos': 1, 'WCH3': 2}
  id: cpd00010
  nH_std: 33
  name: CoA
  formula: C21H33N7O16P3S
  deltaGf_std: -751.994
  error: Nil
  charge_std: -3
  other_names: ['CoA', 'Coenzyme A', 'CoA-SH', 'CoenzymeA', 'coA', 'coenzyme a']
--------------------------------------------------

# VERY IMPORTANT CODE

In [ ]:
# ================================
# VERY IMPORTANT CODE
# CORRECT GEM FORMULAS TO MAKE COMPATIBLE WITH THERMODB (BEFORE RUNNING TFA)
# ================================

import re
from collections import Counter

# --------------------------------
# INPUT DATA
# --------------------------------
Thermodb_meta_interest = [
    "C21H27N7O17P3",
    "C21H27N7O14P2",
    "C23H35N7O17P3S",
    "C21H26N7O14P2",
    "C25H39N7O18P3S",
    "C21H26N7O17P3",
    "C25H37N7O18P3S",
    "C21H33N7O16P3S"
]

GEM_meta_interest = [
    "C21H26N7O17P3",
    "C21H27N7O14P2",
    "C23H34N7O17P3S",
    "C21H26N7O14P2",
    "C25H38N7O18P3S",
    "C21H25N7O17P3",
    "C25H36N7O18P3S",
    "C21H32N7O16P3S"
]

# GEM metabolite IDs in SAME ORDER
gem_met_ids = [
    "nadph_c",
    "nadh_c",
    "accoa_c",
    "nad_c",
    "3hbcoa__R_c",
    "nadp_c",
    "aacoa_c",
    "coa_c",
]

# --------------------------------
# FORMULA PARSING UTILITIES
# --------------------------------
def parse_formula(formula):
    """Convert formula string to Counter"""
    return Counter({
        elem: int(count) if count else 1
        for elem, count in re.findall(r'([A-Z][a-z]?)(\d*)', formula)
    })

def counter_to_formula(counter):
    """Convert Counter back to formula string (Hill order, omit 1s)"""
    parts = []

    # Hill system: C, H, then others alphabetically
    if 'C' in counter:
        parts.append(f"C{counter['C']}" if counter['C'] != 1 else "C")
    if 'H' in counter:
        parts.append(f"H{counter['H']}" if counter['H'] != 1 else "H")

    for el in sorted(counter):
        if el in ('C', 'H'):
            continue
        count = counter[el]
        parts.append(f"{el}{count}" if count != 1 else el)

    return ''.join(parts)


def compare_formulas(thermo_f, gem_f):
    """Return element-wise difference GEM − ThermoDB"""
    t = parse_formula(thermo_f)
    g = parse_formula(gem_f)
    elements = set(t) | set(g)
    return {el: g.get(el, 0) - t.get(el, 0) for el in elements}

def update_gem_formula(gem_f, thermo_f):
    """Add missing elements from ThermoDB into GEM formula"""
    g = parse_formula(gem_f)
    t = parse_formula(thermo_f)

    for el, count in t.items():
        if g.get(el, 0) < count:
            g[el] = count

    return counter_to_formula(g)

# --------------------------------
# APPLY UPDATES TO MODEL
# --------------------------------
for met_id, thermo_f, gem_f in zip(gem_met_ids,
                                   Thermodb_meta_interest,
                                   GEM_meta_interest):

    diff = compare_formulas(thermo_f, gem_f)

    # Safety check (CRITICAL for TFA)
    for el in diff:
        if el in ("C", "N", "P") and diff[el] != 0:
            raise ValueError(
                f"Unsafe formula mismatch for {met_id}: element {el}"
            )

    new_formula = update_gem_formula(gem_f, thermo_f)

    if new_formula != gem_f:
        met = mytfa.metabolites.get_by_id(met_id)

        print(f"Updating {met_id}")
        print(f"  old: {gem_f}")
        print(f"  new: {new_formula}")
        print(f"  ThermoDB:       {thermo_f}")

        met.formula = new_formula

        # PRINT FROM MODEL OBJECT
        print(f"  new (model):  {met.formula}")
        print("-" * 40)


print("✅ GEM formulas updated and TFA-ready.")

Updating nadph_c
  old: C21H26N7O17P3
  new: C21H27N7O17P3
  ThermoDB:       C21H27N7O17P3
  new (model):  C21H27N7O17P3
----------------------------------------
Updating accoa_c
  old: C23H34N7O17P3S
  new: C23H35N7O17P3S
  ThermoDB:       C23H35N7O17P3S
  new (model):  C23H35N7O17P3S
----------------------------------------
Updating 3hbcoa__R_c
  old: C25H38N7O18P3S
  new: C25H39N7O18P3S
  ThermoDB:       C25H39N7O18P3S
  new (model):  C25H39N7O18P3S
----------------------------------------
Updating nadp_c
  old: C21H25N7O17P3
  new: C21H26N7O17P3
  ThermoDB:       C21H26N7O17P3
  new (model):  C21H26N7O17P3
----------------------------------------
Updating aacoa_c
  old: C25H36N7O18P3S
  new: C25H37N7O18P3S
  ThermoDB:       C25H37N7O18P3S
  new (model):  C25H37N7O18P3S
----------------------------------------
Updating coa_c
  old: C21H32N7O16P3S
  new: C21H33N7O16P3S
  ThermoDB:       C21H33N7O16P3S
  new (model):  C21H33N7O16P3S
----------------------------------------
✅ GEM formulas updated and TFA-ready.

In [ ]:
model.metabolites.get_by_id("coa[c]").summary()

NameError: name 'model' is not defined

In [ ]:
# Match metabolites of interest with

mets_to_check = [
    "nadph[c]",
    "nadh[c]",
    "accoa[c]",
    "nad[c]",
    "3hbcoa__R[c]",
    "nadp[c]",
    "aacoa[c]",
    "coa[c]"
]
results = []

for met_id in mets_to_check:
    try:
        met = model.metabolites.get_by_id(met_id)
        model_formula = met.formula
        in_thermo = model_formula in thermo_formulas
        results.append((met_id, met.formula, model_formula, in_thermo))
    except KeyError:
        results.append((met_id, None, None, False))
for met_id, raw, norm, hit in results:
    print(f"{met_id:12s} | model: {raw} | normalized: {norm} | in thermodb: {hit}")

NameError: name 'model' is not defined

# GEM to TFA prep

In [ ]:
# Adjust model compartments as required by TFA

cobra_model.compartments = {
    'c': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'e': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },

    'u': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    },
    'p': {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02,
    }
}

# Step 1: map metabolites to standard compartments
for met in cobra_model.metabolites:
    if met.compartment in ["c", "cytosol"]:
        met.compartment = "c"
    elif met.compartment in ["e", "extracellular"]:
        met.compartment = "e"

# Step 2: collect all compartments used by metabolites
used_compartments = set([met.compartment for met in cobra_model.metabolites])

# Step 3: ensure all compartments exist and are dicts
for c in used_compartments:
    val = cobra_model.compartments.get(c)
    # overwrite any string or missing compartment with dict
    cobra_model.compartments[c] = {
        'pH': 7.0,
        'ionicStr': 0.25,
        'c_min': 1e-6,
        'c_max': 0.02
    }

print("Final compartments:", cobra_model.compartments)

Final compartments: {'c': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'u': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'p': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}, 'e': {'pH': 7.0, 'ionicStr': 0.25, 'c_min': 1e-06, 'c_max': 0.02}}

## Run test

In [ ]:
thermo_data = {
    "name": "PHB_minimal",

    "units": {
        "energy": "kJ/mol"
    },

    "metabolites": {
        m.id: {"formula": m.formula}
        for m in model.metabolites
        if m.formula is not None and m.id.endswith("_c")
    },

    "cues": {
        "AACOAR_syn": {
            "delta_g0": -25.0,
            "uncertainty": 5.0
        }
    }
}

NameError: name 'model' is not defined

In [ ]:
thermo_data.keys()

dict_keys(['name', 'units', 'metabolites', 'cues'])

In [ ]:
for m in model.metabolites:
    m.id = m.id.replace("[c]", "_c")

In [ ]:
# Build thermo model

# Ensure the COBRA model has a description attribute
if not hasattr(model, "description"):
    model.description = ""

# Correct argument order for your pyTFA version
tmodel = ThermoModel(thermo_data, model)

for c, val in tmodel.compartments.items():
    if isinstance(val, dict):
        tmodel.compartments[c] = c  # just keep the key as a string

2025-12-30 06:15:07,156 - thermomodel_Model Exported from COBRA Toolbox - INFO - # Model initialized with units {'energy': 'kJ/mol'} and temperature 298.15 K
INFO:thermomodel_Model Exported from COBRA Toolbox:# Model initialized with units {'energy': 'kJ/mol'} and temperature 298.15 K

# Add missing metabolites seed ID

In [ ]:
# Adjust constraints since some reactions have values ><1000
for rxn in tmodel.reactions:
    if rxn.lower_bound < -1000:
        rxn.lower_bound = -1000
    if rxn.upper_bound > 1000:
        rxn.upper_bound = 1000

In [ ]:
# CHECK MODEL BEFORE TFA
model.summary() #  is the default objective function

In [ ]:
model.metabolites.get_by_id('nadph[c]').summary()

# Match reactions

In [ ]:
# CHECK PRECURSOR REACTIONS
precursor_rxns = [
    "AACOAR_syn",
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
]

for rxn_id in precursor_rxns:
    if any(rxn_id in v.name for v in dg_vars):
        print(f"{rxn_id}: thermo-constrained ✅")
    else:
        print(f"{rxn_id}: NOT thermo-constrained ❌")

AACOAR_syn: NOT thermo-constrained ❌
PHBS_syn: NOT thermo-constrained ❌
ACACT1r: NOT thermo-constrained ❌
ACACCT: NOT thermo-constrained ❌

In [ ]:
# Assuming your model is called 'model' and it's a COBRApy model

# Get the metabolite
met = model.metabolites.get_by_id("3hbcoa__R[c]")

# Find reactions where this metabolite is produced (stoichiometry > 0)
producing_reactions = [rxn for rxn in met.reactions if rxn.get_coefficient(met) > 0]

# Print them
for rxn in producing_reactions:
    print(rxn.id, rxn.reaction)

AACOAR_syn aacoa[c] + h[c] + nadph[c] --> 3hbcoa__R[c] + nadp[c]

In [ ]:


# Re-run prepare and convert
tmodel.prepare()
tmodel.convert()

2025-12-30 06:15:19,195 - thermomodel_Model Exported from COBRA Toolbox - INFO - # Model preparation starting...
INFO:thermomodel_Model Exported from COBRA Toolbox:# Model preparation starting...
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gam6p_c (D-Glucosamine 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cgly_c (Cys Gly C5H10N2O3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite achms_c (O Acetyl L homoserine C6H11NO4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pcox_u (Plastocyanin(Cu2+)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite octe9ACP_c (Cis-octadec-9-enoyl-[acyl-carrier protein] ((9Z)-n-C18:1)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fdp_c (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5caiz_c (5-phosphoribosyl-5-carboxyaminoimidazole) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pep_c (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cpd00010 (Coenzyme A) not present in thermoDB
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbam_c (Hydrogenobyrinate a,c diamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nac_c (Nicotinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite r3mmal_c (D-erythro-3-Methylmalate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite leu__L_c (L-Leucine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ahcys_c (S-Adenosyl-L-homocysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ru5p__D_c (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 14dhncoa_c (1,4-dihydroxy-2-napthoyl-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2o_cx_c (H2O H2O) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2s_c (Hydrogen sulfide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite orot_c (Orotate C5H3N2O4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite g1p_c (D-Glucose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hdecACP_c ((R)-3-Hydroxydecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite na1_c (Sodium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala_B_c (Beta-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyc3p_c (Glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pqh2_um[p] (Plastoquinol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap_LL_c (LL-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ddcaACP_c (Dodecanoyl-ACP (n-C12:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_cx_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdox_c (Oxidized thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3oddecACP_c (3-Oxododecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glu__D_c (D-Glutamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h_cx_c (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dutp_c (DUTP C9H11N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite paps_c (3'-Phosphoadenylyl sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mg2_c (Magnesium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hdeACP_c (Cis-hexadec-9-enoyl-[acyl-carrier protein] (n-C16:1)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_c (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite anth_c (Anthranilate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhpt_c (Dihydropteroate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thex2eACP_c (Trans-Hex-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fmn_c (FMN C17H19N4O9P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pppi_c (Inorganic triphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udp_c (UDP C9H11N2O12P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cit_c (Citrate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acACP_c (Acetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uama_c (UDP-N-acetylmuramoyl-L-alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite eig3p_c (D-erythro-1-(Imidazol-4-yl)glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c4mop_c (3-Carboxy-4-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lys__L_c (L-Lysine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 13dpg_c (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gmp_c (GMP C10H12N5O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite utp_c (UTP C9H11N2O15P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdrd_c (Reduced thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite so4_c (Sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5apru_c (5-Amino-6-(5'-phosphoribosylamino)uracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hmppp9_c ( 13(1)-Hydroxy-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pydx5p_c (Pyridoxal 5'-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2dhp_c (2-Dehydropantoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ade_c (Adenine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite asp__L_c (L-Aspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2sephchc_c (2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acg5p_c (N-Acetyl-L-glutamyl 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdp_c (GDP C10H12N5O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbyr_c (Hydrogenobyrinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite palmACP_c (Palmitoyl-ACP (n-C16:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pser__L_c (O-Phospho-L-serine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ocACP_c (Octanoyl-ACP (n-C8:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dttp_c (DTTP C10H13N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 6pgc_c (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gcald_c (Glycolaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2p4c2me_c (2-phospho-4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cmp_c (CMP C9H12N3O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pro_c (Protein component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pi_c (Phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pnto__R_c ((R)-Pantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dump_c (DUMP C9H11N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite omppp9_c (13(1)-Oxo-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 23dhmp_c ((R)-2,3-Dihydroxy-3-methylpentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gtp_c (GTP C10H12N5O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4h2oglt_c (4 Hydroxy 2 oxoglutarate C5H4O6) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prfp_c (1-(5-Phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite man1p_c (D-Mannose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dxyl5p_c (1-deoxy-D-xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hddecACP_c ((R)-3-Hydroxydodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cu2_c (Copper) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malACP_c (Malonyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2mahmp_c (2-Methyl-4-amino-5-hydroxymethylpyrimidine diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phpyr_c (Phenylpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fe2_c (Fe2+ mitochondria) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phllqne_c (Phylloquinone) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite toct2eACP_c (Trans-Oct-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dgdp_c (DGDP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uaccg_c (UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acald_c (Acetaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2s_c (Superoxide anion) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite alac__S_c ((S)-2-Acetolactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hmop_c ((R)-3-Hydroxy-3-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4abz_c (4-Aminobenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prbamp_c (1-(5-Phosphoribosyl)-AMP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ca2_c (Calcium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyclt_c (Glycolate C2H3O3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite butACP_c (Butyryl-ACP (n-C4:0ACP)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppcys_c (N-((R)-4-Phosphopantothenoyl)-L-cysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpgal_c (UDPgalactose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite f6p_c (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lac__D_c (D-Lactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite his__L_c (L-Histidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite agdpcbi_c (Adenosine-GDP-cobinamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s17bp_c (Sedoheptulose 1,7-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dctp_c (DCTP C9H12N3O13P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thf_c (5,6,7,8-Tetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 25aics_c ((S)-2-[5-Amino-1-(5-phospho-D-ribosyl)imidazole-4-carboxamido]succinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ni2_c (Nickel) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dtdp4d6dg_c (DTDP-4-dehydro-6-deoxy-D-glucose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malcoa_c (Malonyl CoA C24H33N7O19P3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fum_c (Fumarate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_cw_c (Cell wall component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ACP_c (Acyl carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mlthf_c (5,10-Methylenetetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h[p] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhf_c (7,8-Dihydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dudp_c (DUDP C9H11N2O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3omrsACP_c (3-Oxotetradecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trnaglu_c (TRNA (Glu)) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pre6a_c (Precorrin 6A) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ametam_c (S-Adenosylmethioninamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hhexACP_c ((R)-3-Hydroxyhexanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppan_c (D-4'-Phosphopantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite quln_c (Quinolinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite frdp_c (Farnesyl diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyald_c (D-Glyceraldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uacgam_c (UDP-N-acetyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pram_c (5-Phospho-beta-D-ribosylamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap__M_c (Meso-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdpmann_c (GDP-D-mannose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite db4p_c (3,4-dihydroxy-2-butanone 4-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actACP_c (Acetoacetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actp_c (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ugmd_c (UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s7p_c (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cbm_c (Carbamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite co2_c (CO2 CO2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite zeax_c (Zeaxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ptrc_c (Putrescine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adp_c (ADP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3a2oxpp_c (3-Amino-2-oxopropyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aspsa_c (L-Aspartate 4-semialdehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite tdec2eACP_c (Trans-Dec-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phom_c (O-Phospho-L-homoserine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite amylose_c (Amylose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5mdr1p_c (5-Methylthio-5-deoxy-D-ribose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite rb15bp_cx_c (D-Ribulose 1,5-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bcryptox_c (Beta-Cryptoxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite spmd_c (Spermidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpsq_c (UDP-6-sulfoquinovose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2_c (Hydrogen) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adocbip_c (Adenosyl cobinamide phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phycy_c ((3Z)-Phycocyanobilin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nadh_c (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aps_c (Adenosine 5'-phosphosulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dpcoa_c (Dephospho-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite xu5p__D_c (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite no2_c (Nitrite) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4hbz_c (4-Hydroxybenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3odecACP_c (3-Oxodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhnpt_c (Dihydroneopterin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5aprbu_c (5-Amino-6-(5'-phosphoribitylamino)uracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite iasp_c (Iminoaspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nmn_c (NMN C11H14N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pigm_c (Pigment component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2cpr5p_c (1-(2-Carboxyphenylamino)-1-deoxy-D-ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pchlld_c (Protochlorophyllide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_u (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala__L_c (L-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c2hmp_c (3-Carboxy-2-hydroxy-4-methylpentanoate) has no seed_id

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPTc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC20M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHFR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHPPDA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHORM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCBT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:E4PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLGC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cu2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THISAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DBTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BACCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtex : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COCHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1bpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FNOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD1ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PBDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCALDD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLBRAN2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCGLYCabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLMS_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUCYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUK_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUSx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCL_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCTO1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOXG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRRx : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBCh : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HESR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACALD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACNML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBIK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADOCBLtonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPRDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3PApp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM3Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PApp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMHE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGt3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHGDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AKGt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATA_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATA_L2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD19xr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD3y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALKP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLTN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLULPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALPATE160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALPATG160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AM3PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AM4PA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMALT4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMMQLT8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPMS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPTASEPG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APG3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARBTNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARBabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARHGDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARMEPNS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASCBptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATHRDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BETALDHx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BETALDHy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BGLA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BMOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BUTCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BUTSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BWCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBIAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBItonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBL1abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBL1tonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBLAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CD2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CD2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGUNPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CELBpts : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS160E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS160G : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS180E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CFAS180G : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHLabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHLt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHOLD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHOLID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHTBSptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CINNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CMtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAPabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPGNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPGNtonex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPH4S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CRNCAL2 : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIR2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:O16A4COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:O16AT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OBTFL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCTDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OHPHM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMBZLM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMMBLHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OMPHHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHHXy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXCOAHDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXDHCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PA181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAI2I : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPSR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDE1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDE4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PE181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PG181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP120abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP140abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP141abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP160abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP161abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP180abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGP181abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHEMEabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PNSPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POAACR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPAKr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCSCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPDOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPGPPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPTHpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSP_Lpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHRpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTRCTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUACGAMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUACGAMtr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYROX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINDHyi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R15BPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R5PPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:REPHACCOAI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RFAMPtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RIBabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR3b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR1c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR2c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR3c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR4c2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPNTPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RU5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SADT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SBTPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SBTptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SCYSDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SELabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SGSAD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHSL1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SKMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SLNTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SOTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCt2_2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULFACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:T2DECAI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TALA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TAURabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPAGTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TGBPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THIORDXi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THMabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMAOR1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMAOR2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMPPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPRDCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRE6PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TREptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPAS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TSULabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TTRCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TUNGSabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UACMAMO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPKAAT : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sulfac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tartr__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tartr__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_taur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_thr__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tma_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tmao_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tol_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tre_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_tsul_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_udcpo5_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ump_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_urate_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_val__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_vanln_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_xmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FACOAL160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALGTHLs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FAS120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FAS200 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FASC200ACP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCOAHA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOAMtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FORAMD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PCtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PStex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCCb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCCc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCTR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCBL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYC2Ptex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GPDDA4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTPHs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2CO3D : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD8i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIStex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KAT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LACD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCTStpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSMO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MACCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP2ex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP3ex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MELIBt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METOX1s : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METOX2s : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MGSA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMTSAO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOSDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MUCCY_kt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:N2trpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH3c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NMNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NT5C : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD6pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OHEDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHACOAOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA1E180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2A181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2E181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLIPA2G181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPAt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPCOAC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PREPHACPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RFAMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SCYSSL_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SLCYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTRDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TARTRDtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THPAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPPtppi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VNLNpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:XMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:XTSNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BSORy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:INS2D : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HGD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6AR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:N2OR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6YM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MHPGLUT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APPLDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTMLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APATr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRUK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFK_2 : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B
Warning : BO3/B

Streaming output truncated to the last 5000 lines.
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP1ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP1ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP4ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MDDCP5ex
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMETabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_METabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MGt5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MLTG5
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MME
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMM2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMSAD2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MMSAD3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MNabc
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTH4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MOTS4
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MTHFR2_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionMTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_MTI
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADHDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADPHQR2
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADPHQR3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NADS1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NAt3_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NFORGLUAH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NH4t
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NIT1b_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NTD5pp
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionNTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_NTPTP1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OCBT_1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OCOAT1
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OOR3r
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OPHHX
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OXOAEL
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionOXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_OXPTNDH
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionPACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UF_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: UR_PACCOAL3
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating only use constraints for reactionPC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: FU_PC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: BU_PC
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added constraint: SU_PC

In [ ]:
from pytfa.optim.variables import DeltaG

print("ΔG present:", DeltaG in tmodel.variables)

ΔG present: False

In [ ]:
rxn = tmodel.reactions.get_by_id("AACOAR_syn")

# Manually define standard Gibbs energy (kJ/mol)
tmodel.add_reaction_thermo(
    rxn,
    delta_g0=-25.0,    # literature estimate
    uncertainty=5.0
)

NameError: name 'tmodel' is not defined

In [ ]:
print("ΔG variables present:", DeltaG in tmodel.variables)

if DeltaG not in tmodel.variables:
    raise RuntimeError(
        "❌ No DeltaG variables created → thermo_data not matched"
    )

ΔG variables present: False

RuntimeError: ❌ No DeltaG variables created → thermo_data not matched

In [ ]:
tmodel.metabolites.get_by_id("nadph[c]").concentration = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("nadp[c]").concentration  = (1e-6, 1e-3)
tmodel.metabolites.get_by_id("h[c]").concentration     = (1e-8, 1e-6)
tmodel.metabolites.get_by_id("coa[c]").concentration   = (1e-6, 1e-3)

KeyError: 'nadph_c'

In [ ]:
rxn_id = "AACOAR_syn"
rxn = tmodel.reactions.get_by_id(rxn_id)

dg = tmodel.variables[DeltaG][rxn]

print(f"{rxn_id} ΔG bounds (kJ/mol):")
print("  LB:", dg.lb)
print("  UB:", dg.ub)

In [ ]:
# Solve
# FBA max PHB
fba = model.optimize()

# TFA max PHB
tfa = tmodel.optimize()
print("Thermo-FBA objective:", tfa.objective_value)

DEBUG:thermomodel_Model Exported from COBRA Toolbox:'slim_optimize' ((), {}) 91.40 sec

Thermo-FBA objective: 0.18

In [ ]:
print(tfa.objective_value -fba.objective_value)

In [ ]:
import inspect
from pytfa import ThermoModel

print(inspect.signature(ThermoModel))

(thermo_data=None, model=<Model None at 0x7e7adc9688c0>, name=None, temperature=298.15, min_ph=3, max_ph=9)

In [ ]:
# Reaction ID in your GEM
rxn = tmodel.reactions.get_by_id("AACOAR_syn")


# Add standard Gibbs energy (kJ/mol)
tmodel.add_reaction_thermo(
    rxn,
    delta_g0=-25.0,   # literature-based estimate
    uncertainty=5.0
)

In [ ]:
# --------------------------------------
# 2. PREPARE + CONVERT (safe even if partial)
# --------------------------------------
tmodel.convert()

2025-12-30 02:59:25,442 - thermomodel_Model Exported from COBRA Toolbox - INFO - # Model preparation starting...
INFO:thermomodel_Model Exported from COBRA Toolbox:# Model preparation starting...
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gam6p[c] (D-Glucosamine 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cgly[c] (Cys Gly C5H10N2O3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite achms[c] (O Acetyl L homoserine C6H11NO4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pcox_u (Plastocyanin_Cu2+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite octe9ACP[c] (Cis-octadec-9-enoyl-_acyl-carrier protein __9Z-n-C18:1) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fdp[c] (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5caiz[c] (5-phosphoribosyl-5-carboxyaminoimidazole) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pep[c] (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbam[c] (Hydrogenobyrinate a,c diamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nac[c] (Nicotinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite r3mmal[c] (D-erythro-3-Methylmalate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite leu__L[c] (L-Leucine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ahcys[c] (S-Adenosyl-L-homocysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ru5p__D[c] (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 14dhncoa[c] (1,4-dihydroxy-2-napthoyl-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2o_cx[c] (H2O H2O) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2s[c] (Hydrogen sulfide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite orot[c] (Orotate C5H3N2O4) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite g1p[c] (D-Glucose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hdecACP[c] (_R-3-Hydroxydecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite na1[c] (Sodium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc[c] (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala_B[c] (Beta-Alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyc3p[c] (Glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pqh2_um[p] (Plastoquinol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap_LL[c] (LL-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ddcaACP[c] (Dodecanoyl-ACP _n-C12:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2pglyc_cx[c] (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdox[c] (Oxidized thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3oddecACP[c] (3-Oxododecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glu__D[c] (D-Glutamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h_cx[c] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dutp[c] (DUTP C9H11N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite paps[c] (3'-Phosphoadenylyl sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mg2[c] (Magnesium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hdeACP[c] (Cis-hexadec-9-enoyl-_acyl-carrier protein _n-C16:1) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2[c] (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite anth[c] (Anthranilate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhpt[c] (Dihydropteroate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thex2eACP[c] (Trans-Hex-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fmn[c] (FMN C17H19N4O9P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pppi[c] (Inorganic triphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udp[c] (UDP C9H11N2O12P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cit[c] (Citrate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acACP[c] (Acetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uama[c] (UDP-N-acetylmuramoyl-L-alanine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite eig3p[c] (D-erythro-1-_Imidazol-4-ylglycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3c4mop[c] (3-Carboxy-4-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lys__L[c] (L-Lysine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 13dpg[c] (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gmp[c] (GMP C10H12N5O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite utp[c] (UTP C9H11N2O15P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trdrd[c] (Reduced thioredoxin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite so4[c] (Sulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5apru[c] (5-Amino-6-_5'-phosphoribosylaminouracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hmppp9[c] ( 13_1-Hydroxy-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pydx5p[c] (Pyridoxal 5'-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2dhp[c] (2-Dehydropantoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ade[c] (Adenine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite asp__L[c] (L-Aspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2sephchc[c] (2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acg5p[c] (N-Acetyl-L-glutamyl 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdp[c] (GDP C10H12N5O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite hgbyr[c] (Hydrogenobyrinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite palmACP[c] (Palmitoyl-ACP _n-C16:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pser__L[c] (O-Phospho-L-serine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ocACP[c] (Octanoyl-ACP _n-C8:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dttp[c] (DTTP C10H13N2O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 6pgc[c] (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gcald[c] (Glycolaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2p4c2me[c] (2-phospho-4-_cytidine 5'-diphospho-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cmp[c] (CMP C9H12N3O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pro[c] (Protein component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pi[c] (Phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pnto__R[c] (_R-Pantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dump[c] (DUMP C9H11N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite omppp9[c] (13_1-Oxo-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 23dhmp[c] (_R-2,3-Dihydroxy-3-methylpentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gtp[c] (GTP C10H12N5O14P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4h2oglt[c] (4 Hydroxy 2 oxoglutarate C5H4O6) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prfp[c] (1-_5-Phosphoribosyl-5-__5-phosphoribosylaminomethylideneaminoimidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite man1p[c] (D-Mannose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dxyl5p[c] (1-deoxy-D-xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hddecACP[c] (_R-3-Hydroxydodecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cu2[c] (Copper) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malACP[c] (Malonyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2mahmp[c] (2-Methyl-4-amino-5-hydroxymethylpyrimidine diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phpyr[c] (Phenylpyruvate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fe2[c] (Fe2+ mitochondria) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phllqne[c] (Phylloquinone) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite toct2eACP[c] (Trans-Oct-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dgdp[c] (DGDP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uaccg[c] (UDP-N-acetyl-3-O-_1-carboxyvinyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite acald[c] (Acetaldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2s[c] (Superoxide anion) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite alac__S[c] (_S-2-Acetolactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hmop[c] (_R-3-Hydroxy-3-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4abz[c] (4-Aminobenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite prbamp[c] (1-_5-Phosphoribosyl-AMP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ca2[c] (Calcium) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyclt[c] (Glycolate C2H3O3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite butACP[c] (Butyryl-ACP _n-C4:0ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppcys[c] (N-__R-4-Phosphopantothenoyl-L-cysteine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpgal[c] (UDPgalactose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite f6p[c] (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite lac__D[c] (D-Lactate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite his__L[c] (L-Histidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite agdpcbi[c] (Adenosine-GDP-cobinamide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s17bp[c] (Sedoheptulose 1,7-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dctp[c] (DCTP C9H12N3O13P3) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite thf[c] (5,6,7,8-Tetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 25aics[c] (_S-2-_5-Amino-1-_5-phospho-D-ribosylimidazole-4-carboxamidosuccinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ni2[c] (Nickel) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dtdp4d6dg[c] (DTDP-4-dehydro-6-deoxy-D-glucose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite malcoa[c] (Malonyl CoA C24H33N7O19P3S) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite fum[c] (Fumarate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_cw[c] (Cell wall component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ACP[c] (Acyl carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite mlthf[c] (5,10-Methylenetetrahydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h[p] (H+) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhf[c] (7,8-Dihydrofolate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dudp[c] (DUDP C9H11N2O11P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3omrsACP[c] (3-Oxotetradecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite trnaglu[c] (TRNA _Glu) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pre6a[c] (Precorrin 6A) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ametam[c] (S-Adenosylmethioninamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3hhexACP[c] (_R-3-Hydroxyhexanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4ppan[c] (D-4'-Phosphopantothenate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite quln[c] (Quinolinate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite frdp[c] (Farnesyl diphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite glyald[c] (D-Glyceraldehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite uacgam[c] (UDP-N-acetyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pram[c] (5-Phospho-beta-D-ribosylamine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 26dap__M[c] (Meso-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite gdpmann[c] (GDP-D-mannose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite db4p[c] (3,4-dihydroxy-2-butanone 4-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actACP[c] (Acetoacetyl-ACP) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite actp[c] (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ugmd[c] (UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite s7p[c] (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite cbm[c] (Carbamate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite co2[c] (CO2 CO2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite zeax[c] (Zeaxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ptrc[c] (Putrescine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adp[c] (ADP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3a2oxpp[c] (3-Amino-2-oxopropyl phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aspsa[c] (L-Aspartate 4-semialdehyde) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite tdec2eACP[c] (Trans-Dec-2-enoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phom[c] (O-Phospho-L-homoserine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite amylose[c] (Amylose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5mdr1p[c] (5-Methylthio-5-deoxy-D-ribose 1-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite rb15bp_cx[c] (D-Ribulose 1,5-bisphosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bcryptox[c] (Beta-Cryptoxanthin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite spmd[c] (Spermidine) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite udpsq[c] (UDP-6-sulfoquinovose) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite h2[c] (Hydrogen) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite adocbip[c] (Adenosyl cobinamide phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite phycy[c] (_3Z-Phycocyanobilin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nadh[c] (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite aps[c] (Adenosine 5'-phosphosulfate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dpcoa[c] (Dephospho-CoA) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite xu5p__D[c] (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite no2[c] (Nitrite) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 4hbz[c] (4-Hydroxybenzoate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 3odecACP[c] (3-Oxodecanoyl-_acyl-carrier protein) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite dhnpt[c] (Dihydroneopterin) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 5aprbu[c] (5-Amino-6-_5'-phosphoribitylaminouracil) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite iasp[c] (Iminoaspartate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite nmn[c] (NMN C11H14N2O8P) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite bm_pigm[c] (Pigment component of biomass) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite 2cpr5p[c] (1-_2-Carboxyphenylamino-1-deoxy-D-ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite pchlld[c] (Protochlorophyllide) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite o2_u (O2 O2) has no seed_id
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Metabolite ala__L[c] (L-Alanine) has no seed_id

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC11M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMDPHT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYCOPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RB15BPtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DB4PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXPRIi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTPCII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EHGLAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDX5PS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPDi_nadp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRC3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RZ5PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6YM_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DDPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNabc_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMMM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_23dhmp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPMD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PGtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPMEK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITCIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DVOCHR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2CO3_NAt_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEMEOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAMAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITCIb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_COFACTORS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSERTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR160y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDHf : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR3_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDAPAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E_1_cx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACODA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLU5K : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR100y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPOb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_h2_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPTASECG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHCHCS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_4_um_copy1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGCVT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSL2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRASCSi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRDR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTRCabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3MT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCOATA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMPK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HMBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGLYCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HTHRPDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCT1_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPDDI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPODM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MAN6PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSERT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NNDPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CUabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCYRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPCcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR180y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHRDH_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRAIi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTPATi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC6AR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPTc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ORPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FCLT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHQS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC20M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHFR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AFAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FRTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GTHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DADK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHPPDA : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CHORM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GAPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCBT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:E4PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLGC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RPI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BPNT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cu2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PItex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THISAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THII : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DBTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BACCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEOHtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_amob_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADNK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CCGS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUERT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SAMTRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EPXQR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPGLDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMAND : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GFUCS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPGLC46DH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_1_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH_1_4_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KAS15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACPS6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDR18 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDDC17 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT161 : thermo constraint NOT created

Warning : None/None

DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT1819Z_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPAT160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGPATACP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPA_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQDGS_PALM_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CDPDAGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGPS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGPP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PFOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Ktu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACLS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGTi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COCHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1bpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN181_9 : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DPPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FNOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PAT184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G3PD1ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:G6PBDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GCALDD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLBRAN2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCGLYCabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLCS1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLMS_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLNTRAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUCYS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUK_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUSx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLUt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLXCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYALDDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCL_2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYCTO1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GMPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOXG : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPROa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HSDxi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IMACTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:KARA2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LALDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCARS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LGTHL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MAN1PT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDH_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MI1PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MI1PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMC1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPOMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFD2i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NABTNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NAR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_1u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_2p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_2u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_3u : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH1_4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDH2_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NDPK9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NH4tpp_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NPHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHBDC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:P5CD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:P5CRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC17M : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHbr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDHcr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PDX5PS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGSA184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHYTES2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPNCL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPPGO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PROabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PUTA3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYAM5PO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXNO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBCh : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RBPC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SSALy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNF : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HESR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACALD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACNML : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACPPAT120 : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD7 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HACD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HADPCOADH3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HBZOPT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEPT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HEPT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HG2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HISTD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HKNDDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HKNTDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HMPK1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HOMt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPACOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPPK2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPPPNDO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HPYRP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXAND : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HXPRT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:HYD3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:I4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ICYSDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ILEabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:INDOLEt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:IPDPS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ISETACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:K2L4Aabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:K2L4Aabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kt2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Kt3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCADi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LCARSyi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDGUNPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LDH_D2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LEUTAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPACabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LIPOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LKDRA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPADSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1A181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1E181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G120pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G140pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G141pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G160pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G161pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G180pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL1G181pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2A181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATE181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2ATG181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2E181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LPLIPAL2G181 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LSERDHr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:LYSAM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:L_LACD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:L_LACD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MACPD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALDDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTATr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTHXabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MALTptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MANGLYCptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MANptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCITL2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCPST : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP1App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MCTP2App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MDDCP5pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MECDPDH5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MEPNabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METDabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METNA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METSOXR1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METSOXR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:METabcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MG2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MICITDr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MINCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP1App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP2App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP2Bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDCP3App : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MLTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMCD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MMM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN2tipp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MN6PP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MNLptspp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOADSUx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOAT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSAR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADDP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOx : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NODOy : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:NTPP1 : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_Model Exported from COBRA Toolbox:OCOAT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OOR3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OPHHX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXOAEL : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:OXPTNDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PACCOAL3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PC : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PEPCK_re : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PGK_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC100 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC121 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC140 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC60 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PHAPC80 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:POR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPA_1pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPDK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPK2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PPKr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRDX : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PRFGS_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSD180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSSA160 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:PSSA180 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QRr : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:QUINtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RIBabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:RNTR4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:S7PI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SALCHS4abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SDPTAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SHSL2r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCBZT1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCBZT2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCCabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SUCR : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:SULabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THD2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRA2i : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRAi : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:THRabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TMDPP : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TREabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TRPTA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TSULabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:TYRt2rpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:USHD : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:VALabc : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ZN2t4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT120 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT141 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:2AGPEAT161 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4CMLCL_kt : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:4HTHRK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:5CM2HMUDI : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ACGAMPM : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AGMtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD2ir : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALCD4 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD31_1 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALDD6 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ALR3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:AMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ANHGMtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APENTAMAH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:APTNAT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASO3tex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ASPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ATPHs : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BSCT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:BTS3r : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CITtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CLt3_2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:COALCDH : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CONFRLtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CONFRLtpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYO1a : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:CYOO2pp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DAPDA : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DCMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGNSK : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DGSNtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DHNAOT : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DKMPPD3 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:DTMPtex : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ECOAH12 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EDTXS2 : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:ETOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_12ppd__S_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_2hxmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_3mb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_4hbz_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_4hphac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_agm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ala__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_amp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_anhgm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_arbt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_aso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_aso4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_asp__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_btoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_but_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_buts_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_butso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_bz_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cell4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cell500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cellb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cgly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cit_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_cmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_confrl_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dad_2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_damp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dca_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dcmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dcyt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dextrin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dgmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dgsn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_drib_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_dtmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_duri_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_enter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_eths_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_Model Exported from COBRA Toolbox:EX_sulfac_e : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B
Warning : BO3/B

Streaming output truncated to the last 5000 lines.
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for starch[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_starch[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for zcarote[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_zcarote[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 1h12dhl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_1h12dhl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhrdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhrdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34thsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34thsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 34dhr[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_34dhr[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ardv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rdv[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hsxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for sxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_sxt[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for phytfl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_phytfl[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for phytof[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_phytof[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for pq[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_pq[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for neuspn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_neuspn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 3vbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_3vbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 3hebcpd[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_3hebcpd[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpda[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpda[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpdb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpdb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ggbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ggbcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ggbcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ggbcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpa[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bcpb[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bo3[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bo3[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bo3[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bo3[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bm_min[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bm_min[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for bm_oth[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_bm_oth[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4abut[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4abut[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4hpro_LT[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4hpro_LT[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5dglcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5dglcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5oxpro[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5oxpro[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acac[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acac[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acglu[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acglu[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acmana[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acmana[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for akg[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_akg[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for arab__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_arab__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for asn__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_asn__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for citm[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_citm[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for etha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_etha[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for f6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_f6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fum[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fum[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g1p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g1p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g6p[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gal[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gal[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ghb[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ghb[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glu__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glu__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glyclt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glyclt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glycogen[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glycogen[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hpyr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hpyr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hxa[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hxa[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for inost[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_inost[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lac__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lac__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for malttr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_malttr[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for man[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_man[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for xyl__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_xyl__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 12ppd__S[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_12ppd__S[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4abut[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4abut[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 4hpro_LT[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_4hpro_LT[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5dglcn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5dglcn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 5oxpro[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_5oxpro[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acac[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acac[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for acglu[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_acglu[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for asn__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_asn__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for citm[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_citm[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for etha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_etha[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for f6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_f6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fum[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fum[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for g6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_g6p[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ghb[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ghb[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glyclt[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glyclt[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glycogen[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glycogen[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for hpyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_hpyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for inost[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_inost[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lac__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lac__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mal__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mal__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for oxa[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_oxa[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for pyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_pyr[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for tartr__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_tartr__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rbl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rbl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for ru5p__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_ru5p__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gal1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gal1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galt[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fuc__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fuc__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fcl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fcl__L[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fc1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fc1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcur[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcur[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for glcur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_glcur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for fruur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_fruur[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mana[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mana[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2ddglcn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2ddglcn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for xylu__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_xylu__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for mnl[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_mnl[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for galctn__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_galctn__D[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2dh3dgal[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2dh3dgal[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for 2dh3dgal6p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_2dh3dgal6p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[p]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rmn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rmn[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rml[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rml[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for rml1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_rml1p[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for melib[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_melib[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for gam[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_gam[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for lcts[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_lcts[e]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for dkdi[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_dkdi[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:generating thermo variables for d5kg[c]
DEBUG:thermomodel_Model Exported from COBRA Toolbox:Added variable: LC_d5kg[c]

In [ ]:
DeltaG in tmodel.variables

False

In [ ]:
print(tmodel.variables.keys())

['QULNS', 'QULNS_reverse_66da1', 'ORNDC', 'ORNDC_reverse_63596', 'MSBENZMT', 'MSBENZMT_reverse_a902a', 'DESAT18a', 'DESAT18a_reverse_fd859', 'FUM', 'FUM_reverse_d3642', 'PHYFXOR', 'PHYFXOR_reverse_84960', 'VPAMTr', 'VPAMTr_reverse_872bd', 'GLYCL', 'GLYCL_reverse_e418f', 'NDPK7', 'NDPK7_reverse_9dc79', 'GTPCI', 'GTPCI_reverse_1ee86', 'MTHFC', 'MTHFC_reverse_f6fcc', 'GCATENEC', 'GCATENEC_reverse_ae4a5', 'ORNTA', 'ORNTA_reverse_5adff', 'UPPDC1', 'UPPDC1_reverse_cb592', 'GARFT', 'GARFT_reverse_7ecb6', 'H4THDPR', 'H4THDPR_reverse_617be', 'UDPG4E', 'UDPG4E_reverse_08c7f', 'GLCS3', 'GLCS3_reverse_5e7ed', 'ASPTA', 'ASPTA_reverse_36525', 'PRAGSr', 'PRAGSr_reverse_fd2d8', 'ACKr', 'ACKr_reverse_b49c0', 'KAS14', 'KAS14_reverse_25582', 'UDCPDPS', 'UDCPDPS_reverse_04082', 'GLNS', 'GLNS_reverse_59581', 'SHKK', 'SHKK_reverse_163fd', 'G1PACT', 'G1PACT_reverse_51580', '5DOAN', '5DOAN_reverse_c8e7d', 'OHPBAT', 'OHPBAT_reverse_7e72e', 'Htex', 'Htex_reverse_6f9a4', '3HAD60', '3HAD60_reverse_d7fb5', 'PGI', 'PGI_reverse_27efc', 'PNTK', 'PNTK_reverse_236b6', '3OAR60', '3OAR60_reverse_40a5c', 'ACGK', 'ACGK_reverse_684be', 'LEUabcpp', 'LEUabcpp_reverse_ab30a', 'G5SD', 'G5SD_reverse_af8c0', 'DTMPK', 'DTMPK_reverse_44d5a', 'NDH_1_1_um_copy1', 'NDH_1_1_um_copy1_reverse_4db8b', 'HSTPT', 'HSTPT_reverse_b3657', 'U23GAAT2', 'U23GAAT2_reverse_387ef', 'PGK', 'PGK_reverse_02696', 'IMPD', 'IMPD_reverse_6e625', 'LPOR', 'LPOR_reverse_ae81c', 'CHRPL', 'CHRPL_reverse_46f50', 'GCALDDy', 'GCALDDy_reverse_2af46', 'RNDR1', 'RNDR1_reverse_f4be1', 'AIRC2', 'AIRC2_reverse_50d74', 'MTAP', 'MTAP_reverse_96009', 'DHORD3um', 'DHORD3um_reverse_137f3', 'TRPS1', 'TRPS1_reverse_35c22', 'NNATr', 'NNATr_reverse_8ab73', '3OAR120', '3OAR120_reverse_5a2b4', 'HISTDb', 'HISTDb_reverse_acd55', 'ADCL', 'ADCL_reverse_0051f', 'CYTK1', 'CYTK1_reverse_2fa21', 'PSIum', 'PSIum_reverse_43c5e', 'Cobalt2abcppI', 'Cobalt2abcppI_reverse_894f2', 'THRS', 'THRS_reverse_a994c', 'AOXPBDC', 'AOXPBDC_reverse_81d1e', 'NAMNPP', 'NAMNPP_reverse_ebb31', 'PERD', 'PERD_reverse_c9aa4', 'DAPDC', 'DAPDC_reverse_d3ab8', 'COCHL_1', 'COCHL_1_reverse_736d9', '3OAR100', '3OAR100_reverse_d47e7', 'PPK2', 'PPK2_reverse_3275d', 'ZNabcpp', 'ZNabcpp_reverse_14d34', 'GLYDHDA', 'GLYDHDA_reverse_663d3', 'ANS', 'ANS_reverse_4e062', 'SUCBZL', 'SUCBZL_reverse_536e6', 'ADPT', 'ADPT_reverse_567cf', 'RNDR3', 'RNDR3_reverse_bc84a', 'DHNANT', 'DHNANT_reverse_39a88', 'GND', 'GND_reverse_eec5c', 'O2tcx', 'O2tcx_reverse_6b2f8', 'TRPS3', 'TRPS3_reverse_bdfbb', 'DNTPPA', 'DNTPPA_reverse_7e624', 'HOXGfx', 'HOXGfx_reverse_2964c', 'TMPPP_1', 'TMPPP_1_reverse_7b964', 'ACONT', 'ACONT_reverse_7c2d5', 'IGPS', 'IGPS_reverse_feb80', 'HBZNPT', 'HBZNPT_reverse_37fab', 'HSDy', 'HSDy_reverse_77ce7', 'GLYOX', 'GLYOX_reverse_6ab0a', 'AICART', 'AICART_reverse_b7b59', 'SQD1', 'SQD1_reverse_c0265', 'GK1', 'GK1_reverse_11a40', 'R05219', 'R05219_reverse_1009e', 'PPND', 'PPND_reverse_5463c', 'IPDPS_syn', 'IPDPS_syn_reverse_8eea6', 'H4THDPS', 'H4THDPS_reverse_5f722', 'BIOMASS_PIGMENTS', 'BIOMASS_PIGMENTS_reverse_b23ff', '3HAD160', '3HAD160_reverse_c0da0', 'HISTDa', 'HISTDa_reverse_76147', 'ADSL1r', 'ADSL1r_reverse_2ae14', 'H2Otu_syn', 'H2Otu_syn_reverse_7aa62', 'ADOCBLS', 'ADOCBLS_reverse_005a5', 'ALAALAr', 'ALAALAr_reverse_18faa', 'ACOATA', 'ACOATA_reverse_8c02f', 'GLCP2_1', 'GLCP2_1_reverse_b0967', 'GLYCK', 'GLYCK_reverse_c3ee2', 'MAN1PT', 'MAN1PT_reverse_c317b', 'DMBZIDS2', 'DMBZIDS2_reverse_6417b', 'CS', 'CS_reverse_8d7e9', 'DMATT', 'DMATT_reverse_3a731', 'PSP_L', 'PSP_L_reverse_cfa3c', 'NDPK3', 'NDPK3_reverse_37ea6', 'G3PD2', 'G3PD2_reverse_0c363', 'PHYTES', 'PHYTES_reverse_45da8', 'MOHMT', 'MOHMT_reverse_83ce0', 'FBA', 'FBA_reverse_84806', 'BIOMASS__1', 'BIOMASS__1_reverse_063c7', 'ACLSa', 'ACLSa_reverse_75fb2', 'ASAD', 'ASAD_reverse_39a64', 'PSCVT', 'PSCVT_reverse_1a852', 'TYRTA', 'TYRTA_reverse_e9311', 'SERAT', 'SERAT_reverse_0de5e', 'DHFS', 'DHFS_reverse_f7920', 'AMPMS3', 'AMPMS3_reverse_b5e80', 'ACBIPGT', 'ACBIPGT_reverse_bcc45', 'ATPM', 'ATPM_reverse_5b752', 'SEPHCHCS', 'SEPHCHCS_reverse_cb185', 'NMNDA', 'NMNDA_reverse_0dc65', 'IGPDH', 'IGPDH_reverse_b1a3c', 'OMPDC', 'OMPDC_reverse_45ba1', '3OAR80', '3OAR80_reverse_fe338', '3OAR180', '3OAR180_reverse_e234c', 'GLUSfx', 'GLUSfx_reverse_468d6', 'NADS2', 'NADS2_reverse_b427b', 'GLUTRR', 'GLUTRR_reverse_355d5', 'UAMAGS', 'UAMAGS_reverse_a0d94', 'FOLD3', 'FOLD3_reverse_4bc58', '3HAD100', '3HAD100_reverse_ca00f', 'GALUi', 'GALUi_reverse_c40d5', 'P5CR', 'P5CR_reverse_55c58', 'PQH2tum', 'PQH2tum_reverse_270a9', 'ICHORS', 'ICHORS_reverse_8e175', '3OAS140', '3OAS140_reverse_65ddc', 'SBP', 'SBP_reverse_78d5c', 'EAR60y', 'EAR60y_reverse_02e5e', 'O2tu', 'O2tu_reverse_2d1e7', 'SULabcpp', 'SULabcpp_reverse_40679', 'PPK', 'PPK_reverse_69cd8', 'BIOMASS_DNA', 'BIOMASS_DNA_reverse_9947a', 'UAPGR', 'UAPGR_reverse_4f67b', 'DHAD1', 'DHAD1_reverse_39dca', 'IPPS', 'IPPS_reverse_d94c0', 'PPBNGS', 'PPBNGS_reverse_dc5a2', 'PRE3BS', 'PRE3BS_reverse_ea947', 'PHYTES2_1', 'PHYTES2_1_reverse_bb66c', '3HAD80', '3HAD80_reverse_29891', 'LTHRK', 'LTHRK_reverse_61b82', 'ADCPS2', 'ADCPS2_reverse_34636', 'GF6PTA', 'GF6PTA_reverse_21fb1', 'O2tpp', 'O2tpp_reverse_28c7e', 'PGMT', 'PGMT_reverse_5bcdd', '3OAR140', '3OAR140_reverse_4eb2a', 'NDPK2', 'NDPK2_reverse_10df6', 'LPADSS2', 'LPADSS2_reverse_9cafc', 'DPR', 'DPR_reverse_691d8', 'H2Otex', 'H2Otex_reverse_57da2', 'TKT2', 'TKT2_reverse_7ebc7', 'SK_for_c', 'SK_for_c_reverse_b95aa', 'PPNCL2', 'PPNCL2_reverse_a65ee', 'CYTBD4cm', 'CYTBD4cm_reverse_64e50', 'HPYRRy', 'HPYRRy_reverse_197c5', 'CHORS', 'CHORS_reverse_17772', '3OAR160', '3OAR160_reverse_15066', 'ADMDC', 'ADMDC_reverse_e2782', 'PPPGO2_1', 'PPPGO2_1_reverse_9826c', 'ASP1DC', 'ASP1DC_reverse_5dad1', 'MI3PP', 'MI3PP_reverse_1228d', 'CYSS_2', 'CYSS_2_reverse_8e1d0', 'FTHFD', 'FTHFD_reverse_44321', 'MEPCT', 'MEPCT_reverse_de97a', 'PDX5POi', 'PDX5POi_reverse_797dd', 'PPCDC', 'PPCDC_reverse_39306', 'NTD6', 'NTD6_reverse_c5bce', 'NNDMBRT', 'NNDMBRT_reverse_13f8c', 'PRAIS', 'PRAIS_reverse_8e616', 'ORNTAC', 'ORNTAC_reverse_b265a', 'SUCBZS', 'SUCBZS_reverse_cdbc9', 'HGYDAS', 'HGYDAS_reverse_bc303', 'GGDPR', 'GGDPR_reverse_ea652', 'ASPCT', 'ASPCT_reverse_c18b9', 'PPNDH', 'PPNDH_reverse_58300', 'ME2', 'ME2_reverse_2b0a2', 'APRAUR', 'APRAUR_reverse_e674d', 'SADT', 'SADT_reverse_91e08', 'LDH_D', 'LDH_D_reverse_f8507', 'DPCOAK', 'DPCOAK_reverse_56ab9', 'O2tex', 'O2tex_reverse_a3b28', 'DPOR', 'DPOR_reverse_8b09e', 'ARGSL', 'ARGSL_reverse_1b949', 'HSK', 'HSK_reverse_e4218', 'EAR120y', 'EAR120y_reverse_c7353', 'BCAROHX2', 'BCAROHX2_reverse_888eb', 'HPPK', 'HPPK_reverse_e0ee3', 'PPNCL3', 'PPNCL3_reverse_cd065', 'AHCi', 'AHCi_reverse_d29ff', 'G6PDH2r', 'G6PDH2r_reverse_19ddf', 'PMANM', 'PMANM_reverse_53eb0', 'CPPPGO2', 'CPPPGO2_reverse_e5000', 'PC17M_1', 'PC17M_1_reverse_fc1bc', 'ACCOAC', 'ACCOAC_reverse_9d1cd', 'CYNL', 'CYNL_reverse_91a39', 'CYOOum', 'CYOOum_reverse_37909', 'ACLSb', 'ACLSb_reverse_588fa', 'DNMPPA', 'DNMPPA_reverse_131b7', 'METS_1', 'METS_1_reverse_65e3f', 'TRPS2', 'TRPS2_reverse_cd73f', 'PRUK', 'PRUK_reverse_a0fb4', 'FNOR_1', 'FNOR_1_reverse_80b2d', 'GART', 'GART_reverse_61742', 'G5SADs', 'G5SADs_reverse_c7fa4', 'DMTPHT', 'DMTPHT_reverse_a16f8', 'SPMDabcpp', 'SPMDabcpp_reverse_7abfe', 'DHAD2', 'DHAD2_reverse_755c6', 'PRAMPC', 'PRAMPC_reverse_54696', '3OAS80', '3OAS80_reverse_c6446', 'G1PCTYT', 'G1PCTYT_reverse_16243', 'BIOMASS_CELL_WALL', 'BIOMASS_CELL_WALL_reverse_8d1a4', 'CA2abcpp', 'CA2abcpp_reverse_aa3d6', 'UHGADA2', 'UHGADA2_reverse_e04ae', 'ASPO6', 'ASPO6_reverse_ec15c', 'ASPK', 'ASPK_reverse_115d7', 'DXPS', 'DXPS_reverse_86aca', 'PRATPP', 'PRATPP_reverse_99bf0', 'NH4tpp', 'NH4tpp_reverse_eca16', 'PAPSR', 'PAPSR_reverse_75961', 'NAD_H2', 'NAD_H2_reverse_69196', 'CYRDAAT', 'CYRDAAT_reverse_d0652', 'NTPP8', 'NTPP8_reverse_ce3f8', 'PC11M', 'PC11M_reverse_f4161', 'ARGabcpp', 'ARGabcpp_reverse_2f37a', 'PMDPHT', 'PMDPHT_reverse_8a0fd', 'DAPE', 'DAPE_reverse_e08be', 'LYCOPC', 'LYCOPC_reverse_fd996', 'RB15BPtcx', 'RB15BPtcx_reverse_6fe05', 'GLCBRAN3', 'GLCBRAN3_reverse_4cd37', 'DB4PS', 'DB4PS_reverse_43dd1', 'DXPRIi', 'DXPRIi_reverse_85956', 'GTPCII', 'GTPCII_reverse_a84d9', 'RBFSa', 'RBFSa_reverse_61d96', 'GLUTRS', 'GLUTRS_reverse_b214d', 'ALDD2y', 'ALDD2y_reverse_03afb', 'EHGLAT', 'EHGLAT_reverse_8439b', 'METAT', 'METAT_reverse_793ef', 'DHORTS', 'DHORTS_reverse_82d73', 'PDX5PS2', 'PDX5PS2_reverse_cfb17', 'GAPDi_nadp', 'GAPDi_nadp_reverse_782a6', 'PGCD', 'PGCD_reverse_1bc76', 'AIRC3', 'AIRC3_reverse_f015f', 'UMPK', 'UMPK_reverse_ae8e3', 'CBPS', 'CBPS_reverse_80907', '3HAD180', '3HAD180_reverse_c801d', 'IPPMIb', 'IPPMIb_reverse_e37a1', 'RZ5PP', 'RZ5PP_reverse_b2942', 'RBFSb_1', 'RBFSb_1_reverse_7d59e', 'GLNabcpp', 'GLNabcpp_reverse_c0546', 'NDPK8', 'NDPK8_reverse_13dd1', 'PC6YM_1', 'PC6YM_1_reverse_0b971', 'DDPA', 'DDPA_reverse_575e8', 'ACOTA', 'ACOTA_reverse_c4379', 'FBP', 'FBP_reverse_bf2c9', 'MNabc_1', 'MNabc_1_reverse_d9c27', 'NTD7', 'NTD7_reverse_20dab', 'MPOMMM', 'MPOMMM_reverse_30349', 'MTHFD', 'MTHFD_reverse_c10fd', 'PANTS', 'PANTS_reverse_11dcb', 'TMPK', 'TMPK_reverse_b7673', 'KARI_23dhmp_1', 'KARI_23dhmp_1_reverse_ef22e', 'IPMD', 'IPMD_reverse_d7a5e', '3PGtcx', '3PGtcx_reverse_a3768', 'CDPMEK', 'CDPMEK_reverse_01872', 'CITCIa', 'CITCIa_reverse_6a08b', 'DVOCHR_1', 'DVOCHR_1_reverse_1b3d8', 'H2CO3_NAt_syn', 'H2CO3_NAt_syn_reverse_5b4d9', 'HEMEOS', 'HEMEOS_reverse_b63ba', 'RPE', 'RPE_reverse_a1b04', 'MPOMT_1', 'MPOMT_1_reverse_63f7f', 'UAMAS', 'UAMAS_reverse_2b5e6', 'CITCIb', 'CITCIb_reverse_a5ab2', 'BPNT2', 'BPNT2_reverse_ab8bb', 'BIOMASS_COFACTORS', 'BIOMASS_COFACTORS_reverse_d79f8', 'HSERTA', 'HSERTA_reverse_23c8f', 'NDPK1', 'NDPK1_reverse_9216a', 'PGL', 'PGL_reverse_2bb6b', 'EAR160y', 'EAR160y_reverse_e0622', 'MECDPDHf', 'MECDPDHf_reverse_07da8', 'MTHFR3_1', 'MTHFR3_1_reverse_1a948', '3HAD140', '3HAD140_reverse_13958', 'FBA3', 'FBA3_reverse_0d49f', 'LDAPAT', 'LDAPAT_reverse_81d9c', 'MG2uabcpp', 'MG2uabcpp_reverse_adeed', 'HCO3E_1_cx', 'HCO3E_1_cx_reverse_3a8f8', 'ACODA', 'ACODA_reverse_504cc', 'GLU5K', 'GLU5K_reverse_0d895', 'EAR100y', 'EAR100y_reverse_863b6', 'PGM', 'PGM_reverse_fc9af', 'ASPOb', 'ASPOb_reverse_0f7c6', 'DM_h2_c', 'DM_h2_c_reverse_84240', 'ACS', 'ACS_reverse_37635', 'AMPTASECG', 'AMPTASECG_reverse_11d5d', 'SHCHCS3', 'SHCHCS3_reverse_fb361', 'ATPPRT', 'ATPPRT_reverse_00060', 'NDH_1_4_um_copy1', 'NDH_1_4_um_copy1_reverse_4512a', 'UAGCVT', 'UAGCVT_reverse_ba1ab', 'ADSL2r', 'ADSL2r_reverse_42348', 'PRASCSi', 'PRASCSi_reverse_11704', 'MG2tex', 'MG2tex_reverse_a1983', 'HPROb', 'HPROb_reverse_9e6b2', 'NTPP2', 'NTPP2_reverse_bff4f', 'TRDR', 'TRDR_reverse_6372e', 'NDPK6', 'NDPK6_reverse_d41ea', 'GLUPRT', 'GLUPRT_reverse_1f180', 'PTRCabcpp', 'PTRCabcpp_reverse_96b27', 'UPP3MT', 'UPP3MT_reverse_2adf0', 'DHNCOAS', 'DHNCOAS_reverse_af3a9', 'MCOATA', 'MCOATA_reverse_d10f2', 'PMPK', 'PMPK_reverse_48b12', 'HMBS', 'HMBS_reverse_23a06', 'PGLYCP', 'PGLYCP_reverse_9063f', 'UAGAAT2', 'UAGAAT2_reverse_8209e', 'HTHRPDH', 'HTHRPDH_reverse_9ee3b', 'BCT1_syn', 'BCT1_syn_reverse_8b530', 'IPDDI', 'IPDDI_reverse_6c5f9', 'GLYALDDy', 'GLYALDDy_reverse_7e106', 'CITMS', 'CITMS_reverse_37134', 'IMPC', 'IMPC_reverse_efa41', 'Htcx', 'Htcx_reverse_e3f6b', 'DHQTi', 'DHQTi_reverse_c4498', 'SPODM', 'SPODM_reverse_2648f', 'MAN6PI', 'MAN6PI_reverse_d96f0', '3OAS120', '3OAS120_reverse_06658', 'PGAMT', 'PGAMT_reverse_52c23', 'PSERT', 'PSERT_reverse_cbee4', 'HISTP', 'HISTP_reverse_5e409', 'NNDPR', 'NNDPR_reverse_445ff', 'ADSK', 'ADSK_reverse_6806d', 'MECDPS', 'MECDPS_reverse_8baa5', 'CUabcpp', 'CUabcpp_reverse_119a1', 'ADCYRS', 'ADCYRS_reverse_3513c', 'RBPCcx', 'RBPCcx_reverse_6742e', '3HAD40_2', '3HAD40_2_reverse_de35f', 'EAR180y', 'EAR180y_reverse_2cedd', 'GTHRDH_syn', 'GTHRDH_syn_reverse_d99c5', 'PRAIi', 'PRAIi_reverse_e568f', 'CYNTtabcpp', 'CYNTtabcpp_reverse_c4528', 'PTPATi', 'PTPATi_reverse_381d9', 'PC6AR_1', 'PC6AR_1_reverse_296a7', 'Kabcpp', 'Kabcpp_reverse_35f86', 'ENO', 'ENO_reverse_40eea', 'PRFGS', 'PRFGS_reverse_db4e5', 'PC8XM', 'PC8XM_reverse_8cde7', '3OAS60', '3OAS60_reverse_bff6a', 'GMPS2', 'GMPS2_reverse_aa6c4', 'RBFK', 'RBFK_reverse_8faa7', 'NTRIRfx', 'NTRIRfx_reverse_8d8c5', 'GTHPi', 'GTHPi_reverse_0b1e5', 'ARGSS', 'ARGSS_reverse_5760d', 'SPTc', 'SPTc_reverse_5cf47', 'H2Otpp', 'H2Otpp_reverse_01d15', 'TDPDRE', 'TDPDRE_reverse_26405', 'GTHOr', 'GTHOr_reverse_8f1f9', 'SHK3Dr', 'SHK3Dr_reverse_d5c8f', 'CYRDAR', 'CYRDAR_reverse_9aae4', 'ORPT', 'ORPT_reverse_19432', 'GRTT', 'GRTT_reverse_f3afe', 'BIOMASS_MEM_LIPIDS', 'BIOMASS_MEM_LIPIDS_reverse_7c142', 'PRPPS', 'PRPPS_reverse_dd7f2', 'KARA1', 'KARA1_reverse_2b971', 'FCLT', 'FCLT_reverse_1a6b6', 'PPA', 'PPA_reverse_c5293', 'DHQS', 'DHQS_reverse_3d16b', 'ANPRT', 'ANPRT_reverse_e2684', 'ADK1', 'ADK1_reverse_a6f90', 'UPP3S', 'UPP3S_reverse_8bb53', 'NDPK5', 'NDPK5_reverse_6973f', 'DHNPA_1', 'DHNPA_1_reverse_b1649', 'NDPK4', 'NDPK4_reverse_9a1c8', 'RNDR4', 'RNDR4_reverse_aff84', 'NADK', 'NADK_reverse_bba52', '3OAR40_2', '3OAR40_2_reverse_0fceb', 'TKT1', 'TKT1_reverse_a1021', 'NO3abcpp', 'NO3abcpp_reverse_79978', 'FE3abcpp', 'FE3abcpp_reverse_4aad8', 'MOBDabcpp', 'MOBDabcpp_reverse_4be38', 'NPHBDC', 'NPHBDC_reverse_8b305', 'NPDPS', 'NPDPS_reverse_e1c6b', 'NI2uabcpp', 'NI2uabcpp_reverse_db325', 'HCO3tcx', 'HCO3tcx_reverse_7ac35', 'RNDR2', 'RNDR2_reverse_7df82', 'KARI_1', 'KARI_1_reverse_0a82a', 'EAR40y', 'EAR40y_reverse_0f912', 'NADTRHD', 'NADTRHD_reverse_49725', 'DHNCOAT', 'DHNCOAT_reverse_58c26', 'BIOMASS_PROTEIN', 'BIOMASS_PROTEIN_reverse_cd861', '3OAS100', '3OAS100_reverse_bfd7d', 'G1SAT', 'G1SAT_reverse_2ec2f', 'ILETA', 'ILETA_reverse_aec70', 'UAAGDS', 'UAAGDS_reverse_313a9', 'GLCDBRAN3', 'GLCDBRAN3_reverse_85d8b', 'HEX1', 'HEX1_reverse_25efa', 'ATPSum', 'ATPSum_reverse_7df19', 'CHPHYS', 'CHPHYS_reverse_77b21', 'BCAROHX', 'BCAROHX_reverse_82eaa', 'GLYCLTDx', 'GLYCLTDx_reverse_d2f71', 'PIuabcpp', 'PIuabcpp_reverse_c4f9b', 'PC20M', 'PC20M_reverse_ceb32', 'ADSS', 'ADSS_reverse_c75bb', 'BIOMASS_RNA', 'BIOMASS_RNA_reverse_fec8b', 'DM_dialurate_c', 'DM_dialurate_c_reverse_ae7c2', 'THRPDC', 'THRPDC_reverse_877ef', 'TMDS3', 'TMDS3_reverse_bd1fa', 'DHFR', 'DHFR_reverse_65c32', 'ACGS', 'ACGS_reverse_c8939', 'AFAT', 'AFAT_reverse_951b7', 'GLYOX_1', 'GLYOX_1_reverse_d01d4', 'EAR140y', 'EAR140y_reverse_dff77', 'FRTT', 'FRTT_reverse_5200c', 'CTPS2', 'CTPS2_reverse_9c0ad', 'DESAT16a', 'DESAT16a_reverse_7f95a', 'CO2tex', 'CO2tex_reverse_3d081', 'GTHS', 'GTHS_reverse_172f9', 'UAGDP', 'UAGDP_reverse_a5ec0', 'DADK', 'DADK_reverse_006ea', 'MPOMC1_1', 'MPOMC1_1_reverse_7706e', 'Nat_Kpp', 'Nat_Kpp_reverse_03d15', '3OAS180', '3OAS180_reverse_3d9f8', 'EAR80y', 'EAR80y_reverse_2df0a', 'ERTHMMOR', 'ERTHMMOR_reverse_d7ffe', 'PDH', 'PDH_reverse_ca160', 'MPML', 'MPML_reverse_2bf21', 'USHD2', 'USHD2_reverse_08d67', 'TPI', 'TPI_reverse_c2c3b', 'DHPPDA', 'DHPPDA_reverse_11c00', 'PRMICI', 'PRMICI_reverse_af0a9', 'CYTBD4um', 'CYTBD4um_reverse_0a2a0', 'DM_co_c', 'DM_co_c_reverse_cb46e', 'CAT', 'CAT_reverse_c01ae', 'GLUR', 'GLUR_reverse_6b3bf', 'ALAR', 'ALAR_reverse_77133', 'SULR_2', 'SULR_2_reverse_59d07', 'NAt3pp', 'NAt3pp_reverse_421a2', 'ADCS', 'ADCS_reverse_5303c', 'UGMDDS', 'UGMDDS_reverse_2401f', 'BIOMASS_CARB', 'BIOMASS_CARB_reverse_8edd4', 'ICDHyr', 'ICDHyr_reverse_7f84b', 'ACHBSb', 'ACHBSb_reverse_a040e', 'MTRI', 'MTRI_reverse_36e0d', 'SPMS', 'SPMS_reverse_92c51', 'AHSERL2_1', 'AHSERL2_1_reverse_bd815', 'PEPC', 'PEPC_reverse_66f39', 'PHETA1', 'PHETA1_reverse_9d47a', 'CHORM', 'CHORM_reverse_38aac', 'GAPD', 'GAPD_reverse_459c1', 'PQH2tcm', 'PQH2tcm_reverse_90815', 'CPPPGO', 'CPPPGO_reverse_f858f', 'URIDK2r', 'URIDK2r_reverse_1aa74', 'OCBT', 'OCBT_reverse_f5568', 'E4PD', 'E4PD_reverse_babdb', 'IPPMIa', 'IPPMIa_reverse_0594d', 'GLGC', 'GLGC_reverse_f6fb0', 'PYK', 'PYK_reverse_bc8ff', '3HAD120', '3HAD120_reverse_82f09', '2PGLYCtcx', '2PGLYCtcx_reverse_9a509', 'MPOMOR_1', 'MPOMOR_1_reverse_17bb1', '3OAS160', '3OAS160_reverse_08317', 'IG3PS', 'IG3PS_reverse_12008', 'NTRARf2', 'NTRARf2_reverse_5d5d6', 'CA2t2pp', 'CA2t2pp_reverse_81d82', 'DM_5drib_c', 'DM_5drib_c_reverse_37606', 'RPI', 'RPI_reverse_853a1', 'FMNRy_1', 'FMNRy_1_reverse_1bd17', 'ANS2', 'ANS2_reverse_5a40c', 'GHMT2r', 'GHMT2r_reverse_d977f', 'BPNT', 'BPNT_reverse_53108', 'PSIIum', 'PSIIum_reverse_30799', 'CBFCum', 'CBFCum_reverse_e7502', 'SK_amylose_c', 'SK_amylose_c_reverse_116da', 'SK_14glucan_c', 'SK_14glucan_c_reverse_d5217', 'SK_glycogen_c', 'SK_glycogen_c_reverse_bf5b0', 'EX_h2o_e', 'EX_h2o_e_reverse_3ced4', 'EX_o2_e', 'EX_o2_e_reverse_efa94', 'EX_co2_e', 'EX_co2_e_reverse_d0466', 'EX_leu__L_e', 'EX_leu__L_e_reverse_d40a5', 'EX_cobalt2_e', 'EX_cobalt2_e_reverse_2bf0e', 'EX_zn2_e', 'EX_zn2_e_reverse_3c725', 'EX_so4_e', 'EX_so4_e_reverse_5c8ed', 'EX_spmd_e', 'EX_spmd_e_reverse_761ad', 'EX_ca2_e', 'EX_ca2_e_reverse_aac13', 'EX_nh4_e', 'EX_nh4_e_reverse_f9cc6', 'EX_arg__L_e', 'EX_arg__L_e_reverse_d8799', 'EX_gln__L_e', 'EX_gln__L_e_reverse_6a1a1', 'EX_mn2_e', 'EX_mn2_e_reverse_48316', 'EX_hco3_e', 'EX_hco3_e_reverse_55cc1', 'EX_mg2_e', 'EX_mg2_e_reverse_b1c98', 'EX_ptrc_e', 'EX_ptrc_e_reverse_6c850', 'EX_fe2_e', 'EX_fe2_e_reverse_25e68', 'EX_cu2_e', 'EX_cu2_e_reverse_02682', 'EX_k_e', 'EX_k_e_reverse_42613', 'EX_no3_e', 'EX_no3_e_reverse_98d30', 'EX_fe3_e', 'EX_fe3_e_reverse_8b617', 'EX_mobd_e', 'EX_mobd_e_reverse_c6396', 'EX_ni2_e', 'EX_ni2_e_reverse_7ba33', 'EX_na1_e', 'EX_na1_e_reverse_c64df', 'EX_cynt_e', 'EX_cynt_e_reverse_b53e8', 'EX_h_e', 'EX_h_e_reverse_3e0c5', 'FE3tex', 'FE3tex_reverse_d0931', 'FE2tex', 'FE2tex_reverse_62032', 'NI2tex', 'NI2tex_reverse_a2971', 'MNtex', 'MNtex_reverse_711cc', 'COBALT2tex', 'COBALT2tex_reverse_0862d', 'CU2tex', 'CU2tex_reverse_521e6', 'Zn2tex', 'Zn2tex_reverse_6b2c9', 'SPMDtex', 'SPMDtex_reverse_5a2d5', 'LEUtex', 'LEUtex_reverse_a9685', 'HCO3tex', 'HCO3tex_reverse_d9055', 'GLNtex', 'GLNtex_reverse_7b7bb', 'CYNTtex', 'CYNTtex_reverse_8c4ef', 'ARGtex', 'ARGtex_reverse_244d5', 'MOBDtex', 'MOBDtex_reverse_4fdc7', 'NH4tex', 'NH4tex_reverse_ce04b', 'SO4tex', 'SO4tex_reverse_1908f', 'NO3tex', 'NO3tex_reverse_b1290', 'NAtex', 'NAtex_reverse_0181e', 'CA2tex', 'CA2tex_reverse_27b69', 'Ktex', 'Ktex_reverse_03b32', 'CO2tpp', 'CO2tpp_reverse_d9a27', 'EX_pi_e', 'EX_pi_e_reverse_1fb09', 'PItex', 'PItex_reverse_05721', 'MDRPD', 'MDRPD_reverse_fc553', 'ENOPH', 'ENOPH_reverse_b1c96', 'ARD', 'ARD_reverse_1e910', 'UNK3', 'UNK3_reverse_8083f', 'PHYPQOX', 'PHYPQOX_reverse_846b6', 'ZISO', 'ZISO_reverse_27e2a', 'ZCARDS', 'ZCARDS_reverse_28abb', 'PLYCOI', 'PLYCOI_reverse_c2299', 'TRNFE', 'TRNFE_reverse_f6e07', 'PTHPS', 'PTHPS_reverse_272ea', 'SPR', 'SPR_reverse_d4f3a', 'THBTGT', 'THBTGT_reverse_0885a', 'CYSDES', 'CYSDES_reverse_02598', 'THISAT', 'THISAT_reverse_a22de', 'THII', 'THII_reverse_23906', 'GLYCOX1', 'GLYCOX1_reverse_b84e6', 'DXYTST', 'DXYTST_reverse_72484', 'THZT', 'THZT_reverse_26970', 'SHS1', 'SHS1_reverse_92a6f', 'MALCOAMT', 'MALCOAMT_reverse_1031e', 'OGMEACPS', 'OGMEACPS_reverse_13b17', 'OGMEACPR', 'OGMEACPR_reverse_53919', 'OGMEACPD', 'OGMEACPD_reverse_fa697', 'EGMEACPR', 'EGMEACPR_reverse_1b486', 'OPMEACPS', 'OPMEACPS_reverse_e3f2d', 'OPMEACPR', 'OPMEACPR_reverse_7cc6e', 'OPMEACPD', 'OPMEACPD_reverse_d1190', 'EPMEACPR', 'EPMEACPR_reverse_794bd', 'PMEACPE', 'PMEACPE_reverse_002c3', 'AOXSr2', 'AOXSr2_reverse_0c982', 'AMAOTr', 'AMAOTr_reverse_a5426', 'DBTS', 'DBTS_reverse_b5da6', 'BTS6', 'BTS6_reverse_40426', 'BACCL', 'BACCL_reverse_8bcde', 'LIPOCT', 'LIPOCT_reverse_0078e', 'LIPOS2', 'LIPOS2_reverse_2319a', 'MEOHtrpp', 'MEOHtrpp_reverse_3d00f', 'MEOHtex', 'MEOHtex_reverse_fb32d', 'DM_amob_c', 'DM_amob_c_reverse_90c8f', 'ADNK1', 'ADNK1_reverse_fe466', 'CDGS', 'CDGS_reverse_6b7cb', 'CCGS', 'CCGS_reverse_3ff79', 'CDGR', 'CDGR_reverse_e4464', 'QUERT', 'QUERT_reverse_caaac', 'SAMTRI', 'SAMTRI_reverse_06c4c', 'EPXQR', 'EPXQR_reverse_6205d', 'UDPGD', 'UDPGD_reverse_de167', 'UDPGLDC', 'UDPGLDC_reverse_6bd69', 'GMAND', 'GMAND_reverse_b3087', 'GFUCS', 'GFUCS_reverse_2cd5e', 'CDPGLC46DH', 'CDPGLC46DH_reverse_17ba1', 'NDH_1_1_um_copy2', 'NDH_1_1_um_copy2_reverse_85ca2', 'NDH_1_4_um_copy2', 'NDH_1_4_um_copy2_reverse_22689', 'KAS15', 'KAS15_rev

In [ ]:


# --------------------------------------
# 3. MANUAL SEED-ID ANNOTATION (COFACTORS ONLY)
# --------------------------------------
SEED_MAP1 = {
    "h[c]":     "cpd00067",
    "nadp[c]":  "cpd00005",
    "nadph[c]": "cpd00006",
    "coa[c]":   "cpd00010"
}

for met_id, seed_id in SEED_MAP1.items():
    met = tmodel.metabolites.get_by_id(met_id)
    met.annotation["seed_id"] = seed_id


conc_bounds = {
    "nadph[c]": (1e-6, 1e-3),
    "nadp[c]":  (1e-6, 1e-3),
    "h[c]":     (1e-8, 1e-6),
    "coa[c]":   (1e-6, 1e-3),
}

for met_id, bounds in conc_bounds.items():
    met = tmodel.metabolites.get_by_id(met_id)
    met.concentration = bounds

# --------------------------------------
# 5. FORCE THERMODYNAMIC FEASIBILITY
#    Acetoacetyl-CoA reductase (AACOAR)
# --------------------------------------
# Reaction: aacoa + nadph + H -> 3hbcoa + nadp
# Literature ΔG°′ ≈ −25 to −30 kJ/mol
# We enforce directionality conservatively


from pytfa.optim.variables import DeltaG

rxn = tmodel.reactions.get_by_id("AACOAR_syn")
dg = tmodel.variables[DeltaG][rxn]

# Set thermodynamic directionality
dg.upper_bound = -1.0   # kJ/mol
dg.lower_bound = -100.0

# --------------------------------------
# 6. OPTIONAL: OBJECTIVE (PHB / growth)
# --------------------------------------
# Example: maximize PHB precursor
# tmodel.objective = "PHB_SYN"

# --------------------------------------
# 7. RUN TFA OPTIMIZATION
# --------------------------------------
solution = tmodel.optimize()

dg_value = solution.raw[dg.name]
print("ΔG_AACOAR (kJ/mol):", dg_value)


# --------------------------------------
# 8. REPORT RESULTS
# --------------------------------------
print("TFA status:", solution.status)
print("Objective value:", solution.objective_value)

print("\n--- AACOAR thermodynamics ---")
print("Flux:", solution.fluxes["AACOAR_syn"])
print("ΔG (kJ/mol):", solution.raw[tmodel.reactions.AACOAR_syn.delta_g.name])

# Optional: check PHB precursor
if "3hbcoa__R[c]" in solution.fluxes:
    print("\n3HB-CoA flux:", solution.fluxes["3hbcoa__R[c]"])

KeyError: <class 'pytfa.optim.variables.DeltaG'>

In [ ]:
from pytfa.optim.variables import DeltaG

print("DeltaG variables:")
for r, var in tmodel.variables[DeltaG].items():
    if "AACOAR" in r.id:
        print(var.name)

DeltaG variables:

KeyError: <class 'pytfa.optim.variables.DeltaG'>

In [ ]:
from pytfa.optim.variables import DeltaG

phb_rxns = [
    "AACOAR_syn",
    "PHBS_syn",
    "ACACT1r",
    "ACACCT",
]

# Force thermo mode
tmodel.convert(add_thermo=True)

for r_id in phb_rxns:
    rxn = tmodel.reactions.get_by_id(r_id)

    dg = tmodel.variables[DeltaG][rxn]
    dg.lower_bound = -100
    dg.upper_bound = -5   # irreversible forward

TypeError: ThermoModel.convert() got an unexpected keyword argument 'add_thermo'

In [ ]:
def has_dGr_variable(tmodel, rxn_id):
    return any(v.name == f"DG_r_{rxn_id}" for v in tmodel.variables)

for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    print(rxn_id, has_dGr_variable(tmodel, rxn_id))

def thermo_constraints_for_rxn(tmodel, rxn_id):
    return [
        c.name for c in tmodel.constraints
        if rxn_id in c.name and "thermo" in c.name.lower()
    ]

for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    cons = thermo_constraints_for_rxn(tmodel, rxn_id)
    print(rxn_id, cons)


rows = []
for rxn_id in ["ACACT1", "ACCOAC", "PHBS_syn"]:
    rows.append({
        "reaction": rxn_id,
        "has_DG": has_dGr_variable(tmodel, rxn_id),
        "n_thermo_constraints": len(thermo_constraints_for_rxn(tmodel, rxn_id))
    })

pd.DataFrame(rows)

ACACT1 False
ACCOAC False
PHBS_syn False
ACACT1 []
ACCOAC []
PHBS_syn []

   reaction  has_DG  n_thermo_constraints
0    ACACT1   False                     0
1    ACCOAC   False                     0
2  PHBS_syn   False                     0

In [ ]:
thermo_rxns = []

for rxn in tmodel.reactions:
    rxn_id = rxn.id

    # 1) check ΔG variable
    has_dg = f"DG_r_{rxn_id}" in [v.name for v in tmodel.variables]

    if not has_dg:
        continue

    # 2) check thermo constraints
    thermo_cons = [
        c for c in tmodel.constraints
        if rxn_id in c.name and "thermo" in c.name.lower()
    ]

    if len(thermo_cons) > 0:
        thermo_rxns.append(rxn_id)

print(f"Number of thermo-constrained reactions: {len(thermo_rxns)}")
thermo_rxns[:20]

Number of thermo-constrained reactions: 0

[]

In [ ]:
rxn = tmodel.reactions.get_by_id('PHBS_syn')
for met in rxn.metabolites:
    print(met.id, getattr(met, "seed_id", "no seed_id"))

3hbcoa__R[c] C12345
phbg[c] C23456
coa[c] C00010
PHB[c] C34567

In [ ]:
# List all variables (variable objects)
for var in tmodel.variables:
    print(var)

In [ ]:
rxn = tmodel.reactions.get_by_id('PHBS_syn')

if hasattr(rxn, 'deltaG_r') and rxn.deltaG_r in tmodel.variables:
    print(f"{rxn.id} now has a thermodynamic constraint (ΔG applied).")
else:
    print(f"{rxn.id} still does NOT have a thermodynamic constraint.")

PHBS_syn still does NOT have a thermodynamic constraint.

## Map to ModelSEED Database

*   https://modelseed.org/biochem/compounds/cpd00805

*   https://academic.oup.com/nar/article/49/D1/D575/5912569

*   https://github.com/ModelSEED/ModelSEEDpy/tree/dev/tests/biochem

*   https://github.com/ModelSEED/ModelSEEDDatabase?utm_source=chatgpt.com

In [13]:
import json
from pathlib import Path

db_path = Path(MODELS_DIR / "ModelSEEDDatabase"/"Biochemistry"/"compounds.json")
if not db_path.exists():
    raise FileNotFoundError(f"File not found: {db_path}")

with open(db_path) as f:
    compounds = json.load(f)

In [14]:
print(len(compounds))
print(compounds[100])

33992
{'abbreviation': 'r5p', 'abstract_compound': None, 'aliases': ["Name: CPD-15317; D-Ribose 5-phosphate; D-ribose 5'-phosphate; D-ribose 5-phosphate; D-ribose-5-P; D-ribose-5-phosphate; D-ribose-5-phosphoric acid; RIBOSE-5P; Ribose 5-phosphate; aldehydo-D-ribose 5-phosphate; alpha-D-Ribose5-phosphate; alpha-D-ribose-5-phosphate; keto-D-ribose 5-phosphate; ribose-5-P; ribose-5-phosphate; ribose-5-phosphoric acid; ribose-5P", 'AraCyc: RIBOSE-5P', 'BiGG: r5p', 'BrachyCyc: RIBOSE-5P', 'KEGG: C00117', 'MetaCyc: CPD-15317; CPD-15895; RIBOSE-5P'], 'charge': -2, 'comprised_of': None, 'deltag': -394.12, 'deltagerr': 1.32, 'formula': 'C5H9O8P', 'id': 'cpd00101', 'inchikey': 'KTVPXOYAKDPRHY-SOOFDHNKSA-L', 'is_cofactor': 0, 'is_core': 1, 'is_obsolete': 0, 'linked_compound': None, 'mass': 229.0, 'name': 'ribose-5-phosphate', 'notes': ['GC'], 'pka': '1:3:1.22;1:4:6.25;1:11:12.91;1:13:14.31;1:14:11.31', 'pkb': '1:9:-4.39;1:11:-3.68;1:13:-3.94;1:14:-4.39', 'smiles': 'O=P([O-])([O-])OC[C@H]1OC(O)[C@H](O)[C@@H]1O', 'source': 'Primary Database'}

In [15]:
# Create mapping from BiGG, KEGG, Name, etc.
bigg_to_seed = {}

for c in compounds:
    seed_id = c["id"]
    aliases = c.get("aliases") or []
    for entry in aliases:
        entry = str(entry).strip()
        if entry.startswith(("BiGG:", "KEGG:", "Name:")):
            ids = entry.split(":", 1)[1]
            for alias in ids.split(";"):
                alias = alias.strip().lower()
                if alias:
                    if alias not in bigg_to_seed:
                        bigg_to_seed[alias] = seed_id

In [16]:
print(bigg_to_seed.get("h2o"))      # could give cpd00001 if present
print(bigg_to_seed.get("nad"))    # check compartmented version
print(bigg_to_seed.get("fe2"))    # check name alias
print(bigg_to_seed.get(""))   # check KEGG.get("h2o_c"))  # should return 'cpd00001'

cpd00001
cpd00003
cpd10515
None

In [ ]:
def base_met(m):
    return m.rsplit("_",1)[0]

lexicon = []

for m in cobra_model.metabolites:

    base = base_met(m.id)

    seed_id = bigg_to_seed.get(base)

    lexicon.append((m.id, seed_id))

In [ ]:
import pandas as pd

lexicon = pd.DataFrame(
    lexicon,
    columns=["metabolite_id","seed_id"]
)

In [ ]:
mapped = lexicon.seed_id.notna().sum()

print("coverage:", mapped/len(lexicon))

coverage: 0.6944444444444444

In [ ]:
lexicon[lexicon.seed_id.notna()].head(50)

   metabolite_id   seed_id
0        gam6p_c  cpd00288
1         cgly_c  cpd01017
2        achms_c  cpd03399
5          fdp_c  cpd19036
6        5caiz_c  cpd11310
7          pep_c  cpd00061
8          coa_c  cpd00010
9        hgbam_c  cpd03913
10         nac_c  cpd00218
11      r3mmal_c  cpd03593
13       ahcys_c  cpd00019
17         h2s_c  cpd24697
18        orot_c  cpd00247
19         g1p_c  cpd00089
21         na1_c  cpd16174
22      2pglyc_c  cpd00727
24      glyc3p_c  cpd00080
29       trdox_c  cpd27735
33        dutp_c  cpd00358
34        paps_c  cpd00044
35         mg2_c  cpd00254
37          o2_c  cpd00007
38        anth_c  cpd00093
39        dhpt_c  cpd00683
41         fmn_c  cpd00050
42        pppi_c  cpd00421
43         udp_c  cpd00014
44         cit_c  cpd00137
46        uama_c  cpd00890
47       eig3p_c  cpd02843
48      3c4mop_c  cpd02605
50       13dpg_c  cpd00203
51         gmp_c  cpd00126
52         utp_c  cpd00062
53       trdrd_c  cpd28060
54         so4_c  cpd00048
55       5apru_c  cpd00931
56      hmppp9_c  cpd08629
57      pydx5p_c  cpd00016
58        2dhp_c  cpd00712
59         ade_c  cpd00128
61    2sephchc_c  cpd16335
62       acg5p_c  cpd02552
63         gdp_c  cpd00031
64       hgbyr_c  cpd03832
68        dttp_c  cpd00357
69        6pgc_c  cpd00284
70       gcald_c  cpd00229
71     2p4c2me_c  cpd08288
72         cmp_c  cpd00046

In [ ]:
lexicon.to_csv("lexicon_20260308.csv", sep="\t", index=False)

## Precompiled database

In [ ]:
seed_db = {c["id"]: c for c in compounds}
seed_db["cpd00001"]

{'abbreviation': 'h2o',
 'abstract_compound': None,
 'aliases': ['Name: H20; H2O; H3O+; HO-; Hydroxide ion; OH; OH-; Water; hydrogen oxide; hydroxide; hydroxide ion; hydroxyl; hydroxyl ion; oxonium; water',
  'AraCyc: OH; WATER',
  'BiGG: h2o; oh1',
  'BrachyCyc: WATER',
  'KEGG: C00001; C01328',
  'MetaCyc: OH; OXONIUM; WATER'],
 'charge': 0,
 'comprised_of': None,
 'deltag': -37.54,
 'deltagerr': 0.18,
 'formula': 'H2O',
 'id': 'cpd00001',
 'inchikey': 'XLYOFNOQVPJJNP-UHFFFAOYSA-N',
 'is_cofactor': 0,
 'is_core': 1,
 'is_obsolete': 0,
 'linked_compound': None,
 'mass': 18.0,
 'name': 'H2O',
 'notes': ['GC', 'EQ', 'EQU'],
 'pka': '1:1:15.70',
 'pkb': '1:1:-1.80',
 'smiles': 'O',
 'source': 'Primary Database'}

In [ ]:
thermo_mets = []

for _, row in lexicon.iterrows():

    met_id = row["metabolite_id"]
    seed_id = row["seed_id"]

    if pd.isna(seed_id):
        continue

    c = seed_db.get(seed_id)

    if c is None:
        continue

    thermo_mets.append({
        "metabolite_id": met_id,
        "seed_id": seed_id,
        "dGf": c.get("deltag"),
        "dGf_err": c.get("deltagerr"),
        "formula": c.get("formula"),
        "charge": c.get("charge"),
        "pka": c.get("pka"),
        "pkb": c.get("pkb")
    })

In [ ]:
thermo_mets = pd.DataFrame(thermo_mets)

In [ ]:
print(len(thermo_mets))
print(len(cobra_model_mat.metabolites))

1475
2128

In [ ]:
thermo_mets = thermo_mets[thermo_mets["dGf"].notna()]

In [ ]:
import json

met_list = []

for _, row in thermo_mets.iterrows():

    met_id = row["metabolite_id"]

    met_list.append({
        "id": met_id,
        "name": cobra_model_mat.metabolites.get_by_id(met_id).name,
        "compartment": met_id.split("_")[-1],
        "charge": int(row["charge"]) if row["charge"] is not None else None,
        "formula": row["formula"]
    })

thermo_json = {"metabolites": met_list}

with open("thermo_metabolites.json","w") as f:
    json.dump(thermo_json, f, indent=2)

# *Save xml cobra model to json

In [17]:
from cobra.io import read_sbml_model, save_json_model

cobra_model = read_sbml_model(PHB_MODEL_DIR / "02_model_rpalustris_PHB_constrained.xml")

save_json_model(cobra_model, PHB_MODEL_DIR / "02_model_rpalustris_PHB_constrained.json")

In [18]:
cobra_model = load_json_model(
    PHB_MODEL_DIR / "02_model_rpalustris_PHB_constrained.json"
)

In [ ]:
import pandas as pd

lexicon_path = PHB_MODEL_TFA_DIR / "lexicon_iDT1294.csv"# "lexicon_20260308.csv"

# Read CSV properly
lexicon = pd.read_csv(
    lexicon_path,
    sep="\t",        # tab-separated file
    header=None,     # no header in the file
    skiprows=0       # skip extra header row if present, otherwise 0
)

# Rename columns
lexicon.columns = ["metabolite_id", "seed_id"]

# Replace missing seed_id with NaN
lexicon["seed_id"] = lexicon["seed_id"].replace("", pd.NA)

# Save a fixed version
lexicon.to_csv(PHB_MODEL_TFA_DIR / "lexicon_fixed.csv", index=False)

# Check
print(lexicon.head())
print(lexicon.columns)

In [ ]:
lexicon_path = PHB_MODEL_TFA_DIR / "lexicon_iDT1294.csv" # "lexicon_20260308.csv"
lexicon = pd.read_csv(lexicon_path)
lexicon.rename(columns={"metabolite_id": "met_id"}, inplace=True)
lexicon.head()

    Unnamed: 0     seed_id
0  3hbcoa__R_c    cpd00842
1     3hbcoa_c  cpd03043
2    3hbycoa_c    cpd00842
3      aacoa_c    cpd00279
4         ac_c    cpd00029

In [ ]:
compartment_data = read_compartment_data(
    str(PHB_MODEL_TFA_DIR / "compartment_data.json")
)

In [ ]:
thermo_data = load_thermoDB(PHB_MODEL_TFA_DIR / "thermo_data.thermodb")  # if loaded correctly, this should be a ThermoData
# but if you used json.load(), then thermo_data is a dict

In [ ]:
thermo_data['metabolites'].keys()

dict_keys([np.str_('cpd00805'), np.str_('cpd11364'), np.str_('cpd18424'), np.str_('cpd17488'), np.str_('cpd03902'), np.str_('cpd14767'), np.str_('cpd05076'), np.str_('cpd00475'), np.str_('cpd17550'), np.str_('cpd08432'), np.str_('cpd07669'), np.str_('cpd02398'), np.str_('cpd19498'), np.str_('cpd01442'), np.str_('cpd11437'), np.str_('cpd00087'), np.str_('cpd11395'), np.str_('cpd04959'), np.str_('cpd15625'), np.str_('cpd18361'), np.str_('cpd06546'), np.str_('cpd00372'), np.str_('cpd18691'), np.str_('cpd19841'), np.str_('cpd00872'), np.str_('cpd17787'), np.str_('cpd19729'), np.str_('cpd00304'), np.str_('cpd14524'), np.str_('cpd10597'), np.str_('cpd14588'), np.str_('cpd01231'), np.str_('cpd04691'), np.str_('cpd00111'), np.str_('cpd04068'), np.str_('cpd09476'), np.str_('cpd11126'), np.str_('cpd16375'), np.str_('cpd15649'), np.str_('cpd09999'), np.str_('cpd03405'), np.str_('cpd09059'), np.str_('cpd18413'), np.str_('cpd01057'), np.str_('cpd19453'), np.str_('cpd19201'), np.str_('cpd08677'), np.str_('cpd12309'), np.str_('cpd16152'), np.str_('cpd10577'), np.str_('cpd03314'), np.str_('cpd06273'), np.str_('cpd12213'), np.str_('cpd07931'), np.str_('cpd02409'), np.str_('cpd00542'), np.str_('cpd01389'), np.str_('cpd02322'), np.str_('cpd03481'), np.str_('cpd12243'), np.str_('cpd09124'), np.str_('cpd12572'), np.str_('cpd04888'), np.str_('cpd01221'), np.str_('cpd10369'), np.str_('cpd15423'), np.str_('cpd02901'), np.str_('cpd03043'), np.str_('cpd07770'), np.str_('cpd01306'), np.str_('cpd02020'), np.str_('cpd19165'), np.str_('cpd09816'), np.str_('cpd14564'), np.str_('cpd18260'), np.str_('cpd07302'), np.str_('cpd01778'), np.str_('cpd03354'), np.str_('cpd16530'), np.str_('cpd08525'), np.str_('cpd09445'), np.str_('cpd04738'), np.str_('cpd05001'), np.str_('cpd07527'), np.str_('cpd01878'), np.str_('cpd07481'), np.str_('cpd10418'), np.str_('cpd17153'), np.str_('cpd01800'), np.str_('cpd10677'), np.str_('cpd15032'), np.str_('cpd12506'), np.str_('cpd05171'), np.str_('cpd08837'), np.str_('cpd05627'), np.str_('cpd19693'), np.str_('cpd02114'), np.str_('cpd09201'), np.str_('cpd18661'), np.str_('cpd01844'), np.str_('cpd02235'), np.str_('cpd06023'), np.str_('cpd01195'), np.str_('cpd05406'), np.str_('cpd19208'), np.str_('cpd02259'), np.str_('cpd06284'), np.str_('cpd19817'), np.str_('cpd19337'), np.str_('cpd15360'), np.str_('cpd01978'), np.str_('cpd19199'), np.str_('cpd13416'), np.str_('cpd19625'), np.str_('cpd04726'), np.str_('cpd18487'), np.str_('cpd19186'), np.str_('cpd06312'), np.str_('cpd12613'), np.str_('cpd18968'), np.str_('cpd07254'), np.str_('cpd10600'), np.str_('cpd00023'), np.str_('cpd09017'), np.str_('cpd19608'), np.str_('cpd14447'), np.str_('cpd08973'), np.str_('cpd09339'), np.str_('cpd16770'), np.str_('cpd18930'), np.str_('cpd09414'), np.str_('cpd02942'), np.str_('cpd10785'), np.str_('cpd07423'), np.str_('cpd06083'), np.str_('cpd08660'), np.str_('cpd00633'), np.str_('cpd06370'), np.str_('cpd00483'), np.str_('cpd05132'), np.str_('cpd04896'), np.str_('cpd02041'), np.str_('cpd04598'), np.str_('cpd16797'), np.str_('cpd17364'), np.str_('cpd05174'), np.str_('cpd12319'), np.str_('cpd06868'), np.str_('cpd16113'), np.str_('cpd09023'), np.str_('cpd01826'), np.str_('cpd12202'), np.str_('cpd01635'), np.str_('cpd12347'), np.str_('cpd00004'), np.str_('cpd00897'), np.str_('cpd18939'), np.str_('cpd16608'), np.str_('cpd16988'), np.str_('cpd01329'), np.str_('cpd19371'), np.str_('cpd14769'), np.str_('cpd01250'), np.str_('cpd18176'), np.str_('cpd01331'), np.str_('cpd07974'), np.str_('cpd02915'), np.str_('cpd16133'), np.str_('cpd01020'), np.str_('cpd01059'), np.str_('cpd08133'), np.str_('cpd11675'), np.str_('cpd15220'), np.str_('cpd00053'), np.str_('cpd10016'), np.str_('cpd14479'), np.str_('cpd05393'), np.str_('cpd04640'), np.str_('cpd10906'), np.str_('cpd03824'), np.str_('cpd11930'), np.str_('cpd15427'), np.str_('cpd01062'), np.str_('cpd08227'), np.str_('cpd12568'), np.str_('cpd19296'), np.str_('cpd06020'), np.str_('cpd09759'), np.str_('cpd07871'), np.str_('cpd04205'), np.str_('cpd18111'), np.str_('cpd06350'), np.str_('cpd02722'), np.str_('cpd04755'), np.str_('cpd16651'), np.str_('cpd04171'), np.str_('cpd08984'), np.str_('cpd09408'), np.str_('cpd06757'), np.str_('cpd05530'), np.str_('cpd05386'), np.str_('cpd11799'), np.str_('cpd09442'), np.str_('cpd06118'), np.str_('cpd17981'), np.str_('cpd05140'), np.str_('cpd19428'), np.str_('cpd06891'), np.str_('cpd16296'), np.str_('cpd16598'), np.str_('cpd03804'), np.str_('cpd16356'), np.str_('cpd02327'), np.str_('cpd03908'), np.str_('cpd16487'), np.str_('cpd18166'), np.str_('cpd01614'), np.str_('cpd01959'), np.str_('cpd00320'), np.str_('cpd08998'), np.str_('cpd03461'), np.str_('cpd02101'), np.str_('cpd00909'), np.str_('cpd04329'), np.str_('cpd18857'), np.str_('cpd17388'), np.str_('cpd04975'), np.str_('cpd17817'), np.str_('cpd04793'), np.str_('cpd13345'), np.str_('cpd08689'), np.str_('cpd18607'), np.str_('cpd19889'), np.str_('cpd05047'), np.str_('cpd18038'), np.str_('cpd18809'), np.str_('cpd18090'), np.str_('cpd05415'), np.str_('cpd18498'), np.str_('cpd05211'), np.str_('cpd16839'), np.str_('cpd15897'), np.str_('cpd18865'), np.str_('cpd12407'), np.str_('cpd09485'), np.str_('cpd11452'), np.str_('cpd15453'), np.str_('cpd00027'), np.str_('cpd08428'), np.str_('cpd12507'), np.str_('cpd17839'), np.str_('cpd16590'), np.str_('cpd09794'), np.str_('cpd06898'), np.str_('cpd02623'), np.str_('cpd07346'), np.str_('cpd19287'), np.str_('cpd17449'), np.str_('cpd18913'), np.str_('cpd14544'), np.str_('cpd00415'), np.str_('cpd10818'), np.str_('cpd03821'), np.str_('cpd09704'), np.str_('cpd04133'), np.str_('cpd11827'), np.str_('cpd01360'), np.str_('cpd08135'), np.str_('cpd19041'), np.str_('cpd02508'), np.str_('cpd01697'), np.str_('cpd11506'), np.str_('cpd19811'), np.str_('cpd01392'), np.str_('cpd17029'), np.str_('cpd03770'), np.str_('cpd04593'), np.str_('cpd01529'), np.str_('cpd17229'), np.str_('cpd01181'), np.str_('cpd14822'), np.str_('cpd19364'), np.str_('cpd19183'), np.str_('cpd10848'), np.str_('cpd08248'), np.str_('cpd06824'), np.str_('cpd01744'), np.str_('cpd10770'), np.str_('cpd06419'), np.str_('cpd01348'), np.str_('cpd19456'), np.str_('cpd02044'), np.str_('cpd04081'), np.str_('cpd00565'), np.str_('cpd15879'), np.str_('cpd09375'), np.str_('cpd09850'), np.str_('cpd15219'), np.str_('cpd08113'), np.str_('cpd10599'), np.str_('cpd14990'), np.str_('cpd00408'), np.str_('cpd02629'), np.str_('cpd03839'), np.str_('cpd10510'), np.str_('cpd06622'), np.str_('cpd17983'), np.str_('cpd16478'), np.str_('cpd16902'), np.str_('cpd19175'), np.str_('cpd05981'), np.str_('cpd02861'), np.str_('cpd15511'), np.str_('cpd06486'), np.str_('cpd09542'), np.str_('cpd05794'), np.str_('cpd05020'), np.str_('cpd15329'), np.str_('cpd03832'), np.str_('cpd00322'), np.str_('cpd12108'), np.str_('cpd00928'), np.str_('cpd06088'), np.str_('cpd06237'), np.str_('cpd18051'), np.str_('cpd09957'), np.str_('cpd01453'), np.str_('cpd10443'), np.str_('cpd18024'), np.str_('cpd01440'), np.str_('cpd17320'), np.str_('cpd04212'), np.str_('cpd06722'), np.str_('cpd03792'), np.str_('cpd08797'), np.str_('cpd12694'), np.str_('cpd00268'), np.str_('cpd16586'), np.str_('cpd11349'), np.str_('cpd04340'), np.str_('cpd08129'), np.str_('cpd06771'), np.str_('cpd02022'), np.str_('cpd09145'), np.str_('cpd11101'), np.str_('cpd16043'), np.str_('cpd03838'), np.str_('cpd00614'), np.str_('cpd15432'), np.str_('cpd11158'), np.str_('cpd19747'), np.str_('cpd14910'), np.str_('cpd06094'), np.str_('cpd02647'), np.str_('cpd11301'), np.str_('cpd13267'), np.str_('cpd00176'), np.str_('cpd03473'), np.str_('cpd18632'), np.str_('cpd07047'), np.str_('cpd12732'), np.str_('cpd01811'), np.str_('cpd18631'), np.str_('cpd03390'), np.str_('cpd07906'), np.str_('cpd12489'), np.str_('cpd10112'), np.str_('cpd07163'), np.str_('cpd04671'), np.str_('cpd10687'), np.str_('cpd10426'), np.str_('cpd19431'), np.str_('cpd05389'), np.str_('cpd09520'), np.str_('cpd09743'), np.str_('cpd15300'), np.str_('cpd00391'), np.str_('cpd01642'), np.str_('cpd06304'), np.str_('cpd08459'), np.str_('cpd16201'), np.str_('cpd17678'), np.str_('cpd18275'), np.str_('cpd12355'), np.str_('cpd06882'), np.str_('cpd10912'), np.str_('cpd10846'), np.str_('cpd06918'), np.str_('cpd07594'), np.str_('cpd00429'), np.str_('cpd18555'), np.str_('cpd08838'), np.str_('cpd11932'), np.str_('cpd11917'), np.str_('cpd14671'), np.str_('cpd19424'), np.str_('cpd19857'), np.str_('cpd06360'), np.str_('cpd07812'), np.str_('cpd07166'), np.str_('cpd01232'), np.str_('cpd00838'), np.str_('cpd15078'), np.str_('cpd06740'), np.str_('cpd00640'), np.str_('cpd11676'), np.str_('cpd01517'), np.str_('cpd02968'), np.str_('cpd12688'), np.str_('cpd11332'), np.str_('cpd11531'), np.str_('cpd17389'), np.str_('cpd10880'), np.str_('cpd05286'), np.str_('cpd02238'), np.str_('cpd03775'), np.str_('cpd10066'), np.str_('cpd18861'), np.str_('cpd15314'), np.str_('cpd05928'), np.str_('cpd02479'), np.str_('cpd18197'), np.str_('cpd16645'), np.str_('cpd14968'), np.str_('cpd19410'), np.str_('cpd08641'), np.str_('cpd09885'), np.str_('cpd06330'), np.str_('cpd11525'), np.str_('cpd19047'), np.str_('cpd07444'), np.str_('cpd00045'), np.str_('cpd16300'), np.str_('cpd11260'), np.str_('cpd15895'), np.str_('cpd16292'), np.str_('cpd11801'), np.str_('cpd05367'), np.str_('cpd09693'), np.str_('cpd07837'), np.str_('cpd11422'), np.str_('cpd19145'), np.str_('cpd11597'), np.str_('cpd18391'), np.str_('cpd07946'), np.str_('cpd13953'), np.str_('cpd01373'), np.str_('cpd16418'), np.str_('cpd17524'), np.str_('cpd02609'), np.str_('cpd18352'), np.str_('cpd08098'), np.str_('cpd11055'), np.str_('cpd11661'), np.str_('cpd00201'), np.str_('cpd17196'), np.str_('cpd11120'), np.str_('cpd00432'), np.str_('cpd13379'), np.str_('cpd05207'), np.str_('cpd04062'), np.str_('cpd00710'), np.str_('cpd16953'), np.str_('cpd08313'), np.str_('cpd14787'), np.str_('cpd00664'), np.str_('cpd04601'), np.str_('cpd17752'), np.str_('cpd18083'), np.str_('cpd18713'), np.str_('cpd15116'), np.str_('cpd15551'), np.str_('cpd11540'), np.str_('cpd07304'), np.str_('cpd14532'), np.str_('cpd01856'), np.str_('cpd00096'), np.str_('cpd14490'), np.str_('cpd17083'), np.str_('cpd00190'), np.str_('cpd17392'), np.str_('cpd15850'), np.str_('cpd06126'), np.str_('cpd07894'), np.str_('cpd15251'), np.str_('cpd00143'), np.str_('cpd09669'), np.str_('cpd16689'), np.str_('cpd14576'), np.str_('cpd12105'), np.str_('cpd00356'), np.str_('cpd16017'), np.str_('cpd03379'), np.str_('cpd09778'), np.str_('cpd12698'), np.str_('cpd11501'), np.str_('cpd01296'), np.str_('cpd10101'), np.str_('cpd01188'), np.str_('cpd08339'), np.str_('cpd07532'), np.str_('cpd07445'), np.str_('cpd01182'), np.str_('cpd16429'), np.str_('cpd09505'), np.str_('cpd16551'), np.str_('cpd01147'), np.str_('cpd03123'), np.str_('cpd06792'), np.str_('cpd02975'), np.str_('cpd19158'), np.str_('cpd10394'), np.str_('cpd04056'), np.str_('cpd12890'), np.str_('cpd14522'), np.str_('cpd07738'), np.str_('cpd03310'), np.str_('cpd07119'), np.str_('cpd18840'), np.str_('cpd19210'), np.str_('cpd04011'), np.str_('cpd16079'), np.str_('cpd07497'), np.str_('cpd11405'), np.str_('cpd12233'), np.str_('cpd02499'), np.str_('cpd18122'), np.str_('cpd17674'), np.str_('cpd07168'), np.str_('cpd04674'), np.str_('cpd09062'), np.str_('cpd03166'), np.str_('cpd02225'), np.str_('cpd07208'), np.str_('cpd08906'), np.str_('cpd15835'), np.str_('cpd15127'), np.str_('cpd15386'), np.str_('cpd03860'), np.str_('cpd19529'), np.str_('cpd02735'), np.str_('cpd12401'), np.str_('cpd08668'), np.str_('cpd03812'), np.str_('cpd06369'), np.str_('cpd03666'), np.str_('cpd10103'), np.str_('cpd17502'), np.str_('cpd06721'), np.str_('cpd05321'), np.str_('cpd16931'), np.str_('cpd07816'), np.str_('cpd09083'), np.str_('cpd06064'), np.str_('cpd09406'), np.str_('cpd03075'), np.str_('cpd14648'), np.str_('cpd03403'), np.str_('cpd08752'), np.str_('cpd17576'), np.str_('cpd06657'), np.str_('cpd07252'), np.str_('cpd03600'), np.str_('cpd08415'), np.str_('cpd19692'), np.str_('cpd15585'), np.str_('cpd04613'), np.str_('cpd02354'), np.str_('cpd18238'), np.str_('cpd00269'), np.str_('cpd02166'), np.str_('cpd04273'), np.str_('cpd01134'), np.str_('cpd08121'), np.str_('cpd19228'), np.str_('cpd12778'), np.str_('cpd03756'), np.str_('cpd19595'), np.str_('cpd10856'), np.str_('cpd18453'), np.str_('cpd00507'), np.str_('cpd06693'), np.str_('cpd19044'), np.str_('cpd04786'), np.str_('cpd11226'), np.str_('cpd05577'), np.str_('cpd00301'), np.str_('cpd00737'), np.str_('cpd19512'), np.str_('cpd18330'), np.str_('cpd19191'), np.str_('cpd04194'), np.str_('cpd07483'), np.str_('cpd11271'), np.str_('cpd09930'), np.str_('cpd12901'), np.str_('cpd15530'), np.str_('cpd15910'), np.str_('cpd14991'), np.str_('cpd08368'), np.str_('cpd11456'), np.str_('cpd04689'), np.str_('cpd00272'), np.str_('cpd11992'), np.str_('cpd03617'), np.str_('cpd06421'), np.str_('cpd03041'), np.str_('cpd02636'), np.str_('cpd09448'), np.str_('cpd16925'), np.str_('cpd11877'), np.str_('cpd02031'), np.str_('cpd10180'), np.str_('cpd04860'), np.str_('cpd12021'), np.str_('cpd11455'), np.str_('cpd02385'), np.str_('cpd04059'), np.str_('cpd08959'), np.str_('cpd12251'), np.str_('cpd15977'), np.str_('cpd09474'), np.str_('cpd06505'), np.str_('cpd07883'), np.str_('cpd05194'), np.str_('cpd02133'), np.str_('cpd00100'), np.str_('cpd09508'), np.str_('cpd08162'), np.str_('cpd19440'), np.str_('cpd00434'), np.str_('cpd05218'), np.str_('cpd03217'), np.str_('cpd03826'), np.str_('cpd11641'), np.str_('cpd17501'), np.str_('cpd06883'), np.str_('cpd03231'), np.str_('cpd06555'), np.str_('cpd02842'), np.str_('cpd09200'), np.str_('cpd19924'), np.str_('cpd16646'), np.str_('cpd02305'), np.str_('cpd08947'), np.str_('cpd06763'), np.str_('cpd04104'), np.str_('cpd05004'), np.str_('cpd04587'), np.str_('cpd19784'), np.str_('cpd14891'), np.str_('cpd18685'), np.str_('cpd15733'), np.str_('cpd01650'), np.str_('cpd10362'), np.str_('cpd16842'), np.str_('cpd09216'), np.str_('cpd16067'), np.str_('cpd06216'), np.str_('cpd04235'), np.str_('cpd06296'), np.str_('cpd01291'), np.str_('cpd17629'), np.str_('cpd05433'), np.str_('cpd07568'), np.str_('cpd09617'), np.str_('cpd18455'), np.str_('cpd16911'), np.str_('cpd00312'), np.str_('cpd08527'), np.str_('cpd02789'), np.str_('cpd05540'), np.str_('cpd09737'), np.str_('cpd14832'), np.str_('cpd07130'), np.str_('cpd10760'), np.str_('cpd17782'), np.str_('cpd03866'), np.str_('cpd05305'), np.str_('cpd11651'), np.str_('cpd04324'), np.str_('cpd09314'), np.str_('cpd09613'), np.str_('cpd15484'), np.str_('cpd17408'), np.str_('cpd01876'), np.str_('cpd00511'), np.str_('cpd17009'), np.str_('cpd03893'), np.str_('cpd16604'), np.str_('cpd16492'), np.str_('cpd03377'), np.str_('cpd05022'), np.str_('cpd07574'), np.str_('cpd04799'), np.str_('cpd03878'), np.str_('cpd03258'), np.str_('cpd05299'), np.str_('cpd06306'), np.str_('cpd18843'), np.str_('cpd02540'), np.str_('cpd16390'), np.str_('cpd08482'), np.str_('cpd05796'), np.str_('cpd17070'), np.str_('cpd11738'), np.str_('cpd03664'), np.str_('cpd18626'), np.str_('cpd03248'), np.str_('cpd11137'), np.str_('cpd10484'), np.str_('cpd03072'), np.str_('cpd06823'), np.str_('cpd18284'), np.str_('cpd07301'), np.str_('cpd02791'), np.str_('cpd00858'), np.str_('cpd04988'), np.str_('cpd03489'), np.str_('cpd14663'), np.str_('cpd18758'), np.str_('cpd11056'), np.str_('cpd12727'), np.str_('cpd06129'), np.str_('cpd01620'), np.str_('cpd09753'), np.str_('cpd01652'), np.str_('cpd11808'), np.str_('cpd00351'), np.str_('cpd00306'), np.str_('cpd16574'), np.str_('cpd12197'), np.str_('cpd02951'), np.str_('cpd15270'), np.str_('cpd06542'), np.str_('cpd07545'), np.str_('cpd02721'), np.str_('cpd07309'), np.str_('cpd07516'), np.str_('cpd12306'), np.str_('cpd14771'), np.str_('cpd18904'), np.str_('cpd09122'), np.str_('cpd06677'), np.str_('cpd17635'), np.str_('cpd17973'), np.str_('cpd17075'), np.str_('cpd16591'), np.str_('cpd18000'), np.str_('cpd15960'), np.str_('cpd12446'), np.str_('cpd01374'), np.str_('cpd00715'), np.str_('cpd07111'), np.str_('cpd07485'), np.str_('cpd06916'), np.str_('cpd05865'), np.str_('cpd02033'), np.str_('cpd04647'), np.str_('cpd06988'), np.str_('cpd19567'), np.str_('cpd03781'), np.str_('cpd03713'), np.str_('cpd12716'), np.str_('cpd15290'), np.str_('cpd02736'), np.str_('cpd02576'), np.str_('cpd01153'), np.str_('cpd04972'), np.str_('cpd18136'), np.str_('cpd03675'), np.str_('cpd18293'), np.str_('cpd07370'), np.str_('cpd18745'), np.str_('cpd05250'), np.str_('cpd19860'), np.str_('cpd17332'), np.str_('cpd02621'), np.str_('cpd07278'), np.str_('cpd12455'), np.str_('cpd10134'), np.str_('cpd03198'), np.str_('cpd19698'), np.str_('cpd04140'), np.str_('cpd12479'), np.str_('cpd04951'), np.str_('cpd02991'), np.str_('cpd09973'), np.str_('cpd11593'), np.str_('cpd02507'), np.str_('cpd17181'), np.str_('cpd14875'), np.str_('cpd06815'), np.str_('cpd18301'), np.str_('cpd09697'), np.str_('cpd10765'), np.str_('cpd07741'), np.str_('cpd10626'), np.str_('cpd19690'), np.str_('cpd16661'), np.str_('cpd11074'), np.str_('cpd16607'), np.str_('cpd09927'), np.str_('cpd19598'), np.str_('cpd06774'), np.str_('cpd19586'), np.str_('cpd03395'), np.str_('cpd04447'), np.str_('cpd02914'), np.str_('cpd05173'), np.str_('cpd08390'), np.str_('cpd02919'), np.str_('cpd04185'), np.str_('cpd12540'), np.str_('cpd07373'), np.str_('cpd15195'), np.str_('cpd13050'), np.str_('cpd17802'), np.str_('cpd09990'), np.str_('cpd02040'), np.str_('cpd01302'), np.str_('cpd06021'), np.str_('cpd02881'), np.str_('cpd16952'), np.str_('cpd02131'), np.str_('cpd03928'), np.str_('cpd04007'), np.str_('cpd19154'), np.str_('cpd06202'), np.str_('cpd12640'), np.str_('cpd14790'), np.str_('cpd02581'), np.str_('cpd08025'), np.str_('cpd19366'), np.str_('cpd03400'), np.str_('cpd05974'), np.str_('cpd11229'), np.str_('cpd16342'), np.str_('cpd08166'), np.str_('cpd12320'), np.str_('cpd05460'), np.str_('cpd18170'), np.str_('cpd10099'), np.str_('cpd02472'), np.str_('cpd15280'), np.str_('cpd03344'), np.str_('cpd16666'), np.str_('cpd09439'), np.str_('cpd14640'), np.str_('cpd08353'), np.str_('cpd06791'), np.str_('cpd03186'), np.str_('cpd12215'), np.str_('cpd04501'), np.str_('cpd19033'), np.str_('cpd02741'), np.str_('cpd17452'), np.str_('cpd10660'), np.str_('cpd10130'), np.str_('cpd16118'), np.str_('cpd11291'), np.str_('cpd15643'), np.str_('cpd00070'), np.str_('cpd19125'), np.str_('cpd09452'), np.str_('cpd02355'), np.str_('cpd18266'), np.str_('cpd10515'), np.str_('cpd16410'), np.str_('cpd18718'), np.str_('cpd09393'), np.str_('cpd15376'), np.str_('cpd05192'), np.str_('cpd03435'), np.str_('cpd00231'), np.str_('cpd16380'), np.str_('cpd19542'), np.str_('cpd01699'), np.str_('cpd02803'), np.str_('cpd19127'), np.str_('cpd03195'), np.str_('cpd01236'), np.str_('cpd01966'), np.str_('cpd16875'), np.str_('cpd13420'), np.str_('cpd17916'), np.str_('cpd01818'), np.str_('cpd14594'), np.str_('cpd12055'), np.str_('cpd01451'), np.str_('cpd02261'), np.str_('cpd12648'), np.str_('cpd09653'), np.str_('cpd19198'), np.str_('cpd00826'), np.str_('cpd03056'), np.str_('cpd01345'), np.str_('cpd16528'), np.str_('cpd15671'), np.str_('cpd19214'), np.str_('cpd07387'), np.str_('cpd18887'), np.str_('cpd19831'), np.str_('cpd15707'), np.str_('cpd10547'), np.str_('cpd11251'), np.str_('cpd19674'), np.str_('cpd11952'), np.str_('cpd07901'), np.str_('cpd09001'), np.str_('cpd17669'), np.str_('cpd12229'), np.str_('cpd05683'), np.str_('cpd10795'), np.str_('cpd03128'), np.str_('cpd05739'), np.str_('cpd14568'), np.str_('cpd04915'), np.str_('cpd15603'), np.str_('cpd11090'), np.str_('cpd07137'), np.str_('cpd01971'), np.str_('cpd03863'), np.str_('cpd08825'), np.str_('cpd01367'), np.str_('cpd03260'), np.str_('cpd08726'), np.str_('cpd05646'), np.str_('cpd10322'), np.str_('cpd00671'), np.str_('cpd08553'), np.str_('cpd04719'), np.str_('cpd07734'), np.str_('cpd15629'), np.str_('cpd04228'), np.str_('cpd08564'), np.str_('cpd02628'), np.str_('cpd10672'), np.str_('cpd15762'), np.str_('cpd00160'), np.str_('cpd05307'), np.str_('cpd00170'), np.str_('cpd19340'), np.str_('cpd03702'), np.str_('cpd15302'), np.str_('cpd03288'), np.str_('cpd11165'), np.str_('cpd02169'), np.str_('cpd07283'), np.str_('cpd14946'), np.str_('cpd15035'), np.str_('cpd19487'

In [ ]:
from pytfa.io import load_thermoDB
from pathlib import Path
import pandas as pd

# --- 1️⃣ Load thermoDB ---
thermo_data = load_thermoDB(PHB_MODEL_TFA_DIR / "thermo_data.thermodb")


# --- 2️⃣ Load lexicon & compartment data ---
lexicon = read_lexicon(PHB_MODEL_TFA_DIR / "lexicon_fixed.csv")
compartment_data = read_compartment_data(
    str(PHB_MODEL_TFA_DIR / "compartment_data.json")
)

# Lexicon seed IDs as Python strings
lexicon_seed_ids = set(map(str, lexicon['seed_id'].dropna()))

# Thermo seed IDs as Python strings
thermo_seed_ids = set(map(str, thermo_data['metabolites'].keys()))

present_in_thermo = lexicon_seed_ids & thermo_seed_ids
missing_in_thermo = lexicon_seed_ids - thermo_seed_ids

print(f"Seed IDs present in thermo_data: {present_in_thermo}")
print(f"Seed IDs missing in thermo_data: {missing_in_thermo}")

Seed IDs present in thermo_data: {'cpd15432', 'cpd00054', 'cpd15325', 'cpd15660', 'cpd16747', 'cpd00044', 'cpd00086', 'cpd15349', 'cpd16750', 'cpd00235', 'cpd00032', 'cpd12255', 'cpd15277', 'cpd01262', 'cpd01977', 'cpd12228', 'cpd03584', 'cpd01113', 'cpd00261', 'cpd00209', 'cpd00342', 'cpd15421', 'cpd15551', 'cpd15307', 'cpd08405', 'cpd03122', 'cpd00403', 'cpd03671', 'cpd00875', 'cpd01695', 'cpd00277', 'cpd08287', 'cpd11341', 'cpd15399', 'cpd12733', 'cpd00739', 'cpd02724', 'cpd15275', 'cpd02394', 'cpd00207', 'cpd12100', 'cpd15419', 'cpd11255', 'cpd00296', 'cpd15578', 'cpd02484', 'cpd02678', 'cpd15539', 'cpd00484', 'cpd03387', 'cpd00092', 'cpd00355', 'cpd15413', 'cpd00800', 'cpd01844', 'cpd00626', 'cpd01563', 'cpd03704', 'cpd15525', 'cpd00523', 'cpd15341', 'cpd15481', 'cpd01997', 'cpd02345', 'cpd15437', 'cpd00120', 'cpd08305', 'cpd15468', 'cpd03593', 'cpd00309', 'cpd15572', 'cpd15313', 'cpd15529', 'cpd01882', 'cpd00413', 'cpd00266', 'cpd00755', 'cpd03752', 'cpd15422', 'cpd01171', 'cpd00299', 'cpd02494', 'cpd03637', 'cpd15294', 'cpd02041', 'cpd16050', 'cpd00956', 'cpd16754', 'cpd11310', 'cpd00289', 'cpd02182', 'cpd00587', 'cpd15417', 'cpd00241', 'cpd03119', 'cpd00141', 'cpd00016', 'cpd02501', 'cpd00863', 'cpd03306', 'cpd01908', 'cpd15543', 'cpd02666', 'cpd15338', 'cpd00249', 'cpd00282', 'cpd01693', 'cpd00048', 'cpd02979', 'cpd03915', 'cpd02295', 'cpd00533', 'cpd19024', 'cpd15479', 'cpd16753', 'cpd09410', 'cpd11631', 'cpd14905', 'cpd03738', 'cpd15441', 'cpd11490', 'cpd00782', 'cpd00102', 'cpd00039', 'cpd03761', 'cpd03760', 'cpd00731', 'cpd08928', 'cpd05178', 'cpd00393', 'cpd00869', 'cpd11467', 'cpd03426', 'cpd00550', 'cpd03444', 'cpd08626', 'cpd00293', 'cpd03725', 'cpd11480', 'cpd00164', 'cpd11694', 'cpd03494', 'cpd00686', 'cpd00085', 'cpd15351', 'cpd00346', 'cpd12105', 'cpd15499', 'cpd15386', 'cpd16056', 'cpd00327', 'cpd03117', 'cpd03118', 'cpd15395', 'cpd12036', 'cpd00856', 'cpd15484', 'cpd00042', 'cpd02258', 'cpd01901', 'cpd15361', 'cpd00938', 'cpd00930', 'cpd03148', 'cpd00988', 'cpd00163', 'cpd15400', 'cpd02730', 'cpd00215', 'cpd00630', 'cpd02089', 'cpd00900', 'cpd00507', 'cpd00401', 'cpd00417', 'cpd19047', 'cpd00121', 'cpd00638', 'cpd12003', 'cpd00607', 'cpd03919', 'cpd02016', 'cpd15346', 'cpd00227', 'cpd00108', 'cpd15402', 'cpd00450', 'cpd01042', 'cpd00683', 'cpd15249', 'cpd03490', 'cpd11669', 'cpd15489', 'cpd00478', 'cpd00644', 'cpd15540', 'cpd00386', 'cpd03198', 'cpd02943', 'cpd19039', 'cpd00464', 'cpd03327', 'cpd03805', 'cpd15464', 'cpd00292', 'cpd03802', 'cpd08209', 'cpd00830', 'cpd15503', 'cpd00022', 'cpd00034', 'cpd02835', 'cpd15469', 'cpd00139', 'cpd00461', 'cpd00010', 'cpd19035', 'cpd00040', 'cpd00060', 'cpd02090', 'cpd03587', 'cpd15319', 'cpd03914', 'cpd00008', 'cpd16007', 'cpd15574', 'cpd00504', 'cpd00201', 'cpd00659', 'cpd00125', 'cpd11920', 'cpd01914', 'cpd15236', 'cpd12060', 'cpd00338', 'cpd14718', 'cpd00989', 'cpd12689', 'cpd00221', 'cpd00202', 'cpd11770', 'cpd00118', 'cpd00156', 'cpd00145', 'cpd03420', 'cpd00493', 'cpd19032', 'cpd16136', 'cpd02711', 'cpd09253', 'cpd03751', 'cpd11921', 'cpd00155', 'cpd00161', 'cpd00071', 'cpd00129', 'cpd00871', 'cpd11917', 'cpd03724', 'cpd00305', 'cpd01777', 'cpd00069', 'cpd15327', 'cpd00009', 'cpd19012', 'cpd00531', 'cpd00868', 'cpd15318', 'cpd11595', 'cpd19069', 'cpd10516', 'cpd00066', 'cpd03124', 'cpd01919', 'cpd12132', 'cpd02698', 'cpd15329', 'cpd00383', 'cpd02762', 'cpd03608', 'cpd00506', 'cpd00809', 'cpd00378', 'cpd02693', 'cpd00094', 'cpd11911', 'cpd15323', 'cpd15502', 'cpd00802', 'cpd02654', 'cpd00043', 'cpd00149', 'cpd02851', 'cpd00211', 'cpd00026', 'cpd00185', 'cpd00764', 'cpd15553', 'cpd00095', 'cpd03453', 'cpd15320', 'cpd19019', 'cpd00214', 'cpd00428', 'cpd00059', 'cpd19179', 'cpd00168', 'cpd16756', 'cpd00528', 'cpd04089', 'cpd11484', 'cpd15295', 'cpd00902', 'cpd15344', 'cpd00390', 'cpd03696', 'cpd00525', 'cpd12336', 'cpd00134', 'cpd03129', 'cpd00233', 'cpd19031', 'cpd00703', 'cpd15440', 'cpd15414', 'cpd00113', 'cpd00055', 'cpd03809', 'cpd15435', 'cpd02717', 'cpd00588', 'cpd15392', 'cpd00330', 'cpd00132', 'cpd16745', 'cpd00348', 'cpd00003', 'cpd12313', 'cpd01211', 'cpd15541', 'cpd00229', 'cpd02169', 'cpd11906', 'cpd01067', 'cpd11464', 'cpd00797', 'cpd15385', 'cpd00023', 'cpd11472', 'cpd00806', 'cpd03217', 'cpd03591', 'cpd00359', 'cpd00270', 'cpd00037', 'cpd11657', 'cpd03214', 'cpd15406', 'cpd15377', 'cpd02961', 'cpd16740', 'cpd08023', 'cpd15555', 'cpd02333', 'cpd08289', 'cpd00655', 'cpd11295', 'cpd00152', 'cpd15562', 'cpd03445', 'cpd00851', 'cpd15391', 'cpd03913', 'cpd01401', 'cpd08353', 'cpd19018', 'cpd16258', 'cpd02904', 'cpd01747', 'cpd08301', 'cpd00015', 'cpd01264', 'cpd11751', 'cpd00939', 'cpd15513', 'cpd08286', 'cpd10596', 'cpd00697', 'cpd02216', 'cpd15308', 'cpd03049', 'cpd15951', 'cpd00083', 'cpd12285', 'cpd11959', 'cpd00096', 'cpd15339', 'cpd01831', 'cpd00090', 'cpd02893', 'cpd02547', 'cpd19241', 'cpd02738', 'cpd00714', 'cpd01151', 'cpd00932', 'cpd02642', 'cpd00105', 'cpd15359', 'cpd02843', 'cpd03848', 'cpd15350', 'cpd00585', 'cpd00047', 'cpd00027', 'cpd01293', 'cpd11579', 'cpd03116', 'cpd01861', 'cpd00836', 'cpd15423', 'cpd19046', 'cpd00834', 'cpd00288', 'cpd00807', 'cpd00608', 'cpd01711', 'cpd00218', 'cpd12227', 'cpd15459', 'cpd03917', 'cpd00169', 'cpd00051', 'cpd00641', 'cpd00219', 'cpd04100', 'cpd00485', 'cpd19036', 'cpd00138', 'cpd02069', 'cpd15485', 'cpd02661', 'cpd03835', 'cpd02784', 'cpd02978', 'cpd15524', 'cpd00712', 'cpd00100', 'cpd19008', 'cpd15495', 'cpd00080', 'cpd15534', 'cpd00680', 'cpd00759', 'cpd02140', 'cpd00905', 'cpd00518', 'cpd00379', 'cpd02315', 'cpd02701', 'cpd11923', 'cpd00078', 'cpd00135', 'cpd00589', 'cpd00334', 'cpd15457', 'cpd01710', 'cpd00706', 'cpd00251', 'cpd03446', 'cpd00322', 'cpd00107', 'cpd01329', 'cpd01502', 'cpd17076', 'cpd11620', 'cpd00130', 'cpd02113', 'cpd04461', 'cpd11830', 'cpd11640', 'cpd00186', 'cpd16749', 'cpd03606', 'cpd03399', 'cpd15315', 'cpd11477', 'cpd11470', 'cpd08374', 'cpd02555', 'cpd16746', 'cpd00280', 'cpd02201', 'cpd01157', 'cpd00005', 'cpd11494', 'cpd11596', 'cpd00111', 'cpd00258', 'cpd15397', 'cpd00738', 'cpd02820', 'cpd01048', 'cpd00114', 'cpd00193', 'cpd01011', 'cpd00890', 'cpd02775', 'cpd00763', 'cpd00729', 'cpd00075', 'cpd15401', 'cpd03127', 'cpd00854', 'cpd03585', 'cpd00455', 'cpd03126', 'cpd00143', 'cpd00858', 'cpd03032', 'cpd15480', 'cpd03165', 'cpd03577', 'cpd00052', 'cpd15527', 'cpd02656', 'cpd02605', 'cpd02993', 'cpd00200', 'cpd15577', 'cpd00236', 'cpd01015', 'cpd02068', 'cpd04139', 'cpd02507', 'cpd02826', 'cpd12690', 'cpd01775', 'cpd15505', 'cpd16739', 'cpd15298', 'cpd00371', 'cpd00210', 'cpd15328', 'cpd11473', 'cpd12229', 'cpd00011', 'cpd15357', 'cpd00115', 'cpd16267', 'cpd03378', 'cpd00162', 'cpd00774', 'cpd03052', 'cpd00353', 'cpd03846', 'cpd00067', 'cpd00397', 'cpd00532', 'cpd15354', 'cpd00685', 'cpd12005', 'cpd15558', 'cpd03423', 'cpd03121', 'cpd15238', 'cpd15337', 'cpd11479', 'cpd11912', 'cpd12164', 'cpd00308', 'cpd00837', 'cpd00637', 'cpd00345', 'cpd02612', 'cpd00216', 'cpd02857', 'cpd00180', 'cpd11916', 'cpd00945', 'cpd00762', 'cpd00389', 'cpd15309', 'cpd16025', 'cpd00443', 'cpd16026', 'cpd00298', 'cpd11486', 'cpd03128', 'cpd02030', 'cpd03839', 'cpd09878', 'cpd00018', 'cpd00699', 'cpd00977', 'cpd03732', 'cpd12256', 'cpd01507', 'cpd00182', 'cpd00811', 'cpd00031', 'cpd00274', 'cpd00477', 'cpd00482', 'cpd00897', 'cpd00224', 'cpd00540', 'cpd00159', 'cpd00817', 'cpd11493', 'cpd00264', 'cpd15331', 'cpd00002', 'cpd15336', 'cpd15364', 'cpd16266', 'cpd19174', 'cpd00426', 'cpd00434', 'cpd15340', 'cpd00402', 'cpd12133', 'cpd16506', 'cpd16757', 'cpd00137', 'cpd02083', 'cpd02991', 'cpd00728', 'cpd15342', 'cpd02791', 'cpd00248', 'cpd00142', 'cpd00272', 'cpd00847', 'cpd04073', 'cpd00028', 'cpd00306', 'cpd02255', 'cpd00157', 'cpd00794', 'cpd00421', 'cpd15531', 'cpd00014', 'cpd00722', 'cpd11492', 'cpd00510', 'cpd01335', 'cpd00861', 'cpd03443', 'cpd00029', 'cpd02552', 'cpd16262', 'cpd11478', 'cpd09255', 'cpd00356', 'cpd01311', 'cpd00843', 'cpd14935', 'cpd11488', 'cpd00781', 'cpd01726', 'cpd11225', 'cpd03416', 'cpd15411', 'cpd03048', 'cpd15362', 'cpd15506', 'cpd02685', 'cpd00017', 'cpd00082', 'cpd02606', 'cpd15398', 'cpd15557', 'cpd00780', 'cpd00358', 'cpd00112', 'cpd15542', 'cpd08210', 'cpd00184', 'cpd02799', 'cpd15321', 'cpd00103', 'cpd15358', 'cpd15509', 'cpd03343', 'cpd12225', 'cpd01420', 'cpd15317', 'cpd00068', 'cpd15530', 'cpd00516', 'cpd00091', 'cpd15460', 'cpd15352', 'cpd11915', 'cpd03526', 'cpd00343', 'cpd00331', 'cpd11918', 'cpd00408', 'cpd01947', 'cpd00093', 'cpd02197', 'cpd15396', 'cpd15507', 'cpd11469', 'cpd15363', 'cpd16759', 'cpd15547', 'cpd00104', 'cpd00842', 'cpd15561', 'cpd01260', 'cpd00448', 'cpd08615', 'cpd00911', 'cpd15407', 'cpd16738', 'cpd01845', 'cpd15500', 'cpd00891', 'cpd11465', 'cpd00978', 'cpd00957', 'cpd15545', 'cpd00158', 'cpd16748', 'cpd15930', 'cpd16876', 'cpd01059', 'cpd11924', 'cpd00658', 'cpd00268', 'cpd03400', 'cpd02124', 'cpd00742', 'cpd11735', 'cpd00192', 'cpd00045', 'cpd03920', 'cpd12843', 'cpd03470', 'cpd00081', 'cpd00894', 'cpd11491', 'cpd05498', 'cpd03750', 'cpd00176', 'cpd00177', 'cpd12829', 'cpd00350', 'cpd15528', 'cpd07326', 'cpd02546', 'cpd15322', 'cpd01923', 'cpd03002', 'cpd00106', 'cpd00035', 'cpd00653', 'cpd00254', 'cpd00144', 'cpd12226', 'cpd00238', 'cpd15579', 'cpd00773', 'cpd15312', 'cpd00438', 'cpd00089', 'cpd01647', 'cpd00592', 'cpd00452', 'cpd00036', 'cpd16335', 'cpd00321', 'cpd00347', 'cpd15532', 'cpd00804', 'cpd15403', 'cpd00486', 'cpd00151', 'cpd15537', 'cpd00367', 'cpd15971', 'cpd01476', 'cpd15535', 'cpd00489', 'cpd00294', 'cpd00065', 'cpd01441', 'cpd01217', 'cpd00519', 'cpd01246', 'cpd00363', 'cpd11922', 'cpd00281', 'cpd15348', 'cpd15538', 'cpd15515', 'cpd00314', 'cpd00918', 'cpd02920', 'cpd01973', 'cpd00307', 'cpd02446', 'cpd01024', 'cpd12547', 'cpd15575', 'cpd08358', 'cpd03834', 'cpd15546', 'cpd08288', 'cpd00873', 'cpd16174', 'cpd16184', 'cpd00727', 'cpd02147', 'cpd00242', 'cpd01155', 'cpd00262', 'cpd00509', 'cpd08300', 'cpd12335', 'cpd19020', 'cpd00446', 'cpd16038', 'cpd01017', 'cpd11471', 'cpd15512', 'cpd03414', 'cpd02160', 'cpd00357', 'cpd03726', 'cpd00654', 'cpd00419', 'cpd00559', 'cpd17002', 'cpd03697', 'cpd03916', 'cpd15433', 'cpd00530', 'cpd00053', 'cpd00098', 'cpd15493', 'cpd03307', 'cpd03105', 'cpd01030', 'cpd11485', 'cpd17595', 'cpd00196', 'cpd11474', 'cpd00284', 'cpd11668', 'cpd15405', 'cpd00388', 'cpd01200', 'cpd00246', 'cpd00349', 'cpd02097', 'cpd15510', 'cpd00515', 'cpd03422', 'cpd11909', 'cpd02168', 'cpd00147', 'cpd08630', 'cpd16079', 'cpd02100', 'cpd08376', 'cpd03832', 'cpd00033', 'cpd08631', 'cpd00004', 'cpd00073', 'cpd03215', 'cpd04122', 'cpd00046', 'cpd11482', 'cpd03125', 'cpd15353', 'cpd00808', 'cpd00116', 'cpd00117', 'cpd00689', 'cpd11919', 'cpd00050', 'cpd00642', 'cpd00191', 'cpd03701', 'cpd00025', 'cpd15388', 'cpd00263', 'cpd06227', 'cpd15522', 'cpd15526', 'cpd00226', 'cpd03977', 'cpd00283', 'cpd00295', 'cpd00521', 'cpd03279', 'cpd11907', 'cpd14659', 'cpd15497', 'cpd10515', 'cpd15394', 'cpd00166', 'cpd00012', 'cpd19245', 'cpd00199', 'cpd16736', 'cpd00119', 'cpd14545', 'cpd01031', 'cpd15310', 'cpd15548', 'cpd03525', 'cpd01107', 'cpd01646', 'cpd11910', 'cpd02720', 'cpd00946', 'cpd12828', 'cpd00561', 'cpd03114', 'cpd11836', 'cpd15494', 'cpd11468', 'cpd15436', 'cpd08629', 'cpd15451', 'cpd15501', 'cpd15316', 'cpd01449', 'cpd00024', 'cpd09844', 'cpd03918', 'cpd03831', 'cpd15523', 'cpd19016', 'cpd04095', 'cpd19045', 'cpd00126', 'cpd00203', 'cpd14937', 'cpd01889', 'cpd15360', 'cpd19030', 'cpd00084', 'cpd02625', 'cpd00123', 'cpd00441', 'cpd15544', 'cpd16507', 'cpd00006', 'cpd00497', 'cpd15533', 'cpd11313', 'cpd15487', 'cpd00058', 'cpd01982', 'cpd00604', 'cpd15418', 'cpd00931', 'cpd02731', 'cpd03485', 'cpd15521', 'cpd15314', 'cpd16828', 'cpd00099', 'cpd00136', 'cpd03282', 'cpd10719', 'cpd15450', 'cpd16758', 'cpd11913', 'cpd00205', 'cpd00524', 'cpd00056', 'cpd02229', 'cpd00128', 'cpd11489', 'cpd00041', 'cpd00982', 'cpd00475', 'cpd03130', 'cpd00250', 'cpd03454', 'cpd03529', 'cpd01355', 'cpd00382', 'cpd00220', 'cpd00793', 'cpd16055', 'cpd02884', 'cpd15347', 'cpd00146', 'cpd00745', 'cpd01772', 'cpd02234', 'cpd01399', 'cpd00908', 'cpd00437', 'cpd19172', 'cpd03220', 'cpd11621', 'cpd16897', 'cpd02894', 'cpd02375', 'cpd01307', 'cpd15237', 'cpd11914', 'cpd19013', 'cpd02886', 'cpd11908', 'cpd15343', 'cpd15345', 'cpd00311', 'cpd02060', 'cpd16755', 'cpd03833', 'cpd04099', 'cpd11175', 'cpd11408', 'cpd15326', 'cpd00415', 'cpd01012', 'cpd00418', 'cpd01587', 'cpd00076', 'cpd00019', 'cpd00840', 'cpd01716', 'cpd00279', 'cpd00976', 'cpd01186', 'cpd15387', 'cpd00447', 'cpd19042', 'cpd03847', 'cpd15404', 'cpd00465', 'cpd02721', 'cpd00087', 'cpd00204', 'cpd01055', 'cpd11594', 'cpd02631', 'cpd00412', 'cpd00222', 'cpd16744', 'cpd01620', 'cpd00867', 'cpd01796', 'cpd00278', 'cpd15355', 'cpd00810', 'cpd01270', 'cpd02572', 'cpd15508', 'cpd01793', 'cpd15518', 'cpd15504', 'cpd04761', 'cpd15536', 'cpd15511', 'cpd15324', 'cpd11487', 'cpd01298', 'cpd00805', 'cpd08021', 'cpd00007', 'cpd00070', 'cpd11574', 'cpd15439', 'cpd03586', 'cpd01960', 'cpd00573', 'cpd00526', 'cpd01553', 'cpd03517', 'cpd03396', 'cpd11665', 'cpd02021', 'cpd01966', 'cpd12194', 'cpd00062', 'cpd03708', 'cpd15434', 'cpd15420', 'cpd02740', 'cpd03123', 'cpd03320', 'cpd00693', 'cpd15311', 'cpd01101', 'cpd00223', 'cpd03113', 'cpd03216', 'cpd15330', 'cpd00171', 'cpd02636', 'cpd15274', 'cpd00297', 'cpd01741', 'cpd16752', 'cpd00020', 'cpd00791', 'cpd00458', 'cpd00300', 'cpd00831', 'cpd03091', 'cpd15514', 'cpd19171', 'cpd00061', 'cpd02437', 'cpd02597', 'cpd15306', 'cpd00198', 'cpd00247', 'cpd02211', 'cpd15410', 'cpd01080', 'cpd00038', 'cpd02431', 'cpd00557', 'cpd00197', 'cpd12852', 'cpd03471', 'cpd02465', 'cpd12884', 'cpd01133', 'cpd01034', 'cpd05499', 'cpd00206', 'cpd15408', 'cpd19028', 'cpd01733', 'cpd00635', 'cpd00663'}
Seed IDs missing in thermo_data: {'cpd29681', 'cpd28023', 'cpd28273', 'cpd26385', 'cpd22077', 'cpd26805', 'cpd27735', 'cpd27569', 'cpd30760', 'cpd21488', 'cpd28473', 'cpd29672', 'cpd26831', 'cpd27608', 'cpd26436', 'cpd30761', 'cpd24697', 'cpd23280', 'cpd28379', 'cpd23282', 'cpd29676', 'cpd29671', 'cpd21120', 'cpd28030', 'cpd28024', 'cpd29667', 'cpd26726', 'cpd29665', 'cpd29674', 'cpd29680', 'cpd22021', 'cpd22061', 'cpd27013', 'cpd22075', 'cpd27551', 'cpd29679', 'cpd22119', 'cpd28276', 'cpd22495', 'cpd29731', 'cpd28275', 'cpd23281', 'cpd28162', 'cpd27358', 'cpd29668', 'cpd28277', 'cpd27371', 'cpd15465', 'cpd29678', 'cpd28060', 'cpd20862', 'cpd27830', 'cpd30744', 'cpd29677', 'cpd27563', 'cpd29670', 'cpd27042', 'cpd20863', 'cpd29733', 'cpd27436', 'cpd25615', 'cpd22621', 'cpd29669', 'cpd26836', 'cpd29666', 'cpd29675', 'cpd24605', 'cpd27103', 'cpd26729', 'cpd22076', 'cpd29673', 'cpd28378', 'cpd22062', 'cpd27379'}

In [ ]:
# --- 4️⃣ Initialize ThermoModel ---
mytfa = pytfa.ThermoModel(thermo_data, cobra_model)

# --- 5️⃣ Annotate metabolites from lexicon and apply compartment info ---

annotate_from_lexicon(mytfa, lexicon)
apply_compartment_data(mytfa, compartment_data)

2026-03-09 15:31:51,938 - thermomodel_None - INFO - # Model initialized with units kcal/mol and temperature 298.15 K
INFO:thermomodel_None:# Model initialized with units kcal/mol and temperature 298.15 K

# Lexicon autocreation V2

In [ ]:
from pathlib import Path
import pandas as pd

# --- Paths ---

compounds_path = MODELS_DIR / "ModelSEEDDatabase"/"Biochemistry"/"compounds.json"  # your ModelSEED compounds JSON
#lexicon_out_path = PHB_MODEL_TFA_DIR / "lexicon_auto.csv"



# --- Load ModelSEED compounds ---
import json
# --- Load ModelSEED compounds ---
with open(compounds_path) as f:
    compounds = json.load(f)

# --- Create mappings ---
name_to_seed = {}
bigg_to_seed = {}

for c in compounds:
    seed_id = c["id"]

    # Map names / synonyms
    names = [c.get("name", "")] + (c.get("aliases") or [])
    for n in names:
        if n:
            n_clean = str(n).strip().lower()
            name_to_seed[n_clean] = seed_id

    # Map BiGG IDs if available
    aliases = c.get("aliases") or []
    for entry in aliases:
        if isinstance(entry, str) and entry.startswith("BiGG:"):
            ids = entry.split(":", 1)[1]
            for bigg in ids.split(";"):
                bigg = bigg.strip().lower()
                if bigg:
                    bigg_to_seed[bigg] = seed_id

# --- Function to strip compartment suffix ---
def strip_compartment(met_id):
    return re.sub(r'_[cpep]$', '', met_id.lower())

# --- Map COBRA model metabolites ---
# Assume cobra_model is already loaded
lexicon_rows = []

for m in cobra_model.metabolites:
    met_id_clean = strip_compartment(m.id)

    # 1️⃣ Try BiGG ID mapping
    seed_id = bigg_to_seed.get(met_id_clean)

    # 2️⃣ Try metabolite name mapping (fallback)
    if seed_id is None and hasattr(m, "name"):
        seed_id = name_to_seed.get(m.name.lower())

    # 3️⃣ Try stripped metabolite id as a last resort
    if seed_id is None:
        seed_id = name_to_seed.get(met_id_clean)

    # 4️⃣ If still not found, leave empty
    if seed_id is None:
        seed_id = ""

    lexicon_rows.append({"met_id": m.id, "seed_id": seed_id})

# --- Save lexicon ---
lexicon_df = pd.DataFrame(lexicon_rows)
lexicon_df.to_csv(lexicon_out_path, index=False)

# --- Report coverage ---
mapped = (lexicon_df['seed_id'] != '').sum()
total = len(lexicon_df)
coverage = mapped / total * 100

print(f"Lexicon saved to {lexicon_out_path}")
print(f"Metabolites mapped: {mapped} / {total} ({coverage:.1f}%)")

# --- List unmapped metabolites for manual curation ---
unmapped = lexicon_df[lexicon_df['seed_id'] == '']
print(f"\nUnmapped metabolites ({len(unmapped)}):")
print(unmapped['met_id'].tolist())

Lexicon saved to /content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/models/phb/tfa/lexicon_auto.csv
Metabolites mapped: 1859 / 2124 (87.5%)

Unmapped metabolites (265):
['14dhncoa_c', 'h2o_cx_c', 'bm_pro_c', 'bm_cw_c', 'bm_pigm_c', 'o2_u', 'u3hga2_c', '3pg_cx_c', 'npdp_c', 'hco3_cx_c', 'bm_cofactors_c', 'co2_cx_c', 'bm_rna_c', 'o2_cx_c', 'bm_dna_c', 'bm_carbs_c', 'bm_memlip_c', 'lipidX2_c', 'phyto_c', 'h2o_u', 'dvpchlda_c', 'lipidAds2_c', 'cthzp_c', 'tczcaro_c', 'dczcaro_c', 'ttclyco_c', 'gthbpt_c', 'iscssh_c', 'iscsh_c', 'this_c', 'athis_c', 'thissh_c', 'ogmeACP_c', 'hgmeACP_c', 'egmeACP_c', 'gmeACP_c', 'opmeACP_c', 'hpmeACP_c', 'epmeACP_c', 'pmeACP_c', 'pimACP_c', 'octapb_c', 'lipopb_c', 'cdg_c', 'preq1_c', 'preqtrna_c', 'epxqtrna_c', 'quetrna_c', 'pa1619Z160_c', '12dgr1619Z160_c', 'sqdg160_c', 'sqdg1619Z160_c', 'mgdg1619Z160_c', 'dgdg1619Z160_c', 'dgdg161_c', 'mgdg161_c', 'glcdg1619Z160_c', 'glcdg161_c', 'glcdg1819Z1619Z_c', 'glcdg1819Z160_c', 'dgdg1819Z160Z_c', 'photon410_e', 'photon430_e', 'photon470_e', 'photon510_e', 'photon530_e', 'photon550_e', 'photon570_e', 'photon590_e', 'photon610_e', 'photon630_e', 'photon650_e', 'photon670_e', 'photon690_e', 'chla_qy1_exc_c', 'pho_loss_c', 'u23ga2_c', 'u3aga2_c', 'kdolipid4cy_c', 'unagam_c', 'pchlld_exc_c', 'chla_qy2_exc_c', 'p700_um_p', 'p700_exc_um_p', 'p680_exc_um_p', 'p680_um_p', 'k_u', 'ps2d1_um_p', 'ps2d1_exc_um_p', 'bamppald_c', 'ficytc6_u', 'focytc6_u', 'ficytc6_p', 'focytc6_p', 'pa181_9_c', 'cdpdodec9eg_c', 'pa182_9_12_c', 'cdpdodec912eg_c', 'pa183_6_9_12_c', 'cdpdodec6912eg_c', 'pa183_9_12_15_c', 'cdpdodec91215eg_c', 'pa184_6_9_12_15_c', 'cdpdodec691215eg_c', 'octe_9_ACP_c', '1odec912eg3p_c', 'octe_9_12_ACP_c', '1odec691215eg3p_c', 'octe_6_9_12_15_ACP_c', '1odec91215eg3p_c', 'octe_9_12_15_ACP_c', '1odec6912eg3p_c', 'octe_6_9_12_ACP_c', 'pgp181_9_c', 'pgp182_9_12_c', 'pgp183_6_9_12_c', 'pgp183_9_12_15_c', 'pgp184_6_9_12_15_c', 'sqdg161_c', 'sqdg180_c', 'sqdg181_c', '12dgr181_9_c', '12dgr182_9_12_c', 'sqdg182_9_12_c', '12dgr183_6_9_12_c', 'sqdg183_6_9_12_c', '12dgr183_9_12_15_c', '12dgr184_6_9_12_15_c', 'sqdg184_6_9_12_15_c', 'fdxo_42_c', 'fdxr_42_c', '2ddara_c', 'mercpeth_c', '3amac_c', 'sla_c', 'sf_c', 'sfp_c', 'ddcap_c', 'ttdcap_c', 'ttdceap_c', 'hdcap_c', 'hdceap_c', 'ocdcap_c', 'ocdceap_c', '6pgg_c', 'bmoco_c', 'moco_c', 'bmoco1gdp_c', 'bmocogdp_c', '2fe1s_c', '2fe2s_c', 'bwco_c', 'bwco1gdp_c', 'bwcogdp_c', 'wco_c', '5pg35pg_c', 'dhcholn_c', 'chtbs6p_c', 'colipap_p', 'colipap_e', 'prpmn_c', 'prcp_c', '23dhacoa_c', 'fe3dhbzs3_c', 'fe3dhbzs3_p', 'dhmpt_c', 'thmnp_c', 'flxso_c', 'f_p', 'f_c', 'iscu_2fe2s_c', 'iscu_c', 'iscs_c', 'iscu_2fe2s2_c', 'iscu_4fe4s_c', '4fe4s_c', 'moadamp_c', 'moadcosh_c', 'moadcoo_c', 'nadhx__R_c', 'nadhx__S_c', 'nadphx__S_c', 'rephaccoa_c', 'dhptdp_c', 'dhptdd_c', 'gmplys_c', 'nalme_c', 'poaac_c', 'puacgam_c', 'puacgam_p', 'uracp_c', 'sufbcd_2fe2s_c', 'sufsesh_c', 'sufse_c', 'sufbcd_c', 'sufbcd_2fe2s2_c', 'sufbcd_4fe4s_c', 'udcpgl_c', 'dccoa_c', 'ddcoa_c', '2o3mpt_c', 'eths_c', 'buts_c', 'hxal_c', 'hexs_c', 'amacald_c', 'sula_c', 'istnt_c', 'hghhlipa_c', 'hghhlipa_p', '3hbycoa_c', 'malttre_c', 'malttrtre_c', 'maltttrtre_c', 'maltpttre_c', 'salchs4_c', 'salchs4_p', 'btoh_c', '2hxmp_e', 'btoh_e', 'buts_e', 'cell4_e', 'cell500_e', 'eths_e', 'glucan1500_e', 'glucan4_e', 'glucan6_e', 'gm1lipa_e', 'hexs_e', 'istnt_e', 'madg_e', 'mbdg_e', 'salchs4_e', 'salchs4fe_e', 'sula_e', 'ghhlipa_c', '2h3opp_c', 'dhlplarg_c', 'lplarg_c', '3hphaccoa_c', '1h12dhl_c', 'phytfl_c', 'phytof_c', 'ggbcpa_c', 'bcpa_c', 'bcpb_c', 'bo3_c', 'bo3_e', 'bm_min_c', 'bm_oth_c', 'chitob_c', 'urdgci_c', 'tag1p__D_c', 'thcnm_c', 't23dxcm_c', 'mand_e', 'mand_p', 'mand_c', 'phbg_c', 'PHB_c', 'oanticy_p', 'oanticy_c', 'colipacy_e', 'colipacy_p', '2d5kg_c']

In [ ]:
# List metabolites with thermo data
annotated = [m.id for m in mytfa.metabolites if hasattr(m, "thermo")]
print(f"Metabolites annotated with thermodynamic data: {len(annotated)} / {len(mytfa.metabolites)}")

Metabolites annotated with thermodynamic data: 2124 / 2124

In [ ]:
for m in mytfa.metabolites[:10]:  # first 10 metabolites
    print(m.id, "->", getattr(m, "thermo", None))

gam6p_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
cgly_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
achms_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
pcox_u -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.0, 'ionicStr': 0.25}
octe9ACP_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
fdp_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
5caiz_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
pep_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
coa_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}
hgbam_c -> {'id': None, 'pKa': [], 'error': None, 'deltaGf_std': 1000.0, 'deltaGf_err': 1000.0, 'mass': 1000.0, 'nH_std': None, 'charge_std': 1000.0, 'struct_cues': None, 'deltaGf_tr': 1000.0, 'pH': 7.5, 'ionicStr': 0.25}

In [ ]:
unmapped = lexicon_df[lexicon_df['seed_id'] == '']
print(f"Unmapped metabolites ({len(unmapped)}):")
print(unmapped['met_id'].tolist())

Unmapped metabolites (265):
['14dhncoa_c', 'h2o_cx_c', 'bm_pro_c', 'bm_cw_c', 'bm_pigm_c', 'o2_u', 'u3hga2_c', '3pg_cx_c', 'npdp_c', 'hco3_cx_c', 'bm_cofactors_c', 'co2_cx_c', 'bm_rna_c', 'o2_cx_c', 'bm_dna_c', 'bm_carbs_c', 'bm_memlip_c', 'lipidX2_c', 'phyto_c', 'h2o_u', 'dvpchlda_c', 'lipidAds2_c', 'cthzp_c', 'tczcaro_c', 'dczcaro_c', 'ttclyco_c', 'gthbpt_c', 'iscssh_c', 'iscsh_c', 'this_c', 'athis_c', 'thissh_c', 'ogmeACP_c', 'hgmeACP_c', 'egmeACP_c', 'gmeACP_c', 'opmeACP_c', 'hpmeACP_c', 'epmeACP_c', 'pmeACP_c', 'pimACP_c', 'octapb_c', 'lipopb_c', 'cdg_c', 'preq1_c', 'preqtrna_c', 'epxqtrna_c', 'quetrna_c', 'pa1619Z160_c', '12dgr1619Z160_c', 'sqdg160_c', 'sqdg1619Z160_c', 'mgdg1619Z160_c', 'dgdg1619Z160_c', 'dgdg161_c', 'mgdg161_c', 'glcdg1619Z160_c', 'glcdg161_c', 'glcdg1819Z1619Z_c', 'glcdg1819Z160_c', 'dgdg1819Z160Z_c', 'photon410_e', 'photon430_e', 'photon470_e', 'photon510_e', 'photon530_e', 'photon550_e', 'photon570_e', 'photon590_e', 'photon610_e', 'photon630_e', 'photon650_e', 'photon670_e', 'photon690_e', 'chla_qy1_exc_c', 'pho_loss_c', 'u23ga2_c', 'u3aga2_c', 'kdolipid4cy_c', 'unagam_c', 'pchlld_exc_c', 'chla_qy2_exc_c', 'p700_um_p', 'p700_exc_um_p', 'p680_exc_um_p', 'p680_um_p', 'k_u', 'ps2d1_um_p', 'ps2d1_exc_um_p', 'bamppald_c', 'ficytc6_u', 'focytc6_u', 'ficytc6_p', 'focytc6_p', 'pa181_9_c', 'cdpdodec9eg_c', 'pa182_9_12_c', 'cdpdodec912eg_c', 'pa183_6_9_12_c', 'cdpdodec6912eg_c', 'pa183_9_12_15_c', 'cdpdodec91215eg_c', 'pa184_6_9_12_15_c', 'cdpdodec691215eg_c', 'octe_9_ACP_c', '1odec912eg3p_c', 'octe_9_12_ACP_c', '1odec691215eg3p_c', 'octe_6_9_12_15_ACP_c', '1odec91215eg3p_c', 'octe_9_12_15_ACP_c', '1odec6912eg3p_c', 'octe_6_9_12_ACP_c', 'pgp181_9_c', 'pgp182_9_12_c', 'pgp183_6_9_12_c', 'pgp183_9_12_15_c', 'pgp184_6_9_12_15_c', 'sqdg161_c', 'sqdg180_c', 'sqdg181_c', '12dgr181_9_c', '12dgr182_9_12_c', 'sqdg182_9_12_c', '12dgr183_6_9_12_c', 'sqdg183_6_9_12_c', '12dgr183_9_12_15_c', '12dgr184_6_9_12_15_c', 'sqdg184_6_9_12_15_c', 'fdxo_42_c', 'fdxr_42_c', '2ddara_c', 'mercpeth_c', '3amac_c', 'sla_c', 'sf_c', 'sfp_c', 'ddcap_c', 'ttdcap_c', 'ttdceap_c', 'hdcap_c', 'hdceap_c', 'ocdcap_c', 'ocdceap_c', '6pgg_c', 'bmoco_c', 'moco_c', 'bmoco1gdp_c', 'bmocogdp_c', '2fe1s_c', '2fe2s_c', 'bwco_c', 'bwco1gdp_c', 'bwcogdp_c', 'wco_c', '5pg35pg_c', 'dhcholn_c', 'chtbs6p_c', 'colipap_p', 'colipap_e', 'prpmn_c', 'prcp_c', '23dhacoa_c', 'fe3dhbzs3_c', 'fe3dhbzs3_p', 'dhmpt_c', 'thmnp_c', 'flxso_c', 'f_p', 'f_c', 'iscu_2fe2s_c', 'iscu_c', 'iscs_c', 'iscu_2fe2s2_c', 'iscu_4fe4s_c', '4fe4s_c', 'moadamp_c', 'moadcosh_c', 'moadcoo_c', 'nadhx__R_c', 'nadhx__S_c', 'nadphx__S_c', 'rephaccoa_c', 'dhptdp_c', 'dhptdd_c', 'gmplys_c', 'nalme_c', 'poaac_c', 'puacgam_c', 'puacgam_p', 'uracp_c', 'sufbcd_2fe2s_c', 'sufsesh_c', 'sufse_c', 'sufbcd_c', 'sufbcd_2fe2s2_c', 'sufbcd_4fe4s_c', 'udcpgl_c', 'dccoa_c', 'ddcoa_c', '2o3mpt_c', 'eths_c', 'buts_c', 'hxal_c', 'hexs_c', 'amacald_c', 'sula_c', 'istnt_c', 'hghhlipa_c', 'hghhlipa_p', '3hbycoa_c', 'malttre_c', 'malttrtre_c', 'maltttrtre_c', 'maltpttre_c', 'salchs4_c', 'salchs4_p', 'btoh_c', '2hxmp_e', 'btoh_e', 'buts_e', 'cell4_e', 'cell500_e', 'eths_e', 'glucan1500_e', 'glucan4_e', 'glucan6_e', 'gm1lipa_e', 'hexs_e', 'istnt_e', 'madg_e', 'mbdg_e', 'salchs4_e', 'salchs4fe_e', 'sula_e', 'ghhlipa_c', '2h3opp_c', 'dhlplarg_c', 'lplarg_c', '3hphaccoa_c', '1h12dhl_c', 'phytfl_c', 'phytof_c', 'ggbcpa_c', 'bcpa_c', 'bcpb_c', 'bo3_c', 'bo3_e', 'bm_min_c', 'bm_oth_c', 'chitob_c', 'urdgci_c', 'tag1p__D_c', 'thcnm_c', 't23dxcm_c', 'mand_e', 'mand_p', 'mand_c', 'phbg_c', 'PHB_c', 'oanticy_p', 'oanticy_c', 'colipacy_e', 'colipacy_p', '2d5kg_c']

In [ ]:
mytfa.prepare()

In [ ]:
thermo_data = load_thermoDB(PHB_MODEL_TFA_DIR / "thermo_data.thermodb")
thermo_data.keys
seed_ids_in_thermo = [str(k) for k in thermo_data['metabolites'].keys()]
print(seed_ids)

['cpd00805', 'cpd11364', 'cpd18424', 'cpd17488', 'cpd03902', 'cpd14767', 'cpd05076', 'cpd00475', 'cpd17550', 'cpd08432', 'cpd07669', 'cpd02398', 'cpd19498', 'cpd01442', 'cpd11437', 'cpd00087', 'cpd11395', 'cpd04959', 'cpd15625', 'cpd18361', 'cpd06546', 'cpd00372', 'cpd18691', 'cpd19841', 'cpd00872', 'cpd17787', 'cpd19729', 'cpd00304', 'cpd14524', 'cpd10597', 'cpd14588', 'cpd01231', 'cpd04691', 'cpd00111', 'cpd04068', 'cpd09476', 'cpd11126', 'cpd16375', 'cpd15649', 'cpd09999', 'cpd03405', 'cpd09059', 'cpd18413', 'cpd01057', 'cpd19453', 'cpd19201', 'cpd08677', 'cpd12309', 'cpd16152', 'cpd10577', 'cpd03314', 'cpd06273', 'cpd12213', 'cpd07931', 'cpd02409', 'cpd00542', 'cpd01389', 'cpd02322', 'cpd03481', 'cpd12243', 'cpd09124', 'cpd12572', 'cpd04888', 'cpd01221', 'cpd10369', 'cpd15423', 'cpd02901', 'cpd03043', 'cpd07770', 'cpd01306', 'cpd02020', 'cpd19165', 'cpd09816', 'cpd14564', 'cpd18260', 'cpd07302', 'cpd01778', 'cpd03354', 'cpd16530', 'cpd08525', 'cpd09445', 'cpd04738', 'cpd05001', 'cpd07527', 'cpd01878', 'cpd07481', 'cpd10418', 'cpd17153', 'cpd01800', 'cpd10677', 'cpd15032', 'cpd12506', 'cpd05171', 'cpd08837', 'cpd05627', 'cpd19693', 'cpd02114', 'cpd09201', 'cpd18661', 'cpd01844', 'cpd02235', 'cpd06023', 'cpd01195', 'cpd05406', 'cpd19208', 'cpd02259', 'cpd06284', 'cpd19817', 'cpd19337', 'cpd15360', 'cpd01978', 'cpd19199', 'cpd13416', 'cpd19625', 'cpd04726', 'cpd18487', 'cpd19186', 'cpd06312', 'cpd12613', 'cpd18968', 'cpd07254', 'cpd10600', 'cpd00023', 'cpd09017', 'cpd19608', 'cpd14447', 'cpd08973', 'cpd09339', 'cpd16770', 'cpd18930', 'cpd09414', 'cpd02942', 'cpd10785', 'cpd07423', 'cpd06083', 'cpd08660', 'cpd00633', 'cpd06370', 'cpd00483', 'cpd05132', 'cpd04896', 'cpd02041', 'cpd04598', 'cpd16797', 'cpd17364', 'cpd05174', 'cpd12319', 'cpd06868', 'cpd16113', 'cpd09023', 'cpd01826', 'cpd12202', 'cpd01635', 'cpd12347', 'cpd00004', 'cpd00897', 'cpd18939', 'cpd16608', 'cpd16988', 'cpd01329', 'cpd19371', 'cpd14769', 'cpd01250', 'cpd18176', 'cpd01331', 'cpd07974', 'cpd02915', 'cpd16133', 'cpd01020', 'cpd01059', 'cpd08133', 'cpd11675', 'cpd15220', 'cpd00053', 'cpd10016', 'cpd14479', 'cpd05393', 'cpd04640', 'cpd10906', 'cpd03824', 'cpd11930', 'cpd15427', 'cpd01062', 'cpd08227', 'cpd12568', 'cpd19296', 'cpd06020', 'cpd09759', 'cpd07871', 'cpd04205', 'cpd18111', 'cpd06350', 'cpd02722', 'cpd04755', 'cpd16651', 'cpd04171', 'cpd08984', 'cpd09408', 'cpd06757', 'cpd05530', 'cpd05386', 'cpd11799', 'cpd09442', 'cpd06118', 'cpd17981', 'cpd05140', 'cpd19428', 'cpd06891', 'cpd16296', 'cpd16598', 'cpd03804', 'cpd16356', 'cpd02327', 'cpd03908', 'cpd16487', 'cpd18166', 'cpd01614', 'cpd01959', 'cpd00320', 'cpd08998', 'cpd03461', 'cpd02101', 'cpd00909', 'cpd04329', 'cpd18857', 'cpd17388', 'cpd04975', 'cpd17817', 'cpd04793', 'cpd13345', 'cpd08689', 'cpd18607', 'cpd19889', 'cpd05047', 'cpd18038', 'cpd18809', 'cpd18090', 'cpd05415', 'cpd18498', 'cpd05211', 'cpd16839', 'cpd15897', 'cpd18865', 'cpd12407', 'cpd09485', 'cpd11452', 'cpd15453', 'cpd00027', 'cpd08428', 'cpd12507', 'cpd17839', 'cpd16590', 'cpd09794', 'cpd06898', 'cpd02623', 'cpd07346', 'cpd19287', 'cpd17449', 'cpd18913', 'cpd14544', 'cpd00415', 'cpd10818', 'cpd03821', 'cpd09704', 'cpd04133', 'cpd11827', 'cpd01360', 'cpd08135', 'cpd19041', 'cpd02508', 'cpd01697', 'cpd11506', 'cpd19811', 'cpd01392', 'cpd17029', 'cpd03770', 'cpd04593', 'cpd01529', 'cpd17229', 'cpd01181', 'cpd14822', 'cpd19364', 'cpd19183', 'cpd10848', 'cpd08248', 'cpd06824', 'cpd01744', 'cpd10770', 'cpd06419', 'cpd01348', 'cpd19456', 'cpd02044', 'cpd04081', 'cpd00565', 'cpd15879', 'cpd09375', 'cpd09850', 'cpd15219', 'cpd08113', 'cpd10599', 'cpd14990', 'cpd00408', 'cpd02629', 'cpd03839', 'cpd10510', 'cpd06622', 'cpd17983', 'cpd16478', 'cpd16902', 'cpd19175', 'cpd05981', 'cpd02861', 'cpd15511', 'cpd06486', 'cpd09542', 'cpd05794', 'cpd05020', 'cpd15329', 'cpd03832', 'cpd00322', 'cpd12108', 'cpd00928', 'cpd06088', 'cpd06237', 'cpd18051', 'cpd09957', 'cpd01453', 'cpd10443', 'cpd18024', 'cpd01440', 'cpd17320', 'cpd04212', 'cpd06722', 'cpd03792', 'cpd08797', 'cpd12694', 'cpd00268', 'cpd16586', 'cpd11349', 'cpd04340', 'cpd08129', 'cpd06771', 'cpd02022', 'cpd09145', 'cpd11101', 'cpd16043', 'cpd03838', 'cpd00614', 'cpd15432', 'cpd11158', 'cpd19747', 'cpd14910', 'cpd06094', 'cpd02647', 'cpd11301', 'cpd13267', 'cpd00176', 'cpd03473', 'cpd18632', 'cpd07047', 'cpd12732', 'cpd01811', 'cpd18631', 'cpd03390', 'cpd07906', 'cpd12489', 'cpd10112', 'cpd07163', 'cpd04671', 'cpd10687', 'cpd10426', 'cpd19431', 'cpd05389', 'cpd09520', 'cpd09743', 'cpd15300', 'cpd00391', 'cpd01642', 'cpd06304', 'cpd08459', 'cpd16201', 'cpd17678', 'cpd18275', 'cpd12355', 'cpd06882', 'cpd10912', 'cpd10846', 'cpd06918', 'cpd07594', 'cpd00429', 'cpd18555', 'cpd08838', 'cpd11932', 'cpd11917', 'cpd14671', 'cpd19424', 'cpd19857', 'cpd06360', 'cpd07812', 'cpd07166', 'cpd01232', 'cpd00838', 'cpd15078', 'cpd06740', 'cpd00640', 'cpd11676', 'cpd01517', 'cpd02968', 'cpd12688', 'cpd11332', 'cpd11531', 'cpd17389', 'cpd10880', 'cpd05286', 'cpd02238', 'cpd03775', 'cpd10066', 'cpd18861', 'cpd15314', 'cpd05928', 'cpd02479', 'cpd18197', 'cpd16645', 'cpd14968', 'cpd19410', 'cpd08641', 'cpd09885', 'cpd06330', 'cpd11525', 'cpd19047', 'cpd07444', 'cpd00045', 'cpd16300', 'cpd11260', 'cpd15895', 'cpd16292', 'cpd11801', 'cpd05367', 'cpd09693', 'cpd07837', 'cpd11422', 'cpd19145', 'cpd11597', 'cpd18391', 'cpd07946', 'cpd13953', 'cpd01373', 'cpd16418', 'cpd17524', 'cpd02609', 'cpd18352', 'cpd08098', 'cpd11055', 'cpd11661', 'cpd00201', 'cpd17196', 'cpd11120', 'cpd00432', 'cpd13379', 'cpd05207', 'cpd04062', 'cpd00710', 'cpd16953', 'cpd08313', 'cpd14787', 'cpd00664', 'cpd04601', 'cpd17752', 'cpd18083', 'cpd18713', 'cpd15116', 'cpd15551', 'cpd11540', 'cpd07304', 'cpd14532', 'cpd01856', 'cpd00096', 'cpd14490', 'cpd17083', 'cpd00190', 'cpd17392', 'cpd15850', 'cpd06126', 'cpd07894', 'cpd15251', 'cpd00143', 'cpd09669', 'cpd16689', 'cpd14576', 'cpd12105', 'cpd00356', 'cpd16017', 'cpd03379', 'cpd09778', 'cpd12698', 'cpd11501', 'cpd01296', 'cpd10101', 'cpd01188', 'cpd08339', 'cpd07532', 'cpd07445', 'cpd01182', 'cpd16429', 'cpd09505', 'cpd16551', 'cpd01147', 'cpd03123', 'cpd06792', 'cpd02975', 'cpd19158', 'cpd10394', 'cpd04056', 'cpd12890', 'cpd14522', 'cpd07738', 'cpd03310', 'cpd07119', 'cpd18840', 'cpd19210', 'cpd04011', 'cpd16079', 'cpd07497', 'cpd11405', 'cpd12233', 'cpd02499', 'cpd18122', 'cpd17674', 'cpd07168', 'cpd04674', 'cpd09062', 'cpd03166', 'cpd02225', 'cpd07208', 'cpd08906', 'cpd15835', 'cpd15127', 'cpd15386', 'cpd03860', 'cpd19529', 'cpd02735', 'cpd12401', 'cpd08668', 'cpd03812', 'cpd06369', 'cpd03666', 'cpd10103', 'cpd17502', 'cpd06721', 'cpd05321', 'cpd16931', 'cpd07816', 'cpd09083', 'cpd06064', 'cpd09406', 'cpd03075', 'cpd14648', 'cpd03403', 'cpd08752', 'cpd17576', 'cpd06657', 'cpd07252', 'cpd03600', 'cpd08415', 'cpd19692', 'cpd15585', 'cpd04613', 'cpd02354', 'cpd18238', 'cpd00269', 'cpd02166', 'cpd04273', 'cpd01134', 'cpd08121', 'cpd19228', 'cpd12778', 'cpd03756', 'cpd19595', 'cpd10856', 'cpd18453', 'cpd00507', 'cpd06693', 'cpd19044', 'cpd04786', 'cpd11226', 'cpd05577', 'cpd00301', 'cpd00737', 'cpd19512', 'cpd18330', 'cpd19191', 'cpd04194', 'cpd07483', 'cpd11271', 'cpd09930', 'cpd12901', 'cpd15530', 'cpd15910', 'cpd14991', 'cpd08368', 'cpd11456', 'cpd04689', 'cpd00272', 'cpd11992', 'cpd03617', 'cpd06421', 'cpd03041', 'cpd02636', 'cpd09448', 'cpd16925', 'cpd11877', 'cpd02031', 'cpd10180', 'cpd04860', 'cpd12021', 'cpd11455', 'cpd02385', 'cpd04059', 'cpd08959', 'cpd12251', 'cpd15977', 'cpd09474', 'cpd06505', 'cpd07883', 'cpd05194', 'cpd02133', 'cpd00100', 'cpd09508', 'cpd08162', 'cpd19440', 'cpd00434', 'cpd05218', 'cpd03217', 'cpd03826', 'cpd11641', 'cpd17501', 'cpd06883', 'cpd03231', 'cpd06555', 'cpd02842', 'cpd09200', 'cpd19924', 'cpd16646', 'cpd02305', 'cpd08947', 'cpd06763', 'cpd04104', 'cpd05004', 'cpd04587', 'cpd19784', 'cpd14891', 'cpd18685', 'cpd15733', 'cpd01650', 'cpd10362', 'cpd16842', 'cpd09216', 'cpd16067', 'cpd06216', 'cpd04235', 'cpd06296', 'cpd01291', 'cpd17629', 'cpd05433', 'cpd07568', 'cpd09617', 'cpd18455', 'cpd16911', 'cpd00312', 'cpd08527', 'cpd02789', 'cpd05540', 'cpd09737', 'cpd14832', 'cpd07130', 'cpd10760', 'cpd17782', 'cpd03866', 'cpd05305', 'cpd11651', 'cpd04324', 'cpd09314', 'cpd09613', 'cpd15484', 'cpd17408', 'cpd01876', 'cpd00511', 'cpd17009', 'cpd03893', 'cpd16604', 'cpd16492', 'cpd03377', 'cpd05022', 'cpd07574', 'cpd04799', 'cpd03878', 'cpd03258', 'cpd05299', 'cpd06306', 'cpd18843', 'cpd02540', 'cpd16390', 'cpd08482', 'cpd05796', 'cpd17070', 'cpd11738', 'cpd03664', 'cpd18626', 'cpd03248', 'cpd11137', 'cpd10484', 'cpd03072', 'cpd06823', 'cpd18284', 'cpd07301', 'cpd02791', 'cpd00858', 'cpd04988', 'cpd03489', 'cpd14663', 'cpd18758', 'cpd11056', 'cpd12727', 'cpd06129', 'cpd01620', 'cpd09753', 'cpd01652', 'cpd11808', 'cpd00351', 'cpd00306', 'cpd16574', 'cpd12197', 'cpd02951', 'cpd15270', 'cpd06542', 'cpd07545', 'cpd02721', 'cpd07309', 'cpd07516', 'cpd12306', 'cpd14771', 'cpd18904', 'cpd09122', 'cpd06677', 'cpd17635', 'cpd17973', 'cpd17075', 'cpd16591', 'cpd18000', 'cpd15960', 'cpd12446', 'cpd01374', 'cpd00715', 'cpd07111', 'cpd07485', 'cpd06916', 'cpd05865', 'cpd02033', 'cpd04647', 'cpd06988', 'cpd19567', 'cpd03781', 'cpd03713', 'cpd12716', 'cpd15290', 'cpd02736', 'cpd02576', 'cpd01153', 'cpd04972', 'cpd18136', 'cpd03675', 'cpd18293', 'cpd07370', 'cpd18745', 'cpd05250', 'cpd19860', 'cpd17332', 'cpd02621', 'cpd07278', 'cpd12455', 'cpd10134', 'cpd03198', 'cpd19698', 'cpd04140', 'cpd12479', 'cpd04951', 'cpd02991', 'cpd09973', 'cpd11593', 'cpd02507', 'cpd17181', 'cpd14875', 'cpd06815', 'cpd18301', 'cpd09697', 'cpd10765', 'cpd07741', 'cpd10626', 'cpd19690', 'cpd16661', 'cpd11074', 'cpd16607', 'cpd09927', 'cpd19598', 'cpd06774', 'cpd19586', 'cpd03395', 'cpd04447', 'cpd02914', 'cpd05173', 'cpd08390', 'cpd02919', 'cpd04185', 'cpd12540', 'cpd07373', 'cpd15195', 'cpd13050', 'cpd17802', 'cpd09990', 'cpd02040', 'cpd01302', 'cpd06021', 'cpd02881', 'cpd16952', 'cpd02131', 'cpd03928', 'cpd04007', 'cpd19154', 'cpd06202', 'cpd12640', 'cpd14790', 'cpd02581', 'cpd08025', 'cpd19366', 'cpd03400', 'cpd05974', 'cpd11229', 'cpd16342', 'cpd08166', 'cpd12320', 'cpd05460', 'cpd18170', 'cpd10099', 'cpd02472', 'cpd15280', 'cpd03344', 'cpd16666', 'cpd09439', 'cpd14640', 'cpd08353', 'cpd06791', 'cpd03186', 'cpd12215', 'cpd04501', 'cpd19033', 'cpd02741', 'cpd17452', 'cpd10660', 'cpd10130', 'cpd16118', 'cpd11291', 'cpd15643', 'cpd00070', 'cpd19125', 'cpd09452', 'cpd02355', 'cpd18266', 'cpd10515', 'cpd16410', 'cpd18718', 'cpd09393', 'cpd15376', 'cpd05192', 'cpd03435', 'cpd00231', 'cpd16380', 'cpd19542', 'cpd01699', 'cpd02803', 'cpd19127', 'cpd03195', 'cpd01236', 'cpd01966', 'cpd16875', 'cpd13420', 'cpd17916', 'cpd01818', 'cpd14594', 'cpd12055', 'cpd01451', 'cpd02261', 'cpd12648', 'cpd09653', 'cpd19198', 'cpd00826', 'cpd03056', 'cpd01345', 'cpd16528', 'cpd15671', 'cpd19214', 'cpd07387', 'cpd18887', 'cpd19831', 'cpd15707', 'cpd10547', 'cpd11251', 'cpd19674', 'cpd11952', 'cpd07901', 'cpd09001', 'cpd17669', 'cpd12229', 'cpd05683', 'cpd10795', 'cpd03128', 'cpd05739', 'cpd14568', 'cpd04915', 'cpd15603', 'cpd11090', 'cpd07137', 'cpd01971', 'cpd03863', 'cpd08825', 'cpd01367', 'cpd03260', 'cpd08726', 'cpd05646', 'cpd10322', 'cpd00671', 'cpd08553', 'cpd04719', 'cpd07734', 'cpd15629', 'cpd04228', 'cpd08564', 'cpd02628', 'cpd10672', 'cpd15762', 'cpd00160', 'cpd05307', 'cpd00170', 'cpd19340', 'cpd03702', 'cpd15302', 'cpd03288', 'cpd11165', 'cpd02169', 'cpd07283', 'cpd14946', 'cpd15035', 'cpd19487', 'cpd01346', 'cpd18575', 'cpd05479', 'cpd14992', 'cpd00283', 'cpd03483', 'cpd14821', 'cpd18075', 'cpd09423', 'cpd05501', 'cpd15627', 'cpd10415', 'cpd01110', 'cpd01946', 'cpd10630', 'cpd06427', 'cpd08563', 'cpd17826', 'cpd04802', 'cpd11821', 'cpd18185', 'cpd15385', 'cpd08864', 'cpd17125', 'cpd18888', 'cpd04042', 'cpd00397', 'cpd19627', 'cpd11390', 'cpd10061', 'cpd05402', 'cpd12300', 'cpd19519', 'cpd03774', 'cpd16396', 'cpd09422', 'cpd07475', 'cpd06851', 'cpd17249', 'cpd05335', 'cpd00333', 'cpd18645', 'cpd01446', 'cpd03642', 'cpd01172', 'cpd03868', 'cpd11542', 'cpd04402', 'cpd14620', 'cpd18767', 'cpd16276', 'cpd03822', 'cpd15827', 'cpd00124', 'cpd10825', 'cpd10218', 'cpd18559', 'cpd14476', 'cpd09722', 'cpd17476', 'cpd02548', 'cpd11880', 'cpd16050', 'cpd01437', 'cpd12886', 'cpd08183', 'cpd12659', 'cpd11537', 'cpd11884', 'cpd01593', 'cpd05392', 'cpd10145', 'cpd04260', 'cpd11977', 'cpd11814', 'cpd01184', 'cpd11474', 'cpd04312', 'cpd02608', 'cpd17371', 'cpd01243', 'cpd04979', 'cpd04143', 'cpd09213', 'cpd00744', 'cpd00941', 'cpd17398', 'cpd10954', 'cpd18560', 'cpd17287', 'cpd10695', 'cpd15642', 'cpd05008', 'cpd09763', 'cpd10165', 'cpd10989', 'cpd09663', 'cpd19187', 'cpd15888', 'cpd18201', 'cpd14611', 'cpd05970', 'cpd05541', 'cpd11890', 'cpd18545', 'cpd08255', 'cpd13436', 'cpd19867', 'cpd02279', 'cpd02425', 'cpd06879', 'cpd10839', 'cpd19003', 'cpd17203', 'cpd04127', 'cpd11907', 'cpd02577', 'cpd18491', 'cpd17030', 'cpd02937', 'cpd10079', 'cpd01873', 'cpd11289', 'cpd02635', 'cpd01237', 'cpd15905', 'cpd19684', 'cpd18662', 'cpd01708', 'cpd02818', 'cpd16207', 'cpd07681', 'cpd07435', 'cpd08115', 'cpd04230', 'cpd02949', 'cpd07075', 'cpd00011', 'cpd01824', 'cpd11934', 'cpd05072', 'cpd18688', 'cpd07954', 'cpd11965', 'cpd12275', 'cpd00518', 'cpd16527', 'cpd11639', 'cpd14782', 'cpd04226', 'cpd19304', 'cpd17170', 'cpd17276', 'cpd00924', 'cpd07766', 'cpd01615', 'cpd05854', 'cpd15253', 'cpd01698', 'cpd10353', 'cpd03141', 'cpd11562', 'cpd03680', 'cpd06468', 'cpd04326', 'cpd09605', 'cpd07884', 'cpd09139', 'cpd07617', 'cpd02804', 'cpd11314', 'cpd03039', 'cpd06932', 'cpd00315', 'cpd08157', 'cpd06455', 'cpd06445', 'cpd12480', 'cpd00357', 'cpd01272', 'cpd17594', 'cpd06327', 'cpd12093', 'cpd04034', 'cpd16387', 'cpd10303', 'cpd02339', 'cpd17784', 'cpd19143', 'cpd11047', 'cpd00393', 'cpd11257', 'cpd06329', 'cpd14339', 'cpd18721', 'cpd11842', 'cpd07629', 'cpd17330', 'cpd17318', 'cpd18770', 'cpd04427', 'cpd07648', 'cpd14794', 'cpd11595', 'cpd06248', 'cpd18504', 'cpd06972', 'cpd06913', 'cpd11397', 'cpd11299', 'cpd05225', 'cpd08682', 'cpd04904', 'cpd15652', 'cpd10213', 'cpd10781', 'cpd07904', 'cpd09771', 'cpd12588', 'cpd09284', 'cpd12043', 'cpd05718', 'cpd02457', 'cpd11773', 'cpd05088', 'cpd04758', 'cpd14486', 'cpd03294', 'cpd12448', 'cpd00813', 'cpd08264', 'cpd04353', 'cpd16790', 'cpd03885', 'cpd19184', 'cpd10999', 'cpd15672', 'cpd18616', 'cpd01791', 'cpd08370', 'cpd10884', 'cpd18463', 'cpd04743', 'cpd06520', 'cpd14477', 'cpd07192', 'cpd02063', 'cpd06514', 'cpd03760', 'cpd02088', 'cpd17663', 'cpd02306', 'cpd06400', 'cpd00465', 'cpd17120', 'cpd02862', 'cpd01463', 'cpd05332', 'cpd18621', 'cpd02470', 'cpd18964', 'cpd05452', 'cpd00285', 'cpd07442', 'cpd02588', 'cpd09589', 'cpd03279', 'cpd00200', 'cpd05533', 'cpd07735', 'cpd17131', 'cpd09769', 'cpd06857', 'cpd06870', 'cpd02848', 'cpd04064', 'cpd00109', 'cpd10194', 'cpd11385', 'cpd12349', 'cpd17065', 'cpd05280', 'cpd06122', 'cpd09129', 'cpd06146', 'cpd02342', 'cpd11950', 'cpd18792', 'cpd07436', 'cpd12097', 'cpd10261', 'cpd11027', 'cpd02445', 'cpd14978', 'cpd00756', 'cpd01492', 'cpd11293', 'cpd01766', 'cpd18813', 'cpd06464', 'cpd10072', 'cpd01142', 'cpd00654', 'cpd16015', 'cpd03521', 'cpd14550', 'cpd18975', 'cpd05537', 'cpd16393', 'cpd17145', 'cpd06308', 'cpd14928', 'cpd08517', 'cpd17022', 'cpd01144', 'cpd12261', 'cpd17575', 'cpd14889', 'cpd06265', 'cpd03197', 'cpd17610', 'cpd17242', 'cpd03648', 'cpd15847', 'cpd01354', 'cpd00017', 'cpd12419', 'cpd19442', 'cpd14842', 'cpd19798', 'cpd17285', 'cpd15346', 'cpd04841', 'cpd14484', 'cpd08153', 'cpd18369', 'cpd01948', 'cpd11609', 'cpd18751', 'cpd06104', 'cpd03587', 'cpd01859', 'cpd07094', 'cpd00660', 'cpd17224', 'cpd07940', 'cpd05375', 'cpd11447', 'cpd01879', 'cpd11220', 'cpd15670', 'cpd09685', 'cpd14494', 'cpd19480', 'cpd02594', 'cpd09799', 'cpd09154', 'cpd03229', 'cpd08552', 'cpd04830', 'cpd10108', 'cpd06560', 'cpd09744', 'cpd18817', 'cpd01748', 'cpd11188', 'cpd07921', 'cpd16280', 'cpd02672', 'cpd18066', 'cpd08610', 'cpd02769', 'cpd12493', 'cpd13430', 'cpd02513', 'cpd19294', 'cpd04325', 'cpd08439', 'cpd17623', 'cpd06554', 'cpd01551', 'cpd14945', 'cpd12589', 'cpd01961', 'cpd04515', 'cpd15685', 'cpd19034', 'cpd15675', 'cpd03814', 'cpd01838', 'cpd07165', 'cpd18239', 'cpd03015', 'cpd16825', 'cpd11490', 'cpd15193', 'cpd02386', 'cpd05155', 'cpd00321', 'cpd15541', 'cpd10709', 'cpd06504', 'cpd11218', 'cpd19128', 'cpd04283', 'cpd11037', 'cpd07125', 'cpd19247', 'cpd04061', 'cpd19510', 'cpd16540', 'cpd03777', 'cpd18738', 'cpd19553', 'cpd09681', 'cpd16957', 'cpd12073', 'cpd17980', 'cpd08806', 'cpd03067', 'cpd03085', 'cpd00348', 'cpd00718', 'cpd14338', 'cpd00581', 'cpd08743', 'cpd07588', 'cpd08802', 'cpd05806', 'cpd12550', 'cpd01863', 'cpd15149', 'cpd07008', 'cpd02546', 'cpd12751', 'cpd10897', 'cpd00132', 'cpd11457', 'cpd06518', 'cpd06493', 'cpd04628', 'cpd17660', 'cpd04323', 'cpd02753', 'cpd12718', 'cpd16299', 'cpd04798', 'cpd15956', 'cpd03394', 'cpd09349', 'cpd13440', 'cpd18492', 'cpd02550', 'cpd09826', 'cpd01396', 'cpd00613', 'cpd09905', 'cpd00079', 'cpd19471', 'cpd06855', 'cpd10224', 'cpd01106', 'cpd09376', 'cpd00384', 'cpd07140', 'cpd07329', 'cpd03881', 'cpd00956', 'cpd11742', 'cpd15969', 'cpd06481', 'cpd06405', 'cpd04968', 'cpd00973', 'cpd11464', 'cpd19009', 'cpd17250', 'cpd07180', 'cpd00589', 'cpd01667', 'cpd04546', 'cpd18324', 'cpd01070', 'cpd19623', 'cpd09884', 'cpd04476', 'cpd08771', 'cpd03446', 'cpd15604', 'cpd03750', 'cpd19493', 'cpd00729', 'cpd17528', 'cpd08199', 'cpd18571', 'cpd16114', 'cpd05959', 'cpd10651', 'cpd09961', 'cpd01152', 'cpd16495', 'cpd04715', 'cpd12818', 'cpd15701', 'cpd01923', 'cpd18085', 'cpd09342', 'cpd14626', 'cpd02344', 'cpd17267', 'cpd05506', 'cpd09354', 'cpd02527', 'cpd04502', 'cpd19151', 'cpd05565', 'cpd00760', 'cpd14746', 'cpd03580', 'cpd15934', 'cpd16662', 'cpd06485', 'cpd09101', 'cpd05686', 'cpd11392', 'cpd06548', 'cpd07024', 'cpd07129', 'cpd01917', 'cpd10811', 'cpd04268', 'cpd10612', 'cpd04908', 'cpd19753', 'cpd06124', 'cpd10064', 'cpd00330', 'cpd11277', 'cpd07898', 'cpd19707', 'cpd05444', 'cpd12474', 'cpd02912', 'cpd12007', 'cpd18532', 'cpd07961', 'cpd16308', 'cpd10987', 'cpd06496', 'cpd01336', 'cpd16187', 'cpd15976', 'cpd06161', 'cpd17805', 'cpd02816', 'cpd12615', 'cpd10652', 'cpd11295', 'cpd09982', 'cpd09177', 'cpd17862', 'cpd11124', 'cpd03029', 'cpd06157', 'cpd19897', 'cpd04430', 'cpd19630', 'cpd08022', 'cpd03172', 'cpd02765', 'cpd01538', 'cpd15793', 'cpd08277', 'cpd03046', 'cpd08732', 'cpd02787', 'cpd06886', 'cpd18879', 'cpd15872', 'cpd02292', 'cpd10506', 'cpd07313', 'cpd01655', 'cpd03865', 'cpd08084', 'cpd12642', 'cpd17255', 'cpd10688', 'cpd05813', 'cpd09084', 'cpd10308', 'cpd03964', 'cpd16690', 'cpd09498', 'cpd10830', 'cpd00645', 'cpd01191', 'cpd06487', 'cpd15477', 'cpd11820', 'cpd05243', 'cpd03747', 'cpd05661', 'cpd01569', 'cpd19405', 'cpd06645', 'cpd02690', 'cpd14921', 'cpd06102', 'cpd15479', 'cpd02144', 'cpd15419', 'cpd06743', 'cpd01319', 'cpd08173', 'cpd01501', 'cpd08235', 'cpd11853', 'cpd12454', 'cpd16103', 'cpd11794', 'cpd00028', 'cpd00471', 'cpd18642', 'cpd02692', 'cpd08597', 'cpd06101', 'cpd17053', 'cpd11967', 'cpd05685', 'cpd00576', 'cpd07722', 'cpd18131', 'cpd16138', 'cpd10734', 'cpd18958', 'cpd18990', 'cpd05503', 'cpd00498', 'cpd16592', 'cpd03351', 'cpd12302', 'cpd17619', 'cpd06051', 'cpd05311', 'cpd02356', 'cpd03409', 'cpd19803', 'cpd11523', 'cpd06690', 'cpd06683', 'cpd08901', 'cpd04414', 'cpd14605', 'cpd01431', 'cpd11268', 'cpd11924', 'cpd03618', 'cpd11592', 'cpd02782', 'cpd16471', 'cpd06755', 'cpd05254', 'cpd11065', 'cpd05826', 'cpd10980', 'cpd19641', 'cpd14820', 'cpd17044', 'cpd08230', 'cpd01662', 'cpd06214', 'cpd12534', 'cpd03795', 'cpd15747', 'cpd05764', 'cpd01066', 'cpd17288', 'cpd18982', 'cpd17748', 'cpd19859', 'cpd16035', 'cpd07324', 'cpd19576', 'cpd05038', 'cpd16366', 'cpd18254', 'cpd10046', 'cpd06773', 'cpd06154', 'cpd04266', 'cpd08206', 'cpd00059', 'cpd02428', 'cpd19290', 'cpd11483', 'cpd00462', 'cpd04053', 'cpd11843', 'cpd14813', 'cpd12649', 'cpd12877', 'cpd01176', 'cpd04817', 'cpd10869', 'cpd04696', 'cpd19515', 'cpd07489', 'cpd01962', 'cpd00855', 'cpd08328', 'cpd12693', 'cpd17206', 'cpd16182', 'cpd031

In [ ]:
seed_ids_in_lexicon = set(lexicon_df['seed_id'])
len(seed_ids_in_lexicon)

1295

In [ ]:
seed_ids_in_thermo = {str(k) for k in thermo_data['metabolites'].keys()}
seed_ids_in_lexicon = set(lexicon_df['seed_id'])

missing_in_thermo = seed_ids_in_lexicon - seed_ids_in_thermo
present_in_thermo = seed_ids_in_lexicon & seed_ids_in_thermo
unused_thermo_ids = seed_ids_in_thermo - seed_ids_in_lexicon

In [ ]:
print("Seed IDs in lexicon:", len(seed_ids_in_lexicon))
print("Seed IDs in ThermoDB:", len(seed_ids_in_thermo))
print("Lexicon IDs found in ThermoDB:", len(present_in_thermo))
print("Lexicon IDs missing in ThermoDB:", len(missing_in_thermo))

Seed IDs in lexicon: 1295
Seed IDs in ThermoDB: 18307
Lexicon IDs found in ThermoDB: 1175
Lexicon IDs missing in ThermoDB: 120

In [ ]:
sum("seed_id" in m.annotation for m in cobra_model.metabolites)

0

In [ ]:
cobra_model.metabolites[0].annotation

{'SeedID': 'cpd00288'}

In [ ]:
cobra_model.metabolites[0].annotation["SeedID"]

'cpd00288'

In [ ]:
for m in cobra_model.metabolites:
    if 'SeedID' in m.annotation:
        m.annotation['seed.compound'] = m.annotation['SeedID']

In [ ]:
for m in cobra_model.metabolites[:10]:
    print(m.id, m.annotation)

gam6p_c {'SeedID': 'cpd00288', 'seed.compound': 'cpd00288'}
cgly_c {}
achms_c {}
pcox_u {}
octe9ACP_c {}
fdp_c {}
5caiz_c {}
pep_c {}
coa_c {}
hgbam_c {}

# Fixing

In [ ]:
mytfa = ThermoModel(thermo_data, cobra_model)

mytfa.prepare()

2026-03-09 19:47:42,133 - thermomodel_None - INFO - # Model initialized with units kcal/mol and temperature 298.15 K
INFO:thermomodel_None:# Model initialized with units kcal/mol and temperature 298.15 K
2026-03-09 19:47:42,137 - thermomodel_None - INFO - # Model preparation starting...
INFO:thermomodel_None:# Model preparation starting...
DEBUG:thermomodel_None:Metabolite gam6p_c (D-Glucosamine 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite cgly_c (Cys Gly C5H10N2O3S) has no seed_id
DEBUG:thermomodel_None:Metabolite achms_c (O Acetyl L homoserine C6H11NO4) has no seed_id
DEBUG:thermomodel_None:Metabolite pcox_u (Plastocyanin(Cu2+)) has no seed_id
DEBUG:thermomodel_None:Metabolite octe9ACP_c (Cis-octadec-9-enoyl-[acyl-carrier protein] ((9Z)-n-C18:1)) has no seed_id
DEBUG:thermomodel_None:Metabolite fdp_c (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 5caiz_c (5-phosphoribosyl-5-carboxyaminoimidazole) has no seed_id
DEBUG:thermomodel_None:Metabolite pep_c (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite coa_c (Coenzyme A) has no seed_id
DEBUG:thermomodel_None:Metabolite hgbam_c (Hydrogenobyrinate a,c diamide) has no seed_id
DEBUG:thermomodel_None:Metabolite nac_c (Nicotinate) has no seed_id
DEBUG:thermomodel_None:Metabolite r3mmal_c (D-erythro-3-Methylmalate) has no seed_id
DEBUG:thermomodel_None:Metabolite leu__L_c (L-Leucine) has no seed_id
DEBUG:thermomodel_None:Metabolite ahcys_c (S-Adenosyl-L-homocysteine) has no seed_id
DEBUG:thermomodel_None:Metabolite ru5p__D_c (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 14dhncoa_c (1,4-dihydroxy-2-napthoyl-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_cx_c (H2O H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h2s_c (Hydrogen sulfide) has no seed_id
DEBUG:thermomodel_None:Metabolite orot_c (Orotate C5H3N2O4) has no seed_id
DEBUG:thermomodel_None:Metabolite g1p_c (D-Glucose 1-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hdecACP_c ((R)-3-Hydroxydecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite na1_c (Sodium) has no seed_id
DEBUG:thermomodel_None:Metabolite 2pglyc_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_None:Metabolite ala_B_c (Beta-Alanine) has no seed_id
DEBUG:thermomodel_None:Metabolite glyc3p_c (Glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pqh2_um_p (Plastoquinol) has no seed_id
DEBUG:thermomodel_None:Metabolite 26dap_LL_c (LL-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_None:Metabolite ddcaACP_c (Dodecanoyl-ACP (n-C12:0ACP)) has no seed_id
DEBUG:thermomodel_None:Metabolite 2pglyc_cx_c (2-Phosphoglycolate) has no seed_id
DEBUG:thermomodel_None:Metabolite trdox_c (Oxidized thioredoxin) has no seed_id
DEBUG:thermomodel_None:Metabolite 3oddecACP_c (3-Oxododecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__D_c (D-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite h_cx_c (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite dutp_c (DUTP C9H11N2O14P3) has no seed_id
DEBUG:thermomodel_None:Metabolite paps_c (3'-Phosphoadenylyl sulfate) has no seed_id
DEBUG:thermomodel_None:Metabolite mg2_c (Magnesium) has no seed_id
DEBUG:thermomodel_None:Metabolite hdeACP_c (Cis-hexadec-9-enoyl-[acyl-carrier protein] (n-C16:1)) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_c (O2 O2) has no seed_id
DEBUG:thermomodel_None:Metabolite anth_c (Anthranilate) has no seed_id
DEBUG:thermomodel_None:Metabolite dhpt_c (Dihydropteroate) has no seed_id
DEBUG:thermomodel_None:Metabolite thex2eACP_c (Trans-Hex-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite fmn_c (FMN C17H19N4O9P) has no seed_id
DEBUG:thermomodel_None:Metabolite pppi_c (Inorganic triphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite udp_c (UDP C9H11N2O12P2) has no seed_id
DEBUG:thermomodel_None:Metabolite cit_c (Citrate) has no seed_id
DEBUG:thermomodel_None:Metabolite acACP_c (Acetyl-ACP) has no seed_id
DEBUG:thermomodel_None:Metabolite uama_c (UDP-N-acetylmuramoyl-L-alanine) has no seed_id
DEBUG:thermomodel_None:Metabolite eig3p_c (D-erythro-1-(Imidazol-4-yl)glycerol 3-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3c4mop_c (3-Carboxy-4-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite lys__L_c (L-Lysine) has no seed_id
DEBUG:thermomodel_None:Metabolite 13dpg_c (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite gmp_c (GMP C10H12N5O8P) has no seed_id
DEBUG:thermomodel_None:Metabolite utp_c (UTP C9H11N2O15P3) has no seed_id
DEBUG:thermomodel_None:Metabolite trdrd_c (Reduced thioredoxin) has no seed_id
DEBUG:thermomodel_None:Metabolite so4_c (Sulfate) has no seed_id
DEBUG:thermomodel_None:Metabolite 5apru_c (5-Amino-6-(5'-phosphoribosylamino)uracil) has no seed_id
DEBUG:thermomodel_None:Metabolite hmppp9_c (13(1)-Hydroxy-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_None:Metabolite pydx5p_c (Pyridoxal 5'-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 2dhp_c (2-Dehydropantoate) has no seed_id
DEBUG:thermomodel_None:Metabolite ade_c (Adenine) has no seed_id
DEBUG:thermomodel_None:Metabolite asp__L_c (L-Aspartate) has no seed_id
DEBUG:thermomodel_None:Metabolite 2sephchc_c (2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylate) has no seed_id
DEBUG:thermomodel_None:Metabolite acg5p_c (N-Acetyl-L-glutamyl 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite gdp_c (GDP C10H12N5O11P2) has no seed_id
DEBUG:thermomodel_None:Metabolite hgbyr_c (Hydrogenobyrinate) has no seed_id
DEBUG:thermomodel_None:Metabolite palmACP_c (Palmitoyl-ACP (n-C16:0ACP)) has no seed_id
DEBUG:thermomodel_None:Metabolite pser__L_c (O-Phospho-L-serine) has no seed_id
DEBUG:thermomodel_None:Metabolite ocACP_c (Octanoyl-ACP (n-C8:0ACP)) has no seed_id
DEBUG:thermomodel_None:Metabolite dttp_c (DTTP C10H13N2O14P3) has no seed_id
DEBUG:thermomodel_None:Metabolite 6pgc_c (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_None:Metabolite gcald_c (Glycolaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite 2p4c2me_c (2-phospho-4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_None:Metabolite cmp_c (CMP C9H12N3O8P) has no seed_id
DEBUG:thermomodel_None:Metabolite bm_pro_c (Protein component of biomass) has no seed_id
DEBUG:thermomodel_None:Metabolite pi_c (Phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pnto__R_c ((R)-Pantothenate) has no seed_id
DEBUG:thermomodel_None:Metabolite dump_c (DUMP C9H11N2O8P) has no seed_id
DEBUG:thermomodel_None:Metabolite omppp9_c (13(1)-Oxo-magnesium-protoporphyrin IX 13-monomethyl ester) has no seed_id
DEBUG:thermomodel_None:Metabolite 23dhmp_c ((R)-2,3-Dihydroxy-3-methylpentanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite gtp_c (GTP C10H12N5O14P3) has no seed_id
DEBUG:thermomodel_None:Metabolite 4h2oglt_c (4 Hydroxy 2 oxoglutarate C5H4O6) has no seed_id
DEBUG:thermomodel_None:Metabolite prfp_c (1-(5-Phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_None:Metabolite man1p_c (D-Mannose 1-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite dxyl5p_c (1-deoxy-D-xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hddecACP_c ((R)-3-Hydroxydodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite cu2_c (Copper) has no seed_id
DEBUG:thermomodel_None:Metabolite malACP_c (Malonyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite 2mahmp_c (2-Methyl-4-amino-5-hydroxymethylpyrimidine diphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite phpyr_c (Phenylpyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite fe2_c (Fe2+ mitochondria) has no seed_id
DEBUG:thermomodel_None:Metabolite phllqne_c (Phylloquinone) has no seed_id
DEBUG:thermomodel_None:Metabolite toct2eACP_c (Trans-Oct-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite dgdp_c (DGDP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_None:Metabolite uaccg_c (UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine) has no seed_id
DEBUG:thermomodel_None:Metabolite acald_c (Acetaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite o2s_c (Superoxide anion) has no seed_id
DEBUG:thermomodel_None:Metabolite alac__S_c ((S)-2-Acetolactate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hmop_c ((R)-3-Hydroxy-3-methyl-2-oxopentanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite 4abz_c (4-Aminobenzoate) has no seed_id
DEBUG:thermomodel_None:Metabolite prbamp_c (1-(5-Phosphoribosyl)-AMP) has no seed_id
DEBUG:thermomodel_None:Metabolite ca2_c (Calcium) has no seed_id
DEBUG:thermomodel_None:Metabolite glyclt_c (Glycolate C2H3O3) has no seed_id
DEBUG:thermomodel_None:Metabolite butACP_c (Butyryl-ACP (n-C4:0ACP)) has no seed_id
DEBUG:thermomodel_None:Metabolite 4ppcys_c (N-((R)-4-Phosphopantothenoyl)-L-cysteine) has no seed_id
DEBUG:thermomodel_None:Metabolite udpgal_c (UDPgalactose) has no seed_id
DEBUG:thermomodel_None:Metabolite f6p_c (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite lac__D_c (D-Lactate) has no seed_id
DEBUG:thermomodel_None:Metabolite his__L_c (L-Histidine) has no seed_id
DEBUG:thermomodel_None:Metabolite agdpcbi_c (Adenosine-GDP-cobinamide) has no seed_id
DEBUG:thermomodel_None:Metabolite s17bp_c (Sedoheptulose 1,7-bisphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite dctp_c (DCTP C9H12N3O13P3) has no seed_id
DEBUG:thermomodel_None:Metabolite thf_c (5,6,7,8-Tetrahydrofolate) has no seed_id
DEBUG:thermomodel_None:Metabolite 25aics_c ((S)-2-[5-Amino-1-(5-phospho-D-ribosyl)imidazole-4-carboxamido]succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite ni2_c (Nickel) has no seed_id
DEBUG:thermomodel_None:Metabolite dtdp4d6dg_c (DTDP-4-dehydro-6-deoxy-D-glucose) has no seed_id
DEBUG:thermomodel_None:Metabolite malcoa_c (Malonyl CoA C24H33N7O19P3S) has no seed_id
DEBUG:thermomodel_None:Metabolite fum_c (Fumarate) has no seed_id
DEBUG:thermomodel_None:Metabolite bm_cw_c (Cell wall component of biomass) has no seed_id
DEBUG:thermomodel_None:Metabolite ACP_c (Acyl carrier protein) has no seed_id
DEBUG:thermomodel_None:Metabolite mlthf_c (5,10-Methylenetetrahydrofolate) has no seed_id
DEBUG:thermomodel_None:Metabolite h_p (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite dhf_c (7,8-Dihydrofolate) has no seed_id
DEBUG:thermomodel_None:Metabolite dudp_c (DUDP C9H11N2O11P2) has no seed_id
DEBUG:thermomodel_None:Metabolite 3omrsACP_c (3-Oxotetradecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite trnaglu_c (TRNA (Glu)) has no seed_id
DEBUG:thermomodel_None:Metabolite pre6a_c (Precorrin 6A) has no seed_id
DEBUG:thermomodel_None:Metabolite ametam_c (S-Adenosylmethioninamine) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hhexACP_c ((R)-3-Hydroxyhexanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite 4ppan_c (D-4'-Phosphopantothenate) has no seed_id
DEBUG:thermomodel_None:Metabolite quln_c (Quinolinate) has no seed_id
DEBUG:thermomodel_None:Metabolite frdp_c (Farnesyl diphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite glyald_c (D-Glyceraldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite uacgam_c (UDP-N-acetyl-D-glucosamine) has no seed_id
DEBUG:thermomodel_None:Metabolite pram_c (5-Phospho-beta-D-ribosylamine) has no seed_id
DEBUG:thermomodel_None:Metabolite 26dap__M_c (Meso-2,6-Diaminoheptanedioate) has no seed_id
DEBUG:thermomodel_None:Metabolite gdpmann_c (GDP-D-mannose) has no seed_id
DEBUG:thermomodel_None:Metabolite db4p_c (3,4-dihydroxy-2-butanone 4-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite actACP_c (Acetoacetyl-ACP) has no seed_id
DEBUG:thermomodel_None:Metabolite actp_c (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite ugmd_c (UDP-N-acetylmuramoyl-L-alanyl-D-gamma-glutamyl-meso-2,6-diaminopimelate) has no seed_id
DEBUG:thermomodel_None:Metabolite s7p_c (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite cbm_c (Carbamate) has no seed_id
DEBUG:thermomodel_None:Metabolite co2_c (CO2 CO2) has no seed_id
DEBUG:thermomodel_None:Metabolite zeax_c (Zeaxanthin) has no seed_id
DEBUG:thermomodel_None:Metabolite ptrc_c (Putrescine) has no seed_id
DEBUG:thermomodel_None:Metabolite adp_c (ADP C10H12N5O10P2) has no seed_id
DEBUG:thermomodel_None:Metabolite 3a2oxpp_c (3-Amino-2-oxopropyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite aspsa_c (L-Aspartate 4-semialdehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite tdec2eACP_c (Trans-Dec-2-enoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite phom_c (O-Phospho-L-homoserine) has no seed_id
DEBUG:thermomodel_None:Metabolite amylose_c (Amylose) has no seed_id
DEBUG:thermomodel_None:Metabolite 5mdr1p_c (5-Methylthio-5-deoxy-D-ribose 1-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite rb15bp_cx_c (D-Ribulose 1,5-bisphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite bcryptox_c (Beta-Cryptoxanthin) has no seed_id
DEBUG:thermomodel_None:Metabolite spmd_c (Spermidine) has no seed_id
DEBUG:thermomodel_None:Metabolite udpsq_c (UDP-6-sulfoquinovose) has no seed_id
DEBUG:thermomodel_None:Metabolite h2_c (Hydrogen) has no seed_id
DEBUG:thermomodel_None:Metabolite adocbip_c (Adenosyl cobinamide phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite phycy_c ((3Z)-Phycocyanobilin) has no seed_id
DEBUG:thermomodel_None:Metabolite nadh_c (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_None:Metabolite aps_c (Adenosine 5'-phosphosulfate) has no seed_id
DEBUG:thermomodel_None:Metabolite dpcoa_c (Dephospho-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite xu5p__D_c (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite no2_c (Nitrite) has no seed_id
DEBUG:thermomodel_None:Metabolite 4hbz_c (4-Hydroxybenzoate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3odecACP_c (3-Oxodecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite dhnpt_c (Dihydroneopterin) has no seed_id
DEBUG:thermomodel_None:Metabolite 5aprbu_c (5-Amino-6-(5'-phosphoribitylamino)uracil) has no seed_id
DEBUG:thermomodel_None:Metabolite iasp_c (Iminoaspartate) has no seed_id
DEBUG:thermomodel_None:Metabolite nmn_c (NMN C11H14N2O8P) has no seed_id
DEBUG:thermomodel_None:Metabolite bm_pigm_c (Pigment component of biomass) has no seed_id
DEBUG:thermomodel_None:Metabolite 2cpr5p_c (1-(2-Carboxyphenylamino)-1-deoxy-D-ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pchlld_c (Protochlorophyllide) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_u (O2 O2) has no seed_id
DEBUG:thermomodel_None:Metabolite ala__L_c (L-Alanine) has no seed_id
DEBUG:thermomodel_None:Metabolite 3c2hmp_c (3-Carboxy-2-hydroxy-4-methylpentanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite pyr_c (Pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite hco3_c (Bicarbonate) has no seed_id
DEBUG:thermomodel_None:Metabolite pan4p_c (Pantetheine 4'-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite succ_c (Succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite citac_c (Citraconate) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_c (H2O H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h_c (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite ugmda_c (UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimeloyl-D-alanyl-D-alanine) has no seed_id
DEBUG:thermomodel_None:Metabolite pq_um_p (Plastoquinone) has no seed_id
DEBUG:thermomodel_None:Metabolite man6p_c (D-Mannose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite cobalt2_c (Co2+) has no seed_id
DEBUG:thermomodel_None:Metabolite gam1p_c (D-Glucosamine 1-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite argsuc_c (N(omega)-(L-Arginino)succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite dhap_c (Dihydroxyacetone phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite mn2_c (Manganese) has no seed_id
DEBUG:thermomodel_None:Metabolite u3hga2_c (UDP-3-O-(3-hydroxyhexadecanoyl)-D-glucosamine) has no seed_id
DEBUG:thermomodel_None:Metabolite 2obut_c (2-Oxobutanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite dtmp_c (DTMP C10H13N2O8P) has no seed_id
DEBUG:thermomodel_None:Metabolite fpram_c (2-(Formamido)-N1-(5-phospho-D-ribosyl)acetamidine) has no seed_id
DEBUG:thermomodel_None:Metabolite ump_c (UMP C9H11N2O9P) has no seed_id
DEBUG:thermomodel_None:Metabolite 3pg_cx_c (3-Phospho-D-glycerate) has no seed_id
DEBUG:thermomodel_None:Metabolite pq_cm_c (Plastoquinone) has no seed_id
DEBUG:thermomodel_None:Metabolite ahdt_c (2-Amino-4-hydroxy-6-(erythro-1,2,3-trihydroxypropyl)dihydropteridine triphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite npdp_c (All-trans-Nonaprenyl diphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite dhor__S_c ((S)-Dihydroorotate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3opalmACP_c (3-Oxohexadecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite glx_c (Glyoxylate) has no seed_id
DEBUG:thermomodel_None:Metabolite thdp_c (2,3,4,5-Tetrahydrodipicolinate) has no seed_id
DEBUG:thermomodel_None:Metabolite fprica_c (5-Formamido-1-(5-phospho-D-ribosyl)imidazole-4-carboxamide) has no seed_id
DEBUG:thermomodel_None:Metabolite adocbl_c (Adenosylcobalamin) has no seed_id
DEBUG:thermomodel_None:Metabolite thr__L_c (L-Threonine) has no seed_id
DEBUG:thermomodel_None:Metabolite so3_c (Sulfite) has no seed_id
DEBUG:thermomodel_None:Metabolite 2m6sbenzq_c (2-Methyl-6-solanyl-1,4-benzoquinol) has no seed_id
DEBUG:thermomodel_None:Metabolite hco3_cx_c (Bicarbonate) has no seed_id
DEBUG:thermomodel_None:Metabolite glu5p_c (L-Glutamate 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hmrsACP_c ((R)-3-Hydroxytetradecanoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite 4c2me_c (4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol) has no seed_id
DEBUG:thermomodel_None:Metabolite damp_c (DAMP C10H12N5O6P) has no seed_id
DEBUG:thermomodel_None:Metabolite histda_c (L-histidinal) has no seed_id
DEBUG:thermomodel_None:Metabolite gthox_c (Oxidized glutathione) has no seed_id
DEBUG:thermomodel_None:Metabolite amp_c (AMP C10H12N5O7P) has no seed_id
DEBUG:thermomodel_None:Metabolite 23dhmb_c ((R)-2,3-Dihydroxy-3-methylbutanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite 5mdru1p_c (5-Methylthio-5-deoxy-D-ribulose 1-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite mppp9_c (Magnesium protoporphyrin) has no seed_id
DEBUG:thermomodel_None:Metabolite cdp_c (CDP C9H12N3O11P2) has no seed_id
DEBUG:thermomodel_None:Metabolite dcaACP_c (Decanoyl-ACP (n-C10:0ACP)) has no seed_id
DEBUG:thermomodel_None:Metabolite 2me4p_c (2-C-methyl-D-erythritol 4-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3hpalmACP_c (R-3-hydroxypalmitoyl-[acyl-carrier protein]) has no seed_id
DEBUG:thermomodel_None:Metabolite 2ahbut_c ((S)-2-Aceto-2-hydroxybutanoate) has no seed_id
DEBUG:thermomodel_None:Metabolite caro_c (Beta-Carotene) has no seed_id
DEBUG:thermomodel_None:Metabolite 3dhq_c (3-Dehydroquinate) has no seed_id
DEBUG:thermomodel_None:Metabolite 4adcho_c (4-amino-4-deoxychorismate) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__L_c (L-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite bm_cofactors_c (Biomass metabolite: cofactors and ions) has no seed_id
DEBUG:thermomodel_None:Metabolite 34hpp_c (3-(4-Hydroxyphenyl)pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite ctp_c (CTP C9H12N3O14P3) has no seed_id
DEBUG:thermomodel_None:Metabolite pqh2_cm_c (Plastoquinol) has no seed_id
DEBUG:thermomodel_None:Metabolite fad_c (Flavin adenine dinucleotide oxidized) has no seed_id

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_None:NDPK1 : thermo constraint NOT created
DEBUG:thermomodel_None:PGL : thermo constraint NOT created
DEBUG:thermomodel_None:EAR160y : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDHf : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR3_1 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD140 : thermo constraint NOT created
DEBUG:thermomodel_None:FBA3 : thermo constraint NOT created
DEBUG:thermomodel_None:LDAPAT : thermo constraint NOT created
DEBUG:thermomodel_None:MG2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3E_1_cx : thermo constraint NOT created
DEBUG:thermomodel_None:ACODA : thermo constraint NOT created
DEBUG:thermomodel_None:GLU5K : thermo constraint NOT created
DEBUG:thermomodel_None:EAR100y : thermo constraint NOT created
DEBUG:thermomodel_None:PGM : thermo constraint NOT created
DEBUG:thermomodel_None:ASPOb : thermo constraint NOT created
DEBUG:thermomodel_None:DM_h2_c : thermo constraint NOT created
DEBUG:thermomodel_None:ACS : thermo constraint NOT created
DEBUG:thermomodel_None:AMPTASECG : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHCS3 : thermo constraint NOT created
DEBUG:thermomodel_None:ATPPRT : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_4_um_copy1 : thermo constraint NOT created
DEBUG:thermomodel_None:UAGCVT : thermo constraint NOT created
DEBUG:thermomodel_None:ADSL2r : thermo constraint NOT created
DEBUG:thermomodel_None:PRASCSi : thermo constraint NOT created
DEBUG:thermomodel_None:MG2tex : thermo constraint NOT created
DEBUG:thermomodel_None:HPROb : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP2 : thermo constraint NOT created
DEBUG:thermomodel_None:TRDR : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK6 : thermo constraint NOT created
DEBUG:thermomodel_None:GLUPRT : thermo constraint NOT created
DEBUG:thermomodel_None:PTRCabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:UPP3MT : thermo constraint NOT created
DEBUG:thermomodel_None:DHNCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:MCOATA : thermo constraint NOT created
DEBUG:thermomodel_None:PMPK : thermo constraint NOT created
DEBUG:thermomodel_None:HMBS : thermo constraint NOT created
DEBUG:thermomodel_None:PGLYCP : thermo constraint NOT created
DEBUG:thermomodel_None:UAGAAT2 : thermo constraint NOT created
DEBUG:thermomodel_None:HTHRPDH : thermo constraint NOT created
DEBUG:thermomodel_None:BCT1_syn : thermo constraint NOT created
DEBUG:thermomodel_None:IPDDI : thermo constraint NOT created
DEBUG:thermomodel_None:GLYALDDy : thermo constraint NOT created
DEBUG:thermomodel_None:CITMS : thermo constraint NOT created
DEBUG:thermomodel_None:IMPC : thermo constraint NOT created
DEBUG:thermomodel_None:Htcx : thermo constraint NOT created
DEBUG:thermomodel_None:DHQTi : thermo constraint NOT created
DEBUG:thermomodel_None:SPODM : thermo constraint NOT created
DEBUG:thermomodel_None:MAN6PI : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS120 : thermo constraint NOT created
DEBUG:thermomodel_None:PGAMT : thermo constraint NOT created
DEBUG:thermomodel_None:PSERT : thermo constraint NOT created
DEBUG:thermomodel_None:HISTP : thermo constraint NOT created
DEBUG:thermomodel_None:NNDPR : thermo constraint NOT created
DEBUG:thermomodel_None:ADSK : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPS : thermo constraint NOT created
DEBUG:thermomodel_None:CUabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADCYRS : thermo constraint NOT created
DEBUG:thermomodel_None:RBPCcx : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD40_2 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR180y : thermo constraint NOT created
DEBUG:thermomodel_None:GTHRDH_syn : thermo constraint NOT created
DEBUG:thermomodel_None:PRAIi : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTtabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTPATi : thermo constraint NOT created
DEBUG:thermomodel_None:PC6AR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:Kabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ENO : thermo constraint NOT created
DEBUG:thermomodel_None:PRFGS : thermo constraint NOT created
DEBUG:thermomodel_None:PC8XM : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS60 : thermo constraint NOT created
DEBUG:thermomodel_None:GMPS2 : thermo constraint NOT created
DEBUG:thermomodel_None:RBFK : thermo constraint NOT created
DEBUG:thermomodel_None:NTRIRfx : thermo constraint NOT created
DEBUG:thermomodel_None:GTHPi : thermo constraint NOT created
DEBUG:thermomodel_None:ARGSS : thermo constraint NOT created
DEBUG:thermomodel_None:SPTc : thermo constraint NOT created
DEBUG:thermomodel_None:H2Otpp : thermo constraint NOT created
DEBUG:thermomodel_None:TDPDRE : thermo constraint NOT created
DEBUG:thermomodel_None:GTHOr : thermo constraint NOT created
DEBUG:thermomodel_None:SHK3Dr : thermo constraint NOT created
DEBUG:thermomodel_None:CYRDAR : thermo constraint NOT created
DEBUG:thermomodel_None:ORPT : thermo constraint NOT created
DEBUG:thermomodel_None:GRTT : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_MEM_LIPIDS : thermo constraint NOT created
DEBUG:thermomodel_None:PRPPS : thermo constraint NOT created
DEBUG:thermomodel_None:KARA1 : thermo constraint NOT created
DEBUG:thermomodel_None:FCLT : thermo constraint NOT created
DEBUG:thermomodel_None:PPA : thermo constraint NOT created
DEBUG:thermomodel_None:DHQS : thermo constraint NOT created
DEBUG:thermomodel_None:ANPRT : thermo constraint NOT created
DEBUG:thermomodel_None:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_None:UPP3S : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK5 : thermo constraint NOT created
DEBUG:thermomodel_None:DHNPA_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK4 : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR4 : thermo constraint NOT created
DEBUG:thermomodel_None:NADK : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR40_2 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_None:NO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:FE3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MOBDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:NPHBDC : thermo constraint NOT created
DEBUG:thermomodel_None:NPDPS : thermo constraint NOT created
DEBUG:thermomodel_None:NI2uabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3tcx : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR2 : thermo constraint NOT created
DEBUG:thermomodel_None:KARI_1 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR40y : thermo constraint NOT created
DEBUG:thermomodel_None:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_None:DHNCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_PROTEIN : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS100 : thermo constraint NOT created
DEBUG:thermomodel_None:G1SAT : thermo constraint NOT created
DEBUG:thermomodel_None:ILETA : thermo constraint NOT created
DEBUG:thermomodel_None:UAAGDS : thermo constraint NOT created
DEBUG:thermomodel_None:GLCDBRAN3 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX1 : thermo constraint NOT created
DEBUG:thermomodel_None:ATPSum : thermo constraint NOT created
DEBUG:thermomodel_None:CHPHYS : thermo constraint NOT created
DEBUG:thermomodel_None:BCAROHX : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCLTDx : thermo constraint NOT created
DEBUG:thermomodel_None:PIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PC20M : thermo constraint NOT created
DEBUG:thermomodel_None:ADSS : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_RNA : thermo constraint NOT created
DEBUG:thermomodel_None:DM_dialurate_c : thermo constraint NOT created
DEBUG:thermomodel_None:THRPDC : thermo constraint NOT created
DEBUG:thermomodel_None:TMDS3 : thermo constraint NOT created
DEBUG:thermomodel_None:DHFR : thermo constraint NOT created
DEBUG:thermomodel_None:ACGS : thermo constraint NOT created
DEBUG:thermomodel_None:AFAT : thermo constraint NOT created
DEBUG:thermomodel_None:GLYOX_1 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR140y : thermo constraint NOT created
DEBUG:thermomodel_None:FRTT : thermo constraint NOT created
DEBUG:thermomodel_None:CTPS2 : thermo constraint NOT created
DEBUG:thermomodel_None:DESAT16a : thermo constraint NOT created
DEBUG:thermomodel_None:CO2tex : thermo constraint NOT created
DEBUG:thermomodel_None:GTHS : thermo constraint NOT created
DEBUG:thermomodel_None:UAGDP : thermo constraint NOT created
DEBUG:thermomodel_None:DADK : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMC1_1 : thermo constraint NOT created
DEBUG:thermomodel_None:Nat_Kpp : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS180 : thermo constraint NOT created
DEBUG:thermomodel_None:EAR80y : thermo constraint NOT created
DEBUG:thermomodel_None:ERTHMMOR : thermo constraint NOT created
DEBUG:thermomodel_None:PDH : thermo constraint NOT created
DEBUG:thermomodel_None:MPML : thermo constraint NOT created
DEBUG:thermomodel_None:USHD2 : thermo constraint NOT created
DEBUG:thermomodel_None:TPI : thermo constraint NOT created
DEBUG:thermomodel_None:DHPPDA : thermo constraint NOT created
DEBUG:thermomodel_None:PRMICI : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBD4um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_co_c : thermo constraint NOT created
DEBUG:thermomodel_None:CAT : thermo constraint NOT created
DEBUG:thermomodel_None:GLUR : thermo constraint NOT created
DEBUG:thermomodel_None:ALAR : thermo constraint NOT created
DEBUG:thermomodel_None:SULR_2 : thermo constraint NOT created
DEBUG:thermomodel_None:NAt3pp : thermo constraint NOT created
DEBUG:thermomodel_None:ADCS : thermo constraint NOT created
DEBUG:thermomodel_None:UGMDDS : thermo constraint NOT created
DEBUG:thermomodel_None:BIOMASS_CARB : thermo constraint NOT created
DEBUG:thermomodel_None:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_None:ACHBSb : thermo constraint NOT created
DEBUG:thermomodel_None:MTRI : thermo constraint NOT created
DEBUG:thermomodel_None:SPMS : thermo constraint NOT created
DEBUG:thermomodel_None:AHSERL2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PEPC : thermo constraint NOT created
DEBUG:thermomodel_None:PHETA1 : thermo constraint NOT created
DEBUG:thermomodel_None:CHORM : thermo constraint NOT created
DEBUG:thermomodel_None:GAPD : thermo constraint NOT created
DEBUG:thermomodel_None:PQH2tcm : thermo constraint NOT created
DEBUG:thermomodel_None:CPPPGO : thermo constraint NOT created
DEBUG:thermomodel_None:URIDK2r : thermo constraint NOT created
DEBUG:thermomodel_None:OCBT : thermo constraint NOT created
DEBUG:thermomodel_None:E4PD : thermo constraint NOT created
DEBUG:thermomodel_None:IPPMIa : thermo constraint NOT created
DEBUG:thermomodel_None:GLGC : thermo constraint NOT created
DEBUG:thermomodel_None:PYK : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD120 : thermo constraint NOT created
DEBUG:thermomodel_None:2PGLYCtcx : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMOR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS160 : thermo constraint NOT created
DEBUG:thermomodel_None:IG3PS : thermo constraint NOT created
DEBUG:thermomodel_None:NTRARf2 : thermo constraint NOT created
DEBUG:thermomodel_None:CA2t2pp : thermo constraint NOT created
DEBUG:thermomodel_None:DM_5drib_c : thermo constraint NOT created
DEBUG:thermomodel_None:RPI : thermo constraint NOT created
DEBUG:thermomodel_None:FMNRy_1 : thermo constraint NOT created
DEBUG:thermomodel_None:ANS2 : thermo constraint NOT created
DEBUG:thermomodel_None:GHMT2r : thermo constraint NOT created
DEBUG:thermomodel_None:BPNT : thermo constraint NOT created
DEBUG:thermomodel_None:PSIIum : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCum : thermo constraint NOT created
DEBUG:thermomodel_None:SK_amylose_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_14glucan_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_glycogen_c : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_leu__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cobalt2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_zn2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_so4_e : thermo constraint NOT created

Warning : None/None
Warning : None/None
Warning : None/None
Warning : None/None

DEBUG:thermomodel_None:EX_spmd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ca2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_arg__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mn2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hco3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mg2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ptrc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fe2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cu2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_k_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_no3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fe3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mobd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ni2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_na1_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cynt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_None:FE3tex : thermo constraint NOT created
DEBUG:thermomodel_None:FE2tex : thermo constraint NOT created
DEBUG:thermomodel_None:NI2tex : thermo constraint NOT created
DEBUG:thermomodel_None:MNtex : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2tex : thermo constraint NOT created
DEBUG:thermomodel_None:CU2tex : thermo constraint NOT created
DEBUG:thermomodel_None:Zn2tex : thermo constraint NOT created
DEBUG:thermomodel_None:SPMDtex : thermo constraint NOT created
DEBUG:thermomodel_None:LEUtex : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:GLNtex : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTtex : thermo constraint NOT created
DEBUG:thermomodel_None:ARGtex : thermo constraint NOT created
DEBUG:thermomodel_None:MOBDtex : thermo constraint NOT created
DEBUG:thermomodel_None:NH4tex : thermo constraint NOT created
DEBUG:thermomodel_None:SO4tex : thermo constraint NOT created
DEBUG:thermomodel_None:NO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:NAtex : thermo constraint NOT created
DEBUG:thermomodel_None:CA2tex : thermo constraint NOT created
DEBUG:thermomodel_None:Ktex : thermo constraint NOT created
DEBUG:thermomodel_None:CO2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:PItex : thermo constraint NOT created
DEBUG:thermomodel_None:MDRPD : thermo constraint NOT created
DEBUG:thermomodel_None:ENOPH : thermo constraint NOT created
DEBUG:thermomodel_None:ARD : thermo constraint NOT created
DEBUG:thermomodel_None:UNK3 : thermo constraint NOT created
DEBUG:thermomodel_None:PHYPQOX : thermo constraint NOT created
DEBUG:thermomodel_None:ZISO : thermo constraint NOT created
DEBUG:thermomodel_None:ZCARDS : thermo constraint NOT created
DEBUG:thermomodel_None:PLYCOI : thermo constraint NOT created
DEBUG:thermomodel_None:TRNFE : thermo constraint NOT created
DEBUG:thermomodel_None:PTHPS : thermo constraint NOT created
DEBUG:thermomodel_None:SPR : thermo constraint NOT created
DEBUG:thermomodel_None:THBTGT : thermo constraint NOT created
DEBUG:thermomodel_None:CYSDES : thermo constraint NOT created
DEBUG:thermomodel_None:THISAT : thermo constraint NOT created
DEBUG:thermomodel_None:THII : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCOX1 : thermo constraint NOT created
DEBUG:thermomodel_None:DXYTST : thermo constraint NOT created
DEBUG:thermomodel_None:THZT : thermo constraint NOT created
DEBUG:thermomodel_None:SHS1 : thermo constraint NOT created
DEBUG:thermomodel_None:MALCOAMT : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPS : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OGMEACPD : thermo constraint NOT created
DEBUG:thermomodel_None:EGMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPS : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:OPMEACPD : thermo constraint NOT created
DEBUG:thermomodel_None:EPMEACPR : thermo constraint NOT created
DEBUG:thermomodel_None:PMEACPE : thermo constraint NOT created
DEBUG:thermomodel_None:AOXSr2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMAOTr : thermo constraint NOT created
DEBUG:thermomodel_None:DBTS : thermo constraint NOT created
DEBUG:thermomodel_None:BTS6 : thermo constraint NOT created
DEBUG:thermomodel_None:BACCL : thermo constraint NOT created
DEBUG:thermomodel_None:LIPOCT : thermo constraint NOT created
DEBUG:thermomodel_None:LIPOS2 : thermo constraint NOT created
DEBUG:thermomodel_None:MEOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:MEOHtex : thermo constraint NOT created
DEBUG:thermomodel_None:DM_amob_c : thermo constraint NOT created
DEBUG:thermomodel_None:ADNK1 : thermo constraint NOT created
DEBUG:thermomodel_None:CDGS : thermo constraint NOT created
DEBUG:thermomodel_None:CCGS : thermo constraint NOT created
DEBUG:thermomodel_None:CDGR : thermo constraint NOT created
DEBUG:thermomodel_None:QUERT : thermo constraint NOT created
DEBUG:thermomodel_None:SAMTRI : thermo constraint NOT created
DEBUG:thermomodel_None:EPXQR : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGD : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGLDC : thermo constraint NOT created
DEBUG:thermomodel_None:GMAND : thermo constraint NOT created
DEBUG:thermomodel_None:GFUCS : thermo constraint NOT created
DEBUG:thermomodel_None:CDPGLC46DH : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_1_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_None:NDH_1_4_um_copy2 : thermo constraint NOT created
DEBUG:thermomodel_None:KAS15 : thermo constraint NOT created
DEBUG:thermomodel_None:AACPS6 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDR18 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDDC17 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT1819Z_1 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:AGPAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:AGPATACP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA161 : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:PAPA_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:SQDGS_PALM_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:SQDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:CDPDAGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PGPS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:PGPP_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_HDE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_HDE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_OLE_HDE : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDGE_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:DGDGS_OLE_PALM : thermo constraint NOT created
DEBUG:thermomodel_None:H2Otcx : thermo constraint NOT created
DEBUG:thermomodel_None:GLNTRS : thermo constraint NOT created
DEBUG:thermomodel_None:TYRTRS : thermo constraint NOT created
DEBUG:thermomodel_None:METTRS : thermo constraint NOT created
DEBUG:thermomodel_None:SERTRS : thermo constraint NOT created
DEBUG:thermomodel_None:GLYTRS : thermo constraint NOT created
DEBUG:thermomodel_None:PROTRS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ARGTRS : thermo constraint NOT created
DEBUG:thermomodel_None:TRPTRS : thermo constraint NOT created
DEBUG:thermomodel_None:PHETRS : thermo constraint NOT created
DEBUG:thermomodel_None:HISTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ASPTRS : thermo constraint NOT created
DEBUG:thermomodel_None:THRTRS : thermo constraint NOT created
DEBUG:thermomodel_None:LEUTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ILETRS : thermo constraint NOT created
DEBUG:thermomodel_None:LYSTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ALATRS : thermo constraint NOT created
DEBUG:thermomodel_None:VALTRS : thermo constraint NOT created
DEBUG:thermomodel_None:FMETTRS : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon410_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon430_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon450_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon470_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon490_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon510_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon530_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon550_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon570_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon590_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon610_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon630_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon650_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon670_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_photon690_e : thermo constraint NOT created
DEBUG:thermomodel_None:ZXANHX : thermo constraint NOT created
DEBUG:thermomodel_None:CXANHX : thermo constraint NOT created
DEBUG:thermomodel_None:PHOA690um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_pho_loss_c : thermo constraint NOT created
DEBUG:thermomodel_None:A5PISO : thermo constraint NOT created
DEBUG:thermomodel_None:KDOPS : thermo constraint NOT created
DEBUG:thermomodel_None:KDOPP : thermo constraint NOT created
DEBUG:thermomodel_None:KDOCT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UAG2E : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAMT : thermo constraint NOT created
DEBUG:thermomodel_None:ACMAMT : thermo constraint NOT created
DEBUG:thermomodel_None:ICLIPAS : thermo constraint NOT created
DEBUG:thermomodel_None:ICLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OANTS : thermo constraint NOT created
DEBUG:thermomodel_None:OANTIabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OANTILpp : thermo constraint NOT created
DEBUG:thermomodel_None:COLIPAabcex : thermo constraint NOT created
DEBUG:thermomodel_None:MPTG : thermo constraint NOT created
DEBUG:thermomodel_None:MPTG2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDEP4pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTGY4pp : thermo constraint NOT created
DEBUG:thermomodel_None:UM4PL : thermo constraint NOT created
DEBUG:thermomodel_None:ALAGLUE : thermo constraint NOT created
DEBUG:thermomodel_None:UM3PL : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:4PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:UAGPT3 : thermo constraint NOT created
DEBUG:thermomodel_None:UDCPDP : thermo constraint NOT created
DEBUG:thermomodel_None:PAPPT3 : thermo constraint NOT created
DEBUG:thermomodel_None:ALAALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PCHLDA430 : thermo constraint NOT created
DEBUG:thermomodel_None:PCHLDA650 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_meoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:PFOR : thermo constraint NOT created
DEBUG:thermomodel_None:NO2tabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:Htabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PSICSum : thermo constraint NOT created
DEBUG:thermomodel_None:PSIICSum : thermo constraint NOT created
DEBUG:thermomodel_None:FALDH2 : thermo constraint NOT created
DEBUG:thermomodel_None:SFGTHi : thermo constraint NOT created
DEBUG:thermomodel_None:GGCLUT2 : thermo constraint NOT created
DEBUG:thermomodel_None:OPAH : thermo constraint NOT created
DEBUG:thermomodel_None:ANHMK : thermo constraint NOT created
DEBUG:thermomodel_None:CLt3_1pp : thermo constraint NOT created
DEBUG:thermomodel_None:CLtex : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cl_e : thermo constraint NOT created
DEBUG:thermomodel_None:Ktu : thermo constraint NOT created
DEBUG:thermomodel_None:SK_fum_c : thermo constraint NOT created
DEBUG:thermomodel_None:DM_succ_c : thermo constraint NOT created
DEBUG:thermomodel_None:SK_akg_c : thermo constraint NOT created
DEBUG:thermomodel_None:NGAM_D1um : thermo constraint NOT created
DEBUG:thermomodel_None:DM_ac_c : thermo constraint NOT created
DEBUG:thermomodel_None:DM_lac__D_c : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO5 : thermo constraint NOT created
DEBUG:thermomodel_None:MNHNAtpp : thermo constraint NOT created
DEBUG:thermomodel_None:PCXHtpp : thermo constraint NOT created
DEBUG:thermomodel_None:34DHOXPEGOX : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD121 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD141 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD161 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD181 : thermo constraint NOT created
DEBUG:thermomodel_None:3HAD40 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR121 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR141 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR161 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR181 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAR40 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS121 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS141 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS161 : thermo constraint NOT created
DEBUG:thermomodel_None:3OAS181 : thermo constraint NOT created
DEBUG:thermomodel_None:AACOAR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:ABTA : thermo constraint NOT created
DEBUG:thermomodel_None:ABUTD : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT1r : thermo constraint NOT created
DEBUG:thermomodel_None:ACHBS : thermo constraint NOT created
DEBUG:thermomodel_None:ACLS : thermo constraint NOT created
DEBUG:thermomodel_None:ACP1_FMN : thermo constraint NOT created
DEBUG:thermomodel_None:ADCPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:ADPT2 : thermo constraint NOT created
DEBUG:thermomodel_None:AGTi : thermo constraint NOT created
DEBUG:thermomodel_None:AHMMPS : thermo constraint NOT created
DEBUG:thermomodel_None:AIRCr : thermo constraint NOT created
DEBUG:thermomodel_None:ALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD19 : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2y : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD20x : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD2x : thermo constraint NOT created
DEBUG:thermomodel_None:AMID : thermo constraint NOT created
DEBUG:thermomodel_None:AMID2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMID3 : thermo constraint NOT created
DEBUG:thermomodel_None:AOXSr : thermo constraint NOT created
DEBUG:thermomodel_None:ATPSu : thermo constraint NOT created
DEBUG:thermomodel_None:BAMPPALDOX : thermo constraint NOT created
DEBUG:thermomodel_None:BCAROKE : thermo constraint NOT created
DEBUG:thermomodel_None:BTS4 : thermo constraint NOT created
DEBUG:thermomodel_None:CBFC2 : thermo constraint NOT created
DEBUG:thermomodel_None:CBFC2pp : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBFCu : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:COCHL : thermo constraint NOT created
DEBUG:thermomodel_None:CTPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:CU2abcu_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYNTAH : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b2_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b2pp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1b_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1bpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:CYSS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSTA : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBDpp_1 : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBDu : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN160 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN161 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN180 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN181 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:DASYN184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:DHDPS : thermo constraint NOT created
DEBUG:thermomodel_None:DHORDi : thermo constraint NOT created
DEBUG:thermomodel_None:DPPS : thermo constraint NOT created
DEBUG:thermomodel_None:EAR121y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR141y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR161y : thermo constraint NOT created
DEBUG:thermomodel_None:EAR181y : thermo constraint NOT created
DEBUG:thermomodel_None:FBA2 : thermo constraint NOT created
DEBUG:thermomodel_None:FMNAT : thermo constraint NOT created
DEBUG:thermomodel_None:FNOR : thermo constraint NOT created
DEBUG:thermomodel_None:FOMETRi : thermo constraint NOT created
DEBUG:thermomodel_None:G1PTT : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:G3PAT184_6_9_12_15 : thermo constraint NOT created

Warning : Z/Z
Warning : Z/Z
Warning : Z/Z

DEBUG:thermomodel_None:GLYK : thermo constraint NOT created
DEBUG:thermomodel_None:GLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:GMPS : thermo constraint NOT created
DEBUG:thermomodel_None:GUACYC : thermo constraint NOT created
DEBUG:thermomodel_None:H2ASE_syn : thermo constraint NOT created
DEBUG:thermomodel_None:HCO3E : thermo constraint NOT created
DEBUG:thermomodel_None:HIBDkt : thermo constraint NOT created
DEBUG:thermomodel_None:HISabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:HOXG : thermo constraint NOT created
DEBUG:thermomodel_None:HPROa : thermo constraint NOT created
DEBUG:thermomodel_None:HPYRRx : thermo constraint NOT created
DEBUG:thermomodel_None:HSDxi : thermo constraint NOT created
DEBUG:thermomodel_None:IMACTD : thermo constraint NOT created
DEBUG:thermomodel_None:KARA2 : thermo constraint NOT created
DEBUG:thermomodel_None:LALDO : thermo constraint NOT created
DEBUG:thermomodel_None:LCARS : thermo constraint NOT created
DEBUG:thermomodel_None:LGTHL : thermo constraint NOT created
DEBUG:thermomodel_None:LYSDC : thermo constraint NOT created
DEBUG:thermomodel_None:LYSabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MAN1PT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDH : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDH_syn : thermo constraint NOT created
DEBUG:thermomodel_None:METS : thermo constraint NOT created
DEBUG:thermomodel_None:MI1PP : thermo constraint NOT created
DEBUG:thermomodel_None:MI1PS : thermo constraint NOT created
DEBUG:thermomodel_None:MNt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMC1 : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMOR : thermo constraint NOT created
DEBUG:thermomodel_None:MPOMT : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFD2i : thermo constraint NOT created
DEBUG:thermomodel_None:NABTNO : thermo constraint NOT created
DEBUG:thermomodel_None:NADH5 : thermo constraint NOT created
DEBUG:thermomodel_None:NAR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_1p : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_1u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_2p : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_2u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_3u : thermo constraint NOT created
DEBUG:thermomodel_None:NDH1_4pp : thermo constraint NOT created
DEBUG:thermomodel_None:NDH2_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK10 : thermo constraint NOT created
DEBUG:thermomodel_None:NDPK9 : thermo constraint NOT created
DEBUG:thermomodel_None:NH4tpp_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NOR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:NPHS : thermo constraint NOT created
DEBUG:thermomodel_None:NTD4 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP4 : thermo constraint NOT created
DEBUG:thermomodel_None:OPHBDC : thermo constraint NOT created
DEBUG:thermomodel_None:P5CD : thermo constraint NOT created
DEBUG:thermomodel_None:P5CRx : thermo constraint NOT created
DEBUG:thermomodel_None:PC17M : thermo constraint NOT created
DEBUG:thermomodel_None:PDHa : thermo constraint NOT created
DEBUG:thermomodel_None:PDHbr : thermo constraint NOT created
DEBUG:thermomodel_None:PDHcr : thermo constraint NOT created
DEBUG:thermomodel_None:PDX5PS : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA161 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA180 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA181 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:PHCD : thermo constraint NOT created
DEBUG:thermomodel_None:PHYTES2 : thermo constraint NOT created
DEBUG:thermomodel_None:POR_1 : thermo constraint NOT created
DEBUG:thermomodel_None:POR_syn : thermo constraint NOT created
DEBUG:thermomodel_None:PPC : thermo constraint NOT created
DEBUG:thermomodel_None:PPM : thermo constraint NOT created
DEBUG:thermomodel_None:PPNCL : thermo constraint NOT created
DEBUG:thermomodel_None:PPPGO : thermo constraint NOT created
DEBUG:thermomodel_None:PROD2 : thermo constraint NOT created
DEBUG:thermomodel_None:PROabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PUTA3 : thermo constraint NOT created
DEBUG:thermomodel_None:PYAM5PO : thermo constraint NOT created
DEBUG:thermomodel_None:PYDXNO : thermo constraint NOT created
DEBUG:thermomodel_None:PYDXO : thermo constraint NOT created
DEBUG:thermomodel_None:PYK2 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK3 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK4 : thermo constraint NOT created
DEBUG:thermomodel_None:PYK5 : thermo constraint NOT created
DEBUG:thermomodel_None:R05224_1 : thermo constraint NOT created
DEBUG:thermomodel_None:RBCh : thermo constraint NOT created
DEBUG:thermomodel_None:RBFSb : thermo constraint NOT created
DEBUG:thermomodel_None:RBPC : thermo constraint NOT created
DEBUG:thermomodel_None:SDPTA : thermo constraint NOT created
DEBUG:thermomodel_None:SERD_L : thermo constraint NOT created
DEBUG:thermomodel_None:SERabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SPS : thermo constraint NOT created
DEBUG:thermomodel_None:SPT_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_160 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_161 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_180 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_181 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_181_9 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_182_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_183_6_9_12 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_183_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:SQD2_184_6_9_12_15 : thermo constraint NOT created
DEBUG:thermomodel_None:SQLC : thermo constraint NOT created
DEBUG:thermomodel_None:SQLC2 : thermo constraint NOT created
DEBUG:thermomodel_None:SSALy : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDu_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:SUCRabcpp_syn : thermo constraint NOT created
DEBUG:thermomodel_None:TDPDRR : thermo constraint NOT created
DEBUG:thermomodel_None:TDPGDH : thermo constraint NOT created
DEBUG:thermomodel_None:THFGLUS : thermo constraint NOT created
DEBUG:thermomodel_None:THRD_L : thermo constraint NOT created
DEBUG:thermomodel_None:THZPSN : thermo constraint NOT created
DEBUG:thermomodel_None:THZSN_1 : thermo constraint NOT created
DEBUG:thermomodel_None:TRSARr : thermo constraint NOT created
DEBUG:thermomodel_None:U23GAAT : thermo constraint NOT created
DEBUG:thermomodel_None:UAGAAT : thermo constraint NOT created
DEBUG:thermomodel_None:UDPDPS : thermo constraint NOT created
DEBUG:thermomodel_None:UGLDDS2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UHGADA : thermo constraint NOT created
DEBUG:thermomodel_None:UPPDC2 : thermo constraint NOT created
DEBUG:thermomodel_None:ZN2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_n2_e : thermo constraint NOT created
DEBUG:thermomodel_None:NIT1b : thermo constraint NOT created
DEBUG:thermomodel_None:NADFADOR : thermo constraint NOT created
DEBUG:thermomodel_None:RNF : thermo constraint NOT created
DEBUG:thermomodel_None:14GLUCANabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:23DOGULNt4pp : thermo constraint NOT created
DEBUG:thermomodel_None:2DDARAA : thermo constraint NOT created
DEBUG:thermomodel_None:2DGLCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRGx : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRGy : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRx : thermo constraint NOT created
DEBUG:thermomodel_None:2DGULRy : thermo constraint NOT created
DEBUG:thermomodel_None:2DOXG6PP : thermo constraint NOT created
DEBUG:thermomodel_None:2HESR : thermo constraint NOT created
DEBUG:thermomodel_None:2HPTCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:3AMACHYD : thermo constraint NOT created
DEBUG:thermomodel_None:3HPADHi : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_None:3NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_None:3OXCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:3PEPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:3SLAR : thermo constraint NOT created
DEBUG:thermomodel_None:4ABZGLUH : thermo constraint NOT created
DEBUG:thermomodel_None:4HTHRA : thermo constraint NOT created
DEBUG:thermomodel_None:4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_None:5DGLCNR : thermo constraint NOT created
DEBUG:thermomodel_None:5DKGR : thermo constraint NOT created
DEBUG:thermomodel_None:6D6SFK : thermo constraint NOT created
DEBUG:thermomodel_None:AAMYLpp : thermo constraint NOT created
DEBUG:thermomodel_None:ACACCT : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT2r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT3r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT4r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT5r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT6r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT7r : thermo constraint NOT created
DEBUG:thermomodel_None:ACACT8r : thermo constraint NOT created
DEBUG:thermomodel_None:ACALD : thermo constraint NOT created
DEBUG:thermomodel_None:ACCOAL : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACMANAptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACMUMptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ACNML : thermo constraint NOT created
DEBUG:thermomodel_None:ACOAD1fr : thermo constraint NOT created
DEBUG:thermomodel_None:ACOLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:ACONMT : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_None:ACOXT : thermo constraint NOT created
DEBUG:thermomodel_None:ACP1p : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT140 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPPAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:ACPS1 : thermo constraint NOT created
DEBUG:thermomodel_None:ACt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADK3 : thermo constraint NOT created
DEBUG:thermomodel_None:ADK4 : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBIK : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ADOCBLtonex : thermo constraint NOT created
DEBUG:thermomodel_None:ADPRDP : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3PA : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3PApp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3Pt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PA : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PApp : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PCPpp : thermo constraint NOT created
DEBUG:thermomodel_None:AGMHE : thermo constraint NOT created
DEBUG:thermomodel_None:AGMt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:AGPR : thermo constraint NOT created
DEBUG:thermomodel_None:AGt3 : thermo constraint NOT created
DEBUG:thermomodel_None:AHGDx : thermo constraint NOT created
DEBUG:thermomodel_None:AI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_None:AKGt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALATA_L : thermo constraint NOT created
DEBUG:thermomodel_None:ALATA_L2 : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD19xr : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD3y : thermo constraint NOT created
DEBUG:thermomodel_None:ALKP : thermo constraint NOT created
DEBUG:thermomodel_None:ALLPI : thermo constraint NOT created
DEBUG:thermomodel_None:ALLTN : thermo constraint NOT created
DEBUG:thermomodel_None:ALLULPE : thermo constraint NOT created
DEBUG:thermomodel_None:ALLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALPATE160pp : thermo constraint NOT created
DEBUG:thermomodel_None:ALPATG160pp : thermo constraint NOT created
DEBUG:thermomodel_None:ALR2 : thermo constraint NOT created
DEBUG:thermomodel_None:ALR2x : thermo constraint NOT created
DEBUG:thermomodel_None:AM3PA : thermo constraint NOT created
DEBUG:thermomodel_None:AM4PA : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT1 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT3 : thermo constraint NOT created
DEBUG:thermomodel_None:AMALT4 : thermo constraint NOT created
DEBUG:thermomodel_None:AMMQLT8 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPMS2 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPTASEPG : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT140 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT160 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT180 : thermo constraint NOT created
DEBUG:thermomodel_None:APG3PAT181 : thermo constraint NOT created
DEBUG:thermomodel_None:ARBTNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARBabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARGDC : thermo constraint NOT created
DEBUG:thermomodel_None:ARHGDx : thermo constraint NOT created
DEBUG:thermomodel_None:ARMEPNS : thermo constraint NOT created
DEBUG:thermomodel_None:ASCBptspp : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO3 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPO4 : thermo constraint NOT created
DEBUG:thermomodel_None:ASPT : thermo constraint NOT created
DEBUG:thermomodel_None:ASPabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ASR : thermo constraint NOT created
DEBUG:thermomodel_None:ATHRDHr : thermo constraint NOT created
DEBUG:thermomodel_None:BETALDHx : thermo constraint NOT created
DEBUG:thermomodel_None:BETALDHy : thermo constraint NOT created
DEBUG:thermomodel_None:BGLA1 : thermo constraint NOT created
DEBUG:thermomodel_None:BMOCOS : thermo constraint NOT created
DEBUG:thermomodel_None:BMOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_None:BMOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_None:BTS5 : thermo constraint NOT created
DEBUG:thermomodel_None:BUTCT : thermo constraint NOT created
DEBUG:thermomodel_None:BUTSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOGDS1 : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOGDS2 : thermo constraint NOT created
DEBUG:thermomodel_None:BWCOS : thermo constraint NOT created
DEBUG:thermomodel_None:CA2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:CBIAT : thermo constraint NOT created
DEBUG:thermomodel_None:CBItonex : thermo constraint NOT created
DEBUG:thermomodel_None:CBIuabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBL1abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CBL1tonex : thermo constraint NOT created
DEBUG:thermomodel_None:CBLAT : thermo constraint NOT created
DEBUG:thermomodel_None:CD2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CD2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:CDGUNPD : thermo constraint NOT created
DEBUG:thermomodel_None:CELBpts : thermo constraint NOT created
DEBUG:thermomodel_None:CFAS160E : thermo constraint NOT created
DEBUG:thermomodel_None:CFAS160G : thermo constraint NOT created
DEBUG:thermomodel_None:CFAS180E : thermo constraint NOT created
DEBUG:thermomodel_None:CFAS180G : thermo constraint NOT created
DEBUG:thermomodel_None:CGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CHLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CHLt3pp : thermo constraint NOT created
DEBUG:thermomodel_None:CHOLD : thermo constraint NOT created
DEBUG:thermomodel_None:CHOLID : thermo constraint NOT created
DEBUG:thermomodel_None:CHTBSptspp : thermo constraint NOT created
DEBUG:thermomodel_None:CINNDO : thermo constraint NOT created
DEBUG:thermomodel_None:CITL : thermo constraint NOT created
DEBUG:thermomodel_None:CLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:CMtpp : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:COBALT2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:COLIPAPabctex : thermo constraint NOT created
DEBUG:thermomodel_None:COLIPAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:CPGNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CPGNtonex : thermo constraint NOT created
DEBUG:thermomodel_None:CPH4S : thermo constraint NOT created
DEBUG:thermomodel_None:CPL : thermo constraint NOT created
DEBUG:thermomodel_None:CPMPS : thermo constraint NOT created
DEBUG:thermomodel_None:CRNCAL2 : thermo constraint NOT created
DEBUG:thermomodel_None:CRNCAR : thermo constraint NOT created
DEBUG:thermomodel_None:CRNCDH : thermo constraint NOT created
DEBUG:thermomodel_None:CRNDCAL2 : thermo constraint NOT created
DEBUG:thermomodel_None:CRNDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CRNDt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:CRNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CRNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:CTBTCAL2 : thermo constraint NOT created
DEBUG:thermomodel_None:CTBTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CTBTt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:CTECOAI6 : thermo constraint NOT created
DEBUG:thermomodel_None:CTECOAI7 : thermo constraint NOT created
DEBUG:thermomodel_None:CTECOAI8 : thermo constraint NOT created
DEBUG:thermomodel_None:CU1abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CU2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:CURR : thermo constraint NOT created
DEBUG:thermomodel_None:CUt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:CUt3 : thermo constraint NOT created
DEBUG:thermomodel_None:CYANST : thermo constraint NOT created
DEBUG:thermomodel_None:CYANSTpp : thermo constraint NOT created
DEBUG:thermomodel_None:CYSDDS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSDS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSSADS : thermo constraint NOT created
DEBUG:thermomodel_None:CYSTL : thermo constraint NOT created

Warning : F/F
Warning : F/F

DEBUG:thermomodel_None:LPLIPAL2A160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2A181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATE181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2ATG181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2E181 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G120 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G140 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G141 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G160 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G161 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G180 : thermo constraint NOT created
DEBUG:thermomodel_None:LPLIPAL2G181 : thermo constraint NOT created
DEBUG:thermomodel_None:LSERDHr : thermo constraint NOT created
DEBUG:thermomodel_None:LYSAM : thermo constraint NOT created
DEBUG:thermomodel_None:L_LACD2 : thermo constraint NOT created
DEBUG:thermomodel_None:L_LACD3 : thermo constraint NOT created
DEBUG:thermomodel_None:MACPD : thermo constraint NOT created
DEBUG:thermomodel_None:MALDDH : thermo constraint NOT created
DEBUG:thermomodel_None:MALS : thermo constraint NOT created
DEBUG:thermomodel_None:MALTATr : thermo constraint NOT created
DEBUG:thermomodel_None:MALTHXabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTPTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTTTRabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MALTptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MANGLYCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MANptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MCITL2 : thermo constraint NOT created
DEBUG:thermomodel_None:MCPST : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP1App : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MCTP2App : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP4pp : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP5pp : thermo constraint NOT created
DEBUG:thermomodel_None:MECDPDH5 : thermo constraint NOT created
DEBUG:thermomodel_None:MEPNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:METDabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:METNA : thermo constraint NOT created
DEBUG:thermomodel_None:METSOXR1 : thermo constraint NOT created
DEBUG:thermomodel_None:METSOXR2 : thermo constraint NOT created
DEBUG:thermomodel_None:METabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MG2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:MICITDr : thermo constraint NOT created
DEBUG:thermomodel_None:MINCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP1App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP1Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP2App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP2Bpp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDCP3App : thermo constraint NOT created
DEBUG:thermomodel_None:MLDEP1pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLDEP2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP2 : thermo constraint NOT created
DEBUG:thermomodel_None:MLTP3 : thermo constraint NOT created
DEBUG:thermomodel_None:MMCD : thermo constraint NOT created
DEBUG:thermomodel_None:MMM : thermo constraint NOT created
DEBUG:thermomodel_None:MN2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:MN2tipp : thermo constraint NOT created
DEBUG:thermomodel_None:MN6PP : thermo constraint NOT created
DEBUG:thermomodel_None:MNLptspp : thermo constraint NOT created
DEBUG:thermomodel_None:MOADSUx : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT : thermo constraint NOT created
DEBUG:thermomodel_None:MOAT2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOCOS : thermo constraint NOT created
DEBUG:thermomodel_None:MOGDS : thermo constraint NOT created
DEBUG:thermomodel_None:MPTS : thermo constraint NOT created
DEBUG:thermomodel_None:MPTSS : thermo constraint NOT created
DEBUG:thermomodel_None:MSAR : thermo constraint NOT created
DEBUG:thermomodel_None:MSO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADDP : thermo constraint NOT created
DEBUG:thermomodel_None:NADH10 : thermo constraint NOT created
DEBUG:thermomodel_None:NADH16pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH17pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH18pp : thermo constraint NOT created
DEBUG:thermomodel_None:NADH9 : thermo constraint NOT created
DEBUG:thermomodel_None:NADHHR : thermo constraint NOT created
DEBUG:thermomodel_None:NADHHS : thermo constraint NOT created
DEBUG:thermomodel_None:NADHPO : thermo constraint NOT created
DEBUG:thermomodel_None:NADHXD : thermo constraint NOT created
DEBUG:thermomodel_None:NADHXE : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHHR : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHHS : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHXD : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHXE : thermo constraint NOT created
DEBUG:thermomodel_None:NHFRBO : thermo constraint NOT created
DEBUG:thermomodel_None:NI2abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:NI2t3pp : thermo constraint NOT created
DEBUG:thermomodel_None:NI2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO2t2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO3R1bpp : thermo constraint NOT created
DEBUG:thermomodel_None:NO3R2bpp : thermo constraint NOT created
DEBUG:thermomodel_None:NODOx : thermo constraint NOT created
DEBUG:thermomodel_None:NODOy : thermo constraint NOT created
DEBUG:thermomodel_None:NOVBCNtpp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD11 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD12 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD2 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD4pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD7pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD8 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD9 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD9pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTP5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP10 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP11 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP3 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP5 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP6 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP7 : thermo constraint NOT created
DEBUG:thermomodel_None:NTPP9 : thermo constraint NOT created
DEBUG:thermomodel_None:NTRIR2x : thermo constraint NOT created
DEBUG:thermomodel_None:O16A4COLIPAabctex : thermo constraint NOT created
DEBUG:thermomodel_None:O16AT : thermo constraint NOT created
DEBUG:thermomodel_None:OBTFL : thermo constraint NOT created
DEBUG:thermomodel_None:OCTDPS : thermo constraint NOT created
DEBUG:thermomodel_None:OHPHM : thermo constraint NOT created
DEBUG:thermomodel_None:OMBZLM : thermo constraint NOT created
DEBUG:thermomodel_None:OMMBLHXy : thermo constraint NOT created
DEBUG:thermomodel_None:OMPHHXy : thermo constraint NOT created
DEBUG:thermomodel_None:OPHHXy : thermo constraint NOT created
DEBUG:thermomodel_None:ORNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:OXCOAHDH : thermo constraint NOT created
DEBUG:thermomodel_None:OXDHCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:PA120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PA181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAE : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAL : thermo constraint NOT created
DEBUG:thermomodel_None:PACOAT : thermo constraint NOT created
DEBUG:thermomodel_None:PAI2I : thermo constraint NOT created
DEBUG:thermomodel_None:PAPSR2 : thermo constraint NOT created
DEBUG:thermomodel_None:PCNO : thermo constraint NOT created
DEBUG:thermomodel_None:PDE1 : thermo constraint NOT created
DEBUG:thermomodel_None:PDE4 : thermo constraint NOT created
DEBUG:thermomodel_None:PE120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PE181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PFK : thermo constraint NOT created
DEBUG:thermomodel_None:PFL : thermo constraint NOT created
DEBUG:thermomodel_None:PG120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PG181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP120abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP140abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP141abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP160abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP161abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP180abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGP181abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA120 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA140 : thermo constraint NOT created
DEBUG:thermomodel_None:PGSA141 : thermo constraint NOT created
DEBUG:thermomodel_None:PHEMEabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PNSPA : thermo constraint NOT created
DEBUG:thermomodel_None:POAACR : thermo constraint NOT created
DEBUG:thermomodel_None:POR5 : thermo constraint NOT created
DEBUG:thermomodel_None:POX : thermo constraint NOT created
DEBUG:thermomodel_None:PPA2 : thermo constraint NOT created
DEBUG:thermomodel_None:PPAKr : thermo constraint NOT created
DEBUG:thermomodel_None:PPCK : thermo constraint NOT created
DEBUG:thermomodel_None:PPCSCT : thermo constraint NOT created
DEBUG:thermomodel_None:PPDOy : thermo constraint NOT created
DEBUG:thermomodel_None:PPGPPDP : thermo constraint NOT created
DEBUG:thermomodel_None:PPPNDO : thermo constraint NOT created
DEBUG:thermomodel_None:PPPNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PPTHpp : thermo constraint NOT created
DEBUG:thermomodel_None:PROD3 : thermo constraint NOT created
DEBUG:thermomodel_None:PROGLYabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:PROt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:PSP_Lpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTA2 : thermo constraint NOT created
DEBUG:thermomodel_None:PTHRpp : thermo constraint NOT created
DEBUG:thermomodel_None:PTRCTA : thermo constraint NOT created
DEBUG:thermomodel_None:PUACGAMS : thermo constraint NOT created
DEBUG:thermomodel_None:PUACGAMtr : thermo constraint NOT created
DEBUG:thermomodel_None:PYK6 : thermo constraint NOT created
DEBUG:thermomodel_None:PYROX : thermo constraint NOT created
DEBUG:thermomodel_None:QUINDH : thermo constraint NOT created
DEBUG:thermomodel_None:QUINDHyi : thermo constraint NOT created
DEBUG:thermomodel_None:R15BPK : thermo constraint NOT created
DEBUG:thermomodel_None:R5PP : thermo constraint NOT created
DEBUG:thermomodel_None:R5PPpp : thermo constraint NOT created
DEBUG:thermomodel_None:RBK : thermo constraint NOT created
DEBUG:thermomodel_None:REPHACCOAI : thermo constraint NOT created
DEBUG:thermomodel_None:RFAMPtpp : thermo constraint NOT created
DEBUG:thermomodel_None:RIBabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR1b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR2b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR3b : thermo constraint NOT created
DEBUG:thermomodel_None:RNDR4b : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR1c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR2c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR3c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR4c2 : thermo constraint NOT created
DEBUG:thermomodel_None:RPNTPH : thermo constraint NOT created
DEBUG:thermomodel_None:RU5PP : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SR : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SS : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2SS2 : thermo constraint NOT created
DEBUG:thermomodel_None:S2FE2ST : thermo constraint NOT created
DEBUG:thermomodel_None:S4FE4SR : thermo constraint NOT created
DEBUG:thermomodel_None:S4FE4ST : thermo constraint NOT created
DEBUG:thermomodel_None:SADT2 : thermo constraint NOT created
DEBUG:thermomodel_None:SBTPD : thermo constraint NOT created
DEBUG:thermomodel_None:SBTptspp : thermo constraint NOT created
DEBUG:thermomodel_None:SCYSDS : thermo constraint NOT created
DEBUG:thermomodel_None:SDPDS : thermo constraint NOT created
DEBUG:thermomodel_None:SELabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SGSAD : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHD2 : thermo constraint NOT created
DEBUG:thermomodel_None:SHCHF : thermo constraint NOT created
DEBUG:thermomodel_None:SHSL1 : thermo constraint NOT created
DEBUG:thermomodel_None:SKMt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:SLNTabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SOTA : thermo constraint NOT created
DEBUG:thermomodel_None:SPMDt3pp : thermo constraint NOT created
DEBUG:thermomodel_None:SSALx : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt2_2pp : thermo constraint NOT created
DEBUG:thermomodel_None:SUCptspp : thermo constraint NOT created
DEBUG:thermomodel_None:SULFACabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SULR : thermo constraint NOT created
DEBUG:thermomodel_None:T2DECAI : thermo constraint NOT created
DEBUG:thermomodel_None:TALA : thermo constraint NOT created
DEBUG:thermomodel_None:TARTD : thermo constraint NOT created
DEBUG:thermomodel_None:TAURabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:TDPAGTA : thermo constraint NOT created
DEBUG:thermomodel_None:TDSK : thermo constraint NOT created
DEBUG:thermomodel_None:TGBPA : thermo constraint NOT created
DEBUG:thermomodel_None:THD2pp : thermo constraint NOT created
DEBUG:thermomodel_None:THDPS : thermo constraint NOT created
DEBUG:thermomodel_None:THFAT : thermo constraint NOT created
DEBUG:thermomodel_None:THIORDXi : thermo constraint NOT created
DEBUG:thermomodel_None:THMabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:THRA : thermo constraint NOT created
DEBUG:thermomodel_None:THRA2 : thermo constraint NOT created
DEBUG:thermomodel_None:THRD : thermo constraint NOT created
DEBUG:thermomodel_None:THRabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:THRt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:THZPSN3 : thermo constraint NOT created
DEBUG:thermomodel_None:TMAOR1pp : thermo constraint NOT created
DEBUG:thermomodel_None:TMAOR2pp : thermo constraint NOT created
DEBUG:thermomodel_None:TMDS : thermo constraint NOT created
DEBUG:thermomodel_None:TMPPP : thermo constraint NOT created
DEBUG:thermomodel_None:TPRDCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:TRE6PH : thermo constraint NOT created
DEBUG:thermomodel_None:TRE6PP : thermo constraint NOT created
DEBUG:thermomodel_None:TRE6PS : thermo constraint NOT created
DEBUG:thermomodel_None:TREptspp : thermo constraint NOT created
DEBUG:thermomodel_None:TRPAS2 : thermo constraint NOT created
DEBUG:thermomodel_None:TSULabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:TTRCYCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:TUNGSabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:TYRL : thermo constraint NOT created
DEBUG:thermomodel_None:UACMAMO : thermo constraint NOT created
DEBUG:thermomodel_None:UDCPDPpp : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGDC : thermo constraint NOT created
DEBUG:thermomodel_None:UDPGPT : thermo constraint NOT created
DEBUG:thermomodel_None:UDPKAAT : thermo constraint NOT created
DEBUG:thermomodel_None:ULA4NFT : thermo constraint NOT created
DEBUG:thermomodel_None:UPLA4FNT : thermo constraint NOT created
DEBUG:thermomodel_None:VALTA : thermo constraint NOT created
DEBUG:thermomodel_None:VALabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:WCOS : thermo constraint NOT created
DEBUG:thermomodel_None:XAND : thermo constraint NOT created
DEBUG:thermomodel_None:XPPT : thermo constraint NOT created
DEBUG:thermomodel_None:XYLUt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:XYLabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ZN2t3pp : thermo constraint NOT created

Warning : CrO4/Cr
Warning : CrO4/Cr

DEBUG:thermomodel_None:MOTH4 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS1 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS2 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS3 : thermo constraint NOT created
DEBUG:thermomodel_None:MOTS4 : thermo constraint NOT created
DEBUG:thermomodel_None:MTHFR2_1 : thermo constraint NOT created
DEBUG:thermomodel_None:MTI : thermo constraint NOT created
DEBUG:thermomodel_None:NADHDH : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHQR2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADPHQR3 : thermo constraint NOT created
DEBUG:thermomodel_None:NADS1 : thermo constraint NOT created
DEBUG:thermomodel_None:NAt3_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NFORGLUAH : thermo constraint NOT created
DEBUG:thermomodel_None:NH4t : thermo constraint NOT created
DEBUG:thermomodel_None:NIT1b_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTD5pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTPTP1 : thermo constraint NOT created
DEBUG:thermomodel_None:OCBT_1 : thermo constraint NOT created
DEBUG:thermomodel_None:OCOAT1 : thermo constraint NOT created
DEBUG:thermomodel_None:OOR3r : thermo constraint NOT created
DEBUG:thermomodel_None:OPHHX : thermo constraint NOT created
DEBUG:thermomodel_None:OXOAEL : thermo constraint NOT created
DEBUG:thermomodel_None:OXPTNDH : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAL3 : thermo constraint NOT created
DEBUG:thermomodel_None:PC : thermo constraint NOT created
DEBUG:thermomodel_None:PEPCK_re : thermo constraint NOT created
DEBUG:thermomodel_None:PGK_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC100 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC120 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC121 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC140 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC141 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC60 : thermo constraint NOT created
DEBUG:thermomodel_None:PHAPC80 : thermo constraint NOT created
DEBUG:thermomodel_None:PIabc : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_None:POR : thermo constraint NOT created
DEBUG:thermomodel_None:PPA_1pp : thermo constraint NOT created
DEBUG:thermomodel_None:PPDK : thermo constraint NOT created
DEBUG:thermomodel_None:PPK2r : thermo constraint NOT created
DEBUG:thermomodel_None:PPKr : thermo constraint NOT created
DEBUG:thermomodel_None:PRDX : thermo constraint NOT created
DEBUG:thermomodel_None:PRFGS_1 : thermo constraint NOT created
DEBUG:thermomodel_None:PSD160 : thermo constraint NOT created
DEBUG:thermomodel_None:PSD180 : thermo constraint NOT created
DEBUG:thermomodel_None:PSSA160 : thermo constraint NOT created
DEBUG:thermomodel_None:PSSA180 : thermo constraint NOT created
DEBUG:thermomodel_None:QRr : thermo constraint NOT created
DEBUG:thermomodel_None:QUINtex : thermo constraint NOT created
DEBUG:thermomodel_None:RIBabc : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR1 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR2 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR3 : thermo constraint NOT created
DEBUG:thermomodel_None:RNTR4 : thermo constraint NOT created
DEBUG:thermomodel_None:S7PI : thermo constraint NOT created
DEBUG:thermomodel_None:SALCHS4abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SDPTAi : thermo constraint NOT created
DEBUG:thermomodel_None:SHSL2r : thermo constraint NOT created
DEBUG:thermomodel_None:SO3abcpp : thermo constraint NOT created
DEBUG:thermomodel_None:SUCBZT1 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCBZT2 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCabc : thermo constraint NOT created
DEBUG:thermomodel_None:SUCR : thermo constraint NOT created
DEBUG:thermomodel_None:SULabc : thermo constraint NOT created
DEBUG:thermomodel_None:THD2 : thermo constraint NOT created
DEBUG:thermomodel_None:THRA2i : thermo constraint NOT created
DEBUG:thermomodel_None:THRAi : thermo constraint NOT created
DEBUG:thermomodel_None:THRabc : thermo constraint NOT created
DEBUG:thermomodel_None:TMDPP : thermo constraint NOT created
DEBUG:thermomodel_None:TREabc : thermo constraint NOT created
DEBUG:thermomodel_None:TRPTA : thermo constraint NOT created
DEBUG:thermomodel_None:TSULabc : thermo constraint NOT created
DEBUG:thermomodel_None:TYRt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:USHD : thermo constraint NOT created
DEBUG:thermomodel_None:VALabc : thermo constraint NOT created
DEBUG:thermomodel_None:ZN2t4 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT120 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT141 : thermo constraint NOT created
DEBUG:thermomodel_None:2AGPEAT161 : thermo constraint NOT created
DEBUG:thermomodel_None:4CMLCL_kt : thermo constraint NOT created
DEBUG:thermomodel_None:4HTHRK : thermo constraint NOT created
DEBUG:thermomodel_None:5CM2HMUDI : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAMPM : thermo constraint NOT created
DEBUG:thermomodel_None:AGMtex : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2ir : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD4 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD31_1 : thermo constraint NOT created
DEBUG:thermomodel_None:ALDD6 : thermo constraint NOT created
DEBUG:thermomodel_None:ALR3 : thermo constraint NOT created
DEBUG:thermomodel_None:AMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ANHGMtex : thermo constraint NOT created
DEBUG:thermomodel_None:APENTAMAH : thermo constraint NOT created
DEBUG:thermomodel_None:APTNAT : thermo constraint NOT created
DEBUG:thermomodel_None:ASO3tex : thermo constraint NOT created
DEBUG:thermomodel_None:ASPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ATPHs : thermo constraint NOT created
DEBUG:thermomodel_None:BSCT : thermo constraint NOT created
DEBUG:thermomodel_None:BTS3r : thermo constraint NOT created
DEBUG:thermomodel_None:CITtex : thermo constraint NOT created
DEBUG:thermomodel_None:CLt3_2pp : thermo constraint NOT created
DEBUG:thermomodel_None:CMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:COALCDH : thermo constraint NOT created
DEBUG:thermomodel_None:CONFRLtex : thermo constraint NOT created
DEBUG:thermomodel_None:CONFRLtpp : thermo constraint NOT created
DEBUG:thermomodel_None:CYO1a : thermo constraint NOT created
DEBUG:thermomodel_None:CYOO2pp : thermo constraint NOT created
DEBUG:thermomodel_None:DAMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DAPDA : thermo constraint NOT created
DEBUG:thermomodel_None:DCMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DGMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:DGNSK : thermo constraint NOT created
DEBUG:thermomodel_None:DGSNtex : thermo constraint NOT created
DEBUG:thermomodel_None:DHNAOT : thermo constraint NOT created
DEBUG:thermomodel_None:DKMPPD3 : thermo constraint NOT created
DEBUG:thermomodel_None:DTMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:ECOAH12 : thermo constraint NOT created
DEBUG:thermomodel_None:EDTXS2 : thermo constraint NOT created
DEBUG:thermomodel_None:ETOHtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_12ppd__S_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_2hxmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_3mb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_4hbz_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_4hphac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_agm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ala__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_amp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_anhgm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_arbt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_aso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_aso4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_asp__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_btoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_but_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_buts_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_butso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_bz_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cell4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cell500_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cellb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cgly_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cit_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_confrl_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dad_2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_damp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dca_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dcmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dcyt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dextrin_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dgmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dgsn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_drib_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_dtmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_duri_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_enter_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_eths_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ethso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_feenter_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3pc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_g3ps_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_galct__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glcur_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan1500_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glucan6_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gly_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyb_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc2p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glyc_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gm1lipa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gthox_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gthrd_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2s_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hexs_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_his__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hqn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_hxan_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ibt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_id3acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ile__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_imp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_isetac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_istnt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_kdo2lipid4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lipa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lys__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_madg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_malt_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_malthp_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mbdg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_met__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mso3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4p3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4p4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein4px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p3p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5p5p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_murein5px4px4p_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nmn_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_octa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pdima_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ppa_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pro__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_quin_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_rib__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_rnam_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_s_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_salchs4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_salchs4fe_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sbt__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_skm_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_so3_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sucr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sula_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_sulfac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tartr__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tartr__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_taur_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_thr__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tma_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tmao_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tol_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tre_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tsul_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_udcpo5_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ump_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_urate_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_val__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_vanln_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_xmp_e : thermo constraint NOT created
DEBUG:thermomodel_None:FACOAL160 : thermo constraint NOT created
DEBUG:thermomodel_None:FALGTHLs : thermo constraint NOT created
DEBUG:thermomodel_None:FAS120 : thermo constraint NOT created
DEBUG:thermomodel_None:FAS200 : thermo constraint NOT created
DEBUG:thermomodel_None:FASC200ACP : thermo constraint NOT created
DEBUG:thermomodel_None:FCOAHA : thermo constraint NOT created
DEBUG:thermomodel_None:FOAMtrpp : thermo constraint NOT created
DEBUG:thermomodel_None:FORAMD : thermo constraint NOT created
DEBUG:thermomodel_None:G3PCtex : thermo constraint NOT created
DEBUG:thermomodel_None:G3PItex : thermo constraint NOT created
DEBUG:thermomodel_None:G3PStex : thermo constraint NOT created
DEBUG:thermomodel_None:G6PI : thermo constraint NOT created
DEBUG:thermomodel_None:GCCb : thermo constraint NOT created
DEBUG:thermomodel_None:GCCc : thermo constraint NOT created
DEBUG:thermomodel_None:GLCTR4 : thermo constraint NOT created
DEBUG:thermomodel_None:GLXCBL : thermo constraint NOT created
DEBUG:thermomodel_None:GLYC2Ptex : thermo constraint NOT created
DEBUG:thermomodel_None:GLYCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:GLYtex : thermo constraint NOT created
DEBUG:thermomodel_None:GMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA1 : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA3 : thermo constraint NOT created
DEBUG:thermomodel_None:GPDDA4 : thermo constraint NOT created
DEBUG:thermomodel_None:GTPHs : thermo constraint NOT created
DEBUG:thermomodel_None:H2CO3D : thermo constraint NOT created
DEBUG:thermomodel_None:H2tpp : thermo constraint NOT created
DEBUG:thermomodel_None:HACD8i : thermo constraint NOT created
DEBUG:thermomodel_None:HACD9 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX4 : thermo constraint NOT created
DEBUG:thermomodel_None:HEX7 : thermo constraint NOT created
DEBUG:thermomodel_None:HIStex : thermo constraint NOT created
DEBUG:thermomodel_None:HPAtex : thermo constraint NOT created
DEBUG:thermomodel_None:IMPtex : thermo constraint NOT created
DEBUG:thermomodel_None:KAT1 : thermo constraint NOT created
DEBUG:thermomodel_None:LACD : thermo constraint NOT created
DEBUG:thermomodel_None:LCTStpp : thermo constraint NOT created
DEBUG:thermomodel_None:LPD5 : thermo constraint NOT created
DEBUG:thermomodel_None:LYSMO : thermo constraint NOT created
DEBUG:thermomodel_None:MACCOAT : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP2ex : thermo constraint NOT created
DEBUG:thermomodel_None:MDDCP3ex : thermo constraint NOT created
DEBUG:thermomodel_None:MELIBt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:METOX1s : thermo constraint NOT created
DEBUG:thermomodel_None:METOX2s : thermo constraint NOT created
DEBUG:thermomodel_None:METtex : thermo constraint NOT created
DEBUG:thermomodel_None:MGSA : thermo constraint NOT created
DEBUG:thermomodel_None:MMTSAO : thermo constraint NOT created
DEBUG:thermomodel_None:MOSDC : thermo constraint NOT created
DEBUG:thermomodel_None:MPTAT : thermo constraint NOT created
DEBUG:thermomodel_None:MUCCY_kt : thermo constraint NOT created
DEBUG:thermomodel_None:N2trpp : thermo constraint NOT created
DEBUG:thermomodel_None:NH3c : thermo constraint NOT created
DEBUG:thermomodel_None:NMNAT : thermo constraint NOT created
DEBUG:thermomodel_None:NMNR : thermo constraint NOT created
DEBUG:thermomodel_None:NOVBCNtex : thermo constraint NOT created
DEBUG:thermomodel_None:NT5C : thermo constraint NOT created
DEBUG:thermomodel_None:NTD10pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD11pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD3pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD6pp : thermo constraint NOT created
DEBUG:thermomodel_None:NTD8pp : thermo constraint NOT created
DEBUG:thermomodel_None:OHEDH : thermo constraint NOT created
DEBUG:thermomodel_None:PACCOAL2 : thermo constraint NOT created
DEBUG:thermomodel_None:PHACOAOR : thermo constraint NOT created
DEBUG:thermomodel_None:PLIPA1E120pp : thermo constraint NOT created
DEBUG:thermomodel_None:PLIPA1E141pp : thermo constraint NOT created

Warning : BO3/B
Warning : BO3/B

DEBUG:thermomodel_None:GUI2 : thermo constraint NOT created
DEBUG:thermomodel_None:TAGURr : thermo constraint NOT created
DEBUG:thermomodel_None:ALTRH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_urea_e : thermo constraint NOT created
DEBUG:thermomodel_None:UREAtex : thermo constraint NOT created
DEBUG:thermomodel_None:UREA : thermo constraint NOT created
DEBUG:thermomodel_None:UREASE : thermo constraint NOT created
DEBUG:thermomodel_None:ARGN : thermo constraint NOT created
DEBUG:thermomodel_None:ARGN_1 : thermo constraint NOT created
DEBUG:thermomodel_None:UREAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ASNS1 : thermo constraint NOT created
DEBUG:thermomodel_None:ASNTRS : thermo constraint NOT created
DEBUG:thermomodel_None:ASNS2 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ala__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:DALAtex : thermo constraint NOT created
DEBUG:thermomodel_None:DALAt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:ALAALAR : thermo constraint NOT created
DEBUG:thermomodel_None:DALAabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:ALATA_D2 : thermo constraint NOT created
DEBUG:thermomodel_None:ALAALAD : thermo constraint NOT created
DEBUG:thermomodel_None:EX_acgam_e : thermo constraint NOT created
DEBUG:thermomodel_None:ACGAtex : thermo constraint NOT created
DEBUG:thermomodel_None:AGM4PH : thermo constraint NOT created
DEBUG:thermomodel_None:AGMH : thermo constraint NOT created
DEBUG:thermomodel_None:AGM3PH : thermo constraint NOT created
DEBUG:thermomodel_None:HXAD : thermo constraint NOT created
DEBUG:thermomodel_None:AGDC : thermo constraint NOT created
DEBUG:thermomodel_None:AMANAPEr : thermo constraint NOT created
DEBUG:thermomodel_None:EX_xan_e : thermo constraint NOT created
DEBUG:thermomodel_None:XANtex : thermo constraint NOT created
DEBUG:thermomodel_None:XANt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:XANtpp : thermo constraint NOT created
DEBUG:thermomodel_None:URIC : thermo constraint NOT created
DEBUG:thermomodel_None:ALLTAMH2 : thermo constraint NOT created
DEBUG:thermomodel_None:UGCIAMH : thermo constraint NOT created
DEBUG:thermomodel_None:UGLYCH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_xtsn_e : thermo constraint NOT created
DEBUG:thermomodel_None:XTSNtex : thermo constraint NOT created
DEBUG:thermomodel_None:XTSNH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_alltn_e : thermo constraint NOT created
DEBUG:thermomodel_None:ALLTNtex : thermo constraint NOT created
DEBUG:thermomodel_None:ALLTNt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_arab__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:DARBtex : thermo constraint NOT created
DEBUG:thermomodel_None:DARBt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARABDI : thermo constraint NOT created
DEBUG:thermomodel_None:EX_abt__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:DABtex : thermo constraint NOT created
DEBUG:thermomodel_None:DABt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:DABTD : thermo constraint NOT created
DEBUG:thermomodel_None:EX_abt_e : thermo constraint NOT created
DEBUG:thermomodel_None:LABtex : thermo constraint NOT created
DEBUG:thermomodel_None:LABt2rpp : thermo constraint NOT created
DEBUG:thermomodel_None:ARABR : thermo constraint NOT created
DEBUG:thermomodel_None:DRIBtex : thermo constraint NOT created
DEBUG:thermomodel_None:DRIBtpp : thermo constraint NOT created
DEBUG:thermomodel_None:DRPA : thermo constraint NOT created
DEBUG:thermomodel_None:ARBTtex : thermo constraint NOT created
DEBUG:thermomodel_None:ARBTptspp : thermo constraint NOT created
DEBUG:thermomodel_None:AB6PGH : thermo constraint NOT created
DEBUG:thermomodel_None:sink_hqn_c : thermo constraint NOT created
DEBUG:thermomodel_None:SALCNtex : thermo constraint NOT created
DEBUG:thermomodel_None:SALCtpp : thermo constraint NOT created
DEBUG:thermomodel_None:SALCNH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_salcn_e : thermo constraint NOT created
DEBUG:thermomodel_None:sink_2hymeph_c : thermo constraint NOT created
DEBUG:thermomodel_None:BG_MADG : thermo constraint NOT created
DEBUG:thermomodel_None:BG_MBDG : thermo constraint NOT created
DEBUG:thermomodel_None:EX_metglcur_e : thermo constraint NOT created
DEBUG:thermomodel_None:METGLCURt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:METGLCURtex : thermo constraint NOT created
DEBUG:thermomodel_None:METGLCUR : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pala_e : thermo constraint NOT created
DEBUG:thermomodel_None:PALAtex : thermo constraint NOT created
DEBUG:thermomodel_None:PALAt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:ISOMS : thermo constraint NOT created
DEBUG:thermomodel_None:EX_raffin_e : thermo constraint NOT created
DEBUG:thermomodel_None:RAFFtex : thermo constraint NOT created
DEBUG:thermomodel_None:RAFHpp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_srb__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:SRBtex : thermo constraint NOT created
DEBUG:thermomodel_None:SRBtpp : thermo constraint NOT created
DEBUG:thermomodel_None:SORD_D : thermo constraint NOT created
DEBUG:thermomodel_None:SBTD_D2 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_stys_e : thermo constraint NOT created
DEBUG:thermomodel_None:STYStex : thermo constraint NOT created
DEBUG:thermomodel_None:STYStpp : thermo constraint NOT created
DEBUG:thermomodel_None:STACHGALACT : thermo constraint NOT created
DEBUG:thermomodel_None:RAFGH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_tag__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:TAGtex : thermo constraint NOT created
DEBUG:thermomodel_None:TAGptspp : thermo constraint NOT created
DEBUG:thermomodel_None:TAG1PK : thermo constraint NOT created
DEBUG:thermomodel_None:EX_xylt_e : thermo constraint NOT created
DEBUG:thermomodel_None:XYLTtex : thermo constraint NOT created
DEBUG:thermomodel_None:XYLTtpp : thermo constraint NOT created
DEBUG:thermomodel_None:XYLTD_D : thermo constraint NOT created
DEBUG:thermomodel_None:sink_oxptn_c : thermo constraint NOT created
DEBUG:thermomodel_None:EX_5aptn_e : thermo constraint NOT created
DEBUG:thermomodel_None:5APTNtex : thermo constraint NOT created
DEBUG:thermomodel_None:5APTNabcpp : thermo constraint NOT created
DEBUG:thermomodel_None:sink_2obut_c : thermo constraint NOT created
DEBUG:thermomodel_None:EX_bhb_e : thermo constraint NOT created
DEBUG:thermomodel_None:BHBtex : thermo constraint NOT created
DEBUG:thermomodel_None:BHBt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MALONtex : thermo constraint NOT created
DEBUG:thermomodel_None:MALONt2pp : thermo constraint NOT created
DEBUG:thermomodel_None:MACPT : thermo constraint NOT created
DEBUG:thermomodel_None:EX_malon_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_oxa_e : thermo constraint NOT created
DEBUG:thermomodel_None:OXCDC : thermo constraint NOT created
DEBUG:thermomodel_None:EX_btd_RR_e : thermo constraint NOT created
DEBUG:thermomodel_None:BTDDtex : thermo constraint NOT created
DEBUG:thermomodel_None:BTDDtpp : thermo constraint NOT created
DEBUG:thermomodel_None:BTDD_RR : thermo constraint NOT created
DEBUG:thermomodel_None:ACTD2 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_actn__R_e : thermo constraint NOT created
DEBUG:thermomodel_None:ACTNtex : thermo constraint NOT created
DEBUG:thermomodel_None:ACTNtpp : thermo constraint NOT created
DEBUG:thermomodel_None:Bztex : thermo constraint NOT created
DEBUG:thermomodel_None:BZt1pp : thermo constraint NOT created
DEBUG:thermomodel_None:4HBZtex : thermo constraint NOT created
DEBUG:thermomodel_None:UHBZ1t_pp : thermo constraint NOT created
DEBUG:thermomodel_None:EX_bzf_e : thermo constraint NOT created
DEBUG:thermomodel_None:BZFtex : thermo constraint NOT created
DEBUG:thermomodel_None:BZFpp : thermo constraint NOT created
DEBUG:thermomodel_None:BZFDC : thermo constraint NOT created
DEBUG:thermomodel_None:BZDH : thermo constraint NOT created
DEBUG:thermomodel_None:EX_34dhcinm_e : thermo constraint NOT created
DEBUG:thermomodel_None:34DHCINMtex : thermo constraint NOT created
DEBUG:thermomodel_None:34DHCINMtpp : thermo constraint NOT created
DEBUG:thermomodel_None:CAFFCOA : thermo constraint NOT created
DEBUG:thermomodel_None:CACOAHA : thermo constraint NOT created
DEBUG:thermomodel_None:VNDH_3 : thermo constraint NOT created
DEBUG:thermomodel_None:PCADYOX2 : thermo constraint NOT created
DEBUG:thermomodel_None:4HMSADM : thermo constraint NOT created
DEBUG:thermomodel_None:4CHSOX : thermo constraint NOT created
DEBUG:thermomodel_None:2PDCLH : thermo constraint NOT created
DEBUG:thermomodel_None:4OXATM : thermo constraint NOT created
DEBUG:thermomodel_None:OMAHY : thermo constraint NOT created
DEBUG:thermomodel_None:CINNMtpp : thermo constraint NOT created
DEBUG:thermomodel_None:TCNMM : thermo constraint NOT created
DEBUG:thermomodel_None:2EHP2NOX : thermo constraint NOT created
DEBUG:thermomodel_None:2EDPOX : thermo constraint NOT created
DEBUG:thermomodel_None:H6DH : thermo constraint NOT created
DEBUG:thermomodel_None:OP4ENH : thermo constraint NOT created
DEBUG:thermomodel_None:HOPNTAL : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fer_e : thermo constraint NOT created
DEBUG:thermomodel_None:FERtex : thermo constraint NOT created
DEBUG:thermomodel_None:FERtpp : thermo constraint NOT created
DEBUG:thermomodel_None:VNDH : thermo constraint NOT created
DEBUG:thermomodel_None:VNTDM : thermo constraint NOT created
DEBUG:thermomodel_None:VANLNtex : thermo constraint NOT created
DEBUG:thermomodel_None:EX_3hbz_e : thermo constraint NOT created
DEBUG:thermomodel_None:3HBZtex : thermo constraint NOT created
DEBUG:thermomodel_None:3HBZtpp : thermo constraint NOT created
DEBUG:thermomodel_None:3HBZ4MO : thermo constraint NOT created
DEBUG:thermomodel_None:EX_4hbzf_e : thermo constraint NOT created
DEBUG:thermomodel_None:4HBZFtex : thermo constraint NOT created
DEBUG:thermomodel_None:4HBZFtpp : thermo constraint NOT created
DEBUG:thermomodel_None:4HBZFCL : thermo constraint NOT created
DEBUG:thermomodel_None:VNDH_2 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_T4hcinnm_e : thermo constraint NOT created
DEBUG:thermomodel_None:T4HCINNMtex : thermo constraint NOT created
DEBUG:thermomodel_None:T4HCINNMtpp : thermo constraint NOT created
DEBUG:thermomodel_None:4CMCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:COCOAHA : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mand_e : thermo constraint NOT created
DEBUG:thermomodel_None:MANDtex : thermo constraint NOT created
DEBUG:thermomodel_None:MANDtpp : thermo constraint NOT created
DEBUG:thermomodel_None:2HPA2OX : thermo constraint NOT created
DEBUG:thermomodel_None:EX_coucoa_e : thermo constraint NOT created
DEBUG:thermomodel_None:COUCOAtex : thermo constraint NOT created
DEBUG:thermomodel_None:COUCOAtpp : thermo constraint NOT created
DEBUG:thermomodel_None:PHBS_syn : thermo constraint NOT created
DEBUG:thermomodel_None:SK_phbg_c : thermo constraint NOT created
DEBUG:thermomodel_None:DM_PHB_c : thermo constraint NOT created
DEBUG:thermomodel_None:NITOR : thermo constraint NOT created
DEBUG:thermomodel_None:NTRSA : thermo constraint NOT created
DEBUG:thermomodel_None:GLNS_1 : thermo constraint NOT created
DEBUG:thermomodel_None:NTRNO : thermo constraint NOT created
DEBUG:thermomodel_None:NOFCOR : thermo constraint NOT created
DEBUG:thermomodel_None:NGFCOR : thermo constraint NOT created
DEBUG:thermomodel_None:AHEXASE3 : thermo constraint NOT created
DEBUG:thermomodel_None:EX_cinnm_e : thermo constraint NOT created
DEBUG:thermomodel_None:CINNMtex : thermo constraint NOT created
2026-03-09 19:47:55,834 - thermomodel_None - INFO - # Model preparation done.
INFO:thermomodel_None:# Model preparation done.

# *Lexicon_auto creation

In [19]:
# --- Paths ---
compounds_path = MODELS_DIR / "ModelSEEDDatabase" / "Biochemistry" / "compounds.json"
lexicon_out_path = PHB_MODEL_TFA_DIR / "lexicon_auto.csv"
thermo_path = DATA_DIR / "thermo_data.thermodb"

# --- Load ThermoDB ---
thermo_data = load_thermoDB(thermo_path)

# --- Load ModelSEED compounds ---
with open(compounds_path) as f:
    compounds = json.load(f)

# --- Create mapping from names / BiGG IDs to seed IDs ---
name_to_seed = {}
bigg_to_seed = {}

for c in compounds:
    seed_id = c["id"]

    # Names / synonyms
    names = [c.get("name", "")] + (c.get("aliases") or [])
    for n in names:
        if n:
            n_clean = str(n).strip().lower()
            name_to_seed[n_clean] = seed_id

    # BiGG IDs in aliases
    aliases = c.get("aliases") or []
    for entry in aliases:
        if isinstance(entry, str) and entry.startswith("BiGG:"):
            ids = entry.split(":", 1)[1]
            for bigg in ids.split(";"):
                bigg = bigg.strip().lower()
                if bigg:
                    bigg_to_seed[bigg] = seed_id

# --- Function to strip compartment suffix ---
def strip_compartment(met_id):
    return re.sub(r'_[cepu]$', '', met_id.lower())

# --- Map COBRA model metabolites ---
lexicon_rows = []

for m in cobra_model.metabolites:
    met_id_clean = strip_compartment(m.id)

    # 1. Try BiGG ID mapping
    seed_id = bigg_to_seed.get(met_id_clean)

    # 2. Try metabolite name mapping
    if seed_id is None and hasattr(m, "name"):
        seed_id = name_to_seed.get(m.name.lower())

    # 3. Try stripped metabolite id as fallback
    if seed_id is None:
        seed_id = name_to_seed.get(met_id_clean)

    # 4. If still not found, leave empty
    if seed_id is None:
        seed_id = ""

    lexicon_rows.append({"met_id": m.id, "seed_id": seed_id})

# --- Save lexicon ---
lexicon_df = pd.DataFrame(lexicon_rows)
lexicon_df.to_csv(lexicon_out_path, index=False)

# --- Report coverage ---
mapped = (lexicon_df['seed_id'] != '').sum()
total = len(lexicon_df)
coverage = mapped / total * 100
print(f"Lexicon saved to {lexicon_out_path}")
print(f"Metabolites mapped: {mapped} / {total} ({coverage:.1f}%)")

# --- Filter out empty seed IDs for PyTFA ---
lexicon_df = lexicon_df[lexicon_df['seed_id'] != '']
lexicon_df['seed_id'] = lexicon_df['seed_id'].astype(str)

# --- Check which seed IDs exist in ThermoDB ---
seed_ids_in_thermo = set(map(str, thermo_data['metabolites'].keys()))
missing_in_thermo = set(lexicon_df['seed_id']) - seed_ids_in_thermo

print(f"Number of seed IDs in lexicon not in ThermoDB: {len(missing_in_thermo)}")
if missing_in_thermo:
    print("Some metabolites will not get thermodynamic constraints:")
    print(sorted(list(missing_in_thermo)))

Lexicon saved to /content/drive/MyDrive/metabolic_modelling/phb-optimization-rpalustris/models/phb/tfa/lexicon_auto.csv
Metabolites mapped: 1862 / 2124 (87.7%)
Number of seed IDs in lexicon not in ThermoDB: 118
Some metabolites will not get thermodynamic constraints:
['cpd15465', 'cpd20862', 'cpd20863', 'cpd20921', 'cpd21090', 'cpd21120', 'cpd21184', 'cpd21214', 'cpd21472', 'cpd21479', 'cpd21488', 'cpd22021', 'cpd22061', 'cpd22062', 'cpd22075', 'cpd22076', 'cpd22077', 'cpd22085', 'cpd22119', 'cpd22495', 'cpd22621', 'cpd23280', 'cpd23281', 'cpd23282', 'cpd23828', 'cpd23829', 'cpd24196', 'cpd24423', 'cpd24605', 'cpd24697', 'cpd25615', 'cpd25960', 'cpd26318', 'cpd26385', 'cpd26436', 'cpd26518', 'cpd26527', 'cpd26726', 'cpd26729', 'cpd26805', 'cpd26830', 'cpd26831', 'cpd26836', 'cpd27013', 'cpd27042', 'cpd27103', 'cpd27358', 'cpd27371', 'cpd27379', 'cpd27436', 'cpd27551', 'cpd27563', 'cpd27569', 'cpd27608', 'cpd27735', 'cpd27797', 'cpd27830', 'cpd28023', 'cpd28024', 'cpd28030', 'cpd28060', 'cpd28162', 'cpd28273', 'cpd28275', 'cpd28276', 'cpd28277', 'cpd28378', 'cpd28379', 'cpd28473', 'cpd28786', 'cpd28920', 'cpd29665', 'cpd29666', 'cpd29667', 'cpd29668', 'cpd29669', 'cpd29670', 'cpd29671', 'cpd29672', 'cpd29673', 'cpd29674', 'cpd29675', 'cpd29676', 'cpd29677', 'cpd29678', 'cpd29679', 'cpd29680', 'cpd29681', 'cpd29731', 'cpd29733', 'cpd30034', 'cpd30035', 'cpd30070', 'cpd30071', 'cpd30087', 'cpd30201', 'cpd30236', 'cpd30370', 'cpd30372', 'cpd30403', 'cpd30416', 'cpd30435', 'cpd30437', 'cpd30487', 'cpd30498', 'cpd30505', 'cpd30506', 'cpd30744', 'cpd30760', 'cpd30761', 'cpd31356', 'cpd31397', 'cpd31745', 'cpd33914', 'cpd33930', 'cpd34745', 'cpd37287', 'cpd37289']

In [21]:
# --- Initialize ThermoModel ---
mytfa = ThermoModel(thermo_data, cobra_model)

lexicon = read_lexicon(lexicon_out_path)

# --- Annotate metabolites with lexicon and compartments ---
annotate_from_lexicon(mytfa, lexicon)
apply_compartment_data(mytfa, cobra_model.compartments)

# --- Check annotated metabolites ---
annotated = [m for m in mytfa.metabolites if hasattr(m, "thermo")]
print(f"Metabolites with thermodynamic data: {len(annotated)} / {len(mytfa.metabolites)}")

# --- Prepare TFA model ---
mytfa.prepare()  # Should now fail less, because lexicon filtering removed empty mappings
print("ThermoModel prepared successfully.")

2026-03-16 15:28:07,252 - thermomodel_None - INFO - # Model initialized with units kcal/mol and temperature 298.15 K
INFO:thermomodel_None:# Model initialized with units kcal/mol and temperature 298.15 K
2026-03-16 15:28:07,282 - thermomodel_None - INFO - # Model preparation starting...
INFO:thermomodel_None:# Model preparation starting...

Metabolites with thermodynamic data: 0 / 2124

TypeError: string indices must be integers, not 'str'

In [ ]:
annotated = [m for m in mytfa.metabolites if hasattr(m, "thermo")]
print(f"Metabolites with thermodynamic data: {len(annotated)} / {len(mytfa.metabolites)}")
print([m.id for m in annotated[:20]])  # first 20 for inspection

Metabolites with thermodynamic data: 2124 / 2124
['gam6p_c', 'cgly_c', 'achms_c', 'pcox_u', 'octe9ACP_c', 'fdp_c', '5caiz_c', 'pep_c', 'coa_c', 'hgbam_c', 'nac_c', 'r3mmal_c', 'leu__L_c', 'ahcys_c', 'ru5p__D_c', '14dhncoa_c', 'h2o_cx_c', 'h2s_c', 'orot_c', 'g1p_c']

In [ ]:
cobra_model.metabolites[0].annotation = {
  'SeedID': 'cpd00288'
}

In [ ]:
cobra_model.metabolites[0]

In [ ]:
# Example seed ID
seed_id = "cpd00001"

# Check if it exists in ThermoDB
if seed_id in thermo_data['metabolites']:
    print(f"{seed_id} exists in ThermoDB")
else:
    print(f"{seed_id} NOT found in ThermoDB")

cpd00001 exists in ThermoDB

In [ ]:
# Get metabolite
met = mytfa.metabolites.get_by_id("h2o_c")

# Assign seed ID manually
met.seed_id = "cpd00001"

# Now check ThermoDB
if met.seed_id in thermo_data['metabolites']:
    print(f"{met.id} with seed ID {met.seed_id} exists in ThermoDB")
else:
    print(f"{met.id} with seed ID {met.seed_id} NOT found in ThermoDB")

h2o_c with seed ID cpd00001 exists in ThermoDB

In [ ]:
cobra_model.convert()

2026-03-09 05:59:05,324 - thermomodel_None - INFO - # Model conversion starting...
INFO:thermomodel_None:# Model conversion starting...
DEBUG:thermomodel_None:generating thermo variables for gam6p_c
DEBUG:thermomodel_None:Added variable: LC_gam6p_c
DEBUG:thermomodel_None:generating thermo variables for cgly_c
DEBUG:thermomodel_None:Added variable: LC_cgly_c
DEBUG:thermomodel_None:generating thermo variables for achms_c
DEBUG:thermomodel_None:Added variable: LC_achms_c
DEBUG:thermomodel_None:generating thermo variables for pcox_u
DEBUG:thermomodel_None:Added variable: LC_pcox_u
DEBUG:thermomodel_None:generating thermo variables for octe9ACP_c
DEBUG:thermomodel_None:Added variable: LC_octe9ACP_c
DEBUG:thermomodel_None:generating thermo variables for fdp_c
DEBUG:thermomodel_None:Added variable: LC_fdp_c
DEBUG:thermomodel_None:generating thermo variables for 5caiz_c
DEBUG:thermomodel_None:Added variable: LC_5caiz_c
DEBUG:thermomodel_None:generating thermo variables for pep_c
DEBUG:thermomodel_None:Added variable: LC_pep_c
DEBUG:thermomodel_None:generating thermo variables for coa_c
DEBUG:thermomodel_None:Added variable: LC_coa_c
DEBUG:thermomodel_None:generating thermo variables for hgbam_c
DEBUG:thermomodel_None:Added variable: LC_hgbam_c
DEBUG:thermomodel_None:generating thermo variables for nac_c
DEBUG:thermomodel_None:Added variable: LC_nac_c
DEBUG:thermomodel_None:generating thermo variables for r3mmal_c
DEBUG:thermomodel_None:Added variable: LC_r3mmal_c
DEBUG:thermomodel_None:generating thermo variables for leu__L_c
DEBUG:thermomodel_None:Added variable: LC_leu__L_c
DEBUG:thermomodel_None:generating thermo variables for ahcys_c
DEBUG:thermomodel_None:Added variable: LC_ahcys_c
DEBUG:thermomodel_None:generating thermo variables for ru5p__D_c
DEBUG:thermomodel_None:Added variable: LC_ru5p__D_c
DEBUG:thermomodel_None:generating thermo variables for 14dhncoa_c
DEBUG:thermomodel_None:Added variable: LC_14dhncoa_c
DEBUG:thermomodel_None:Added variable: LC_h2o_cx_c
DEBUG:thermomodel_None:generating thermo variables for h2s_c
DEBUG:thermomodel_None:Added variable: LC_h2s_c
DEBUG:thermomodel_None:generating thermo variables for orot_c
DEBUG:thermomodel_None:Added variable: LC_orot_c
DEBUG:thermomodel_None:generating thermo variables for g1p_c
DEBUG:thermomodel_None:Added variable: LC_g1p_c
DEBUG:thermomodel_None:generating thermo variables for 3hdecACP_c
DEBUG:thermomodel_None:Added variable: LC_3hdecACP_c
DEBUG:thermomodel_None:generating thermo variables for na1_c
DEBUG:thermomodel_None:Added variable: LC_na1_c
DEBUG:thermomodel_None:generating thermo variables for 2pglyc_c
DEBUG:thermomodel_None:Added variable: LC_2pglyc_c
DEBUG:thermomodel_None:generating thermo variables for ala_B_c
DEBUG:thermomodel_None:Added variable: LC_ala_B_c
DEBUG:thermomodel_None:generating thermo variables for glyc3p_c
DEBUG:thermomodel_None:Added variable: LC_glyc3p_c
DEBUG:thermomodel_None:generating thermo variables for pqh2_um_p
DEBUG:thermomodel_None:Added variable: LC_pqh2_um_p
DEBUG:thermomodel_None:generating thermo variables for 26dap_LL_c
DEBUG:thermomodel_None:Added variable: LC_26dap_LL_c
DEBUG:thermomodel_None:generating thermo variables for ddcaACP_c
DEBUG:thermomodel_None:Added variable: LC_ddcaACP_c
DEBUG:thermomodel_None:generating thermo variables for 2pglyc_cx_c
DEBUG:thermomodel_None:Added variable: LC_2pglyc_cx_c
DEBUG:thermomodel_None:generating thermo variables for trdox_c
DEBUG:thermomodel_None:Added variable: LC_trdox_c
DEBUG:thermomodel_None:generating thermo variables for 3oddecACP_c
DEBUG:thermomodel_None:Added variable: LC_3oddecACP_c
DEBUG:thermomodel_None:generating thermo variables for glu__D_c
DEBUG:thermomodel_None:Added variable: LC_glu__D_c
DEBUG:thermomodel_None:Added variable: LC_h_cx_c
DEBUG:thermomodel_None:generating thermo variables for dutp_c
DEBUG:thermomodel_None:Added variable: LC_dutp_c
DEBUG:thermomodel_None:generating thermo variables for paps_c
DEBUG:thermomodel_None:Added variable: LC_paps_c
DEBUG:thermomodel_None:generating thermo variables for mg2_c
DEBUG:thermomodel_None:Added variable: LC_mg2_c
DEBUG:thermomodel_None:generating thermo variables for hdeACP_c
DEBUG:thermomodel_None:Added variable: LC_hdeACP_c
DEBUG:thermomodel_None:generating thermo variables for o2_c
DEBUG:thermomodel_None:Added variable: LC_o2_c
DEBUG:thermomodel_None:generating thermo variables for anth_c
DEBUG:thermomodel_None:Added variable: LC_anth_c
DEBUG:thermomodel_None:generating thermo variables for dhpt_c
DEBUG:thermomodel_None:Added variable: LC_dhpt_c
DEBUG:thermomodel_None:generating thermo variables for thex2eACP_c
DEBUG:thermomodel_None:Added variable: LC_thex2eACP_c
DEBUG:thermomodel_None:generating thermo variables for fmn_c
DEBUG:thermomodel_None:Added variable: LC_fmn_c
DEBUG:thermomodel_None:generating thermo variables for pppi_c
DEBUG:thermomodel_None:Added variable: LC_pppi_c
DEBUG:thermomodel_None:generating thermo variables for udp_c
DEBUG:thermomodel_None:Added variable: LC_udp_c
DEBUG:thermomodel_None:generating thermo variables for cit_c
DEBUG:thermomodel_None:Added variable: LC_cit_c
DEBUG:thermomodel_None:generating thermo variables for acACP_c
DEBUG:thermomodel_None:Added variable: LC_acACP_c
DEBUG:thermomodel_None:generating thermo variables for uama_c
DEBUG:thermomodel_None:Added variable: LC_uama_c
DEBUG:thermomodel_None:generating thermo variables for eig3p_c
DEBUG:thermomodel_None:Added variable: LC_eig3p_c
DEBUG:thermomodel_None:generating thermo variables for 3c4mop_c
DEBUG:thermomodel_None:Added variable: LC_3c4mop_c
DEBUG:thermomodel_None:generating thermo variables for lys__L_c
DEBUG:thermomodel_None:Added variable: LC_lys__L_c
DEBUG:thermomodel_None:generating thermo variables for 13dpg_c
DEBUG:thermomodel_None:Added variable: LC_13dpg_c
DEBUG:thermomodel_None:generating thermo variables for gmp_c
DEBUG:thermomodel_None:Added variable: LC_gmp_c
DEBUG:thermomodel_None:generating thermo variables for utp_c
DEBUG:thermomodel_None:Added variable: LC_utp_c
DEBUG:thermomodel_None:generating thermo variables for trdrd_c
DEBUG:thermomodel_None:Added variable: LC_trdrd_c
DEBUG:thermomodel_None:generating thermo variables for so4_c
DEBUG:thermomodel_None:Added variable: LC_so4_c
DEBUG:thermomodel_None:generating thermo variables for 5apru_c
DEBUG:thermomodel_None:Added variable: LC_5apru_c
DEBUG:thermomodel_None:generating thermo variables for hmppp9_c
DEBUG:thermomodel_None:Added variable: LC_hmppp9_c
DEBUG:thermomodel_None:generating thermo variables for pydx5p_c
DEBUG:thermomodel_None:Added variable: LC_pydx5p_c
DEBUG:thermomodel_None:generating thermo variables for 2dhp_c
DEBUG:thermomodel_None:Added variable: LC_2dhp_c
DEBUG:thermomodel_None:generating thermo variables for ade_c
DEBUG:thermomodel_None:Added variable: LC_ade_c
DEBUG:thermomodel_None:generating thermo variables for asp__L_c
DEBUG:thermomodel_None:Added variable: LC_asp__L_c
DEBUG:thermomodel_None:generating thermo variables for 2sephchc_c
DEBUG:thermomodel_None:Added variable: LC_2sephchc_c
DEBUG:thermomodel_None:generating thermo variables for acg5p_c
DEBUG:thermomodel_None:Added variable: LC_acg5p_c
DEBUG:thermomodel_None:generating thermo variables for gdp_c
DEBUG:thermomodel_None:Added variable: LC_gdp_c
DEBUG:thermomodel_None:generating thermo variables for hgbyr_c
DEBUG:thermomodel_None:Added variable: LC_hgbyr_c
DEBUG:thermomodel_None:generating thermo variables for palmACP_c
DEBUG:thermomodel_None:Added variable: LC_palmACP_c
DEBUG:thermomodel_None:generating thermo variables for pser__L_c
DEBUG:thermomodel_None:Added variable: LC_pser__L_c
DEBUG:thermomodel_None:generating thermo variables for ocACP_c
DEBUG:thermomodel_None:Added variable: LC_ocACP_c
DEBUG:thermomodel_None:generating thermo variables for dttp_c
DEBUG:thermomodel_None:Added variable: LC_dttp_c
DEBUG:thermomodel_None:generating thermo variables for 6pgc_c
DEBUG:thermomodel_None:Added variable: LC_6pgc_c
DEBUG:thermomodel_None:generating thermo variables for gcald_c
DEBUG:thermomodel_None:Added variable: LC_gcald_c
DEBUG:thermomodel_None:generating thermo variables for 2p4c2me_c
DEBUG:thermomodel_None:Added variable: LC_2p4c2me_c
DEBUG:thermomodel_None:generating thermo variables for cmp_c
DEBUG:thermomodel_None:Added variable: LC_cmp_c
DEBUG:thermomodel_None:generating thermo variables for bm_pro_c
DEBUG:thermomodel_None:Added variable: LC_bm_pro_c
DEBUG:thermomodel_None:generating thermo variables for pi_c
DEBUG:thermomodel_None:Added variable: LC_pi_c
DEBUG:thermomodel_None:generating thermo variables for pnto__R_c
DEBUG:thermomodel_None:Added variable: LC_pnto__R_c
DEBUG:thermomodel_None:generating thermo variables for dump_c
DEBUG:thermomodel_None:Added variable: LC_dump_c
DEBUG:thermomodel_None:generating thermo variables for omppp9_c
DEBUG:thermomodel_None:Added variable: LC_omppp9_c
DEBUG:thermomodel_None:generating thermo variables for 23dhmp_c
DEBUG:thermomodel_None:Added variable: LC_23dhmp_c
DEBUG:thermomodel_None:generating thermo variables for gtp_c
DEBUG:thermomodel_None:Added variable: LC_gtp_c
DEBUG:thermomodel_None:generating thermo variables for 4h2oglt_c
DEBUG:thermomodel_None:Added variable: LC_4h2oglt_c
DEBUG:thermomodel_None:generating thermo variables for prfp_c
DEBUG:thermomodel_None:Added variable: LC_prfp_c
DEBUG:thermomodel_None:generating thermo variables for man1p_c
DEBUG:thermomodel_None:Added variable: LC_man1p_c
DEBUG:thermomodel_None:generating thermo variables for dxyl5p_c
DEBUG:thermomodel_None:Added variable: LC_dxyl5p_c
DEBUG:thermomodel_None:generating thermo variables for 3hddecACP_c
DEBUG:thermomodel_None:Added variable: LC_3hddecACP_c
DEBUG:thermomodel_None:generating thermo variables for cu2_c
DEBUG:thermomodel_None:Added variable: LC_cu2_c
DEBUG:thermomodel_None:generating thermo variables for malACP_c
DEBUG:thermomodel_None:Added variable: LC_malACP_c
DEBUG:thermomodel_None:generating thermo variables for 2mahmp_c
DEBUG:thermomodel_None:Added variable: LC_2mahmp_c
DEBUG:thermomodel_None:generating thermo variables for phpyr_c
DEBUG:thermomodel_None:Added variable: LC_phpyr_c
DEBUG:thermomodel_None:generating thermo variables for fe2_c
DEBUG:thermomodel_None:Added variable: LC_fe2_c
DEBUG:thermomodel_None:generating thermo variables for phllqne_c
DEBUG:thermomodel_None:Added variable: LC_phllqne_c
DEBUG:thermomodel_None:generating thermo variables for toct2eACP_c
DEBUG:thermomodel_None:Added variable: LC_toct2eACP_c
DEBUG:thermomodel_None:generating thermo variables for dgdp_c
DEBUG:thermomodel_None:Added variable: LC_dgdp_c
DEBUG:thermomodel_None:generating thermo variables for uaccg_c
DEBUG:thermomodel_None:Added variable: LC_uaccg_c
DEBUG:thermomodel_None:generating thermo variables for acald_c
DEBUG:thermomodel_None:Added variable: LC_acald_c
DEBUG:thermomodel_None:generating thermo variables for o2s_c
DEBUG:thermomodel_None:Added variable: LC_o2s_c
DEBUG:thermomodel_None:generating thermo variables for alac__S_c
DEBUG:thermomodel_None:Added variable: LC_alac__S_c
DEBUG:thermomodel_None:generating thermo variables for 3hmop_c
DEBUG:thermomodel_None:Added variable: LC_3hmop_c
DEBUG:thermomodel_None:generating thermo variables for 4abz_c
DEBUG:thermomodel_None:Added variable: LC_4abz_c
DEBUG:thermomodel_None:generating thermo variables for prbamp_c
DEBUG:thermomodel_None:Added variable: LC_prbamp_c
DEBUG:thermomodel_None:generating thermo variables for ca2_c
DEBUG:thermomodel_None:Added variable: LC_ca2_c
DEBUG:thermomodel_None:generating thermo variables for glyclt_c
DEBUG:thermomodel_None:Added variable: LC_glyclt_c
DEBUG:thermomodel_None:generating thermo variables for butACP_c
DEBUG:thermomodel_None:Added variable: LC_butACP_c
DEBUG:thermomodel_None:generating thermo variables for 4ppcys_c
DEBUG:thermomodel_None:Added variable: LC_4ppcys_c
DEBUG:thermomodel_None:generating thermo variables for udpgal_c
DEBUG:thermomodel_None:Added variable: LC_udpgal_c
DEBUG:thermomodel_None:generating thermo variables for f6p_c
DEBUG:thermomodel_None:Added variable: LC_f6p_c
DEBUG:thermomodel_None:generating thermo variables for lac__D_c
DEBUG:thermomodel_None:Added variable: LC_lac__D_c

KeyboardInterrupt:

In [ ]:
sol = tmodel.optimize()
print("Thermo-FBA objective:", sol.objective_value)

DEBUG:thermomodel_None:'slim_optimize' ((), {}) 71.43 sec

Thermo-FBA objective: 1.0

In [ ]:
import json
from pathlib import Path

# Load ModelSEED compounds
with open(db_path) as f:
    compounds = json.load(f)  # dict keyed by 'cpdXXXX'
    print(compounds)


import pandas as pd

# Load your GEM metabolites
gem_mets = [
    '13dpg_c', '2pg_c', '3pg_c', '6pgc_c', '6pgl_c', 'ac_c', 'ac_e',
    'acald_c', 'acald_e', 'accoa_c', 'acon_C_c', 'actp_c', 'adp_c',
    'akg_c', 'akg_e', 'amp_c', 'atp_c', 'cit_c', 'co2_c', 'co2_e'
]

# Load ModelSEED thermodynamic database (JSON or CSV)
thermobase = pd.read_json(db_path)  # replace with your thermodb path
# Example columns: 'id', 'name', 'formula', 'synonyms'

def map_to_modelseed(gem_mets, gem_met_info, thermobase):
    """
    gem_met_info: dict {met_id: {'name': ..., 'formula': ...}}
    thermobase: pandas DataFrame of ModelSEED compounds
    """
    mapping = {}
    unmatched = []
    for met in gem_mets:
        info = gem_met_info.get(met, {})
        formula = info.get('formula', None)
        name = info.get('name', None)

        # Match by formula first
        candidates = thermobase[thermobase['formula'] == formula]
        if len(candidates) == 1:
            mapping[met] = candidates['id'].values[0]
            continue

        # Match by name / synonym
        candidates = thermobase[
            thermobase['name'].str.lower() == name.lower() |
            thermobase['synonyms'].apply(lambda x: name.lower() in [s.lower() for s in x])
        ]
        if len(candidates) >= 1:
            mapping[met] = candidates['id'].values[0]
        else:
            unmatched.append(met)

    return mapping, unmatched

# Example usage:
# gem_met_info = {met.id: {'name': met.name, 'formula': met.formula} for met in cobra_model.metabolites}
# mapping, unmatched = map_to_modelseed(gem_mets, gem_met_info, thermobase)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
print("Number of metabolites with ΔG° info:", len(tmodel.metabolites))
print("Number of reactions with ΔG° info:", len(tmodel.reactions))

Number of metabolites with ΔG° info: 2128
Number of reactions with ΔG° info: 2739

In [ ]:
tmodel.prepare()  # sets up thermodynamic variables and constraints
tmodel.convert()  # adds thermodynamic constraints to the COBRA model

2025-12-02 18:56:22,544 - thermomodel_None - INFO - # Model preparation starting...
INFO:thermomodel_None:# Model preparation starting...
DEBUG:thermomodel_None:Metabolite 13dpg_c (3-Phospho-D-glyceroyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 2pg_c (D-Glycerate 2-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite 3pg_c (3-Phospho-D-glycerate) has no seed_id
DEBUG:thermomodel_None:Metabolite 6pgc_c (6-Phospho-D-gluconate) has no seed_id
DEBUG:thermomodel_None:Metabolite 6pgl_c (6-phospho-D-glucono-1,5-lactone) has no seed_id
DEBUG:thermomodel_None:Metabolite ac_c (Acetate) has no seed_id
DEBUG:thermomodel_None:Metabolite ac_e (Acetate) has no seed_id
DEBUG:thermomodel_None:Metabolite acald_c (Acetaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite acald_e (Acetaldehyde) has no seed_id
DEBUG:thermomodel_None:Metabolite accoa_c (Acetyl-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite acon_C_c (cis-Aconitate) has no seed_id
DEBUG:thermomodel_None:Metabolite actp_c (Acetyl phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite adp_c (ADP) has no seed_id
DEBUG:thermomodel_None:Metabolite akg_c (2-Oxoglutarate) has no seed_id
DEBUG:thermomodel_None:Metabolite akg_e (2-Oxoglutarate) has no seed_id
DEBUG:thermomodel_None:Metabolite amp_c (AMP) has no seed_id
DEBUG:thermomodel_None:Metabolite atp_c (ATP) has no seed_id
DEBUG:thermomodel_None:Metabolite cit_c (Citrate) has no seed_id
DEBUG:thermomodel_None:Metabolite co2_c (CO2) has no seed_id
DEBUG:thermomodel_None:Metabolite co2_e (CO2) has no seed_id
DEBUG:thermomodel_None:Metabolite coa_c (Coenzyme A) has no seed_id
DEBUG:thermomodel_None:Metabolite dhap_c (Dihydroxyacetone phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite e4p_c (D-Erythrose 4-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite etoh_c (Ethanol) has no seed_id
DEBUG:thermomodel_None:Metabolite etoh_e (Ethanol) has no seed_id
DEBUG:thermomodel_None:Metabolite f6p_c (D-Fructose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite fdp_c (D-Fructose 1,6-bisphosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite for_c (Formate) has no seed_id
DEBUG:thermomodel_None:Metabolite for_e (Formate) has no seed_id
DEBUG:thermomodel_None:Metabolite fru_e (D-Fructose) has no seed_id
DEBUG:thermomodel_None:Metabolite fum_c (Fumarate) has no seed_id
DEBUG:thermomodel_None:Metabolite fum_e (Fumarate) has no seed_id
DEBUG:thermomodel_None:Metabolite g3p_c (Glyceraldehyde 3-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite g6p_c (D-Glucose 6-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite glc__D_e (D-Glucose) has no seed_id
DEBUG:thermomodel_None:Metabolite gln__L_c (L-Glutamine) has no seed_id
DEBUG:thermomodel_None:Metabolite gln__L_e (L-Glutamine) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__L_c (L-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite glu__L_e (L-Glutamate) has no seed_id
DEBUG:thermomodel_None:Metabolite glx_c (Glyoxylate) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_c (H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h2o_e (H2O) has no seed_id
DEBUG:thermomodel_None:Metabolite h_c (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite h_e (H+) has no seed_id
DEBUG:thermomodel_None:Metabolite icit_c (Isocitrate) has no seed_id
DEBUG:thermomodel_None:Metabolite lac__D_c (D-Lactate) has no seed_id
DEBUG:thermomodel_None:Metabolite lac__D_e (D-Lactate) has no seed_id
DEBUG:thermomodel_None:Metabolite mal__L_c (L-Malate) has no seed_id
DEBUG:thermomodel_None:Metabolite mal__L_e (L-Malate) has no seed_id
DEBUG:thermomodel_None:Metabolite nad_c (Nicotinamide adenine dinucleotide) has no seed_id
DEBUG:thermomodel_None:Metabolite nadh_c (Nicotinamide adenine dinucleotide - reduced) has no seed_id
DEBUG:thermomodel_None:Metabolite nadp_c (Nicotinamide adenine dinucleotide phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite nadph_c (Nicotinamide adenine dinucleotide phosphate - reduced) has no seed_id
DEBUG:thermomodel_None:Metabolite nh4_c (Ammonium) has no seed_id
DEBUG:thermomodel_None:Metabolite nh4_e (Ammonium) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_c (O2) has no seed_id
DEBUG:thermomodel_None:Metabolite o2_e (O2) has no seed_id
DEBUG:thermomodel_None:Metabolite oaa_c (Oxaloacetate) has no seed_id
DEBUG:thermomodel_None:Metabolite pep_c (Phosphoenolpyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite pi_c (Phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pi_e (Phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite pyr_c (Pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite pyr_e (Pyruvate) has no seed_id
DEBUG:thermomodel_None:Metabolite q8_c (Ubiquinone-8) has no seed_id
DEBUG:thermomodel_None:Metabolite q8h2_c (Ubiquinol-8) has no seed_id
DEBUG:thermomodel_None:Metabolite r5p_c (alpha-D-Ribose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite ru5p__D_c (D-Ribulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite s7p_c (Sedoheptulose 7-phosphate) has no seed_id
DEBUG:thermomodel_None:Metabolite succ_c (Succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite succ_e (Succinate) has no seed_id
DEBUG:thermomodel_None:Metabolite succoa_c (Succinyl-CoA) has no seed_id
DEBUG:thermomodel_None:Metabolite xu5p__D_c (D-Xylulose 5-phosphate) has no seed_id
DEBUG:thermomodel_None:computing reaction thermodynamic data
DEBUG:thermomodel_None:ACALD : thermo constraint NOT created
DEBUG:thermomodel_None:ACALDt : thermo constraint NOT created
DEBUG:thermomodel_None:ACKr : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTa : thermo constraint NOT created
DEBUG:thermomodel_None:ACONTb : thermo constraint NOT created
DEBUG:thermomodel_None:ACt2r : thermo constraint NOT created
DEBUG:thermomodel_None:ADK1 : thermo constraint NOT created
DEBUG:thermomodel_None:AKGDH : thermo constraint NOT created
DEBUG:thermomodel_None:AKGt2r : thermo constraint NOT created
DEBUG:thermomodel_None:ALCD2x : thermo constraint NOT created
DEBUG:thermomodel_None:ATPM : thermo constraint NOT created
DEBUG:thermomodel_None:ATPS4r : thermo constraint NOT created
DEBUG:thermomodel_None:Biomass_Ecoli_core : thermo constraint NOT created
DEBUG:thermomodel_None:CO2t : thermo constraint NOT created
DEBUG:thermomodel_None:CS : thermo constraint NOT created
DEBUG:thermomodel_None:CYTBD : thermo constraint NOT created
DEBUG:thermomodel_None:D_LACt2 : thermo constraint NOT created
DEBUG:thermomodel_None:ENO : thermo constraint NOT created
DEBUG:thermomodel_None:ETOHt2r : thermo constraint NOT created
DEBUG:thermomodel_None:EX_ac_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_acald_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_akg_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_co2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_etoh_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_for_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fru_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_fum_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glc__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_gln__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_glu__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_h2o_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_lac__D_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_mal__L_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_nh4_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_o2_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pi_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_pyr_e : thermo constraint NOT created
DEBUG:thermomodel_None:EX_succ_e : thermo constraint NOT created
DEBUG:thermomodel_None:FBA : thermo constraint NOT created
DEBUG:thermomodel_None:FBP : thermo constraint NOT created
DEBUG:thermomodel_None:FORt2 : thermo constraint NOT created
DEBUG:thermomodel_None:FORti : thermo constraint NOT created
DEBUG:thermomodel_None:FRD7 : thermo constraint NOT created
DEBUG:thermomodel_None:FRUpts2 : thermo constraint NOT created
DEBUG:thermomodel_None:FUM : thermo constraint NOT created
DEBUG:thermomodel_None:FUMt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:G6PDH2r : thermo constraint NOT created
DEBUG:thermomodel_None:GAPD : thermo constraint NOT created
DEBUG:thermomodel_None:GLCpts : thermo constraint NOT created
DEBUG:thermomodel_None:GLNS : thermo constraint NOT created
DEBUG:thermomodel_None:GLNabc : thermo constraint NOT created
DEBUG:thermomodel_None:GLUDy : thermo constraint NOT created
DEBUG:thermomodel_None:GLUN : thermo constraint NOT created
DEBUG:thermomodel_None:GLUSy : thermo constraint NOT created
DEBUG:thermomodel_None:GLUt2r : thermo constraint NOT created
DEBUG:thermomodel_None:GND : thermo constraint NOT created
DEBUG:thermomodel_None:H2Ot : thermo constraint NOT created
DEBUG:thermomodel_None:ICDHyr : thermo constraint NOT created
DEBUG:thermomodel_None:ICL : thermo constraint NOT created
DEBUG:thermomodel_None:LDH_D : thermo constraint NOT created
DEBUG:thermomodel_None:MALS : thermo constraint NOT created
DEBUG:thermomodel_None:MALt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:MDH : thermo constraint NOT created
DEBUG:thermomodel_None:ME1 : thermo constraint NOT created
DEBUG:thermomodel_None:ME2 : thermo constraint NOT created
DEBUG:thermomodel_None:NADH16 : thermo constraint NOT created
DEBUG:thermomodel_None:NADTRHD : thermo constraint NOT created
DEBUG:thermomodel_None:NH4t : thermo constraint NOT created
DEBUG:thermomodel_None:O2t : thermo constraint NOT created
DEBUG:thermomodel_None:PDH : thermo constraint NOT created
DEBUG:thermomodel_None:PFK : thermo constraint NOT created
DEBUG:thermomodel_None:PFL : thermo constraint NOT created
DEBUG:thermomodel_None:PGI : thermo constraint NOT created
DEBUG:thermomodel_None:PGK : thermo constraint NOT created
DEBUG:thermomodel_None:PGL : thermo constraint NOT created
DEBUG:thermomodel_None:PGM : thermo constraint NOT created
DEBUG:thermomodel_None:PIt2r : thermo constraint NOT created
DEBUG:thermomodel_None:PPC : thermo constraint NOT created
DEBUG:thermomodel_None:PPCK : thermo constraint NOT created
DEBUG:thermomodel_None:PPS : thermo constraint NOT created
DEBUG:thermomodel_None:PTAr : thermo constraint NOT created
DEBUG:thermomodel_None:PYK : thermo constraint NOT created
DEBUG:thermomodel_None:PYRt2 : thermo constraint NOT created
DEBUG:thermomodel_None:RPE : thermo constraint NOT created
DEBUG:thermomodel_None:RPI : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt2_2 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCCt3 : thermo constraint NOT created
DEBUG:thermomodel_None:SUCDi : thermo constraint NOT created
DEBUG:thermomodel_None:SUCOAS : thermo constraint NOT created
DEBUG:thermomodel_None:TALA : thermo constraint NOT created
DEBUG:thermomodel_None:THD2 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT1 : thermo constraint NOT created
DEBUG:thermomodel_None:TKT2 : thermo constraint NOT created
DEBUG:thermomodel_None:TPI : thermo constraint NOT created
2025-12-02 18:56:22,767 - thermomodel_None - INFO - # Model preparation done.
INFO:thermomodel_None:# Model preparation done.
2025-12-02 18:56:22,768 - thermomodel_None - INFO - # Model conversion starting...
INFO:thermomodel_None:# Model conversion starting...
DEBUG:thermomodel_None:generating thermo variables for 13dpg_c
DEBUG:thermomodel_None:Added variable: LC_13dpg_c
DEBUG:thermomodel_None:generating thermo variables for 2pg_c
DEBUG:thermomodel_None:Added variable: LC_2pg_c
DEBUG:thermomodel_None:generating thermo variables for 3pg_c
DEBUG:thermomodel_None:Added variable: LC_3pg_c
DEBUG:thermomodel_None:generating thermo variables for 6pgc_c
DEBUG:thermomodel_None:Added variable: LC_6pgc_c
DEBUG:thermomodel_None:generating thermo variables for 6pgl_c
DEBUG:thermomodel_None:Added variable: LC_6pgl_c
DEBUG:thermomodel_None:generating thermo variables for ac_c
DEBUG:thermomodel_None:Added variable: LC_ac_c
DEBUG:thermomodel_None:generating thermo variables for ac_e
DEBUG:thermomodel_None:Added variable: LC_ac_e
DEBUG:thermomodel_None:generating thermo variables for acald_c
DEBUG:thermomodel_None:Added variable: LC_acald_c
DEBUG:thermomodel_None:generating thermo variables for acald_e
DEBUG:thermomodel_None:Added variable: LC_acald_e
DEBUG:thermomodel_None:generating thermo variables for accoa_c
DEBUG:thermomodel_None:Added variable: LC_accoa_c
DEBUG:thermomodel_None:generating thermo variables for acon_C_c
DEBUG:thermomodel_None:Added variable: LC_acon_C_c
DEBUG:thermomodel_None:generating thermo variables for actp_c
DEBUG:thermomodel_None:Added variable: LC_actp_c
DEBUG:thermomodel_None:generating thermo variables for adp_c
DEBUG:thermomodel_None:Added variable: LC_adp_c
DEBUG:thermomodel_None:generating thermo variables for akg_c
DEBUG:thermomodel_None:Added variable: LC_akg_c
DEBUG:thermomodel_None:generating thermo variables for akg_e
DEBUG:thermomodel_None:Added variable: LC_akg_e
DEBUG:thermomodel_None:generating thermo variables for amp_c
DEBUG:thermomodel_None:Added variable: LC_amp_c
DEBUG:thermomodel_None:generating thermo variables for atp_c
DEBUG:thermomodel_None:Added variable: LC_atp_c
DEBUG:thermomodel_None:generating thermo variables for cit_c
DEBUG:thermomodel_None:Added variable: LC_cit_c
DEBUG:thermomodel_None:generating thermo variables for co2_c
DEBUG:thermomodel_None:Added variable: LC_co2_c
DEBUG:thermomodel_None:generating thermo variables for co2_e
DEBUG:thermomodel_None:Added variable: LC_co2_e
DEBUG:thermomodel_None:generating thermo variables for coa_c
DEBUG:thermomodel_None:Added variable: LC_coa_c
DEBUG:thermomodel_None:generating thermo variables for dhap_c
DEBUG:thermomodel_None:Added variable: LC_dhap_c
DEBUG:thermomodel_None:generating thermo variables for e4p_c
DEBUG:thermomodel_None:Added variable: LC_e4p_c
DEBUG:thermomodel_None:generating thermo variables for etoh_c
DEBUG:thermomodel_None:Added variable: LC_etoh_c
DEBUG:thermomodel_None:generating thermo variables for etoh_e
DEBUG:thermomodel_None:Added variable: LC_etoh_e
DEBUG:thermomodel_None:generating thermo variables for f6p_c
DEBUG:thermomodel_None:Added variable: LC_f6p_c
DEBUG:thermomodel_None:generating thermo variables for fdp_c
DEBUG:thermomodel_None:Added variable: LC_fdp_c
DEBUG:thermomodel_None:generating thermo variables for for_c
DEBUG:thermomodel_None:Added variable: LC_for_c
DEBUG:thermomodel_None:generating thermo variables for for_e
DEBUG:thermomodel_None:Added variable: LC_for_e
DEBUG:thermomodel_None:generating thermo variables for fru_e
DEBUG:thermomodel_None:Added variable: LC_fru_e
DEBUG:thermomodel_None:generating thermo variables for fum_c
DEBUG:thermomodel_None:Added variable: LC_fum_c
DEBUG:thermomodel_None:generating thermo variables for fum_e
DEBUG:thermomodel_None:Added variable: LC_fum_e
DEBUG:thermomodel_None:generating thermo variables for g3p_c
DEBUG:thermomodel_None:Added variable: LC_g3p_c
DEBUG:thermomodel_None:generating thermo variables for g6p_c
DEBUG:thermomodel_None:Added variable: LC_g6p_c
DEBUG:thermomodel_None:generating thermo variables for glc__D_e
DEBUG:thermomodel_None:Added variable: LC_glc__D_e
DEBUG:thermomodel_None:generating thermo variables for gln__L_c
DEBUG:thermomodel_None:Added variable: LC_gln__L_c
DEBUG:thermomodel_None:generating thermo variables for gln__L_e
DEBUG:thermomodel_None:Added variable: LC_gln__L_e
DEBUG:thermomodel_None:generating thermo variables for glu__L_c
DEBUG:thermomodel_None:Added variable: LC_glu__L_c
DEBUG:thermomodel_None:generating thermo variables for glu__L_e
DEBUG:thermomodel_None:Added variable: LC_glu__L_e
DEBUG:thermomodel_None:generating thermo variables for glx_c
DEBUG:thermomodel_None:Added variable: LC_glx_c
DEBUG:thermomodel_None:Added variable: LC_h2o_c
DEBUG:thermomodel_None:Added variable: LC_h2o_e
DEBUG:thermomodel_None:Added variable: LC_h_c
DEBUG:thermomodel_None:Added variable: LC_h_e
DEBUG:thermomodel_None:generating thermo variables for icit_c
DEBUG:thermomodel_None:Added variable: LC_icit_c
DEBUG:thermomodel_None:generating thermo variables for lac__D_c
DEBUG:thermomodel_None:Added variable: LC_lac__D_c
DEBUG:thermomodel_None:generating thermo variables for lac__D_e
DEBUG:thermomodel_None:Added variable: LC_lac__D_e
DEBUG:thermomodel_None:generating thermo variables for mal__L_c
DEBUG:thermomodel_None:Added variable: LC_mal__L_c
DEBUG:thermomodel_None:generating thermo variables for mal__L_e
DEBUG:thermomodel_None:Added variable: LC_mal__L_e
DEBUG:thermomodel_None:generating thermo variables for nad_c
DEBUG:thermomodel_None:Added variable: LC_nad_c
DEBUG:thermomodel_None:generating thermo variables for nadh_c
DEBUG:thermomodel_None:Added variable: LC_nadh_c
DEBUG:thermomodel_None:generating thermo variables for nadp_c
DEBUG:thermomodel_None:Added variable: LC_nadp_c
DEBUG:thermomodel_None:generating thermo variables for nadph_c
DEBUG:thermomodel_None:Added variable: LC_nadph_c
DEBUG:thermomodel_None:generating thermo variables for nh4_c
DEBUG:thermomodel_None:Added variable: LC_nh4_c
DEBUG:thermomodel_None:generating thermo variables for nh4_e
DEBUG:thermomodel_None:Added variable: LC_nh4_e
DEBUG:thermomodel_None:generating thermo variables for o2_c
DEBUG:thermomodel_None:Added variable: LC_o2_c
DEBUG:thermomodel_None:generating thermo variables for o2_e
DEBUG:thermomodel_None:Added variable: LC_o2_e
DEBUG:thermomodel_None:generating thermo variables for oaa_c
DEBUG:thermomodel_None:Added variable: LC_oaa_c
DEBUG:thermomodel_None:generating thermo variables for pep_c
DEBUG:thermomodel_None:Added variable: LC_pep_c
DEBUG:thermomodel_None:generating thermo variables for pi_c
DEBUG:thermomodel_None:Added variable: LC_pi_c
DEBUG:thermomodel_None:generating thermo variables for pi_e
DEBUG:thermomodel_None:Added variable: LC_pi_e
DEBUG:thermomodel_None:generating thermo variables for pyr_c
DEBUG:thermomodel_None:Added variable: LC_pyr_c
DEBUG:thermomodel_None:generating thermo variables for pyr_e
DEBUG:thermomodel_None:Added variable: LC_pyr_e
DEBUG:thermomodel_None:generating thermo variables for q8_c
DEBUG:thermomodel_None:Added variable: LC_q8_c
DEBUG:thermomodel_None:generating thermo variables for q8h2_c
DEBUG:thermomodel_None:Added variable: LC_q8h2_c
DEBUG:thermomodel_None:generating thermo variables for r5p_c
DEBUG:thermomodel_None:Added variable: LC_r5p_c
DEBUG:thermomodel_None:generating thermo variables for ru5p__D_c
DEBUG:thermomodel_None:Added variable: LC_ru5p__D_c
DEBUG:thermomodel_None:generating thermo variables for s7p_c
DEBUG:thermomodel_None:Added variable: LC_s7p_c
DEBUG:thermomodel_None:generating thermo variables for succ_c
DEBUG:thermomodel_None:Added variable: LC_succ_c
DEBUG:thermomodel_None:generating thermo variables for succ_e
DEBUG:thermomodel_None:Added variable: LC_succ_e
DEBUG:thermomodel_None:generating thermo variables for succoa_c
DEBUG:thermomodel_None:Added variable: LC_succoa_c
DEBUG:thermomodel_None:generating thermo variables for xu5p__D_c
DEBUG:thermomodel_None:Added variable: LC_xu5p__D_c
DEBUG:thermomodel_None:generating only use constraints for reactionACALD
DEBUG:thermomodel_None:Added variable: FU_ACALD
DEBUG:thermomodel_None:Added variable: BU_ACALD
DEBUG:thermomodel_None:Added constraint: SU_ACALD
DEBUG:thermomodel_None:Added constraint: UF_ACALD
DEBUG:thermomodel_None:Added constraint: UR_ACALD
DEBUG:thermomodel_None:generating only use constraints for reactionACALDt
DEBUG:thermomodel_None:Added variable: FU_ACALDt
DEBUG:thermomodel_None:Added variable: BU_ACALDt
DEBUG:thermomodel_None:Added constraint: SU_ACALDt
DEBUG:thermomodel_None:Added constraint: UF_ACALDt
DEBUG:thermomodel_None:Added constraint: UR_ACALDt
DEBUG:thermomodel_None:generating only use constraints for reactionACKr
DEBUG:thermomodel_None:Added variable: FU_ACKr

## Run model with coreected IDs

In [ ]:
sol = tmodel.optimize()
print("Thermo-FBA objective:", sol.objective_value)

DEBUG:thermomodel_None:'slim_optimize' ((), {}) 0.05 sec

Thermo-FBA objective: 0.8739215069684306

## Check fluxes

In [ ]:
# Top 10 reactions with largest flux
top_fluxes = sol.fluxes.abs().sort_values(ascending=False).head(10)
print(top_fluxes)

ATPS4r      45.514010
CYTBD       43.598985
NADH16      38.534610
EX_h2o_e    29.175827
H2Ot        29.175827
EX_co2_e    22.809833
CO2t        22.809833
EX_o2_e     21.799493
O2t         21.799493
EX_h_e      17.530865
Name: fluxes, dtype: float64

In [ ]:
# Look at key pathways
pathway_rxns = ['PGK', 'PYK', 'PDH', 'CS']
for rxn_id in pathway_rxns:
    print(rxn_id, sol.fluxes.get(rxn_id, "not in solution"))

PGK -16.023526143167604
PYK 1.7581774441067848
PDH 9.282532599166615
CS 6.00724957535033